use super::{
    final_executable_verify_helpers::{non_empty_toml_string, optional_usize_value},
    toml,
};

#[derive(Default)]
pub(crate) struct NsldFinalExecutableEmitActual {
    pub(crate) final_stage_plan_hash: Option<String>,
    pub(crate) emitted: Option<bool>,
    pub(crate) writer_input_valid: Option<bool>,
    pub(crate) writer_input_hash: Option<String>,
    pub(crate) writer_input_issues: Vec<String>,
    pub(crate) host_dry_run_environment_ready: Option<bool>,
    pub(crate) host_dry_run_driver_available: Option<bool>,
    pub(crate) host_dry_run_can_invoke: Option<bool>,
    pub(crate) host_dry_run_driver_resolved_path: Option<String>,
    pub(crate) host_dry_run_invocation_policy: Option<String>,
    pub(crate) host_dry_run_invocation_policy_reason: Option<String>,
    pub(crate) host_dry_run_command_arg_count: Option<usize>,
    pub(crate) host_dry_run_command_args: Vec<String>,
    pub(crate) host_dry_run_blocker_count: Option<usize>,
    pub(crate) host_dry_run_blockers: Vec<String>,
    pub(crate) host_invoke_plan_valid: Option<bool>,
    pub(crate) host_invoke_plan_would_invoke: Option<bool>,
    pub(crate) host_invoke_plan_hash: Option<String>,
    pub(crate) host_invoke_plan_invocation_policy: Option<String>,
    pub(crate) host_invoke_plan_requires_explicit_allow: Option<bool>,
    pub(crate) host_invoke_plan_explicit_allow_present: Option<bool>,
    pub(crate) host_invoke_plan_blocker_count: Option<usize>,
    pub(crate) host_invoke_plan_issues: Vec<String>,
    pub(crate) host_finalizer_gate_status: Option<String>,
    pub(crate) host_finalizer_gate_action: Option<String>,
    pub(crate) layout_plan_valid: Option<bool>,
    pub(crate) layout_plan_hash: Option<String>,
    pub(crate) layout_plan_issues: Vec<String>,
    pub(crate) image_dry_run_valid: Option<bool>,
    pub(crate) image_dry_run_hash: Option<String>,
    pub(crate) image_dry_run_size_bytes: Option<usize>,
    pub(crate) image_dry_run_issues: Vec<String>,
    pub(crate) final_output_checked: Option<bool>,
    pub(crate) final_output_present: Option<bool>,
    pub(crate) final_output_size_bytes: Option<usize>,
    pub(crate) final_output_hash: Option<String>,
    pub(crate) final_output_image_header_valid: Option<bool>,
    pub(crate) final_output_runnable_candidate: Option<bool>,
    pub(crate) blocker_count: Option<usize>,
    pub(crate) blockers: Vec<String>,
}

pub(crate) fn nsld_final_executable_emit_actual_from_source(
    source: &str,
) -> NsldFinalExecutableEmitActual {
    NsldFinalExecutableEmitActual {
        final_stage_plan_hash: toml::string_value(source, "final_stage_plan_hash"),
        emitted: toml::bool_value(source, "emitted"),
        writer_input_valid: toml::bool_value(source, "writer_input_valid"),
        writer_input_hash: non_empty_toml_string(source, "writer_input_hash"),
        writer_input_issues: toml::string_array_value(source, "writer_input_issues"),
        host_dry_run_environment_ready: toml::bool_value(source, "host_dry_run_environment_ready"),
        host_dry_run_driver_available: toml::bool_value(source, "host_dry_run_driver_available"),
        host_dry_run_can_invoke: toml::bool_value(source, "host_dry_run_can_invoke"),
        host_dry_run_driver_resolved_path: non_empty_toml_string(
            source,
            "host_dry_run_driver_resolved_path",
        ),
        host_dry_run_invocation_policy: non_empty_toml_string(
            source,
            "host_dry_run_invocation_policy",
        ),
        host_dry_run_invocation_policy_reason: non_empty_toml_string(
            source,
            "host_dry_run_invocation_policy_reason",
        ),
        host_dry_run_command_arg_count: toml::usize_value(source, "host_dry_run_command_arg_count"),
        host_dry_run_command_args: toml::string_array_value(source, "host_dry_run_command_args"),
        host_dry_run_blocker_count: toml::usize_value(source, "host_dry_run_blocker_count"),
        host_dry_run_blockers: toml::string_array_value(source, "host_dry_run_blockers"),
        host_invoke_plan_valid: toml::bool_value(source, "host_invoke_plan_valid"),
        host_invoke_plan_would_invoke: toml::bool_value(source, "host_invoke_plan_would_invoke"),
        host_invoke_plan_hash: non_empty_toml_string(source, "host_invoke_plan_hash"),
        host_invoke_plan_invocation_policy: non_empty_toml_string(
            source,
            "host_invoke_plan_invocation_policy",
        ),
        host_invoke_plan_requires_explicit_allow: toml::bool_value(
            source,
            "host_invoke_plan_requires_explicit_allow",
        ),
        host_invoke_plan_explicit_allow_present: toml::bool_value(
            source,
            "host_invoke_plan_explicit_allow_present",
        ),
        host_invoke_plan_blocker_count: toml::usize_value(source, "host_invoke_plan_blocker_count"),
        host_invoke_plan_issues: toml::string_array_value(source, "host_invoke_plan_issues"),
        host_finalizer_gate_status: non_empty_toml_string(source, "host_finalizer_gate_status"),
        host_finalizer_gate_action: non_empty_toml_string(source, "host_finalizer_gate_action"),
        layout_plan_valid: toml::bool_value(source, "layout_plan_valid"),
        layout_plan_hash: non_empty_toml_string(source, "layout_plan_hash"),
        layout_plan_issues: toml::string_array_value(source, "layout_plan_issues"),
        image_dry_run_valid: toml::bool_value(source, "image_dry_run_valid"),
        image_dry_run_hash: non_empty_toml_string(source, "image_dry_run_hash"),
        image_dry_run_size_bytes: optional_usize_value(source, "image_dry_run_size_bytes"),
        image_dry_run_issues: toml::string_array_value(source, "image_dry_run_issues"),
        final_output_checked: toml::bool_value(source, "final_output_checked"),
        final_output_present: toml::bool_value(source, "final_output_present"),
        final_output_size_bytes: optional_usize_value(source, "final_output_size_bytes"),
        final_output_hash: non_empty_toml_string(source, "final_output_hash"),
        final_output_image_header_valid: toml::bool_value(
            source,
            "final_output_image_header_valid",
        ),
        final_output_runnable_candidate: toml::bool_value(
            source,
            "final_output_runnable_candidate",
        ),
        blocker_count: toml::usize_value(source, "blocker_count"),
        blockers: toml::string_array_value(source, "blockers"),
    }
}
