use super::{fnv1a64_hex, reports::NsldFinalExecutableLauncherManifestReport};
use std::{fs, path::Path};
#[cfg(unix)]
use std::{fs::Permissions, os::unix::fs::PermissionsExt};

const HOST_ENTRYPOINT_STUB_PROTOCOL: &str = "nuis-nsld-host-entrypoint-v1";

pub(crate) struct NsldPipelineEntrypointMaterializationPlan {
    pub(crate) kind: String,
    pub(crate) path: Option<String>,
    pub(crate) ready: bool,
    pub(crate) first_blocker: Option<String>,
}

pub(crate) fn nsld_pipeline_entrypoint_materialization_status(
    self_owned_image_status: &str,
    launcher_dry_run_ready: bool,
    would_enter_lifecycle_hook: bool,
) -> &'static str {
    if launcher_dry_run_ready && would_enter_lifecycle_hook {
        return "host-launcher-ready";
    }
    if self_owned_image_status == "ready" {
        return "image-ready-entrypoint-pending";
    }
    "blocked"
}

pub(crate) fn nsld_pipeline_entrypoint_materialization_plan(
    plan: &nuisc::linker::LinkPlan,
    status: &str,
    execution_handoff_ready: bool,
    execution_handoff_target: &str,
    execution_handoff_first_blocker: Option<&str>,
    blockers: &[String],
) -> NsldPipelineEntrypointMaterializationPlan {
    let handoff_target_can_enter_host_entrypoint = matches!(
        execution_handoff_target,
        "entrypoint-materializer" | "container-loader"
    );
    let ready = status == "host-launcher-ready"
        && execution_handoff_ready
        && handoff_target_can_enter_host_entrypoint;
    let path = if ready {
        Some(
            Path::new(&plan.output_dir)
                .join("nuis.host-entrypoint.sh")
                .display()
                .to_string(),
        )
    } else {
        None
    };
    let first_blocker = if ready {
        None
    } else {
        execution_handoff_first_blocker
            .map(str::to_owned)
            .or_else(|| blockers.first().cloned())
            .or_else(|| Some(format!("entrypoint-materialization:{status}")))
    };
    NsldPipelineEntrypointMaterializationPlan {
        kind: if ready {
            "host-shell-entrypoint-plan".to_owned()
        } else {
            "none".to_owned()
        },
        path,
        ready,
        first_blocker,
    }
}

pub(crate) fn nsld_write_host_entrypoint_script(
    manifest: &Path,
    plan: &nuisc::linker::LinkPlan,
    launcher: &NsldFinalExecutableLauncherManifestReport,
    entrypoint: &NsldPipelineEntrypointMaterializationPlan,
) -> Result<(), String> {
    let Some(path) = entrypoint.path.as_deref() else {
        return Ok(());
    };
    let source = render_host_entrypoint_script(manifest, plan, launcher);
    fs::write(path, source).map_err(|error| format!("{}:{error}", path))?;
    #[cfg(unix)]
    fs::set_permissions(path, Permissions::from_mode(0o755))
        .map_err(|error| format!("{}:{error}", path))?;
    Ok(())
}

pub(crate) fn entrypoint_materialization_evidence(
    path: Option<&str>,
) -> (Option<bool>, Option<String>) {
    let Some(path) = path else {
        return (Some(false), None);
    };
    match fs::read(path) {
        Ok(bytes) => (Some(true), Some(fnv1a64_hex(&bytes))),
        Err(_) => (Some(false), None),
    }
}

pub(crate) fn render_host_entrypoint_runner_command(
    manifest: &Path,
    plan: &nuisc::linker::LinkPlan,
    launcher: &NsldFinalExecutableLauncherManifestReport,
) -> String {
    render_host_entrypoint_runner_command_parts(
        manifest,
        &plan.output_dir,
        &launcher.nsb_path,
        &launcher.scheduler_entry,
        &launcher.entry_lifecycle_hook,
    )
}

pub(crate) fn render_host_entrypoint_runner_command_parts(
    manifest: &Path,
    output_dir: &str,
    nsb_path: &str,
    scheduler_entry: &str,
    lifecycle_hook: &str,
) -> String {
    format!(
        "nuis-host-runner --manifest {} --nsb {} --output-dir {} --scheduler-entry {} --lifecycle-hook {}",
        shell_single_quote(&manifest.display().to_string()),
        shell_single_quote(nsb_path),
        shell_single_quote(output_dir),
        shell_single_quote(scheduler_entry),
        shell_single_quote(lifecycle_hook)
    )
}

fn render_host_entrypoint_script(
    manifest: &Path,
    plan: &nuisc::linker::LinkPlan,
    launcher: &NsldFinalExecutableLauncherManifestReport,
) -> String {
    let protocol = shell_single_quote(HOST_ENTRYPOINT_STUB_PROTOCOL);
    let manifest_path = shell_single_quote(&manifest.display().to_string());
    let nsb_path = shell_single_quote(&launcher.nsb_path);
    let output_dir = shell_single_quote(&plan.output_dir);
    let scheduler_entry = shell_single_quote(&launcher.scheduler_entry);
    let lifecycle_hook = shell_single_quote(&launcher.entry_lifecycle_hook);
    format!(
        "#!/bin/sh\n\
set -eu\n\
# Generated by nsld. This is a host-shell entrypoint handoff stub.\n\
# It delegates execution to the host runner without embedding runner logic in nsld.\n\
NUIS_HOST_ENTRYPOINT_STUB_PROTOCOL={protocol}\n\
MANIFEST_PATH={manifest_path}\n\
NSB_PATH={nsb_path}\n\
NUIS_OUTPUT_DIR={output_dir}\n\
SCHEDULER_ENTRY={scheduler_entry}\n\
LIFECYCLE_HOOK={lifecycle_hook}\n\
export NUIS_HOST_ENTRYPOINT_STUB_PROTOCOL\n\
: \"${{NUIS_HOST_RUNNER:=nuis-host-runner}}\"\n\
exec \"$NUIS_HOST_RUNNER\" \\\n\
  --manifest \"$MANIFEST_PATH\" \\\n\
  --nsb \"$NSB_PATH\" \\\n\
  --output-dir \"$NUIS_OUTPUT_DIR\" \\\n\
  --scheduler-entry \"$SCHEDULER_ENTRY\" \\\n\
  --lifecycle-hook \"$LIFECYCLE_HOOK\"\n"
    )
}

fn shell_single_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\\''"))
}
