use super::{json_fields::*, json_fragments::*, json_object_image::*, reports::NsldCheckReport};

pub(crate) fn check_report_object_fields(report: &NsldCheckReport) -> Vec<String> {
    vec![
        json_bool_field("object_plan_present", report.object_plan_present),
        json_optional_bool_field("object_plan_valid", report.object_plan_valid),
        json_string_array_field("object_plan_issues", &report.object_plan_issues),
        json_bool_field(
            "object_writer_input_present",
            report.object_writer_input_present,
        ),
        json_optional_bool_field(
            "object_writer_input_valid",
            report.object_writer_input_valid,
        ),
        json_string_array_field(
            "object_writer_input_issues",
            &report.object_writer_input_issues,
        ),
        json_bool_field(
            "object_byte_layout_present",
            report.object_byte_layout_present,
        ),
        json_optional_bool_field("object_byte_layout_valid", report.object_byte_layout_valid),
        json_string_array_field(
            "object_byte_layout_issues",
            &report.object_byte_layout_issues,
        ),
        json_bool_field(
            "object_file_layout_present",
            report.object_file_layout_present,
        ),
        json_optional_bool_field("object_file_layout_valid", report.object_file_layout_valid),
        json_string_array_field(
            "object_file_layout_issues",
            &report.object_file_layout_issues,
        ),
        json_bool_field(
            "object_image_dry_run_present",
            report.object_image_dry_run_present,
        ),
        json_optional_bool_field(
            "object_image_dry_run_valid",
            report.object_image_dry_run_valid,
        ),
        json_string_array_field(
            "object_image_dry_run_issues",
            &report.object_image_dry_run_issues,
        ),
        json_optional_bool_field(
            "object_image_relocation_lowering_valid",
            report.object_image_relocation_lowering_valid,
        ),
        json_optional_usize_field(
            "object_image_relocation_lowering_rule_count",
            report.object_image_relocation_lowering_rule_count,
        ),
        format!(
            "\"object_image_relocation_lowering_rules\":[{}]",
            relocation_lowering_rules_json(&report.object_image_relocation_lowering_rules)
        ),
        json_string_array_field(
            "object_image_relocation_lowering_issues",
            &report.object_image_relocation_lowering_issues,
        ),
        json_optional_usize_field(
            "object_image_relocation_record_count",
            report.object_image_relocation_record_count,
        ),
        json_optional_string_field(
            "object_image_relocation_record_table_hash",
            report.object_image_relocation_record_table_hash.as_deref(),
        ),
        format!(
            "\"object_image_relocation_records\":[{}]",
            relocation_records_json(&report.object_image_relocation_records)
        ),
        json_bool_field(
            "object_image_dry_run_bytes_present",
            report.object_image_dry_run_bytes_present,
        ),
        json_bool_field(
            "object_emit_blocked_present",
            report.object_emit_blocked_present,
        ),
        json_optional_bool_field(
            "object_emit_blocked_valid",
            report.object_emit_blocked_valid,
        ),
        json_string_array_field(
            "object_emit_blocked_issues",
            &report.object_emit_blocked_issues,
        ),
        json_bool_field("object_output_present", report.object_output_present),
        json_optional_bool_field("object_output_valid", report.object_output_valid),
        json_optional_usize_field(
            "object_output_expected_size_bytes",
            report.object_output_expected_size_bytes,
        ),
        json_optional_usize_field(
            "object_output_actual_size_bytes",
            report.object_output_actual_size_bytes,
        ),
        json_optional_string_field(
            "object_output_expected_hash",
            report.object_output_expected_hash.as_deref(),
        ),
        json_optional_string_field(
            "object_output_actual_hash",
            report.object_output_actual_hash.as_deref(),
        ),
        json_string_array_field("object_output_issues", &report.object_output_issues),
        json_bool_field(
            "object_writer_dry_run_present",
            report.object_writer_dry_run_present,
        ),
        json_optional_bool_field(
            "object_writer_dry_run_valid",
            report.object_writer_dry_run_valid,
        ),
        json_string_array_field(
            "object_writer_dry_run_issues",
            &report.object_writer_dry_run_issues,
        ),
    ]
}

pub(crate) fn check_report_container_fields(report: &NsldCheckReport) -> Vec<String> {
    vec![
        json_bool_field("container_plan_present", report.container_plan_present),
        json_optional_bool_field("container_plan_valid", report.container_plan_valid),
        json_string_array_field("container_plan_issues", &report.container_plan_issues),
        json_bool_field("container_present", report.container_present),
        json_optional_bool_field("container_valid", report.container_valid),
        json_string_array_field("container_issues", &report.container_issues),
        json_string_array_field("container_section_issues", &report.container_section_issues),
        json_string_array_field(
            "container_loader_symbol_issues",
            &report.container_loader_symbol_issues,
        ),
        json_string_array_field(
            "container_relocation_issues",
            &report.container_relocation_issues,
        ),
        json_string_array_field(
            "container_compatibility_domain_issues",
            &report.container_compatibility_domain_issues,
        ),
        json_string_array_field(
            "container_external_import_issues",
            &report.container_external_import_issues,
        ),
        json_bool_field(
            "container_payload_present",
            report.container_payload_present,
        ),
        json_string_array_field("container_payload_issues", &report.container_payload_issues),
        json_bool_field("closure_snapshot_present", report.closure_snapshot_present),
        json_optional_bool_field("closure_snapshot_valid", report.closure_snapshot_valid),
        json_string_array_field("closure_snapshot_issues", &report.closure_snapshot_issues),
        json_optional_string_field(
            "closure_snapshot_linker_contract_hash",
            report.closure_snapshot_linker_contract_hash.as_deref(),
        ),
        json_optional_string_field(
            "closure_snapshot_container_hash",
            report.closure_snapshot_container_hash.as_deref(),
        ),
        json_optional_usize_field(
            "closure_snapshot_payload_size_bytes",
            report.closure_snapshot_payload_size_bytes,
        ),
        json_optional_string_field(
            "closure_snapshot_payload_hash",
            report.closure_snapshot_payload_hash.as_deref(),
        ),
    ]
}

pub(crate) fn check_report_tail_fields(report: &NsldCheckReport) -> Vec<String> {
    vec![
        json_optional_string_field(
            "container_loader_readiness",
            report.container_loader_readiness.as_deref(),
        ),
        json_string_array_field(
            "container_loader_blockers",
            &report.container_loader_blockers,
        ),
        json_optional_string_field(
            "container_metadata_table_hash",
            report.container_metadata_table_hash.as_deref(),
        ),
        json_optional_usize_field(
            "container_compatibility_domain_count",
            report.container_compatibility_domain_count,
        ),
        json_optional_string_field(
            "container_compatibility_domain_table_hash",
            report.container_compatibility_domain_table_hash.as_deref(),
        ),
        json_optional_string_field(
            "container_compatibility_domain_id",
            report.container_compatibility_domain_id.as_deref(),
        ),
        json_optional_string_field(
            "container_compatibility_domain_kind",
            report.container_compatibility_domain_kind.as_deref(),
        ),
        json_optional_string_field(
            "container_compatibility_domain_paradigm",
            report.container_compatibility_domain_paradigm.as_deref(),
        ),
        json_optional_string_field(
            "container_compatibility_domain_lifecycle_hook",
            report
                .container_compatibility_domain_lifecycle_hook
                .as_deref(),
        ),
        json_optional_string_field(
            "container_compatibility_domain_abi_family",
            report.container_compatibility_domain_abi_family.as_deref(),
        ),
        json_optional_string_field(
            "container_compatibility_domain_wrapper_policy",
            report
                .container_compatibility_domain_wrapper_policy
                .as_deref(),
        ),
        json_optional_bool_field(
            "container_compatibility_domain_required",
            report.container_compatibility_domain_required,
        ),
        format!(
            "\"container_compatibility_domain_summary\":{}",
            compatibility_domain_summary_json(
                report.container_compatibility_domain_count,
                report.container_compatibility_domain_table_hash.as_deref(),
                report.container_compatibility_domain_id.as_deref(),
                report.container_compatibility_domain_kind.as_deref(),
                report.container_compatibility_domain_paradigm.as_deref(),
                report
                    .container_compatibility_domain_lifecycle_hook
                    .as_deref(),
                report.container_compatibility_domain_abi_family.as_deref(),
                report
                    .container_compatibility_domain_wrapper_policy
                    .as_deref(),
                report.container_compatibility_domain_required,
            )
        ),
        json_optional_usize_field(
            "container_external_import_count",
            report.container_external_import_count,
        ),
        json_bool_field(
            "container_native_object_section_present",
            report.container_native_object_section_present,
        ),
        json_optional_string_field(
            "container_native_object_section_id",
            report.container_native_object_section_id.as_deref(),
        ),
        json_bool_field(
            "container_native_object_loader_symbol_present",
            report.container_native_object_loader_symbol_present,
        ),
        json_optional_string_field(
            "container_native_object_loader_symbol_id",
            report.container_native_object_loader_symbol_id.as_deref(),
        ),
        json_bool_field(
            "container_native_object_relocation_present",
            report.container_native_object_relocation_present,
        ),
        json_optional_string_field(
            "container_native_object_relocation_id",
            report.container_native_object_relocation_id.as_deref(),
        ),
        json_bool_field(
            "container_shader_section_present",
            report.container_shader_section_present,
        ),
        json_optional_string_field(
            "container_shader_section_id",
            report.container_shader_section_id.as_deref(),
        ),
        json_bool_field(
            "container_shader_loader_symbol_present",
            report.container_shader_loader_symbol_present,
        ),
        json_optional_string_field(
            "container_shader_loader_symbol_id",
            report.container_shader_loader_symbol_id.as_deref(),
        ),
        json_bool_field(
            "container_shader_relocation_present",
            report.container_shader_relocation_present,
        ),
        json_optional_string_field(
            "container_shader_relocation_id",
            report.container_shader_relocation_id.as_deref(),
        ),
        json_bool_field(
            "container_kernel_section_present",
            report.container_kernel_section_present,
        ),
        json_optional_string_field(
            "container_kernel_section_id",
            report.container_kernel_section_id.as_deref(),
        ),
        json_bool_field(
            "container_kernel_loader_symbol_present",
            report.container_kernel_loader_symbol_present,
        ),
        json_optional_string_field(
            "container_kernel_loader_symbol_id",
            report.container_kernel_loader_symbol_id.as_deref(),
        ),
        json_bool_field(
            "container_kernel_relocation_present",
            report.container_kernel_relocation_present,
        ),
        json_optional_string_field(
            "container_kernel_relocation_id",
            report.container_kernel_relocation_id.as_deref(),
        ),
        json_bool_field("artifact_chain_valid", report.artifact_chain_valid),
        json_string_array_field(
            "artifact_chain_advisories",
            &report.artifact_chain_advisories,
        ),
        json_optional_string_field(
            "artifact_chain_advisory_command_id",
            report.artifact_chain_advisory_command_id.as_deref(),
        ),
        json_optional_string_field(
            "artifact_chain_advisory_command",
            report.artifact_chain_advisory_command.as_deref(),
        ),
        json_optional_string_field(
            "artifact_chain_advisory_command_resolved",
            report.artifact_chain_advisory_command_resolved.as_deref(),
        ),
        json_optional_string_field(
            "artifact_chain_advisory_command_reason",
            report.artifact_chain_advisory_command_reason.as_deref(),
        ),
        json_optional_string_field(
            "artifact_chain_next_action_command_id",
            report.artifact_chain_next_action_command_id.as_deref(),
        ),
        json_optional_string_field(
            "artifact_chain_next_action_command",
            report.artifact_chain_next_action_command.as_deref(),
        ),
        json_optional_string_field(
            "artifact_chain_next_action_command_resolved",
            report
                .artifact_chain_next_action_command_resolved
                .as_deref(),
        ),
        json_optional_string_field(
            "artifact_chain_next_action_command_reason",
            report.artifact_chain_next_action_command_reason.as_deref(),
        ),
        json_optional_string_field(
            "artifact_chain_next_action_source",
            report.artifact_chain_next_action_source.as_deref(),
        ),
        json_bool_field(
            "artifact_chain_next_action_available",
            report.artifact_chain_next_action_available,
        ),
        json_bool_field(
            "artifact_chain_final_output_boundary_ready",
            report.artifact_chain_final_output_boundary_ready,
        ),
        json_optional_string_field(
            "artifact_chain_final_output_boundary_command_id",
            report
                .artifact_chain_final_output_boundary_command_id
                .as_deref(),
        ),
        json_optional_string_field(
            "artifact_chain_final_output_boundary_command",
            report
                .artifact_chain_final_output_boundary_command
                .as_deref(),
        ),
        json_optional_string_field(
            "artifact_chain_final_output_boundary_command_resolved",
            report
                .artifact_chain_final_output_boundary_command_resolved
                .as_deref(),
        ),
        json_optional_string_field(
            "artifact_chain_final_output_boundary_reason",
            report
                .artifact_chain_final_output_boundary_reason
                .as_deref(),
        ),
        json_string_array_field(
            "artifact_chain_final_output_boundary_blockers",
            &report.artifact_chain_final_output_boundary_blockers,
        ),
        json_string_array_field("artifact_chain_issues", &report.artifact_chain_issues),
        json_string_field("final_stage_link_mode", &report.final_stage_link_mode),
        format!("\"domains\":[{}]", domains_json(&report.domains)),
        format!(
            "\"sidecar_capabilities\":[{}]",
            sidecar_capabilities_json(&report.sidecar_capabilities)
        ),
        format!(
            "\"clock_edges\":[{}]",
            clock_edges_json(&report.clock_edges)
        ),
        format!(
            "\"data_segments\":[{}]",
            data_segments_json(&report.data_segments)
        ),
        json_string_array_field("issues", &report.issues),
    ]
}
