use super::{json_fields::*, reports::NsldCheckReport};

pub(crate) fn check_report_final_fields(report: &NsldCheckReport) -> Vec<String> {
    vec![
        json_bool_field("final_stage_plan_present", report.final_stage_plan_present),
        json_optional_bool_field("final_stage_plan_valid", report.final_stage_plan_valid),
        json_optional_bool_field("final_stage_plan_ready", report.final_stage_plan_ready),
        json_optional_string_field(
            "final_stage_plan_hash",
            report.final_stage_plan_hash.as_deref(),
        ),
        json_optional_usize_field(
            "final_stage_plan_blocker_count",
            report.final_stage_plan_blocker_count,
        ),
        json_string_array_field("final_stage_plan_issues", &report.final_stage_plan_issues),
        json_bool_field(
            "final_executable_writer_input_present",
            report.final_executable_writer_input_present,
        ),
        json_optional_bool_field(
            "final_executable_writer_input_valid",
            report.final_executable_writer_input_valid,
        ),
        json_optional_string_field(
            "final_executable_writer_input_hash",
            report.final_executable_writer_input_hash.as_deref(),
        ),
        json_optional_usize_field(
            "final_executable_writer_input_command_arg_count",
            report.final_executable_writer_input_command_arg_count,
        ),
        json_string_array_field(
            "final_executable_writer_input_issues",
            &report.final_executable_writer_input_issues,
        ),
        json_bool_field(
            "final_executable_host_invoke_plan_present",
            report.final_executable_host_invoke_plan_present,
        ),
        json_optional_bool_field(
            "final_executable_host_invoke_plan_valid",
            report.final_executable_host_invoke_plan_valid,
        ),
        json_optional_string_field(
            "final_executable_host_invoke_plan_hash",
            report.final_executable_host_invoke_plan_hash.as_deref(),
        ),
        json_optional_string_field(
            "final_executable_host_invoke_plan_invocation_policy",
            report
                .final_executable_host_invoke_plan_invocation_policy
                .as_deref(),
        ),
        json_optional_bool_field(
            "final_executable_host_invoke_plan_requires_explicit_allow",
            report.final_executable_host_invoke_plan_requires_explicit_allow,
        ),
        json_optional_bool_field(
            "final_executable_host_invoke_plan_explicit_allow_present",
            report.final_executable_host_invoke_plan_explicit_allow_present,
        ),
        json_optional_bool_field(
            "final_executable_host_invoke_plan_would_invoke",
            report.final_executable_host_invoke_plan_would_invoke,
        ),
        json_optional_usize_field(
            "final_executable_host_invoke_plan_blocker_count",
            report.final_executable_host_invoke_plan_blocker_count,
        ),
        json_string_array_field(
            "final_executable_host_invoke_plan_issues",
            &report.final_executable_host_invoke_plan_issues,
        ),
        json_bool_field(
            "final_executable_layout_plan_present",
            report.final_executable_layout_plan_present,
        ),
        json_optional_bool_field(
            "final_executable_layout_plan_valid",
            report.final_executable_layout_plan_valid,
        ),
        json_optional_string_field(
            "final_executable_layout_plan_hash",
            report.final_executable_layout_plan_hash.as_deref(),
        ),
        json_optional_usize_field(
            "final_executable_layout_plan_payload_count",
            report.final_executable_layout_plan_payload_count,
        ),
        json_string_array_field(
            "final_executable_layout_plan_issues",
            &report.final_executable_layout_plan_issues,
        ),
        json_bool_field(
            "final_executable_image_dry_run_present",
            report.final_executable_image_dry_run_present,
        ),
        json_optional_bool_field(
            "final_executable_image_dry_run_valid",
            report.final_executable_image_dry_run_valid,
        ),
        json_optional_string_field(
            "final_executable_image_dry_run_hash",
            report.final_executable_image_dry_run_hash.as_deref(),
        ),
        json_optional_usize_field(
            "final_executable_image_dry_run_size_bytes",
            report.final_executable_image_dry_run_size_bytes,
        ),
        json_string_array_field(
            "final_executable_image_dry_run_issues",
            &report.final_executable_image_dry_run_issues,
        ),
        json_bool_field(
            "final_executable_blocked_present",
            report.final_executable_blocked_present,
        ),
        json_optional_bool_field(
            "final_executable_blocked_valid",
            report.final_executable_blocked_valid,
        ),
        json_optional_bool_field(
            "final_executable_blocked_emitted",
            report.final_executable_blocked_emitted,
        ),
        json_optional_string_field(
            "final_executable_blocked_plan_hash",
            report.final_executable_blocked_plan_hash.as_deref(),
        ),
        json_optional_usize_field(
            "final_executable_blocked_blocker_count",
            report.final_executable_blocked_blocker_count,
        ),
        json_string_array_field(
            "final_executable_blocked_issues",
            &report.final_executable_blocked_issues,
        ),
        json_bool_field(
            "final_executable_output_path_present",
            report.final_executable_output_path_present,
        ),
        json_string_field(
            "final_executable_output_kind",
            &report.final_executable_output_kind,
        ),
        json_string_field(
            "final_executable_output_validation_mode",
            &report.final_executable_output_validation_mode,
        ),
        json_bool_field(
            "final_executable_output_nsld_owned",
            report.final_executable_output_nsld_owned,
        ),
        json_bool_field(
            "final_executable_output_present",
            report.final_executable_output_present,
        ),
        json_optional_usize_field(
            "final_executable_output_size_bytes",
            report.final_executable_output_size_bytes,
        ),
        json_optional_string_field(
            "final_executable_output_hash",
            report.final_executable_output_hash.as_deref(),
        ),
        json_optional_bool_field(
            "final_executable_output_image_header_valid",
            report.final_executable_output_image_header_valid,
        ),
        json_optional_string_field(
            "final_executable_output_image_magic",
            report.final_executable_output_image_magic.as_deref(),
        ),
        json_optional_usize_field(
            "final_executable_output_image_version",
            report.final_executable_output_image_version,
        ),
        json_optional_string_field(
            "final_executable_output_image_layout_hash",
            report.final_executable_output_image_layout_hash.as_deref(),
        ),
        json_optional_string_field(
            "final_executable_output_image_byte_map_hash",
            report
                .final_executable_output_image_byte_map_hash
                .as_deref(),
        ),
        json_optional_bool_field(
            "final_executable_output_runnable_candidate",
            report.final_executable_output_runnable_candidate,
        ),
        json_optional_usize_field(
            "final_executable_output_blocker_count",
            report.final_executable_output_blocker_count,
        ),
        json_string_array_field(
            "final_executable_output_issues",
            &report.final_executable_output_issues,
        ),
        json_bool_field(
            "final_executable_launcher_manifest_present",
            report.final_executable_launcher_manifest_present,
        ),
        json_optional_bool_field(
            "final_executable_launcher_manifest_valid",
            report.final_executable_launcher_manifest_valid,
        ),
        json_optional_string_field(
            "final_executable_launcher_manifest_hash",
            report.final_executable_launcher_manifest_hash.as_deref(),
        ),
        json_optional_bool_field(
            "final_executable_launcher_manifest_ready",
            report.final_executable_launcher_manifest_ready,
        ),
        json_optional_usize_field(
            "final_executable_launcher_manifest_blocker_count",
            report.final_executable_launcher_manifest_blocker_count,
        ),
        json_string_array_field(
            "final_executable_launcher_manifest_issues",
            &report.final_executable_launcher_manifest_issues,
        ),
        json_bool_field(
            "final_executable_launcher_dry_run_present",
            report.final_executable_launcher_dry_run_present,
        ),
        json_optional_bool_field(
            "final_executable_launcher_dry_run_valid",
            report.final_executable_launcher_dry_run_valid,
        ),
        json_optional_string_field(
            "final_executable_launcher_dry_run_hash",
            report.final_executable_launcher_dry_run_hash.as_deref(),
        ),
        json_optional_bool_field(
            "final_executable_launcher_dry_run_ready",
            report.final_executable_launcher_dry_run_ready,
        ),
        json_optional_bool_field(
            "final_executable_launcher_dry_run_would_enter_lifecycle_hook",
            report.final_executable_launcher_dry_run_would_enter_lifecycle_hook,
        ),
        json_optional_usize_field(
            "final_executable_launcher_dry_run_blocker_count",
            report.final_executable_launcher_dry_run_blocker_count,
        ),
        json_string_array_field(
            "final_executable_launcher_dry_run_issues",
            &report.final_executable_launcher_dry_run_issues,
        ),
        json_bool_field(
            "final_executable_pipeline_present",
            report.final_executable_pipeline_present,
        ),
        json_optional_bool_field(
            "final_executable_pipeline_valid",
            report.final_executable_pipeline_valid,
        ),
        json_optional_string_field(
            "final_executable_pipeline_hash",
            report.final_executable_pipeline_hash.as_deref(),
        ),
        json_optional_bool_field(
            "final_executable_pipeline_ready",
            report.final_executable_pipeline_ready,
        ),
        json_optional_bool_field(
            "final_executable_pipeline_emitted",
            report.final_executable_pipeline_emitted,
        ),
        json_optional_usize_field(
            "final_executable_pipeline_required_stage_path_count",
            report.final_executable_pipeline_required_stage_path_count,
        ),
        json_optional_usize_field(
            "final_executable_pipeline_required_stage_path_present_count",
            report.final_executable_pipeline_required_stage_path_present_count,
        ),
        json_string_array_field(
            "final_executable_pipeline_missing_required_stage_paths",
            &report.final_executable_pipeline_missing_required_stage_paths,
        ),
        json_optional_usize_field(
            "final_executable_pipeline_blocker_count",
            report.final_executable_pipeline_blocker_count,
        ),
        json_string_array_field(
            "final_executable_pipeline_issues",
            &report.final_executable_pipeline_issues,
        ),
    ]
}
