use nuisc::linker::{
    ArtifactLoweringAlignmentSummary, LinkPlan, LinkPlanArtifact, LinkPlanClockProtocol,
    LinkPlanCpuTarget, LinkPlanEnvelope, LinkPlanFinalStage, LinkPlanHeteroCalculate,
    LinkPlanHostFfiFootprint, LinkPlanHostFfiValidationSummary, LinkPlanLifecycle,
};

pub(crate) fn empty_link_plan() -> LinkPlan {
    LinkPlan {
        schema: "nuis-link-plan-v1".to_owned(),
        input: "in".to_owned(),
        output_dir: "out".to_owned(),
        packaging_mode: "executable".to_owned(),
        cpu_target: LinkPlanCpuTarget {
            abi: "nuis".to_owned(),
            machine_arch: "arm64".to_owned(),
            machine_os: "macos".to_owned(),
            object_format: "mach-o".to_owned(),
            calling_abi: "aapcs64".to_owned(),
            clang_target: "arm64-apple-macos".to_owned(),
            cross_compile: false,
        },
        lifecycle: LinkPlanLifecycle {
            bootstrap_entry: "main".to_owned(),
            tick_policy: "single".to_owned(),
            shutdown_policy: "return".to_owned(),
            yalivia_rpc: "none".to_owned(),
            hook_surface: Vec::new(),
            export_surface: Vec::new(),
            runtime_capability_flags: Vec::new(),
        },
        envelope: LinkPlanEnvelope {
            schema: "nuis-artifact-envelope-v1".to_owned(),
            package_count: 0,
            contract_families: Vec::new(),
            domain_families: Vec::new(),
            function_kind: "function".to_owned(),
            graph_kind: "static".to_owned(),
            default_time_mode: "logical".to_owned(),
        },
        compiled_artifact: LinkPlanArtifact {
            path: "out/nuis.compiled.artifact".to_owned(),
            binary_name: "demo".to_owned(),
            binary_path: "out/demo".to_owned(),
            binary_bytes: 0,
            build_manifest_bytes: 0,
            container_kind: Some("compiled-artifact-section-table-v2".to_owned()),
            container_version: Some(2),
            section_count: Some(0),
            section_names: Vec::new(),
            section_table_valid: Some(true),
            lowering_unit_count: Some(0),
            lowering_domain_families: Vec::new(),
            lowering_targets: Vec::new(),
            lowering_units: Vec::new(),
        },
        bridge_registry_path: None,
        host_bridge_plan_index_path: None,
        lowering_plan_index_path: None,
        lowering_plan_index_source: "unavailable".to_owned(),
        host_ffi: LinkPlanHostFfiFootprint {
            index_path: None,
            symbol_count: 0,
            policy_count: 0,
            policy: "signature-whitelist-required".to_owned(),
            abi_groups: Vec::new(),
            entries: Vec::new(),
            validation: LinkPlanHostFfiValidationSummary {
                checked: 0,
                valid: true,
                link_allowed: true,
                issues: Vec::new(),
                notes: Vec::new(),
            },
        },
        domain_units: Vec::new(),
        artifact_lowering_alignment: ArtifactLoweringAlignmentSummary {
            checked: 0,
            mismatches: 0,
            consistent: true,
            checks: Vec::new(),
        },
        clock_protocol: LinkPlanClockProtocol {
            schema: "nuis-clock-protocol-v1".to_owned(),
            mode: "static".to_owned(),
            source: "test".to_owned(),
            default_time_mode: "logical".to_owned(),
            lifecycle_tick_policy: "single".to_owned(),
            domains: Vec::new(),
            edges: Vec::new(),
            validation: nuisc::linker::LinkPlanClockValidationSummary {
                checked: 0,
                valid: true,
                issues: Vec::new(),
            },
        },
        hetero_calculate: LinkPlanHeteroCalculate {
            schema: "nuis-hetero-calculate-link-v1".to_owned(),
            mode: "static".to_owned(),
            static_link: true,
            lifecycle_driven: true,
            time_order_model: "partial-order".to_owned(),
            data_order_model: "deterministic".to_owned(),
            c_world_policy: "wrapped".to_owned(),
            nodes: Vec::new(),
            data_segments: Vec::new(),
            validation: nuisc::linker::LinkPlanHeteroValidationSummary {
                checked: 0,
                valid: true,
                issues: Vec::new(),
            },
        },
        final_stage: LinkPlanFinalStage {
            kind: "native-executable".to_owned(),
            driver: "clang".to_owned(),
            link_mode: "host-toolchain-finalize".to_owned(),
            output_path: "out/demo".to_owned(),
            inputs: Vec::new(),
            notes: Vec::new(),
        },
    }
}
