#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct NsldFinalStagePlanReport {
    pub(crate) manifest: String,
    pub(crate) ready: bool,
    pub(crate) plan_hash: String,
    pub(crate) final_stage_kind: String,
    pub(crate) final_stage_driver: String,
    pub(crate) final_stage_link_mode: String,
    pub(crate) final_output_path: String,
    pub(crate) host_wrapper_required: bool,
    pub(crate) compatibility_mode: String,
    pub(crate) input_count: usize,
    pub(crate) inputs: Vec<NsldFinalStageInputDiagnostic>,
    pub(crate) container_hash: String,
    pub(crate) payload_hash: String,
    pub(crate) linker_contract_hash: String,
    pub(crate) native_object_required: bool,
    pub(crate) native_object_present: bool,
    pub(crate) blockers: Vec<String>,
    pub(crate) notes: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct NsldFinalStageInputDiagnostic {
    pub(crate) order_index: usize,
    pub(crate) input_id: String,
    pub(crate) input_kind: String,
    pub(crate) path: String,
    pub(crate) content_hash: String,
    pub(crate) required: bool,
    pub(crate) present: bool,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct NsldFinalStagePlanEmitReport {
    pub(crate) manifest: String,
    pub(crate) output_path: String,
    pub(crate) ready: bool,
    pub(crate) plan_hash: String,
    pub(crate) input_count: usize,
    pub(crate) blocker_count: usize,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct NsldFinalStagePlanVerifyReport {
    pub(crate) manifest: String,
    pub(crate) input_path: String,
    pub(crate) valid: bool,
    pub(crate) expected_plan_hash: String,
    pub(crate) expected_input_count: usize,
    pub(crate) expected_input_ids: Vec<String>,
    pub(crate) actual_input_ids: Vec<String>,
    pub(crate) expected_input_entry_count: usize,
    pub(crate) actual_input_entry_count: usize,
    pub(crate) expected_blockers: Vec<String>,
    pub(crate) actual_blockers: Vec<String>,
    pub(crate) expected_notes: Vec<String>,
    pub(crate) actual_notes: Vec<String>,
    pub(crate) actual_plan_hash: Option<String>,
    pub(crate) actual_input_count: Option<usize>,
    pub(crate) issues: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct NsldFinalExecutableEmitReport {
    pub(crate) manifest: String,
    pub(crate) output_path: String,
    pub(crate) blocked_report_path: String,
    pub(crate) emitted: bool,
    pub(crate) can_emit_final_executable: bool,
    pub(crate) final_stage_ready: bool,
    pub(crate) final_stage_plan_hash: String,
    pub(crate) final_stage_driver: String,
    pub(crate) final_stage_link_mode: String,
    pub(crate) host_wrapper_required: bool,
    pub(crate) writer_kind: String,
    pub(crate) writer_status: String,
    pub(crate) writer_blockers: Vec<String>,
    pub(crate) writer_input_path: String,
    pub(crate) writer_input_valid: Option<bool>,
    pub(crate) writer_input_hash: Option<String>,
    pub(crate) writer_input_issues: Vec<String>,
    pub(crate) host_dry_run_environment_ready: Option<bool>,
    pub(crate) host_dry_run_driver_available: Option<bool>,
    pub(crate) host_dry_run_driver_resolved_path: Option<String>,
    pub(crate) host_dry_run_can_invoke: Option<bool>,
    pub(crate) host_dry_run_invocation_policy: Option<String>,
    pub(crate) host_dry_run_invocation_policy_reason: Option<String>,
    pub(crate) host_dry_run_command_arg_count: usize,
    pub(crate) host_dry_run_command_args: Vec<String>,
    pub(crate) host_dry_run_blocker_count: usize,
    pub(crate) host_dry_run_blockers: Vec<String>,
    pub(crate) host_invoke_plan_path: String,
    pub(crate) host_invoke_plan_valid: Option<bool>,
    pub(crate) host_invoke_plan_hash: Option<String>,
    pub(crate) host_invoke_plan_invocation_policy: Option<String>,
    pub(crate) host_invoke_plan_requires_explicit_allow: Option<bool>,
    pub(crate) host_invoke_plan_explicit_allow_present: Option<bool>,
    pub(crate) host_invoke_plan_would_invoke: Option<bool>,
    pub(crate) host_invoke_plan_blocker_count: Option<usize>,
    pub(crate) host_invoke_plan_issues: Vec<String>,
    pub(crate) layout_plan_path: String,
    pub(crate) layout_plan_valid: Option<bool>,
    pub(crate) layout_plan_hash: Option<String>,
    pub(crate) layout_plan_issues: Vec<String>,
    pub(crate) image_dry_run_path: String,
    pub(crate) image_dry_run_bytes_path: String,
    pub(crate) image_dry_run_valid: Option<bool>,
    pub(crate) image_dry_run_hash: Option<String>,
    pub(crate) image_dry_run_size_bytes: Option<usize>,
    pub(crate) image_dry_run_issues: Vec<String>,
    pub(crate) final_output_checked: bool,
    pub(crate) final_output_present: bool,
    pub(crate) final_output_size_bytes: Option<usize>,
    pub(crate) final_output_hash: Option<String>,
    pub(crate) final_output_image_header_valid: Option<bool>,
    pub(crate) final_output_runnable_candidate: Option<bool>,
    pub(crate) input_count: usize,
    pub(crate) blockers: Vec<String>,
    pub(crate) notes: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct NsldFinalExecutableWriterPlanReport {
    pub(crate) manifest: String,
    pub(crate) output_path: String,
    pub(crate) writer_kind: String,
    pub(crate) writer_status: String,
    pub(crate) final_stage_plan_hash: String,
    pub(crate) final_stage_driver: String,
    pub(crate) final_stage_link_mode: String,
    pub(crate) host_wrapper_required: bool,
    pub(crate) input_count: usize,
    pub(crate) inputs: Vec<NsldFinalStageInputDiagnostic>,
    pub(crate) writer_steps: Vec<String>,
    pub(crate) writer_blockers: Vec<String>,
    pub(crate) notes: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct NsldFinalExecutableWriterInputEmitReport {
    pub(crate) manifest: String,
    pub(crate) output_path: String,
    pub(crate) writer_input_hash: String,
    pub(crate) writer_kind: String,
    pub(crate) writer_status: String,
    pub(crate) final_stage_plan_hash: String,
    pub(crate) final_stage_driver: String,
    pub(crate) final_stage_link_mode: String,
    pub(crate) host_wrapper_required: bool,
    pub(crate) command_arg_count: usize,
    pub(crate) writer_blockers: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct NsldFinalExecutableWriterInputVerifyReport {
    pub(crate) manifest: String,
    pub(crate) input_path: String,
    pub(crate) valid: bool,
    pub(crate) expected_writer_input_hash: String,
    pub(crate) actual_writer_input_hash: Option<String>,
    pub(crate) expected_final_stage_plan_hash: String,
    pub(crate) actual_final_stage_plan_hash: Option<String>,
    pub(crate) expected_writer_kind: String,
    pub(crate) actual_writer_kind: Option<String>,
    pub(crate) expected_writer_status: String,
    pub(crate) actual_writer_status: Option<String>,
    pub(crate) expected_command_arg_count: usize,
    pub(crate) actual_command_arg_count: Option<usize>,
    pub(crate) expected_command_args: Vec<String>,
    pub(crate) actual_command_args: Vec<String>,
    pub(crate) expected_writer_blockers: Vec<String>,
    pub(crate) actual_writer_blockers: Vec<String>,
    pub(crate) issues: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct NsldFinalExecutableHostDryRunReport {
    pub(crate) manifest: String,
    pub(crate) writer_input_path: String,
    pub(crate) writer_input_valid: bool,
    pub(crate) writer_input_hash: Option<String>,
    pub(crate) driver: String,
    pub(crate) driver_available: bool,
    pub(crate) driver_resolved_path: Option<String>,
    pub(crate) command_arg_count: usize,
    pub(crate) command_args: Vec<String>,
    pub(crate) environment_ready: bool,
    pub(crate) invocation_policy: String,
    pub(crate) invocation_policy_reason: String,
    pub(crate) can_invoke_host_finalizer: bool,
    pub(crate) blockers: Vec<String>,
    pub(crate) notes: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct NsldFinalExecutableHostInvokePlanReport {
    pub(crate) manifest: String,
    pub(crate) output_path: String,
    pub(crate) writer_input_path: String,
    pub(crate) invocation_kind: String,
    pub(crate) invocation_policy: String,
    pub(crate) invocation_policy_reason: String,
    pub(crate) requires_explicit_allow: bool,
    pub(crate) explicit_allow_present: bool,
    pub(crate) environment_ready: bool,
    pub(crate) driver_available: bool,
    pub(crate) driver_resolved_path: Option<String>,
    pub(crate) can_invoke_host_finalizer: bool,
    pub(crate) would_invoke: bool,
    pub(crate) command_arg_count: usize,
    pub(crate) command_args: Vec<String>,
    pub(crate) blockers: Vec<String>,
    pub(crate) notes: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct NsldFinalExecutableHostInvokePlanEmitReport {
    pub(crate) manifest: String,
    pub(crate) output_path: String,
    pub(crate) invoke_plan_hash: String,
    pub(crate) invocation_policy: String,
    pub(crate) requires_explicit_allow: bool,
    pub(crate) explicit_allow_present: bool,
    pub(crate) would_invoke: bool,
    pub(crate) blocker_count: usize,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct NsldFinalExecutableHostInvokePlanVerifyReport {
    pub(crate) manifest: String,
    pub(crate) input_path: String,
    pub(crate) valid: bool,
    pub(crate) expected_invoke_plan_hash: String,
    pub(crate) actual_invoke_plan_hash: Option<String>,
    pub(crate) expected_invocation_policy: String,
    pub(crate) actual_invocation_policy: Option<String>,
    pub(crate) expected_requires_explicit_allow: bool,
    pub(crate) actual_requires_explicit_allow: Option<bool>,
    pub(crate) expected_explicit_allow_present: bool,
    pub(crate) actual_explicit_allow_present: Option<bool>,
    pub(crate) expected_would_invoke: bool,
    pub(crate) actual_would_invoke: Option<bool>,
    pub(crate) expected_command_arg_count: usize,
    pub(crate) actual_command_arg_count: Option<usize>,
    pub(crate) expected_command_args: Vec<String>,
    pub(crate) actual_command_args: Vec<String>,
    pub(crate) expected_blocker_count: usize,
    pub(crate) actual_blocker_count: Option<usize>,
    pub(crate) expected_blockers: Vec<String>,
    pub(crate) actual_blockers: Vec<String>,
    pub(crate) issues: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct NsldFinalExecutableLayoutPlanReport {
    pub(crate) manifest: String,
    pub(crate) output_path: String,
    pub(crate) layout_hash: String,
    pub(crate) final_stage_plan_hash: String,
    pub(crate) final_stage_link_mode: String,
    pub(crate) platform_envelope_family: String,
    pub(crate) platform_envelope_policy: String,
    pub(crate) internal_binary_format: String,
    pub(crate) lifecycle_entry_hook: String,
    pub(crate) scheduler_contract: String,
    pub(crate) scheduler_metadata_payload: String,
    pub(crate) scheduler_metadata_lifecycle_hook: String,
    pub(crate) scheduler_hetero_node_count: usize,
    pub(crate) scheduler_wait_event_count: usize,
    pub(crate) scheduler_emit_event_count: usize,
    pub(crate) data_segment_ordering: String,
    pub(crate) native_object_path: String,
    pub(crate) native_object_required: bool,
    pub(crate) native_object_present: bool,
    pub(crate) compatibility_domain: String,
    pub(crate) compatibility_lifecycle_hook: String,
    pub(crate) payload_count: usize,
    pub(crate) payloads: Vec<NsldFinalExecutablePayloadDiagnostic>,
    pub(crate) payload_names: Vec<String>,
    pub(crate) byte_alignment: usize,
    pub(crate) byte_span: usize,
    pub(crate) byte_map_hash: String,
    pub(crate) byte_map_entries: Vec<NsldFinalExecutableByteMapEntry>,
    pub(crate) notes: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct NsldFinalExecutablePayloadDiagnostic {
    pub(crate) order_index: usize,
    pub(crate) payload_id: String,
    pub(crate) payload_kind: String,
    pub(crate) lifecycle_hook: String,
    pub(crate) path: String,
    pub(crate) content_hash: String,
    pub(crate) required: bool,
    pub(crate) present: bool,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct NsldFinalExecutableByteMapEntry {
    pub(crate) order_index: usize,
    pub(crate) payload_id: String,
    pub(crate) payload_kind: String,
    pub(crate) offset: usize,
    pub(crate) size_bytes: usize,
    pub(crate) alignment: usize,
    pub(crate) content_hash: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct NsldFinalExecutableLayoutPlanEmitReport {
    pub(crate) manifest: String,
    pub(crate) output_path: String,
    pub(crate) layout_hash: String,
    pub(crate) final_stage_plan_hash: String,
    pub(crate) payload_count: usize,
    pub(crate) native_object_present: bool,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct NsldFinalExecutableLayoutPlanVerifyReport {
    pub(crate) manifest: String,
    pub(crate) input_path: String,
    pub(crate) valid: bool,
    pub(crate) expected_layout_hash: String,
    pub(crate) actual_layout_hash: Option<String>,
    pub(crate) expected_payload_count: usize,
    pub(crate) actual_payload_count: Option<usize>,
    pub(crate) expected_payloads: Vec<String>,
    pub(crate) actual_payloads: Vec<String>,
    pub(crate) expected_payload_entry_count: usize,
    pub(crate) actual_payload_entry_count: usize,
    pub(crate) expected_byte_map_entry_count: usize,
    pub(crate) actual_byte_map_entry_count: usize,
    pub(crate) expected_byte_span: usize,
    pub(crate) actual_byte_span: Option<usize>,
    pub(crate) expected_byte_map_hash: String,
    pub(crate) actual_byte_map_hash: Option<String>,
    pub(crate) expected_lifecycle_entry_hook: String,
    pub(crate) actual_lifecycle_entry_hook: Option<String>,
    pub(crate) expected_scheduler_hetero_node_count: usize,
    pub(crate) actual_scheduler_hetero_node_count: Option<usize>,
    pub(crate) expected_platform_envelope_family: String,
    pub(crate) actual_platform_envelope_family: Option<String>,
    pub(crate) issues: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct NsldFinalExecutableImageDryRunReport {
    pub(crate) manifest: String,
    pub(crate) output_path: String,
    pub(crate) image_path: String,
    pub(crate) image_format: String,
    pub(crate) image_magic: String,
    pub(crate) image_header_size: usize,
    pub(crate) payload_byte_offset: usize,
    pub(crate) payload_byte_span: usize,
    pub(crate) layout_hash: String,
    pub(crate) byte_map_hash: String,
    pub(crate) payload_count: usize,
    pub(crate) byte_span: usize,
    pub(crate) scheduler_metadata_payload_id: String,
    pub(crate) scheduler_metadata_present: bool,
    pub(crate) scheduler_metadata_offset: Option<usize>,
    pub(crate) scheduler_metadata_hash: Option<String>,
    pub(crate) image_constructed: bool,
    pub(crate) image_ready: bool,
    pub(crate) image_size_bytes: Option<usize>,
    pub(crate) image_hash: Option<String>,
    pub(crate) blockers: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct NsldFinalExecutableImageDryRunEmitReport {
    pub(crate) manifest: String,
    pub(crate) output_path: String,
    pub(crate) image_path: String,
    pub(crate) image_emitted: bool,
    pub(crate) image_constructed: bool,
    pub(crate) image_ready: bool,
    pub(crate) image_format: String,
    pub(crate) image_header_size: usize,
    pub(crate) payload_byte_offset: usize,
    pub(crate) image_size_bytes: Option<usize>,
    pub(crate) image_hash: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct NsldFinalExecutableImageDryRunVerifyReport {
    pub(crate) manifest: String,
    pub(crate) input_path: String,
    pub(crate) image_path: String,
    pub(crate) valid: bool,
    pub(crate) expected_layout_hash: String,
    pub(crate) actual_layout_hash: Option<String>,
    pub(crate) expected_byte_map_hash: String,
    pub(crate) actual_byte_map_hash: Option<String>,
    pub(crate) expected_image_magic: String,
    pub(crate) actual_image_magic: Option<String>,
    pub(crate) expected_image_version: u32,
    pub(crate) actual_image_version: Option<u32>,
    pub(crate) expected_image_header_size: usize,
    pub(crate) actual_image_header_size: Option<usize>,
    pub(crate) expected_payload_byte_offset: usize,
    pub(crate) actual_payload_byte_offset: Option<usize>,
    pub(crate) expected_payload_byte_span: usize,
    pub(crate) actual_payload_byte_span: Option<usize>,
    pub(crate) actual_header_layout_hash: Option<String>,
    pub(crate) actual_header_byte_map_hash: Option<String>,
    pub(crate) expected_payload_region_count: usize,
    pub(crate) actual_payload_region_count: Option<usize>,
    pub(crate) expected_payload_region_hash: Option<String>,
    pub(crate) actual_payload_region_hash: Option<String>,
    pub(crate) expected_scheduler_metadata_payload_id: String,
    pub(crate) actual_scheduler_metadata_payload_id: Option<String>,
    pub(crate) expected_scheduler_metadata_present: bool,
    pub(crate) actual_scheduler_metadata_present: Option<bool>,
    pub(crate) expected_scheduler_metadata_offset: Option<usize>,
    pub(crate) actual_scheduler_metadata_offset: Option<usize>,
    pub(crate) expected_scheduler_metadata_hash: Option<String>,
    pub(crate) actual_scheduler_metadata_hash: Option<String>,
    pub(crate) expected_image_constructed: bool,
    pub(crate) actual_image_constructed: Option<bool>,
    pub(crate) expected_image_ready: bool,
    pub(crate) actual_image_ready: Option<bool>,
    pub(crate) expected_image_size_bytes: Option<usize>,
    pub(crate) actual_image_size_bytes: Option<usize>,
    pub(crate) expected_image_hash: Option<String>,
    pub(crate) actual_image_hash: Option<String>,
    pub(crate) expected_blockers: Vec<String>,
    pub(crate) actual_blockers: Vec<String>,
    pub(crate) issues: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct NsldFinalExecutableEmitVerifyReport {
    pub(crate) manifest: String,
    pub(crate) input_path: String,
    pub(crate) valid: bool,
    pub(crate) expected_final_stage_plan_hash: String,
    pub(crate) actual_final_stage_plan_hash: Option<String>,
    pub(crate) expected_emitted: bool,
    pub(crate) actual_emitted: Option<bool>,
    pub(crate) expected_writer_input_valid: Option<bool>,
    pub(crate) actual_writer_input_valid: Option<bool>,
    pub(crate) expected_writer_input_hash: Option<String>,
    pub(crate) actual_writer_input_hash: Option<String>,
    pub(crate) expected_writer_input_issues: Vec<String>,
    pub(crate) actual_writer_input_issues: Vec<String>,
    pub(crate) expected_host_dry_run_environment_ready: Option<bool>,
    pub(crate) actual_host_dry_run_environment_ready: Option<bool>,
    pub(crate) expected_host_dry_run_driver_available: Option<bool>,
    pub(crate) actual_host_dry_run_driver_available: Option<bool>,
    pub(crate) expected_host_dry_run_can_invoke: Option<bool>,
    pub(crate) actual_host_dry_run_can_invoke: Option<bool>,
    pub(crate) expected_host_dry_run_driver_resolved_path: Option<String>,
    pub(crate) actual_host_dry_run_driver_resolved_path: Option<String>,
    pub(crate) expected_host_dry_run_invocation_policy: Option<String>,
    pub(crate) actual_host_dry_run_invocation_policy: Option<String>,
    pub(crate) expected_host_dry_run_invocation_policy_reason: Option<String>,
    pub(crate) actual_host_dry_run_invocation_policy_reason: Option<String>,
    pub(crate) expected_host_dry_run_command_arg_count: usize,
    pub(crate) actual_host_dry_run_command_arg_count: Option<usize>,
    pub(crate) expected_host_dry_run_command_args: Vec<String>,
    pub(crate) actual_host_dry_run_command_args: Vec<String>,
    pub(crate) expected_host_dry_run_blocker_count: usize,
    pub(crate) actual_host_dry_run_blocker_count: Option<usize>,
    pub(crate) expected_host_dry_run_blockers: Vec<String>,
    pub(crate) actual_host_dry_run_blockers: Vec<String>,
    pub(crate) expected_host_invoke_plan_valid: Option<bool>,
    pub(crate) actual_host_invoke_plan_valid: Option<bool>,
    pub(crate) expected_host_invoke_plan_would_invoke: Option<bool>,
    pub(crate) actual_host_invoke_plan_would_invoke: Option<bool>,
    pub(crate) expected_host_invoke_plan_hash: Option<String>,
    pub(crate) actual_host_invoke_plan_hash: Option<String>,
    pub(crate) expected_host_invoke_plan_invocation_policy: Option<String>,
    pub(crate) actual_host_invoke_plan_invocation_policy: Option<String>,
    pub(crate) expected_host_invoke_plan_requires_explicit_allow: Option<bool>,
    pub(crate) actual_host_invoke_plan_requires_explicit_allow: Option<bool>,
    pub(crate) expected_host_invoke_plan_explicit_allow_present: Option<bool>,
    pub(crate) actual_host_invoke_plan_explicit_allow_present: Option<bool>,
    pub(crate) expected_host_invoke_plan_blocker_count: Option<usize>,
    pub(crate) actual_host_invoke_plan_blocker_count: Option<usize>,
    pub(crate) expected_host_invoke_plan_issues: Vec<String>,
    pub(crate) actual_host_invoke_plan_issues: Vec<String>,
    pub(crate) expected_layout_plan_valid: Option<bool>,
    pub(crate) actual_layout_plan_valid: Option<bool>,
    pub(crate) expected_layout_plan_hash: Option<String>,
    pub(crate) actual_layout_plan_hash: Option<String>,
    pub(crate) expected_layout_plan_issues: Vec<String>,
    pub(crate) actual_layout_plan_issues: Vec<String>,
    pub(crate) expected_image_dry_run_valid: Option<bool>,
    pub(crate) actual_image_dry_run_valid: Option<bool>,
    pub(crate) expected_image_dry_run_hash: Option<String>,
    pub(crate) actual_image_dry_run_hash: Option<String>,
    pub(crate) expected_image_dry_run_size_bytes: Option<usize>,
    pub(crate) actual_image_dry_run_size_bytes: Option<usize>,
    pub(crate) expected_image_dry_run_issues: Vec<String>,
    pub(crate) actual_image_dry_run_issues: Vec<String>,
    pub(crate) expected_final_output_checked: bool,
    pub(crate) actual_final_output_checked: Option<bool>,
    pub(crate) expected_final_output_present: bool,
    pub(crate) actual_final_output_present: Option<bool>,
    pub(crate) expected_final_output_size_bytes: Option<usize>,
    pub(crate) actual_final_output_size_bytes: Option<usize>,
    pub(crate) expected_final_output_hash: Option<String>,
    pub(crate) actual_final_output_hash: Option<String>,
    pub(crate) expected_final_output_image_header_valid: Option<bool>,
    pub(crate) actual_final_output_image_header_valid: Option<bool>,
    pub(crate) expected_final_output_runnable_candidate: Option<bool>,
    pub(crate) actual_final_output_runnable_candidate: Option<bool>,
    pub(crate) expected_blocker_count: usize,
    pub(crate) actual_blocker_count: Option<usize>,
    pub(crate) expected_blockers: Vec<String>,
    pub(crate) actual_blockers: Vec<String>,
    pub(crate) issues: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct NsldFinalExecutableOutputReport {
    pub(crate) manifest: String,
    pub(crate) output_path: String,
    pub(crate) output_kind: String,
    pub(crate) output_validation_mode: String,
    pub(crate) boundary_status: String,
    pub(crate) path_present: bool,
    pub(crate) nsld_owned_output: bool,
    pub(crate) present: bool,
    pub(crate) size_bytes: Option<usize>,
    pub(crate) output_hash: Option<String>,
    pub(crate) output_image_header_required: bool,
    pub(crate) output_image_header_valid: bool,
    pub(crate) output_image_magic: Option<String>,
    pub(crate) output_image_version: Option<usize>,
    pub(crate) output_image_header_size: Option<usize>,
    pub(crate) output_payload_byte_offset: Option<usize>,
    pub(crate) output_payload_byte_span: Option<usize>,
    pub(crate) output_layout_hash: Option<String>,
    pub(crate) output_byte_map_hash: Option<String>,
    pub(crate) scheduler_metadata_payload_id: Option<String>,
    pub(crate) scheduler_metadata_present: Option<bool>,
    pub(crate) scheduler_metadata_offset: Option<usize>,
    pub(crate) scheduler_metadata_hash: Option<String>,
    pub(crate) expected_image_size_bytes: Option<usize>,
    pub(crate) expected_image_hash: Option<String>,
    pub(crate) matches_expected_image: bool,
    pub(crate) final_stage_plan_valid: bool,
    pub(crate) final_stage_plan_hash: Option<String>,
    pub(crate) final_executable_emit_valid: bool,
    pub(crate) final_executable_emitted: Option<bool>,
    pub(crate) final_executable_blocker_count: Option<usize>,
    pub(crate) runnable_candidate: bool,
    pub(crate) blockers: Vec<String>,
    pub(crate) issues: Vec<String>,
}
