#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct NsldFinalExecutableLauncherManifestReport {
    pub(crate) manifest: String,
    pub(crate) output_path: String,
    pub(crate) launcher_manifest_path: String,
    pub(crate) ready: bool,
    pub(crate) launcher_kind: String,
    pub(crate) launcher_format: String,
    pub(crate) host_envelope_family: String,
    pub(crate) host_os: String,
    pub(crate) host_arch: String,
    pub(crate) output_kind: String,
    pub(crate) output_validation_mode: String,
    pub(crate) final_output_path: String,
    pub(crate) final_output_present: bool,
    pub(crate) final_output_size_bytes: Option<usize>,
    pub(crate) final_output_hash: Option<String>,
    pub(crate) nsb_path: String,
    pub(crate) nsb_present: bool,
    pub(crate) nsb_size_bytes: Option<usize>,
    pub(crate) nsb_hash: Option<String>,
    pub(crate) image_header_required: bool,
    pub(crate) image_header_valid: bool,
    pub(crate) entry_lifecycle_hook: String,
    pub(crate) scheduler_entry: String,
    pub(crate) verification_steps: Vec<String>,
    pub(crate) blockers: Vec<String>,
    pub(crate) notes: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct NsldFinalExecutableLauncherManifestEmitReport {
    pub(crate) manifest: String,
    pub(crate) output_path: String,
    pub(crate) launcher_manifest_hash: String,
    pub(crate) ready: bool,
    pub(crate) blocker_count: usize,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct NsldFinalExecutableLauncherManifestVerifyReport {
    pub(crate) manifest: String,
    pub(crate) input_path: String,
    pub(crate) valid: bool,
    pub(crate) expected_launcher_manifest_hash: String,
    pub(crate) actual_launcher_manifest_hash: Option<String>,
    pub(crate) expected_ready: bool,
    pub(crate) actual_ready: Option<bool>,
    pub(crate) expected_nsb_path: String,
    pub(crate) actual_nsb_path: Option<String>,
    pub(crate) expected_nsb_size_bytes: Option<usize>,
    pub(crate) actual_nsb_size_bytes: Option<usize>,
    pub(crate) expected_nsb_hash: Option<String>,
    pub(crate) actual_nsb_hash: Option<String>,
    pub(crate) expected_output_kind: String,
    pub(crate) actual_output_kind: Option<String>,
    pub(crate) expected_output_validation_mode: String,
    pub(crate) actual_output_validation_mode: Option<String>,
    pub(crate) expected_final_output_path: String,
    pub(crate) actual_final_output_path: Option<String>,
    pub(crate) expected_final_output_size_bytes: Option<usize>,
    pub(crate) actual_final_output_size_bytes: Option<usize>,
    pub(crate) expected_final_output_hash: Option<String>,
    pub(crate) actual_final_output_hash: Option<String>,
    pub(crate) expected_image_header_required: bool,
    pub(crate) actual_image_header_required: Option<bool>,
    pub(crate) expected_image_header_valid: bool,
    pub(crate) actual_image_header_valid: Option<bool>,
    pub(crate) expected_entry_lifecycle_hook: String,
    pub(crate) actual_entry_lifecycle_hook: Option<String>,
    pub(crate) expected_scheduler_entry: String,
    pub(crate) actual_scheduler_entry: Option<String>,
    pub(crate) expected_verification_steps: Vec<String>,
    pub(crate) actual_verification_steps: Vec<String>,
    pub(crate) expected_blocker_count: usize,
    pub(crate) actual_blocker_count: Option<usize>,
    pub(crate) expected_blockers: Vec<String>,
    pub(crate) actual_blockers: Vec<String>,
    pub(crate) issues: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct NsldFinalExecutableLauncherDryRunReport {
    pub(crate) manifest: String,
    pub(crate) launcher_manifest_path: String,
    pub(crate) launcher_manifest_valid: bool,
    pub(crate) final_output_path: Option<String>,
    pub(crate) final_output_readable: bool,
    pub(crate) final_output_hash_expected: Option<String>,
    pub(crate) final_output_hash_actual: Option<String>,
    pub(crate) final_output_hash_matches: bool,
    pub(crate) nsb_path: Option<String>,
    pub(crate) nsb_readable: bool,
    pub(crate) nsb_hash_expected: Option<String>,
    pub(crate) nsb_hash_actual: Option<String>,
    pub(crate) nsb_hash_matches: bool,
    pub(crate) output_kind: Option<String>,
    pub(crate) output_validation_mode: Option<String>,
    pub(crate) image_header_required: Option<bool>,
    pub(crate) image_header_valid: Option<bool>,
    pub(crate) entry_lifecycle_hook: Option<String>,
    pub(crate) scheduler_entry: Option<String>,
    pub(crate) dry_run_ready: bool,
    pub(crate) would_enter_lifecycle_hook: bool,
    pub(crate) launch_steps: Vec<String>,
    pub(crate) blockers: Vec<String>,
    pub(crate) notes: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct NsldFinalExecutableLauncherDryRunEmitReport {
    pub(crate) manifest: String,
    pub(crate) output_path: String,
    pub(crate) dry_run_hash: String,
    pub(crate) dry_run_ready: bool,
    pub(crate) blocker_count: usize,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct NsldFinalExecutableLauncherDryRunVerifyReport {
    pub(crate) manifest: String,
    pub(crate) input_path: String,
    pub(crate) valid: bool,
    pub(crate) expected_dry_run_hash: String,
    pub(crate) actual_dry_run_hash: Option<String>,
    pub(crate) expected_dry_run_ready: bool,
    pub(crate) actual_dry_run_ready: Option<bool>,
    pub(crate) expected_would_enter_lifecycle_hook: bool,
    pub(crate) actual_would_enter_lifecycle_hook: Option<bool>,
    pub(crate) expected_nsb_hash_actual: Option<String>,
    pub(crate) actual_nsb_hash_actual: Option<String>,
    pub(crate) expected_launch_steps: Vec<String>,
    pub(crate) actual_launch_steps: Vec<String>,
    pub(crate) expected_blocker_count: usize,
    pub(crate) actual_blocker_count: Option<usize>,
    pub(crate) expected_blockers: Vec<String>,
    pub(crate) actual_blockers: Vec<String>,
    pub(crate) issues: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct NsldFinalExecutablePipelineEmitReport {
    pub(crate) manifest: String,
    pub(crate) valid: bool,
    pub(crate) final_stage_plan_path: String,
    pub(crate) final_output_path: String,
    pub(crate) writer_input_path: String,
    pub(crate) host_invoke_plan_path: String,
    pub(crate) layout_plan_path: String,
    pub(crate) image_dry_run_path: String,
    pub(crate) final_executable_blocked_path: String,
    pub(crate) launcher_manifest_path: String,
    pub(crate) launcher_dry_run_path: String,
    pub(crate) final_executable_emitted: bool,
    pub(crate) launcher_manifest_ready: bool,
    pub(crate) launcher_dry_run_ready: bool,
    pub(crate) would_enter_lifecycle_hook: bool,
    pub(crate) required_stage_path_count: usize,
    pub(crate) required_stage_path_present_count: usize,
    pub(crate) missing_required_stage_paths: Vec<String>,
    pub(crate) blocker_count: usize,
    pub(crate) blockers: Vec<String>,
    pub(crate) issues: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct NsldFinalExecutablePipelineVerifyReport {
    pub(crate) manifest: String,
    pub(crate) input_path: String,
    pub(crate) valid: bool,
    pub(crate) expected_pipeline_hash: String,
    pub(crate) actual_pipeline_hash: Option<String>,
    pub(crate) expected_valid: bool,
    pub(crate) actual_valid: Option<bool>,
    pub(crate) expected_final_executable_emitted: bool,
    pub(crate) actual_final_executable_emitted: Option<bool>,
    pub(crate) expected_launcher_manifest_ready: bool,
    pub(crate) actual_launcher_manifest_ready: Option<bool>,
    pub(crate) expected_launcher_dry_run_ready: bool,
    pub(crate) actual_launcher_dry_run_ready: Option<bool>,
    pub(crate) expected_would_enter_lifecycle_hook: bool,
    pub(crate) actual_would_enter_lifecycle_hook: Option<bool>,
    pub(crate) expected_required_stage_path_count: usize,
    pub(crate) actual_required_stage_path_count: Option<usize>,
    pub(crate) expected_required_stage_path_present_count: usize,
    pub(crate) actual_required_stage_path_present_count: Option<usize>,
    pub(crate) expected_missing_required_stage_paths: Vec<String>,
    pub(crate) actual_missing_required_stage_paths: Vec<String>,
    pub(crate) expected_blocker_count: usize,
    pub(crate) actual_blocker_count: Option<usize>,
    pub(crate) expected_blockers: Vec<String>,
    pub(crate) actual_blockers: Vec<String>,
    pub(crate) issues: Vec<String>,
}
