[package]
name = "nsdb"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
readme.workspace = true
description = "Nsdb YIR-layer debugger front-door prototype for the Nuis toolchain."

[dependencies]
nuisc = { path = "../nuisc" }
ed25519-dalek.workspace = true
libc.workspace = true
yir-core = { path = "../../crates/yir-core" }
yir-domain-shader = { path = "../../crates/yir-domain-shader" }

[build-dependencies]
nuisc = { path = "../nuisc" }

[dev-dependencies]
yir-exec = { path = "../../crates/yir-exec" }
yir-runtime-host = { path = "../../crates/yir-runtime-host" }
yir-verify = { path = "../../crates/yir-verify" }
