name = "shader_metal_fan_out_provider_demo"
version = "0.1.0"
entry = "main.ns"
packaging_mode = "nuis-self-contained-image"
artifact_provider_metadata = [
  "official.shader:provider-sample=metal-add-xor-pair-u32"
]
modules = ["main.ns", "surface_shader.ns"]
abi = [
  "cpu=cpu.arm64.apple_aapcs64",
  "shader=shader.metal.msl2_4",
]
