use crate::artifact_nsdb_replay_cursor_lineage::DebuggerCursorLineageRepairAction;
use crate::workflow::link_plan_final_output_replay_vocabulary::FinalOutputReplayVocabulary;
use crate::workflow::link_plan_provider_dispatch_identity::ValidatedProviderDispatchIdentityCapability;
use crate::workflow::link_plan_provider_request_completion::ValidatedProviderRequestCompletionCapability;

#[derive(Clone)]
pub(crate) struct ProviderRequestCompletionBoundarySummary {
    pub(crate) contract: String,
    pub(crate) status: String,
    pub(crate) request_id: String,
    pub(crate) provider_family: String,
    pub(crate) dispatch_id: String,
    pub(crate) completion_clock: String,
    pub(crate) output_hash: String,
    pub(crate) completion_token: String,
    pub(crate) selected_set_hash: String,
}

#[derive(Clone)]
pub(crate) struct ProviderRequestCompletionCollectionBoundarySummary {
    pub(crate) source_trace_id: String,
    pub(crate) source_provider_family: String,
    pub(crate) dispatch_selected_set_hash: String,
    pub(crate) contract: String,
    pub(crate) status: String,
    pub(crate) count: usize,
    pub(crate) root_hash: String,
    pub(crate) validation_status: String,
    pub(crate) receipts: Vec<ProviderRequestCompletionBoundarySummary>,
}

#[derive(Clone)]
pub(crate) struct ProviderCompletionBoundarySummary {
    pub(crate) trace_id: String,
    pub(crate) provider_family: String,
    pub(crate) output_contract: String,
    pub(crate) output_evidence: String,
    pub(crate) dispatch_selected_set_hash: String,
    pub(crate) request_completion: ProviderRequestCompletionCollectionBoundarySummary,
    pub(crate) record_hash: String,
}

#[derive(Default)]
pub(crate) struct RuntimeDispatchReceiptBoundarySummary {
    pub(crate) contract: Option<String>,
    pub(crate) status: String,
    pub(crate) receipt_hash: Option<String>,
    pub(crate) execution_identity_hash: Option<String>,
    pub(crate) import_identity_hash: Option<String>,
    pub(crate) table_identity: Option<String>,
    pub(crate) capability_mask: Option<String>,
    pub(crate) slot: Option<u32>,
    pub(crate) status_code: Option<i32>,
    pub(crate) acknowledged: Option<bool>,
}

impl RuntimeDispatchReceiptBoundarySummary {
    pub(super) fn from_persisted(
        receipt: &crate::artifact_runtime_dispatch_receipt::PersistedRuntimeDispatchReceipt,
    ) -> Self {
        Self {
            contract: receipt.contract.clone(),
            status: receipt.verification_status.clone(),
            receipt_hash: receipt.receipt_hash.clone(),
            execution_identity_hash: receipt.execution_identity_hash.clone(),
            import_identity_hash: receipt.import_identity_hash.clone(),
            table_identity: receipt.table_identity.clone(),
            capability_mask: receipt.capability_mask.clone(),
            slot: receipt.slot,
            status_code: receipt.status_code,
            acknowledged: receipt.acknowledged,
        }
    }
}

pub(crate) struct NsldFinalExecutableOutputBoundarySummary {
    pub(crate) artifact_chain_safe_next_contract: String,
    pub(crate) artifact_chain_safe_next_probe_command: String,
    pub(crate) ready: bool,
    pub(crate) boundary_status: String,
    pub(crate) materialization_status: String,
    pub(crate) execution_handoff_contract: String,
    pub(crate) execution_handoff_ready: bool,
    pub(crate) execution_handoff_status: String,
    pub(crate) execution_handoff_target: String,
    pub(crate) execution_handoff_evidence_status: String,
    pub(crate) execution_handoff_first_blocker: Option<String>,
    pub(crate) execution_handoff_decision_code: String,
    pub(crate) entrypoint_materialization_evidence_status: String,
    pub(crate) launcher_manifest_present: bool,
    pub(crate) launcher_manifest_ready: Option<bool>,
    pub(crate) launcher_manifest_blocker_count: Option<usize>,
    pub(crate) launcher_dry_run_present: bool,
    pub(crate) launcher_dry_run_ready: Option<bool>,
    pub(crate) launcher_dry_run_would_enter_lifecycle_hook: Option<bool>,
    pub(crate) launcher_dry_run_blocker_count: Option<usize>,
    pub(crate) payload_execution_trace_protocol: String,
    pub(crate) payload_execution_trace_available: bool,
    pub(crate) payload_execution_trace_record_count: usize,
    pub(crate) payload_execution_trace_ready_record_count: usize,
    pub(crate) device_provider_sample_manifest_available: bool,
    pub(crate) device_provider_sample_manifest_status: String,
    pub(crate) device_provider_sample_manifest_record_count: usize,
    pub(crate) device_provider_sample_manifest_pending_record_count: usize,
    pub(crate) device_provider_sample_manifest_blocked_record_count: usize,
    pub(crate) device_provider_sample_manifest_first_provider_family: String,
    pub(crate) device_provider_sample_manifest_first_materialization_status: String,
    pub(crate) device_provider_sample_provider_bundle_registry_contract: String,
    pub(crate) device_provider_sample_provider_bundle_manifest_contract: String,
    pub(crate) device_provider_sample_provider_bundle_manifest_hash: String,
    pub(crate) device_provider_sample_provider_bundle_manifest_entry_count: usize,
    pub(crate) device_provider_sample_manifest_first_provider_bundle_package_id: String,
    pub(crate) device_provider_sample_manifest_first_provider_bundle_id: String,
    pub(crate) device_provider_sample_provider_bundle_evidence_status: String,
    pub(crate) device_provider_sample_selected_provider_bundle_set_contract: String,
    pub(crate) device_provider_sample_selected_provider_bundle_count: usize,
    pub(crate) device_provider_sample_selected_provider_bundle_set_hash: String,
    pub(crate) device_provider_sample_selected_provider_bundle_set_validation_status: String,
    pub(crate) nsdb_replay_contract: String,
    pub(crate) nsdb_replay_ready: bool,
    pub(crate) nsdb_replay_status: String,
    pub(crate) nsdb_replay_checkpoint_count: usize,
    pub(crate) nsdb_replayable_checkpoint_count: usize,
    pub(crate) runtime_dispatch_receipt: RuntimeDispatchReceiptBoundarySummary,
    pub(crate) nsdb_provider_completion_count: usize,
    pub(crate) nsdb_first_provider_family: Option<String>,
    pub(crate) nsdb_first_provider_output_contract: Option<String>,
    pub(crate) nsdb_first_provider_output_evidence: Option<String>,
    pub(crate) nsdb_provider_completion_claim_authority_contract: Option<String>,
    pub(crate) nsdb_provider_completion_claim_authority: Option<String>,
    pub(crate) nsdb_provider_completion_claim_authority_status: String,
    pub(crate) nsdb_provider_completion_signature_contract: Option<String>,
    pub(crate) nsdb_provider_completion_signature_public_key_id: Option<String>,
    pub(crate) nsdb_provider_completion_signature_status: String,
    pub(crate) nsdb_provider_completion_digest_contract: Option<String>,
    pub(crate) nsdb_provider_completion_set_hash_claim: Option<String>,
    pub(crate) nsdb_provider_completion_set_hash: Option<String>,
    pub(crate) nsdb_provider_completion_set_hash_validation_status: String,
    pub(crate) nsdb_provider_completions: Vec<ProviderCompletionBoundarySummary>,
    pub(crate) nsdb_replay_command: Option<String>,
    pub(crate) nsdb_replay_next_action: String,
    pub(crate) nsdb_replay_next_command: Option<String>,
    pub(crate) nsdb_replay_first_blocker: Option<String>,
    pub(crate) replay_vocabulary: FinalOutputReplayVocabulary,
    pub(crate) object_package_summary_contract: String,
    pub(crate) object_package_summary_ready: bool,
    pub(crate) object_package_summary_status: String,
    pub(crate) object_package_summary_next_action: String,
    pub(crate) object_package_summary_next_command: Option<String>,
    pub(crate) debugger_transcript_contract: String,
    pub(crate) debugger_transcript_ready: bool,
    pub(crate) debugger_transcript_status: String,
    pub(crate) debugger_transcript_next_action: String,
    pub(crate) debugger_transcript_next_command: Option<String>,
    pub(crate) debugger_transcript_first_blocker: Option<String>,
    pub(crate) debugger_cursor_handoff_contract: String,
    pub(crate) debugger_cursor_path: String,
    pub(crate) debugger_cursor_ready: bool,
    pub(crate) debugger_cursor_status: String,
    pub(crate) debugger_cursor_next_command: Option<String>,
    pub(crate) debugger_cursor_lineage_contract: String,
    pub(crate) debugger_cursor_lineage_source_protocol: String,
    pub(crate) debugger_cursor_lineage_path: String,
    pub(crate) debugger_cursor_lineage_ready: bool,
    pub(crate) debugger_cursor_lineage_status: String,
    pub(crate) debugger_cursor_lineage_entry_count: usize,
    pub(crate) debugger_cursor_lineage_latest_hash: Option<String>,
    pub(crate) debugger_cursor_lineage_provider_dispatch_identity_hash: Option<String>,
    pub(crate) provider_dispatch_identity_capability: ValidatedProviderDispatchIdentityCapability,
    pub(crate) provider_request_completion_capability: ValidatedProviderRequestCompletionCapability,
    pub(crate) debugger_cursor_lineage_first_blocker: Option<String>,
    pub(crate) debugger_cursor_lineage_next_action: Option<String>,
    pub(crate) debugger_cursor_lineage_next_command: Option<String>,
    pub(crate) debugger_cursor_lineage_repair_contract: String,
    pub(crate) debugger_cursor_lineage_repair_path: String,
    pub(crate) debugger_cursor_lineage_repair_status: String,
    pub(crate) debugger_cursor_lineage_repair_entry_count: usize,
    pub(crate) debugger_cursor_lineage_repair_rotation_generation: Option<u64>,
    pub(crate) debugger_cursor_lineage_repair_evicted_prefix_hash: Option<String>,
    pub(crate) debugger_cursor_lineage_repair_window_hash: Option<String>,
    pub(crate) debugger_cursor_lineage_repair_latest_mutated: Option<bool>,
    pub(crate) debugger_cursor_lineage_repair_latest_event_status: Option<String>,
    pub(crate) debugger_cursor_lineage_repair_latest_lineage_mutated: Option<bool>,
    pub(crate) debugger_cursor_lineage_repair_latest_journal_mutated: Option<bool>,
    pub(crate) debugger_cursor_lineage_repair_latest_archived_path: Option<String>,
    pub(crate) debugger_cursor_lineage_repair_latest_archived_hash: Option<String>,
    pub(crate) debugger_cursor_lineage_repair_latest_archived_journal_path: Option<String>,
    pub(crate) debugger_cursor_lineage_repair_latest_archived_journal_hash: Option<String>,
    pub(crate) debugger_cursor_lineage_repair_latest_rebuilt_hash: Option<String>,
    pub(crate) debugger_cursor_lineage_repair_action: DebuggerCursorLineageRepairAction,
    pub(crate) recommended_next_action: String,
    pub(crate) path_present: bool,
    pub(crate) nsld_owned: Option<bool>,
    pub(crate) object_valid: bool,
    pub(crate) object_path: String,
    pub(crate) object_family: String,
    pub(crate) object_magic_status: String,
    pub(crate) object_magic: Option<String>,
    pub(crate) object_expected_size_bytes: Option<usize>,
    pub(crate) object_actual_size_bytes: Option<usize>,
    pub(crate) object_expected_hash: Option<String>,
    pub(crate) object_actual_hash: Option<String>,
    pub(crate) object_issues: Vec<String>,
    pub(crate) blockers: Vec<String>,
    pub(crate) first_blocker: Option<String>,
}
