use crate::registry_build_contract_summary::{
    NustarDomainBackendStubSummary, NustarDomainBridgePlanSummary,
    NustarDomainBuildContractSummary, NustarDomainLoweringPlanSummary, NustarHostBridgeSpecSummary,
};

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct FallbackDomainBuildPreset {
    lane_policy: &'static str,
    bridge_surface: &'static str,
    emission_kind: &'static str,
    bridge_entry: &'static str,
    bridge_kind: &'static str,
    stub_kind: &'static str,
    submission_mode: &'static str,
    wake_policy: &'static str,
    scheduler_binding: &'static str,
    phase_bind: &'static str,
    phase_submit: &'static str,
    phase_wait: &'static str,
    phase_finalize: &'static str,
    transport_model: Option<&'static str>,
    request_shape: Option<&'static str>,
    response_shape: Option<&'static str>,
    dispatch_shape: Option<&'static str>,
    memory_binding: Option<&'static str>,
    resource_binding: Option<&'static str>,
    completion_model: Option<&'static str>,
    host_ffi_surface: &'static [&'static str],
    handle_family: &'static [&'static str],
    phase_bind_inputs: &'static [&'static str],
    phase_bind_outputs: &'static [&'static str],
    phase_submit_inputs: &'static [&'static str],
    phase_submit_outputs: &'static [&'static str],
    phase_wait_inputs: &'static [&'static str],
    phase_wait_outputs: &'static [&'static str],
    phase_finalize_inputs: &'static [&'static str],
    phase_finalize_outputs: &'static [&'static str],
    phase_bind_wake: &'static str,
    phase_submit_wake: &'static str,
    phase_wait_wake: &'static str,
    phase_finalize_wake: &'static str,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct FallbackBackendFacet {
    stub_kind: &'static str,
    submission_mode: &'static str,
    wake_policy: &'static str,
    transport_model: Option<&'static str>,
    request_shape: Option<&'static str>,
    response_shape: Option<&'static str>,
    dispatch_shape: Option<&'static str>,
    memory_binding: Option<&'static str>,
    resource_binding: Option<&'static str>,
    completion_model: Option<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct FallbackBridgeFlowFacet {
    lane_policy: &'static str,
    bridge_surface: &'static str,
    bridge_entry: &'static str,
    scheduler_binding: &'static str,
    phase_bind: &'static str,
    phase_submit: &'static str,
    phase_wait: &'static str,
    phase_finalize: &'static str,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct FallbackHostBridgeFacet {
    host_ffi_surface: &'static [&'static str],
    handle_family: &'static [&'static str],
    phase_bind_inputs: &'static [&'static str],
    phase_bind_outputs: &'static [&'static str],
    phase_submit_inputs: &'static [&'static str],
    phase_submit_outputs: &'static [&'static str],
    phase_wait_inputs: &'static [&'static str],
    phase_wait_outputs: &'static [&'static str],
    phase_finalize_inputs: &'static [&'static str],
    phase_finalize_outputs: &'static [&'static str],
    phase_bind_wake: &'static str,
    phase_submit_wake: &'static str,
    phase_wait_wake: &'static str,
    phase_finalize_wake: &'static str,
}

const DEFAULT_BRIDGE_PHASE_ORDER: [&str; 4] = ["bind", "submit", "wait", "finalize"];

fn preset_vec(values: &[&str]) -> Vec<String> {
    values.iter().map(|v| (*v).to_owned()).collect()
}

fn preset_csv(values: &[&str]) -> String {
    values.join(",")
}

fn fallback_preset(
    flow: FallbackBridgeFlowFacet,
    backend: FallbackBackendFacet,
    host_bridge: FallbackHostBridgeFacet,
) -> FallbackDomainBuildPreset {
    FallbackDomainBuildPreset {
        lane_policy: flow.lane_policy,
        bridge_surface: flow.bridge_surface,
        emission_kind: "sidecar-plan",
        bridge_entry: flow.bridge_entry,
        bridge_kind: "managed-lifecycle-bridge",
        stub_kind: backend.stub_kind,
        submission_mode: backend.submission_mode,
        wake_policy: backend.wake_policy,
        scheduler_binding: flow.scheduler_binding,
        phase_bind: flow.phase_bind,
        phase_submit: flow.phase_submit,
        phase_wait: flow.phase_wait,
        phase_finalize: flow.phase_finalize,
        transport_model: backend.transport_model,
        request_shape: backend.request_shape,
        response_shape: backend.response_shape,
        dispatch_shape: backend.dispatch_shape,
        memory_binding: backend.memory_binding,
        resource_binding: backend.resource_binding,
        completion_model: backend.completion_model,
        host_ffi_surface: host_bridge.host_ffi_surface,
        handle_family: host_bridge.handle_family,
        phase_bind_inputs: host_bridge.phase_bind_inputs,
        phase_bind_outputs: host_bridge.phase_bind_outputs,
        phase_submit_inputs: host_bridge.phase_submit_inputs,
        phase_submit_outputs: host_bridge.phase_submit_outputs,
        phase_wait_inputs: host_bridge.phase_wait_inputs,
        phase_wait_outputs: host_bridge.phase_wait_outputs,
        phase_finalize_inputs: host_bridge.phase_finalize_inputs,
        phase_finalize_outputs: host_bridge.phase_finalize_outputs,
        phase_bind_wake: host_bridge.phase_bind_wake,
        phase_submit_wake: host_bridge.phase_submit_wake,
        phase_wait_wake: host_bridge.phase_wait_wake,
        phase_finalize_wake: host_bridge.phase_finalize_wake,
    }
}

impl FallbackDomainBuildPreset {
    pub(crate) fn into_summary(self) -> NustarDomainBuildContractSummary {
        NustarDomainBuildContractSummary {
            lowering: NustarDomainLoweringPlanSummary {
                lane_policy: self.lane_policy.to_owned(),
                bridge_surface: self.bridge_surface.to_owned(),
                emission_kind: self.emission_kind.to_owned(),
            },
            backend: NustarDomainBackendStubSummary {
                stub_kind: self.stub_kind.to_owned(),
                bridge_entry: self.bridge_entry.to_owned(),
                submission_mode: self.submission_mode.to_owned(),
                wake_policy: self.wake_policy.to_owned(),
                scheduler_binding: self.scheduler_binding.to_owned(),
                phase_bind: Some(self.phase_bind.to_owned()),
                phase_submit: Some(self.phase_submit.to_owned()),
                phase_wait: Some(self.phase_wait.to_owned()),
                phase_finalize: Some(self.phase_finalize.to_owned()),
                transport_model: self.transport_model.map(str::to_owned),
                request_shape: self.request_shape.map(str::to_owned),
                response_shape: self.response_shape.map(str::to_owned),
                dispatch_shape: self.dispatch_shape.map(str::to_owned),
                memory_binding: self.memory_binding.map(str::to_owned),
                resource_binding: self.resource_binding.map(str::to_owned),
                completion_model: self.completion_model.map(str::to_owned),
            },
            bridge: NustarDomainBridgePlanSummary {
                bridge_surface: self.bridge_surface.to_owned(),
                bridge_entry: self.bridge_entry.to_owned(),
                scheduler_binding: self.scheduler_binding.to_owned(),
                phase_bind: self.phase_bind.to_owned(),
                phase_submit: self.phase_submit.to_owned(),
                phase_wait: self.phase_wait.to_owned(),
                phase_finalize: self.phase_finalize.to_owned(),
                bridge_kind: self.bridge_kind.to_owned(),
            },
            host_bridge: NustarHostBridgeSpecSummary {
                host_ffi_surface: preset_csv(self.host_ffi_surface),
                handle_family: preset_csv(self.handle_family),
                phase_order: preset_vec(&DEFAULT_BRIDGE_PHASE_ORDER),
                phase_bind_inputs: preset_vec(self.phase_bind_inputs),
                phase_bind_outputs: preset_vec(self.phase_bind_outputs),
                phase_submit_inputs: preset_vec(self.phase_submit_inputs),
                phase_submit_outputs: preset_vec(self.phase_submit_outputs),
                phase_wait_inputs: preset_vec(self.phase_wait_inputs),
                phase_wait_outputs: preset_vec(self.phase_wait_outputs),
                phase_finalize_inputs: preset_vec(self.phase_finalize_inputs),
                phase_finalize_outputs: preset_vec(self.phase_finalize_outputs),
                phase_bind_wake: self.phase_bind_wake.to_owned(),
                phase_submit_wake: self.phase_submit_wake.to_owned(),
                phase_wait_wake: self.phase_wait_wake.to_owned(),
                phase_finalize_wake: self.phase_finalize_wake.to_owned(),
                bridge_plan_begin: true,
                bridge_plan_end: true,
            },
        }
    }
}

pub(crate) fn fallback_domain_build_preset(
    domain_family: &str,
) -> Option<FallbackDomainBuildPreset> {
    match domain_family {
        "network" => Some(fallback_preset(
            FallbackBridgeFlowFacet {
                lane_policy: "dispatch-lanes.io-bound",
                bridge_surface: "host-ffi.bridge.network",
                bridge_entry: "nuis.network.bridge.dispatch.v1",
                scheduler_binding: "network-poll-bridge",
                phase_bind: "socket-bind-or-session-open",
                phase_submit: "packet-write-dispatch",
                phase_wait: "callback-or-read-ready",
                phase_finalize: "response-commit-and-wake",
            },
            FallbackBackendFacet {
                stub_kind: "network-host-bridge",
                submission_mode: "request-response",
                wake_policy: "io-ready",
                transport_model: Some("client-session"),
                request_shape: Some("packetized-exchange"),
                response_shape: Some("completion-callback"),
                dispatch_shape: None,
                memory_binding: None,
                resource_binding: None,
                completion_model: None,
            },
            FallbackHostBridgeFacet {
                host_ffi_surface: &["socket", "urlsession"],
                handle_family: &["network.request", "network.response"],
                phase_bind_inputs: &["request.packet", "bridge.config", "host.session"],
                phase_bind_outputs: &["session.handle", "request.handle"],
                phase_submit_inputs: &["session.handle", "request.handle", "request.packet"],
                phase_submit_outputs: &["inflight.request", "poll.token"],
                phase_wait_inputs: &["poll.token", "callback.slot"],
                phase_wait_outputs: &["response.packet", "completion.signal"],
                phase_finalize_inputs: &["response.packet", "completion.signal"],
                phase_finalize_outputs: &["result.value", "scheduler.wake"],
                phase_bind_wake: "bind-ready",
                phase_submit_wake: "submit-ready",
                phase_wait_wake: "io-ready",
                phase_finalize_wake: "result-commit",
            },
        )),
        "kernel" => Some(fallback_preset(
            FallbackBridgeFlowFacet {
                lane_policy: "dispatch-lanes.accelerator-bound",
                bridge_surface: "host-ffi.bridge.hetero",
                bridge_entry: "nuis.kernel.bridge.dispatch.v1",
                scheduler_binding: "hetero-submit-bridge",
                phase_bind: "buffer-and-argument-bind",
                phase_submit: "queue-dispatch-submit",
                phase_wait: "fence-await-or-poll",
                phase_finalize: "result-commit-and-release",
            },
            FallbackBackendFacet {
                stub_kind: "kernel-dispatch",
                submission_mode: "accelerator-dispatch",
                wake_policy: "completion-fence",
                transport_model: None,
                request_shape: None,
                response_shape: None,
                dispatch_shape: Some("grid-launch"),
                memory_binding: Some("buffer-table"),
                resource_binding: None,
                completion_model: Some("device-fence"),
            },
            FallbackHostBridgeFacet {
                host_ffi_surface: &["buffer", "queue", "fence"],
                handle_family: &["kernel.buffer", "kernel.dispatch"],
                phase_bind_inputs: &["kernel.args", "buffer.table", "dispatch.config"],
                phase_bind_outputs: &["bound.buffer.table", "dispatch.handle"],
                phase_submit_inputs: &["dispatch.handle", "bound.buffer.table", "queue.slot"],
                phase_submit_outputs: &["inflight.dispatch", "fence.handle"],
                phase_wait_inputs: &["fence.handle", "poll.token"],
                phase_wait_outputs: &["completion.state", "result.buffer"],
                phase_finalize_inputs: &["completion.state", "result.buffer"],
                phase_finalize_outputs: &["result.value", "resource.release"],
                phase_bind_wake: "bind-ready",
                phase_submit_wake: "submit-ready",
                phase_wait_wake: "completion-fence",
                phase_finalize_wake: "result-commit",
            },
        )),
        "shader" => Some(fallback_preset(
            FallbackBridgeFlowFacet {
                lane_policy: "dispatch-lanes.render-bound",
                bridge_surface: "host-ffi.bridge.hetero",
                bridge_entry: "nuis.shader.bridge.dispatch.v1",
                scheduler_binding: "render-submit-bridge",
                phase_bind: "pipeline-and-resource-bind",
                phase_submit: "draw-or-dispatch-encode",
                phase_wait: "frame-fence-await",
                phase_finalize: "present-or-signal",
            },
            FallbackBackendFacet {
                stub_kind: "shader-dispatch",
                submission_mode: "frame-graph-dispatch",
                wake_policy: "frame-present",
                transport_model: None,
                request_shape: None,
                response_shape: None,
                dispatch_shape: Some("render-pass"),
                memory_binding: None,
                resource_binding: Some("pipeline-layout"),
                completion_model: Some("frame-fence"),
            },
            FallbackHostBridgeFacet {
                host_ffi_surface: &["pipeline", "resource", "fence"],
                handle_family: &["shader.pipeline", "shader.dispatch"],
                phase_bind_inputs: &["pipeline.layout", "resource.table", "frame.config"],
                phase_bind_outputs: &["bound.pipeline", "dispatch.handle"],
                phase_submit_inputs: &["dispatch.handle", "bound.pipeline", "encoder.slot"],
                phase_submit_outputs: &["inflight.frame", "frame.fence"],
                phase_wait_inputs: &["frame.fence", "present.slot"],
                phase_wait_outputs: &["frame.state", "present.signal"],
                phase_finalize_inputs: &["frame.state", "present.signal"],
                phase_finalize_outputs: &["present.result", "scheduler.wake"],
                phase_bind_wake: "bind-ready",
                phase_submit_wake: "submit-ready",
                phase_wait_wake: "frame-present",
                phase_finalize_wake: "present-commit",
            },
        )),
        "host" | "cpu" => Some(fallback_preset(
            FallbackBridgeFlowFacet {
                lane_policy: "dispatch-lanes.host-bound",
                bridge_surface: "host-ffi.bridge.none",
                bridge_entry: "nuis.host.bridge.dispatch.v1",
                scheduler_binding: "host-inline",
                phase_bind: "direct-bind",
                phase_submit: "direct-call",
                phase_wait: "immediate",
                phase_finalize: "return-and-finish",
            },
            FallbackBackendFacet {
                stub_kind: "host-fallback",
                submission_mode: "direct-call",
                wake_policy: "immediate",
                transport_model: None,
                request_shape: None,
                response_shape: None,
                dispatch_shape: None,
                memory_binding: None,
                resource_binding: None,
                completion_model: None,
            },
            FallbackHostBridgeFacet {
                host_ffi_surface: &["host-inline"],
                handle_family: &["host.inline"],
                phase_bind_inputs: &["call.args"],
                phase_bind_outputs: &["bound.call"],
                phase_submit_inputs: &["bound.call"],
                phase_submit_outputs: &["inflight.call"],
                phase_wait_inputs: &["inflight.call"],
                phase_wait_outputs: &["call.result"],
                phase_finalize_inputs: &["call.result"],
                phase_finalize_outputs: &["result.value"],
                phase_bind_wake: "bind-ready",
                phase_submit_wake: "submit-ready",
                phase_wait_wake: "immediate",
                phase_finalize_wake: "return",
            },
        )),
        _ => None,
    }
}
