use super::*;

pub(super) fn lower_network_expr(
    expr: &NirExpr,
    state: &mut LoweringState<'_>,
    bindings: &BTreeMap<String, String>,
) -> Option<Result<String, String>> {
    match expr {
        NirExpr::NetworkProfileBindCoreRef { unit } => Some(lower_project_profile_ref(
            state,
            "network",
            unit,
            "bind_core",
        )),
        NirExpr::NetworkProfileEndpointKindRef { unit } => Some(lower_project_profile_ref(
            state,
            "network",
            unit,
            "endpoint_kind",
        )),
        NirExpr::NetworkProfileTransportFamilyRef { unit } => Some(lower_project_profile_ref(
            state,
            "network",
            unit,
            "transport_family",
        )),
        NirExpr::NetworkProfileLocalPortRef { unit } => Some(lower_project_profile_ref(
            state,
            "network",
            unit,
            "local_port",
        )),
        NirExpr::NetworkProfileRemotePortRef { unit } => Some(lower_project_profile_ref(
            state,
            "network",
            unit,
            "remote_port",
        )),
        NirExpr::NetworkProfileConnectTimeoutRef { unit } => Some(lower_project_profile_ref(
            state,
            "network",
            unit,
            "connect_timeout_ms",
        )),
        NirExpr::NetworkProfileReadTimeoutRef { unit } => Some(lower_project_profile_ref(
            state,
            "network",
            unit,
            "read_timeout_ms",
        )),
        NirExpr::NetworkProfileWriteTimeoutRef { unit } => Some(lower_project_profile_ref(
            state,
            "network",
            unit,
            "write_timeout_ms",
        )),
        NirExpr::NetworkProfileTimeoutBudgetRef { unit } => Some(lower_project_profile_ref(
            state,
            "network",
            unit,
            "connect_timeout_ms",
        )),
        NirExpr::NetworkProfileRetryBudgetRef { unit } => Some(lower_project_profile_ref(
            state,
            "network",
            unit,
            "retry_budget",
        )),
        NirExpr::NetworkProfileStreamWindowRef { unit } => Some(lower_project_profile_ref(
            state,
            "network",
            unit,
            "stream_window",
        )),
        NirExpr::NetworkProfileRecvWindowRef { unit } => Some(lower_project_profile_ref(
            state,
            "network",
            unit,
            "recv_window",
        )),
        NirExpr::NetworkProfileSendWindowRef { unit } => Some(lower_project_profile_ref(
            state,
            "network",
            unit,
            "send_window",
        )),
        NirExpr::NetworkProfileProtocolKindRef { unit } => Some(lower_project_profile_ref(
            state,
            "network",
            unit,
            "protocol_kind",
        )),
        NirExpr::NetworkProfileProtocolVersionRef { unit } => Some(lower_project_profile_ref(
            state,
            "network",
            unit,
            "protocol_version",
        )),
        NirExpr::NetworkProfileProtocolHeaderBytesRef { unit } => Some(lower_project_profile_ref(
            state,
            "network",
            unit,
            "protocol_header_bytes",
        )),
        NirExpr::NetworkResult { value, state: flow } => Some(lower_result_observe_node(
            state,
            bindings,
            ResultLoweringDomain::Network,
            value,
            "network_result",
            flow.render(),
        )),
        NirExpr::NetworkConfigReady(result) => Some(lower_result_unary_value_effect(
            state,
            bindings,
            ResultLoweringDomain::Network,
            result,
            "network_config_ready",
            "is_config_ready",
        )),
        NirExpr::NetworkSendReady(result) => Some(lower_result_unary_value_effect(
            state,
            bindings,
            ResultLoweringDomain::Network,
            result,
            "network_send_ready",
            "is_send_ready",
        )),
        NirExpr::NetworkRecvReady(result) => Some(lower_result_unary_value_effect(
            state,
            bindings,
            ResultLoweringDomain::Network,
            result,
            "network_recv_ready",
            "is_recv_ready",
        )),
        NirExpr::NetworkAcceptReady(result) => Some(lower_result_unary_value_effect(
            state,
            bindings,
            ResultLoweringDomain::Network,
            result,
            "network_accept_ready",
            "is_accept_ready",
        )),
        NirExpr::NetworkValue(result) => Some(lower_result_unary_value_effect(
            state,
            bindings,
            ResultLoweringDomain::Network,
            result,
            "network_value",
            "value",
        )),
        _ => None,
    }
}
