use super::PersistedNsdbHandoffSummary;
use crate::{json_bool_field, json_field, json_optional_string_field, json_usize_field};

pub(super) fn fields(summary: &PersistedNsdbHandoffSummary, prefix: &str) -> Vec<String> {
    let mut fields = vec![
        json_bool_field(&format!("{prefix}_available"), summary.available),
        json_optional_string_field(&format!("{prefix}_protocol"), summary.protocol.as_deref()),
        json_optional_string_field(
            &format!("{prefix}_debugger_contract"),
            summary.debugger_contract.as_deref(),
        ),
        json_field(
            &format!("{prefix}_path"),
            &summary.path.display().to_string(),
        ),
        json_usize_field(&format!("{prefix}_record_count"), summary.record_count),
        json_usize_field(
            &format!("{prefix}_ready_record_count"),
            summary.ready_record_count,
        ),
        json_optional_string_field(
            &format!("{prefix}_first_trace_id"),
            summary.first_trace_id.as_deref(),
        ),
        json_optional_string_field(
            &format!("{prefix}_first_status"),
            summary.first_status.as_deref(),
        ),
        json_optional_string_field(
            &format!("{prefix}_first_next_action"),
            summary.first_next_action.as_deref(),
        ),
        json_optional_string_field(
            &format!("{prefix}_final_image_binding_proof_contract"),
            summary.final_image_binding_proof.contract.as_deref(),
        ),
        json_usize_field(
            &format!("{prefix}_final_image_metadata_binding_count"),
            summary.final_image_binding_proof.binding_count,
        ),
        json_optional_string_field(
            &format!("{prefix}_final_image_metadata_binding_table_hash"),
            summary
                .final_image_binding_proof
                .binding_table_hash
                .as_deref(),
        ),
        json_field(
            &format!("{prefix}_final_image_metadata_binding_validation_status"),
            &summary.final_image_binding_proof.validation_status,
        ),
        json_optional_string_field(
            &format!("{prefix}_final_image_selected_provider_bundle_set_contract"),
            summary
                .final_image_binding_proof
                .selected_set_contract
                .as_deref(),
        ),
        json_usize_field(
            &format!("{prefix}_final_image_selected_provider_bundle_count"),
            summary
                .final_image_binding_proof
                .selected_set_count
                .unwrap_or(0),
        ),
        json_optional_string_field(
            &format!("{prefix}_final_image_selected_provider_bundle_set_hash"),
            summary
                .final_image_binding_proof
                .selected_set_hash
                .as_deref(),
        ),
        json_optional_string_field(
            &format!("{prefix}_final_image_binding_proof_hash"),
            summary.final_image_binding_proof.proof_hash.as_deref(),
        ),
        json_field(
            &format!("{prefix}_final_image_binding_proof_verification_status"),
            &summary.final_image_binding_proof.verification_status,
        ),
        json_field(
            &format!("{prefix}_final_image_binding_proof_next_action"),
            crate::artifact_nsdb_handoff_binding::next_action(
                &summary.final_image_binding_proof.verification_status,
            ),
        ),
        json_usize_field(
            &format!("{prefix}_provider_completion_count"),
            summary.provider_completion_count,
        ),
        json_optional_string_field(
            &format!("{prefix}_first_provider_family"),
            summary.first_provider_family.as_deref(),
        ),
        json_optional_string_field(
            &format!("{prefix}_first_provider_output_contract"),
            summary.first_provider_output_contract.as_deref(),
        ),
        json_optional_string_field(
            &format!("{prefix}_first_provider_output_evidence"),
            summary.first_provider_output_evidence.as_deref(),
        ),
        json_optional_string_field(
            &format!("{prefix}_provider_completion_claim_authority_contract"),
            summary
                .provider_completion_claim_authority_contract
                .as_deref(),
        ),
        json_optional_string_field(
            &format!("{prefix}_provider_completion_claim_authority"),
            summary.provider_completion_claim_authority.as_deref(),
        ),
        json_field(
            &format!("{prefix}_provider_completion_claim_authority_status"),
            &summary.provider_completion_claim_authority_status,
        ),
        json_optional_string_field(
            &format!("{prefix}_provider_completion_signature_contract"),
            summary.provider_completion_signature_contract.as_deref(),
        ),
        json_optional_string_field(
            &format!("{prefix}_provider_completion_signature_public_key_id"),
            summary
                .provider_completion_signature_public_key_id
                .as_deref(),
        ),
        json_field(
            &format!("{prefix}_provider_completion_signature_status"),
            &summary.provider_completion_signature_status,
        ),
        json_optional_string_field(
            &format!("{prefix}_provider_completion_digest_contract"),
            summary.provider_completion_digest_contract.as_deref(),
        ),
        json_optional_string_field(
            &format!("{prefix}_provider_completion_set_hash_claim"),
            summary.provider_completion_set_hash_claim.as_deref(),
        ),
        json_optional_string_field(
            &format!("{prefix}_provider_completion_set_hash"),
            summary.provider_completion_set_hash.as_deref(),
        ),
        json_field(
            &format!("{prefix}_provider_completion_set_hash_validation_status"),
            &summary.provider_completion_set_hash_validation_status,
        ),
        json_optional_string_field(
            &format!("{prefix}_hetero_execution_closure_status"),
            summary.hetero_execution_closure_status.as_deref(),
        ),
        json_optional_string_field(
            &format!("{prefix}_hetero_execution_closure_ready"),
            summary.hetero_execution_closure_ready.as_deref(),
        ),
        json_optional_string_field(
            &format!("{prefix}_hetero_execution_closure_next_action"),
            summary.hetero_execution_closure_next_action.as_deref(),
        ),
        json_optional_string_field(&format!("{prefix}_error"), summary.error.as_deref()),
    ];
    fields.extend(
        summary
            .runtime_dispatch_receipt
            .json_fields_with_prefix(prefix),
    );
    fields
}
