use crate::dev_tensor_drift::DevTensorDriftCheckSpec;

pub(crate) const DEV_TENSOR_RUNTIME_SHADER_GRAPH_DRIFT_CHECKS: &[DevTensorDriftCheckSpec] = &[
    DevTensorDriftCheckSpec {
        id: "nuis-shader-vulkan-device-sample-registration",
        path: "tools/nuis/src/artifact_device_sample_shader_vulkan.rs",
        required_patterns: &[
            "DeviceSampleInputRegistration",
            "official.shader.vulkan-copy-u32",
            "official.shader.vulkan-add-u32",
            "official.shader.vulkan-add-pair-u32",
            "official.shader.vulkan-sub-u32",
            "official.shader.vulkan-mul-u32",
            "official.shader.vulkan-xor-u32",
            "official.shader.vulkan-u32-chain",
            "official.shader:provider-sample=vulkan-add-u32",
            "official.shader:provider-sample=vulkan-add-pair-u32",
            "official.shader:provider-sample=vulkan-sub-u32",
            "official.shader:provider-sample=vulkan-mul-u32",
            "official.shader:provider-sample=vulkan-xor-u32",
            "official.shader:provider-sample=vulkan-u32-chain",
            "provider_request_collection_contract=nuis-provider-request-collection-v1",
            "provider_request_count=2",
            "provider_request_1_input_binding_0_source=dependency",
            "provider_request_1_dependency_0_transport_contract=nuis-provider-edge-transport-v1",
            "provider_code_asset_identity_set_count=2",
            "provider_family: \"spirv:vulkan-gpu\"",
            "render_u32_sample_request_evidence",
            "render_u32_prefixed_request_evidence",
            "render_u32_dependency_edge",
            "render_u32_pair_artifact_binding",
            "nuis-provider-input-binding-v2",
            "tensor-row-major",
            "2x2",
            "shader.vulkan.copy-u32.spirv",
            "shader.vulkan.add-u32.spirv",
            "shader.vulkan.add-pair-u32.spirv",
            "shader.vulkan.sub-u32.spirv",
            "shader.vulkan.mul-u32.spirv",
            "shader.vulkan.xor-u32.spirv",
            "code_asset_registration_by_id",
            "provider_kernel_operation={}",
            "provider_code_asset_format=spirv-binary",
            "provider_adapter_binding_provider_family=spirv:vulkan-gpu",
            "select_compiled_code_asset_contribution",
            "render_selected_contribution_set_evidence",
            "validate_provider_request_evidence",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-shader-metal-device-sample-registration",
        path: "tools/nuis/src/artifact_device_sample_shader_metal.rs",
        required_patterns: &[
            "official.shader.metal-copy-u32",
            "official.shader.metal-add-u32",
            "official.shader.metal-add-pair-u32",
            "official.shader.metal-sub-u32",
            "official.shader.metal-mul-u32",
            "official.shader.metal-xor-u32",
            "official.shader.metal-u32-chain",
            "official.shader:provider-sample=metal-copy-u32",
            "official.shader:provider-sample=metal-add-u32",
            "official.shader:provider-sample=metal-add-pair-u32",
            "official.shader:provider-sample=metal-sub-u32",
            "official.shader:provider-sample=metal-mul-u32",
            "official.shader:provider-sample=metal-xor-u32",
            "official.shader:provider-sample=metal-u32-chain",
            "shader.metal.copy-u32.msl",
            "shader.metal.add-u32.msl",
            "shader.metal.add-pair-u32.msl",
            "shader.metal.sub-u32.msl",
            "shader.metal.mul-u32.msl",
            "shader.metal.xor-u32.msl",
            "code_asset_registration_by_id",
            "provider_kernel_operation={}",
            "render_u32_sample_request_evidence",
            "render_u32_prefixed_request_evidence",
            "render_u32_dependency_edge",
            "render_u32_pair_artifact_binding",
            "nuis-provider-input-binding-v2",
            "tensor-row-major",
            "2x2",
            "msl2.4",
            "provider_adapter_binding_provider_family=metal:apple-silicon-gpu",
            "select_compiled_code_asset_contribution",
            "render_selected_contribution_set_evidence",
            "nuis-module-lowering-plan",
            "provider_request_collection_contract",
            "provider_request_1_input_binding_0_source=dependency",
            "glm:provider-edge:shader.metal.chain.add-u32:output.values->shader.metal.chain.xor-u32:input.values",
            "provider_code_asset_identity_set_count=2",
            "validate_provider_request_evidence",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-device-sample-canonical-provider-family",
        path: "tools/nuis/src/artifact_device_sample_registration.rs",
        required_patterns: &[
            "provider_family",
            "registered_provider_family",
            "provider_sample_registration_id",
            "metadata_selector",
            "selected_registration",
            "evidence_matches_registration",
            "nuis.pixelmagic.gray8-filter",
            "official.shader.metal-copy-u32",
            "official.shader.metal-add-u32",
            "official.shader.metal-add-pair-u32",
            "official.shader.metal-sub-u32",
            "official.shader.metal-mul-u32",
            "official.shader.metal-xor-u32",
            "official.shader.metal-u32-chain",
            "official.shader.vulkan-add-u32",
            "official.shader.vulkan-add-pair-u32",
            "official.shader.vulkan-sub-u32",
            "official.shader.vulkan-mul-u32",
            "official.shader.vulkan-xor-u32",
            "official.shader.vulkan-u32-chain",
            "provider_sample_registration_package=official.shader",
            "vulkan",
            "discrete-or-integrated-gpu",
            "spirv:vulkan-gpu",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-code-asset-selection-set-single-base-case",
        path: "tools/nsdb/src/provider_code_asset_selection_payload.rs",
        required_patterns: &[
            "SINGLE_CONTRACT | SET_CONTRACT",
            "single_item_selection_set_round_trips_as_base_case",
            "compiled_code_asset_selection_count",
            "nuis-provider-code-asset-contribution-selection-set-v1",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-shader-vulkan-provider-demo",
        path: "examples/projects/domains/shader_vulkan_provider_demo/nuis.toml",
        required_patterns: &[
            "shader_vulkan_provider_demo",
            "cpu=cpu.x86_64.sysv64",
            "shader=shader.vulkan.spv1_6",
            "nuis-self-contained-image",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-shader-vulkan-add-provider-demo",
        path: "examples/projects/domains/shader_vulkan_add_provider_demo/nuis.toml",
        required_patterns: &[
            "shader_vulkan_add_provider_demo",
            "official.shader:provider-sample=vulkan-add-u32",
            "shader=shader.vulkan.spv1_6",
            "nuis-self-contained-image",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-shader-vulkan-sub-provider-demo",
        path: "examples/projects/domains/shader_vulkan_sub_provider_demo/nuis.toml",
        required_patterns: &[
            "shader_vulkan_sub_provider_demo",
            "official.shader:provider-sample=vulkan-sub-u32",
            "shader=shader.vulkan.spv1_6",
            "nuis-self-contained-image",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-shader-vulkan-add-pair-provider-demo",
        path: "examples/projects/domains/shader_vulkan_add_pair_provider_demo/nuis.toml",
        required_patterns: &[
            "shader_vulkan_add_pair_provider_demo",
            "official.shader:provider-sample=vulkan-add-pair-u32",
            "shader=shader.vulkan.spv1_6",
            "nuis-self-contained-image",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-shader-vulkan-mul-provider-demo",
        path: "examples/projects/domains/shader_vulkan_mul_provider_demo/nuis.toml",
        required_patterns: &[
            "shader_vulkan_mul_provider_demo",
            "official.shader:provider-sample=vulkan-mul-u32",
            "shader=shader.vulkan.spv1_6",
            "nuis-self-contained-image",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-shader-vulkan-xor-provider-demo",
        path: "examples/projects/domains/shader_vulkan_xor_provider_demo/nuis.toml",
        required_patterns: &[
            "shader_vulkan_xor_provider_demo",
            "official.shader:provider-sample=vulkan-xor-u32",
            "shader=shader.vulkan.spv1_6",
            "nuis-self-contained-image",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-shader-vulkan-chain-provider-demo",
        path: "examples/projects/domains/shader_vulkan_chain_provider_demo/nuis.toml",
        required_patterns: &[
            "shader_vulkan_chain_provider_demo",
            "official.shader:provider-sample=vulkan-u32-chain",
            "shader=shader.vulkan.spv1_6",
            "nuis-self-contained-image",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "official-shader-metal-provider-demo",
        path: "examples/projects/domains/shader_metal_provider_demo/nuis.toml",
        required_patterns: &[
            "shader_metal_provider_demo",
            "official.shader:provider-sample=metal-copy-u32",
            "shader=shader.metal.msl2_4",
            "nuis-self-contained-image",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "official-shader-metal-add-provider-demo",
        path: "examples/projects/domains/shader_metal_add_provider_demo/nuis.toml",
        required_patterns: &[
            "shader_metal_add_provider_demo",
            "official.shader:provider-sample=metal-add-u32",
            "shader=shader.metal.msl2_4",
            "nuis-self-contained-image",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "official-shader-metal-add-pair-provider-demo",
        path: "examples/projects/domains/shader_metal_add_pair_provider_demo/nuis.toml",
        required_patterns: &[
            "shader_metal_add_pair_provider_demo",
            "official.shader:provider-sample=metal-add-pair-u32",
            "shader=shader.metal.msl2_4",
            "nuis-self-contained-image",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "official-shader-metal-sub-provider-demo",
        path: "examples/projects/domains/shader_metal_sub_provider_demo/nuis.toml",
        required_patterns: &[
            "shader_metal_sub_provider_demo",
            "official.shader:provider-sample=metal-sub-u32",
            "shader=shader.metal.msl2_4",
            "nuis-self-contained-image",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "official-shader-metal-mul-provider-demo",
        path: "examples/projects/domains/shader_metal_mul_provider_demo/nuis.toml",
        required_patterns: &[
            "shader_metal_mul_provider_demo",
            "official.shader:provider-sample=metal-mul-u32",
            "shader=shader.metal.msl2_4",
            "nuis-self-contained-image",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "official-shader-metal-xor-provider-demo",
        path: "examples/projects/domains/shader_metal_xor_provider_demo/nuis.toml",
        required_patterns: &[
            "shader_metal_xor_provider_demo",
            "official.shader:provider-sample=metal-xor-u32",
            "shader=shader.metal.msl2_4",
            "nuis-self-contained-image",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "official-shader-metal-chain-provider-demo",
        path: "examples/projects/domains/shader_metal_chain_provider_demo/nuis.toml",
        required_patterns: &[
            "shader_metal_chain_provider_demo",
            "official.shader:provider-sample=metal-u32-chain",
            "shader=shader.metal.msl2_4",
            "nuis-self-contained-image",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "official-shader-metal-provider-smoke",
        path: "tools/nuis/tests/official_galaxy_hetero_smoke/shader_metal.rs",
        required_patterns: &[
            "shader_metal_generated_msl_sample_executes_provider_output",
            "shader_metal_generated_add_msl_sample_executes_provider_output",
            "shader_metal_generated_add_pair_msl_sample_executes_provider_output",
            "shader_metal_generated_sub_msl_sample_executes_provider_output",
            "shader_metal_generated_mul_msl_sample_executes_provider_output",
            "shader_metal_generated_xor_msl_sample_executes_provider_output",
            "shader_metal_generated_chain_msl_sample_executes_provider_graph",
            "shader_metal_provider_demo",
            "shader_metal_add_provider_demo",
            "shader_metal_add_pair_provider_demo",
            "shader_metal_sub_provider_demo",
            "shader_metal_mul_provider_demo",
            "shader_metal_xor_provider_demo",
            "shader_metal_chain_provider_demo",
            "official.shader.metal-copy-u32",
            "provider_sample_registration_id={}",
            "official.shader.metal-add-u32",
            "official.shader.metal-add-pair-u32",
            "official.shader.metal-sub-u32",
            "official.shader.metal-mul-u32",
            "official.shader.metal-xor-u32",
            "official.shader.metal-u32-chain",
            "code_asset_target=msl2.4",
            "nuis-metal-u32-copy-provider-runner-v1",
            "nuis-metal-u32-canonical-provider-runner-v1",
            "0x88201fb960ff6465",
            "0x02f6f7f591bff68f",
            "0xbada6f73928b9f42",
            "input_binding_contract=nuis-provider-input-binding-v2",
            "input_binding_1_row_stride_bytes=8",
            "0x88201fb960ff6465",
            "provider-tensor-u32",
            "native_output_count = \\\"2\\\"",
            "provider_edge_transport_receipt_count = \\\"1\\\"",
            "compiled_code_asset_selection_count = \\\"2\\\"",
            "compiled_code_asset_selection_status",
            "assemble_provider_complete_final_image",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "linux-vulkan-provider-sample-smoke",
        path: "tools/nuis/tests/official_galaxy_hetero_smoke/linux_vulkan.rs",
        required_patterns: &[
            "linux_vulkan_shader_sample_executes_provider_output",
            "linux_vulkan_add_shader_sample_executes_provider_output",
            "linux_vulkan_add_pair_shader_sample_executes_provider_output",
            "linux_vulkan_sub_shader_sample_executes_provider_output",
            "linux_vulkan_mul_shader_sample_executes_provider_output",
            "linux_vulkan_xor_shader_sample_executes_provider_output",
            "linux_vulkan_chain_shader_sample_executes_provider_graph",
            "shader_vulkan_add_provider_demo",
            "shader_vulkan_add_pair_provider_demo",
            "shader_vulkan_sub_provider_demo",
            "shader_vulkan_mul_provider_demo",
            "shader_vulkan_xor_provider_demo",
            "shader_vulkan_chain_provider_demo",
            "execute-provider-samples",
            "materialize-provider-samples",
            "native_output_count = \\\"2\\\"",
            "provider_edge_transport_receipt_count = \\\"1\\\"",
            "compiled_code_asset_selection_count = \\\"2\\\"",
            "assemble_provider_complete_final_image",
            "nsld_final_executable_output_object_package_provider_dispatch_identity_status",
            "nsld_final_executable_output_debugger_api_provider_dispatch_identity_status",
            "spirv.vulkan-gpu.bundle.v1",
            "nuis-vulkan-spirv-provider-execution-v1",
            "0x6ebcdd244b594ee4",
            "0xdce2c1aca0f32707",
            "0xbada6f73928b9f42",
            "input_binding_contract=nuis-provider-input-binding-v2",
            "input_binding_1_row_stride_bytes=8",
            "0x88201fb960ff6465",
            "0x02f6f7f591bff68f",
            "0x88201fb960ff6465",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-provider-input-binding-v2",
        path: "tools/nsdb/src/provider_input_binding.rs",
        required_patterns: &[
            "nuis-provider-input-binding-v1",
            "nuis-provider-input-binding-v2",
            "layout",
            "row_stride_bytes",
            "tensor-row-major",
            "input_binding_matches_buffer",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-shader-typed-output-binding-evidence",
        path: "tools/nuis/src/artifact_device_sample_shader_common.rs",
        required_patterns: &[
            "nuis-provider-output-binding-v2",
            "output_binding_0_layout",
            "output_binding_0_row_stride_bytes",
            "args.buffer_layout",
            "args.row_stride_bytes",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-provider-input-binding-v2-payload",
        path: "tools/nsdb/src/provider_request_payload.rs",
        required_patterns: &[
            "PROVIDER_INPUT_BINDING_CONTRACT",
            "binding.layout",
            "row_stride_bytes",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-provider-output-binding-v2",
        path: "tools/nsdb/src/provider_output_binding.rs",
        required_patterns: &[
            "nuis-provider-output-binding-v1",
            "nuis-provider-output-binding-v2",
            "layout",
            "row_stride_bytes",
            "tensor-row-major",
            "output_binding_matches_buffer",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-provider-output-binding-v2-payload",
        path: "tools/nsdb/src/provider_request_payload.rs",
        required_patterns: &[
            "PROVIDER_OUTPUT_BINDING_CONTRACT",
            "binding.layout",
            "binding.row_stride_bytes",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-vulkan-final-image-dispatch-smoke",
        path: "tools/nsld/src/main_container_metadata_binding_tests.rs",
        required_patterns: &[
            "final_image_loader_verifies_vulkan_provider_dispatch_without_backend_branch",
            "spirv:vulkan-gpu",
            "spirv.vulkan-gpu.bundle.v1",
            "spirv.vulkan.real-device",
            "spirv.vulkan.fake-device",
            "fnv1a64:f8efa211643f7bcd",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-vulkan-completion-dispatch-authority",
        path: "tools/nsdb/src/provider_completion_dispatch.rs",
        required_patterns: &[
            "vulkan_completion_authority_is_bound_from_open_final_image_dispatch",
            "vulkan_completion_authority_rejects_runner_identity_drift",
            "spirv:vulkan-gpu",
            "spirv.vulkan-gpu.bundle.v1",
            "provider-completion-dispatch:runner-drift",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-code-asset-selection-set-base-case",
        path: "tools/nsld/src/final_executable_output_code_asset.rs",
        required_patterns: &[
            "nuis-provider-code-asset-contribution-selection-set-v1",
            "selected_count == 1",
            "validates_verified_or_not_applicable_selection",
        ],
    },
];
