use crate::dev_tensor_drift::DevTensorDriftCheckSpec;

pub(super) const CHECKS: &[DevTensorDriftCheckSpec] = &[
    DevTensorDriftCheckSpec {
        id: "native-conditional-return-comparison-constant-fold-preserves-bool-kind",
        path: "tools/nuisc/src/optimize_expr.rs",
        required_patterns: &[
            "fold_int_binary(op, *lhs_value, *rhs_value)",
            "Comparisons stay bool through bindings and branch folding",
            "NirExpr::Bool(folded != 0)",
            "NirExpr::Int(folded)",
            "return (value, true)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-conditional-return-comparison-constant-fold-type-and-effect-regressions",
        path: "tools/nuisc/src/optimize_tests.rs",
        required_patterns: &[
            "constant_comparisons_keep_bool_kind_through_aliases_and_struct_fields",
            "constant_comparisons_select_typed_branches_without_changing_selected_effects",
            "vec![NirStmt::Return(Some(NirExpr::Bool(true)))]",
            "(i64::MIN, i64::MAX)",
            "(i64::MAX, i64::MIN)",
            "if selected { yes } else { no }",
            "crate::pipeline::compile_source(source).unwrap()",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-conditional-return-comparison-typed-atoms-and-bounded-normalization",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_predicates.rs",
        required_patterns: &[
            "enum Value",
            "Self::Compared(_) => None",
            "pub(super) fn from_parent(scope: &Scope)",
            "ty == &scalar_type(\"bool\")",
            "ty == &scalar_type(\"i64\")",
            "NirExpr::Var(name) => self.0.get(name).cloned()",
            "let (lhs, left_kind) = left.atom()?",
            "let (rhs, right_kind) = right.atom()?",
            "control_values::binary_type(*op, scalar_type(left_kind), scalar_type(right_kind))",
            "normalized value stays at most three nodes across alias chains",
            "_ => None",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-conditional-return-comparison-after-type-proof-before-clone-and-seed",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_fallthrough.rs",
        required_patterns: &[
            "mod comparison_tests;",
            "terminal::partial_inputs(body, result, scope, catalog, layouts)?",
            "let aliases = predicates::Values::from_parent(scope)",
            "let ready = readiness(body, &aliases, &mut leaves)?",
            "let mut aliases = aliases.clone()",
            "aliases.bind(name, value)",
            "aliases.boolean(condition)?",
            "let mut body = body.to_vec()",
            "seed_fallthroughs(&mut body, result)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-conditional-return-comparison-reference-order-and-value-exit-proofs",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_comparison_tests.rs",
        required_patterns: &[
            "conditional_return_comparisons_keep_all_signed_operators_selected_calls_and_checks",
            "assert_eq!(cases, 216)",
            "conditional_return_comparisons_keep_boolean_equality_literals_and_parent_atoms",
            "assert_eq!(cases, 192)",
            "conditional_return_comparisons_keep_zero_returns_and_full_width_signed_atoms",
            "conditional_return_comparisons_preserve_prefix_checks_early_exits_and_fallible_parent_suffixes",
            "conditional_return_comparisons_keep_nested_sibling_comparisons_and_current_parent_versions",
            "conditional_return_comparisons_keep_original_bodies_captures_hygiene_and_idempotence",
            "assert_seed_after_work(original, seeded)",
            "assert_eq!(module, once)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-conditional-return-comparison-no-dag-expansion-and-non-total-vetoes",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_comparison_tests.rs",
        required_patterns: &[
            "conditional_return_comparisons_bound_alias_expansion_and_retain_non_total_vetoes",
            "for count in [30, 31]",
            "let decision = divisor > 0; let selected = decision == true",
            "let a0 = gate == true; let a1 = a0 == a0; let a2 = a1 == a1",
            "let input = divisor / divisor",
            "let input = packet.value",
            "assert_eq!(module, before",
            "yir_lower_llvm::emit_module(&compiled.yir).unwrap()",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-conditional-return-comparison-default-source-aot-proof",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_comparison_native_tests.rs",
        required_patterns: &[
            "conditional_return_comparisons_execute_default_aot_selected_calls_real_exits_and_traps",
            "conditional_return_comparisons_execute_default_aot_zero_returns_and_continuation_checks",
            "tests::native::run",
            "Some(\"99\\n77\\n19\")",
            "Some(\"99\\n0\")",
            "run(&source, expected)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-conditional-return-comparison-documentation-boundary",
        path: "docs/reference/nuis-native-scalar-loop-snapshots-v1.md",
        required_patterns: &[
            "## Total Comparisons For Exit Readiness",
            "at most three expression nodes",
            "Other inline computed branch conditions remain outside this proof",
            "Readiness may repeat only the proven total comparison",
            "one extra binding rejects unchanged",
            "Nine conditional-return tests cover 503 runtime source cases and 1006 ordinary/",
            "1852/1852 passing drift checks",
            "Logical outer gates and other inline conditions",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-conditional-return-comparison-tensor-boundary",
        path: "tools/nuis/src/dev_tensor_data.rs",
        required_patterns: &[
            "Total comparison-readiness follow-up:",
            "Total comparison-readiness acceptance:",
            "normalized facts stay at most three nodes",
            "no calls, arithmetic or checks are replayed",
            "Other computed/call-derived exit predicates, intermediate branch suffixes",
            "conditional_return_comparisons conditional_return_aliases",
            "active/86 remains unchanged",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-conditional-return-alias-atoms-after-bounded-type-proof",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_fallthrough.rs",
        required_patterns: &[
            "mod alias_tests;",
            "terminal::partial_inputs(body, result, scope, catalog, layouts)?",
            "let aliases = predicates::Values::from_parent(scope)",
            "let ready = readiness(body, &aliases, &mut leaves)?",
            "let mut body = body.to_vec()",
            "seed_fallthroughs(&mut body, result)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-conditional-return-alias-lexical-scopes-and-no-initializer-replay",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_fallthrough.rs",
        required_patterns: &[
            "let mut aliases = aliases.clone()",
            "aliases.bind(name, value)",
            "aliases.boolean(condition)?",
            "readiness(then_body, &aliases, leaves)?",
            "readiness(else_body, &aliases, leaves)?",
            "Flatten only proven total values, never replay calls or checked work",
            "has_return: leaves.0",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-conditional-return-alias-reference-order-and-zero-exit-proofs",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_alias_tests.rs",
        required_patterns: &[
            "conditional_return_aliases_keep_selected_calls_short_circuit_and_actual_exits",
            "assert_eq!(cases, 144)",
            "conditional_return_aliases_keep_literal_atoms_and_current_parent_binding_versions",
            "conditional_return_aliases_distinguish_zero_results_and_preserve_selected_prefix_checks",
            "conditional_return_aliases_do_not_speculate_parent_suffix_after_false_returns",
            "conditional_return_aliases_keep_nested_sibling_alias_identities_independent",
            "conditional_return_aliases_flatten_readiness_only_keep_lexical_bodies_and_idempotence",
            "assert_seed_after_work(then_body, yes)",
            "assert_eq!(module, once)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-conditional-return-alias-computed-veto-and-shared-budget-proofs",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_alias_tests.rs",
        required_patterns: &[
            "conditional_return_aliases_share_budgets_before_alias_proof_and_leave_rejections_unchanged",
            "for count in [30, 31]",
            "let selected: bool = nested == true",
            "let first = helper(produce(divisor)); let selected = first",
            "assert_eq!(module, before",
            "yir_lower_llvm::emit_module(&compiled.yir).unwrap()",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-conditional-return-alias-default-source-aot-proof",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_alias_native_tests.rs",
        required_patterns: &[
            "conditional_return_aliases_execute_default_aot_selected_atoms_calls_and_traps",
            "conditional_return_aliases_execute_default_aot_zero_return_and_continuation_checks",
            "tests::native::run",
            "Some(\"99\\n77\\n19\")",
            "Some(\"99\\n0\")",
            "run(&source, expected)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-conditional-return-alias-documentation-boundary",
        path: "docs/reference/nuis-native-scalar-loop-snapshots-v1.md",
        required_patterns: &[
            "## Local Atom Aliases For Exit Readiness",
            "A rejected readiness proof leaves the candidate unchanged",
            "Exact 30-binding plus branch/return trees fit",
            "Nine compiler tests cover 200 runtime source cases and 400 reference executions",
            "1843/1843 passing drift checks",
            "Logical outer gates and other inline conditions",
            "not public/FFI ABI expansion",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-conditional-return-alias-tensor-boundary",
        path: "tools/nuis/src/dev_tensor_data.rs",
        required_patterns: &[
            "Local atom-alias readiness follow-up:",
            "Local atom-alias readiness acceptance:",
            "original local work stays selected without replaying calls or checks",
            "Other computed/call-derived exit predicates, intermediate branch suffixes",
            "conditional_return_aliases conditional_root_values",
            "active/86 remains unchanged",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-conditional-returns-exact-kinds-and-local-window",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns.rs",
        required_patterns: &[
            "function.return_type.as_ref().filter(|ty| scalar(ty))",
            "control_roots.contains(&function.name)",
            "function.is_async",
            "!function.generic_params.is_empty()",
            "!function.where_bounds.is_empty()",
            "Do not lift work out of loops or an enclosing source branch",
            "[NirStmt::Return(Some(value))]",
            "== Some(result)",
            "!scope.get(name).is_some_and(scalar)",
            "ty == &scalar_type(\"bool\") || ty == &scalar_type(\"i64\")",
            "conditional_values::prefix::computed_logical_root(value)",
            "scope.remove(name)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-conditional-returns-complete-values-and-ready-parent-exit",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns.rs",
        required_patterns: &[
            "Some((Some(body.to_vec()), NirExpr::Bool(true)))",
            "branches::fresh_name(\"__nuis_return_condition\", &mut parameter_names)",
            "let both = plan.yes.is_some() && plan.no.is_some()",
            "NirExpr::Var(param.name.clone())",
            "plan.yes.unwrap_or_else(|| skipped.clone())",
            "plan.no.unwrap_or(skipped)",
            "branches::collect_bindings(body, &mut parameter_names)",
            "value: plan.condition",
            "output.push(NirStmt::Return(Some(call)))",
            "NirStmt::Return(Some(NirExpr::Var(value)))",
            "fallible computation. Its existing speculation barrier stays intact",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-conditional-returns-shared-budget-and-pipeline",
        path: "tools/nuisc/src/lowering/buffer_loop_outline.rs",
        required_patterns: &[
            "mod conditional_returns;",
            "let mut selections = conditional_returns::outline(",
            "selections.extend(conditional_values::outline(",
            "if !selections.is_empty()",
            "scalar_helpers::collect_typed_values(module, &value_layouts, &control_catalog)",
            "scalar_control::outline(",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-conditional-returns-retain-fallible-speculation-barrier",
        path: "tools/nuisc/src/lowering/if_lowering.rs",
        required_patterns: &[
            "The remaining shortcuts may materialize both branches before selecting",
            "speculation::block_has_checked_arithmetic(branch, &state.checked_arithmetic_helpers)",
            "conditional fallible return requires guarded helper lowering",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-conditional-returns-execution-identity-and-veto-proofs",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_tests.rs",
        required_patterns: &[
            "conditional_returns_preserve_parent_effects_two_guards_and_actual_exits",
            "conditional_returns_keep_i64_checked_work_and_current_binding_versions",
            "conditional_returns_keep_current_inferred_bool_versions_after_rebinding",
            "conditional_returns_preserve_complete_expressions_parent_tail_and_idempotence",
            "conditional_returns_keep_loop_nested_effect_resource_kind_and_work_vetoes",
            "yir.edges.reverse()",
            "YirFunctionRole::Entry",
            "usize::from(rhs)",
            "event.contains(\"] helper(\")",
            "let divisor = divisor + 2",
            "assert_eq!(module, once)",
            "assert_eq!(module, before",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-conditional-returns-default-aot-lazy-effects-and-traps",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_native_tests.rs",
        required_patterns: &[
            "conditional_returns_execute_default_source_parent_effects_exits_and_native_traps",
            "Default source compilation, with no private projection registration",
            "Some(\"99\\n77\\n19\")",
            "Some(\"99\\n11\")",
            "Some(\"19\")",
            "Duration::from_secs(10)",
            "child.kill()",
            "child.wait()",
            "Some(4 | 5)",
            "fs::remove_dir_all",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-conditional-returns-documentation-boundary",
        path: "docs/reference/nuis-native-scalar-loop-snapshots-v1.md",
        required_patterns: &[
            "## Effectful-Parent Conditional Returns",
            "210 runtime source cases and 420 reference executions",
            "the original speculation barrier remains intact",
            "Pure control roots retain their existing whole-function route",
            "not broader private projection",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-conditional-return-prefixes-fresh-typed-whole-arm-admission",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_prefix.rs",
        required_patterns: &[
            "conditional_values::prefix::return_body(body)",
            "if inner.contains_key(name)",
            "control_values::value_type(value, &inner, catalog, layouts)?",
            "declared.is_some_and(|declared| declared != &ty)",
            "local_names.insert(name.clone())",
            "inputs.retain(|name| !local_names.contains(name))",
            "!scope.get(name).is_some_and(scalar)",
            "body: body.to_vec()",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-conditional-return-prefixes-shared-work-depth-and-logical-boundaries",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_values_prefix.rs",
        required_patterns: &[
            "fn return_body(body: &[NirStmt])",
            "locals.is_empty() || body.len() > 32",
            "let mut work = 4096usize",
            "depth >= 64 || work == 0",
            "pending.push((value, 0, true))",
            "!logical_root",
            "depth != 0",
            "NirExpr::Bool(_) | NirExpr::Var(_)",
            "expression_roots(pending)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-conditional-return-prefixes-execution-hygiene-veto-and-budget-proofs",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_prefix_tests.rs",
        required_patterns: &[
            "conditional_return_prefixes_preserve_local_work_two_guards_and_parent_exits",
            "conditional_return_prefixes_preserve_i64_producers_and_unused_checks",
            "conditional_return_prefixes_preserve_complete_arm_identity_capture_hygiene_and_idempotence",
            "conditional_return_prefixes_retain_outer_rebind_effect_kind_scope_and_shape_vetoes",
            "conditional_return_prefixes_bound_whole_arm_work_and_statement_depth_before_cloning",
            "matches!(kind, \"packet\" | \"unused\")",
            "[\"let\", \"const\", \"packet\", \"unused\", \"inferred\", \"hygiene\"]",
            "for count in [31, 32]",
            "return_body(&total(2))",
            "return_body(&total(3))",
            "assert_eq!(module, before",
            "assert_eq!(module, once)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-conditional-return-prefixes-default-aot-shared-native-harness",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_prefix_native_tests.rs",
        required_patterns: &[
            "conditional_return_prefixes_execute_default_source_unused_checks_local_records_and_native_traps",
            "tests::native::run",
            "Some(\"99\\n77\\n19\")",
            "Some(\"99\\n11\")",
            "Some(\"19\")",
            "run(&source, expected)",
            "deadline, kill/reap, native trap and scratch-cleanup probe",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-conditional-return-prefixes-documentation-scope",
        path: "docs/reference/nuis-native-scalar-loop-snapshots-v1.md",
        required_patterns: &[
            "## Pure Prefixes Before Conditional Returns",
            "468 source cases and 936 reference executions",
            "32 statements including the final return",
            "No outer-state rebinding",
            "prefix checks still run when the inner RHS is skipped",
            "not resource/aggregate capture transport",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-conditional-return-prefixes-tensor-scope",
        path: "tools/nuis/src/dev_tensor_data.rs",
        required_patterns: &[
            "Pure conditional-return prefix follow-up:",
            "468 source cases and 936 reference executions",
            "fresh typed locals stay inside their selected return arm",
            "active/86 remains unchanged",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-conditional-returns-tensor-and-registration",
        path: "tools/nuis/src/dev_tensor_data.rs",
        required_patterns: &[
            "Effectful-parent conditional-return follow-up:",
            "parent effects and exits remain in place",
            "210 source cases and 420 reference executions",
            "active/86 remains unchanged",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-conditional-return-terminal-trees-complete-fresh-lexical-admission",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_terminal.rs",
        required_patterns: &[
            "if !bounded(body)",
            "if inner.contains_key(name)",
            "declared.is_some_and(|declared| declared != &ty)",
            "control_values::value_type(condition, &inner, catalog, layouts).as_ref()",
            "== Some(&scalar_type(\"bool\"))",
            "validate(\n                then_body,\n                inner.clone(),",
            "validate(\n                else_body,\n                inner,",
            "outer.contains_key(name)",
            "!scope.get(name).is_some_and(scalar)",
            "body: body.to_vec()",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-conditional-return-terminal-trees-shared-preflight-budgets",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_terminal.rs",
        required_patterns: &[
            "let mut statements = 32usize",
            "bounded_tree(body, false)",
            "depth >= 64 || body.len() > statements",
            "if body.is_empty()",
            "if !allow_fallthrough",
            "statements -= body.len()",
            "split_tail(body, allow_fallthrough)",
            "Some(NirStmt::Return(Some(value))) => expressions.push((value, 0, true))",
            "(then_body.as_slice(), depth + 1)",
            "(else_body.as_slice(), depth + 1)",
            "(nested || allow_fallthrough)",
            "conditional_values::prefix::computed_expression_roots(expressions)",
            "Every leaf returns; no parent continuation is copied into the helper",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-conditional-return-terminal-trees-pipeline-independent-fallback",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns.rs",
        required_patterns: &[
            "mod terminal;",
            "prefix::prepare(body, result, scope, catalog, layouts)",
            "terminal::prepare(body, result, scope, catalog, layouts)",
            "branches::collect_bindings(body, &mut parameter_names)",
            "function.is_async",
            "control_roots.contains(&function.name)",
            "fallible computation. Its existing speculation barrier stays intact",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-conditional-return-terminal-trees-behavior-identity-veto-and-budget-proof",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_terminal_tests.rs",
        required_patterns: &[
            "conditional_return_terminal_trees_preserve_three_guards_prefix_checks_and_actual_exits",
            "conditional_return_terminal_trees_preserve_selected_i64_leaf_checks",
            "conditional_return_terminal_trees_keep_complete_arms_scalar_captures_hygiene_and_idempotence",
            "conditional_return_terminal_trees_retain_fallthrough_effect_rebind_scope_kind_and_capture_vetoes",
            "conditional_return_terminal_trees_share_statement_expression_and_depth_budgets",
            "conditional_return_terminal_trees_keep_deep_lexical_paths_and_sibling_local_identity",
            "[\"divisor\", \"gate\", \"nested\"]",
            "for count in [29, 30]",
            "assert!(bounded(&exact))",
            "assert!(!bounded(&excess))",
            "assert_eq!(module, before",
            "assert_eq!(module, once)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-conditional-return-terminal-trees-default-source-aot-proof",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_terminal_native_tests.rs",
        required_patterns: &[
            "conditional_return_terminal_trees_execute_default_aot_skipped_leaf_and_prefix_traps",
            "tests::native::run",
            "Some(\"99\\n77\\n19\")",
            "Some(\"99\\n11\")",
            "Some(\"19\")",
            "run(&source, expected)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-conditional-return-terminal-trees-documentation-boundary",
        path: "docs/reference/nuis-native-scalar-loop-snapshots-v1.md",
        required_patterns: &[
            "## Pure Terminal Return Trees",
            "every leaf must return",
            "32 statements across the entire tree",
            "507 runtime source cases and 1014 reference executions",
            "Parent effects and the continuation suffix remain outside",
            "not general nested effectful return closure",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-conditional-return-terminal-trees-tensor-boundary",
        path: "tools/nuis/src/dev_tensor_data.rs",
        required_patterns: &[
            "Pure terminal-return tree follow-up:",
            "507 runtime source cases and 1014 reference executions",
            "every leaf returns without copying the parent suffix",
            "active/86 remains unchanged",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-conditional-return-fallthrough-stable-parent-predicates-and-shared-preflight",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_terminal.rs",
        required_patterns: &[
            "pub(super) fn partial_inputs(",
            "if !bounded_tree(body, true)",
            "return allow_fallthrough.then_some(())",
            "The caller must separately prove replayable facts or store an exit signal",
            "let mut statements = 32usize",
            "conditional_values::prefix::computed_expression_roots(expressions)",
            "if inner.contains_key(name)",
            "declared.is_some_and(|declared| declared != &ty)",
            "scope.get(name).is_some_and(scalar)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-conditional-return-fallthrough-readiness-and-seed-separation",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_fallthrough.rs",
        required_patterns: &[
            "terminal::partial_inputs(body, result, scope, catalog, layouts)?",
            "if !leaves.1",
            "has_return: leaves.0",
            "let mut body = body.to_vec()",
            "seed_fallthroughs(&mut body, result)",
            "NirExpr::Bool(false)",
            "NirExpr::Int(0)",
            "binary(NirBinaryOp::And, condition.clone(), yes)",
            "binary(NirBinaryOp::Eq, condition, NirExpr::Bool(false))",
            "a real return may itself be false/zero",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-conditional-return-fallthrough-value-before-independent-parent-exit",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns.rs",
        required_patterns: &[
            "mod fallthrough;",
            "fallthrough::prepare(body, result, scope, catalog, layouts)",
            "readiness: partial.then_some((yes_ready, no_ready))",
            "if let Some((yes, no)) = plan.readiness",
            "branches::fresh_name(\"__nuis_return_exit\", bindings)",
            "value: call,",
            "value: fallthrough::select(NirExpr::Var(condition), yes, no)",
            "condition: NirExpr::Var(ready)",
            "NirStmt::Return(Some(NirExpr::Var(value)))",
            "else if both",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-conditional-return-fallthrough-reference-identity-veto-and-budget-proofs",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_fallthrough_tests.rs",
        required_patterns: &[
            "conditional_return_fallthrough_trees_distinguish_false_returns_from_continuations",
            "conditional_return_fallthrough_trees_keep_independent_deep_and_outer_arm_exit_choices",
            "conditional_return_fallthrough_trees_distinguish_zero_returns_and_keep_literal_and_current_gates",
            "conditional_return_fallthrough_trees_seed_only_empty_leaves_keep_parent_tail_and_hygiene",
            "conditional_return_fallthrough_trees_veto_computed_exit_decisions_effects_rebinds_and_logical_prefixes",
            "conditional_return_fallthrough_trees_share_preclone_statement_expression_and_depth_budgets",
            "conditional_return_fallthrough_readiness_is_total_boolean_selection_not_value_selection",
            "assert_seed_only(old, new)",
            "assert!(total_readiness(value))",
            "for count in [30, 31]",
            "assert_eq!(module, once)",
            "assert_eq!(module, before",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-conditional-return-fallthrough-default-source-aot-and-trap-proofs",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_fallthrough_native_tests.rs",
        required_patterns: &[
            "conditional_return_fallthrough_trees_execute_default_aot_false_exits_and_prefix_traps",
            "conditional_return_fallthrough_trees_execute_default_aot_zero_returns_not_seed_exits",
            "tests::native::run",
            "Some(\"99\\n77\\n19\")",
            "Some(\"99\\n19\")",
            "Some(\"99\\n0\")",
            "Some(\"19\")",
            "run(&source, expected)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-conditional-return-fallthrough-documentation-boundary",
        path: "docs/reference/nuis-native-scalar-loop-snapshots-v1.md",
        required_patterns: &[
            "## Pure Fallthrough Return Trees",
            "600 runtime source cases and 1200 reference executions",
            "The return value and exit readiness are independent",
            "No parent suffix is copied",
            "Fourteen default-source AOT variants",
            "Logical outer gates and other inline conditions",
            "not general nonterminal/effectful return closure",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-conditional-return-fallthrough-retain-original-root-case-and-rejection-boundaries",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_values_roots_tests.rs",
        required_patterns: &[
            "conditional_root_values_retain_effectful_nested_return_speculation_rejection",
            "crate::pipeline::compile_source(&admitted).unwrap()",
            "yir_lower_llvm::emit_module(&compiled.yir).unwrap()",
            "let selected: bool = helper(produce(divisor));",
            "Stored signals admit the pure local predicate, not branch effects",
            "unproven branch-effect return must stay rejected",
            "conditional fallible return requires guarded helper lowering",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-conditional-return-fallthrough-tensor-boundary",
        path: "tools/nuis/src/dev_tensor_data.rs",
        required_patterns: &[
            "Pure fallthrough-return tree follow-up:",
            "600 runtime source cases and 1200 reference executions",
            "return value and exit readiness remaining independent",
            "active/86 remains unchanged",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-conditional-return-continuations-whole-leaf-preflight-and-exact-fresh-types",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_terminal.rs",
        required_patterns: &[
            "fn split_tail(body: &[NirStmt], allow_fallthrough: bool)",
            "_ if allow_fallthrough => Some((body, None))",
            "let Some((locals, last)) = split_tail(body, allow_fallthrough)",
            "NirStmt::Let { value, .. } | NirStmt::Const { value, .. } => value",
            "let (locals, last) = split_tail(body, allow_fallthrough)?",
            "if inner.contains_key(name)",
            "declared.is_some_and(|declared| declared != &ty)",
            "None => return allow_fallthrough.then_some(())",
            "bounded_tree(body, false)",
            "let mut statements = 32usize",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-conditional-return-continuations-require-an-original-return",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns.rs",
        required_patterns: &[
            "let mut has_return = false",
            "has_return = true",
            "has_return |= arm.has_return",
            "if !has_return",
            "readiness: partial.then_some((yes_ready, no_ready))",
            "control_roots.contains(&function.name)",
            "!scope.get(name).is_some_and(scalar)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-conditional-return-continuations-seed-after-original-work",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_fallthrough.rs",
        required_patterns: &[
            "None | Some(NirStmt::Let { .. } | NirStmt::Const { .. })",
            "match body.last_mut()",
            "Some(NirStmt::Return(Some(_))) => {}",
            "seed_fallthroughs(then_body, result)",
            "seed_fallthroughs(else_body, result)",
            "body.push(NirStmt::Return(Some(if result",
            "has_return: leaves.0",
            "a real return may itself be false/zero",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-conditional-return-continuations-execution-identity-veto-and-budget-proof",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_continuation_tests.rs",
        required_patterns: &[
            "conditional_return_continuations_keep_selected_pure_work_and_parent_suffix_order",
            "conditional_return_continuations_keep_zero_returns_and_do_not_speculate_the_parent_suffix",
            "conditional_return_continuations_keep_all_fallthrough_subtrees_and_sibling_scopes",
            "conditional_return_continuations_append_only_leaf_seeds_preserve_captures_hygiene_and_idempotence",
            "conditional_return_continuations_retain_effect_rebind_scope_kind_capture_and_no_return_vetoes",
            "conditional_return_continuations_bound_all_original_leaf_work_before_synthesizing_seeds",
            "assert_seed_after_work(original, seeded)",
            "assert!(!accepted.has_return)",
            "assert_eq!(accepted.ready, NirExpr::Bool(false))",
            "assert_eq!(module, before",
            "assert_eq!(module, once)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-conditional-return-continuations-default-source-aot-proof",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_continuation_native_tests.rs",
        required_patterns: &[
            "conditional_return_continuations_execute_default_aot_selected_unused_work_and_real_exits",
            "conditional_return_continuations_execute_default_aot_zero_results_and_continuation_checks",
            "tests::native::run",
            "suffix_source(returned, false)",
            "Some(\"99\\n77\\n19\")",
            "Some(\"99\\n0\")",
            "Some(\"19\")",
            "run(&source, expected)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-conditional-return-continuations-documentation-boundary",
        path: "docs/reference/nuis-native-scalar-loop-snapshots-v1.md",
        required_patterns: &[
            "## Pure Work Before Continuation Leaves",
            "652 runtime source cases and 1304 reference executions",
            "At least one original return leaf",
            "the seed is\nappended after all original leaf work",
            "Sixteen default-source AOT variants",
            "not effectful continuation closure",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-conditional-return-continuations-tensor-boundary",
        path: "tools/nuis/src/dev_tensor_data.rs",
        required_patterns: &[
            "Pure continuation-leaf work follow-up:",
            "652 runtime source cases and 1304 reference executions",
            "fresh pure continuation work remains selected",
            "at least one original return leaf",
            "active/86 remains unchanged",
        ],
    },
];
