use crate::dev_tensor_drift::DevTensorDriftCheckSpec;

pub(super) const CHECKS: &[DevTensorDriftCheckSpec] = &[
    DevTensorDriftCheckSpec {
        id: "native-computed-logical-gates-shared-whole-root-budget-and-independent-modes",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_values_prefix.rs",
        required_patterns: &[
            "roots(pending, false)",
            "fn computed_logical_root",
            "computed_expression_roots(vec![(expr, 0, true)])",
            "roots(pending, true)",
            "let mut work = 4096usize",
            "if depth >= 64 || work == 0",
            "!logical_root",
            "(!computed_gate && depth != 0)",
            "!computed_gate",
            "(lhs.as_ref(), depth + 1, false)",
            "(rhs.as_ref(), depth + 1, false)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-computed-logical-gates-first-argument-and-selected-rhs-contract",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_values_logical.rs",
        required_patterns: &[
            "!prefix::computed_logical_root(condition)",
            "control_values::value_type(condition, scope, self.catalog, self.layouts)?",
            "Prove the complete original tree before allocating names or helpers",
            "control_values::collect_inputs(rhs, &mut inputs)",
            "body: vec![NirStmt::Return(Some(right))]",
            "self.extract(left, yes, no, scope, false)",
            "evaluated once as argument zero",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-computed-logical-gates-original-site-entry-and-unchanged-arm-authority",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_entry.rs",
        required_patterns: &[
            "single_edge(condition, scope)",
            "computed_edge(condition)",
            "== Some(scalar_type(\"bool\"))",
            "fn computed_edge",
            "conditional_values::prefix::computed_logical_root(condition)",
            "roots retain the atom-only mode",
            "predicate(lhs, scope)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-computed-logical-gates-reference-left-rhs-entry-order-and-composition",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_computed_gates_tests.rs",
        required_patterns: &[
            "conditional_computed_gates_preserve_value_roots_left_checks_and_lazy_rhs_once",
            "assert_eq!(cases, 256)",
            "conditional_computed_gates_compose_saved_entries_complete_partial_and_suffix_returns",
            "assert_eq!(cases, 720)",
            "conditional_computed_gates_keep_parent_records_current_rebinding_total_rhs_and_real_zero_exits",
            "assert_eq!(cases, 64)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-computed-logical-gates-structure-boundaries-and-isolated-vetoes",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_computed_gates_tests.rs",
        required_patterns: &[
            "conditional_computed_gates_keep_original_gate_first_selected_rhs_and_parent_only_record_transport",
            "assert_eq!(&args[0], lhs.as_ref())",
            "assert_eq!(module, once)",
            "conditional_computed_gates_share_whole_root_work_depth_before_inference_and_keep_arm_modes_separate",
            "4093 argument nodes + call + logical root + RHS atom = 4096",
            "for count in [61, 62]",
            "conditional_computed_gates_retain_nested_effect_type_loop_capture_vetoes_and_internal_arm_admission",
            "assert!(!outline_values(&mut module, true).is_empty())",
            "assert_eq!(module, before)",
            "for atom_gate in [false, true]",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-computed-logical-gates-default-source-binaries-and-left-traps",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_computed_gates_native_tests.rs",
        required_patterns: &[
            "conditional_computed_gates_execute_default_aot_value_roots_and_original_left_failures",
            "conditional_computed_gates_execute_default_aot_entries_signals_parent_records_and_zero_exits",
            "use super::super::super::tests::native::run",
            "Some(\"99\\n0\")",
            "run(&source, expected)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-computed-logical-gates-documented-scope-and-current-boundaries",
        path: "docs/reference/nuis-native-computed-logical-gates-v1.md",
        required_patterns: &[
            "# Native Computed Logical Gates",
            "Eight new compiler tests cover 1040 runtime source cases and 2080 ordinary/reversed",
            "Three older suites retain",
            "entire root must fit 4096 nodes and depth below",
            "original internal return conditions",
            "The original checkpoint recorded `active/92`",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-computed-logical-gates-tensor-evidence-receipt-and-residual-boundary",
        path: "tools/nuis/src/dev_tensor_data.rs",
        required_patterns: &[
            "Computed logical-gate follow-up:",
            "Computed logical-gate acceptance:",
            "Previous logical-arm-root checkpoint:",
            "1040 runtime source cases and 2080 ordinary/reversed reference executions",
            "conditional_computed_gates",
            "active/92",
            "computed internal return-arm gates",
        ],
    },
];
