use crate::dev_tensor_drift::DevTensorDriftCheckSpec;

pub(crate) const DEV_TENSOR_RUNTIME_BOOTSTRAP_EVIDENCE_DRIFT_CHECKS:
    &[DevTensorDriftCheckSpec] = &[
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-stage-handoff-v2-contract",
        path: "docs/reference/nuis-compiler-stage-handoff-v2.toml",
        required_patterns: &[
            "nuis-compiler-stage-handoff-v2",
            "nuis-compiler-derived-stage-selection-v1",
            "reversible-derived-stage-selection-no-replacement",
            "every-registered-transformation-has-one-same-ordinal-semantic-comparison",
            "selection-order-is-registration-order-without-stage-specific-driver-logic",
            "registered-ast-structured-record-codec-v1",
            "registered-nir-structured-record-codec-v1",
            "two-of-two-reversible-semantic-equivalence",
            "selection-does-not-authorize-canonical-stage-or-compiler-replacement",
            "replacement_authorized = false",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-stage-handoff-v2-artifact",
        path: "crates/nuis-artifact/src/compiler_stage_handoff_v2.rs",
        required_patterns: &[
            "COMPILER_STAGE_HANDOFF_V2_PROTOCOL",
            "CompilerStageSelectionRecord",
            "build_compiler_stage_handoff_v2",
            "read_compiler_stage_handoff_v2",
            "verify_compiler_stage_handoff_v2",
            "selection_for_stage",
            "replacement_authorized: false",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-stage-handoff-v2-registry-regression",
        path: "crates/nuis-artifact/src/compiler_stage_handoff_v2_tests.rs",
        required_patterns: &[
            "selects_every_registered_stage_without_stage_specific_protocol_logic",
            "CompilerStageKind::Ast",
            "CompilerStageKind::Nir",
            "selection_count, 2",
            "reader_replays_all_sibling_evidence_and_rejects_tampering",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-component-representation-differential-contract",
        path: "docs/reference/nuis-compiler-component-representation-differential-v1.toml",
        required_patterns: &[
            "nuis-compiler-component-representation-differential-v1",
            "nuis-compiler-selected-reversible-representation-comparison-v1",
            "every-registered-v2-selection-in-registration-order",
            "current_production_stages = [\"ast\", \"nir\"]",
            "current_comparison_count = 2",
            "no-stage-specific-selection-branch-is-permitted",
            "representation_report_bound_by_generation_one_aggregate = false",
            "replacement_authorized = false",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-component-representation-differential-artifact",
        path: "crates/nuis-artifact/src/compiler_component_representation_diff.rs",
        required_patterns: &[
            "CompilerComponentRepresentationDifferential",
            "build_compiler_component_representation_differential",
            "compare_compiler_component_representation_paths",
            "candidate_selected_payload_sha256",
            "candidate_recovered_payload_sha256",
            "replacement_authorized: false",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-component-representation-differential-regression",
        path: "crates/nuis-artifact/src/compiler_component_representation_diff_tests.rs",
        required_patterns: &[
            "registered_representations_are_compared_without_stage_specific_branches",
            "CompilerStageKind::Ast",
            "CompilerStageKind::Nir",
            "canonical_drift_remains_blocked_even_when_candidate_representation_is_reversible",
            "representation_report_tampering_fails_closed",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-component-representation-differential-frontdoor",
        path: "tools/nuisc/src/bootstrap_differential.rs",
        required_patterns: &[
            "compare_compiler_component_representation_paths",
            "COMPILER_COMPONENT_REPRESENTATION_DIFFERENTIAL_FILE",
            "selected_representations_equivalent",
            "representation_report_sha256",
            "all_representations_equivalent",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-stage-semantic-differential-artifact",
        path: "crates/nuis-artifact/src/compiler_stage_semantic_differential.rs",
        required_patterns: &[
            "COMPILER_STAGE_SEMANTIC_DIFFERENTIAL_PROTOCOL",
            "build_compiler_stage_semantic_differential",
            "read_compiler_stage_semantic_differential",
            "deterministic_semantic_equivalent",
            "byte_identical",
            "replacement_authorized: false",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-candidate-production-frontdoor",
        path: "tools/nuis/src/bootstrap_candidate_build.rs",
        required_patterns: &[
            "handle_bootstrap_candidate_build",
            "run_candidate_adapter",
            "build_compiler_stage_transformations",
            "materialize_compiler_stage_transformation_payloads",
            "build_compiler_stage_semantic_differential",
            "build_compiler_stage_handoff_v2",
            "read_compiler_stage_handoff_v2",
            "selected_derived_stages",
            "promote_compiler_component_candidate",
            "build_compiler_candidate_production",
            "BootstrapDiff",
            "equivalent-awaiting-authorization",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-candidate-production-native-regression",
        path: "tools/nuis/tests/compiler_structural_projection_candidate.rs",
        required_patterns: &[
            "bootstrap-candidate-build",
            "read_compiler_candidate_production",
            "COMPILER_COMPONENT_STAGE1_CANDIDATE_ROLE",
            "nuis-stage1-compact-structured-nir-producer-v10",
            "token_page_identity, 164_749_511_446",
            "production.token_page_count > 1",
            "production.token_terminal_page_hash > 0",
            "production.token_page_chain_identity > 0",
            "ast_page_identity, 174_028_320_749",
            "ast_continuation_page_identity, 50_235_927_296",
            "nir_page_identity, 132_469_386_887",
            "nir_continuation_page_identity, 38_763_668_594",
            "transformations.record_count, 2",
            "output_word_count, 22",
            "semantic_differential.equivalent_count, 2",
            "stage_handoff_v2.selection_count, 2",
            "equivalent_count, 13",
            "read_compiler_component_representation_differential",
            "representation_differential.equivalent_count, 2",
            "representation.byte_identical",
            "representation.candidate_recovered_payload_sha256",
            "stage transformation tampering must invalidate production proof",
            "derived stage payload tampering must invalidate production proof",
            "stage handoff v2 tampering must invalidate production proof",
            "adapter tampering must invalidate production proof",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-remote-attestation-evidence-index",
        path: "docs/evidence/compiler-attestation/linux-amd64-cleanroom/generation-1/nuis.compiler-component-remote-evidence.toml",
        required_patterns: &[
            "nuis-compiler-component-remote-evidence-v1",
            "verified-separate-machine",
            "kyuubiki-lab-1",
            "linux-amd64-cleanroom",
            "90b8f7f4c9d336c72caa7dc4dc9a91c41ec263a7bfffa282ee8211088b164f01",
            "random-seed-generated-and-retained-on-attester-only",
            "wrong_challenge_fails_closed = true",
            "wrong_registry_pin_fails_closed = true",
            "physical_machine_independence_cryptographically_proven = false",
            "replacement_authorized = false",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-remote-attestation-claim",
        path: "docs/evidence/compiler-attestation/linux-amd64-cleanroom/generation-1/nuis.compiler-component-attestation.toml",
        required_patterns: &[
            "nuis-compiler-component-attestation-v1",
            "d5aeef8c1d33a5b473f11142197fd361df26dc0f2ec1c0188362f9ece139338c",
            "c7fc7ae1490a78af36ab5dee6fd57815265b1874ba09f3680f36d3ccb684cd14",
            "ed25519:sha256:c2819cec7c31d85e4c5acaae10b852966fb8979ec3a4030233d207a866adfaca",
            "f29add6af3377892852a2d21366563f3366ac4c69cbbb6ae5b28649f246aedcd",
            "replacement_authorized = false",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-remote-attestation-trust-registry",
        path: "docs/evidence/compiler-attestation/linux-amd64-cleanroom/generation-1/nuis.compiler-component-attester-trust-registry.toml",
        required_patterns: &[
            "nuis-compiler-component-attester-trust-registry-v1",
            "generation = 1",
            "independent-machine-compiler-reproducibility-v1",
            "b92387677cc1c63d8418d86b85183574386475a5c720e06bcd405097fb2f7355",
            "status = \"active\"",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-remote-attestation-regression",
        path: "tools/nuis/tests/compiler_remote_attestation_evidence.rs",
        required_patterns: &[
            "checked_in_remote_attestation_verifies_and_fails_closed",
            "read_compiler_component_attestation",
            "90b8f7f4c9d336c72caa7dc4dc9a91c41ec263a7bfffa282ee8211088b164f01",
            "challenge replay must fail closed",
            "unpinned registry bytes must fail closed",
            "replacement_authorized",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-component-image-staging-runtime",
        path: "tools/nuis/src/bootstrap_component_image.rs",
        required_patterns: &[
            "stage_verified_image",
            "create_new(true)",
            "persisted != bytes",
            "PermissionsExt",
            "write_new",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-component-compile-dispatch-contract",
        path: "docs/reference/nuis-compiler-component-compile-dispatch-v1.toml",
        required_patterns: &[
            "nuis-compiler-component-compile-dispatch-v1",
            "nuis-stage0-stage1-verified-compile-dispatch-v1",
            "canonical-verified-stage0-component-rebuild-v1",
            "nuis-compiled-artifact-semantic-identity-v1",
            "nuis bootstrap-dispatch-compile",
            "current-compiled-forward-retained",
            "operational-input-and-output-paths-never-enter-the-receipt",
            "fresh-source-and-native-materialization-under-stage1-ownership",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-component-compile-dispatch-artifact",
        path: "crates/nuis-artifact/src/compiler_component_compile_dispatch.rs",
        required_patterns: &[
            "build_compiler_component_compile_dispatch_receipt",
            "decode_nuis_compiled_artifact_binary",
            "compiled_artifact_semantic_identity",
            "verify_compile_result",
            "request_compiled_artifact",
            "result_compiled_artifact",
            "COMPILER_COMPONENT_COMPILE_DISPATCH_VERDICT",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-component-compile-dispatch-runtime",
        path: "tools/nuis/src/bootstrap_component_compile_dispatch.rs",
        required_patterns: &[
            "handle_bootstrap_dispatch_compile",
            "load_verified_component_transition",
            "read_compiler_component_build",
            "resolve_compiler_component_dispatch",
            "stage_verified_image",
            "COMPILER_COMPONENT_COMPILE_COMMAND",
            "compiled through selected current image",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-component-compile-dispatch-integration",
        path: "tools/nuis/tests/compiler_structural_projection_candidate.rs",
        required_patterns: &[
            "bootstrap-dispatch-compile",
            "canonical compile request through selected current image",
            "parse_compiler_component_compile_dispatch_receipt",
            "COMPILER_COMPONENT_COMPILE_DISPATCH_VERDICT",
            "request_reproducible_build_sha256",
            "result_reproducible_build_sha256",
            ".nuis-stage-driver-",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-candidate-compile-capability-artifact",
        path: "crates/nuis-artifact/src/compiler_candidate_compile_capability.rs",
        required_patterns: &[
            "COMPILER_CANDIDATE_COMPILE_CAPABILITY_PROTOCOL",
            "build_compiler_candidate_compile_capability",
            "verify_compiler_component_rebuild",
            "compiled_artifact_semantic_identity",
            "nuis-owned-stage-fold-v1",
            "replacement_authorized: false",
            "selection_authorized: false",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-candidate-compile-capability-adapter",
        path: "tools/nuis/src/bootstrap_candidate_adapter.rs",
        required_patterns: &[
            "NUIS_BOOTSTRAP_STAGE0_PROVIDER_V1",
            "run_compile_request",
            "nuis_bootstrap_candidate_stage_fold_v1",
            "nuis_bootstrap_candidate_bundle_fold_v1",
            "execl(provider, provider, NUIS_COMPILE_COMMAND",
            "candidate_compile_admission=nuis-owned-stage-fold-v1",
            "bootstrap_candidate_fresh_source_adapter",
            "run_fresh_source",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-candidate-compile-capability-runtime",
        path: "tools/nuis/src/bootstrap_candidate_compile_capability.rs",
        required_patterns: &[
            "handle_bootstrap_candidate_compile_capability",
            "read_compiler_candidate_production",
            "changed before private staging",
            "verify_compiler_component_build_image",
            "stage_verified_image",
            "COMPILER_CANDIDATE_COMPILE_PROVIDER_ENVIRONMENT",
            "build_compiler_candidate_compile_capability",
            "selection_authorized: false",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-candidate-compile-capability-integration",
        path: "tools/nuis/tests/compiler_structural_projection_candidate.rs",
        required_patterns: &[
            "bootstrap-candidate-compile-capability",
            "execute candidate adapter without a provider",
            "compiler image identity mismatch",
            "parse_compiler_candidate_compile_capability",
            "COMPILER_CANDIDATE_COMPILE_CAPABILITY_VERDICT",
            "rebuilt.reproducible_build_sha256",
            "selection_authorized",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-candidate-frontend-result-artifact",
        path: "crates/nuis-artifact/src/compiler_candidate_frontend_result.rs",
        required_patterns: &[
            "COMPILER_CANDIDATE_FRONTEND_RESULT_PROTOCOL",
            "build_compiler_candidate_frontend_result",
            "EXPECTED_LINE_COUNT: usize = 53",
            "verify_transformation_binding",
            "verify_production_summary",
            "parse_compiler_candidate_frontend_result_bytes",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-candidate-direct-compile-artifact",
        path: "crates/nuis-artifact/src/compiler_candidate_direct_compile.rs",
        required_patterns: &[
            "nuis-compiler-candidate-compile-capability-v2",
            "build_compiler_candidate_direct_compile_capability",
            "no-runtime-compiler-provider-v1",
            "cleared-process-environment-v1",
            "provider_dependency_required: false",
            "direct_stage1_compile: true",
            "native_materialization: false",
            "selection_authorized: false",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-candidate-direct-compile-runtime",
        path: "tools/nuis/src/bootstrap_candidate_direct_compile.rs",
        required_patterns: &[
            "handle_bootstrap_candidate_direct_compile",
            "read_compiler_stage_handoff",
            "read_compiler_stage_transformations",
            ".env_clear()",
            "build_compiler_candidate_direct_compile_capability",
            "provider_dependency_required: false",
            "native_materialization: false",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-candidate-direct-compile-integration",
        path: "tools/nuis/tests/compiler_candidate_direct_compile.rs",
        required_patterns: &[
            "bootstrap-candidate-direct-compile",
            "/provider-must-not-be-observed",
            "parse_compiler_candidate_frontend_result",
            "parse_compiler_candidate_direct_compile_capability",
            "provider_dependency_required",
            "direct_stage1_compile",
            "native_materialization",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-candidate-direct-compile-contract",
        path: "docs/reference/nuis-compiler-candidate-direct-compile-capability-v2.toml",
        required_patterns: &[
            "nuis-compiler-candidate-compile-capability-v2",
            "nuis bootstrap-candidate-direct-compile",
            "no-runtime-compiler-provider-v1",
            "provider_dependency_required = false",
            "direct_stage1_compile = true",
            "native_materialization = false",
            "selection_authorized = false",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-candidate-preselection-contract",
        path: "docs/reference/nuis-compiler-candidate-preselection-v1.toml",
        required_patterns: &[
            "nuis-compiler-candidate-preselection-v1",
            "independent-ed25519-component-owner-preselection",
            "target_generation = 3",
            "provider_dependency_required = true",
            "direct_stage1_compile = false",
            "selection_authorized = false",
            "preselection_authorized = true",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-candidate-preselection-artifact",
        path: "crates/nuis-artifact/src/compiler_candidate_preselection.rs",
        required_patterns: &[
            "build_compiler_candidate_preselection",
            "verify_compiler_candidate_preselection",
            "validate_bound_sources",
            "verify_compiler_component_transition",
            "COMPILER_CANDIDATE_PRESELECTION_PROVIDER_CONTRACT",
            "preselection_authorized: true",
            "selection_authorized: false",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-candidate-preselection-runtime",
        path: "tools/nuis/src/bootstrap_candidate_preselection.rs",
        required_patterns: &[
            "handle_bootstrap_preselect_candidate",
            "load_verified_component_transition",
            "load_verified_candidate_compile_lineage",
            "build_compiler_candidate_preselection",
            "failed to self-verify candidate preselection",
            "selection_authorized: false",
            "preselection_authorized: true",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-candidate-preselection-integration",
        path: "tools/nuis/tests/compiler_structural_projection_candidate.rs",
        required_patterns: &[
            "bootstrap-preselect-candidate",
            "snapshot generation two",
            "signed generation-three candidate preselection",
            "parse_compiler_candidate_preselection",
            "COMPILER_CANDIDATE_PRESELECTION_VERDICT",
            "provider_dependency_required",
            "selection_authorized",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-candidate-successor-contract",
        path: "docs/reference/nuis-compiler-candidate-successor-v1.toml",
        required_patterns: &[
            "nuis-compiler-candidate-successor-v1",
            "same-generation-capability-strengthening-v1",
            "nuis bootstrap-sign-candidate-successor",
            "provider_dependency_required = false",
            "direct_stage1_compile = true",
            "fresh_source_compile = false",
            "native_materialization = false",
            "selection_authorized = false",
            "successor_authorized = true",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-candidate-successor-reference",
        path: "docs/reference/nuis-compiler-candidate-successor.md",
        required_patterns: &[
            "immutable delegated preselection chain",
            "continuing component-owner identity",
            "same-generation-capability-strengthening-v1",
            "complete preselection-v1 source",
            "candidate-owned 56-byte source-to-",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-candidate-successor-artifact",
        path: "crates/nuis-artifact/src/compiler_candidate_successor.rs",
        required_patterns: &[
            "build_compiler_candidate_successor",
            "verify_compiler_candidate_successor",
            "verify_compiler_candidate_preselection",
            "verify_compiler_candidate_direct_compile_capability",
            "same-generation-capability-strengthening-v1",
            "fresh_source_compile: false",
            "native_materialization: false",
            "selection_authorized: false",
            "successor_authorized: true",
            "compiler candidate successor signature mismatch",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-candidate-successor-parser",
        path: "crates/nuis-artifact/src/compiler_candidate_successor_parse.rs",
        required_patterns: &[
            "parse_compiler_candidate_successor",
            "parse_compiler_candidate_successor_from_source",
            "must be canonical UTF-8/LF text",
            "validate_successor",
            "is not canonically encoded",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-candidate-successor-runtime",
        path: "tools/nuis/src/bootstrap_candidate_successor.rs",
        required_patterns: &[
            "handle_bootstrap_sign_candidate_successor",
            "load_verified_component_transition",
            "load_verified_candidate_compile_lineage",
            "CompilerCandidatePreselectionVerificationInput",
            "CompilerCandidateDirectCompileCapabilityInput",
            "build_compiler_candidate_successor",
            "fresh_source_compile: false",
            "selection_authorized: false",
            "successor_authorized: true",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-candidate-successor-integration",
        path: "tools/nuis/tests/compiler_structural_projection_candidate/generation_three_successor.rs",
        required_patterns: &[
            "bootstrap-candidate-direct-compile",
            "bootstrap-sign-candidate-successor",
            "snapshot predecessor preselection",
            "snapshot delegated capability v1",
            "parse_compiler_candidate_successor",
            "COMPILER_CANDIDATE_SUCCESSOR_VERDICT",
            "fresh_source_compile",
            "native_materialization",
            "selection_authorized",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-candidate-fresh-source-contract",
        path: "docs/reference/nuis-compiler-candidate-fresh-source-capability-v1.toml",
        required_patterns: &[
            "nuis-compiler-candidate-fresh-source-capability-v1",
            "nuis bootstrap-candidate-fresh-source",
            "single-canonical-utf8-lf-source-no-stage0-handoff-v1",
            "candidate_owned_source_processing = true",
            "fresh_source_compile = true",
            "native_materialization = false",
            "selection_authorized = false",
            "bundle_fold = 357450558",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-candidate-fresh-source-result-artifact",
        path: "crates/nuis-artifact/src/compiler_candidate_fresh_source_result.rs",
        required_patterns: &[
            "build_compiler_candidate_fresh_source_result",
            "parse_compiler_candidate_fresh_source_result_bytes",
            "nuis-canonical-bootstrap-source-snapshot-v1",
            "return 7;",
            "EXPECTED_RECORD_COUNTS",
            "candidate_owned_source_processing: true",
            "native_materialization: false",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-candidate-fresh-source-capability-artifact",
        path: "crates/nuis-artifact/src/compiler_candidate_fresh_source.rs",
        required_patterns: &[
            "build_compiler_candidate_fresh_source_capability",
            "verify_compiler_candidate_fresh_source_capability",
            "parse_compiler_candidate_successor_from_source",
            "stage0_handoff_required: false",
            "candidate_owned_source_processing: true",
            "fresh_source_compile: true",
            "native_materialization: false",
            "selection_authorized: false",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-candidate-fresh-source-nuis",
        path: "examples/projects/tooling/bootstrap_structural_projection_candidate/fresh_source.ns",
        required_patterns: &[
            "mod cpu CandidateFreshSource",
            "candidate_fresh_source_byte",
            "candidate_fresh_stage_seed",
            "candidate_fresh_stage_step",
            "candidate_fresh_stage_record_count",
            "candidate_fresh_stage_finish",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-candidate-fresh-source-runtime",
        path: "tools/nuis/src/bootstrap_candidate_fresh_source.rs",
        required_patterns: &[
            "handle_bootstrap_candidate_fresh_source",
            "load_verified_candidate_compile_lineage",
            "stage_verified_image",
            ".env_clear()",
            ".stdin(Stdio::null())",
            "build_compiler_candidate_fresh_source_result",
            "write_new",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-candidate-fresh-source-integration",
        path: "tools/nuis/tests/compiler_structural_projection_candidate/generation_three_successor.rs",
        required_patterns: &[
            "bootstrap-candidate-fresh-source",
            "parse_compiler_candidate_fresh_source_result",
            "parse_compiler_candidate_fresh_source_capability",
            "candidate_owned_source_processing",
            "fresh_source_compile",
            "native_materialization",
            "tampered[literal] = b'8';",
        ],
    },
];
