use crate::dev_tensor_drift::DevTensorDriftCheckSpec;

pub(super) const CHECKS: &[DevTensorDriftCheckSpec] = &[
    DevTensorDriftCheckSpec {
        id: "native-caller-records-bounded-readonly-total-constructor-proof",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_caller_records.rs",
        required_patterns: &[
            "valid_with_budget(caller, name, plan, layouts, 65_536)",
            "scalar_aliases::validate_expansion(&caller.body, &mut remaining)?",
            "if depth >= 64",
            "!written.contains(param.name.as_str())",
            "matches!(arg, NirExpr::StructLiteral { .. })",
            "dead_records::ready_type(",
            "Some(&plan.original_types[index])",
            "Validate the complete constructor, not just selected fields",
            "Some(&field.param.ty)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-caller-records-canonical-word-authority-and-direct-selection",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_caller_records.rs",
        required_patterns: &[
            "return words.valid_argument(arg)",
            "matches!(input, Input::Keep(_)) || access(arg).is_some()",
            "charge(remaining, fields.len())?",
            "preflighted total caller record field",
            "Select constructor fields directly",
            "value.clone()",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-caller-records-every-caller-transaction-and-registration",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_projection.rs",
        required_patterns: &[
            "mod caller_records;",
            "original_types: Vec<NirTypeRef>",
            "if !callers.iter().all(|i|",
            "valid_caller(&module.functions[*i].body, &name, &plan)",
            "|| (!scoped.contains(&name)",
            "caller_records::valid(&module.functions[*i], &name, &plan, layouts)",
            "module.functions[index] = candidate",
            "caller_records::project(&arg, &field.path)",
            "record_words::project(&arg, &field.path)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-caller-records-rollback-kinds-work-and-independent-oracle",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_caller_records_tests.rs",
        required_patterns: &[
            "caller_record_constructors_select_nested_fields_without_copying_whole_constructors",
            "caller_record_constructors_keep_subrecord_kinds_and_scalar_operand_order",
            "caller_record_constructors_preserve_exact_mixed_scalar_kinds",
            "caller_record_constructors_never_drop_computed_unused_fields_or_inline_calls",
            "caller_record_constructors_require_nominal_fields_kinds_and_immutable_input_paths",
            "caller_record_constructors_require_every_caller_before_rewriting_any_signature",
            "caller_record_constructors_keep_bounded_work_and_depth",
            "caller_record_constructors_preserve_kept_checks_and_guarded_timing_with_an_oracle",
            "for budget in 1..1024",
            "yir.nodes.reverse()",
            "assert_eq!(module, before)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-caller-records-total-does-not-bypass-registered-codecs-test",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_record_words_tests.rs",
        required_patterns: &[
            "caller_record_constructors_cannot_bypass_registered_word_transport_proofs",
            "A total, exact constructor is still not the registered codec of Packet",
            "assert!(!caller_records::valid(&caller, \"helper\", &plan, &layouts))",
            "plan.word_inputs.clear()",
            "assert!(caller_records::valid(&caller, \"helper\", &plan, &layouts))",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-caller-records-explicit-projected-ir-native-execution",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_caller_records_native_tests.rs",
        required_patterns: &[
            "caller_record_constructors_execute_projected_ir_as_a_native_binary",
            "Exercise the private-capture IR contract explicitly",
            "assert!(run(&mut nir))",
            "assert_eq!(signature.matches(\"i64 %\").count(), 3",
            "crate::aot::write_and_link_with_source(",
            "Duration::from_secs(10)",
            "child.kill()",
            "child.wait()",
            "trim(), \"27\"",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-caller-records-drift-registration",
        path: "tools/nuis/src/dev_tensor_drift_data_native_iteration_calls.rs",
        required_patterns: &["mod caller_records;", "caller_records::CHECKS,"],
    },
    DevTensorDriftCheckSpec {
        id: "native-caller-records-tensor-scope",
        path: "tools/nuis/src/dev_tensor_data.rs",
        required_patterns: &[
            "Total inline caller-record follow-up:",
            "caller-side totality is not computed-call spilling",
            "explicitly registered projected IR",
            "caller_record_constructors",
            "active/86 is unchanged",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-caller-records-documentation-boundary",
        path: "docs/reference/nuis-native-scalar-loop-snapshots-v1.md",
        required_patterns: &[
            "## Total Inline Caller Records",
            "All fields, including unused fields, must pass",
            "No call is hoisted or spilled",
            "explicitly registered projected IR",
            "not automatic projection authority for source functions",
            "ten-second execution deadline",
        ],
    },
];
