use crate::dev_tensor_drift::DevTensorDriftCheckSpec;

pub(crate) const DEV_TENSOR_RUNTIME_DRIFT_CHECKS: &[DevTensorDriftCheckSpec] = &[
    DevTensorDriftCheckSpec {
            id: "nustar-domain-contract-completeness-status",
            path: "tools/nuisc/src/registry_contract.rs",
            required_patterns: &[
                "contract_status",
                "required_domain_contract_groups",
                "missing_domain_contract_groups",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "nustar-domain-contract-completeness-json",
            path: "tools/nuisc/src/registry_domain_json.rs",
            required_patterns: &[
                "contract_complete",
                "required_contract_groups",
                "missing_contract_groups",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "nustar-dispatch-readiness-contract",
            path: "tools/nuisc/src/registry_contract.rs",
            required_patterns: &[
                "NUSTAR_DOMAIN_CONTRACT_GROUP_DISPATCH_READINESS",
                "dispatch_readiness_summary",
                "required_dispatch_readiness_signals",
                "dispatch_bridge_materialized",
                "execution_readiness_materialized",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "nustar-dispatch-readiness-json",
            path: "tools/nuisc/src/registry_domain_json.rs",
            required_patterns: &[
                "dispatch_readiness_status",
                "dispatch_bridge_materialized",
                "execution_readiness_materialized",
                "dispatch_readiness_missing_signals",
                "NUSTAR_DOMAIN_CONTRACT_GROUP_DISPATCH_READINESS",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "nustar-dispatch-readiness-link-plan-consumption",
            path: "tools/nuis/src/surface_render/link_plan.rs",
            required_patterns: &[
                "backend_artifact_ready",
                "link_plan_heterogeneous_backend_artifact_ready_units",
                "link_plan_heterogeneous_backend_artifact_first_unready",
                "link_plan_heterogeneous_domain_registry_dispatch_ready_units",
                "link_plan_heterogeneous_domain_registry_dispatch_first_blocked",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "nustar-dispatch-readiness-link-plan-model",
            path: "tools/nuis/src/surface_render/link_plan_readiness.rs",
            required_patterns: &[
                "registry_dispatch_readiness_status",
                "registry_dispatch_readiness_ready",
                "registry_dispatch_missing_signals",
                "registry_dispatch_bridge_materialized",
                "registry_execution_readiness_materialized",
                "backend_artifact_key",
                "backend_artifact_candidate",
                "backend_artifact_missing_signals",
                "registry_dispatch_readiness_blocked",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "nustar-dispatch-readiness-workflow-consumption",
            path: "tools/nuis/src/workflow/link_plan_domain.rs",
            required_patterns: &[
                "registry_dispatch_readiness_status",
                "registry_dispatch_readiness_ready",
                "registry_dispatch_missing_signals",
                "registry_dispatch_bridge_materialized",
                "registry_execution_readiness_materialized",
                "backend_artifact_key",
                "backend_artifact_candidate",
                "backend_artifact_ready",
                "backend_artifact_missing_signals",
                "backend_artifact_first_unready",
                "registry_dispatch_readiness_blocked",
                "workflow_registry_dispatch_readiness",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "nustar-dispatch-readiness-nsld-final-output-ordering",
            path: "tools/nsld/src/main_final_executable_output_tests.rs",
            required_patterns: &[
                "final_executable_output_orders_nustar_dispatch_blockers_before_output_bytes",
                "nustar-dispatch:official.ghost:registry-unavailable",
                "backend_artifact_candidate_count",
                "backend_artifact_ready_count",
                "backend_artifact_selection_status",
                "backend_artifact_ordered_candidates",
                "backend_artifact_selected_candidate",
                "backend_artifact_selection_reason",
                "backend_artifact_assembly_status",
                "backend_artifact_selected_payload_path",
                "backend_artifact_selected_payload_consumed",
                "backend_artifact_assembly_first_blocker",
                "backend_artifact_first_unready",
                "nustar-backend-artifact:ghost:ghost:none:unready",
                "final_executable_output_selects_first_ready_backend_artifact_candidate_by_priority",
                "consumed-by-final-layout",
                "payload_execution_trace_protocol",
                "payload_execution_trace_available",
                "payload_execution_trace_record_count",
                "payload_execution_trace_ready_record_count",
                "handoff-payload-trace-to-nsdb",
                "final-executable-output:missing",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "nustar-backend-artifact-image-role-evidence",
            path: "tools/nsld/src/main_final_executable_image_tests.rs",
            required_patterns: &[
                "final_executable_image_dry_run_reports_backend_artifact_payload_roles",
                "backend_artifact_payload_count",
                "backend_artifact_payload_present_count",
                "backend_artifact_payload_role_status",
                "backend_artifact_payload_ids",
                "backend_artifact_payload_kinds",
                "backend_artifact_payload_first_missing",
                "nustar-backend-artifact:kernel:aarch64:apple-silicon-cpu",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "workflow-surface-json-regression",
            path: "tools/nuis/src/main_tests/workflow_surface.rs",
            required_patterns: &[
                "nsld_final_executable_output_boundary_status",
                "nsld_final_executable_output_materialization_status",
                "nsld_final_executable_output_execution_handoff_contract",
                "nsld_final_executable_output_execution_handoff_ready",
                "nsld_final_executable_output_execution_handoff_status",
                "nsld_final_executable_output_execution_handoff_target",
                "nsld_final_executable_output_execution_handoff_evidence_status",
                "nsld_final_executable_output_execution_handoff_first_blocker",
                "nsld_final_executable_output_execution_handoff_decision_code",
                "nsld_final_executable_output_payload_execution_trace_protocol",
                "nsld_final_executable_output_payload_execution_trace_available",
                "nsld_final_executable_output_payload_execution_trace_record_count",
                "nsld_final_executable_output_payload_execution_trace_ready_record_count",
                "nsld_final_executable_pipeline_execution_handoff_contract",
                "nsld_final_executable_pipeline_execution_handoff_ready",
                "nsld_final_executable_pipeline_execution_handoff_status",
                "nsld_final_executable_pipeline_execution_handoff_target",
                "nsld_final_executable_pipeline_execution_handoff_evidence_status",
                "nsld_final_executable_pipeline_execution_handoff_first_blocker",
                "nsld_final_executable_pipeline_execution_handoff_decision_code",
                "workflow_run_artifact_prelaunch_kind",
                "workflow_run_artifact_prelaunch_status",
                "workflow_run_artifact_prelaunch_evidence_status",
                "workflow_run_artifact_prelaunch_command",
                "workflow_run_artifact_prelaunch_reason",
                "workflow_launch_evidence_protocol",
                "workflow_launch_evidence_debugger_contract",
                "workflow_launch_evidence_host_runner_probe_status",
                "workflow_nsdb_handoff_available",
                "workflow_nsdb_handoff_protocol",
                "workflow_nsdb_handoff_record_count",
                "link_plan_heterogeneous_backend_artifact_units",
                "link_plan_heterogeneous_backend_artifact_ready_units",
                "link_plan_heterogeneous_backend_artifact_first_unready",
                "nsld_final_executable_output_recommended_next_action",
                "nsld_final_executable_output_object_valid",
                "nsld_final_executable_output_object_expected_hash",
                "nsld_final_executable_output_object_actual_hash",
                "nsld_final_executable_output_object_issues",
                "nsld_self_owned_image_status",
                "nsld_backend_artifact_payload_evidence_available",
                "nsld_backend_artifact_payload_count",
                "nsld_backend_artifact_payload_role_status",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "artifact-runtime-json-regression",
            path: "tools/nuis/src/main_tests/artifact_runtime.rs",
            required_patterns: &[
                "nsld_final_executable_output_boundary_status",
                "nsld_final_executable_output_materialization_status",
                "nsld_final_executable_output_execution_handoff_contract",
                "nsld_final_executable_output_execution_handoff_ready",
                "nsld_final_executable_output_execution_handoff_status",
                "nsld_final_executable_output_execution_handoff_target",
                "nsld_final_executable_output_execution_handoff_evidence_status",
                "nsld_final_executable_output_execution_handoff_first_blocker",
                "nsld_final_executable_output_execution_handoff_decision_code",
                "nsld_final_executable_output_payload_execution_trace_protocol",
                "nsld_final_executable_output_payload_execution_trace_available",
                "nsld_final_executable_output_payload_execution_trace_record_count",
                "nsld_final_executable_output_payload_execution_trace_ready_record_count",
                "nsld_final_executable_pipeline_execution_handoff_contract",
                "nsld_final_executable_pipeline_execution_handoff_ready",
                "nsld_final_executable_pipeline_execution_handoff_status",
                "nsld_final_executable_pipeline_execution_handoff_target",
                "nsld_final_executable_pipeline_execution_handoff_evidence_status",
                "nsld_final_executable_pipeline_execution_handoff_first_blocker",
                "nsld_final_executable_pipeline_execution_handoff_decision_code",
                "nsld_final_executable_output_recommended_next_action",
                "nsld_self_owned_image_status",
                "run_artifact_prelaunch_kind",
                "run_artifact_prelaunch_status",
                "run_artifact_prelaunch_evidence_status",
                "run_artifact_prelaunch_runner_command_present",
                "run_artifact_prelaunch_entrypoint_present",
                "run_artifact_prelaunch_entrypoint_protocol",
                "run_artifact_prelaunch_entrypoint_protocol_valid",
                "nsld-host-entrypoint",
                "artifact_closure_kind",
                "artifact_closure_status",
                "artifact_closure_evidence_status",
                "artifact_closure_runner_command_present",
                "artifact_closure_entrypoint_present",
                "artifact_closure_entrypoint_protocol",
                "artifact_closure_entrypoint_protocol_valid",
                "artifact_launch_evidence_protocol",
                "artifact_launch_evidence_debugger_contract",
                "artifact_launch_evidence_host_runner_probe_status",
                "artifact_nsdb_handoff_available",
                "artifact_nsdb_handoff_protocol",
                "artifact_nsdb_handoff_record_count",
                "artifact_payload_decoder_manifest_status",
                "nsld_backend_artifact_payload_evidence_available",
                "nsld_backend_artifact_payload_count",
                "nsld_backend_artifact_payload_role_status",
                "nsld_backend_artifact_payload_ids",
                "nsld_backend_artifact_payload_kinds",
                "artifact_launch_evidence_backend_artifact_payload_evidence_available",
                "artifact_launch_evidence_backend_artifact_payload_count",
                "artifact_launch_evidence_backend_artifact_payload_role_status",
                "launch_evidence_backend_artifact_payload_evidence_available",
                "launch_evidence_backend_artifact_payload_count",
                "launch_evidence_backend_artifact_payload_role_status",
                "hetero_runtime_trace_available",
                "hetero_runtime_trace_status",
                "hetero_runtime_trace_debugger_contract",
                "hetero_runtime_trace_backend_artifact_ready_count",
                "hetero_runtime_trace_record_count",
                "hetero_runtime_trace_persisted",
                "hetero_runtime_trace_next_action",
                "build_report_payload_decoder_manifest_status",
                "release_check_payload_decoder_manifest_status",
                "host_runner_backend_artifact_payload_count",
                "host_runner_backend_artifact_payload_ready_count",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "run-artifact-hetero-runtime-trace-surface",
            path: "tools/nuis/src/artifact_runtime_trace.rs",
            required_patterns: &[
                "HeteroRuntimeTraceSummary",
                "nsdb-yir-hetero-runtime-trace-v1",
                "hetero_runtime_trace_available",
                "hetero_runtime_trace_status",
                "hetero_runtime_trace_payload_evidence_available",
                "hetero_runtime_trace_domain_families",
                "HeteroRuntimeTraceRecord",
                "trace_record_for_unit",
                "persist_nsdb_trace",
                "backend-artifact",
                "domain-metadata",
                "materialize-device-execution-trace",
                "handoff-to-nsdb-trace",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "run-artifact-host-runner-probe-surface",
            path: "tools/nuis/src/artifact_runtime_command.rs",
            required_patterns: &[
                "run_artifact_host_runner_surface",
                "HostRunnerJsonSurface",
                "run_nsld_host_runner",
                "try_run_nsld_host_runner",
                "resolve_nuis_host_runner_program",
                "from_surfaces_with_backend_payload_evidence",
                "HeteroRuntimeTraceSummary",
                "persist_launch_evidence_nsdb_handoff",
                "nuis-host-runner",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "run-artifact-nsdb-handoff-persistence",
            path: "tools/nuis/src/artifact_nsdb_handoff.rs",
            required_patterns: &[
                "nuis-nsdb-payload-execution-handoff-v1",
                "nuis.nsdb.payload-execution-handoff.toml",
                "persist_launch_evidence_nsdb_handoff",
                "launch_evidence_nsdb_handoff_persisted",
                "launch_evidence_nsdb_handoff_record_count",
                "launch_evidence_nsdb_handoff_ready_record_count",
                "launch_evidence_nsdb_handoff_first_trace_id",
                "run-artifact-launch-evidence",
                "payload_execution_trace_protocol",
                "next_action",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "nsdb-payload-execution-handoff-consumer",
            path: "tools/nsdb/src/handoff.rs",
            required_patterns: &[
                "nuis.nsdb.payload-execution-handoff.toml",
                "nuis-nsdb-payload-execution-handoff-v1",
                "nsdb-yir-payload-execution-trace-v1",
                "read_payload_execution_handoff",
                "payload_handoff_status",
                "parse_payload_execution_events",
                "NsdbPayloadExecutionEvent",
                "payload-trace:container-loader:nuis.bootstrap.lifecycle.v1",
                "container-loader-handoff",
                "handoff-payload-trace-to-nsdb",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "nsdb-inspect-payload-handoff-surface",
            path: "tools/nsdb/src/json.rs",
            required_patterns: &[
                "payload_execution_handoff_available",
                "payload_execution_handoff_protocol",
                "payload_execution_handoff_debugger_contract",
                "payload_execution_handoff_status",
                "payload_execution_handoff_record_count",
                "payload_execution_handoff_first_trace_id",
                "payload_execution_event_filter_active",
                "hetero_runtime_trace_protocol",
                "payload_execution_event_count",
                "nsdb_replay_plan_json",
                "payload_decoder_manifest_status",
                "value_decoder_format_probe_status",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "run-artifact-launch-evidence-surface",
            path: "tools/nuis/src/artifact_launch_evidence.rs",
            required_patterns: &[
                "RunArtifactLaunchEvidence",
                "HostRunnerJsonSurface",
                "host_runner_invoked",
                "host_runner_status",
                "host_runner_program",
                "host_runner_ready",
                "host_runner_nsb_readable",
                "host_runner_nsb_hash_matches",
                "host_runner_nsb_payload_region_mapped",
                "host_runner_nsb_payload_scan_kind",
                "host_runner_container_loader_status",
                "host_runner_container_loader_entry_kind",
                "host_runner_container_loader_entry_symbol",
                "host_runner_container_loader_entry_section_id",
                "host_runner_container_loader_handoff_ready",
                "host_runner_backend_artifact_payload_count",
                "host_runner_backend_artifact_payload_parsed_count",
                "host_runner_backend_artifact_payload_ready_count",
                "host_runner_backend_artifact_payload_first_kind",
                "host_runner_backend_artifact_payload_table_hash",
                "json_fields_with_prefix",
                "nuis-run-artifact-launch-evidence-v1",
                "nsdb-yir-launch-evidence-v1",
                "nsdb-yir-payload-execution-trace-v1",
                "launch_evidence_first_payload_status",
                "launch_evidence_first_payload_entry_symbol",
                "launch_evidence_payload_execution_trace_records",
                "payload_execution_trace_records",
                "handoff-payload-trace-to-nsdb",
                "launch_evidence_backend_artifact_payload_evidence_available",
                "launch_evidence_backend_artifact_payload_count",
                "launch_evidence_backend_artifact_payload_role_status",
                "launch_evidence_backend_artifact_payload_ids",
                "launch_evidence_backend_artifact_payload_kinds",
                "container_loader_entry_symbol",
                "container_loader_entry_section_id",
                "launch_evidence_first_blocker",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "host-runner-container-loader-handoff-policy",
            path: "tools/nuis-host-runner/src/container.rs",
            required_patterns: &[
                "host_assisted_loader",
                "backend_artifact_payload_count",
                "backend_artifact_payload_table_hash",
                "container_loader_handoff_blockers",
                "external-import:",
                "container-loader:blocker",
                "position(|byte| *byte == 0)",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "host-runner-backend-artifact-payload-scan",
            path: "tools/nuis-host-runner/src/container_backend_payload.rs",
            required_patterns: &[
                "BackendArtifactPayloadSummary",
                "scan_backend_artifact_payloads",
                "backend_artifact_payload",
                "nustar-backend-artifact",
                "role_status",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "host-runner-container-loader-policy-regression",
            path: "tools/nuis-host-runner/src/tests.rs",
            required_patterns: &[
                "allows_host_assisted_container_handoff_when_required_external_import_is_declared",
                "blocks_self_contained_container_handoff_when_required_external_import_is_declared",
                "allows_host_assisted_container_loader_handoff_when_external_import_loader_blockers_are_declared",
                "container_loader_handoff_status",
                "container_loader_handoff_ready",
                "backend_artifact_payload_count",
                "backend_artifact_payload_first_kind",
                "nustar-backend-artifact:kernel:aarch64:apple-silicon-cpu",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "self-contained-nsb-frontdoor-smoke",
            path: "tools/nuis/tests/self_contained_nsb_smoke.rs",
            required_patterns: &[
                "self_contained_nsb_route_moves_from_nsld_drive_to_run_artifact_handoff",
                "nuis-self-contained-image",
                "self-contained-image-awaiting-nsld-handoff",
                "nsld-host-entrypoint",
                "host_runner_invoked",
                "host_runner_nsb_readable",
                "host_runner_nsb_hash_matches",
                "host_runner_nsb_payload_region_mapped",
                "host_runner_nsb_payload_scan_kind",
                "nsld-container-toml",
                "host_runner_container_loader_status",
                "host_runner_container_loader_entry_symbol",
                "host_runner_container_loader_handoff_ready",
                "host_runner_container_loader_handoff_status",
                "host_runner_backend_artifact_payload_count",
                "host_runner_backend_artifact_payload_first_kind",
                "launch_evidence_first_payload_status",
                "launch_evidence_first_payload_entry_symbol",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "run-artifact-entrypoint-protocol-regression",
            path: "tools/nuis/src/main_tests/artifact_runtime_run_artifact.rs",
            required_patterns: &[
                "run_artifact_prelaunch_kind",
                "run_artifact_prelaunch_status",
                "run_artifact_prelaunch_evidence_status",
                "nsld-host-entrypoint",
                "run_artifact_json_blocks_nsld_prelaunch_when_entrypoint_stub_is_missing",
                "run_artifact_json_blocks_nsld_prelaunch_when_entrypoint_protocol_is_missing",
                "host entrypoint stub is missing on disk",
                "nuis-nsld-host-entrypoint-v1",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "frontdoor-reference-doc",
            path: "docs/reference/nuis-frontdoor-surface-reference.md",
            required_patterns: &[
                "nsld_final_executable_output_boundary_status",
                "nsld_final_executable_output_materialization_status",
                "nsld_final_executable_output_execution_handoff_contract",
                "nsld_final_executable_output_execution_handoff_ready",
                "nsld_final_executable_output_execution_handoff_status",
                "nsld_final_executable_output_execution_handoff_target",
                "nsld_final_executable_output_execution_handoff_evidence_status",
                "nsld_final_executable_output_execution_handoff_first_blocker",
                "nsld_final_executable_output_execution_handoff_decision_code",
                "nsld_final_executable_output_payload_execution_trace_protocol",
                "nsld_final_executable_output_payload_execution_trace_available",
                "nsld_final_executable_output_payload_execution_trace_record_count",
                "nsld_final_executable_output_payload_execution_trace_ready_record_count",
                "nsld_final_executable_pipeline_execution_handoff_contract",
                "nsld_final_executable_pipeline_execution_handoff_ready",
                "nsld_final_executable_pipeline_execution_handoff_status",
                "nsld_final_executable_pipeline_execution_handoff_target",
                "nsld_final_executable_pipeline_execution_handoff_evidence_status",
                "nsld_final_executable_pipeline_execution_handoff_first_blocker",
                "nsld_final_executable_pipeline_execution_handoff_decision_code",
                "nsld_final_executable_output_recommended_next_action",
                "nsld_self_owned_image_status",
                "run_artifact_prelaunch_kind",
                "run_artifact_prelaunch_status",
                "run_artifact_prelaunch_evidence_status",
                "workflow_run_artifact_prelaunch_kind",
                "workflow_run_artifact_prelaunch_status",
                "workflow_run_artifact_prelaunch_evidence_status",
                "workflow_run_artifact_prelaunch_command",
                "workflow_run_artifact_prelaunch_reason",
                "workflow_launch_evidence_protocol",
                "workflow_launch_evidence_debugger_contract",
                "workflow_launch_evidence_host_runner_probe_status",
                "workflow_nsdb_handoff_available",
                "workflow_nsdb_handoff_protocol",
                "workflow_nsdb_handoff_record_count",
                "link_plan_heterogeneous_backend_artifact_units",
                "link_plan_heterogeneous_backend_artifact_ready_units",
                "link_plan_heterogeneous_backend_families",
                "link_plan_heterogeneous_target_devices",
                "link_plan_heterogeneous_backend_artifact_first_unready",
                "run_artifact_prelaunch_command",
                "run_artifact_prelaunch_runner_command_present",
                "run_artifact_prelaunch_entrypoint_present",
                "run_artifact_prelaunch_entrypoint_protocol",
                "run_artifact_prelaunch_entrypoint_protocol_valid",
                "host_runner_invoked",
                "host_runner_status",
                "host_runner_nsb_readable",
                "host_runner_nsb_payload_region_mapped",
                "host_runner_container_loader_handoff_status",
                "launch_evidence_protocol",
                "launch_evidence_debugger_contract",
                "launch_evidence_payload_execution_trace_protocol",
                "launch_evidence_payload_execution_trace_record_count",
                "launch_evidence_first_payload_status",
                "launch_evidence_first_payload_entry_symbol",
                "launch_evidence_first_payload_first_blocker",
                "launch_evidence_first_blocker",
                "artifact_closure_kind",
                "artifact_closure_status",
                "artifact_closure_evidence_status",
                "artifact_closure_command",
                "artifact_closure_runner_command_present",
                "artifact_closure_entrypoint_present",
                "artifact_closure_entrypoint_protocol",
                "artifact_closure_entrypoint_protocol_valid",
                "artifact_launch_evidence_protocol",
                "artifact_launch_evidence_debugger_contract",
                "artifact_launch_evidence_host_runner_probe_status",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "nsld-binary-assembly-doc",
            path: "docs/reference/nsld-binary-assembly-gap-map.md",
            required_patterns: &["self_owned_image_status", "internal binary assembly layer"],
        },
    DevTensorDriftCheckSpec {
            id: "native-artifact-workflow-doc",
            path: "docs/reference/nuis-native-artifact-workflow.md",
            required_patterns: &[
                "nsld_final_executable_output_boundary_status",
                "nsld_final_executable_output_materialization_status",
                "nsld_final_executable_output_execution_handoff_contract",
                "nsld_final_executable_output_execution_handoff_ready",
                "nsld_final_executable_output_execution_handoff_status",
                "nsld_final_executable_output_execution_handoff_target",
                "nsld_final_executable_output_execution_handoff_evidence_status",
                "nsld_final_executable_output_execution_handoff_first_blocker",
                "nsld_final_executable_output_execution_handoff_decision_code",
                "nsld_final_executable_output_payload_execution_trace_protocol",
                "nsld_final_executable_output_payload_execution_trace_available",
                "nsld_final_executable_output_payload_execution_trace_record_count",
                "nsld_final_executable_output_payload_execution_trace_ready_record_count",
                "nsld_final_executable_pipeline_execution_handoff_contract",
                "nsld_final_executable_pipeline_execution_handoff_ready",
                "nsld_final_executable_pipeline_execution_handoff_status",
                "nsld_final_executable_pipeline_execution_handoff_target",
                "nsld_final_executable_pipeline_execution_handoff_evidence_status",
                "nsld_final_executable_pipeline_execution_handoff_first_blocker",
                "nsld_final_executable_pipeline_execution_handoff_decision_code",
                "nsld_final_executable_output_recommended_next_action",
                "nsld_self_owned_image_status",
                "run_artifact_prelaunch_kind",
                "run_artifact_prelaunch_status",
                "run_artifact_prelaunch_evidence_status",
                "workflow_run_artifact_prelaunch_kind",
                "workflow_run_artifact_prelaunch_status",
                "workflow_run_artifact_prelaunch_evidence_status",
                "workflow_run_artifact_prelaunch_command",
                "workflow_run_artifact_prelaunch_reason",
                "workflow_launch_evidence_protocol",
                "workflow_launch_evidence_debugger_contract",
                "workflow_launch_evidence_host_runner_probe_status",
                "workflow_nsdb_handoff_available",
                "workflow_nsdb_handoff_protocol",
                "workflow_nsdb_handoff_record_count",
                "link_plan_heterogeneous_backend_artifact_units",
                "link_plan_heterogeneous_backend_artifact_ready_units",
                "link_plan_heterogeneous_backend_families",
                "link_plan_heterogeneous_target_devices",
                "link_plan_heterogeneous_backend_artifact_first_unready",
                "run_artifact_prelaunch_command",
                "run_artifact_prelaunch_runner_command_present",
                "run_artifact_prelaunch_entrypoint_present",
                "run_artifact_prelaunch_entrypoint_protocol",
                "run_artifact_prelaunch_entrypoint_protocol_valid",
                "host_runner_invoked",
                "host_runner_status",
                "host_runner_nsb_readable",
                "host_runner_nsb_payload_region_mapped",
                "host_runner_container_loader_handoff_status",
                "launch_evidence_protocol",
                "launch_evidence_debugger_contract",
                "launch_evidence_payload_execution_trace_protocol",
                "launch_evidence_payload_execution_trace_record_count",
                "launch_evidence_first_payload_status",
                "launch_evidence_first_payload_entry_symbol",
                "launch_evidence_first_payload_first_blocker",
                "launch_evidence_first_blocker",
                "artifact_closure_kind",
                "artifact_closure_status",
                "artifact_closure_evidence_status",
                "artifact_closure_command",
                "artifact_closure_runner_command_present",
                "artifact_closure_entrypoint_present",
                "artifact_closure_entrypoint_protocol",
                "artifact_closure_entrypoint_protocol_valid",
                "artifact_launch_evidence_protocol",
                "artifact_launch_evidence_debugger_contract",
                "artifact_launch_evidence_host_runner_probe_status",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "std-filesystem-light-smoke",
            path: "tools/nuis/tests/std_filesystem_smoke.rs",
            required_patterns: &[
                "STD_TOOLING_LIGHT_SMOKE_PROJECTS",
                "std_tooling_light_project_smokes_build_doctor_and_run",
                "text_pipeline_demo",
                "io_runtime_demo",
                "stdin_runtime_demo",
                "filesystem_io_report_demo",
                "std_tooling_observable_cli_smoke_checks_reports_and_stdin",
                "run_binary_with_stdin",
                "run_binary_with_args",
                "official_galaxy_hetero_projects_emit_shader_and_kernel_artifacts",
                "host_stdin_read",
                "cli_wc_demo",
                "cli_report_file_demo",
                "pixelmagic_report_file_demo",
                "witsage_report_file_demo",
                "pixelmagic_pipeline_demo",
                "witsage_kernel_demo",
                "StdReportContracts.cli_report_file_status_total",
                "StdReportContracts.cli_report_file_validation_total",
                "PixelMagicContracts.filter_chain_total",
                "PixelMagicContracts.shader_pipeline_total",
                "WitSageContracts.classifier_pipeline_total",
                "WitSageContracts.kernel_pipeline_total",
                "shader_stage_model = \\\"metal-render-pipeline\\\"",
                "kernel_ir = \\\"coreml-program\\\"",
                "nuis-domain-build-payload-v1",
                "hetero_runtime_trace_debugger_contract",
                "hetero_runtime_trace_record_count",
                "hetero_runtime_trace_backend_execution_record_count",
                "materialize-device-execution-trace",
                "hetero-trace:shader:metal:apple-silicon-gpu",
                "hetero-trace:kernel:coreml:apple-ane",
                "host_argv_count",
                "host_file_read",
                "host_file_write",
                "host_text_word_count",
                "bytes: 31",
                "words: 5",
                "output: report-file",
                "host_stdout_write",
                "host_stderr_write",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "std-tooling-doc-smoke-chain",
            path: "examples/projects/tooling/README.md",
            required_patterns: &[
                "cargo test -q -p nuis --test std_filesystem_smoke",
                "filesystem_io_report_demo",
                "cli_report_file_demo",
                "text_report_json_demo",
                "terminal/stdin/TTY",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "std-readme-host-io-text-lane",
            path: "stdlib/std/README.md",
            required_patterns: &[
                "host I/O and text",
                "filesystem/path/location",
                "lib/io_contracts.ns",
                "lib/text_contracts.ns",
                "lib/fs_contracts.ns",
                "lib/report_contracts.ns",
                "stdin_runtime_demo",
                "filesystem_io_report_demo",
                "cli_wc_demo",
                "cli_report_file_demo",
                "StdReportContracts",
                "argv -> file.read -> buffer",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "language-bootstrap-result-task-smoke",
            path: "tools/nuis/tests/language_bootstrap_smoke.rs",
            required_patterns: &[
                "task_result_enum_project_anchors_language_bootstrap_smoke",
                "generic_trait_and_glm_buffer_projects_anchor_language_bootstrap_smoke",
                "generic_result_buffer_lambda_project_combines_language_bootstrap_features",
                "../../examples/projects/task/task_result_enum_demo",
                "../../examples/projects/state/generic_method_bound_guarded_nested_match_demo",
                "../../examples/projects/state/glm_buffer_roundtrip_state_demo",
                "../../examples/projects/state/generic_result_buffer_lambda_helper_demo",
                "__hof_result_map_raise_value__i64__i64__ErrorEnvelope",
                "__hof_result_map___lambda_build_report_0__i64__i64__HelperError",
                "__hof_result_map___lambda_build_report_2__i64__i64__HelperError",
                "ok__i64__HelperError(seed)",
                "Result<i64, ErrorEnvelope>",
                "enum Result<T, E>",
                "return Result.Err(error)",
                "if (seed == 3)",
                "err__i64__HelperError(HelperError.Invalid",
                "return Result.Err<i64, HelperError>",
                "trait Addable",
                "impl.Addable.for.i64.add(local, local)",
                "impl.Addable.for.i64.add(item, item)",
                "buffer_len(buffer)",
                "cpu.store_at",
                "edge lifetime",
                "cpu.variant_is",
                "cpu.task_completed",
                "policy=signature-whitelist-required",
                "task_result_enum_demo should execute the Result/task/error path",
                "generic Result/buffer/lambda helper binary",
                "59",
                "10",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "dev-tensor-coverage-doc",
            path: "docs/reference/nuis-development-tensor.md",
            required_patterns: &[
                "Coverage Manifest",
                "Status Protocol",
                "Recursive Hierarchy",
                "dev-tensor-status-v1",
                "hierarchy_root_status",
                "weakest_child_path",
                "weakest_bootstrap_status",
                "weakest_bootstrap_evidence",
                "weakest_bootstrap_next_step",
                "weakest_bootstrap_blocker",
                "weakest_bootstrap_next_action",
                "weakest_bootstrap_validation_command",
                "weakest_bootstrap_expected_artifact",
                "validation_command",
                "expected_artifact",
                "Manifest-Backed Coordinate Coverage",
                "Milestone-Owned Coordinate Coverage",
                "coverage_expected_source",
                "coverage_expected_fallback_used",
                "manifest_coverage_status",
                "manifest_backed_coordinates",
                "manifest_untracked_modules",
                "milestone_coverage_status",
                "milestone_coordinates",
                "milestone_constant_drift_count",
                "coverage_status",
                "coverage_missing_coordinates",
                "coverage_orphaned_coordinates",
                "coverage_stale_coordinates",
                "coverage_first_gap",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "dev-tensor-manifest-derived-coverage",
            path: "tools/nuis/src/dev_tensor_manifest.rs",
            required_patterns: &[
                "DevTensorManifestCoverage",
                "dev_tensor_manifest_coverage",
                "stdlib/index.toml",
                "manifest_backed_coordinates",
                "manifest_untracked_modules",
                "standard-library/std/host-io-filesystem-text",
                "standard-library/pixelmagic/image-processing-lane",
                "standard-library/witsage/classical-ml-lane",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "dev-tensor-milestone-coordinate-manifest",
            path: "docs/reference/nuis-development-tensor.milestones.toml",
            required_patterns: &[
                "nuis-dev-tensor-milestones-v1",
                "alpha-governance",
                "alpha-official-galaxy",
                "required = false",
                "developer-system/dev-tensor/architecture-module-function-progress-model",
                "standard-library/std/host-io-filesystem-text",
                "linker-toolchain/nsld/final-output-boundary",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "dev-tensor-milestone-derived-coverage",
            path: "tools/nuis/src/dev_tensor_milestones.rs",
            required_patterns: &[
                "DevTensorMilestoneCoverage",
                "DevTensorDerivedExpectedCoordinate",
                "dev_tensor_milestone_coverage",
                "expected_coordinates_from_milestones",
                "nuis-development-tensor.milestones.toml",
                "milestone_constant_drift_count",
                "missing-from-milestone-manifest",
                "fallback_used",
            ],
        },
];
