use crate::dev_tensor_drift::DevTensorDriftCheckSpec;

pub(crate) const DEV_TENSOR_RUNTIME_BOOTSTRAP_REPRODUCIBILITY_DRIFT_CHECKS:
    &[DevTensorDriftCheckSpec] = &[
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-data-model-v3-contract",
        path: "docs/reference/nuis-compiler-data-model-v3.toml",
        required_patterns: &[
            "nuis-compiler-data-model-v3",
            "surface.std.compiler-data-model.v3",
            "stdlib/std/lib/compiler_data.ns",
            "stdlib/std/lib/compiler_token_emit.ns",
            "maximum_records = 4",
            "packed_word_bytes = 7",
            "emission_capacity_bytes = 128",
            "expected_native_exit = 122",
            "expected_emitted_bytes = 59",
            "candidate_prefix_emitted_bytes = 91",
            "candidate_prefix_emitted_hash = 1277127995",
            "compiler_token_materializer_decode_first_page",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-data-model-v4-contract",
        path: "docs/reference/nuis-compiler-data-model-v4.toml",
        required_patterns: &[
            "nuis-compiler-data-model-v4",
            "surface.std.compiler-data-model.v4",
            "nuis-bootstrap-language-subset-v8",
            "nuis-compiler-candidate-production-v9",
            "nuis-compiler-token-pagination-v1",
            "token_pagination_page_bytes = 128",
            "adapter-counters-with-nuis-owned-hash-and-chain-transitions",
            "compiler_candidate_token_page_hash_step",
            "compiler_candidate_token_page_chain_fold",
            "page-boundaries-may-cross-records-without-changing-token-bytes",
            "deterministic-map-and-arena-growth",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-data-model-v5-contract",
        path: "docs/reference/nuis-compiler-data-model-v5.toml",
        required_patterns: &[
            "nuis-compiler-data-model-v5",
            "surface.std.compiler-data-model.v5",
            "nuis-compiler-map-ordered-identity-v1",
            "maximum_entries = 16",
            "reference_identity = 415394959",
            "implementation-uses-bounded-Nuis-recursion-without-host-collections",
            "compiler-arena-owned-object-storage",
            "expected_native_exit = 130",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-data-model-v6-contract",
        path: "docs/reference/nuis-compiler-data-model-v6.toml",
        required_patterns: &[
            "nuis-compiler-data-model-v6",
            "surface.std.compiler-data-model.v6",
            "nuis-compiler-arena-ordered-identity-v1",
            "nuis-compiler-candidate-production-v10",
            "maximum_objects = 16",
            "reference_identity = 1064756829",
            "every-successful-store-appends-one-complete-object-atomically",
            "compiler-arena-typed-owned-payload-projection",
            "expected_native_exit = 130",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-data-model-v7-contract",
        path: "docs/reference/nuis-compiler-data-model-v7.toml",
        required_patterns: &[
            "nuis-compiler-data-model-v7",
            "surface.std.compiler-data-model.v7",
            "CompilerTextArena",
            "nuis-compiler-text-arena-ordered-identity-v1",
            "maximum_total_payload_bytes = 16",
            "reference_envelope_identity = 1856301942",
            "reference_identity = 1643761726",
            "new_scalar_exports = 0",
            "expected_native_exit = 130",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-data-model-v8-contract",
        path: "docs/reference/nuis-compiler-data-model-v8.toml",
        required_patterns: &[
            "nuis-compiler-data-model-v8",
            "surface.std.compiler-data-model.v8",
            "nuis-compiler-payload-pages-v1",
            "logical_page_bytes = 16",
            "maximum_total_payload_bytes = 128",
            "reference_page0_identity = 712007164",
            "reference_page1_identity = 132664649",
            "reference_identity = 322532187",
            "new_scalar_exports = 0",
            "expected_native_exit = 130",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-data-model-v8-paged-payload-stdlib",
        path: "stdlib/std/lib/compiler_payload.ns",
        required_patterns: &[
            "pub type CompilerPayloadBuffer = CompilerTokenBuffer",
            "pub struct CompilerPagedTextArena",
            "pub fn compiler_payload_page_identity",
            "pub fn compiler_paged_text_arena_store",
            "pub fn compiler_paged_text_arena_get",
            "pub fn compiler_paged_text_arena_identity",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-data-model-v9-contract",
        path: "docs/reference/nuis-compiler-data-model-v9.toml",
        required_patterns: &[
            "nuis-compiler-data-model-v9",
            "surface.std.compiler-data-model.v9",
            "nuis-compiler-payload-kind-registry-v1",
            "nuis-compiler-registered-aggregate-arena-v1",
            "reference_identity = 1630830726",
            "reference_identity = 1274791798",
            "reference_identity = 1383365918",
            "new_scalar_exports = 0",
            "expected_native_exit = 130",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-data-model-v10-contract",
        path: "docs/reference/nuis-compiler-data-model-v10.toml",
        required_patterns: &[
            "nuis-compiler-data-model-v10",
            "nuis-compiler-data-model-v9",
            "surface.std.compiler-data-model.v10",
            "nuis-compiler-chunked-payload-v1",
            "reference_payload_bytes = 24",
            "reference_identity = 94500080",
            "reference_identity = 1593840720",
            "reference_identity = 551151124",
            "new_scalar_exports = 0",
            "expected_native_exit = 130",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-data-model-v10-registry-stdlib",
        path: "stdlib/std/lib/compiler_payload_registry.ns",
        required_patterns: &[
            "pub type CompilerPayloadRegistry = CompilerMap",
            "pub struct CompilerAggregateArena",
            "pub struct CompilerChunkedPayload",
            "pub fn compiler_payload_registry_register",
            "pub fn compiler_aggregate_arena_store_chunked",
            "pub fn compiler_aggregate_arena_get_chunked",
            "pub fn compiler_aggregate_arena_store_text",
            "pub fn compiler_aggregate_arena_store_source_span",
            "pub fn compiler_aggregate_arena_get_source_span",
            "pub fn compiler_aggregate_arena_identity",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-data-model-v9-native-fixture",
        path: "examples/projects/tooling/bootstrap_compiler_data_model_demo/payload_registry_fixture.ns",
        required_patterns: &[
            "mod cpu CompilerPayloadRegistryFixture",
            "compiler_payload_registry_register",
            "compiler_aggregate_arena_store_text",
            "compiler_aggregate_arena_store_source_span",
            "compiler_aggregate_arena_store_chunked",
            "1630830726",
            "1593840720",
            "94500080",
            "934788601",
            "1229397900",
            "1274791798",
            "551151124",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-component-reproducibility-contract",
        path: "docs/reference/nuis-compiler-component-reproducibility-v1.toml",
        required_patterns: &[
            "nuis-compiler-component-reproducibility-v1",
            "nuis-compiler-two-clean-build-roots-v1",
            "nuis bootstrap-reproducibility",
            "compile_cache_status = \"bypass\"",
            "run_count = 2",
            "reproducible-equivalent-awaiting-authorization",
            "no-physical-paths-or-timestamps-in-aggregate",
            "replacement_authorized = false",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-component-reproducibility-artifact",
        path: "crates/nuis-artifact/src/compiler_component_reproducibility.rs",
        required_patterns: &[
            "COMPILER_COMPONENT_REPRODUCIBILITY_PROTOCOL",
            "COMPILER_COMPONENT_CLEAN_BUILD_CONTRACT",
            "build_compiler_component_reproducibility_from_paths",
            "read_compiler_component_reproducibility",
            "compile-cache bypass evidence",
            "two distinct build roots",
            "drifted across clean runs",
            "replacement_authorized: false",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-component-reproducibility-frontdoor",
        path: "tools/nuis/src/bootstrap_reproducibility.rs",
        required_patterns: &[
            "handle_bootstrap_reproducibility",
            "prepare_empty_output_root",
            "handle_bootstrap_clean_candidate_build",
            "clean-build-0",
            "clean-build-1",
            "build_compiler_component_reproducibility_from_paths",
            "bootstrap compiler reproducibility: verified",
            "replacement_authorized: false",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-component-reproducibility-native-regression",
        path: "tools/nuis/tests/compiler_structural_projection_candidate.rs",
        required_patterns: &[
            "bootstrap-reproducibility",
            "two_uncached_clean_candidates_bind_one_reproducibility_aggregate",
            "compile_cache_status.as_deref(), Some(\"bypass\")",
            "reproducible-equivalent-awaiting-authorization",
            "bound root tampering must invalidate aggregate",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-component-attestation-contract",
        path: "docs/reference/nuis-compiler-component-attestation-v1.toml",
        required_patterns: &[
            "nuis-compiler-component-attestation-v1",
            "nuis-compiler-component-attestation-ed25519-v1",
            "independent-machine-compiler-reproducibility-v1",
            "nuis-compiler-candidate-production-v11",
            "NUIS_COMPILER_ATTESTER_SIGNING_KEY_HEX",
            "exact-trust-registry-sha256-pin",
            "fixed-test-key-unit-coverage-plus-checked-in-separate-machine-generation-one-claim",
            "replacement_authorized = false",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-component-attester-registry-contract",
        path: "docs/reference/nuis-compiler-component-attester-trust-registry-v1.toml",
        required_patterns: &[
            "nuis-compiler-component-attester-trust-registry-v1",
            "sha256-of-exact-canonical-registry-source",
            "maximum_active_keys_per_environment = 1",
            "ed25519:sha256:<public-key-bytes>",
            "statuses = [\"active\", \"revoked\"]",
            "caller-owned-hash-pin",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-component-attestation-artifact",
        path: "crates/nuis-artifact/src/compiler_component_attestation.rs",
        required_patterns: &[
            "COMPILER_COMPONENT_ATTESTATION_PROTOCOL",
            "build_compiler_component_attestation",
            "verify_compiler_component_attestation",
            "first_production_proof_sha256",
            "second_production_proof_sha256",
            "expected_registry_sha256",
            "verify_strict",
            "replacement_authorized: false",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-component-attestation-registry-artifact",
        path: "crates/nuis-artifact/src/compiler_component_attestation_registry.rs",
        required_patterns: &[
            "COMPILER_COMPONENT_ATTESTER_TRUST_REGISTRY_PROTOCOL",
            "build_compiler_component_attester_trust_registry",
            "compiler_component_attester_trust_registry_sha256",
            "resolve_attester_key",
            "only one active key per environment",
            "revoked in the pinned registry",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-component-attestation-frontdoor-regression",
        path: "tools/nuis/tests/compiler_structural_projection_candidate.rs",
        required_patterns: &[
            "bootstrap-attest-reproducibility",
            "NUIS_COMPILER_ATTESTER_SIGNING_KEY_HEX",
            "linux-amd64-cleanroom",
            "bootstrap-verify-reproducibility-attestation",
            "bootstrap compiler attestation: verified",
            "candidate_production_protocol",
            "verifier request",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-component-replacement-authorization-contract",
        path: "docs/reference/nuis-compiler-component-replacement-authorization-v1.toml",
        required_patterns: &[
            "nuis-compiler-component-replacement-authorization-v1",
            "independent-ed25519-component-owner-transition",
            "nuis-compiler-component-replacement-authorizer-registry-v1",
            "same_identity_rejected = true",
            "same_public_key_rejected = true",
            "authorization_applies_transition = false",
            "replacement_authorized = true",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-component-replacement-authorization-artifact",
        path: "crates/nuis-artifact/src/compiler_component_replacement.rs",
        required_patterns: &[
            "COMPILER_COMPONENT_REPLACEMENT_AUTHORIZATION_PROTOCOL",
            "build_compiler_component_replacement_authorization",
            "verify_compiler_component_replacement_authorization",
            "rollback_reproducible_build_sha256",
            "authorizer_public_key_id == authorization.attester_public_key_id",
            "resolve_replacement_authorizer_key",
            "replacement_authorized: true",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-component-replacement-authorizer-registry-artifact",
        path: "crates/nuis-artifact/src/compiler_component_replacement_registry.rs",
        required_patterns: &[
            "COMPILER_COMPONENT_REPLACEMENT_AUTHORIZER_REGISTRY_PROTOCOL",
            "compiler-component-replacement-owner-v1",
            "build_compiler_component_replacement_authorizer_registry",
            "compiler_component_replacement_authorizer_registry_sha256",
            "resolve_replacement_authorizer_key",
            "revoked in the pinned registry",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-component-replacement-frontdoor-regression",
        path: "tools/nuis/tests/compiler_remote_attestation_evidence.rs",
        required_patterns: &[
            "bootstrap-authorize-component-replacement",
            "NUIS_COMPILER_REPLACEMENT_SIGNING_KEY_HEX",
            "bootstrap component replacement: authorized",
            "bootstrap-verify-component-replacement",
            "bootstrap component replacement: verified",
            "bootstrap-activate-component",
            "bootstrap compiler component: activated",
            "active_stage_role: stage1-candidate",
            "rollback_stage_role: stage0",
            "attestation_replacement_authorized",
            "reread immutable attestation",
            "reread immutable authorization",
            "verifier request",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-component-active-state-contract",
        path: "docs/reference/nuis-compiler-component-active-state-v1.toml",
        required_patterns: &[
            "nuis-compiler-component-active-state-v1",
            "nuis-compiler-active-component-selector-v1",
            "nuis bootstrap-activate-component",
            "active_stage_role = \"stage1-candidate\"",
            "rollback_stage_role = \"stage0\"",
            "authorization_source_mutated = false",
            "attestation_source_mutated = false",
            "signed-generation-two-rollback-or-forward-transition-chain",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-component-active-state-artifact",
        path: "crates/nuis-artifact/src/compiler_component_active_state.rs",
        required_patterns: &[
            "COMPILER_COMPONENT_ACTIVE_STATE_PROTOCOL",
            "build_compiler_component_active_state",
            "verify_compiler_component_active_state",
            "select_compiler_component_active_target",
            "CompilerComponentActiveSelection::Active",
            "CompilerComponentActiveSelection::Rollback",
            "compiler active-component state identity mismatch",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-try-expansion-compilation-local-counter",
        path: "tools/nuisc/src/frontend/stmt_lowering_try.rs",
        required_patterns: &[
            "thread_local!",
            "TRY_EXPANSION_COUNTER: Cell<usize>",
            "reset_try_expansion_counter",
            "next_try_expansion_id",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-try-expansion-reproducibility-regression",
        path: "tools/nuisc/src/frontend/tests_reproducibility.rs",
        required_patterns: &[
            "repeated_same_thread_lowering_resets_try_expansion_names",
            "lower_ast_to_nir(&ast)",
            "__nuis_try_result_0",
            "assert_eq!(first, second)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-token-decoder-artifact",
        path: "crates/nuis-artifact/src/compiler_token_decoder.rs",
        required_patterns: &[
            "nuis-compiler-token-decoder-v1",
            "decode_compiler_token_stream",
            "COMPILER_TOKEN_DECODER_MAX_BYTES",
            "COMPILER_TOKEN_DECODER_MAX_RECORDS",
            "fold_hex_payload",
            "fold_integer_payload",
            "fold_symbol_payload",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-token-decoder-stdlib",
        path: "stdlib/std/lib/compiler_tokens.ns",
        required_patterns: &[
            "mod cpu StdCompilerTokens",
            "compiler_token_decoder_step",
            "compiler_token_decoder_count_step",
            "compiler_token_decoder_semantic_step",
            "compiler_token_decoder_finish",
            "compiler_token_decoder_max_bytes",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-token-decoder-candidate-abi",
        path: "examples/projects/tooling/bootstrap_structural_projection_candidate/main.ns",
        required_patterns: &[
            "use cpu StdCompilerTokens",
            "nuis_bootstrap_candidate_token_start_v1",
            "nuis_bootstrap_candidate_token_step_v1",
            "nuis_bootstrap_candidate_token_semantic_step_v1",
            "nuis_bootstrap_candidate_token_finish_v1",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-token-pagination-artifact",
        path: "crates/nuis-artifact/src/compiler_token_pagination.rs",
        required_patterns: &[
            "nuis-compiler-token-pagination-v1",
            "COMPILER_TOKEN_PAGINATION_PAGE_BYTES",
            "compiler_token_pagination_identity",
            "decode_compiler_token_stream",
            "compiler_token_page_hash_step",
            "compiler_token_page_chain_fold",
            "chunks(COMPILER_TOKEN_PAGINATION_PAGE_BYTES)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-token-pagination-regression",
        path: "crates/nuis-artifact/src/compiler_token_pagination_tests.rs",
        required_patterns: &[
            "pagination_covers_long_records_and_a_partial_tail",
            "pagination_chain_is_replayable_and_binds_byte_ranges",
            "pagination_keeps_a_header_only_stream_as_one_complete_page",
            "page_hash_is_independently_replayable",
            "doc-comment",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-token-decoder-production-binding",
        path: "crates/nuis-artifact/src/compiler_candidate_production.rs",
        required_patterns: &[
            "nuis-compiler-candidate-production-v11",
            "token_decoder_contract",
            "token_record_count",
            "token_semantic_fold",
            "token_page_identity",
            "token_pagination_contract",
            "token_page_count",
            "token_terminal_page_hash",
            "token_page_chain_identity",
            "ast_page_identity",
            "nir_page_identity",
            "stage_transformations_sha256",
            "stage_semantic_differential_sha256",
            "stage_semantic_differential_proof_sha256",
            "stage_handoff_v2_sha256",
            "stage_handoff_v2_proof_sha256",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-candidate-production-contract",
        path: "docs/reference/nuis-compiler-candidate-production-v9.toml",
        required_patterns: &[
            "nuis-compiler-candidate-production-v9",
            "nuis-stage1-paginated-token-derived-nir-producer-v9",
            "stage1-candidate-component-production-no-replacement",
            "nuis bootstrap-candidate-build",
            "host-byte-and-opaque-cursor-transport-without-token-ast-or-nir-semantics",
            "nuis-compiler-stage-transformation-v2",
            "nuis-compiler-stage-semantic-differential-v1",
            "nuis-derived-structural-stage-payload-v1",
            "nuis-compiler-token-pagination-v1",
            "token-pages-are-contiguous-128-byte-windows-with-one-partial-tail",
            "reference_token_page_identity = 164749511446",
            "reference_ast_page_identity = 174028320749",
            "reference_ast_continuation_page_identity = 149528711957",
            "reference_nir_page_identity = 132469386887",
            "reference_nir_continuation_page_identity = 146705724977",
            "replacement_authorized = false",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-candidate-production-v10-contract",
        path: "docs/reference/nuis-compiler-candidate-production-v10.toml",
        required_patterns: &[
            "nuis-compiler-candidate-production-v10",
            "nuis-stage1-compact-structured-nir-producer-v10",
            "nuis-compiler-stage-transformation-v3",
            "nuis-compiler-structured-record-codec-v1",
            "nuis-derived-structural-records-v2",
            "compact-records-do-not-contain-one-contiguous-complete-source-blob",
            "compact-records-reparse-to-identical-ordinal-depth-kind-and-body-metadata",
            "replacement_authorized = false",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-candidate-production-v11-contract",
        path: "docs/reference/nuis-compiler-candidate-production-v11.toml",
        required_patterns: &[
            "nuis-compiler-candidate-production-v11",
            "nuis-compiler-candidate-production-v10",
            "nuis-stage1-compact-structured-nir-producer-v10",
            "nuis-bootstrap-candidate-scalar-output-v9",
            "current_selection_count = 2",
            "registered_derived_stages = [\"ast\", \"nir\"]",
            "nuis-compiler-stage-handoff-v2",
            "nuis-compiler-derived-stage-selection-v1",
            "candidate-driver-consumes-every-registered-selection-without-nir-index-special-casing",
            "every-selection-is-reversible-and-semantically-equivalent",
            "replacement_authorized = false",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-development-tensor-candidate-production-baseline",
        path: "docs/reference/nuis-development-tensor.md",
        required_patterns: &[
            "stage-neutral boundary to `usable/99`",
            "stage0/stage1 driver to `usable/99`",
            "differential/reproducibility gate at `usable/99`",
            "Data model v10 reaches `usable/99`",
            "24-byte `CompilerChunkedPayload`",
            "Active-state v1 now repeats both trust checks",
            "deterministic coordinate ordering remains at `compiler-toolchain/bootstrap/stage0-stage1-driver`",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-candidate-production-artifact",
        path: "crates/nuis-artifact/src/compiler_candidate_production.rs",
        required_patterns: &[
            "COMPILER_CANDIDATE_PRODUCTION_PROTOCOL",
            "COMPILER_CANDIDATE_PRODUCTION_AUTHORITY",
            "build_compiler_candidate_production",
            "read_compiler_candidate_production",
            "compiler_candidate_stage_fold",
            "compiler_candidate_bundle_fold",
            "ast_page_contract",
            "nir_page_contract",
            "stage_transformations_file",
            "stage_transformations_sha256",
            "stage_semantic_differential_file",
            "stage_semantic_differential_proof_sha256",
            "stage_handoff_v2_file",
            "stage_handoff_v2_proof_sha256",
            "replacement_authorized: false",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-candidate-production-validation",
        path: "crates/nuis-artifact/src/compiler_candidate_production_validation.rs",
        required_patterns: &[
            "canonical token pagination identity mismatch",
            "structural page chain mismatch",
            "verify_compiler_stage_transformations",
            "verify_compiler_stage_semantic_differential",
            "verify_compiler_stage_handoff_v2",
            "stage transformations do not bind its candidate producer",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-stage-transformation-contract",
        path: "docs/reference/nuis-compiler-stage-transformation-v2.toml",
        required_patterns: &[
            "nuis-compiler-stage-transformation-v2",
            "nuis-compiler-structural-checkpoint-v1",
            "nuis-derived-structural-stage-payload-v1",
            "output_word_count = 22",
            "complete-source-stage-payload:raw-bytes",
            "first_page_identity = 132469386887",
            "continuation_page_identity = 146705724977",
            "replacement_authorized = false",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-stage-transformation-v3-contract",
        path: "docs/reference/nuis-compiler-stage-transformation-v3.toml",
        required_patterns: &[
            "nuis-compiler-stage-transformation-v3",
            "nuis-compiler-structured-record-codec-v1",
            "nuis-derived-structural-records-v2",
            "current_source_stages = [\"ast\", \"nir\"]",
            "semantic_comparison_count = 2",
            "nuis-bootstrap-candidate-scalar-output-v9",
            "magic:NSCSTG02:8-bytes",
            "integer_encoding = \"canonical-unsigned-leb128\"",
            "complete_source_blob_embedded = false",
            "reparse-and-compare-every-record-ordinal-depth-kind-and-body",
            "replacement_authorized = false",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-stage-transformation-artifact",
        path: "crates/nuis-artifact/src/compiler_stage_transformation.rs",
        required_patterns: &[
            "COMPILER_STAGE_TRANSFORMATION_PROTOCOL",
            "compiler_stage_structural_checkpoint_words",
            "build_compiler_stage_transformations",
            "read_compiler_stage_transformations",
            "materialize_compiler_stage_transformation_payloads",
            "independent structural replay",
            "replacement_authorized: false",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-stage-transformation-payload-artifact",
        path: "crates/nuis-artifact/src/compiler_stage_transformation_payload.rs",
        required_patterns: &[
            "NSCSTG02",
            "encode_payload",
            "decode_payload",
            "push_varint",
            "read_varint",
            "parse_compiler_structural_projection",
            "structural record metadata mismatch",
            "validate_materialized_payloads",
            "failed lossless replay",
            "must be a regular file",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-stage-semantic-differential-contract",
        path: "docs/reference/nuis-compiler-stage-semantic-differential-v1.toml",
        required_patterns: &[
            "nuis-compiler-stage-semantic-differential-v1",
            "nuis-lossless-derived-stage-equivalence-v1",
            "exact-bound-stage-transformation-record",
            "nuis-derived-structural-records-v2",
            "nuis-compiler-stage-handoff-v2",
            "nuis-compiler-candidate-production-v11",
            "semantic-equivalent-derived-representation-awaiting-authorization",
            "source-and-derived-bytes-are-different",
            "current_comparison_count = 2",
            "current_source_stages = [\"ast\", \"nir\"]",
            "replacement_authorized = false",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-stage-handoff-v2-contract",
        path: "docs/reference/nuis-compiler-stage-handoff-v2.toml",
        required_patterns: &[
            "nuis-compiler-stage-handoff-v2",
            "nuis-compiler-derived-stage-selection-v1",
            "reversible-derived-stage-selection-no-replacement",
            "every-registered-transformation-has-one-same-ordinal-semantic-comparison",
            "selection-order-is-registration-order-without-stage-specific-driver-logic",
            "registered-ast-structured-record-codec-v1",
            "registered-nir-structured-record-codec-v1",
            "two-of-two-reversible-semantic-equivalence",
            "selection-does-not-authorize-canonical-stage-or-compiler-replacement",
            "replacement_authorized = false",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-stage-handoff-v2-artifact",
        path: "crates/nuis-artifact/src/compiler_stage_handoff_v2.rs",
        required_patterns: &[
            "COMPILER_STAGE_HANDOFF_V2_PROTOCOL",
            "CompilerStageSelectionRecord",
            "build_compiler_stage_handoff_v2",
            "read_compiler_stage_handoff_v2",
            "verify_compiler_stage_handoff_v2",
            "selection_for_stage",
            "replacement_authorized: false",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-stage-handoff-v2-registry-regression",
        path: "crates/nuis-artifact/src/compiler_stage_handoff_v2_tests.rs",
        required_patterns: &[
            "selects_every_registered_stage_without_stage_specific_protocol_logic",
            "CompilerStageKind::Ast",
            "CompilerStageKind::Nir",
            "selection_count, 2",
            "reader_replays_all_sibling_evidence_and_rejects_tampering",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-component-representation-differential-contract",
        path: "docs/reference/nuis-compiler-component-representation-differential-v1.toml",
        required_patterns: &[
            "nuis-compiler-component-representation-differential-v1",
            "nuis-compiler-selected-reversible-representation-comparison-v1",
            "every-registered-v2-selection-in-registration-order",
            "current_production_stages = [\"ast\", \"nir\"]",
            "current_comparison_count = 2",
            "no-stage-specific-selection-branch-is-permitted",
            "representation_report_bound_by_generation_one_aggregate = false",
            "replacement_authorized = false",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-component-representation-differential-artifact",
        path: "crates/nuis-artifact/src/compiler_component_representation_diff.rs",
        required_patterns: &[
            "CompilerComponentRepresentationDifferential",
            "build_compiler_component_representation_differential",
            "compare_compiler_component_representation_paths",
            "candidate_selected_payload_sha256",
            "candidate_recovered_payload_sha256",
            "replacement_authorized: false",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-component-representation-differential-regression",
        path: "crates/nuis-artifact/src/compiler_component_representation_diff_tests.rs",
        required_patterns: &[
            "registered_representations_are_compared_without_stage_specific_branches",
            "CompilerStageKind::Ast",
            "CompilerStageKind::Nir",
            "canonical_drift_remains_blocked_even_when_candidate_representation_is_reversible",
            "representation_report_tampering_fails_closed",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-component-representation-differential-frontdoor",
        path: "tools/nuisc/src/bootstrap_differential.rs",
        required_patterns: &[
            "compare_compiler_component_representation_paths",
            "COMPILER_COMPONENT_REPRESENTATION_DIFFERENTIAL_FILE",
            "selected_representations_equivalent",
            "representation_report_sha256",
            "all_representations_equivalent",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-stage-semantic-differential-artifact",
        path: "crates/nuis-artifact/src/compiler_stage_semantic_differential.rs",
        required_patterns: &[
            "COMPILER_STAGE_SEMANTIC_DIFFERENTIAL_PROTOCOL",
            "build_compiler_stage_semantic_differential",
            "read_compiler_stage_semantic_differential",
            "deterministic_semantic_equivalent",
            "byte_identical",
            "replacement_authorized: false",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-candidate-production-frontdoor",
        path: "tools/nuis/src/bootstrap_candidate_build.rs",
        required_patterns: &[
            "handle_bootstrap_candidate_build",
            "run_candidate_adapter",
            "build_compiler_stage_transformations",
            "materialize_compiler_stage_transformation_payloads",
            "build_compiler_stage_semantic_differential",
            "build_compiler_stage_handoff_v2",
            "read_compiler_stage_handoff_v2",
            "selected_derived_stages",
            "promote_compiler_component_candidate",
            "build_compiler_candidate_production",
            "BootstrapDiff",
            "equivalent-awaiting-authorization",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-candidate-production-native-regression",
        path: "tools/nuis/tests/compiler_structural_projection_candidate.rs",
        required_patterns: &[
            "bootstrap-candidate-build",
            "read_compiler_candidate_production",
            "COMPILER_COMPONENT_STAGE1_CANDIDATE_ROLE",
            "nuis-stage1-compact-structured-nir-producer-v10",
            "token_page_identity, 164_749_511_446",
            "production.token_page_count > 1",
            "production.token_terminal_page_hash > 0",
            "production.token_page_chain_identity > 0",
            "ast_page_identity, 174_028_320_749",
            "ast_continuation_page_identity, 149_528_711_957",
            "nir_page_identity, 132_469_386_887",
            "nir_continuation_page_identity, 146_705_724_977",
            "transformations.record_count, 2",
            "output_word_count, 22",
            "semantic_differential.equivalent_count, 2",
            "stage_handoff_v2.selection_count, 2",
            "equivalent_count, 13",
            "read_compiler_component_representation_differential",
            "representation_differential.equivalent_count, 2",
            "representation.byte_identical",
            "representation.candidate_recovered_payload_sha256",
            "stage transformation tampering must invalidate production proof",
            "derived stage payload tampering must invalidate production proof",
            "stage handoff v2 tampering must invalidate production proof",
            "adapter tampering must invalidate production proof",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-remote-attestation-evidence-index",
        path: "docs/evidence/compiler-attestation/linux-amd64-cleanroom/generation-1/nuis.compiler-component-remote-evidence.toml",
        required_patterns: &[
            "nuis-compiler-component-remote-evidence-v1",
            "verified-separate-machine",
            "kyuubiki-lab-1",
            "linux-amd64-cleanroom",
            "90b8f7f4c9d336c72caa7dc4dc9a91c41ec263a7bfffa282ee8211088b164f01",
            "random-seed-generated-and-retained-on-attester-only",
            "wrong_challenge_fails_closed = true",
            "wrong_registry_pin_fails_closed = true",
            "physical_machine_independence_cryptographically_proven = false",
            "replacement_authorized = false",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-remote-attestation-claim",
        path: "docs/evidence/compiler-attestation/linux-amd64-cleanroom/generation-1/nuis.compiler-component-attestation.toml",
        required_patterns: &[
            "nuis-compiler-component-attestation-v1",
            "d5aeef8c1d33a5b473f11142197fd361df26dc0f2ec1c0188362f9ece139338c",
            "c7fc7ae1490a78af36ab5dee6fd57815265b1874ba09f3680f36d3ccb684cd14",
            "ed25519:sha256:c2819cec7c31d85e4c5acaae10b852966fb8979ec3a4030233d207a866adfaca",
            "f29add6af3377892852a2d21366563f3366ac4c69cbbb6ae5b28649f246aedcd",
            "replacement_authorized = false",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-remote-attestation-trust-registry",
        path: "docs/evidence/compiler-attestation/linux-amd64-cleanroom/generation-1/nuis.compiler-component-attester-trust-registry.toml",
        required_patterns: &[
            "nuis-compiler-component-attester-trust-registry-v1",
            "generation = 1",
            "independent-machine-compiler-reproducibility-v1",
            "b92387677cc1c63d8418d86b85183574386475a5c720e06bcd405097fb2f7355",
            "status = \"active\"",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-remote-attestation-regression",
        path: "tools/nuis/tests/compiler_remote_attestation_evidence.rs",
        required_patterns: &[
            "checked_in_remote_attestation_verifies_and_fails_closed",
            "read_compiler_component_attestation",
            "90b8f7f4c9d336c72caa7dc4dc9a91c41ec263a7bfffa282ee8211088b164f01",
            "challenge replay must fail closed",
            "unpinned registry bytes must fail closed",
            "replacement_authorized",
        ],
    },
];
