use crate::dev_tensor_drift::DevTensorDriftCheckSpec;

pub(crate) const DEV_TENSOR_RUNTIME_CURRENT_DRIFT_CHECKS: &[DevTensorDriftCheckSpec] = &[
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-data-model-v11-contract",
        path: "docs/reference/nuis-compiler-data-model-v11.toml",
        required_patterns: &[
            "nuis-compiler-data-model-v11",
            "nuis-compiler-data-model-v10",
            "surface.std.compiler-data-model.v11",
            "nuis-compiler-complete-aggregate-forwarding-v1",
            "boundary_count = 2",
            "reference_registry_identity = 1593840720",
            "reference_identity = 551151124",
            "status = \"stable\"",
            "progress = 100",
            "new_scalar_exports = 0",
            "expected_native_exit = 130",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-data-model-v11-forwarding-stdlib",
        path: "stdlib/std/lib/compiler_payload_registry.ns",
        required_patterns: &[
            "pub fn compiler_aggregate_arena_forward_checked",
            "expected_registry_identity: i64",
            "expected_arena_identity: i64",
            "pub fn compiler_aggregate_arena_forward",
            "forwarded_registry_identity",
            "forwarded_arena_identity",
            "return Result.Ok(forwarded)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-data-model-v11-native-forwarding",
        path: "examples/projects/tooling/bootstrap_compiler_data_model_demo/payload_registry_fixture.ns",
        required_patterns: &[
            "let forwarded: CompilerAggregateArena",
            "compiler_aggregate_arena_forward",
            "wrong_registry_error",
            "identity_after_wrong_registry",
            "wrong_registry_error != 3",
            "identity_after_wrong_registry != chunked_identity",
            "chunked_identity != 551151124",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-data-provider-inventory-v1-contract",
        path: "docs/reference/nuis-data-provider-inventory-v1.toml",
        required_patterns: &[
            "nuis-data-provider-inventory-v1",
            "nuis-provider-capability-record-v1",
            "fnv1a64:4e27319a33087b95",
            "data.cpu-memory.reference.v1",
            "priority-desc-provider-id-asc",
            "fnv1a64:a5de1600823540c6",
            "nuis-provider-capability-availability-v1",
            "execution.physical",
            "physical_dpu_claimed = false",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-ns-nova-application-lifecycle-v1-contract",
        path: "docs/reference/nuis-ns-nova-application-lifecycle-v1.toml",
        required_patterns: &[
            "nuis-ns-nova-application-lifecycle-v1",
            "progress = 54",
            "owned-state-transition",
            "abstract-monotonic-step",
            "host-auto-recommended",
            "window-and-fabric-boot-observed",
            "cross-domain-result-state-projection-verified",
            "three-frame-nuis-update-loop-verified",
            "typed-capture-validate-submit-verified",
            "stable_interactive_loop_claimed = false",
            "conditional_present_lowering = true",
            "cross_domain_result_state_projection = true",
            "bounded_update_loop = true",
            "runtime_owned_result_handle = true",
            "dynamic_cross_domain_present_predicate = false",
            "loop_carried_application_state = false",
            "compiler_special_cases = 0",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-ns-nova-owned-app-runtime",
        path: "stdlib/ns-nova/lib/app_runtime.ns",
        required_patterns: &[
            "pub struct NovaAppState",
            "pub struct NovaFrameTransaction",
            "pub struct NovaFrameResultHandle",
            "pub fn open(",
            "pub fn begin_frame(",
            "pub fn capture_frame_result(",
            "pub fn frame_result_ready(",
            "pub fn submit_frame(",
            "pub fn commit_frame(",
            "pub fn close(",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-ns-nova-showcase-project",
        path: "examples/projects/domains/ns_nova_showcase/nuis.toml",
        required_patterns: &[
            "ns_nova_showcase",
            "ns-nova=workspace",
            "pixelmagic=workspace",
            "ns-nova:lib/app_runtime.ns",
            "cpu.Main -> shader.PixelMagicRenderSurface via data.FabricPlane",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-ns-nova-showcase-galaxy-package",
        path: "examples/projects/domains/ns_nova_showcase/galaxy.toml",
        required_patterns: &[
            "package_kind = \"nuis-framework\"",
            "framework = \"ns-nova\"",
            "project = \"nuis.toml\"",
            "\"ns-nova.toml\"",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-ns-nova-showcase-framework-profile",
        path: "examples/projects/domains/ns_nova_showcase/ns-nova.toml",
        required_patterns: &[
            "ns-nova-manifest-v1",
            "entry_cpu_unit = \"cpu.Main\"",
            "render_bridge_unit = \"data.FabricPlane\"",
            "render_surface_unit = \"shader.PixelMagicRenderSurface\"",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-ns-nova-showcase-regression",
        path: "tools/nuisc/src/project/tests/ns_nova_runtime.rs",
        required_patterns: &[
            "compiles_ns_nova_lifecycle_with_pixelmagic_rendering",
            "NovaAppRuntime.begin_frame",
            "NovaAppRuntime.capture_frame_result",
            "NovaAppRuntime.submit_frame",
            "PixelMagicRenderSurface",
            "inline_wgsl",
            "branch_effect",
            "present_frame",
            "present_requested",
            "projected shader.observe",
            "loop_while_i64_effect",
            "render_showcase_frame",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "yir-domain-result-state-projection",
        path: "crates/yir-lower-llvm/src/preclassified_lowering.rs",
        required_patterns: &[
            "lower_domain_result_observer_node",
            "YirResultRole::StateProbe",
            "LlvmValueRef::DomainResult",
            "payload remains {family}-provider-owned",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-ns-nova-conditional-present-runtime",
        path: "crates/yir-domain-cpu/src/tests_branch_effect.rs",
        required_patterns: &[
            "branch_effect_presents_a_frame_only_when_selected",
            "BranchEffectAccess::ValueRead",
            "effect cpu.present_frame",
            "state.events.is_empty()",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-ns-nova-conditional-present-llvm",
        path: "crates/yir-lower-llvm/src/tests/branch_effect_tests.rs",
        required_patterns: &[
            "conditional_present_preserves_control_flow_at_the_host_adapter_boundary",
            "branch_effect_then",
            "branch_effect_else",
            "cpu.present_frame frame remains a host-adapter boundary",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuisc-provider-capability-registration-schema",
        path: "tools/nuisc/src/registry_provider_capability.rs",
        required_patterns: &[
            "nuis-provider-capability-record-v1",
            "NustarProviderCapabilityRegistration",
            "provider_capability_registrations",
            "six ordered fields",
            "strictly sorted and unique",
            "priority must be positive",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-data-provider-conformance-v1-contract",
        path: "docs/reference/nuis-data-provider-conformance-v1.toml",
        required_patterns: &[
            "nuis-data-provider-conformance-v1",
            "nuis-provider-conformance-capsule-v1",
            "nuis-provider-conformance-replay-v1",
            "fnv1a64:82270e31b99f2c0b",
            "fnv1a64:7ee93c8f8a4ae011",
            "execution_authority = \"conformance-only\"",
            "physical_execution_claimed = false",
            "grants_physical_certification = false",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-data-provider-conformance-replay",
        path: "tools/nsdb/src/provider_conformance_capsule.rs",
        required_patterns: &[
            "nuis-provider-conformance-capsule-v1",
            "nuis-provider-conformance-replay-v1",
            "data_reference_conformance_capsule",
            "replay_provider_conformance_capsule",
            "provider-conformance-replay:capsule-drift",
            "provider-conformance-replay:clock-order-invalid",
            "provider-conformance-replay:glm-release-missing",
            "provider-conformance-replay:physical-authority-forbidden",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nustar-data-provider-capability-registration",
        path: "nustar-packages/data.toml",
        required_patterns: &[
            "provider_capabilities",
            "data.cpu-memory.reference.v1",
            "data.host.bundle.v1",
            "clock.fabric-monotonic",
            "completion.verified",
            "execution.reference",
            "glm.owned-transfer",
            "memory.cpu",
            "movement.copy",
            "residency.host",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-provider-capability-aot-generator",
        path: "tools/nsdb/build.rs",
        required_patterns: &[
            "provider_capability_registrations",
            "canonical_capability_manifest",
            "nuis-provider-capability-manifest-v1",
            "PROVIDER_CAPABILITY_MANIFEST_HASH",
            "provider_capability_registry_generated.rs",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-provider-capability-selection",
        path: "tools/nsdb/src/provider_capability_registry.rs",
        required_patterns: &[
            "nuis-provider-capability-registry-v1",
            "nuis-provider-capability-selection-v1",
            "select_provider_capability",
            "canonical_requirements",
            "duplicate-requirement",
            "provider-capability-selection:unsupported",
            "provider-capability-selection:provider-unavailable",
            "provider_entry_is_available",
            "rhs.priority",
            "lhs.provider_id",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-cpu-memory-reference-execution",
        path: "tools/nsdb/src/provider_sample_execute_tests.rs",
        required_patterns: &[
            "executes_registered_native_worker_with_two_graph_outputs",
            "data.cpu-memory.reference.v1",
            "fnv1a64:4e27319a33087b95",
            "fnv1a64:01cb51b49b12a49e",
            "provider_capability_availability_status",
            "nuis-provider-completion-evidence-v1",
            "nuis-provider-glm-release-evidence-v1",
            "nuis-provider-completion-clock-v1",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-provider-conformance-completion-binding",
        path: "tools/nsdb/src/provider_completion_evidence.rs",
        required_patterns: &[
            "ProviderConformanceLifecycleEvidence",
            "completion_evidence_from_output",
            "render_completion_event_fields",
            "parse_completion_event_fields",
            "append_completion_hash_material",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-provider-conformance-lifecycle-gate",
        path: "tools/nsld/src/final_executable_output_conformance.rs",
        required_patterns: &[
            "validate_provider_conformance_evidence",
            "PROVIDER_CONFORMANCE_CAPSULE_CONTRACT",
            "PROVIDER_CONFORMANCE_REPLAY_CONTRACT",
            "PROVIDER_CONFORMANCE_EXECUTION_AUTHORITY",
            "physical-execution-claim-forbidden",
            "not-applicable-evidence-not-empty",
            "provider-family-mismatch",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-provider-conformance-final-output-projection",
        path: "tools/nsld/src/json_final_output_provider_completion.rs",
        required_patterns: &[
            "conformance_json",
            "capability_selection_hash",
            "capsule_hash",
            "replay_hash",
            "execution_authority",
            "physical_execution_claimed",
        ],
    },
];
