use crate::dev_tensor_drift::DevTensorDriftCheckSpec;

pub(crate) const DEV_TENSOR_RUNTIME_DEV_DRIFT_CHECKS: &[DevTensorDriftCheckSpec] = &[
    DevTensorDriftCheckSpec {
        id: "language-bootstrap-result-constructor-ambiguity",
        path: "tools/nuisc/src/frontend/tests_generics/zero_arg_expectations.rs",
        required_patterns: &[
            "reports_unconstrained_result_constructor_missing_generic_evidence",
            "keeps_result_constructor_inference_when_let_binding_provides_expected_type",
            "keeps_result_constructor_inference_through_nested_if_match_expected_type",
            "ambiguous Result constructor `Result.Ok(...)`",
            "could not infer `E`",
            "expected type `Result<T, E>`",
            "let result: Result<i64, Error> = Result.Ok(7)",
            "let result: Result<i64, Error> = if flag == 1",
            "Result.Err(Error.Invalid)",
            "branch_binds_result_variant(match_else_body, \"Result.Err\", [\"i64\", \"Error\"], 0)",
            "type_name == \"Result.Ok\"",
            "ty.render() == \"Result<i64, Error>\"",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "language-bootstrap-no-annotation-try-await-hof",
        path: "tools/nuisc/src/frontend/tests_generics/nested_async.rs",
        required_patterns: &[
            "monomorphizes_no_annotation_try_await_result_binding_through_higher_order_mapper",
            "let mapped = map_result",
            "await fetch(seed)?",
            "Result<i64, Error>",
            "__hof_map_result___lambda_compute_0",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "dev-tensor-status-task-card-frontdoor",
        path: "tools/nuis/src/main.rs",
        required_patterns: &[
            "dev_tensor_weakest_task_card_protocol",
            "dev_tensor_weakest_task_card_source",
            "dev_tensor_weakest_task_card_status",
            "dev_tensor_weakest_task_card_ready",
            "dev_tensor_weakest_task_card_coordinate",
            "dev_tensor_weakest_task_card_action",
            "dev_tensor_weakest_task_card_command",
            "dev_tensor_weakest_task_card_expected_artifact",
            "weakest_bootstrap_task_card_protocol",
            "weakest_bootstrap_task_card_source",
            "weakest_bootstrap_task_card_status",
            "weakest_bootstrap_task_card_ready",
            "weakest_bootstrap_task_card_coordinate",
            "weakest_bootstrap_task_card_action",
            "weakest_bootstrap_task_card_command",
            "weakest_bootstrap_task_card_expected_artifact",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "dev-tensor-coverage-doc",
        path: "docs/reference/nuis-development-tensor.md",
        required_patterns: &[
            "Coverage Manifest",
            "Status Protocol",
            "Recursive Hierarchy",
            "dev-tensor-status-v1",
            "hierarchy_root_status",
            "weakest_child_path",
            "weakest_bootstrap_status",
            "weakest_bootstrap_evidence",
            "weakest_bootstrap_next_step",
            "weakest_bootstrap_blocker",
            "weakest_bootstrap_next_action",
            "weakest_bootstrap_validation_command",
            "weakest_bootstrap_expected_artifact",
            "weakest_bootstrap_task_card_protocol",
            "weakest_bootstrap_task_card_source",
            "weakest_bootstrap_task_card_status",
            "weakest_bootstrap_task_card_ready",
            "weakest_bootstrap_task_card_coordinate",
            "weakest_bootstrap_task_card_priority_reason",
            "weakest_bootstrap_task_card_action",
            "weakest_bootstrap_task_card_command",
            "weakest_bootstrap_task_card_expected_artifact",
            "nuis-dev-tensor-task-card-v1",
            "validation_command",
            "expected_artifact",
            "Manifest-Backed Coordinate Coverage",
            "Milestone-Owned Coordinate Coverage",
            "coverage_expected_source",
            "coverage_expected_fallback_used",
            "manifest_coverage_status",
            "manifest_backed_coordinates",
            "manifest_untracked_modules",
            "milestone_coverage_status",
            "milestone_coordinates",
            "milestone_derived_cache_protocol",
            "milestone_derived_cache_status",
            "milestone_derived_cache_key",
            "milestone_constant_drift_count",
            "coverage_status",
            "coverage_missing_coordinates",
            "coverage_orphaned_coordinates",
            "coverage_stale_coordinates",
            "coverage_first_gap",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "dev-tensor-manifest-derived-coverage",
        path: "tools/nuis/src/dev_tensor_manifest.rs",
        required_patterns: &[
            "DevTensorManifestCoverage",
            "dev_tensor_manifest_coverage",
            "stdlib/index.toml",
            "manifest_backed_coordinates",
            "manifest_untracked_modules",
            "standard-library/std/host-io-filesystem-text",
            "standard-library/pixelmagic/image-processing-lane",
            "standard-library/witsage/classical-ml-lane",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "dev-tensor-milestone-coordinate-manifest",
        path: "docs/reference/nuis-development-tensor.milestones.toml",
        required_patterns: &[
            "nuis-dev-tensor-milestones-v1",
            "alpha-governance",
            "alpha-official-galaxy",
            "required = false",
            "developer-system/dev-tensor/architecture-module-function-progress-model",
            "standard-library/std/host-io-filesystem-text",
            "linker-toolchain/nsld/final-output-boundary",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "dev-tensor-milestone-derived-coverage",
        path: "tools/nuis/src/dev_tensor_milestones.rs",
        required_patterns: &[
            "DevTensorMilestoneCoverage",
            "DevTensorDerivedExpectedCoordinate",
            "dev_tensor_milestone_coverage",
            "expected_coordinates_from_milestones",
            "nuis-development-tensor.milestones.toml",
            "nuis-dev-tensor-derived-coordinate-cache-v1",
            "derived_coordinate_cache_key",
            "milestone_constant_drift_count",
            "missing-from-milestone-manifest",
            "fallback_used",
        ],
    },
];
