use crate::dev_tensor_drift::DevTensorDriftCheckSpec;

pub(crate) const DEV_TENSOR_RUNTIME_DEV_DRIFT_CHECKS: &[DevTensorDriftCheckSpec] = &[
    DevTensorDriftCheckSpec {
        id: "nsdb-cursor-lineage-repair-journal",
        path: "tools/nsdb/src/cursor_lineage_repair_journal.rs",
        required_patterns: &[
            "nsdb-yir-replay-cursor-lineage-repair-journal-v5",
            "nuis.nsdb.replay-cursor.lineage-repairs.toml",
            "pub(super) fn record",
            "pub(super) fn preflight",
            "persist_validated_content_atomically",
            "archived_repair_journal_path",
            "archived_hash",
            "rebuilt_hash",
            "previous_event_hash",
            "current_event_hash",
            "event_hash",
            "rotation_generation",
            "evicted_prefix_hash",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-cursor-lineage-repair-journal-mirror",
        path: "tools/nuis/src/artifact_nsdb_replay_cursor_lineage.rs",
        required_patterns: &[
            "nuis-debugger-cursor-lineage-repair-mirror-v1",
            "repair-history-unavailable",
            "repair-history-invalid",
            "repair-history-ready",
            "validate_repair_journal",
            "latest_archived_hash",
            "latest_rebuilt_hash",
            "latest_event_status",
            "latest_lineage_mutated",
            "latest_repair_journal_mutated",
            "latest_archived_repair_journal_hash",
            "previous_event_hash",
            "current_event_hash",
            "repair_event_hash",
            "rotation_generation",
            "evicted_prefix_hash",
            "repair_window_hash",
            "repair-history-contract-invalid",
            "repair-cursor-lineage-history",
            "nuis debug-lineage-repair",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-debugger-cursor-lineage-repair-frontdoor",
        path: "tools/nuis/src/debug_lineage_repair_command.rs",
        required_patterns: &[
            "handle_debug_lineage_repair",
            "resolve_artifact_output_input",
            "read_debugger_cursor_lineage",
            "lineage-unavailable",
            "resolve_nsdb_program",
            "cursor-lineage-repair",
            "--json",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-cursor-lineage-repair-final-output",
        path: "tools/nuis/src/workflow/link_plan_final_output_summary.rs",
        required_patterns: &[
            "debugger_cursor_lineage_repair_rotation_generation",
            "debugger_cursor_lineage_repair_evicted_prefix_hash",
            "debugger_cursor_lineage_repair_window_hash",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-cursor-lineage-repair-closure-json",
        path: "tools/nuis/src/closure_summary_lineage_repair_json.rs",
        required_patterns: &[
            "closure_summary_debugger_cursor_lineage_repair_rotation_generation",
            "closure_summary_debugger_cursor_lineage_repair_evicted_prefix_hash",
            "closure_summary_debugger_cursor_lineage_repair_window_hash",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-debugger-cursor-lineage-repair-cli",
        path: "tools/nuis/src/cli.rs",
        required_patterns: &[
            "DebugLineageRepair",
            "debug-lineage-repair",
            "parse_required_json_input",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-debugger-cursor-lineage-repair-official-smoke",
        path: "tools/nuis/tests/official_galaxy_hetero_smoke.rs",
        required_patterns: &[
            "nuis debug-lineage-repair",
            "run_nuis(&[\"debug-lineage-repair\"",
            "nsdb-yir-replay-cursor-lineage-repair-v2",
            "repair-history-recovered",
            "lineage_mutated",
            "repair_journal_mutated",
            "lineage-rebuilt",
            "archived_path",
            "archived_repair_journal_path",
            "repair_rotation_generation",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "language-bootstrap-result-constructor-ambiguity",
        path: "tools/nuisc/src/frontend/tests_generics/zero_arg_expectations.rs",
        required_patterns: &[
            "reports_unconstrained_result_constructor_missing_generic_evidence",
            "keeps_result_constructor_inference_when_let_binding_provides_expected_type",
            "keeps_result_constructor_inference_through_nested_if_match_expected_type",
            "ambiguous Result constructor `Result.Ok(...)`",
            "could not infer `E`",
            "expected type `Result<T, E>`",
            "let result: Result<i64, Error> = Result.Ok(7)",
            "let result: Result<i64, Error> = if flag == 1",
            "Result.Err(Error.Invalid)",
            "branch_binds_result_variant(match_else_body, \"Result.Err\", [\"i64\", \"Error\"], 0)",
            "type_name == \"Result.Ok\"",
            "ty.render() == \"Result<i64, Error>\"",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "language-bootstrap-no-annotation-try-await-hof",
        path: "tools/nuisc/src/frontend/tests_generics/nested_async.rs",
        required_patterns: &[
            "monomorphizes_no_annotation_try_await_result_binding_through_higher_order_mapper",
            "let mapped = map_result",
            "await fetch(seed)?",
            "Result<i64, Error>",
            "__hof_map_result___lambda_compute_0",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "dev-tensor-status-task-card-frontdoor",
        path: "tools/nuis/src/main.rs",
        required_patterns: &[
            "dev_tensor_weakest_task_card_protocol",
            "dev_tensor_weakest_task_card_source",
            "dev_tensor_weakest_task_card_status",
            "dev_tensor_weakest_task_card_ready",
            "dev_tensor_weakest_task_card_coordinate",
            "dev_tensor_weakest_task_card_action",
            "dev_tensor_weakest_task_card_command",
            "dev_tensor_weakest_task_card_expected_artifact",
            "dev_tensor_weakest_task_card_handoff_mode",
            "dev_tensor_weakest_task_card_handoff_coordinate",
            "dev_tensor_weakest_task_card_handoff_action",
            "dev_tensor_weakest_task_card_handoff_command",
            "weakest_bootstrap_task_card_protocol",
            "weakest_bootstrap_task_card_source",
            "weakest_bootstrap_task_card_status",
            "weakest_bootstrap_task_card_ready",
            "weakest_bootstrap_task_card_coordinate",
            "weakest_bootstrap_task_card_action",
            "weakest_bootstrap_task_card_command",
            "weakest_bootstrap_task_card_expected_artifact",
            "weakest_bootstrap_task_card_handoff_mode",
            "weakest_bootstrap_task_card_handoff_coordinate",
            "weakest_bootstrap_task_card_handoff_action",
            "weakest_bootstrap_task_card_handoff_command",
            "frontdoor_reading_order",
            "frontdoor_sample_closure_summary",
            "frontdoor_sample_tensor_handoff",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-provider-sample-executor",
        path: "tools/nsdb/src/provider_sample_execute.rs",
        required_patterns: &[
            "execute_provider_samples",
            "provider-output-payloads-ready",
            "render_real_device_provider_output_payload",
            "provider_output_payload_file_name",
            "fnv1a64_hex",
            "matched_record_count",
            "first_provider_runner_adapter_id",
            "first_provider_runner_real_device_probe_status",
            "first_provider_execution_mode",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-provider-sample-runner-registry",
        path: "tools/nsdb/src/provider_sample_runner.rs",
        required_patterns: &[
            "ProviderSampleRunner",
            "provider_runner_for",
            "provider_execution_for",
            "provider_execution_outcome_for_runner",
            "nuis-provider-runner-adapter-v1",
            "nuis-provider-runner-registry-v1",
            "builtin-nustar-provider-runner-registry",
            "metal:apple-silicon-gpu",
            "coreml:apple-ane",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-provider-sample-payload-contract",
        path: "tools/nsdb/src/provider_sample_payload.rs",
        required_patterns: &[
            "ProviderOutputPayload",
            "ProviderOutputPayloadSummary",
            "provider_output_payload",
            "provider_output_payload_from_record",
            "provider_output_payload_summary",
            "render_real_device_provider_output_payload",
            "validate_provider_output_payload",
            "nuis-provider-output-payload-v1",
            "nsdb-provider-output-payload-v1",
            "nuis-provider-sample-execution-v1",
            "input_evidence_hash",
            "provider-output-payload-rejected",
            "repair-provider-output-payload",
            "deterministic-provider-output-payload",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-provider-completion-handoff",
        path: "tools/nsdb/src/handoff.rs",
        required_patterns: &[
            "persist_payload_execution_handoff_record",
            "persist_provider_completion_handoff",
            "provider-device-completion",
            "replay-provider-completion",
            "nsdb-provider-sample-materialization",
            "provider_family",
            "output_contract",
            "output_evidence",
            "nuis-provider-completion-digest-fnv1a64-v1",
            "nuis-provider-completion-digest-sha256-v1",
            "nuis-provider-completion-digest-sha256-authority-v1",
            "nuis-provider-completion-claim-authority-v1",
            "provider-completion-set-v2",
            "provider-completion-set-v3",
            "provider-completion-set-v4",
            "provider-completion-digest-contract-unsupported",
            "provider_completion_set_hash",
            "provider completion digest validation failed",
            "provider completion authority validation failed",
            "authority-untrusted",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-provider-completion-closure-mirror",
        path: "tools/nuis/src/closure_summary.rs",
        required_patterns: &[
            "ProviderCompletionClosureMirror",
            "closure_summary_provider_completion_count",
            "closure_summary_first_provider_family",
            "closure_summary_first_provider_output_contract",
            "closure_summary_first_provider_output_evidence",
            "closure_summary_provider_completion_claim_authority_contract",
            "closure_summary_provider_completion_claim_authority",
            "closure_summary_provider_completion_claim_authority_status",
            "closure_summary_provider_completion_digest_contract",
            "closure_summary_provider_completion_set_hash_claim",
            "closure_summary_provider_completion_set_hash",
            "closure_summary_provider_completion_set_hash_validation_status",
            "closure_summary_provider_completions",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-provider-completion-collection-summary",
        path: "tools/nsdb/src/lib.rs",
        required_patterns: &[
            "PayloadExecutionProviderCompletion",
            "provider_completion_digest_contract",
            "provider_completion_set_hash",
            "provider_completion_collection_preserves_order_and_hashes_records",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-independent-provider-completion-collection",
        path: "tools/nuis/src/artifact_nsdb_handoff.rs",
        required_patterns: &[
            "PersistedProviderCompletion",
            "provider_completion_claim_authority_status",
            "provider_completion_digest_contract",
            "provider_completion_set_hash_claim",
            "provider_completion_set_hash",
            "provider_completion_set_hash_validation_status",
            "provider-completion-set-hash-mismatch",
            "provider-completion-digest-contract-unsupported",
            "provider_completions",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-independent-provider-completion-contract-tests",
        path: "tools/nuis/src/artifact_nsdb_handoff_tests.rs",
        required_patterns: &[
            "legacy-unclaimed",
            "legacy-verified",
            "nuis-provider-completion-digest-fnv1a64-v1",
            "nuis-provider-completion-digest-sha256-v1",
            "nuis-provider-completion-digest-sha256-authority-v1",
            "authority-missing",
            "authorized",
            "unsupported-digest-contract",
            "provider-completion-set-hash-mismatch",
            "coreml:apple-ane",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-provider-completion-sha256",
        path: "tools/nsdb/src/digest_sha256.rs",
        required_patterns: &[
            "sha256_hex",
            "e3b0c44298fc1c149afbf4c8996fb924",
            "ba7816bf8f01cfea",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-provider-completion-sha256",
        path: "tools/nuis/src/digest_sha256.rs",
        required_patterns: &[
            "sha256_hex",
            "e3b0c44298fc1c149afbf4c8996fb924",
            "ba7816bf8f01cfea",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-provider-completion-replay-overlay",
        path: "tools/nsdb/src/replay.rs",
        required_patterns: &[
            "projected_hetero_runtime_events",
            "provider-device-completion",
            "event.trace_id == completion.trace_id",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-preserves-provider-completion-handoff",
        path: "tools/nsld/src/main_final_executable_output_nsdb_handoff_tests.rs",
        required_patterns: &[
            "provider-device-completion",
            "metal:apple-silicon-gpu",
            "final_output_nsdb_handoff_record_count, 2",
            "final_output_nsdb_replay_checkpoint_count, 2",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "dev-tensor-coverage-doc",
        path: "docs/reference/nuis-development-tensor.md",
        required_patterns: &[
            "Coverage Manifest",
            "Status Protocol",
            "Recursive Hierarchy",
            "dev-tensor-status-v1",
            "hierarchy_root_status",
            "weakest_child_path",
            "weakest_bootstrap_status",
            "weakest_bootstrap_evidence",
            "weakest_bootstrap_next_step",
            "weakest_bootstrap_blocker",
            "weakest_bootstrap_next_action",
            "weakest_bootstrap_validation_command",
            "weakest_bootstrap_expected_artifact",
            "weakest_bootstrap_task_card_protocol",
            "weakest_bootstrap_task_card_source",
            "weakest_bootstrap_task_card_status",
            "weakest_bootstrap_task_card_ready",
            "weakest_bootstrap_task_card_coordinate",
            "weakest_bootstrap_task_card_priority_reason",
            "weakest_bootstrap_task_card_action",
            "weakest_bootstrap_task_card_command",
            "weakest_bootstrap_task_card_expected_artifact",
            "weakest_bootstrap_task_card_handoff_mode",
            "weakest_bootstrap_task_card_handoff_coordinate",
            "weakest_bootstrap_task_card_handoff_reason",
            "weakest_bootstrap_task_card_handoff_action",
            "weakest_bootstrap_task_card_handoff_command",
            "weakest_bootstrap_task_card_handoff_expected_artifact",
            "nuis-dev-tensor-task-card-v1",
            "validation_command",
            "expected_artifact",
            "Manifest-Backed Coordinate Coverage",
            "Milestone-Owned Coordinate Coverage",
            "coverage_expected_source",
            "coverage_expected_fallback_used",
            "manifest_coverage_status",
            "manifest_backed_coordinates",
            "manifest_untracked_modules",
            "milestone_coverage_status",
            "milestone_coordinates",
            "milestone_derived_cache_protocol",
            "milestone_derived_cache_status",
            "milestone_derived_cache_key",
            "milestone_constant_drift_count",
            "coverage_status",
            "coverage_missing_coordinates",
            "coverage_orphaned_coordinates",
            "coverage_stale_coordinates",
            "coverage_first_gap",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "dev-tensor-manifest-derived-coverage",
        path: "tools/nuis/src/dev_tensor_manifest.rs",
        required_patterns: &[
            "DevTensorManifestCoverage",
            "dev_tensor_manifest_coverage",
            "stdlib/index.toml",
            "manifest_backed_coordinates",
            "manifest_untracked_modules",
            "standard-library/std/host-io-filesystem-text",
            "standard-library/pixelmagic/image-processing-lane",
            "standard-library/witsage/classical-ml-lane",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "dev-tensor-milestone-coordinate-manifest",
        path: "docs/reference/nuis-development-tensor.milestones.toml",
        required_patterns: &[
            "nuis-dev-tensor-milestones-v1",
            "alpha-governance",
            "alpha-official-galaxy",
            "required = false",
            "developer-system/dev-tensor/architecture-module-function-progress-model",
            "standard-library/std/host-io-filesystem-text",
            "linker-toolchain/nsld/final-output-boundary",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "dev-tensor-milestone-derived-coverage",
        path: "tools/nuis/src/dev_tensor_milestones.rs",
        required_patterns: &[
            "DevTensorMilestoneCoverage",
            "DevTensorDerivedExpectedCoordinate",
            "dev_tensor_milestone_coverage",
            "expected_coordinates_from_milestones",
            "nuis-development-tensor.milestones.toml",
            "nuis-dev-tensor-derived-coordinate-cache-v1",
            "derived_coordinate_cache_key",
            "milestone_constant_drift_count",
            "missing-from-milestone-manifest",
            "fallback_used",
        ],
    },
];
