use crate::dev_tensor_drift::DevTensorDriftCheckSpec;

pub(crate) const DEV_TENSOR_RUNTIME_BOOTSTRAP_DRIFT_CHECKS: &[DevTensorDriftCheckSpec] = &[
    DevTensorDriftCheckSpec {
        id: "runtime-lifecycle-bootstrap-plan",
        path: "crates/nuis-runtime/src/lifecycle_bootstrap.rs",
        required_patterns: &[
            "nuis-runtime-lifecycle-bootstrap-plan-v1",
            "nuis-runtime-lifecycle-bootstrap-plan-identity-v1",
            "loader_entry_machine_arch",
            "plan_lifecycle_bootstrap",
            "map-section",
            "apply-relocation",
            "bind-loader-entry",
            "bind-runtime-service",
            "runtime.clock-root",
            "runtime.glm-root",
            "enter-nuis-bootstrap",
            "bind-provider-dispatch",
            "activate-scheduler",
            "runtime-bootstrap:entry-relocation-target-mismatch",
            "runtime-bootstrap:mapped-section-count-mismatch",
            "runtime-bootstrap:applied-relocation-count-mismatch",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "runtime-lifecycle-bootstrap-execution",
        path: "crates/nuis-runtime/src/lifecycle_execution.rs",
        required_patterns: &[
            "nuis-runtime-lifecycle-bootstrap-execution-v1",
            "nuis-runtime-lifecycle-bootstrap-execution-identity-v1",
            "nuis-runtime-compiled-entry-transfer-v1",
            "entry_machine_arch",
            "OwnedImageMapping",
            "OwnedMappedSectionHandle",
            "OwnedAppliedRelocationHandle",
            "OwnedRuntimeServiceHandle",
            "prepare_lifecycle_bootstrap_execution",
            "prepare_lifecycle_bootstrap_execution_with_dispatch",
            "LIFECYCLE_BOOTSTRAP_DISPATCH_EXECUTION_IDENTITY_CONTRACT",
            "consume-mapped-section",
            "consume-applied-relocation",
            "activate-runtime-service",
            "transfer-compiled-entry",
            "bind-runtime-dispatch-import",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "runtime-dispatch-import-binding-contract",
        path: "crates/nuis-runtime/src/runtime_dispatch_binding.rs",
        required_patterns: &[
            "nuis-runtime-dispatch-import-resolution-v1",
            "nuis-runtime-dispatch-import-binding-v1",
            "nuis-runtime-dispatch-import-identity-v1",
            "ResolvedRuntimeDispatchImport",
            "runtime-dispatch-import:declaration-count-invalid",
            "runtime-dispatch-import:provider-unsupported",
            "runtime-dispatch-binding:identity-mismatch",
            "runtime-dispatch-binding:table-identity-mismatch",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "runtime-native-lifecycle-entry-context",
        path: "crates/nuis-runtime/src/native_entry_context.rs",
        required_patterns: &[
            "nuis-runtime-lifecycle-entry-context-i64-v1",
            "nuis-runtime-lifecycle-entry-dispatch-i64-v2",
            "nuis-runtime-lifecycle-entry-context-v1",
            "NativeLifecycleEntryContextV1",
            "#[repr(C)]",
            "struct_size_bytes",
            "runtime.clock-root",
            "runtime.glm-root",
            "bind_transfer_context",
            "validate_transfer_runtime_dispatch",
            "native-entry-context:identity-mismatch",
            "native-entry-context:service-binding-invalid",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "runtime-native-executable-memory-adapter",
        path: "crates/nuis-runtime/src/executable_memory.rs",
        required_patterns: &[
            "nuis-executable-memory-adapter-v1",
            "nuis-native-entry-invocation-v1",
            "nuis-native-entry-invocation-permit-v1",
            "NUIS_LIFECYCLE_ENTRY_CONTEXT_ABI_V1",
            "NUIS_LIFECYCLE_ENTRY_DISPATCH_ABI_V2",
            "nuis-native-entry-code",
            "ExecutableMemoryAdapter",
            "NativeHostExecutableMemoryAdapter",
            "NativeEntryInvocationPermit",
            "AuthorizedNativeEntry",
            "canonical_machine_arch",
            "native_host_machine_arch",
            "PROT_READ | libc::PROT_WRITE",
            "PROT_READ | libc::PROT_EXEC",
            "sys_icache_invalidate",
            "section-kind-unsupported",
            "section-bytes-unverified",
            "entry-range-invalid",
            "host-machine-arch-mismatch",
            "permit-identity-mismatch",
            "runtime_dispatch_import_identity_hash",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-native-lifecycle-entry-section",
        path: "tools/nsld/src/native_entry.rs",
        required_patterns: &[
            "nuis.nsld.native-entry.bin",
            "NATIVE_ENTRY_RELOCATION_SLOT_BYTES",
            "emit_native_entry_asset",
            "native_entry_code_range",
            "NUIS_LIFECYCLE_ENTRY_DISPATCH_ABI_V2",
            "NUIS_NATIVE_ENTRY_SECTION_KIND",
            "native_entry_machine_arch",
            "native_entry_machine_arch(\"arm64\")",
            "native_entry_machine_arch(\"amd64\")",
            "unsupported Nsld native lifecycle-entry architecture",
            "unsupported Nsld native lifecycle-entry calling ABI",
            "call table.handler(context, table, request, response)",
            "SysV: rdi=context, rsi=table, rdx=request, rcx=response",
            "Win64: rcx=context, rdx=table, r8=request, r9=response",
            "emits_deterministic_aarch64_entry_after_relocation_slot",
            "emits_x86_64_entry_without_host_architecture_coupling",
            "emits_x86_64_win64_context_probe",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "host-runner-native-entry-metadata-gate",
        path: "tools/nuis-host-runner/src/container.rs",
        required_patterns: &[
            "loader_entry_abi_contract",
            "loader_entry_machine_arch",
            "is_supported_lifecycle_entry_abi",
            "container-loader:entry-abi-unsupported",
            "container-loader:entry-machine-arch-unsupported",
            "container-loader:symbol-range-invalid",
            "container-loader:symbol-hash-invalid",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "host-runner-native-entry-byte-handoff",
        path: "tools/nuis-host-runner/src/native_entry.rs",
        required_patterns: &[
            "nuis-host-native-entry-handoff-v1",
            "nuis-nsld-container-end-v1",
            "container-payload-padding-invalid",
            "verified-after-relocation-normalization",
            "native-entry:section-hash-mismatch",
            "native-entry:code-hash-mismatch",
            "ExecutableEntryRequest::from_transfer",
            "NativeHostExecutableMemoryAdapter.prepare",
            "NativeEntryInvocationPermit::from_transfer",
            "preparation.authorize(permit, context)",
            "NativeLifecycleEntryContextV1::from_transfer",
            "context_identity_hash",
            "RuntimeDispatchImportResolution",
            "dispatch_import_identity_hash",
            "runtime-dispatch-not-acknowledged",
            "native-entry:bootstrap-return-mismatch",
            "invocation_requested",
            "machine_arch_status",
            "drop(preparation)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "host-runner-native-entry-probe-flag",
        path: "tools/nuis-host-runner/src/args.rs",
        required_patterns: &[
            "--invoke-native-entry",
            "invoke_native_entry",
            "native_entry_invocation_requires_explicit_flag",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-runtime-service-bindings",
        path: "tools/nsld/src/container_metadata_bindings.rs",
        required_patterns: &[
            "runtime.clock-root",
            "runtime.glm-root",
            "clock_protocol_hash",
            "glm_binding_material",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-runtime-only-binding-proof",
        path: "tools/nsdb/src/handoff_binding.rs",
        required_patterns: &[
            "provider_selection_absent",
            "provider_selection_verified",
            "claim_builder_accepts_verified_runtime_only_binding_table",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-runtime-only-binding-proof",
        path: "tools/nuis/src/artifact_nsdb_handoff_binding.rs",
        required_patterns: &[
            "provider_selection_absent",
            "provider_selection_verified",
            "independently_verifies_runtime_only_binding_proof",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "host-runner-runtime-bootstrap-adapter",
        path: "tools/nuis-host-runner/src/runtime_bootstrap.rs",
        required_patterns: &[
            "plan_lifecycle_bootstrap",
            "LifecycleBootstrapFacts",
            "MappedSectionFacts",
            "AppliedRelocationFacts",
            "runtime_service_binding_facts",
            "OwnedImageMapping",
            "prepare_lifecycle_bootstrap_execution_with_dispatch",
            "resolve_runtime_dispatch_import",
            "runtime_dispatch_import_facts",
            "RuntimeBootstrapHandoff",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-final-output-runtime-bootstrap-identity",
        path: "tools/nsld/src/final_executable_bootstrap.rs",
        required_patterns: &[
            "nsld_final_output_bootstrap_plan",
            "actual_relocation_patch_application_status",
            "actual_relocation_patch_byte_audit_status",
            "MappedSectionFacts",
            "AppliedRelocationFacts",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-runtime-bootstrap-replay-identity",
        path: "tools/nsdb/src/lib.rs",
        required_patterns: &[
            "nuis-runtime-lifecycle-bootstrap-plan-identity-v1",
            "runtime_bootstrap_identity_status",
            "runtime-bootstrap-identity:invalid",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-self-hosting-readiness-manifest",
        path: "docs/reference/nuis-self-hosting-readiness.toml",
        required_patterns: &[
            "nuis-self-hosting-readiness-v1",
            "completion_window_start",
            "completion_window_end",
            "language-core/nuisc/bootstrap-language-subset",
            "standard-library/std/compiler-data-model",
            "language-core/nuisc/stage-neutral-ir-boundary",
            "compiler-toolchain/bootstrap/stage0-stage1-driver",
            "developer-system/bootstrap/differential-reproducibility-gate",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-self-hosting-readiness-frontdoor",
        path: "tools/nuis/src/bootstrap_status.rs",
        required_patterns: &[
            "nuis-self-hosting-readiness-v1",
            "ready-for-stage0-stage1-migration",
            "preparing-foundation",
            "stable/100 only for a closed gate",
            "render_bootstrap_readiness_json",
            "render_bootstrap_readiness_text",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-bootstrap-language-subset-contract",
        path: "docs/reference/nuis-bootstrap-language-subset-v1.toml",
        required_patterns: &[
            "nuis-bootstrap-language-subset-v1",
            "nuisc bootstrap-check",
            "NBS001",
            "NBS017",
            "tests/fixtures/bootstrap/accepted/compiler_scanner.ns",
            "tests/fixtures/bootstrap/rejected",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-bootstrap-language-subset-semantics",
        path: "crates/nuis-semantics/src/bootstrap_subset.rs",
        required_patterns: &[
            "BOOTSTRAP_SUBSET_PROTOCOL",
            "BootstrapSubsetContext",
            "validate_bootstrap_subset",
            "CODE_UNSUPPORTED_DOMAIN",
            "CODE_INTRINSIC",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-bootstrap-language-subset-frontdoor",
        path: "tools/nuisc/src/command_bootstrap.rs",
        required_patterns: &[
            "run_bootstrap_check",
            "inspect_bootstrap_modules",
            "semantic_pipeline",
            "resolved.compile()",
            "render_bootstrap_check_json",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-data-model-contract",
        path: "docs/reference/nuis-compiler-data-model-v1.toml",
        required_patterns: &[
            "nuis-compiler-data-model-v1",
            "surface.std.compiler-data-model.v1",
            "fixed-four-slot-proof",
            "canonical-unicode-scalar-encoding",
            "bootstrap_compiler_data_model_demo",
            "expected_native_exit = 43",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-data-model-stdlib",
        path: "stdlib/std/lib/language_core.ns",
        required_patterns: &[
            "pub struct CompilerVector<T>",
            "pub struct CompilerText",
            "pub struct CompilerMap",
            "pub struct CompilerArena",
            "pub struct CompilerDiagnostic",
            "pub fn compiler_text_push_scalar",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-data-model-registration",
        path: "stdlib/std/module.toml",
        required_patterns: &["surface.std.compiler-data-model.v1", "lib/language_core.ns"],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-data-model-component",
        path: "examples/projects/tooling/bootstrap_compiler_data_model_demo/main.ns",
        required_patterns: &[
            "use cpu StdLanguageCore",
            "fn compile_component() -> Result<i64, i64>",
            "fn boundaries_fail_closed",
            "compiler_diagnostic_score",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-data-model-native-regression",
        path: "tools/nuis/tests/compiler_data_model_bootstrap.rs",
        required_patterns: &[
            "compiler_data_model_bootstrap_builds_and_runs_as_pure_nuis",
            "deferred lowering",
            "Some(43)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-image-cache-identity",
        path: "tools/nuisc/src/cache_key.rs",
        required_patterns: &[
            "toolchain.compiler.image",
            "std::env::current_exe()",
            "toolchain.nuisc.cache_epoch",
            "compile.cache.identity",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-image-cache-regression",
        path: "tools/nuisc/src/cache_tests.rs",
        required_patterns: &[
            "default_cache_key_tracks_the_running_compiler_image",
            "explicit_compile_identity_participates_in_cache_key",
            "toolchain.compiler.image",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-stage-handoff-contract",
        path: "docs/reference/nuis-compiler-stage-handoff-v1.toml",
        required_patterns: &[
            "nuis-compiler-stage-handoff-v1",
            "nuis-compiler-stage-producer-v1",
            "source",
            "tokens",
            "ast",
            "nir",
            "yir",
            "producer_identity_in_semantic_hash = false",
            "nuis-compiler-structural-projection-v1",
            "standalone_structural_ast_decoder = true",
            "standalone_structural_nir_decoder = true",
            "nuis_typed_structural_consumer = true",
            "serialized_five_stage_input_consumption_by_nuis = true",
            "nuis-compiler-candidate-production-v1",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-structural-projection-codec",
        path: "crates/nuis-artifact/src/compiler_structural_projection.rs",
        required_patterns: &[
            "COMPILER_STRUCTURAL_PROJECTION_CONTRACT",
            "CompilerStructuralProjection",
            "parse_compiler_structural_projection",
            "render_compiler_structural_projection",
            "verify_compiler_projection_identity",
            "record depth may increase by at most one level",
            "OpaqueBody",
            "unterminated opaque WGSL leaf",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-structural-projection-nuis-consumer",
        path: "stdlib/std/lib/compiler_projection.ns",
        required_patterns: &[
            "mod cpu StdCompilerProjection",
            "CompilerProjectionState",
            "compiler_projection_start",
            "compiler_projection_accept",
            "compiler_projection_finish",
            "compiler_projection_opaque_body_record",
            "compiler_projection_opaque_terminator_record",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-structural-projection-tamper-regression",
        path: "crates/nuis-artifact/src/compiler_stage_handoff_tests.rs",
        required_patterns: &[
            "structurally_invalid_ast_fails_even_with_recomputed_hash_chain",
            "projection_identity_must_match_handoff_during_build",
            "structural tampering must fail after hash verification",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-structural-projection-wgsl-regression",
        path: "tools/nuisc/src/render/tests.rs",
        required_patterns: &[
            "renders_multiline_shader_inline_wgsl_as_wgsl_block",
            "parse_compiler_structural_projection",
            "rendered multiline WGSL should cross the shared structural codec",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-stage-handoff-artifact",
        path: "crates/nuis-artifact/src/compiler_stage_handoff.rs",
        required_patterns: &[
            "COMPILER_STAGE_HANDOFF_PROTOCOL",
            "COMPILER_STAGE_PRODUCER_CONTRACT",
            "ORDERED_STAGES",
            "semantic_root_identity",
            "record_identity",
            "read_compiler_stage_handoff",
            "escapes its handoff root",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-stage-token-stream",
        path: "tools/nuisc/src/frontend/lexer.rs",
        required_patterns: &[
            "nuis-token-stream-v1",
            "render_stage_neutral_token_stream",
            "parse_stage_neutral_token_stream",
            "verify_stage_neutral_token_stream",
            "round_trips_without_rust_layout_identity",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-stage-handoff-writer",
        path: "tools/nuisc/src/stage_handoff.rs",
        required_patterns: &[
            "write_and_verify_compiler_stage_handoff",
            "build_compiler_stage_handoff",
            "verify_stage_neutral_token_stream",
            "parse_compiler_structural_projection",
            "verify_compiler_projection_identity",
            "parse_explicit_module",
            "verify_module",
            "portable boundary",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-stage-yir-text-roundtrip",
        path: "tools/nuisc/src/render/tests.rs",
        required_patterns: &[
            "yir_text_projection_round_trips_escaped_arguments",
            "yir_text_projection_round_trips_empty_and_embedded_quote_arguments",
            "cpu.text empty cpu0",
            "left\\\"right",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-stage-handoff-native-regression",
        path: "tools/nuis/tests/compiler_data_model_bootstrap.rs",
        required_patterns: &[
            "read_compiler_stage_handoff",
            "read_compiler_component_build",
            "read_compiler_diagnostic_report",
            "COMPILER_STAGE_HANDOFF_PROTOCOL",
            "COMPILER_COMPONENT_BUILD_PROTOCOL",
            "CompilerStageKind::Source",
            "CompilerStageKind::Yir",
            "reproducible_build_sha256",
            "bootstrap-diff",
            "tampered native binary must invalidate component build",
            "Some(43)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-candidate-execution-contract",
        path: "docs/reference/nuis-compiler-candidate-execution-v1.toml",
        required_patterns: &[
            "nuis-compiler-candidate-execution-v1",
            "nuis-bootstrap-candidate-runner-v1",
            "stage1-candidate-probe",
            "execution-only-no-component-production",
            "nuis bootstrap-candidate-probe",
            "nuis-compiler-candidate-production-v1",
            "nuis bootstrap-candidate-build",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-candidate-execution-artifact",
        path: "crates/nuis-artifact/src/compiler_candidate_execution.rs",
        required_patterns: &[
            "COMPILER_CANDIDATE_EXECUTION_PROTOCOL",
            "COMPILER_CANDIDATE_EXECUTION_AUTHORITY",
            "build_compiler_candidate_execution",
            "read_compiler_candidate_execution",
            "execution_identity",
            "requires an output-free successful process",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-candidate-execution-frontdoor",
        path: "tools/nuis/src/bootstrap_candidate_probe.rs",
        required_patterns: &[
            "handle_bootstrap_candidate_probe",
            "BootstrapBuild",
            "Stdio::null",
            "COMPILER_CANDIDATE_EXECUTION_FILE",
            "read_compiler_candidate_execution",
            "bootstrap candidate probe: verified",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-candidate-execution-native-regression",
        path: "tools/nuis/tests/compiler_structural_projection_candidate.rs",
        required_patterns: &[
            "bootstrap-candidate-probe",
            "read_compiler_candidate_execution",
            "COMPILER_CANDIDATE_EXECUTION_AUTHORITY",
            "Some(0)",
            "tampered candidate binary must invalidate its execution proof",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-bootstrap-candidate-scalar-export-policy",
        path: "crates/nuis-semantics/src/bootstrap_subset.rs",
        required_patterns: &[
            "BOOTSTRAP_SCALAR_EXPORTS",
            "nuis_bootstrap_candidate_stage_seed_v1",
            "nuis_bootstrap_candidate_stage_fold_v1",
            "nuis_bootstrap_candidate_bundle_seed_v1",
            "nuis_bootstrap_candidate_bundle_fold_v1",
            "is_approved_scalar_export",
            "CODE_ATTRIBUTE",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-bootstrap-candidate-scalar-export-source",
        path: "examples/projects/tooling/bootstrap_structural_projection_candidate/main.ns",
        required_patterns: &[
            "@export(name = \"nuis_bootstrap_candidate_stage_seed_v1\")",
            "@export(name = \"nuis_bootstrap_candidate_stage_fold_v1\")",
            "@export(name = \"nuis_bootstrap_candidate_bundle_seed_v1\")",
            "@export(name = \"nuis_bootstrap_candidate_bundle_fold_v1\")",
            "2147483629",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-candidate-production-contract",
        path: "docs/reference/nuis-compiler-candidate-production-v1.toml",
        required_patterns: &[
            "nuis-compiler-candidate-production-v1",
            "nuis-stage1-scalar-byte-producer-v1",
            "stage1-candidate-component-production-no-replacement",
            "nuis bootstrap-candidate-build",
            "host-byte-transport-without-compiler-semantics",
            "replacement_authorized = false",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-development-tensor-candidate-production-baseline",
        path: "docs/reference/nuis-development-tensor.md",
        required_patterns: &[
            "stage-neutral boundary to `usable/78`",
            "driver to `usable/80`",
            "reaches `13/13` equivalence",
            "differential gate, now\n`usable/78`",
            "`standard-library/std/compiler-data-model` at `usable/75`",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-candidate-production-artifact",
        path: "crates/nuis-artifact/src/compiler_candidate_production.rs",
        required_patterns: &[
            "COMPILER_CANDIDATE_PRODUCTION_PROTOCOL",
            "COMPILER_CANDIDATE_PRODUCTION_AUTHORITY",
            "build_compiler_candidate_production",
            "read_compiler_candidate_production",
            "compiler_candidate_stage_fold",
            "compiler_candidate_bundle_fold",
            "replacement_authorized: false",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-candidate-production-frontdoor",
        path: "tools/nuis/src/bootstrap_candidate_build.rs",
        required_patterns: &[
            "handle_bootstrap_candidate_build",
            "run_candidate_adapter",
            "promote_compiler_component_candidate",
            "build_compiler_candidate_production",
            "BootstrapDiff",
            "equivalent-awaiting-authorization",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-candidate-production-native-regression",
        path: "tools/nuis/tests/compiler_structural_projection_candidate.rs",
        required_patterns: &[
            "bootstrap-candidate-build",
            "read_compiler_candidate_production",
            "COMPILER_COMPONENT_STAGE1_CANDIDATE_ROLE",
            "nuis-stage1-projection-relay-v1",
            "equivalent_count, 13",
            "adapter tampering must invalidate production proof",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-component-build-contract",
        path: "docs/reference/nuis-compiler-component-build-v1.toml",
        required_patterns: &[
            "nuis-compiler-component-build-v1",
            "nuis-stage0-stage1-driver-v1",
            "nuis-compiler-dependency-closure-v1",
            "nuis-compiler-component-reproducible-build-v1",
            "exact-audit-record",
            "cache-stable-reproducible-record",
            "nuis bootstrap-build",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-component-build-artifact",
        path: "crates/nuis-artifact/src/compiler_component_build.rs",
        required_patterns: &[
            "COMPILER_COMPONENT_BUILD_PROTOCOL",
            "COMPILER_COMPONENT_DRIVER_CONTRACT",
            "COMPILER_COMPONENT_REPRODUCIBLE_IDENTITY_CONTRACT",
            "COMPILER_COMPONENT_STAGE1_CANDIDATE_ROLE",
            "read_compiler_component_build",
            "verify_compiler_component_build_image",
            "promote_compiler_component_candidate",
            "dependency closure identity mismatch",
            "reproducible build identity mismatch",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-component-build-identity",
        path: "crates/nuis-artifact/src/compiler_component_build_identity.rs",
        required_patterns: &[
            "dependency_closure_identity",
            "reproducible_build_identity",
            "component_build_identity",
            "compiler_image_sha256",
            "stage_handoff_bundle_sha256",
            "native_binary_sha256",
            "dependency_closure_sha256",
            "build_manifest_sha256",
            "compiled_artifact_sha256",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-stage0-compiler-component-driver",
        path: "tools/nuisc/src/bootstrap_stage_driver.rs",
        required_patterns: &[
            "run_bootstrap_build",
            "ensure_bootstrap_resolved",
            "run_compile_resolved",
            "nuisc-stage0-reference",
            "collect_dependencies",
            "COMPILER_COMPONENT_BUILD_FILE",
            "verify_compiler_component_build_image",
            "reproducible_build_sha256",
            "COMPILER_DIAGNOSTIC_REPORT_FILE",
            "build_compiler_diagnostic_report",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-diagnostic-report-contract",
        path: "docs/reference/nuis-compiler-diagnostic-report-v1.toml",
        required_patterns: &[
            "nuis-compiler-diagnostic-report-v1",
            "nuis-compiler-diagnostic-normalization-v1",
            "exact-component-record-sha256",
            "portable-logical-path-without-absolute-or-parent-traversal",
            "component-record-and-producer-cross-binding",
            "nuis bootstrap-build",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-diagnostic-report-artifact",
        path: "crates/nuis-artifact/src/compiler_diagnostic_report.rs",
        required_patterns: &[
            "COMPILER_DIAGNOSTIC_REPORT_PROTOCOL",
            "COMPILER_DIAGNOSTIC_NORMALIZATION_CONTRACT",
            "build_compiler_diagnostic_report",
            "read_compiler_diagnostic_report",
            "diagnostics_identity",
            "report_identity",
            "accepted compiler diagnostic reports must be checked and diagnostic-free",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-component-differential-contract",
        path: "docs/reference/nuis-compiler-component-differential-v1.toml",
        required_patterns: &[
            "nuis-compiler-component-differential-v1",
            "nuis-compiler-component-differential-gate-v1",
            "nuis-compiler-replacement-authorization-separate-v1",
            "nuis bootstrap-diff",
            "blocked-drift",
            "equivalent-awaiting-authorization",
            "replacement_authorized = false",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-component-differential-artifact",
        path: "crates/nuis-artifact/src/compiler_component_diff.rs",
        required_patterns: &[
            "COMPILER_COMPONENT_DIFFERENTIAL_PROTOCOL",
            "COMPILER_COMPONENT_DIFFERENTIAL_GATE_CONTRACT",
            "COMPILER_COMPONENT_REPLACEMENT_AUTHORITY_CONTRACT",
            "build_compiler_component_differential",
            "compare_compiler_component_paths",
            "read_compiler_candidate_production",
            "replacement_authorized: false",
            "blocked-drift",
            "equivalent-awaiting-authorization",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-component-differential-frontdoor",
        path: "tools/nuisc/src/bootstrap_differential.rs",
        required_patterns: &[
            "run_bootstrap_diff",
            "compare_compiler_component_paths",
            "render_compiler_component_differential",
            "replacement_authorized",
            "report must not overwrite an input component record",
            "compiler component drift blocked replacement",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-self-hosting-readiness-reference",
        path: "docs/reference/nuis-self-hosting-readiness.md",
        required_patterns: &[
            "Roadmap Is Not Readiness",
            "bootstrap-language-subset",
            "stage0-stage1-driver",
            "differential-reproducibility-gate",
            "nuis bootstrap-status --json",
        ],
    },
];
