use crate::{
    dev_tensor::{DevTensorCell, DevTensorExpectedCoordinate},
    dev_tensor_drift::DevTensorDriftCheckSpec,
};

pub(crate) const DEV_TENSOR_CELLS: &[DevTensorCell] = &[
    DevTensorCell {
        architecture: "compiler-frontdoor",
        module: "nuis-cli",
        function: "workflow-and-project-orientation",
        status: "stable",
        progress: 86,
        bootstrap_critical: true,
        closure_role: "developer-frontdoor",
        evidence: "workflow/project-status/project-doctor JSON and text frontdoors are regression-backed",
        next_step: "compress repeated status fields into a higher-level closure summary",
    },
    DevTensorCell {
        architecture: "compiler-frontdoor",
        module: "nuis-cli",
        function: "artifact-runtime-closure",
        status: "active",
        progress: 77,
        bootstrap_critical: true,
        closure_role: "artifact-execution-frontdoor",
        evidence: "run-artifact, artifact-doctor, release-check, nsld handoff, self-contained host-runner probe fields, and final-output boundary reports share closure evidence",
        next_step: "promote host-runner probe summaries into a stable nsdb/debugger-friendly launch evidence contract",
    },
    DevTensorCell {
        architecture: "linker-toolchain",
        module: "nsld",
        function: "artifact-chain-drive",
        status: "stable",
        progress: 82,
        bootstrap_critical: true,
        closure_role: "linker-artifact-chain",
        evidence: "nsld drive can apply whitelisted artifact-chain steps and stop cleanly on host-assisted final output boundaries",
        next_step: "keep drive mutating actions separate from read-only final-output inspection",
    },
    DevTensorCell {
        architecture: "linker-toolchain",
        module: "nsld",
        function: "final-output-boundary",
        status: "active",
        progress: 72,
        bootstrap_critical: true,
        closure_role: "executable-output-boundary",
        evidence: "final-executable-output reports normalized boundary status, materialization status, recommended next action, path presence, ownership, runnable candidate, blockers, Nuis/Nsld mirrors, and a self-contained image whose relocation patches no longer corrupt container metadata",
        next_step: "surface container-loader execution evidence from the final-output boundary instead of only from the host-runner probe",
    },
    DevTensorCell {
        architecture: "heterogeneous-runtime",
        module: "nustar",
        function: "registered-domain-contracts",
        status: "active",
        progress: 71,
        bootstrap_critical: true,
        closure_role: "heterogeneous-domain-registration",
        evidence: "domain units, lowering targets, backend families, contract completeness status, contract drift checks, and heterogeneous domain readiness are visible in build/link reports",
        next_step: "connect shader/kernel/network execution-specific readiness and dispatch bridge materialization to registered Nustar domain contracts without hardcoding nsld domain logic",
    },
    DevTensorCell {
        architecture: "standard-library",
        module: "std",
        function: "host-io-filesystem-text",
        status: "usable",
        progress: 70,
        bootstrap_critical: true,
        closure_role: "bootstrap-std-foundation",
        evidence: "std IO/filesystem/text examples, std_filesystem_smoke, tooling docs, and std lane docs anchor the current host-backed CLI foundation",
        next_step: "promote the light std smoke chain into milestone-owned CLI closure evidence",
    },
    DevTensorCell {
        architecture: "standard-library",
        module: "pixelmagic",
        function: "image-processing-lane",
        status: "early",
        progress: 34,
        bootstrap_critical: false,
        closure_role: "official-compute-package",
        evidence: "PixelMagic exists as an official package lane but still depends on stronger shader/kernel lowering",
        next_step: "add shader-backed image kernels once heterogeneous final-output closure is clearer",
    },
    DevTensorCell {
        architecture: "standard-library",
        module: "witsage",
        function: "classical-ml-lane",
        status: "early",
        progress: 28,
        bootstrap_critical: false,
        closure_role: "official-compute-package",
        evidence: "WitSage is named and staged as an official package lane but not yet a mature compute workload",
        next_step: "anchor first matrix/vector workloads to kernel/shader domain tests",
    },
    DevTensorCell {
        architecture: "language-core",
        module: "nuisc",
        function: "type-control-flow-generics",
        status: "active",
        progress: 72,
        bootstrap_critical: true,
        closure_role: "language-self-hosting-foundation",
        evidence: "control flow, generics, traits, pointers, floats, enums, error handling, and inference have staged coverage",
        next_step: "bind language feature maturity to bootstrap-critical examples rather than isolated syntax tests",
    },
    DevTensorCell {
        architecture: "native-binary-system",
        module: "nsb-nsld",
        function: "self-owned-binary-assembly",
        status: "active",
        progress: 78,
        bootstrap_critical: true,
        closure_role: "self-owned-native-binary",
        evidence: "Nsld container, object/image dry-runs, final executable pipeline, self-contained NSB image emission, container-metadata-first image payload layout, container-payload relocation patching, launcher dry-run checks, host entrypoint handoff stub emission, host-runner image/container probe, Nsld pipeline self-owned image status, entrypoint materialization status, and Nuis frontdoor consumption are visible",
        next_step: "turn host-runner container-loader readiness into first payload execution evidence instead of only a lifecycle handoff proof",
    },
    DevTensorCell {
        architecture: "developer-system",
        module: "dev-tensor",
        function: "architecture-module-function-progress-model",
        status: "active",
        progress: 70,
        bootstrap_critical: true,
        closure_role: "bootstrap-progress-model",
        evidence: "tensor frontdoor maps progress by architecture, module, and function, summarizes through nuis status, and runs drift checks over key docs/tests/frontdoor fields",
        next_step: "expand drift checks from field anchors to milestone-owned test and example evidence",
    },
];

pub(crate) const DEV_TENSOR_EXPECTED_COORDINATES: &[DevTensorExpectedCoordinate] = &[
    DevTensorExpectedCoordinate {
        architecture: "compiler-frontdoor",
        module: "nuis-cli",
        function: "workflow-and-project-orientation",
        milestone: "alpha-frontdoor",
        required: true,
    },
    DevTensorExpectedCoordinate {
        architecture: "compiler-frontdoor",
        module: "nuis-cli",
        function: "artifact-runtime-closure",
        milestone: "alpha-frontdoor",
        required: true,
    },
    DevTensorExpectedCoordinate {
        architecture: "linker-toolchain",
        module: "nsld",
        function: "artifact-chain-drive",
        milestone: "alpha-linker",
        required: true,
    },
    DevTensorExpectedCoordinate {
        architecture: "linker-toolchain",
        module: "nsld",
        function: "final-output-boundary",
        milestone: "alpha-linker",
        required: true,
    },
    DevTensorExpectedCoordinate {
        architecture: "heterogeneous-runtime",
        module: "nustar",
        function: "registered-domain-contracts",
        milestone: "alpha-heterogeneous",
        required: true,
    },
    DevTensorExpectedCoordinate {
        architecture: "standard-library",
        module: "std",
        function: "host-io-filesystem-text",
        milestone: "alpha-stdlib",
        required: true,
    },
    DevTensorExpectedCoordinate {
        architecture: "standard-library",
        module: "pixelmagic",
        function: "image-processing-lane",
        milestone: "alpha-official-galaxy",
        required: false,
    },
    DevTensorExpectedCoordinate {
        architecture: "standard-library",
        module: "witsage",
        function: "classical-ml-lane",
        milestone: "alpha-official-galaxy",
        required: false,
    },
    DevTensorExpectedCoordinate {
        architecture: "language-core",
        module: "nuisc",
        function: "type-control-flow-generics",
        milestone: "alpha-language-core",
        required: true,
    },
    DevTensorExpectedCoordinate {
        architecture: "native-binary-system",
        module: "nsb-nsld",
        function: "self-owned-binary-assembly",
        milestone: "alpha-native-binary",
        required: true,
    },
    DevTensorExpectedCoordinate {
        architecture: "developer-system",
        module: "dev-tensor",
        function: "architecture-module-function-progress-model",
        milestone: "alpha-governance",
        required: true,
    },
];

pub(crate) const DEV_TENSOR_DRIFT_CHECKS: &[DevTensorDriftCheckSpec] = &[
    DevTensorDriftCheckSpec {
        id: "frontdoor-final-output-boundary-status",
        path: "tools/nuis/src/surface_render/link_plan.rs",
        required_patterns: &[
            "nsld_final_executable_output_boundary_status",
            "nsld_final_executable_output_materialization_status",
            "nsld_final_executable_output_execution_handoff_contract",
            "nsld_final_executable_output_execution_handoff_ready",
            "nsld_final_executable_output_execution_handoff_status",
            "nsld_final_executable_output_execution_handoff_target",
            "nsld_final_executable_output_execution_handoff_evidence_status",
            "nsld_final_executable_output_execution_handoff_first_blocker",
            "nsld_final_executable_output_execution_handoff_decision_code",
            "nsld_final_executable_output_recommended_next_action",
            "nsld_final_executable_output_ready",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-final-output-materialization-status",
        path: "tools/nsld/src/final_executable_output.rs",
        required_patterns: &[
            "final_executable_output_materialization_status",
            "final_executable_output_execution_handoff_contract",
            "final_executable_output_execution_handoff_ready",
            "final_executable_output_execution_handoff_status",
            "final_executable_output_execution_handoff_target",
            "final_executable_output_execution_handoff_evidence_status",
            "final_executable_output_execution_handoff_first_blocker",
            "final_executable_output_execution_handoff_decision_code",
            "final_executable_output_recommended_next_action",
            "self-contained-image-ready",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-final-output-materialization-regression",
        path: "tools/nsld/src/main_final_executable_output_tests.rs",
        required_patterns: &[
            "materialization_status",
            "execution_handoff_contract",
            "execution_handoff_ready",
            "execution_handoff_status",
            "execution_handoff_target",
            "execution_handoff_evidence_status",
            "execution_handoff_first_blocker",
            "execution_handoff_decision_code",
            "recommended_next_action",
            "self-contained-image-ready",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-host-finalizer-gate-surface",
        path: "tools/nsld/src/json_final_executable.rs",
        required_patterns: &[
            "host_finalizer_gate_status",
            "host_finalizer_gate_action",
            "policy-blocked",
            "explicit-allow-missing",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-host-finalizer-gate-artifact",
        path: "tools/nsld/src/final_executable_render.rs",
        required_patterns: &[
            "host_finalizer_gate_status",
            "host_finalizer_gate_action",
            "set-env:NUIS_NSLD_HOST_FINALIZER_POLICY=allow-host-invoke",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-host-finalizer-gate-regression",
        path: "tools/nsld/src/main_final_executable_emit_tests.rs",
        required_patterns: &[
            "host_finalizer_gate_status",
            "policy-blocked",
            "set-env:NUIS_NSLD_HOST_FINALIZER_POLICY=allow-host-invoke",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-check-host-finalizer-gate-surface",
        path: "tools/nsld/src/json_check_final.rs",
        required_patterns: &[
            "final_executable_host_finalizer_gate_status",
            "final_executable_host_finalizer_gate_action",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-nsb-relocation-application-layout",
        path: "tools/nsld/src/final_executable_layout_stage.rs",
        required_patterns: &[
            "relocation_application_strategy",
            "nsb-loader-relocation-table",
            "relocation_application_table_hash",
            "relocation_applications",
            "payload0001.container-payload",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-nsb-relocation-application-image-report",
        path: "tools/nsld/src/final_executable_image_stage.rs",
        required_patterns: &[
            "relocation_application_strategy",
            "relocation_application_count",
            "relocation_application_table_hash",
            "relocation_application_audit_status",
            "relocation_application_audit_blockers",
            "relocation_patch_preview_status",
            "relocation_patch_preview_table_hash",
            "relocation_patch_application_status",
            "relocation_patch_application_table_hash",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-nsb-relocation-application-image-verify",
        path: "tools/nsld/src/final_executable_image_verify.rs",
        required_patterns: &[
            "relocation_patch_preview_record_table_hash",
            "relocation_patch_byte_audit_status",
            "relocation_patch_byte_audit_hash",
            "parse_final_executable_image_header",
            "verify_final_executable_image_payload_region",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-nsb-relocation-application-image-resolver",
        path: "tools/nsld/src/final_executable_image_relocation.rs",
        required_patterns: &[
            "resolved_patch_value",
            "target_symbol_image_offset",
            "resolver_status",
            "u64-le-resolved-image-offset",
            "apply_relocation_patches",
            "relocation_patch_byte_audit",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-nsb-relocation-application-image-actual",
        path: "tools/nsld/src/final_executable_image_actual.rs",
        required_patterns: &[
            "relocation_patch_preview_records_from_source",
            "relocation_patch_preview_record_table_hash",
            "resolved_patch_value",
            "target_symbol_image_offset",
            "resolver_status",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-nsb-relocation-final-emit-surface",
        path: "tools/nsld/src/final_executable_emit_shape.rs",
        required_patterns: &[
            "image_dry_run_resolver_status",
            "image_dry_run_patch_application_status",
            "image_dry_run_patch_byte_audit_status",
            "image_dry_run_patch_byte_audit_hash",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-nsb-relocation-final-output-surface",
        path: "tools/nsld/src/final_executable_output.rs",
        required_patterns: &[
            "expected_image_resolver_status",
            "expected_image_patch_application_status",
            "expected_image_patch_byte_audit_status",
            "matches_verified_patched_image",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-nsb-relocation-final-output-check-surface",
        path: "tools/nsld/src/check_final.rs",
        required_patterns: &[
            "final_executable_output_expected_image_resolver_status",
            "final_executable_output_expected_image_patch_application_status",
            "final_executable_output_expected_image_patch_byte_audit_status",
            "final_executable_output_matches_verified_patched_image",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-nsb-relocation-final-output-check-json",
        path: "tools/nsld/src/json_check_final.rs",
        required_patterns: &[
            "final_executable_output_expected_image_resolver_status",
            "final_executable_output_expected_image_patch_application_status",
            "final_executable_output_expected_image_patch_byte_audit_status",
            "final_executable_output_matches_verified_patched_image",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-nsb-relocation-application-regression",
        path: "tools/nsld/src/main_final_executable_layout_tests.rs",
        required_patterns: &[
            "relocation_application_strategy",
            "relocation_application_count",
            "relocation_application_table_hash",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-check-next-action-final-output-boundary",
        path: "tools/nsld/src/check.rs",
        required_patterns: &[
            "artifact_chain_final_output_boundary_ready",
            "final-output-boundary",
            "artifact_chain_final_output_boundary_command_resolved",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-check-next-action-final-output-boundary-regression",
        path: "tools/nsld/src/drive_tests.rs",
        required_patterns: &[
            "drive_until_clean_command_reaches_host_assisted_pipeline_block",
            "final-output-boundary",
            "final-executable-output",
            "blocked-boundary",
            "read-only-boundary:final-executable-output",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-driver-final-output-boundary-doc",
        path: "docs/reference/nsld-driver-frontdoor.md",
        required_patterns: &[
            "final-output-boundary",
            "blocked-boundary",
            "nsld final-executable-output <input>",
            "Host-assisted final executable emission",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "frontdoor-self-owned-image-status",
        path: "tools/nuis/src/surface_render/link_plan.rs",
        required_patterns: &[
            "nsld_self_owned_image_status",
            "nsld_entrypoint_materialization_status",
            "nsld_self_owned_image_header_valid",
            "nsld_final_executable_pipeline_execution_handoff_contract",
            "nsld_final_executable_pipeline_execution_handoff_ready",
            "nsld_final_executable_pipeline_execution_handoff_status",
            "nsld_final_executable_pipeline_execution_handoff_target",
            "nsld_final_executable_pipeline_execution_handoff_evidence_status",
            "nsld_final_executable_pipeline_execution_handoff_first_blocker",
            "nsld_final_executable_pipeline_execution_handoff_decision_code",
            "nsld_final_executable_pipeline_entrypoint_materialization_kind",
            "nsld_final_executable_pipeline_entrypoint_materialization_path",
            "nsld_final_executable_pipeline_entrypoint_materialization_ready",
            "nsld_final_executable_pipeline_entrypoint_materialization_first_blocker",
            "nsld_final_executable_pipeline_entrypoint_materialization_present",
            "nsld_final_executable_pipeline_entrypoint_materialization_hash",
            "nsld_final_executable_pipeline_entrypoint_materialization_runner_command",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-pipeline-orchestrator-split-surface",
        path: "tools/nsld/src/final_executable_pipeline.rs",
        required_patterns: &[
            "nsld_pipeline_self_owned_image_status",
            "nsld_pipeline_entrypoint_materialization_status",
            "final_executable_pipeline_required_stage_paths",
            "render_final_executable_pipeline",
            "push_optional_string_mismatch",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-pipeline-self-owned-image-status",
        path: "tools/nsld/src/final_executable_pipeline_status.rs",
        required_patterns: &[
            "nsld_pipeline_self_owned_image_status",
            "launcher_manifest_ready",
            "image_header_valid",
            "path-missing",
            "header-invalid",
            "hash-missing",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-pipeline-entrypoint-materialization",
        path: "tools/nsld/src/final_executable_pipeline_entrypoint.rs",
        required_patterns: &[
            "nsld_pipeline_entrypoint_materialization_status",
            "nsld_pipeline_entrypoint_materialization_plan",
            "nsld_write_host_entrypoint_script",
            "entrypoint_materialization_evidence",
            "render_host_entrypoint_runner_command",
            "host-launcher-ready",
            "image-ready-entrypoint-pending",
            "entrypoint-materializer",
            "host-shell-entrypoint-plan",
            "nuis-nsld-host-entrypoint-v1",
            "NUIS_HOST_ENTRYPOINT_STUB_PROTOCOL",
            "nuis.host-entrypoint.sh",
            "NUIS_HOST_RUNNER",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-pipeline-render-contract",
        path: "tools/nsld/src/final_executable_pipeline_render.rs",
        required_patterns: &[
            "nuis-nsld-final-executable-pipeline-v1",
            "entrypoint_materialization_status",
            "entrypoint_materialization_runner_command",
            "execution_handoff_contract",
            "execution_handoff_decision_code",
            "scheduler_metadata_payload_id",
            "required_stage_path_count",
            "missing_required_stage_paths",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-pipeline-required-paths",
        path: "tools/nsld/src/final_executable_pipeline_paths.rs",
        required_patterns: &[
            "NsldFinalExecutablePipelineRequiredPaths",
            "final_executable_pipeline_required_stage_paths",
            "entrypoint_materialization_path",
            "final_executable_emitted",
            "missing_paths",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-pipeline-mismatch-helpers",
        path: "tools/nsld/src/final_executable_pipeline_mismatch.rs",
        required_patterns: &[
            "optional_bool_text",
            "push_usize_mismatch",
            "push_bool_mismatch",
            "push_optional_string_mismatch",
            "expected",
            "found",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-check-pipeline-handoff-status",
        path: "tools/nsld/src/reports_check.rs",
        required_patterns: &[
            "final_executable_pipeline_execution_handoff_contract",
            "final_executable_pipeline_execution_handoff_ready",
            "final_executable_pipeline_execution_handoff_status",
            "final_executable_pipeline_execution_handoff_target",
            "final_executable_pipeline_execution_handoff_evidence_status",
            "final_executable_pipeline_execution_handoff_first_blocker",
            "final_executable_pipeline_execution_handoff_decision_code",
            "final_executable_pipeline_entrypoint_materialization_kind",
            "final_executable_pipeline_entrypoint_materialization_path",
            "final_executable_pipeline_entrypoint_materialization_ready",
            "final_executable_pipeline_entrypoint_materialization_first_blocker",
            "final_executable_pipeline_entrypoint_materialization_present",
            "final_executable_pipeline_entrypoint_materialization_hash",
            "final_executable_pipeline_entrypoint_materialization_runner_command",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-pipeline-self-owned-image-regression",
        path: "tools/nsld/src/main_final_executable_pipeline_tests.rs",
        required_patterns: &[
            "actual_self_owned_image_status",
            "actual_entrypoint_materialization_status",
            "actual_entrypoint_materialization_kind",
            "actual_entrypoint_materialization_ready",
            "actual_entrypoint_materialization_first_blocker",
            "actual_entrypoint_materialization_present",
            "actual_entrypoint_materialization_hash",
            "actual_entrypoint_materialization_runner_command",
            "actual_execution_handoff_contract",
            "actual_execution_handoff_ready",
            "actual_execution_handoff_status",
            "actual_execution_handoff_target",
            "actual_execution_handoff_evidence_status",
            "actual_execution_handoff_first_blocker",
            "actual_execution_handoff_decision_code",
            "self_owned_image_status",
            "entrypoint_materialization_status",
            "host-shell-entrypoint-plan",
            "NUIS_HOST_RUNNER",
            "nuis-host-runner --manifest",
            "required_stage_path_count, 10",
            "verify_final_executable_pipeline_reports_missing_entrypoint_materialization",
            "verify_final_executable_pipeline_reports_tampered_entrypoint_materialization",
            "entrypoint_materialization_hash mismatch",
            "nsld-final-output-handoff-v1",
            "handoff-entrypoint-materializer",
            "Some(\"ready\")",
            "Some(\"host-launcher-ready\")",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nustar-domain-contract-completeness-status",
        path: "tools/nuisc/src/registry_contract.rs",
        required_patterns: &[
            "contract_status",
            "required_domain_contract_groups",
            "missing_domain_contract_groups",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nustar-domain-contract-completeness-json",
        path: "tools/nuisc/src/registry_domain_json.rs",
        required_patterns: &[
            "contract_complete",
            "required_contract_groups",
            "missing_contract_groups",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "workflow-surface-json-regression",
        path: "tools/nuis/src/main_tests/workflow_surface.rs",
        required_patterns: &[
            "nsld_final_executable_output_boundary_status",
            "nsld_final_executable_output_materialization_status",
            "nsld_final_executable_output_execution_handoff_contract",
            "nsld_final_executable_output_execution_handoff_ready",
            "nsld_final_executable_output_execution_handoff_status",
            "nsld_final_executable_output_execution_handoff_target",
            "nsld_final_executable_output_execution_handoff_evidence_status",
            "nsld_final_executable_output_execution_handoff_first_blocker",
            "nsld_final_executable_output_execution_handoff_decision_code",
            "nsld_final_executable_pipeline_execution_handoff_contract",
            "nsld_final_executable_pipeline_execution_handoff_ready",
            "nsld_final_executable_pipeline_execution_handoff_status",
            "nsld_final_executable_pipeline_execution_handoff_target",
            "nsld_final_executable_pipeline_execution_handoff_evidence_status",
            "nsld_final_executable_pipeline_execution_handoff_first_blocker",
            "nsld_final_executable_pipeline_execution_handoff_decision_code",
            "workflow_run_artifact_prelaunch_kind",
            "workflow_run_artifact_prelaunch_status",
            "workflow_run_artifact_prelaunch_evidence_status",
            "workflow_run_artifact_prelaunch_command",
            "workflow_run_artifact_prelaunch_reason",
            "nsld_final_executable_output_recommended_next_action",
            "nsld_self_owned_image_status",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "artifact-runtime-json-regression",
        path: "tools/nuis/src/main_tests/artifact_runtime.rs",
        required_patterns: &[
            "nsld_final_executable_output_boundary_status",
            "nsld_final_executable_output_materialization_status",
            "nsld_final_executable_output_execution_handoff_contract",
            "nsld_final_executable_output_execution_handoff_ready",
            "nsld_final_executable_output_execution_handoff_status",
            "nsld_final_executable_output_execution_handoff_target",
            "nsld_final_executable_output_execution_handoff_evidence_status",
            "nsld_final_executable_output_execution_handoff_first_blocker",
            "nsld_final_executable_output_execution_handoff_decision_code",
            "nsld_final_executable_pipeline_execution_handoff_contract",
            "nsld_final_executable_pipeline_execution_handoff_ready",
            "nsld_final_executable_pipeline_execution_handoff_status",
            "nsld_final_executable_pipeline_execution_handoff_target",
            "nsld_final_executable_pipeline_execution_handoff_evidence_status",
            "nsld_final_executable_pipeline_execution_handoff_first_blocker",
            "nsld_final_executable_pipeline_execution_handoff_decision_code",
            "nsld_final_executable_output_recommended_next_action",
            "nsld_self_owned_image_status",
            "run_artifact_prelaunch_kind",
            "run_artifact_prelaunch_status",
            "run_artifact_prelaunch_evidence_status",
            "run_artifact_prelaunch_runner_command_present",
            "run_artifact_prelaunch_entrypoint_present",
            "run_artifact_prelaunch_entrypoint_protocol",
            "run_artifact_prelaunch_entrypoint_protocol_valid",
            "nsld-host-entrypoint",
            "artifact_closure_kind",
            "artifact_closure_status",
            "artifact_closure_evidence_status",
            "artifact_closure_runner_command_present",
            "artifact_closure_entrypoint_present",
            "artifact_closure_entrypoint_protocol",
            "artifact_closure_entrypoint_protocol_valid",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "run-artifact-host-runner-probe-surface",
        path: "tools/nuis/src/artifact_runtime_command.rs",
        required_patterns: &[
            "run_artifact_host_runner_surface",
            "HostRunnerJsonSurface",
            "host_runner_invoked",
            "host_runner_status",
            "host_runner_program",
            "host_runner_ready",
            "host_runner_nsb_readable",
            "host_runner_nsb_hash_matches",
            "host_runner_nsb_payload_region_mapped",
            "host_runner_nsb_payload_scan_kind",
            "host_runner_container_loader_status",
            "host_runner_container_loader_handoff_ready",
            "try_run_nsld_host_runner",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "host-runner-container-loader-handoff-policy",
        path: "tools/nuis-host-runner/src/container.rs",
        required_patterns: &[
            "host_assisted_loader",
            "container_loader_handoff_blockers",
            "external-import:",
            "container-loader:blocker",
            "position(|byte| *byte == 0)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "host-runner-container-loader-policy-regression",
        path: "tools/nuis-host-runner/src/tests.rs",
        required_patterns: &[
            "allows_host_assisted_container_handoff_when_required_external_import_is_declared",
            "blocks_self_contained_container_handoff_when_required_external_import_is_declared",
            "allows_host_assisted_container_loader_handoff_when_external_import_loader_blockers_are_declared",
            "container_loader_handoff_status",
            "container_loader_handoff_ready",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "self-contained-nsb-frontdoor-smoke",
        path: "tools/nuis/tests/self_contained_nsb_smoke.rs",
        required_patterns: &[
            "self_contained_nsb_route_moves_from_nsld_drive_to_run_artifact_handoff",
            "nuis-self-contained-image",
            "self-contained-image-awaiting-nsld-handoff",
            "nsld-host-entrypoint",
            "host_runner_invoked",
            "host_runner_nsb_readable",
            "host_runner_nsb_hash_matches",
            "host_runner_nsb_payload_region_mapped",
            "host_runner_nsb_payload_scan_kind",
            "nsld-container-toml",
            "host_runner_container_loader_status",
            "host_runner_container_loader_handoff_ready",
            "host_runner_container_loader_handoff_status",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "run-artifact-entrypoint-protocol-regression",
        path: "tools/nuis/src/main_tests/artifact_runtime_run_artifact.rs",
        required_patterns: &[
            "run_artifact_prelaunch_kind",
            "run_artifact_prelaunch_status",
            "run_artifact_prelaunch_evidence_status",
            "nsld-host-entrypoint",
            "run_artifact_json_blocks_nsld_prelaunch_when_entrypoint_stub_is_missing",
            "run_artifact_json_blocks_nsld_prelaunch_when_entrypoint_protocol_is_missing",
            "host entrypoint stub is missing on disk",
            "nuis-nsld-host-entrypoint-v1",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "frontdoor-reference-doc",
        path: "docs/reference/nuis-frontdoor-surface-reference.md",
        required_patterns: &[
            "nsld_final_executable_output_boundary_status",
            "nsld_final_executable_output_materialization_status",
            "nsld_final_executable_output_execution_handoff_contract",
            "nsld_final_executable_output_execution_handoff_ready",
            "nsld_final_executable_output_execution_handoff_status",
            "nsld_final_executable_output_execution_handoff_target",
            "nsld_final_executable_output_execution_handoff_evidence_status",
            "nsld_final_executable_output_execution_handoff_first_blocker",
            "nsld_final_executable_output_execution_handoff_decision_code",
            "nsld_final_executable_pipeline_execution_handoff_contract",
            "nsld_final_executable_pipeline_execution_handoff_ready",
            "nsld_final_executable_pipeline_execution_handoff_status",
            "nsld_final_executable_pipeline_execution_handoff_target",
            "nsld_final_executable_pipeline_execution_handoff_evidence_status",
            "nsld_final_executable_pipeline_execution_handoff_first_blocker",
            "nsld_final_executable_pipeline_execution_handoff_decision_code",
            "nsld_final_executable_output_recommended_next_action",
            "nsld_self_owned_image_status",
            "run_artifact_prelaunch_kind",
            "run_artifact_prelaunch_status",
            "run_artifact_prelaunch_evidence_status",
            "workflow_run_artifact_prelaunch_kind",
            "workflow_run_artifact_prelaunch_status",
            "workflow_run_artifact_prelaunch_evidence_status",
            "workflow_run_artifact_prelaunch_command",
            "workflow_run_artifact_prelaunch_reason",
            "run_artifact_prelaunch_command",
            "run_artifact_prelaunch_runner_command_present",
            "run_artifact_prelaunch_entrypoint_present",
            "run_artifact_prelaunch_entrypoint_protocol",
            "run_artifact_prelaunch_entrypoint_protocol_valid",
            "host_runner_invoked",
            "host_runner_status",
            "host_runner_nsb_readable",
            "host_runner_nsb_payload_region_mapped",
            "host_runner_container_loader_handoff_status",
            "artifact_closure_kind",
            "artifact_closure_status",
            "artifact_closure_evidence_status",
            "artifact_closure_command",
            "artifact_closure_runner_command_present",
            "artifact_closure_entrypoint_present",
            "artifact_closure_entrypoint_protocol",
            "artifact_closure_entrypoint_protocol_valid",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-binary-assembly-doc",
        path: "docs/reference/nsld-binary-assembly-gap-map.md",
        required_patterns: &["self_owned_image_status", "internal binary assembly layer"],
    },
    DevTensorDriftCheckSpec {
        id: "native-artifact-workflow-doc",
        path: "docs/reference/nuis-native-artifact-workflow.md",
        required_patterns: &[
            "nsld_final_executable_output_boundary_status",
            "nsld_final_executable_output_materialization_status",
            "nsld_final_executable_output_execution_handoff_contract",
            "nsld_final_executable_output_execution_handoff_ready",
            "nsld_final_executable_output_execution_handoff_status",
            "nsld_final_executable_output_execution_handoff_target",
            "nsld_final_executable_output_execution_handoff_evidence_status",
            "nsld_final_executable_output_execution_handoff_first_blocker",
            "nsld_final_executable_output_execution_handoff_decision_code",
            "nsld_final_executable_pipeline_execution_handoff_contract",
            "nsld_final_executable_pipeline_execution_handoff_ready",
            "nsld_final_executable_pipeline_execution_handoff_status",
            "nsld_final_executable_pipeline_execution_handoff_target",
            "nsld_final_executable_pipeline_execution_handoff_evidence_status",
            "nsld_final_executable_pipeline_execution_handoff_first_blocker",
            "nsld_final_executable_pipeline_execution_handoff_decision_code",
            "nsld_final_executable_output_recommended_next_action",
            "nsld_self_owned_image_status",
            "run_artifact_prelaunch_kind",
            "run_artifact_prelaunch_status",
            "run_artifact_prelaunch_evidence_status",
            "workflow_run_artifact_prelaunch_kind",
            "workflow_run_artifact_prelaunch_status",
            "workflow_run_artifact_prelaunch_evidence_status",
            "workflow_run_artifact_prelaunch_command",
            "workflow_run_artifact_prelaunch_reason",
            "run_artifact_prelaunch_command",
            "run_artifact_prelaunch_runner_command_present",
            "run_artifact_prelaunch_entrypoint_present",
            "run_artifact_prelaunch_entrypoint_protocol",
            "run_artifact_prelaunch_entrypoint_protocol_valid",
            "host_runner_invoked",
            "host_runner_status",
            "host_runner_nsb_readable",
            "host_runner_nsb_payload_region_mapped",
            "host_runner_container_loader_handoff_status",
            "artifact_closure_kind",
            "artifact_closure_status",
            "artifact_closure_evidence_status",
            "artifact_closure_command",
            "artifact_closure_runner_command_present",
            "artifact_closure_entrypoint_present",
            "artifact_closure_entrypoint_protocol",
            "artifact_closure_entrypoint_protocol_valid",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "std-filesystem-light-smoke",
        path: "tools/nuis/tests/std_filesystem_smoke.rs",
        required_patterns: &[
            "STD_TOOLING_LIGHT_SMOKE_PROJECTS",
            "std_tooling_light_project_smokes_build_doctor_and_run",
            "text_pipeline_demo",
            "io_runtime_demo",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "std-tooling-doc-smoke-chain",
        path: "examples/projects/tooling/README.md",
        required_patterns: &[
            "cargo test -q -p nuis --test std_filesystem_smoke",
            "filesystem_io_report_demo",
            "text_report_json_demo",
            "terminal/stdin/TTY",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "std-readme-host-io-text-lane",
        path: "stdlib/std/README.md",
        required_patterns: &[
            "host I/O and text",
            "filesystem/path/location",
            "lib/io_contracts.ns",
            "lib/text_contracts.ns",
            "lib/fs_contracts.ns",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "dev-tensor-coverage-doc",
        path: "docs/reference/nuis-development-tensor.md",
        required_patterns: &[
            "Coverage Manifest",
            "Status Protocol",
            "Recursive Hierarchy",
            "dev-tensor-status-v1",
            "hierarchy_root_status",
            "weakest_child_path",
            "coverage_status",
            "coverage_missing_coordinates",
            "coverage_orphaned_coordinates",
            "coverage_stale_coordinates",
            "coverage_first_gap",
        ],
    },
];
