use crate::dev_tensor_drift::DevTensorDriftCheckSpec;

pub(crate) const DEV_TENSOR_CORE_DRIFT_CHECKS: &[DevTensorDriftCheckSpec] = &[
    DevTensorDriftCheckSpec {
        id: "frontdoor-final-output-boundary-status",
        path: "tools/nuis/src/surface_render/link_plan_nsld_tail.rs",
        required_patterns: &[
            "nsld_final_executable_output_boundary_status",
            "nsld_final_executable_output_materialization_status",
            "nsld_final_executable_output_execution_handoff_contract",
            "nsld_final_executable_output_execution_handoff_ready",
            "nsld_final_executable_output_execution_handoff_status",
            "nsld_final_executable_output_execution_handoff_target",
            "nsld_final_executable_output_execution_handoff_evidence_status",
            "nsld_final_executable_output_execution_handoff_first_blocker",
            "nsld_final_executable_output_execution_handoff_decision_code",
            "nsld_final_executable_output_recommended_next_action",
            "nsld_final_executable_output_ready",
            "nsld_final_executable_output_object_valid",
            "nsld_final_executable_output_object_expected_hash",
            "nsld_final_executable_output_object_actual_hash",
            "nsld_final_executable_output_object_issues",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-final-output-materialization-status",
        path: "tools/nsld/src/final_executable_output_handoff.rs",
        required_patterns: &[
            "final_executable_output_materialization_status",
            "final_executable_output_execution_handoff_contract",
            "final_executable_output_execution_handoff_ready",
            "final_executable_output_execution_handoff_status",
            "final_executable_output_execution_handoff_target",
            "final_executable_output_execution_handoff_evidence_status",
            "final_executable_output_execution_handoff_first_blocker",
            "final_executable_output_execution_handoff_decision_code",
            "final_executable_output_recommended_next_action",
            "final_executable_first_payload_execution",
            "first_payload_execution.ready",
            "handoff-to-container-loader",
            "handoff-container-loader-first-payload",
            "self-contained-image-ready",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-final-output-report-assembly",
        path: "tools/nsld/src/final_executable_output.rs",
        required_patterns: &[
            "final_executable_container_loader_evidence",
            "container_loader_handoff_ready",
            "container_loader_payload_scan_kind",
            "nsld_nustar_dispatch_blockers",
            "nustar-dispatch:",
            "backend_artifact_assembly_status",
            "first_payload_execution_status",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-final-output-materialization-regression",
        path: "tools/nsld/src/main_final_executable_output_tests.rs",
        required_patterns: &[
            "materialization_status",
            "execution_handoff_contract",
            "execution_handoff_ready",
            "execution_handoff_status",
            "execution_handoff_target",
            "execution_handoff_evidence_status",
            "execution_handoff_first_blocker",
            "execution_handoff_decision_code",
            "container_loader_status",
            "container_loader_handoff_ready",
            "container_loader_payload_scan_kind",
            "first_payload_execution_status",
            "first_payload_execution_ready",
            "first_payload_execution_target",
            "handoff-to-container-loader",
            "handoff-container-loader-first-payload",
            "recommended_next_action",
            "self-contained-image-ready",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-host-finalizer-gate-surface",
        path: "tools/nsld/src/json_final_executable.rs",
        required_patterns: &[
            "host_finalizer_gate_status",
            "host_finalizer_gate_action",
            "policy-blocked",
            "explicit-allow-missing",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-host-finalizer-gate-artifact",
        path: "tools/nsld/src/final_executable_render.rs",
        required_patterns: &[
            "host_finalizer_gate_status",
            "host_finalizer_gate_action",
            "set-env:NUIS_NSLD_HOST_FINALIZER_POLICY=allow-host-invoke",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-host-finalizer-gate-regression",
        path: "tools/nsld/src/main_final_executable_emit_tests.rs",
        required_patterns: &[
            "host_finalizer_gate_status",
            "policy-blocked",
            "set-env:NUIS_NSLD_HOST_FINALIZER_POLICY=allow-host-invoke",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-check-host-finalizer-gate-surface",
        path: "tools/nsld/src/json_check_final.rs",
        required_patterns: &[
            "final_executable_host_finalizer_gate_status",
            "final_executable_host_finalizer_gate_action",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-nsb-relocation-application-layout",
        path: "tools/nsld/src/final_executable_layout_stage.rs",
        required_patterns: &[
            "relocation_application_strategy",
            "nsb-loader-relocation-table",
            "relocation_application_table_hash",
            "relocation_applications",
            "payload0001.container-payload",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-nsb-relocation-application-image-report",
        path: "tools/nsld/src/final_executable_image_stage.rs",
        required_patterns: &[
            "relocation_application_strategy",
            "relocation_application_count",
            "relocation_application_table_hash",
            "relocation_application_audit_status",
            "relocation_application_audit_blockers",
            "relocation_patch_preview_status",
            "relocation_patch_preview_table_hash",
            "relocation_patch_application_status",
            "relocation_patch_application_table_hash",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-nsb-relocation-application-image-verify",
        path: "tools/nsld/src/final_executable_image_verify.rs",
        required_patterns: &[
            "relocation_patch_preview_record_table_hash",
            "relocation_patch_byte_audit_status",
            "relocation_patch_byte_audit_hash",
            "parse_final_executable_image_header",
            "verify_final_executable_image_payload_region",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-nsb-relocation-application-image-resolver",
        path: "tools/nsld/src/final_executable_image_relocation.rs",
        required_patterns: &[
            "resolved_patch_value",
            "target_symbol_image_offset",
            "resolver_status",
            "u64-le-resolved-image-offset",
            "apply_relocation_patches",
            "relocation_patch_byte_audit",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-nsb-relocation-application-image-actual",
        path: "tools/nsld/src/final_executable_image_actual.rs",
        required_patterns: &[
            "relocation_patch_preview_records_from_source",
            "relocation_patch_preview_record_table_hash",
            "resolved_patch_value",
            "target_symbol_image_offset",
            "resolver_status",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-nsb-relocation-final-emit-surface",
        path: "tools/nsld/src/final_executable_emit_shape.rs",
        required_patterns: &[
            "image_dry_run_resolver_status",
            "image_dry_run_patch_application_status",
            "image_dry_run_patch_byte_audit_status",
            "image_dry_run_patch_byte_audit_hash",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-nsb-relocation-final-output-surface",
        path: "tools/nsld/src/final_executable_output.rs",
        required_patterns: &[
            "expected_image_resolver_status",
            "expected_image_patch_application_status",
            "expected_image_patch_byte_audit_status",
            "matches_verified_patched_image",
            "object_output_valid",
            "object_output_expected_hash",
            "object_output_actual_hash",
            "object_output_issues",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-nsb-relocation-final-output-check-surface",
        path: "tools/nsld/src/check_final.rs",
        required_patterns: &[
            "final_executable_output_expected_image_resolver_status",
            "final_executable_output_expected_image_patch_application_status",
            "final_executable_output_expected_image_patch_byte_audit_status",
            "final_executable_output_matches_verified_patched_image",
            "final_executable_output_object_valid",
            "final_executable_output_object_expected_hash",
            "final_executable_output_object_actual_hash",
            "final_executable_output_object_issues",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-nsb-relocation-final-output-check-json",
        path: "tools/nsld/src/json_check_final.rs",
        required_patterns: &[
            "final_executable_output_expected_image_resolver_status",
            "final_executable_output_expected_image_patch_application_status",
            "final_executable_output_expected_image_patch_byte_audit_status",
            "final_executable_output_matches_verified_patched_image",
            "final_executable_output_object_valid",
            "final_executable_output_object_expected_hash",
            "final_executable_output_object_actual_hash",
            "final_executable_output_object_issues",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-nsb-relocation-application-regression",
        path: "tools/nsld/src/main_final_executable_layout_tests.rs",
        required_patterns: &[
            "relocation_application_strategy",
            "relocation_application_count",
            "relocation_application_table_hash",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-check-next-action-final-output-boundary",
        path: "tools/nsld/src/check.rs",
        required_patterns: &[
            "artifact_chain_final_output_boundary_ready",
            "final-output-boundary",
            "artifact_chain_final_output_boundary_command_resolved",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-check-next-action-final-output-boundary-regression",
        path: "tools/nsld/src/drive_tests.rs",
        required_patterns: &[
            "drive_until_clean_command_reaches_host_assisted_pipeline_block",
            "final-output-boundary",
            "final-executable-output",
            "blocked-boundary",
            "read-only-boundary:final-executable-output",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-driver-final-output-boundary-doc",
        path: "docs/reference/nsld-driver-frontdoor.md",
        required_patterns: &[
            "final-output-boundary",
            "blocked-boundary",
            "nsld final-executable-output <input>",
            "Host-assisted final executable emission",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "frontdoor-self-owned-image-status",
        path: "tools/nuis/src/surface_render/link_plan_nsld_tail.rs",
        required_patterns: &[
            "nsld_self_owned_image_status",
            "nsld_entrypoint_materialization_status",
            "nsld_self_owned_image_header_valid",
            "nsld_final_executable_pipeline_execution_handoff_contract",
            "nsld_final_executable_pipeline_execution_handoff_ready",
            "nsld_final_executable_pipeline_execution_handoff_status",
            "nsld_final_executable_pipeline_execution_handoff_target",
            "nsld_final_executable_pipeline_execution_handoff_evidence_status",
            "nsld_final_executable_pipeline_execution_handoff_first_blocker",
            "nsld_final_executable_pipeline_execution_handoff_decision_code",
            "nsld_final_executable_pipeline_entrypoint_materialization_kind",
            "nsld_final_executable_pipeline_entrypoint_materialization_path",
            "nsld_final_executable_pipeline_entrypoint_materialization_ready",
            "nsld_final_executable_pipeline_entrypoint_materialization_first_blocker",
            "nsld_final_executable_pipeline_entrypoint_materialization_present",
            "nsld_final_executable_pipeline_entrypoint_materialization_hash",
            "nsld_final_executable_pipeline_entrypoint_materialization_runner_command",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-pipeline-orchestrator-split-surface",
        path: "tools/nsld/src/final_executable_pipeline.rs",
        required_patterns: &[
            "nsld_pipeline_self_owned_image_status",
            "nsld_pipeline_entrypoint_materialization_status",
            "final_executable_pipeline_required_stage_paths",
            "render_final_executable_pipeline",
            "push_optional_string_mismatch",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-pipeline-self-owned-image-status",
        path: "tools/nsld/src/final_executable_pipeline_status.rs",
        required_patterns: &[
            "nsld_pipeline_self_owned_image_status",
            "launcher_manifest_ready",
            "image_header_valid",
            "path-missing",
            "header-invalid",
            "hash-missing",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-pipeline-entrypoint-materialization",
        path: "tools/nsld/src/final_executable_pipeline_entrypoint.rs",
        required_patterns: &[
            "nsld_pipeline_entrypoint_materialization_status",
            "nsld_pipeline_entrypoint_materialization_plan",
            "nsld_write_host_entrypoint_script",
            "entrypoint_materialization_evidence",
            "render_host_entrypoint_runner_command",
            "host-launcher-ready",
            "image-ready-entrypoint-pending",
            "entrypoint-materializer",
            "host-shell-entrypoint-plan",
            "nuis-nsld-host-entrypoint-v1",
            "NUIS_HOST_ENTRYPOINT_STUB_PROTOCOL",
            "nuis.host-entrypoint.sh",
            "NUIS_HOST_RUNNER",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-pipeline-render-contract",
        path: "tools/nsld/src/final_executable_pipeline_render.rs",
        required_patterns: &[
            "nuis-nsld-final-executable-pipeline-v1",
            "entrypoint_materialization_status",
            "entrypoint_materialization_runner_command",
            "execution_handoff_contract",
            "execution_handoff_decision_code",
            "scheduler_metadata_payload_id",
            "required_stage_path_count",
            "missing_required_stage_paths",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-pipeline-required-paths",
        path: "tools/nsld/src/final_executable_pipeline_paths.rs",
        required_patterns: &[
            "NsldFinalExecutablePipelineRequiredPaths",
            "final_executable_pipeline_required_stage_paths",
            "entrypoint_materialization_path",
            "final_executable_emitted",
            "missing_paths",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-pipeline-mismatch-helpers",
        path: "tools/nsld/src/final_executable_pipeline_mismatch.rs",
        required_patterns: &[
            "optional_bool_text",
            "push_usize_mismatch",
            "push_bool_mismatch",
            "push_optional_string_mismatch",
            "expected",
            "found",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-check-pipeline-handoff-status",
        path: "tools/nsld/src/reports_check.rs",
        required_patterns: &[
            "final_executable_pipeline_execution_handoff_contract",
            "final_executable_pipeline_execution_handoff_ready",
            "final_executable_pipeline_execution_handoff_status",
            "final_executable_pipeline_execution_handoff_target",
            "final_executable_pipeline_execution_handoff_evidence_status",
            "final_executable_pipeline_execution_handoff_first_blocker",
            "final_executable_pipeline_execution_handoff_decision_code",
            "final_executable_pipeline_entrypoint_materialization_kind",
            "final_executable_pipeline_entrypoint_materialization_path",
            "final_executable_pipeline_entrypoint_materialization_ready",
            "final_executable_pipeline_entrypoint_materialization_first_blocker",
            "final_executable_pipeline_entrypoint_materialization_present",
            "final_executable_pipeline_entrypoint_materialization_hash",
            "final_executable_pipeline_entrypoint_materialization_runner_command",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-pipeline-self-owned-image-regression",
        path: "tools/nsld/src/main_final_executable_pipeline_tests.rs",
        required_patterns: &[
            "actual_self_owned_image_status",
            "actual_entrypoint_materialization_status",
            "actual_entrypoint_materialization_kind",
            "actual_entrypoint_materialization_ready",
            "actual_entrypoint_materialization_first_blocker",
            "actual_entrypoint_materialization_present",
            "actual_entrypoint_materialization_hash",
            "actual_entrypoint_materialization_runner_command",
            "actual_execution_handoff_contract",
            "actual_execution_handoff_ready",
            "actual_execution_handoff_status",
            "actual_execution_handoff_target",
            "actual_execution_handoff_evidence_status",
            "actual_execution_handoff_first_blocker",
            "actual_execution_handoff_decision_code",
            "self_owned_image_status",
            "entrypoint_materialization_status",
            "host-shell-entrypoint-plan",
            "NUIS_HOST_RUNNER",
            "nuis-host-runner --manifest",
            "required_stage_path_count, 10",
            "verify_final_executable_pipeline_reports_missing_entrypoint_materialization",
            "verify_final_executable_pipeline_reports_tampered_entrypoint_materialization",
            "entrypoint_materialization_hash mismatch",
            "nsld-final-output-handoff-v1",
            "handoff-container-loader-first-payload",
            "Some(\"ready\")",
            "Some(\"host-launcher-ready\")",
        ],
    },
];
