use crate::dev_tensor_drift::DevTensorDriftCheckSpec;

pub(super) const CHECKS: &[DevTensorDriftCheckSpec] = &[
    DevTensorDriftCheckSpec {
        id: "native-logical-trees-shared-edge-node-depth-and-leaf-permission-budget",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_values_prefix.rs",
        required_patterns: &[
            "let mut work = 4096usize",
            "let mut logical_edges = 32usize",
            "if depth >= 64 || work == 0",
            "(!computed_gate && depth != 0)",
            "(computed_gate && logical_edges == 0)",
            "logical_edges -= 1",
            "(lhs.as_ref(), depth + 1, computed_gate)",
            "(rhs.as_ref(), depth + 1, computed_gate)",
            "args.iter().map(|arg| (arg, depth + 1, false))",
            "(lhs.as_ref(), depth + 1, false)",
            "(rhs.as_ref(), depth + 1, false)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-logical-trees-original-type-proof-before-names-and-selected-rhs",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_values_logical.rs",
        required_patterns: &[
            "!prefix::computed_logical_root(condition)",
            "control_values::value_type(condition, scope, self.catalog, self.layouts)?",
            "let (value, changed) = self.logical_tree(condition, scope)",
            "Generated symbols are deliberately absent from the original catalog",
            "let (left, left_changed) = self.logical_tree(lhs, scope)",
            "let (right, right_changed) = self.logical_tree(rhs, scope)",
            "left_changed || right_changed",
            "control_values::collect_inputs(rhs, &mut inputs)",
            "body: vec![NirStmt::Return(Some(right))]",
            "self.extract(left, yes, no, scope, false)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-logical-trees-source-loop-keeps-independent-atom-only-gate",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_values.rs",
        required_patterns: &[
            "mod logical;",
            "if !in_loop",
            "(atom_gate && prefix::expression_roots(vec![(condition, 0, true)]))",
            "self.gated_condition(condition, scope)",
            "let mut args = vec![condition]",
            "Only the predicate and already-bound values cross this boundary",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-logical-trees-reference-oracle-composition-linearity-and-atomic-vetoes",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_logical_trees_tests.rs",
        required_patterns: &[
            "conditional_logical_trees_preserve_nested_lhs_rhs_binding_roots_and_exit_readiness",
            "assert_eq!(cases, 640)",
            "assert_eq!(cases, 32)",
            "fn evaluate",
            "conditional_logical_trees_keep_linear_helpers_original_capture_scope_and_idempotence",
            "assert_eq!(generated.len(), tree.helpers())",
            "assert_eq!(module, once)",
            "conditional_logical_trees_retain_leaf_embedding_type_effect_scope_and_loop_vetoes",
            "assert_eq!(module, before,",
            "for nested in [false, true]",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-logical-trees-shared-original-expanded-budget-boundaries",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_logical_trees_budget_tests.rs",
        required_patterns: &[
            "for edges in [32, 33]",
            "for args in [4091, 4092]",
            "for depth in [61, 62]",
            "conditional_logical_trees_bound_original_and_expanded_return_suffix_fanout",
            "for count in [8, 9]",
            "expansion shares 32/36",
            "assert_eq!(module, before)",
            "conditional_logical_trees_do_not_authorize_logical_nodes_inside_ordinary_leaves",
            "(&edge, 0, false)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-logical-trees-default-source-aot-nested-traps-and-signals",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_logical_trees_native_tests.rs",
        required_patterns: &[
            "use super::super::tests::native::run",
            "conditional_logical_trees_execute_default_aot_nested_edges_traps_signals_and_zero_exits",
            "Some(\"99\\n77\\n19\")",
            "Some(\"19\")",
            "run(&text, expected)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-logical-trees-documented-shared-guard-and-residual-leaf-boundaries",
        path: "docs/reference/nuis-native-computed-logical-gates-v1.md",
        required_patterns: &[
            "## Nested Logical Trees",
            "one shared 32-logical-edge budget",
            "672 runtime source cases and 1344 ordinary/reversed",
            "fifteen default-source AOT variants",
            "logical gates hidden inside ordinary leaves",
            "current coordinate is `active/94`",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-logical-trees-tensor-proof-history-and-selected-acceptance",
        path: "tools/nuis/src/dev_tensor_data.rs",
        required_patterns: &[
            "Nested logical-tree follow-up:",
            "Nested logical-tree acceptance:",
            "Previous computed return-arm checkpoint:",
            "conditional_logical_trees",
            "active/94",
            "32 logical edges",
            "logical gates hidden inside ordinary leaves",
        ],
    },
];
