use crate::dev_tensor_drift::DevTensorDriftCheckSpec;

pub(crate) const DEV_TENSOR_RUNTIME_VULKAN_DRIFT_CHECKS: &[DevTensorDriftCheckSpec] = &[
    DevTensorDriftCheckSpec {
        id: "nsdb-vulkan-host-probe",
        path: "tools/nsdb/src/provider_runner_vulkan.rs",
        required_patterns: &[
            "nuis-vulkan-host-probe-v1",
            "spirv.vulkan-gpu.bundle.v1",
            "spirv:vulkan-gpu",
            "libvulkan.so.1",
            "vkEnumerateInstanceVersion",
            "vkCreateInstance",
            "vkEnumeratePhysicalDevices",
            "vulkan-spirv-real-device-runner",
            "NUIS_REQUIRE_VULKAN_DEVICE_PROBE",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-vulkan-probe-only-execution-gate",
        path: "tools/nsdb/src/provider_execution_vulkan.rs",
        required_patterns: &[
            "vulkan-spirv-real-device-runner",
            "nuis-vulkan-spirv-execution-session-plan-v1",
            "validate_vulkan_execution_session_plan",
            "nuis-vulkan-spirv-provider-execution-v1",
            "parse_vulkan_worker_protocol",
            "vulkan_session_plan_accepts_registered_copy_u32_shape",
            "vulkan_session_plan_rejects_asset_or_binding_drift",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "shader-nustar-vulkan-provider-bundle",
        path: "nustar-packages/shader.toml",
        required_patterns: &[
            "spirv.vulkan-gpu.bundle.v1",
            "spirv:vulkan-gpu",
            "provider_runner_vulkan::PROVIDER_BUNDLE",
            "spirv.vulkan.real-device",
            "vulkan-spirv-real-device-runner",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-vulkan-spirv-process-adapter",
        path: "tools/nsdb/provider-runners/vulkan_spirv_dispatch.c",
        required_patterns: &[
            "nuis-vulkan-spirv-provider-runner-v1",
            "libvulkan.so.1",
            "vkCreateComputePipelines",
            "VK_DESCRIPTOR_TYPE_STORAGE_BUFFER",
            "vkCmdDispatch",
            "vkQueueSubmit",
            "NUIS_PROVIDER_OUTPUT_FD",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "shader-nustar-vulkan-spirv-source",
        path: "nustar-packages/assets/shader/vulkan_copy_u32.nspv",
        required_patterns: &[
            "nuis-spirv-compute-source-v1",
            "operation = \"copy-u32\"",
            "entry = \"nuis_vulkan_copy_u32\"",
            "input_binding = 0",
            "output_binding = 1",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuisc-shader-spirv-emitter",
        path: "tools/nuisc/src/shader_spirv_emitter.rs",
        required_patterns: &[
            "nuis-spirv-compute-source-v1",
            "lower_registered_compute_source",
            "emit_copy_u32_module",
            "SPIRV_MAGIC",
            "SPIRV_VERSION_1_6",
            "rejects_entry_or_binding_drift",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "shader-nustar-vulkan-code-asset-registration",
        path: "nustar-packages/shader.toml",
        required_patterns: &[
            "shader.vulkan.copy-u32.spirv",
            "spirv-binary",
            "vulkan.discrete-or-integrated-gpu",
            "vulkan1.3-spirv1.6",
            "assets/shader/vulkan_copy_u32.nspv",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuisc-vulkan-spirv-aot-materialization",
        path: "tools/nuisc/src/aot_domain_artifact_writer.rs",
        required_patterns: &[
            "materializes_registered_vulkan_spirv_and_contribution_table",
            "shader.vulkan.copy-u32.spirv",
            "nuis.shader.vulkan.copy-u32.spv",
            "spirv-binary",
            "vulkan.discrete-or-integrated-gpu",
            "nuis_vulkan_copy_u32",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuisc-vulkan-spirv-external-validator-hook",
        path: "tools/nuisc/src/registry_code_asset.rs",
        required_patterns: &[
            "registered_vulkan_spirv_passes_external_validator_when_configured",
            "NUIS_SPIRV_VAL",
            "--target-env",
            "vulkan1.3",
            "rejected registered Vulkan SPIR-V",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-shader-vulkan-device-sample-registration",
        path: "tools/nuis/src/artifact_device_sample_shader_vulkan.rs",
        required_patterns: &[
            "DeviceSampleInputRegistration",
            "provider_family: \"spirv:vulkan-gpu\"",
            "shader.vulkan.copy-u32.spirv",
            "provider_code_asset_format=spirv-binary",
            "provider_adapter_binding_provider_family=spirv:vulkan-gpu",
            "select_compiled_code_asset_contribution",
            "render_selected_contribution_set_evidence",
            "validate_provider_request_evidence",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-device-sample-canonical-provider-family",
        path: "tools/nuis/src/artifact_device_sample_registration.rs",
        required_patterns: &[
            "provider_family",
            "registered_provider_family",
            "vulkan",
            "discrete-or-integrated-gpu",
            "spirv:vulkan-gpu",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-code-asset-selection-set-single-base-case",
        path: "tools/nsdb/src/provider_code_asset_selection_payload.rs",
        required_patterns: &[
            "SINGLE_CONTRACT | SET_CONTRACT",
            "single_item_selection_set_round_trips_as_base_case",
            "compiled_code_asset_selection_count",
            "nuis-provider-code-asset-contribution-selection-set-v1",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-shader-vulkan-provider-demo",
        path: "examples/projects/domains/shader_vulkan_provider_demo/nuis.toml",
        required_patterns: &[
            "shader_vulkan_provider_demo",
            "cpu=cpu.x86_64.sysv64",
            "shader=shader.vulkan.spv1_6",
            "nuis-self-contained-image",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "linux-vulkan-provider-sample-smoke",
        path: "tools/nuis/tests/official_galaxy_hetero_smoke/linux_vulkan.rs",
        required_patterns: &[
            "linux_vulkan_shader_sample_executes_provider_output",
            "execute-provider-samples",
            "materialize-provider-samples",
            "nuis-vulkan-spirv-provider-execution-v1",
            "0x6ebcdd244b594ee4",
        ],
    },
];
