use crate::dev_tensor_drift::DevTensorDriftCheckSpec;

pub(crate) const DEV_TENSOR_RUNTIME_NSLD_SHELL_IMAGE_DRIFT_CHECKS: &[DevTensorDriftCheckSpec] = &[
    DevTensorDriftCheckSpec {
        id: "nsld-macho-arm64-shell-image-serialization-contract",
        path: "tools/nsld/src/final_executable_macho_shell_image.rs",
        required_patterns: &[
            "nuis-nsld-macho-arm64-shell-image-serialization-v2",
            "serialize_macho_arm64_shell_image",
            "signed-private-image-validated",
            "private-not-published",
            "plan_macho_arm64_ad_hoc_signature",
            "encode_macho_arm64_ad_hoc_signature",
            "validate_macho_arm64_signed_shell_image",
            "encode_shell_header_and_commands",
            "encode_shell_linkedit",
            "rewrite_shell_image_addresses",
            "serialization_ledger_hash",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-macho-arm64-shell-image-final-address-evidence",
        path: "tools/nsld/src/final_executable_macho_shell_image_tests.rs",
        required_patterns: &[
            "serializes_a_deterministic_private_arm64_shell_image",
            "relocation-final-address",
            "stub-final-address",
            "serializes_internal_got_rebase_with_final_pointer_value",
            "internal-got-final-address",
            "signed_image_validator_rejects_signed_content_drift",
            "signed_image_validator_rejects_load_command_boundary_drift",
            "signed_image_validator_rejects_signature_padding_drift",
            "platform image drift",
            "input hash drift",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-macho-arm64-shell-image-three-surface-evidence",
        path: "tools/nsld/tests/host_finalizer_cli.rs",
        required_patterns: &[
            "nuis-nsld-macho-arm64-shell-image-serialization-v2",
            "signed-private-image-validated",
            "private-not-published",
            "ad-hoc-payload-validated",
            "signed-private-image-structurally-valid",
            "independent-os-load-validation-pending",
            "shell_image_serialization",
            "finalizer_input_shell_image_contract",
            "finalizer_input_shell_image_rewrite",
            "persisted_invoke_plan",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-macho-arm64-ad-hoc-signature-contract",
        path: "tools/nsld/src/final_executable_macho_shell_signature.rs",
        required_patterns: &[
            "nuis-nsld-macho-arm64-ad-hoc-signature-v1",
            "plan_macho_arm64_ad_hoc_signature",
            "encode_macho_arm64_ad_hoc_signature",
            "CSMAGIC_EMBEDDED_SIGNATURE",
            "CSMAGIC_CODEDIRECTORY",
            "HASH_TYPE_SHA256",
            "CODE_PAGE_SIZE_BYTES",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-macho-arm64-signed-image-validation-contract",
        path: "tools/nsld/src/final_executable_macho_shell_signature_validation.rs",
        required_patterns: &[
            "nuis-nsld-macho-arm64-signed-image-validation-v1",
            "nuis-nsld-macho-arm64-publication-eligibility-v1",
            "validate_macho_arm64_signed_shell_image",
            "signed-private-image-structurally-valid",
            "blocked-independent-os-load-validation-pending",
            "validate_load_commands",
            "validate_code_slots",
            "validation_ledger_hash",
        ],
    },
];
