use crate::dev_tensor_drift::DevTensorDriftCheckSpec;

pub(crate) const DEV_TENSOR_RUNTIME_NSLD_DRIFT_CHECKS: &[DevTensorDriftCheckSpec] = &[
    DevTensorDriftCheckSpec {
        id: "nustar-domain-contract-completeness-status",
        path: "tools/nuisc/src/registry_contract.rs",
        required_patterns: &[
            "contract_status",
            "required_domain_contract_groups",
            "missing_domain_contract_groups",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nustar-domain-contract-completeness-json",
        path: "tools/nuisc/src/registry_domain_json.rs",
        required_patterns: &[
            "contract_complete",
            "required_contract_groups",
            "missing_contract_groups",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nustar-dispatch-readiness-contract",
        path: "tools/nuisc/src/registry_contract.rs",
        required_patterns: &[
            "NUSTAR_DOMAIN_CONTRACT_GROUP_DISPATCH_READINESS",
            "dispatch_readiness_summary",
            "required_dispatch_readiness_signals",
            "dispatch_bridge_materialized",
            "execution_readiness_materialized",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nustar-dispatch-readiness-json",
        path: "tools/nuisc/src/registry_domain_json.rs",
        required_patterns: &[
            "dispatch_readiness_status",
            "dispatch_bridge_materialized",
            "execution_readiness_materialized",
            "dispatch_readiness_missing_signals",
            "NUSTAR_DOMAIN_CONTRACT_GROUP_DISPATCH_READINESS",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nustar-dispatch-readiness-link-plan-consumption",
        path: "tools/nuis/src/surface_render/link_plan.rs",
        required_patterns: &[
            "backend_artifact_ready",
            "link_plan_heterogeneous_backend_artifact_ready_units",
            "link_plan_heterogeneous_backend_artifact_first_unready",
            "link_plan_heterogeneous_domain_registry_dispatch_ready_units",
            "link_plan_heterogeneous_domain_registry_dispatch_first_blocked",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nustar-dispatch-readiness-link-plan-model",
        path: "tools/nuis/src/surface_render/link_plan_readiness.rs",
        required_patterns: &[
            "registry_dispatch_readiness_status",
            "registry_dispatch_readiness_ready",
            "registry_dispatch_missing_signals",
            "registry_dispatch_bridge_materialized",
            "registry_execution_readiness_materialized",
            "backend_artifact_key",
            "backend_artifact_candidate",
            "backend_artifact_missing_signals",
            "registry_dispatch_readiness_blocked",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nustar-dispatch-readiness-workflow-consumption",
        path: "tools/nuis/src/workflow/link_plan_domain.rs",
        required_patterns: &[
            "registry_dispatch_readiness_status",
            "registry_dispatch_readiness_ready",
            "registry_dispatch_missing_signals",
            "registry_dispatch_bridge_materialized",
            "registry_execution_readiness_materialized",
            "backend_artifact_key",
            "backend_artifact_candidate",
            "backend_artifact_ready",
            "backend_artifact_missing_signals",
            "backend_artifact_first_unready",
            "registry_dispatch_readiness_blocked",
            "workflow_registry_dispatch_readiness",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nustar-dispatch-readiness-nsld-final-output-ordering",
        path: "tools/nsld/src/main_final_executable_output_tests.rs",
        required_patterns: &[
            "final_executable_output_orders_nustar_dispatch_blockers_before_output_bytes",
            "nustar-dispatch:official.ghost:registry-unavailable",
            "backend_artifact_candidate_count",
            "backend_artifact_ready_count",
            "backend_artifact_selection_status",
            "backend_artifact_ordered_candidates",
            "backend_artifact_selected_candidate",
            "backend_artifact_selection_reason",
            "backend_artifact_assembly_status",
            "backend_artifact_selected_payload_path",
            "backend_artifact_selected_payload_consumed",
            "backend_artifact_assembly_first_blocker",
            "backend_artifact_first_unready",
            "nustar-backend-artifact:ghost:ghost:none:unready",
            "final_executable_output_selects_first_ready_backend_artifact_candidate_by_priority",
            "consumed-by-final-layout",
            "payload_execution_trace_protocol",
            "payload_execution_trace_available",
            "payload_execution_trace_record_count",
            "payload_execution_trace_ready_record_count",
            "handoff-payload-trace-to-nsdb",
            "final-executable-output:missing",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nustar-backend-artifact-image-role-evidence",
        path: "tools/nsld/src/main_final_executable_image_tests.rs",
        required_patterns: &[
            "final_executable_image_dry_run_reports_backend_artifact_payload_roles",
            "backend_artifact_payload_count",
            "backend_artifact_payload_present_count",
            "backend_artifact_payload_role_status",
            "backend_artifact_payload_ids",
            "backend_artifact_payload_kinds",
            "backend_artifact_payload_first_missing",
            "nustar-backend-artifact:kernel:aarch64:apple-silicon-cpu",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-device-provider-sample-final-output-evidence",
        path: "tools/nsld/src/final_executable_provider_sample.rs",
        required_patterns: &[
            "nsld_device_provider_sample_evidence",
            "nuis.nsdb.device-provider-samples.toml",
            "nuis-device-provider-samples-v1",
            "nsdb-yir-device-provider-sample-v1",
            "provider-sample-pending",
            "provider-sample-materialized",
            "device-provider-sample",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-device-provider-sample-final-output-surface",
        path: "tools/nsld/src/main_final_executable_provider_sample_tests.rs",
        required_patterns: &[
            "final_output_reports_pending_device_provider_sample_manifest_as_blocker",
            "final_output_accepts_ready_device_provider_sample_manifest",
            "device_provider_sample_manifest_available",
            "device_provider_sample_manifest_status",
            "device_provider_sample_manifest_first_blocker",
        ],
    },
];
