use crate::dev_tensor_drift::DevTensorDriftCheckSpec;

pub(crate) const DEV_TENSOR_RUNTIME_VULKAN_DRIFT_CHECKS: &[DevTensorDriftCheckSpec] = &[
    DevTensorDriftCheckSpec {
        id: "nsdb-vulkan-host-probe",
        path: "tools/nsdb/src/provider_runner_vulkan.rs",
        required_patterns: &[
            "nuis-vulkan-host-probe-v1",
            "spirv.vulkan-gpu.bundle.v1",
            "spirv:vulkan-gpu",
            "libvulkan.so.1",
            "vkEnumerateInstanceVersion",
            "vkCreateInstance",
            "vkEnumeratePhysicalDevices",
            "vulkan-spirv-real-device-runner",
            "vulkan_dispatch_source_keeps_dynamic_input_and_output_descriptor_abi",
            "NUIS_REQUIRE_VULKAN_DEVICE_PROBE",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-vulkan-probe-only-execution-gate",
        path: "tools/nsdb/src/provider_execution_vulkan.rs",
        required_patterns: &[
            "vulkan-spirv-real-device-runner",
            "nuis-vulkan-spirv-execution-session-plan-v1",
            "validate_vulkan_execution_session_plan",
            "nuis-vulkan-spirv-provider-execution-v1",
            "parse_vulkan_worker_protocol",
            "vulkan_input_source_is_supported",
            "vulkan_u32_entry_for_operation",
            "descriptor layout does not match the registered runner ABI",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-vulkan-execution-contract-tests",
        path: "tools/nsdb/src/provider_execution_vulkan_tests.rs",
        required_patterns: &[
            "vulkan_session_plan_accepts_registered_u32_shapes",
            "vulkan_session_plan_accepts_verified_dependency_input",
            "vulkan_session_plan_accepts_registered_pair_fan_in",
            "vulkan_session_plan_accepts_independent_padded_output_layout",
            "vulkan_session_plan_accepts_reduced_secondary_output_extent",
            "nuis_vulkan_add_pair_u32",
            "16:16:8:8:2,16:24:8:12:2",
            "16:16:8:8:2,8:8:8:8:1",
            "vulkan_session_plan_rejects_asset_or_binding_drift",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-vulkan-spirv-layout-validation",
        path: "tools/nsdb/src/provider_execution_vulkan_spirv.rs",
        required_patterns: &[
            "validate_spirv_u32_module",
            "parse_spirv_storage_buffer_layout",
            "VulkanStorageBufferLayout",
            "DescriptorSet",
            "Binding",
            "non_writable",
            "non_readable",
            "fnv1a64_hex",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "shader-nustar-vulkan-provider-bundle",
        path: "nustar-packages/shader.toml",
        required_patterns: &[
            "spirv.vulkan-gpu.bundle.v1",
            "spirv:vulkan-gpu",
            "provider_runner_vulkan::PROVIDER_BUNDLE",
            "spirv.vulkan.real-device",
            "vulkan-spirv-real-device-runner",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-vulkan-spirv-process-adapter",
        path: "tools/nsdb/provider-runners/vulkan_spirv_dispatch.c",
        required_patterns: &[
            "nuis-vulkan-spirv-provider-runner-v1",
            "libvulkan.so.1",
            "vkCreateComputePipelines",
            "VK_DESCRIPTOR_TYPE_STORAGE_BUFFER",
            "vkCmdDispatch",
            "vkQueueSubmit",
            "read_input(argv[3 + i]",
            "argc != 6 && argc != 7",
            "buffer_count = (size_t)input_count + output_count",
            "buffer_lengths[(size_t)input_count + i] = output_layouts[i].logical_length",
            "output_layouts[i].logical_length > byte_length",
            "VkDescriptorSetLayoutBinding bindings[2 + NUIS_VULKAN_MAX_OUTPUTS]",
            "VkBuffer buffers[2 + NUIS_VULKAN_MAX_OUTPUTS]",
            "VkDeviceMemory memories[2 + NUIS_VULKAN_MAX_OUTPUTS]",
            "output_hashes=",
            "output_count=%zu",
            "output_byte_lengths=",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-vulkan-spirv-process-adapter-io",
        path: "tools/nsdb/provider-runners/vulkan_spirv_dispatch_io.c",
        required_patterns: &[
            "NUIS_VULKAN_MAX_OUTPUTS 8",
            "NUIS_PROVIDER_OUTPUT_FDS",
            "NUIS_PROVIDER_OUTPUT_FD",
            "parse_output_descriptors",
            "parse_output_layouts",
            "OutputLayout",
            "NUISPFD1",
            "read_carrier_frame",
            "valid_spirv_entry",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "shader-nustar-vulkan-spirv-source",
        path: "nustar-packages/assets/shader/vulkan_copy_u32.ns",
        required_patterns: &[
            "shader_inline_wgsl",
            "wgsl {",
            "nuis_vulkan_copy_u32",
            "binding(0, 0)",
            "binding(0, 1)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "shader-nustar-vulkan-add-spirv-source",
        path: "nustar-packages/assets/shader/vulkan_add_u32.ns",
        required_patterns: &[
            "shader_inline_wgsl",
            "wgsl {",
            "nuis_vulkan_add_u32",
            "output_values[idx] = input_values[idx] + input_values[idx];",
            "binding(0, 1)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "shader-nustar-vulkan-sub-spirv-source",
        path: "nustar-packages/assets/shader/vulkan_sub_u32.ns",
        required_patterns: &[
            "shader_inline_wgsl",
            "wgsl {",
            "nuis_vulkan_sub_u32",
            "output_values[idx] = input_values[idx] - input_values[idx];",
            "binding(0, 1)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "shader-nustar-vulkan-add-pair-spirv-source",
        path: "nustar-packages/assets/shader/vulkan_add_pair_u32.ns",
        required_patterns: &[
            "shader_inline_wgsl",
            "nuis_vulkan_add_pair_u32",
            "binding(0, 0)",
            "binding(0, 1)",
            "binding(0, 2)",
            "left_values[idx] + right_values[idx]",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "shader-nustar-vulkan-add-xor-pair-spirv-source",
        path: "nustar-packages/assets/shader/vulkan_add_xor_pair_u32.ns",
        required_patterns: &[
            "shader_inline_wgsl",
            "nuis_vulkan_add_xor_pair_u32",
            "binding(0, 2)",
            "binding(0, 3)",
            "sum_values[idx] = left_values[idx] + right_values[idx]",
            "xor_values[idx] = left_values[idx] ^ right_values[idx]",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "shader-nustar-vulkan-reduced-fan-out-source",
        path: "nustar-packages/assets/shader/vulkan_add_xor_pair_reduced_u32.ns",
        required_patterns: &[
            "nuis_vulkan_add_xor_pair_reduced_u32",
            "xor_values: array<u32, 2>",
            "sum_values[idx] = left_values[idx] + right_values[idx]",
            "xor_values[idx] = left_values[idx] ^ right_values[idx]",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-shader-vulkan-padded-fan-out-registration",
        path: "tools/nuis/src/artifact_device_sample_shader_vulkan_fan_out.rs",
        required_patterns: &[
            "official.shader.vulkan-add-xor-pair-padded-u32",
            "provider-sample=vulkan-add-xor-pair-padded-u32",
            "PADDED_XOR_EXPECTED",
            "row_stride_bytes: xor_row_stride_bytes",
            "0x9adad3c97291d1e8",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-shader-vulkan-padded-fan-out-project",
        path: "examples/projects/domains/shader_vulkan_padded_fan_out_provider_demo/nuis.toml",
        required_patterns: &[
            "shader_vulkan_padded_fan_out_provider_demo",
            "official.shader:provider-sample=vulkan-add-xor-pair-padded-u32",
            "cpu.x86_64.sysv64",
            "shader.vulkan.spv1_6",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-shader-vulkan-reduced-fan-out-registration",
        path: "tools/nuis/src/artifact_device_sample_shader_vulkan_fan_out.rs",
        required_patterns: &[
            "official.shader.vulkan-add-xor-pair-reduced-u32",
            "provider-sample=vulkan-add-xor-pair-reduced-u32",
            "REDUCED_XOR_EXPECTED",
            "output_binding_1_shape=2x1",
            "0x279d73758e81abdd",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-shader-vulkan-reduced-fan-out-project",
        path: "examples/projects/domains/shader_vulkan_reduced_fan_out_provider_demo/nuis.toml",
        required_patterns: &[
            "shader_vulkan_reduced_fan_out_provider_demo",
            "official.shader:provider-sample=vulkan-add-xor-pair-reduced-u32",
            "cpu.x86_64.sysv64",
            "shader.vulkan.spv1_6",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-shader-vulkan-reduced-fan-out-smoke",
        path: "tools/nuis/tests/official_galaxy_hetero_smoke/linux_vulkan.rs",
        required_patterns: &[
            "linux_vulkan_reduced_fan_out_shader_bounds_secondary_output",
            "shader.vulkan.add-xor-pair-reduced-u32.spirv",
            "output_binding_1_shape=2x1",
            "0x279d73758e81abdd",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "shader-nustar-vulkan-mul-spirv-source",
        path: "nustar-packages/assets/shader/vulkan_mul_u32.ns",
        required_patterns: &[
            "shader_inline_wgsl",
            "wgsl {",
            "nuis_vulkan_mul_u32",
            "output_values[idx] = input_values[idx] * input_values[idx];",
            "binding(0, 1)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "shader-nustar-vulkan-xor-spirv-source",
        path: "nustar-packages/assets/shader/vulkan_xor_u32.ns",
        required_patterns: &[
            "shader_inline_wgsl",
            "wgsl {",
            "nuis_vulkan_xor_u32",
            "output_values[idx] = input_values[idx] ^ input_values[idx];",
            "binding(0, 1)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuisc-shader-spirv-emitter",
        path: "tools/nuisc/src/shader_spirv_emitter.rs",
        required_patterns: &[
            "nuis-spirv-compute-source-v1",
            "lower_registered_compute_source",
            "parse_canonical_inline_wgsl_u32_compute",
            "emit_u32_module",
            "spirv_u32_binary_opcode",
            "validate_u32_compute_bindings",
            "aux_input_binding",
            "SpirvInputIds",
            "SpirvOutputIds",
            "SpirvOutputGuardIds",
            "CanonicalU32WriteExtent::Elements",
            "allocate_spirv_id",
            "output_ids",
            "CanonicalU32Operation::AddU32",
            "CanonicalU32Operation::SubU32",
            "CanonicalU32Operation::MulU32",
            "CanonicalU32Operation::XorU32",
            "CanonicalU32Operation::AddPairU32",
            "CanonicalU32Operation::XorPairU32",
            "SPIRV_MAGIC",
            "SPIRV_VERSION_1_6",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuisc-shader-canonical-compute-contract",
        path: "tools/nuisc/src/shader_canonical_compute.rs",
        required_patterns: &[
            "CanonicalU32Compute",
            "CanonicalU32Output",
            "CanonicalU32WriteExtent",
            "parse_u32_array_extent",
            "outputs: Vec<CanonicalU32Output>",
            "one to eight writable storage outputs",
            "parse_canonical_inline_wgsl_u32_compute",
            "parse_u32_operation",
            "U32_OPERATION_PATTERNS",
            "aux_input_binding",
            "detect_two_input_body_operation",
            "CanonicalU32Operation::AddU32",
            "CanonicalU32Operation::SubU32",
            "CanonicalU32Operation::MulU32",
            "CanonicalU32Operation::XorU32",
            "CanonicalU32Operation::AddPairU32",
            "CanonicalU32Operation::XorPairU32",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuisc-shader-msl-emitter",
        path: "tools/nuisc/src/shader_msl_emitter.rs",
        required_patterns: &[
            "lower_canonical_inline_wgsl_u32_for_profile",
            "nuis-yir.shader.backend-lowering-plan.v1",
            "validate_msl_module_lowering_plan",
            "nuis-module-lowering-plan",
            "msl:metal-gpu",
            "argument-buffer-slot",
            "parse_canonical_inline_wgsl_u32_compute",
            "metal.apple-silicon-gpu",
            "metal.mac-discrete-or-integrated-gpu",
            "kernel void",
            "right_values",
            "CanonicalU32Operation::AddU32",
            "CanonicalU32Operation::SubU32",
            "CanonicalU32Operation::MulU32",
            "CanonicalU32Operation::XorU32",
            "CanonicalU32Operation::AddPairU32",
            "CanonicalU32Operation::XorPairU32",
            "output_parameters",
            "output_stores",
            "CanonicalU32WriteExtent::Elements",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuisc-shader-spirv-emitter-tests",
        path: "tools/nuisc/src/shader_spirv_emitter_tests.rs",
        required_patterns: &[
            "rejects_entry_or_binding_drift",
            "emits_binary_u32_modules_from_canonical_wgsl_body",
            "nuis_vulkan_add_u32",
            "nuis_vulkan_sub_u32",
            "nuis_vulkan_mul_u32",
            "nuis_vulkan_xor_u32",
            "nuis_vulkan_add_pair_u32",
            "aux_input_binding",
            "emits_pair_add_u32_module_from_canonical_wgsl_body",
            "emits_canonical_multi_output_spirv",
            "emits_bounds_safe_reduced_output_spirv",
            "rejects_zero_output_write_extent",
            "nuis_vulkan_add_xor_pair_u32",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuisc-shader-msl-emitter-tests",
        path: "tools/nuisc/src/shader_msl_emitter_tests.rs",
        required_patterns: &[
            "emits_msl_copy_module_from_canonical_wgsl_body",
            "emits_binary_u32_msl_from_shared_canonical_body_contract",
            "rejects_msl_module_lowering_plan_drift",
            "assert_msl_plan_proof",
            "nuis_metal_add_u32",
            "nuis_metal_sub_u32",
            "nuis_metal_mul_u32",
            "nuis_metal_xor_u32",
            "nuis_metal_add_pair_u32",
            "emits_pair_add_u32_msl_from_shared_canonical_body_contract",
            "emits_ordered_multi_output_u32_msl",
            "emits_bounds_safe_reduced_output_u32_msl",
            "output_values_1",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "shader-nustar-metal-canonical-source",
        path: "nustar-packages/assets/shader/metal_copy_u32.ns",
        required_patterns: &[
            "shader_inline_wgsl",
            "wgsl {",
            "binding(0, 0)",
            "binding(0, 1)",
            "stage compute",
            "nuis_metal_copy_u32",
            "output_values[idx] = input_values[idx];",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "shader-nustar-metal-add-canonical-source",
        path: "nustar-packages/assets/shader/metal_add_u32.ns",
        required_patterns: &[
            "shader_inline_wgsl",
            "wgsl {",
            "binding(0, 0)",
            "binding(0, 1)",
            "stage compute",
            "nuis_metal_add_u32",
            "output_values[idx] = input_values[idx] + input_values[idx];",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "shader-nustar-metal-sub-canonical-source",
        path: "nustar-packages/assets/shader/metal_sub_u32.ns",
        required_patterns: &[
            "shader_inline_wgsl",
            "wgsl {",
            "binding(0, 0)",
            "binding(0, 1)",
            "stage compute",
            "nuis_metal_sub_u32",
            "output_values[idx] = input_values[idx] - input_values[idx];",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "shader-nustar-metal-add-pair-canonical-source",
        path: "nustar-packages/assets/shader/metal_add_pair_u32.ns",
        required_patterns: &[
            "shader_inline_wgsl",
            "nuis_metal_add_pair_u32",
            "binding(0, 0)",
            "binding(0, 1)",
            "binding(0, 2)",
            "left_values[idx] + right_values[idx]",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "shader-nustar-metal-add-xor-pair-canonical-source",
        path: "nustar-packages/assets/shader/metal_add_xor_pair_u32.ns",
        required_patterns: &[
            "shader_inline_wgsl",
            "nuis_metal_add_xor_pair_u32",
            "binding(0, 2)",
            "binding(0, 3)",
            "sum_values[idx] = left_values[idx] + right_values[idx]",
            "xor_values[idx] = left_values[idx] ^ right_values[idx]",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "shader-nustar-metal-reduced-fan-out-source",
        path: "nustar-packages/assets/shader/metal_add_xor_pair_reduced_u32.ns",
        required_patterns: &[
            "nuis_metal_add_xor_pair_reduced_u32",
            "xor_values: array<u32, 2>",
            "sum_values[idx] = left_values[idx] + right_values[idx]",
            "xor_values[idx] = left_values[idx] ^ right_values[idx]",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "shader-nustar-metal-mul-canonical-source",
        path: "nustar-packages/assets/shader/metal_mul_u32.ns",
        required_patterns: &[
            "shader_inline_wgsl",
            "wgsl {",
            "binding(0, 0)",
            "binding(0, 1)",
            "stage compute",
            "nuis_metal_mul_u32",
            "output_values[idx] = input_values[idx] * input_values[idx];",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "shader-nustar-metal-xor-canonical-source",
        path: "nustar-packages/assets/shader/metal_xor_u32.ns",
        required_patterns: &[
            "shader_inline_wgsl",
            "wgsl {",
            "binding(0, 0)",
            "binding(0, 1)",
            "stage compute",
            "nuis_metal_xor_u32",
            "output_values[idx] = input_values[idx] ^ input_values[idx];",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "shader-nustar-vulkan-code-asset-registration",
        path: "nustar-packages/shader.toml",
        required_patterns: &[
            "shader.vulkan.copy-u32.spirv",
            "spirv-binary",
            "vulkan.discrete-or-integrated-gpu",
            "vulkan1.3-spirv1.6",
            "assets/shader/vulkan_copy_u32.ns",
            "shader.vulkan.add-u32.spirv",
            "nuis_vulkan_add_u32",
            "assets/shader/vulkan_add_u32.ns",
            "shader.vulkan.add-pair-u32.spirv",
            "nuis_vulkan_add_pair_u32",
            "assets/shader/vulkan_add_pair_u32.ns",
            "shader.vulkan.add-xor-pair-reduced-u32.spirv",
            "nuis_vulkan_add_xor_pair_reduced_u32",
            "assets/shader/vulkan_add_xor_pair_reduced_u32.ns",
            "shader.vulkan.sub-u32.spirv",
            "nuis_vulkan_sub_u32",
            "assets/shader/vulkan_sub_u32.ns",
            "shader.vulkan.mul-u32.spirv",
            "nuis_vulkan_mul_u32",
            "assets/shader/vulkan_mul_u32.ns",
            "shader.vulkan.xor-u32.spirv",
            "nuis_vulkan_xor_u32",
            "assets/shader/vulkan_xor_u32.ns",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "shader-nustar-metal-canonical-code-asset-registration",
        path: "nustar-packages/shader.toml",
        required_patterns: &[
            "shader.metal.copy-u32.msl",
            "metal-source",
            "metal.apple-silicon-gpu",
            "msl2.4",
            "nuis_metal_copy_u32",
            "assets/shader/metal_copy_u32.ns",
            "shader.metal.add-u32.msl",
            "nuis_metal_add_u32",
            "assets/shader/metal_add_u32.ns",
            "shader.metal.add-pair-u32.msl",
            "nuis_metal_add_pair_u32",
            "assets/shader/metal_add_pair_u32.ns",
            "shader.metal.add-xor-pair-u32.msl",
            "nuis_metal_add_xor_pair_u32",
            "assets/shader/metal_add_xor_pair_u32.ns",
            "shader.metal.add-xor-pair-reduced-u32.msl",
            "nuis_metal_add_xor_pair_reduced_u32",
            "assets/shader/metal_add_xor_pair_reduced_u32.ns",
            "shader.metal.sub-u32.msl",
            "nuis_metal_sub_u32",
            "assets/shader/metal_sub_u32.ns",
            "shader.metal.mul-u32.msl",
            "nuis_metal_mul_u32",
            "assets/shader/metal_mul_u32.ns",
            "shader.metal.xor-u32.msl",
            "nuis_metal_xor_u32",
            "assets/shader/metal_xor_u32.ns",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuisc-vulkan-spirv-aot-materialization",
        path: "tools/nuisc/src/aot_domain_artifact_writer.rs",
        required_patterns: &[
            "materializes_registered_vulkan_spirv_and_contribution_table",
            "shader.vulkan.copy-u32.spirv",
            "nuis.shader.vulkan.copy-u32.spv",
            "shader.vulkan.add-u32.spirv",
            "nuis.shader.vulkan.add-u32.spv",
            "shader.vulkan.add-pair-u32.spirv",
            "nuis.shader.vulkan.add-pair-u32.spv",
            "shader.vulkan.sub-u32.spirv",
            "nuis.shader.vulkan.sub-u32.spv",
            "shader.vulkan.mul-u32.spirv",
            "nuis.shader.vulkan.mul-u32.spv",
            "shader.vulkan.xor-u32.spirv",
            "nuis.shader.vulkan.xor-u32.spv",
            "spirv-binary",
            "vulkan.discrete-or-integrated-gpu",
            "nuis_vulkan_copy_u32",
            "nuis_vulkan_add_u32",
            "nuis_vulkan_add_pair_u32",
            "nuis_vulkan_sub_u32",
            "nuis_vulkan_mul_u32",
            "nuis_vulkan_xor_u32",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuisc-metal-msl-aot-materialization",
        path: "tools/nuisc/src/aot_domain_artifact_writer.rs",
        required_patterns: &[
            "materializes_registered_msl_from_canonical_wgsl_source",
            "shader.metal.copy-u32.msl",
            "nuis.shader.metal.copy-u32.metal",
            "shader.metal.add-u32.msl",
            "nuis.shader.metal.add-u32.metal",
            "shader.metal.add-pair-u32.msl",
            "nuis.shader.metal.add-pair-u32.metal",
            "shader.metal.sub-u32.msl",
            "nuis.shader.metal.sub-u32.metal",
            "shader.metal.mul-u32.msl",
            "nuis.shader.metal.mul-u32.metal",
            "shader.metal.xor-u32.msl",
            "nuis.shader.metal.xor-u32.metal",
            "nuis-module-lowering-plan",
            "msl:metal-gpu",
            "nuis_metal_copy_u32",
            "nuis_metal_add_u32",
            "nuis_metal_add_pair_u32",
            "nuis_metal_sub_u32",
            "nuis_metal_mul_u32",
            "nuis_metal_xor_u32",
            "metal-source",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-metal-generated-u32-canonical-runner",
        path: "tools/nsdb/src/provider_runner_metal_u32.rs",
        required_patterns: &[
            "nuis-metal-u32-copy-provider-runner-v1",
            "nuis-metal-u32-canonical-provider-runner-v1",
            "u32_compute_runner_contract",
            "execute_u32_canonical_input",
            "execute_u32_canonical_prepared_channel",
            "execute_u32_copy_input",
            "prepare_u32_canonical_worker_invocation",
            "prepare_u32_copy_worker_invocation",
            "copy-u32",
            "add-u32",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-metal-u32-linux-safe-reexports",
        path: "tools/nsdb/src/provider_runner_metal.rs",
        required_patterns: &[
            "#[cfg(test)]",
            "execute_u32_copy_input",
            "u32_compute_runner_contract",
            "#[cfg(target_os = \"macos\")]",
            "prepare_u32_canonical_worker_invocation",
            "prepare_u32_copy_worker_invocation",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-metal-generated-u32-copy-runner-tests",
        path: "tools/nsdb/src/provider_runner_metal_tests.rs",
        required_patterns: &[
            "executes_generated_u32_copy_msl_from_opaque_carrier_bytes",
            "executes_generated_u32_add_msl_from_opaque_carrier_bytes",
            "executes_f32_bias_from_opaque_carrier_bytes",
            "executes_f32_argmax_from_opaque_carrier_bytes",
            "shader.witsage.vector-bias.metal",
            "shader.witsage.argmax.metal",
            "shader.metal.copy-u32.msl",
            "shader.metal.add-u32.msl",
            "shader.metal.sub-u32.msl",
            "shader.metal.mul-u32.msl",
            "shader.metal.xor-u32.msl",
            "code_asset_registration_by_id",
            "registered_shader_source_path",
            "execute_u32_copy_input",
            "execute_u32_canonical_input",
            "nuis-metal-u32-copy-provider-runner-v1",
            "nuis-metal-u32-canonical-provider-runner-v1",
            "[1, 8, 13, 21]",
            "[2, 16, 26, 42]",
            "[0, 0, 0, 0]",
            "[1, 64, 169, 441]",
            "executes_generated_u32_xor_msl_from_opaque_carrier_bytes",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-metal-u32-canonical-execution-adapter",
        path: "tools/nsdb/src/provider_execution_metal.rs",
        required_patterns: &[
            "is_u32_compute",
            "is_u32_copy",
            "ends_with(\"-u32\")",
            "provider-tensor-u32",
            "u32_compute_runner_contract",
            "prepare_u32_canonical_worker_invocation",
            "prepare_u32_copy_worker_invocation",
            "execute_u32_canonical_input",
            "validate_metal_input_count",
            "metal_dense_u32_layout",
            "tensor-row-major",
            "input_binding_matches_buffer",
            "metal_u32_buffer_counts",
            "contiguous read-only u32 inputs",
            "contiguous writable u32 outputs",
            "metal_layout_accepts_contiguous_multiple_outputs",
            "msl2.4",
            "Metal request code asset descriptor is incompatible",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-metal-u32-copy-process-adapter-source",
        path: "tools/nsdb/provider-runners/metal_f32_bias.m",
        required_patterns: &[
            "copyU32",
            "u32Mode",
            "copy-u32",
            "*-u32",
            "nuis-metal-u32-copy-provider-runner-v1",
            "nuis-metal-u32-canonical-provider-runner-v1",
            "sizeof(uint32_t)",
            "inputCount",
            "setBuffer:inputBuffers[index]",
            "atIndex:inputCount",
            "NUIS_PROVIDER_OUTPUT_FDS",
            "outputDescriptors",
            "emitOutputs",
            "output_hashes=",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuisc-vulkan-spirv-external-validator-hook",
        path: "tools/nuisc/src/registry_code_asset.rs",
        required_patterns: &[
            "registered_vulkan_spirv_passes_external_validator_when_configured",
            "NUIS_SPIRV_VAL",
            "--target-env",
            "vulkan1.3",
            "rejected registered Vulkan SPIR-V",
        ],
    },
];
