use crate::dev_tensor_drift::DevTensorDriftCheckSpec;

pub(crate) const DEV_TENSOR_RUNTIME_DEV_LINEAGE_DRIFT_CHECKS: &[DevTensorDriftCheckSpec] = &[
    DevTensorDriftCheckSpec {
        id: "cli-fixture-scope-bound-output-cleanup",
        path: "tools/nuis/src/main_tests/test_dirs.rs",
        required_patterns: &[
            "impl Drop for TestDir",
            "default_build_output_dir(&root)",
            "default_release_check_output_dir(&root)",
            "temporary_project_and_derived_outputs_are_removed_on_drop",
            "temporary_fixture_cleanup_runs_during_unwind",
            "fixture_cleanup_keeps_other_live_fixtures",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "repository-cleanup-workspace-boundary",
        path: "scripts/disk-clean-safe.sh",
        required_patterns: &[
            "APPLY=0",
            "--build-binaries",
            "git -C \"$ROOT_DIR\" ls-files -- \"$relative\"",
            "refusing tracked cleanup path",
            "refusing symlinked cleanup path",
            "refusing non-ignored cleanup path",
            "check_candidate \"$path\"",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "repository-cleanup-safety-regressions",
        path: "scripts/tests/test_disk_cleanup.py",
        required_patterns: &[
            "test_default_is_read_only_and_resolves_workspace_from_script",
            "test_apply_preserves_source_project_state_and_external_resources",
            "test_workspace_removal_is_explicit",
            "test_tracked_candidate_vetoes_every_deletion",
            "test_non_ignored_candidate_is_not_assumed_disposable",
            "test_symlinked_candidate_and_parent_veto_every_deletion",
            "test_removed_global_options_fail_without_cleanup",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "repository-generated-output-source-guard",
        path: "scripts/tests/test_repository_hygiene.py",
        required_patterns: &[
            "test_source_checkout_does_not_ship_generated_outputs",
            "generated outputs belong in ignored local build directories",
            "examples/bins/README.md",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "repository-regeneratable-output-policy",
        path: "docs/repo-cleanup-candidates.md",
        required_patterns: &[
            "Keep source, intentional fixtures, package manifests/locks",
            "Do not remove tests just because their original bug is old",
            "target/example-builds/",
            "Tracked paths, non-ignored paths and paths through symlinks fail closed",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "ci-cold-checkout-workflow",
        path: ".github/workflows/build.yml",
        required_patterns: &[
            "python3 -m unittest discover -s scripts/tests -v",
            "cargo fetch --locked",
            "cargo build --workspace --locked",
            "persist-credentials: false",
            "CARGO_INCREMENTAL: \"0\"",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "ci-portability-focused-locked-test",
        path: "scripts/check-host-absolute-paths.sh",
        required_patterns: &[
            "cargo test --locked -p nuisc --test examples_mainline_compile",
            "checked_in_docs_do_not_embed_host_absolute_paths -- --exact --test-threads=1",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "ci-document-link-extractor-failure-boundary",
        path: "scripts/check-doc-links.sh",
        required_patterns: &[
            "targets=\"$(perl",
            "CHECKED=$((CHECKED + 1))",
            "done <<< \"$targets\"",
            "local links checked",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "ci-cold-source-guard-regressions",
        path: "scripts/tests/test_ci_checks.py",
        required_patterns: &[
            "test_missing_inline_link_fails_instead_of_silent_success",
            "test_extractor_failure_is_not_reported_as_success",
            "test_repository_links_do_not_depend_on_ignored_build_outputs",
            "test_workflow_fetches_locked_dependencies_before_cargo_validation",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "dev-tensor-task-card-recursive-lineage",
        path: "tools/nuis/src/dev_tensor_task_card_lineage.rs",
        required_patterns: &[
            "nuis-dev-tensor-task-card-lineage-v1",
            "validate_dev_tensor_task_card_lineage",
            "resolve_leaf_ancestry",
            "find_node_ancestry",
            "common_ancestor_index",
            "recursive_lineage_resolves_current_task_and_handoff_leaves",
            "direct_lineage_has_zero_transition_depth",
            "lineage_rejects_an_unreachable_handoff_leaf",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "dev-tensor-task-card-lineage-render",
        path: "tools/nuis/src/dev_tensor_task_card_lineage_render.rs",
        required_patterns: &[
            "weakest_bootstrap_task_card_lineage_protocol",
            "weakest_bootstrap_task_card_lineage_status",
            "weakest_bootstrap_task_card_lineage_errors",
            "weakest_bootstrap_task_card_task_ancestry",
            "weakest_bootstrap_task_card_handoff_ancestry",
            "weakest_bootstrap_task_card_common_ancestor_path",
            "weakest_bootstrap_task_card_transition_depth",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "dev-tensor-task-card-lineage-regression",
        path: "tools/nuis/src/dev_tensor_tests.rs",
        required_patterns: &[
            "nuis-dev-tensor-task-card-lineage-v1",
            "weakest_bootstrap_task_card_lineage_status",
            "weakest_bootstrap_task_card_task_ancestry",
            "weakest_bootstrap_task_card_handoff_ancestry",
            "weakest_bootstrap_task_card_transition_depth",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "dev-tensor-task-card-lineage-doc",
        path: "docs/reference/nuis-development-tensor.md",
        required_patterns: &[
            "nuis-dev-tensor-task-card-lineage-v1",
            "weakest_bootstrap_task_card_lineage_status",
            "weakest_bootstrap_task_card_task_ancestry",
            "weakest_bootstrap_task_card_handoff_ancestry",
            "weakest_bootstrap_task_card_common_ancestor_path",
            "weakest_bootstrap_task_card_transition_depth",
            "transition depth zero",
            "different reachable leaf",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "beta-0.15-mainline-router",
        path: "docs/current-mainline-map.md",
        required_patterns: &[
            "current `beta-0.15.*` priority",
            "nuis-beta-0.15.0-snapshot.md",
            "nuis-beta-0.15.0-release-checklist.md",
            "05951bef",
            "field demand through same-name branch-local capture aliases",
            "nuis-beta-0.11-application-led-mainline.md",
            "nuis-beta-0.10.0-self-hosting-entry.md",
            "nuis-beta-0.6.0-mainline-entry.md",
            "standard-library/ns-nova/persistent-application-session",
            "nuis-yir-application-cancellation-v1.md",
            "host-scope retirement",
            "nuis-development-tensor.md",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "beta-0.15-repository-frontdoor",
        path: "README.md",
        required_patterns: &[
            "repository is on `beta-0.15.*`",
            "ns-nova application-led development",
            "formal staged self-hosting migration line",
            "stage0-to-stage1-migration/active",
            "nuis-beta-0.15.0-snapshot.md",
            "nuis-beta-0.15.0-release-checklist.md",
            "05951bef",
            "nuis-native-scalar-value-returns-v1.md",
            "registered execution domains",
            "AppKit cancellation policy",
            "host embeds the YIR lifecycle runtime",
            "generated GNU resolver and symbol-version registry",
            "development tensor",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "beta-0.12-application-session-snapshot",
        path: "docs/versioning/nuis-beta-0.12.0-snapshot.md",
        required_patterns: &[
            "505c820c",
            "beta-0.12.2",
            "active/86",
            "ScopeAdmission",
            "Host cancellation is cooperative",
            "The packaged AppKit host has no explicit cancellation trigger",
            "native CPU frame dispatch",
            "nuis-beta-0.12.0-release-checklist.md",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "beta-0.12-validation-checklist",
        path: "docs/versioning/nuis-beta-0.12.0-release-checklist.md",
        required_patterns: &[
            "505c820c",
            "documentation-only",
            "do not prove physical device drain",
            "ns_nova_application_cancellation",
            "artifact_device_sample_shader_render",
            "std_tooling_observable_cli_smoke_checks_reports_and_stdin",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "beta-0.10-self-hosting-migration-entry",
        path: "docs/versioning/nuis-beta-0.10.0-self-hosting-entry.md",
        required_patterns: &[
            "c496bb67",
            "stage0-to-stage1-migration",
            "migration active: `true`",
            "final readiness: `false`",
            "closed gates: `1/5`",
            "candidate-owned native object or equivalent Nsld input",
            "Stage0 remains part of the",
        ],
    },
];
