use crate::dev_tensor_drift::DevTensorDriftCheckSpec;

pub(crate) const DEV_TENSOR_RUNTIME_VULKAN_DRIFT_CHECKS: &[DevTensorDriftCheckSpec] = &[
    DevTensorDriftCheckSpec {
        id: "nsdb-vulkan-host-probe",
        path: "tools/nsdb/src/provider_runner_vulkan.rs",
        required_patterns: &[
            "nuis-vulkan-host-probe-v1",
            "spirv.vulkan-gpu.bundle.v1",
            "spirv:vulkan-gpu",
            "libvulkan.so.1",
            "vkEnumerateInstanceVersion",
            "vkCreateInstance",
            "vkEnumeratePhysicalDevices",
            "vulkan-spirv-real-device-runner",
            "NUIS_REQUIRE_VULKAN_DEVICE_PROBE",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-vulkan-probe-only-execution-gate",
        path: "tools/nsdb/src/provider_execution_vulkan.rs",
        required_patterns: &[
            "vulkan-spirv-real-device-runner",
            "nuis-vulkan-spirv-execution-session-plan-v1",
            "validate_vulkan_execution_session_plan",
            "nuis-vulkan-spirv-provider-execution-v1",
            "parse_vulkan_worker_protocol",
            "vulkan_session_plan_accepts_registered_copy_u32_shape",
            "vulkan_session_plan_rejects_asset_or_binding_drift",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "shader-nustar-vulkan-provider-bundle",
        path: "nustar-packages/shader.toml",
        required_patterns: &[
            "spirv.vulkan-gpu.bundle.v1",
            "spirv:vulkan-gpu",
            "provider_runner_vulkan::PROVIDER_BUNDLE",
            "spirv.vulkan.real-device",
            "vulkan-spirv-real-device-runner",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-vulkan-spirv-process-adapter",
        path: "tools/nsdb/provider-runners/vulkan_spirv_dispatch.c",
        required_patterns: &[
            "nuis-vulkan-spirv-provider-runner-v1",
            "libvulkan.so.1",
            "vkCreateComputePipelines",
            "VK_DESCRIPTOR_TYPE_STORAGE_BUFFER",
            "vkCmdDispatch",
            "vkQueueSubmit",
            "NUIS_PROVIDER_OUTPUT_FD",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "shader-nustar-vulkan-spirv-source",
        path: "nustar-packages/assets/shader/vulkan_copy_u32.nspv",
        required_patterns: &[
            "nuis-spirv-compute-source-v1",
            "operation = \"copy-u32\"",
            "entry = \"nuis_vulkan_copy_u32\"",
            "input_binding = 0",
            "output_binding = 1",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuisc-shader-spirv-emitter",
        path: "tools/nuisc/src/shader_spirv_emitter.rs",
        required_patterns: &[
            "nuis-spirv-compute-source-v1",
            "lower_registered_compute_source",
            "parse_canonical_inline_wgsl_u32_compute",
            "emit_u32_module",
            "spirv_u32_binary_opcode",
            "CanonicalU32Operation::AddU32",
            "CanonicalU32Operation::SubU32",
            "CanonicalU32Operation::MulU32",
            "SPIRV_MAGIC",
            "SPIRV_VERSION_1_6",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuisc-shader-canonical-compute-contract",
        path: "tools/nuisc/src/shader_canonical_compute.rs",
        required_patterns: &[
            "CanonicalU32Compute",
            "parse_canonical_inline_wgsl_u32_compute",
            "parse_u32_operation",
            "U32_OPERATION_PATTERNS",
            "CanonicalU32Operation::AddU32",
            "CanonicalU32Operation::SubU32",
            "CanonicalU32Operation::MulU32",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuisc-shader-msl-emitter",
        path: "tools/nuisc/src/shader_msl_emitter.rs",
        required_patterns: &[
            "lower_canonical_inline_wgsl_u32_for_profile",
            "nuis-yir.shader.backend-lowering-plan.v1",
            "validate_msl_module_lowering_plan",
            "nuis-module-lowering-plan",
            "msl:metal-gpu",
            "argument-buffer-slot",
            "parse_canonical_inline_wgsl_u32_compute",
            "metal.apple-silicon-gpu",
            "metal.mac-discrete-or-integrated-gpu",
            "kernel void",
            "CanonicalU32Operation::AddU32",
            "CanonicalU32Operation::SubU32",
            "CanonicalU32Operation::MulU32",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuisc-shader-spirv-emitter-tests",
        path: "tools/nuisc/src/shader_spirv_emitter_tests.rs",
        required_patterns: &[
            "rejects_entry_or_binding_drift",
            "emits_binary_u32_modules_from_canonical_wgsl_body",
            "nuis_vulkan_add_u32",
            "nuis_vulkan_sub_u32",
            "nuis_vulkan_mul_u32",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuisc-shader-msl-emitter-tests",
        path: "tools/nuisc/src/shader_msl_emitter_tests.rs",
        required_patterns: &[
            "emits_msl_copy_module_from_canonical_wgsl_body",
            "emits_binary_u32_msl_from_shared_canonical_body_contract",
            "rejects_msl_module_lowering_plan_drift",
            "assert_msl_plan_proof",
            "nuis_metal_add_u32",
            "nuis_metal_sub_u32",
            "nuis_metal_mul_u32",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "shader-nustar-metal-canonical-source",
        path: "nustar-packages/assets/shader/metal_copy_u32.wgsl",
        required_patterns: &[
            "binding(0, 0)",
            "binding(0, 1)",
            "stage compute",
            "nuis_metal_copy_u32",
            "output_values[idx] = input_values[idx];",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "shader-nustar-metal-add-canonical-source",
        path: "nustar-packages/assets/shader/metal_add_u32.wgsl",
        required_patterns: &[
            "binding(0, 0)",
            "binding(0, 1)",
            "stage compute",
            "nuis_metal_add_u32",
            "output_values[idx] = input_values[idx] + input_values[idx];",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "shader-nustar-metal-sub-canonical-source",
        path: "nustar-packages/assets/shader/metal_sub_u32.wgsl",
        required_patterns: &[
            "binding(0, 0)",
            "binding(0, 1)",
            "stage compute",
            "nuis_metal_sub_u32",
            "output_values[idx] = input_values[idx] - input_values[idx];",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "shader-nustar-metal-mul-canonical-source",
        path: "nustar-packages/assets/shader/metal_mul_u32.wgsl",
        required_patterns: &[
            "binding(0, 0)",
            "binding(0, 1)",
            "stage compute",
            "nuis_metal_mul_u32",
            "output_values[idx] = input_values[idx] * input_values[idx];",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "shader-nustar-vulkan-code-asset-registration",
        path: "nustar-packages/shader.toml",
        required_patterns: &[
            "shader.vulkan.copy-u32.spirv",
            "spirv-binary",
            "vulkan.discrete-or-integrated-gpu",
            "vulkan1.3-spirv1.6",
            "assets/shader/vulkan_copy_u32.nspv",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "shader-nustar-metal-canonical-code-asset-registration",
        path: "nustar-packages/shader.toml",
        required_patterns: &[
            "shader.metal.copy-u32.msl",
            "metal-source",
            "metal.apple-silicon-gpu",
            "msl2.4",
            "nuis_metal_copy_u32",
            "assets/shader/metal_copy_u32.wgsl",
            "shader.metal.add-u32.msl",
            "nuis_metal_add_u32",
            "assets/shader/metal_add_u32.wgsl",
            "shader.metal.sub-u32.msl",
            "nuis_metal_sub_u32",
            "assets/shader/metal_sub_u32.wgsl",
            "shader.metal.mul-u32.msl",
            "nuis_metal_mul_u32",
            "assets/shader/metal_mul_u32.wgsl",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuisc-vulkan-spirv-aot-materialization",
        path: "tools/nuisc/src/aot_domain_artifact_writer.rs",
        required_patterns: &[
            "materializes_registered_vulkan_spirv_and_contribution_table",
            "shader.vulkan.copy-u32.spirv",
            "nuis.shader.vulkan.copy-u32.spv",
            "spirv-binary",
            "vulkan.discrete-or-integrated-gpu",
            "nuis_vulkan_copy_u32",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuisc-metal-msl-aot-materialization",
        path: "tools/nuisc/src/aot_domain_artifact_writer.rs",
        required_patterns: &[
            "materializes_registered_msl_from_canonical_wgsl_source",
            "shader.metal.copy-u32.msl",
            "nuis.shader.metal.copy-u32.metal",
            "shader.metal.add-u32.msl",
            "nuis.shader.metal.add-u32.metal",
            "shader.metal.sub-u32.msl",
            "nuis.shader.metal.sub-u32.metal",
            "shader.metal.mul-u32.msl",
            "nuis.shader.metal.mul-u32.metal",
            "nuis-module-lowering-plan",
            "msl:metal-gpu",
            "nuis_metal_copy_u32",
            "nuis_metal_add_u32",
            "nuis_metal_sub_u32",
            "nuis_metal_mul_u32",
            "metal-source",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-metal-generated-u32-canonical-runner",
        path: "tools/nsdb/src/provider_runner_metal_u32.rs",
        required_patterns: &[
            "nuis-metal-u32-copy-provider-runner-v1",
            "nuis-metal-u32-canonical-provider-runner-v1",
            "u32_compute_runner_contract",
            "execute_u32_canonical_input",
            "execute_u32_canonical_prepared_channel",
            "execute_u32_copy_input",
            "prepare_u32_canonical_worker_invocation",
            "prepare_u32_copy_worker_invocation",
            "copy-u32",
            "add-u32",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-metal-u32-linux-safe-reexports",
        path: "tools/nsdb/src/provider_runner_metal.rs",
        required_patterns: &[
            "#[cfg(test)]",
            "execute_u32_copy_input",
            "u32_compute_runner_contract",
            "#[cfg(target_os = \"macos\")]",
            "prepare_u32_canonical_worker_invocation",
            "prepare_u32_copy_worker_invocation",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-metal-generated-u32-copy-runner-tests",
        path: "tools/nsdb/src/provider_runner_metal_tests.rs",
        required_patterns: &[
            "executes_generated_u32_copy_msl_from_opaque_carrier_bytes",
            "executes_generated_u32_add_msl_from_opaque_carrier_bytes",
            "shader.metal.copy-u32.msl",
            "shader.metal.add-u32.msl",
            "shader.metal.sub-u32.msl",
            "shader.metal.mul-u32.msl",
            "code_asset_registration_by_id",
            "execute_u32_copy_input",
            "execute_u32_canonical_input",
            "nuis-metal-u32-copy-provider-runner-v1",
            "nuis-metal-u32-canonical-provider-runner-v1",
            "[1, 8, 13, 21]",
            "[2, 16, 26, 42]",
            "[0, 0, 0, 0]",
            "[1, 64, 169, 441]",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-metal-u32-canonical-execution-adapter",
        path: "tools/nsdb/src/provider_execution_metal.rs",
        required_patterns: &[
            "is_u32_compute",
            "is_u32_copy",
            "add-u32",
            "mul-u32",
            "provider-tensor-u32",
            "u32_compute_runner_contract",
            "prepare_u32_canonical_worker_invocation",
            "prepare_u32_copy_worker_invocation",
            "execute_u32_canonical_input",
            "msl2.4",
            "Metal request code asset descriptor is incompatible",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-metal-u32-copy-process-adapter-source",
        path: "tools/nsdb/provider-runners/metal_f32_bias.m",
        required_patterns: &[
            "copyU32",
            "u32Mode",
            "copy-u32",
            "*-u32",
            "nuis-metal-u32-copy-provider-runner-v1",
            "nuis-metal-u32-canonical-provider-runner-v1",
            "sizeof(uint32_t)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuisc-vulkan-spirv-external-validator-hook",
        path: "tools/nuisc/src/registry_code_asset.rs",
        required_patterns: &[
            "registered_vulkan_spirv_passes_external_validator_when_configured",
            "NUIS_SPIRV_VAL",
            "--target-env",
            "vulkan1.3",
            "rejected registered Vulkan SPIR-V",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-shader-vulkan-device-sample-registration",
        path: "tools/nuis/src/artifact_device_sample_shader_vulkan.rs",
        required_patterns: &[
            "DeviceSampleInputRegistration",
            "official.shader.vulkan-copy-u32",
            "provider_family: \"spirv:vulkan-gpu\"",
            "shader.vulkan.copy-u32.spirv",
            "code_asset_registration_by_id",
            "provider_code_asset_format=spirv-binary",
            "provider_adapter_binding_provider_family=spirv:vulkan-gpu",
            "select_compiled_code_asset_contribution",
            "render_selected_contribution_set_evidence",
            "validate_provider_request_evidence",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-shader-metal-device-sample-registration",
        path: "tools/nuis/src/artifact_device_sample_shader_metal.rs",
        required_patterns: &[
            "official.shader.metal-copy-u32",
            "official.shader.metal-add-u32",
            "official.shader.metal-sub-u32",
            "official.shader.metal-mul-u32",
            "official.shader:provider-sample=metal-copy-u32",
            "official.shader:provider-sample=metal-add-u32",
            "official.shader:provider-sample=metal-sub-u32",
            "official.shader:provider-sample=metal-mul-u32",
            "shader.metal.copy-u32.msl",
            "shader.metal.add-u32.msl",
            "shader.metal.sub-u32.msl",
            "shader.metal.mul-u32.msl",
            "code_asset_registration_by_id",
            "provider_kernel_operation={}",
            "provider_code_asset_target={}",
            "msl2.4",
            "provider_adapter_binding_provider_family=metal:apple-silicon-gpu",
            "select_compiled_code_asset_contribution",
            "render_selected_contribution_set_evidence",
            "nuis-module-lowering-plan",
            "validate_provider_request_evidence",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-device-sample-canonical-provider-family",
        path: "tools/nuis/src/artifact_device_sample_registration.rs",
        required_patterns: &[
            "provider_family",
            "registered_provider_family",
            "provider_sample_registration_id",
            "metadata_selector",
            "selected_registration",
            "evidence_matches_registration",
            "nuis.pixelmagic.gray8-filter",
            "official.shader.metal-copy-u32",
            "official.shader.metal-add-u32",
            "official.shader.metal-sub-u32",
            "official.shader.metal-mul-u32",
            "provider_sample_registration_package=official.shader",
            "vulkan",
            "discrete-or-integrated-gpu",
            "spirv:vulkan-gpu",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-code-asset-selection-set-single-base-case",
        path: "tools/nsdb/src/provider_code_asset_selection_payload.rs",
        required_patterns: &[
            "SINGLE_CONTRACT | SET_CONTRACT",
            "single_item_selection_set_round_trips_as_base_case",
            "compiled_code_asset_selection_count",
            "nuis-provider-code-asset-contribution-selection-set-v1",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-shader-vulkan-provider-demo",
        path: "examples/projects/domains/shader_vulkan_provider_demo/nuis.toml",
        required_patterns: &[
            "shader_vulkan_provider_demo",
            "cpu=cpu.x86_64.sysv64",
            "shader=shader.vulkan.spv1_6",
            "nuis-self-contained-image",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "official-shader-metal-provider-demo",
        path: "examples/projects/domains/shader_metal_provider_demo/nuis.toml",
        required_patterns: &[
            "shader_metal_provider_demo",
            "official.shader:provider-sample=metal-copy-u32",
            "shader=shader.metal.msl2_4",
            "nuis-self-contained-image",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "official-shader-metal-add-provider-demo",
        path: "examples/projects/domains/shader_metal_add_provider_demo/nuis.toml",
        required_patterns: &[
            "shader_metal_add_provider_demo",
            "official.shader:provider-sample=metal-add-u32",
            "shader=shader.metal.msl2_4",
            "nuis-self-contained-image",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "official-shader-metal-sub-provider-demo",
        path: "examples/projects/domains/shader_metal_sub_provider_demo/nuis.toml",
        required_patterns: &[
            "shader_metal_sub_provider_demo",
            "official.shader:provider-sample=metal-sub-u32",
            "shader=shader.metal.msl2_4",
            "nuis-self-contained-image",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "official-shader-metal-mul-provider-demo",
        path: "examples/projects/domains/shader_metal_mul_provider_demo/nuis.toml",
        required_patterns: &[
            "shader_metal_mul_provider_demo",
            "official.shader:provider-sample=metal-mul-u32",
            "shader=shader.metal.msl2_4",
            "nuis-self-contained-image",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "official-shader-metal-provider-smoke",
        path: "tools/nuis/tests/official_galaxy_hetero_smoke/shader_metal.rs",
        required_patterns: &[
            "shader_metal_generated_msl_sample_executes_provider_output",
            "shader_metal_generated_add_msl_sample_executes_provider_output",
            "shader_metal_generated_sub_msl_sample_executes_provider_output",
            "shader_metal_generated_mul_msl_sample_executes_provider_output",
            "shader_metal_provider_demo",
            "shader_metal_add_provider_demo",
            "shader_metal_sub_provider_demo",
            "shader_metal_mul_provider_demo",
            "official.shader.metal-copy-u32",
            "provider_sample_registration_id={}",
            "official.shader.metal-add-u32",
            "official.shader.metal-sub-u32",
            "official.shader.metal-mul-u32",
            "provider_code_asset_target=msl2.4",
            "nuis-metal-u32-copy-provider-runner-v1",
            "nuis-metal-u32-canonical-provider-runner-v1",
            "0x88201fb960ff6465",
            "0x02f6f7f591bff68f",
            "provider-tensor-u32",
            "compiled_code_asset_selection_status",
            "assemble_provider_complete_final_image",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "linux-vulkan-provider-sample-smoke",
        path: "tools/nuis/tests/official_galaxy_hetero_smoke/linux_vulkan.rs",
        required_patterns: &[
            "linux_vulkan_shader_sample_executes_provider_output",
            "execute-provider-samples",
            "materialize-provider-samples",
            "assemble_provider_complete_final_image",
            "nsld_final_executable_output_object_package_provider_dispatch_identity_status",
            "nsld_final_executable_output_debugger_api_provider_dispatch_identity_status",
            "spirv.vulkan-gpu.bundle.v1",
            "nuis-vulkan-spirv-provider-execution-v1",
            "0x6ebcdd244b594ee4",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-vulkan-final-image-dispatch-smoke",
        path: "tools/nsld/src/main_container_metadata_binding_tests.rs",
        required_patterns: &[
            "final_image_loader_verifies_vulkan_provider_dispatch_without_backend_branch",
            "spirv:vulkan-gpu",
            "spirv.vulkan-gpu.bundle.v1",
            "spirv.vulkan.real-device",
            "spirv.vulkan.fake-device",
            "fnv1a64:f8efa211643f7bcd",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-vulkan-completion-dispatch-authority",
        path: "tools/nsdb/src/provider_completion_dispatch.rs",
        required_patterns: &[
            "vulkan_completion_authority_is_bound_from_open_final_image_dispatch",
            "vulkan_completion_authority_rejects_runner_identity_drift",
            "spirv:vulkan-gpu",
            "spirv.vulkan-gpu.bundle.v1",
            "provider-completion-dispatch:runner-drift",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-code-asset-selection-set-base-case",
        path: "tools/nsld/src/final_executable_output_code_asset.rs",
        required_patterns: &[
            "nuis-provider-code-asset-contribution-selection-set-v1",
            "selected_count == 1",
            "validates_verified_or_not_applicable_selection",
        ],
    },
];
