use crate::dev_tensor_drift::DevTensorDriftCheckSpec;

pub(crate) const DEV_TENSOR_RUNTIME_PROVIDER_COMPLETION_DRIFT_CHECKS: &[DevTensorDriftCheckSpec] =
    &[
        DevTensorDriftCheckSpec {
            id: "nuis-provider-completion-closure-mirror",
            path: "tools/nuis/src/closure_summary_provider_completion.rs",
            required_patterns: &[
                "ProviderCompletionClosureMirror",
                "ProviderCompletionRecordClosureMirror",
                "from_final_output",
                "nsdb_provider_completions",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nuis-provider-completion-closure-json",
            path: "tools/nuis/src/closure_summary_provider_completion.rs",
            required_patterns: &[
                "provider_completion_json_fields",
                "closure_summary_provider_completion_count",
                "closure_summary_first_provider_family",
                "closure_summary_first_provider_output_contract",
                "closure_summary_first_provider_output_evidence",
                "closure_summary_provider_completion_claim_authority_contract",
                "closure_summary_provider_completion_claim_authority",
                "closure_summary_provider_completion_claim_authority_status",
                "closure_summary_provider_completion_digest_contract",
                "closure_summary_provider_completion_set_hash_claim",
                "closure_summary_provider_completion_set_hash",
                "closure_summary_provider_completion_set_hash_validation_status",
                "closure_summary_provider_completions",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nuis-provider-completion-workflow-projection",
            path: "tools/nuis/src/workflow/link_plan_json.rs",
            required_patterns: &["append_projection_json_fields"],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-provider-request-completion-receipts",
            path: "tools/nsdb/src/provider_request_completion.rs",
            required_patterns: &[
                "nuis-provider-request-completion-receipt-collection-v1",
                "bind_final_image_dispatch",
                "request_completion_root_hash",
                "request-completion-dispatch:entry-missing",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nuis-independent-request-completion-audit",
            path: "tools/nuis/src/artifact_nsdb_handoff_request_completion.rs",
            required_patterns: &[
                "parse_and_append",
                "receipt_root_hash",
                "receipts_verified",
                "legacy-unavailable",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-provider-request-replay-selector",
            path: "tools/nsdb/src/request_replay_selector.rs",
            required_patterns: &[
                "nsdb-provider-request-replay-selector-v1",
                "resolve_request_replay_selection",
                "request_frame_id",
                "request-ambiguous",
                "dispatch-authority-unverified",
                "completion_clock",
                "completion_token",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-provider-request-replay-frames",
            path: "tools/nsdb/src/request_replay_frames.rs",
            required_patterns: &[
                "nsdb-provider-request-replay-frame-v1",
                "verified_request_replay_frames",
                "expand_request_replay_frames",
                "apply_request_replay_control",
                "request_frame_id",
                "sha256_hex",
                "resume-next-request-frame",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-provider-request-replay-json",
            path: "tools/nsdb/src/json_transcript.rs",
            required_patterns: &[
                "debugger_transcript_request_selector_status",
                "debugger_transcript_request_frame_id",
                "debugger_transcript_request_provider_family",
                "debugger_transcript_request_dispatch_id",
                "debugger_transcript_request_completion_clock",
                "debugger_transcript_request_output_hash",
                "debugger_transcript_request_completion_token",
                "debugger_transcript_request_frame_count",
                "debugger_transcript_replayed_frame_count",
                "request_parent_frame_id",
                "request_ordinal",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nuis-debug-request-frontdoor",
            path: "tools/nuis/src/debug_request_command.rs",
            required_patterns: &[
                "handle_debug_request",
                "resolve_artifact_output_input",
                "resolve_nsdb_program",
                "--request-id",
                "--save-cursor",
                "resolve_debugger_cursor_output",
                "persist_debugger_cursor_selection",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nuis-debugger-cursor-selection",
            path: "tools/nuis/src/artifact_nsdb_replay_cursor.rs",
            required_patterns: &[
                "nuis-debugger-cursor-selection-v1",
                "resolve_debugger_cursor_output",
                "persist_debugger_cursor_selection",
                "persist_selection_atomically",
                "cursor-selection-invalid",
                "cursor-selection-unreadable",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "provider-request-completion-real-mixed-smoke",
            path: "tools/nuis/tests/official_galaxy_hetero_smoke/linux_vulkan.rs",
            required_patterns: &[
                "request_completion_count",
                "request_completion_{index}_request_id",
                "request_completion_{index}_provider_family",
                "request_completion_{index}_dispatch_id",
                "request_completion_{index}_selected_set_hash",
                "nsld_final_executable_output_object_package_provider_request_completion_receipt_count",
                "closure_summary_debugger_api_provider_request_completion_receipt_count",
                "nsdb-provider-request-replay-selector-v1",
                "debugger_transcript_request_selector_status",
                "debugger_transcript_request_provider_family",
                "debugger_transcript_request_frame_count",
                "debugger_transcript_control_status",
                "--save-cursor",
                "Nuis request cursor final Vulkan successor",
                "Nuis selected request cursor projection",
                "Nuis request-frame cursor resume",
                "debugger_transcript_replayed_frame_count",
                "request-replay-selector:request-not-found:missing.request",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsld-provider-request-completion-final-output",
            path: "tools/nsld/src/json_final_output_provider_completion.rs",
            required_patterns: &[
                "request_completion_contract",
                "request_completion_root_hash",
                "request_completions",
                "selected_set_hash",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nuis-validated-provider-request-completion-capability",
            path: "tools/nuis/src/workflow/link_plan_provider_request_completion.rs",
            required_patterns: &[
                "nuis-validated-provider-request-completion-capability-v1",
                "selected-set-mismatch",
                "dispatch_selected_set_hash",
                "verified-empty",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nuis-provider-request-completion-frontdoor-projection",
            path: "tools/nuis/src/workflow/link_plan_provider_request_completion_json.rs",
            required_patterns: &[
                "provider_request_completion_receipt_count",
                "provider_request_completion_collections",
                "request_completion_collection_json",
                "source_trace_id",
                "dispatch_selected_set_hash",
                "completion_token",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nuis-provider-request-completion-closure-projection",
            path: "tools/nuis/src/closure_summary_provider_completion.rs",
            required_patterns: &[
                "dispatch_selected_set_hash",
                "request_completion",
                "request_completion_collection_json",
            ],
        },
    ];
