use crate::dev_tensor_drift::DevTensorDriftCheckSpec;

pub(super) const CHECKS: &[DevTensorDriftCheckSpec] = &[
    DevTensorDriftCheckSpec {
        id: "native-computed-return-arms-shared-whole-root-budget-and-separate-generic-mode",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_values_prefix.rs",
        required_patterns: &[
            "computed_expression_roots(pending)",
            "roots(pending, true)",
            "roots(pending, false)",
            "Return trees share one budget across all roots, including duplicated suffixes",
            "let mut work = 4096usize",
            "if depth >= 64 || work == 0",
            "!logical_root",
            "depth != 0",
            "(lhs.as_ref(), depth + 1, false)",
            "(rhs.as_ref(), depth + 1, false)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-computed-return-arms-complete-partial-original-type-and-scalar-capture-proof",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_terminal.rs",
        required_patterns: &[
            "if !bounded_tree(body, true)",
            "let mut statements = 32usize",
            "computed_expression_roots(expressions)",
            "if inner.contains_key(name)",
            "declared.is_some_and(|declared| declared != &ty)",
            "control_values::value_type(condition, &inner, catalog, layouts)",
            ".is_some_and(|ty| return_values::capture(result, ty))",
            "Non-total partial predicates use stored signals",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-computed-return-arms-expanded-suffix-budget-before-materialization",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_suffix.rs",
        required_patterns: &[
            "if !preflight(body)",
            "validate(body, scope.clone(), result, catalog, layouts)?",
            "let plan = plan(body.iter().collect(), &mut statements)?",
            "computed_expression_roots(expressions).then(|| materialize(plan))",
            "intermediate && conditional_values::prefix::computed_expression_roots(expressions)",
            "*statements = statements.checked_sub(1)?",
            "Do not append any inherited suffix to an observed return",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-computed-return-arms-return-root-preflight-and-independent-exit-authority",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns.rs",
        required_patterns: &[
            "fn expression(value: &NirExpr, _scope: &Scope)",
            "conditional_values::prefix::computed_logical_root(value)",
            "control_values::value_type(value, scope, catalog, layouts)",
            "signal::prepare(body, result, scope, catalog, layouts)?",
            "if !has_return",
            ".is_some_and(|ty| return_values::capture(result, ty))",
            "Do not lift work out of loops or an enclosing source branch",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-computed-return-arms-reference-order-signals-records-budget-and-veto-evidence",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_computed_arm_tests.rs",
        required_patterns: &[
            "assert_eq!(cases, 864)",
            "assert_eq!(cases, 192)",
            "assert_eq!(cases, 48)",
            "assert_eq!(cases, 16)",
            "conditional_return_computed_arms_preserve_original_tree_private_signals_scalar_captures_and_idempotence",
            "conditional_return_computed_arms_bound_whole_original_expanded_roots_before_cloning",
            "4091 argument nodes + call + logical root + RHS atom + two returns = 4096",
            "for count in [61, 62]",
            "for count in [29, 30]",
            "assert!(!conditional_values::prefix::expression_roots",
            "conditional_return_computed_arms_retain_nested_effect_type_scope_loop_and_capture_vetoes",
            "prefix_checked = 10 / left",
            "[\"exited\", \"value\"]",
            "assert_eq!(module, once)",
            "assert_eq!(module, before)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-computed-return-arms-default-source-binaries-left-traps-and-zero-exits",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_computed_arm_native_tests.rs",
        required_patterns: &[
            "use super::super::super::tests::native::run",
            "conditional_return_computed_arms_execute_default_aot_roots_left_checks_and_short_circuit_rhs",
            "conditional_return_computed_arms_execute_default_aot_signals_suffixes_prefix_records_and_zero_exits",
            "Some(\"99\\n77\\n19\")",
            "Some(\"99\\n0\")",
            "run(&text, expected)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-computed-return-arms-documented-whole-arm-proof-and-boundaries",
        path: "docs/reference/nuis-native-computed-logical-gates-v1.md",
        required_patterns: &[
            "## Computed Return-Arm Gates",
            "one shared 4096-node",
            "original tree",
            "32-statement bound",
            "Nine new compiler tests cover 1120 runtime source cases and 2240 ordinary/reversed",
            "fresh name",
            "nineteen binary variants",
            "The return-arm checkpoint recorded `active/93`",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-computed-return-arms-current-tensor-evidence-and-residual-boundaries",
        path: "tools/nuis/src/dev_tensor_data.rs",
        required_patterns: &[
            "Computed return-arm follow-up:",
            "Computed return-arm acceptance:",
            "Previous computed-gate checkpoint:",
            "1120 runtime source cases and 2240 ordinary/reversed reference executions",
            "conditional_return_computed_arms",
            "active/93",
            "nested logical operands",
        ],
    },
];
