use crate::dev_tensor_drift::DevTensorDriftCheckSpec;

pub(crate) const DEV_TENSOR_RUNTIME_CUDA_DRIFT_CHECKS: &[DevTensorDriftCheckSpec] = &[
    DevTensorDriftCheckSpec {
        id: "yir-backend-neutral-function-table",
        path: "crates/yir-core/src/module_graph.rs",
        required_patterns: &[
            "nuis-yir-function-table-v1",
            "pub functions: Vec<YirFunction>",
            "pub enum YirFunctionRole",
            "pub enum YirValueOwnership",
            "pub struct YirFunctionParameter",
            "pub struct YirFunctionResult",
            "pub struct YirFunction",
            "pub body_nodes: Vec<String>",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "yir-function-table-syntax",
        path: "crates/yir-syntax/src/lib.rs",
        required_patterns: &[
            "function-param",
            "function-result",
            "function-node",
            "parse_function_parameter",
            "parse_function_result",
            "parse_function_node",
            "parses_typed_function_boundaries_and_body_membership",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "yir-function-table-verification",
        path: "crates/yir-verify/src/function_contracts.rs",
        required_patterns: &[
            "verify_function_table",
            "invalid or duplicate function boundary",
            "references unknown body node",
            "belongs to both",
            "has invalid parameter",
            "has an invalid result boundary",
            "expected at most one",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuisc-yir-function-membership-lowering",
        path: "tools/nuisc/src/lowering/bootstrap.rs",
        required_patterns: &[
            "main_start_index",
            "main_body_nodes",
            "main_returns_unit",
            "is_unit_scalar",
            "YirFunctionRole::Entry",
            "YirFunctionResult",
            "structured_return",
            "entry function",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuisc-unit-return-type-canonicalization",
        path: "tools/nuisc/src/frontend/return_inference.rs",
        required_patterns: &[
            "AstStmt::Return(None)",
            "returns.push(ast_named_type(\"Unit\"))",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuisc-kernel-code-asset-registry",
        path: "tools/nuisc/src/kernel_code_asset.rs",
        required_patterns: &[
            "nuis-kernel-code-asset-registry-v1",
            "cuda.nvidia-gpu",
            "nuis.domain.kernel.cuda.ptx",
            "nuis_kernel_vector_add_f32",
            "nuis_kernel_scale_f32",
            "visible_entries",
            "registered_kernel_code_assets",
            "lower_cuda_ptx",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuisc-kernel-yir-codegen-table",
        path: "tools/nuisc/src/kernel_codegen_table.rs",
        required_patterns: &[
            "nuis-kernel-yir-codegen-table-v1",
            "nuis-kernel-yir-codegen-function-v1",
            "nuis-kernel-project-code-asset-identity-v1",
            "nuis-provider-code-asset-identity-set-v1",
            "compiled-project-yir",
            "source_fnv1a64",
            "source_kernel_node_count",
            "source_kernel_body_node_count",
            "source_adaptation_contract",
            "source_adaptations",
            "request_projection_contract",
            "request_operation",
            "request_input_shape",
            "request_output_shape",
            "request_input_source_node",
            "request_input_values",
            "request_expected_values",
            "result_projection_contract",
            "result_input_source_node",
            "result_expected_i64",
            "codegen functions do not match source request projections",
            "project_code_asset_identity_hash",
            "project_code_asset_identity_set_root_hash",
            "code_asset_identity_set_root_hash",
            "project_code_asset_entries",
            "project_code_asset_identity_hash(",
            "source_functions",
            "YirFunction",
            "yir_syntax::parse_module",
            "yir_verify::verify_module",
            "kernel.add_f32",
            "kernel.mul_f32",
            "render_codegen_table",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuisc-kernel-yir-source-adapter",
        path: "tools/nuisc/src/kernel_source_adapter.rs",
        required_patterns: &[
            "nuis-kernel-yir-source-adapter-v1",
            "nuis-kernel-source-request-projection-v1",
            "nuis-kernel-source-result-projection-v1",
            "adapt_project_kernel_functions",
            "add_scalar_axis",
            "reduce_sum_axis",
            "InputI64",
            "OutputI64",
            "ScalarI64",
            "add_i64",
            "reduce_sum_i64",
            "KernelSourceAdaptationStatus::Adapted",
            "KernelSourceAdaptationStatus::Projected",
            "KernelSourceAdaptationStatus::Unsupported",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-kernel-project-request-projection",
        path: "tools/nuis/src/artifact_device_sample_kernel_project.rs",
        required_patterns: &[
            "nuis-kernel-source-request-projection-v1",
            "nuis-provider-result-projection-collection-v1",
            "nuis-provider-result-projection-v1",
            "augment_evidence",
            "persist_payloads",
            "uses_project_request_collection",
            "replace_compatibility_collection",
            "compatibility_suffixes",
            "load_project_code_asset_identity",
            "project_code_asset_identity_hash",
            "render_project_code_asset_identity",
            "provider_code_asset_identity_entries",
            "provider_code_asset_identity_set_contract",
            "provider_code_asset_identity_set_count",
            "provider_code_asset_identity_set_root_hash",
            "kernel.cuda.project.",
            "add-scalar-i64",
            "buffer_element_type=i64",
            "scalar:i64",
            "input_binding_0_source=artifact",
            "input_binding_0_source=dependency",
            "dependency_0_transport_contract=nuis-provider-edge-transport-v1",
            "checked_add",
            "try_fold",
            "encode_i64_values",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-nustar-code-asset-identity-assembly",
        path: "tools/nuis/src/artifact_code_asset_identity.rs",
        required_patterns: &[
            "nuis-nustar-code-asset-identity-contribution-v1",
            "NustarCodeAssetContribution",
            "assemble_nustar_code_asset_identity",
            "provider_bundle_registrations",
            "owner_package_id",
            "provider_family",
            "request_index",
            "nuis-provider-code-asset-descriptor-identity-v1",
            "nuis-provider-code-asset-identity-set-v1",
            "identity_set_root_hash",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuisc-domain-code-asset-contribution-table",
        path: "tools/nuisc/src/aot_code_asset_contribution.rs",
        required_patterns: &[
            "nuis-domain-code-asset-contribution-table-v1",
            "nuis-nustar-code-asset-identity-contribution-v1",
            "DomainCodeAssetContribution",
            "shader_sidecar_contribution",
            "kernel_asset_contribution",
            "render_code_asset_contribution_table",
            "compiled_project_code_asset_id",
            "lowering_target",
            "nuis-provider-code-asset-descriptor-identity-v1",
            "nuis-provider-code-asset-identity-set-v1",
            "identity_set_root_hash",
            "contribution_table_hash",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuisc-domain-code-asset-contribution-materialization",
        path: "tools/nuisc/src/aot_domain_artifact_writer.rs",
        required_patterns: &[
            "code_asset_contributions",
            "shader_sidecar_contribution",
            "kernel_asset_contribution",
            "nuis.domain.code-asset-contributions.toml",
            "domain_code_asset_contribution_table",
            "writes_one_table_for_independently_owned_shader_and_kernel_assets",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiled-code-asset-contribution-verifier",
        path: "tools/nuis/src/artifact_code_asset_contribution_table.rs",
        required_patterns: &[
            "nuis.domain.code-asset-contributions.toml",
            "verify_compiled_code_asset_contribution_table",
            "render_verified_table_evidence",
            "select_compiled_code_asset_contribution",
            "render_selected_contribution_evidence",
            "nuis-provider-code-asset-contribution-selection-v1",
            "compiled_code_asset_contribution_table_status=verified",
            "validate_rows",
            "descriptor_identity_hash",
            "identity_set_root_hash",
            "contribution_table_hash",
            "independently_verifies_table_and_asset_bytes",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-device-sample-compiled-code-asset-evidence",
        path: "tools/nuis/src/artifact_device_sample.rs",
        required_patterns: &[
            "verify_compiled_code_asset_contribution_table",
            "render_verified_table_evidence",
            "input_evidence.push_str(&code_asset_table_evidence)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-cuda-compiled-contribution-selection",
        path: "tools/nuis/src/artifact_device_sample_kernel.rs",
        required_patterns: &[
            "select_compiled_code_asset_contribution",
            "validate_cuda_contribution_selection",
            "render_selected_contribution_evidence",
            "cuda.nvidia-gpu",
            "official.kernel",
            "code_asset_entries",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-compiled-contribution-selection-verifier",
        path: "tools/nsdb/src/provider_code_asset_contribution.rs",
        required_patterns: &[
            "nuis-provider-code-asset-contribution-selection-v1",
            "validate_compiled_contribution_selection",
            "validate_table",
            "validate_requests",
            "descriptor_identity_hash",
            "identity_set_root_hash",
            "contribution_table_hash",
            "independently_blocks_selection_or_asset_drift_before_launch",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-compiled-contribution-prelaunch-gate",
        path: "tools/nsdb/src/provider_sample_execute.rs",
        required_patterns: &[
            "validate_compiled_contribution_selection",
            "provider_request_collection_from_evidence",
            "let mut worker_leases",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-witsage-count-two-code-assets",
        path: "tools/nuis/src/artifact_device_sample_witsage.rs",
        required_patterns: &[
            "nuis.witsage.vector-bias.metal",
            "nuis.witsage.argmax.metal",
            "nuis_witsage_vector_bias_f32",
            "nuis_witsage_argmax_f32",
            "witsage_code_asset_identity",
            "provider_code_asset_identity_set_count=2",
            "official.shader",
            "metal:apple-silicon-gpu",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-project-code-asset-identity",
        path: "tools/nsdb/src/provider_code_asset_identity.rs",
        required_patterns: &[
            "nuis-kernel-project-code-asset-identity-v1",
            "nuis-provider-code-asset-descriptor-identity-v1",
            "verified_code_asset_identity_collection",
            "IDENTITY_VALIDATORS",
            "IdentityValidatorRegistration",
            "ProviderCodeAssetIdentity",
            "ProviderCodeAssetIdentitySet",
            "append_provider_output_identity",
            "provider_code_asset_identity_status",
            "provider_code_asset_identity_set_status",
            "validate_project_identity_item",
            "validate_descriptor_identity_item",
            "ordered_request_asset_ids",
            "code_asset_identity_set_root_hash",
            "project_asset_id_matches_hash",
            "project_code_asset_identity_hash",
            "descriptor_code_asset_identity_hash",
            "source_fnv1a64",
            "lowering_target",
            "entries.join",
            "asset.content_hash == first.content_hash",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-provider-result-projection",
        path: "tools/nsdb/src/provider_result_projection.rs",
        required_patterns: &[
            "nuis-provider-result-projection-collection-v1",
            "nuis-provider-result-projection-v1",
            "validate_and_render_result_projections",
            "comparison-passed",
            "worker-output-verified",
            "provider-completion:0x",
            "glm-release:0x",
            "released-at-graph-close",
            "provider_result_projection_status",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuisc-kernel-cuda-ptx-emitter",
        path: "tools/nuisc/src/kernel_ptx_emitter.rs",
        required_patterns: &[
            "nuis-kernel-ptx-emitter-registry-v1",
            "KernelYirCodegenTable",
            "validate_codegen_table",
            "lower_cuda_ptx",
            "add_f32",
            "mul_f32",
            "add_i64",
            "reduce_sum_i64",
            "add.rn.f32",
            "mul.rn.f32",
            "add.s64",
            "st.global.s64",
            "REDUCE_LOOP_",
            "emit_ptx_module",
            "emitter_rejects_unregistered_kernel_yir_instruction",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-kernel-cuda-provider-request",
        path: "tools/nuis/src/artifact_device_sample_kernel.rs",
        required_patterns: &[
            "provider_kernel_input_buffers=input.left,input.right",
            "code_asset_descriptor_contract=nuis-provider-code-asset-descriptor-v1",
            "provider_input_binding_count=2",
            "provider_request_count=2",
            "provider_request_1_input_binding_0_source=dependency",
            "provider_output_binding_0_role=output.result",
            "provider_adapter_binding_provider_family=cuda:nvidia-gpu",
            "resolve_cuda_code_asset_evidence",
            "validate_cuda_code_asset",
            "validate_cuda_request_asset_evidence",
            "registration_binds_provider_evidence_to_project_derived_ptx",
            "validate_provider_request_evidence",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuisc-kernel-code-asset-materialization",
        path: "tools/nuisc/src/aot_domain_artifact_writer.rs",
        required_patterns: &[
            "write_registered_domain_code_asset",
            "domain_code_asset_",
            "materializes_registered_cuda_ptx_without_external_compiler",
            "write_domain_build_unit_stubs_with_kernel_codegen_table",
            "nuis.domain.kernel.codegen-table.toml",
            "project_yir_table_materializes_hashed_sidecar_and_ptx",
            "lower_cuda_ptx(table)",
            "project_code_asset_identity_contract",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-cuda-device-selection-registry",
        path: "tools/nsdb/src/provider_runner_cuda.rs",
        required_patterns: &[
            "nuis-cuda-device-selection-registry-v1",
            "nuis-cuda-device-selection-v1",
            "nuis-cuda-device-inventory-v1",
            "capability-ranked-lowest-ordinal",
            "cuda-driver-device-compute-capability",
            "validates_device_selection",
            "select_cuda_device",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-cuda-persistent-worker-driver-runner",
        path: "tools/nsdb/src/provider_execution_cuda.rs",
        required_patterns: &[
            "prepare_cuda_worker_invocation",
            "validate_provider_code_asset",
            "add-scalar-i64",
            "reduce-sum-i64",
            "scalar_i64",
            "std::mem::size_of::<i64>()",
            "worker_descriptor_argument",
            "nuis-cuda-ptx-driver-provider-execution-v1",
            "cuda-driver-kernel-completed",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-cuda-driver-abi-adapter",
        path: "tools/nsdb/provider-runners/cuda_ptx_dispatch.c",
        required_patterns: &[
            "libcuda.so.1",
            "cuModuleLoad",
            "cuLaunchKernel",
            "cuDeviceGetCount",
            "cuDeviceComputeCapability",
            "device_inventory_contract=nuis-cuda-device-inventory-v1",
            "device_selection_policy=capability-ranked-lowest-ordinal",
            "device_selection_status=verified",
            "NUISPFD1",
            "read_carrier_frame",
            "NUIS_PROVIDER_OUTPUT_FD",
            "add-scalar-i64",
            "reduce-sum-i64",
            "sizeof(int64_t)",
            "add_scalar_i64_parameters",
            "reduce_sum_i64_parameters",
            "nuis-cuda-ptx-driver-provider-runner-v1",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-provider-request-collection-fail-closed",
        path: "tools/nsdb/src/provider_request_tests.rs",
        required_patterns: &[
            "declared_collection_never_falls_back_to_singular_request",
            "provider_request_collection_contract",
            "provider_request_count=2",
            "provider_request_collection_from_evidence",
            "validates_ordered_mixed_asset_identity_partitions",
            "mixed_asset_collection",
            "DESCRIPTOR_CODE_ASSET_IDENTITY_CONTRACT",
            "is_none",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-cuda-real-device-worker-closure-test",
        path: "tools/nsdb/src/provider_sample_execute_tests.rs",
        required_patterns: &[
            "executes_registered_cuda_ptx_through_persistent_worker",
            "cuda:nvidia-gpu",
            "nuis-provider-worker-process-adapter-v5",
            "comparison-passed",
            "graph_output_release_count",
            "nuis-provider-completion-evidence-v1",
            "nuis-provider-glm-release-evidence-v1",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-provider-completion-release-evidence",
        path: "tools/nsdb/src/provider_graph_output.rs",
        required_patterns: &[
            "nuis-provider-completion-clock-v1",
            "session and worker clocks diverged",
            "nuis-provider-glm-release-evidence-v1",
            "release set does not match GLM output handles",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-provider-completion-evidence-handoff",
        path: "tools/nsdb/src/provider_completion_evidence.rs",
        required_patterns: &[
            "nuis-provider-completion-evidence-collection-v1",
            "native-output collection hash mismatch",
            "completion token mismatch",
            "GLM release token mismatch",
            "append_hash_material",
            "code_asset_identity_contract",
            "code_asset_identity_status",
            "code_asset_identity_asset_id",
            "code_asset_identity_hash",
            "code_asset_identity_set_contract",
            "code_asset_identity_set_status",
            "code_asset_identity_set_count",
            "code_asset_identity_set_root_hash",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-provider-completion-evidence-replay",
        path: "tools/nsld/src/final_executable_output_nsdb_handoff.rs",
        required_patterns: &[
            "completion_evidence_contract",
            "completion_clock_evidence",
            "completion_tokens",
            "glm_release_contract",
            "glm_release_tokens",
            "glm_release_status",
            "code_asset_identity_contract",
            "code_asset_identity_status",
            "code_asset_identity_asset_id",
            "code_asset_identity_hash",
            "code_asset_identity_set_contract",
            "code_asset_identity_set_status",
            "code_asset_identity_set_count",
            "code_asset_identity_set_root_hash",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "official-sealed-image-provider-completion-evidence",
        path: "tools/nuis/tests/official_galaxy_hetero_smoke/final_image.rs",
        required_patterns: &[
            "final_image_dispatch_authority_status",
            "nuis-provider-completion-evidence-collection-v1",
            "nuis-provider-glm-release-evidence-v1",
            "assert_provider_output_evidence_hash",
            "Nsld consumes provider completion and GLM evidence",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-elf64-amd64-object-image",
        path: "tools/nsld/src/object_elf_image.rs",
        required_patterns: &[
            "encode_elf_amd64_image",
            "R_X86_64_64",
            "__nuis_entry",
            "elf-relocation-table",
            "elf-section-header-table",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-provider-materialization-refresh",
        path: "tools/nsdb/src/provider_sample_materialize_tests.rs",
        required_patterns: &[
            "materializer_attaches_preexisting_real_device_output_payload",
            "second_evidence",
            "first_provider_output_payload_evidence",
            "status=attached",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "official-linux-cuda-sealed-image-closure",
        path: "tools/nuis/tests/official_galaxy_hetero_smoke/linux_cuda.rs",
        required_patterns: &[
            "sealed_linux_cuda_image_executes_and_replays_completion",
            "final_image_dispatch_authority_status",
            "cuda-driver-kernel-completed",
            "0xbdf4a47186386b21",
            "0xf71115b38f042bf7",
            "kernel.cuda.source.main.kernel_map_axis_2.i64",
            "kernel.cuda.source.main.kernel_reduce_sum_axis_3.i64",
            "nuis_project_main_kernel_map_axis_2_i64",
            "nuis_project_main_kernel_reduce_sum_axis_3_i64",
            "kernel.cuda.project.",
            "nuis.nsdb.device-provider-samples.toml",
            "provider_code_asset_identity_contract",
            "provider_code_asset_identity_entries",
            "provider_code_asset_identity_status",
            "provider_code_asset_identity_asset_id",
            "code_asset_identity_status",
            "code_asset_identity_asset_id",
            "code_asset_identity_hash",
            "provider_code_asset_identity_set_contract",
            "provider_code_asset_identity_set_root_hash",
            "code_asset_identity_set_status",
            "code_asset_identity_set_count",
            "code_asset_identity_set_root_hash",
            "provider_result_projection_status",
            "provider_result_projection_0_value_i64",
            "provider_result_projection_0_completion_token",
            "provider_result_projection_0_glm_release_token",
            "native_output_count",
            "completion_evidence_count",
            "provider_edge_transport_receipt_count",
            "provider.output.transfer.v1",
            "native_output_0_device",
            "completion_evidence_status",
            "glm_release_tokens",
        ],
    },
];
