use crate::dev_tensor_drift::DevTensorDriftCheckSpec;

pub(crate) const DEV_TENSOR_MAINLINE_DRIFT_CHECKS: &[DevTensorDriftCheckSpec] = &[
    DevTensorDriftCheckSpec {
        id: "application-terminal-outcome-contract",
        path: "crates/yir-core/src/application_outcome.rs",
        required_patterns: &[
            "nuis-yir-application-outcome-v1",
            "pub struct ApplicationOutcome",
            "terminal_codes_reject_unknown_and_contradictory_reports",
            "unclassified_failure_never_becomes_success",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "application-terminal-reply-shape",
        path: "crates/yir-runtime-host/src/application_event_pump/outcome.rs",
        required_patterns: &[
            "pub fn outcome",
            "self.cleanup_completed",
            "self.trace.is_ok()",
            "self.trace.is_err()",
            "terminal_reply_matrix_requires_finish_and_retains_cleanup_failure_distinction",
            "nonterminal_failure_cannot_claim_an_outcome",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "application-outcome-nuis-consumer-evidence",
        path: "tools/nuisc/tests/ns_nova_application_outcome.rs",
        required_patterns: &[
            "compiled_nuis_decoder_matches_shared_terminal_contract",
            "terminal_outcome_validation_runs_as_native_nuis_binary",
            "actual_late_finish_snapshot_reaches_nuis_without_reopening_the_image_session",
            "Message::Finish(0)",
            "consume(outcome.codes())",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "application-outcome-observation-not-execution-authority",
        path: "docs/reference/nuis-ns-nova-application-lifecycle-v1.toml",
        required_patterns: &[
            "[application_outcome]",
            "nuis-yir-application-outcome-v1",
            "post_close_observer = false",
            "parent_nuis_delivery = false",
            "resource_retirement_authority = false",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "application-enum-helper-return-execution-parity",
        path: "crates/yir-exec/src/execution_engine/call_result.rs",
        required_patterns: &[
            "Value::VariantUnion",
            "parse_owned_struct_layout",
            "union_matches",
            "owned_calls_accept_canonical_enum_results_and_reject_drift",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "ns-nova-engine-capability-horizon",
        path: "docs/versioning/nuis-beta-0.11-application-led-mainline.md",
        required_patterns: &[
            "Engine Capability Horizon",
            "Rendering, control, ML and audio",
            "dependency partial order, not frame lockstep",
            "not a finite list of allowed backend",
            "Audio device callbacks must not wait",
            "register separate",
            "planned, not verified execution",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "ns-nova-engine-target-honesty-boundary",
        path: "docs/reference/nuis-ns-nova-application-lifecycle-v1.toml",
        required_patterns: &[
            "[engine_target]",
            "capabilities = [\"rendering\", \"control\", \"machine-learning\", \"audio-workflows\"]",
            "cross-workflow-effects-not-isolated-demos",
            "multi-rate-explicit-clock-bridges-not-frame-lockstep",
            "application_ml_integration_claimed = false",
            "application_audio_workflow_claimed = false",
            "combined_workflow_execution_claimed = false",
            "hard_realtime_claimed = false",
            "explicit-future-coordinates-not-new-prerequisites-for-current-image-goal",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "application-session-typed-failure-contract",
        path: "crates/yir-core/src/application_failure.rs",
        required_patterns: &[
            "nuis-yir-application-failure-v2",
            "DispatchLimit = 3",
            "ProviderRejected = 4",
            "ProviderExchange = 5",
            "ProviderContract = 6",
            "ReplayExhausted = 7",
            "ProviderBudget = 9",
            "ProviderExecution = 10",
            "ProviderFinalization = 11",
            "failure_codes_are_explicit_and_unknown_codes_do_not_become_success",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "application-session-first-failure-latch",
        path: "crates/yir-runtime-host/src/application_failure.rs",
        required_patterns: &[
            "struct FailureState(Arc<AtomicI64>)",
            "compare_exchange(0, kind.code()",
            "self.record(failure.kind)",
            "failure_state_is_first_wins_and_isolated_between_sessions",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "application-session-provider-failure-producer",
        path: "crates/yir-runtime-host/src/provider_runtime_ipc.rs",
        required_patterns: &[
            "Result<ProviderResultFrame, ProviderFailure>",
            "ApplicationFailureKind::DispatchLimit",
            "ApplicationFailureKind::ProviderRejected",
            "ProviderFailure::exchange",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "application-session-replay-failure-producer",
        path: "crates/yir-runtime-host/src/provider_result_stream.rs",
        required_patterns: &[
            "provider_registry_with_failures",
            "self.failures.report(failure)",
            "ApplicationFailureKind::ReplayExhausted",
            "finish_provider_source_with_failures",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "application-session-close-reason-contract",
        path: "crates/yir-core/src/application_close_reason.rs",
        required_patterns: &[
            "nuis-yir-application-close-reason-v1",
            "Requested = 0",
            "EventFailed = 1",
            "HostFailed = 2",
            "close_reasons_roundtrip_without_granting_completion_authority",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "application-session-nuis-failure-cleanup",
        path: "stdlib/ns-nova/lib/app_runtime.ns",
        required_patterns: &[
            "pub enum NovaCloseReason",
            "pub fn close_reason",
            "NovaCloseReason.Unknown",
            "pub fn close_with_reason",
            "state.status != status_failed()",
            "pub enum NovaFailureKind",
            "pub fn close_with_failure",
            "state.failure_kind != 0",
            "pub struct NovaAppOutcome",
            "pub fn terminal_outcome",
            "pub fn outcome_succeeded",
            "pub fn outcome_failed",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "application-session-bounded-failure-grace",
        path: "tools/nuis/src/artifact_runtime_provider_ipc.rs",
        required_patterns: &[
            "FAILURE_CLEANUP_GRACE: Duration = Duration::from_secs(5)",
            "failed_at.is_none()",
            "failed_at.is_some_and",
            "runtime child exceeded the provider failure cleanup deadline",
            "match (child_result, server.finish())",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "application-session-failure-grace-evidence",
        path: "tools/nuis/src/artifact_runtime_provider_ipc_tests.rs",
        required_patterns: &[
            "provider_failure_allows_bounded_child_cleanup_instead_of_immediate_kill",
            "failure_grace_is_latched_and_kills_a_child_that_will_not_close",
            "explicit_wall_clock_limit_is_not_extended_by_failure_cleanup",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "application-session-compiled-failure-cleanup-evidence",
        path: "tools/nuis/src/artifact_device_sample_shader_failure_tests.rs",
        required_patterns: &[
            "verify_compiled_provider_failure_cleanup",
            "injected terminal provider failure",
            "run_command_with_request_reader",
            "window_session_close_reason=1",
            "window_session_cleanup_completed=1",
            "failure replaced old replay evidence",
            "verify_compiled_replay_exhaustion_cleanup",
            "window_session_failure_kind=7",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "application-session-window-v3-boundary",
        path: "docs/reference/nuis-yir-window-session-v3.md",
        required_patterns: &[
            "nuis-yir-window-session-v3",
            "nuis-yir-application-close-reason-v1",
            "cleanup_completed",
            "not successful-completion receipts",
            "five seconds",
            "nuis-yir-application-failure-v2",
            "Diagnostic strings are not parsed",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "application-session-idle-request-transport",
        path: "tools/nuis/src/artifact_runtime_provider_transport.rs",
        required_patterns: &[
            "set_nonblocking(false)",
            "set_read_timeout(None)",
            "read_exact(&mut first)",
            "first.as_slice().chain(reader)",
            "checked_duration_since(Instant::now())",
            "set_read_timeout(Some(remaining))",
            "runtime IPC request deadline exceeded",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "application-session-idle-deadline-evidence",
        path: "tools/nuis/src/artifact_runtime_provider_transport_tests.rs",
        required_patterns: &[
            "idle_wait_survives_each_request_timeout_on_the_same_connection",
            "buffered_requests_and_uploads_keep_the_existing_v3_framing",
            "partial_prefix_header_and_upload_fail_with_a_request_deadline",
            "partial_progress_does_not_extend_the_request_deadline",
            "peer_eof_wakes_idle_and_partial_reads_without_a_successful_message",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "application-session-supervised-idle-routing",
        path: "tools/nuis/src/artifact_runtime_provider_ipc.rs",
        required_patterns: &[
            "serve_runtime_provider_session_with_request_reader",
            "transport::read_request(stream, transport::IO_TIMEOUT)",
            "stream.shutdown(Shutdown::Both)",
            "child.kill()",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "application-session-idle-shutdown-evidence",
        path: "tools/nuis/src/artifact_runtime_provider_ipc_tests.rs",
        required_patterns: &[
            "supervisor_shutdown_wakes_an_idle_provider_without_acknowledging_success",
            "observer.read_timeout()",
            "server.finish().unwrap_err()",
            "bounded_child_timeout_kills_and_reaps_without_waiting_for_an_ipc_connection",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-provider-runtime-result-stream",
        path: "tools/nsdb/src/provider_runtime_result_stream.rs",
        required_patterns: &[
            "nuis-provider-runtime-result-stream-v2",
            "ProviderRuntimeResultTarget",
            "ProviderPhysicalCompletion::parse",
            "stream_hash",
            "nuis.runtime.provider-result.",
            "rejected manifest protocol",
            "budget.reserve(result.payload.len())?",
            "manifest.len() > MAX_REPLAY_MANIFEST_BYTES",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "yir-host-provider-runtime-result-consumer",
        path: "crates/yir-runtime-host/src/provider_result_stream.rs",
        required_patterns: &[
            "nuis-provider-runtime-result-stream-v2",
            "ProviderResultShaderMod",
            "ShaderMod.validate_draw_instanced",
            "ShaderMod.record_draw_instanced",
            "ProviderResultSource",
            "physical_fence_required",
            "stage_provider_physical_completion",
            "provider runtime result stream is exhausted",
            "payload path is not output-relative",
            "budget.reserve(usize_field(fields, \"payload_byte_length\")?)?",
            "replay_io::read_bounded",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "application-session-shared-replay-budget",
        path: "crates/yir-core/src/provider_runtime_budget.rs",
        required_patterns: &[
            "ReplayBudget",
            "MAX_REPLAY_BYTES",
            "MAX_REPLAY_MANIFEST_BYTES",
            "checked_add",
            "exact_byte_limit_is_admitted_without_allocating_payloads",
            "count_and_invalid_extent_cannot_change_or_reset_accounting",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "application-session-pre-device-reservation",
        path: "tools/nsdb/src/provider_runtime_ipc.rs",
        required_patterns: &[
            "admitted_payload_bytes",
            "execute_reserved",
            "reserve(payload_bytes)",
            "reserved output extent",
            "session.close()",
            "serve_runtime_provider_session_with_request_reader",
            "let request = read_request(stream).map_err",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "application-session-reservation-boundary-evidence",
        path: "tools/nsdb/src/provider_runtime_ipc_tests.rs",
        required_patterns: &[
            "exhausted_replay_budget_rejects_before_device_execution",
            "failed_admitted_device_work_does_not_refund_its_reservation",
            "device_result_must_fit_the_registered_reservation",
            "exact_dispatch_limit_can_still_finish_without_resetting_the_session",
            "request_reader_failure_is_terminal_without_retry_or_device_execution",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "application-session-bounded-replay-file-read",
        path: "crates/yir-runtime-host/src/provider_replay_io.rs",
        required_patterns: &[
            "metadata.is_file()",
            "file.take(limit as u64 + 1)",
            "bytes.len() > limit",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "application-session-replay-budget-read-evidence",
        path: "crates/yir-runtime-host/src/provider_replay_budget_tests.rs",
        required_patterns: &[
            "declared_replay_budget_is_checked_before_any_payload_is_opened",
            "oversized_sparse_files_are_rejected_without_loading_their_contents",
            "payload_reads_are_limited_and_short_files_still_fail_identity_checks",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "application-session-replay-replacement-evidence",
        path: "tools/nsdb/src/provider_runtime_result_stream_tests.rs",
        required_patterns: &[
            "rejected_replacement_preserves_previous_runtime_evidence",
            "old_manifest",
            "old_payload",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "application-session-window-profile",
        path: "crates/yir-runtime-host/src/window_session.rs",
        required_patterns: &[
            "nuis-yir-window-session-v3",
            "validate_window_session",
            "validate_window_trace",
            "ApplicationSessionSignature::bind",
            "close callback must not present",
            "window_trace_requires_exact_bounded_rgba8_without_glyph_fallback",
            "ApplicationCloseReason::EventFailed",
            "self.pump.close_after_failure(arguments, kind)",
            "self.observe_stopped_error(&result)",
            "pub fn outcome(&self) -> Option<ApplicationOutcome>",
            "self.cleanup_completed = reply.cleanup_completed",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "application-session-window-c-ownership",
        path: "crates/yir-runtime-host/src/window_session/ffi.rs",
        required_patterns: &[
            "nuis_window_session_open",
            "nuis_window_session_poll",
            "nuis_window_session_close_with_reason",
            "nuis_window_session_close_reason",
            "nuis_window_session_cleanup_completed",
            "nuis_window_session_failure_kind",
            "nuis_window_session_outcome_field",
            "terminal_open_failure_has_a_stable_snapshot_without_cleanup",
            "ApplicationCloseReason::from_code(reason)",
            "nuis_window_session_free",
            "poll buffer must be empty",
            "Box::from_raw",
            "exactly one registered IPC or replay",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "application-session-appkit-event-adapter",
        path: "tools/yir-pack-aot/src/host_window_session.rs",
        required_patterns: &[
            "--window-session",
            "nuis_window_session_poll",
            "if (!window_session_mode) nuis_yir_entry()",
            "NSModalPanelRunLoopMode",
            "requestSessionTermination",
            "NSEventTypeApplicationDefined",
            "window_session_closed",
            "window_session_close_reason=",
            "window_session_cleanup_completed=",
            "window_session_close_failure_kind=",
            "window_session_failure_kind=",
            "window_session_outcome_status=",
            "window_session_outcome_cleanup=",
            "window_session_outcome_failure=",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "application-session-compiled-window-evidence",
        path: "tools/nuis/src/artifact_device_sample_shader_window_tests.rs",
        required_patterns: &[
            "compiled_window_routes_appkit_events_through_registered_nuis_and_live_metal",
            "run_command_bounded",
            "handle_run_artifact_with_window",
            "window_session_close_requested",
            "128578",
            "compiled,hit",
            "source_index",
            "failure::verify_compiled_provider_failure_cleanup",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "application-session-window-failure-evidence",
        path: "crates/yir-runtime-host/tests/provider_application_session/window.rs",
        required_patterns: &[
            "window_signature_drift_fails_before_connecting_or_opening",
            "multiple_presentations_reject_before_provider_success",
            "close_presentation_is_rejected_before_finish_acknowledgement",
            "provider_and_dispatch_budget_failures_reach_nuis_close_without_becoming_success",
            "host_failure_is_latched_before_cleanup_and_busy_close_does_not_poison_state",
            "late_finish_failure_preserves_cleanup_without_repeating_or_certifying_it",
            "cleanup_failure_cannot_hide_the_original_provider_failure",
            "invalid_cleanup_trace_cannot_hide_the_original_callback_failure",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "application-session-owned-event-pump",
        path: "crates/yir-runtime-host/src/application_event_pump.rs",
        required_patterns: &[
            "nuis-yir-application-event-pump-v1",
            "mpsc::sync_channel(1)",
            "ApplicationEventPump",
            "recv_timeout(timeout)",
            "self.pending.is_some()",
            "pub fn abort",
            "pub cleanup_completed: bool",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "application-session-pump-scoped-worker",
        path: "crates/yir-runtime-host/src/application_event_pump/worker.rs",
        required_patterns: &[
            "with_registered_provider_application_session",
            "requests.recv()",
            "session.event(command.arguments)",
            "session.close(command.arguments)",
            "ApplicationPumpPhase::Closed",
            "ApplicationPumpPhase::Stopped",
            "session.record_host_failure(kind)",
            "cleanup_completed = trace.is_ok()",
            "failure_kind: failures.kind()",
            "session.completion_status().and(trace)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "application-session-pump-failure-and-pressure-evidence",
        path: "crates/yir-runtime-host/tests/provider_application_session/event_pump.rs",
        required_patterns: &[
            "owned_pump_keeps_one_session_across_one_hundred_host_deliveries",
            "close_reply_waits_for_provider_acknowledgement",
            "failed_event_latches_and_successful_cleanup_cannot_certify_completion",
            "abort_does_not_join_an_in_flight_callback_or_queue_cleanup",
            "provider_dispatch_budget_is_not_reset_between_host_events",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "application-session-static-yir-contract",
        path: "crates/yir-core/src/application_session.rs",
        required_patterns: &[
            "nuis-yir-application-session-v1",
            "YirApplicationSession",
            "ApplicationSessionSignature",
            "validate_application_sessions",
            "registered_application_session",
            "duplicate application session",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "application-session-project-declaration",
        path: "tools/nuisc/src/project/application_sessions.rs",
        required_patterns: &[
            "parse_application_sessions",
            "duplicate application_sessions field",
            "malformed application_sessions string array",
            "register_project_application_sessions",
            "validate_application_sessions",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "application-session-registered-host-admission",
        path: "crates/yir-runtime-host/src/provider_application_session.rs",
        required_patterns: &[
            "with_registered_provider_application_session",
            "registered_application_session",
            "registration.entries()",
            "ApplicationSession::preflight",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "application-session-uncalled-host-roots",
        path: "tools/nuisc/tests/ns_nova_application_session.rs",
        required_patterns: &[
            "registration_preserves_uncalled_helpers_as_host_roots",
            "compiled_registration_roundtrips_and_rejects_signature_drift",
            "ApplicationSession::open_registered",
            "unknown",
            "duplicate application session",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "application-session-embedded-registration-evidence",
        path: "tools/nuis/src/artifact_device_sample_shader_session_tests.rs",
        required_patterns: &[
            "with_registered_provider_application_session",
            "application-session ",
            ".windows(record.len())",
            "compiled host must retain the lifecycle registration",
            "different YIR module",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "application-session-provider-finish-gate",
        path: "crates/yir-runtime-host/src/provider_application_session.rs",
        required_patterns: &[
            "nuis-yir-provider-application-session-v1",
            "ApplicationSession::preflight",
            "ApplicationProviderSource::Ipc",
            "ApplicationProviderSource::Replay",
            "application.completion_status()?",
            "finish_provider_source_with_failures(&provider, &failures)?",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "application-session-provider-failure-regressions",
        path: "crates/yir-runtime-host/tests/provider_application_session.rs",
        required_patterns: &[
            "one_transport_carries_independent_events_and_finishes_only_after_close",
            "missing_close_driver_error_and_swallowed_failures_do_not_acknowledge_success",
            "wrong_module_and_close_acknowledgement_are_rejected",
            "invalid_binding_is_rejected_before_connecting",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "application-session-live-metal-evidence",
        path: "tools/nuis/src/artifact_device_sample_shader_session_tests.rs",
        required_patterns: &[
            "executes_ns_nova_persistent_image_session_through_live_provider",
            "ApplicationEventPump::spawn",
            "nsdb::serve_runtime_provider_session",
            "PhysicalFence",
            "runtime_dispatch_session_worker_count",
            "compiled,hit",
            "unconsumed frame",
            "transport::read_request(stream, Duration::from_secs(1))",
            "Duration::from_millis(1500)",
            "idle must not generate an event or frame",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "application-session-boundary-and-scope",
        path: "docs/reference/nuis-yir-application-session-v1.md",
        required_patterns: &[
            "nuis-yir-application-session-v1",
            "reference provider",
            "not migrated",
            "no rollback",
            "ns_nova_application_session",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "application-session-runtime-carrier",
        path: "crates/yir-runtime-host/src/application_session.rs",
        required_patterns: &[
            "APPLICATION_SESSION_CONTRACT",
            "SessionBoundary::bind",
            "FunctionSession::new",
            "ApplicationSessionPhase::Faulted",
            "ApplicationSessionPhase::Closed",
            "close_error",
            "pub(crate) fn record_host_failure",
            "application host requested failed cleanup",
            "pub fn failure_kind",
            "cleanup failed: {close}",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "application-session-compiled-nuis-evidence",
        path: "tools/nuisc/tests/ns_nova_application_session.rs",
        required_patterns: &[
            "compile_project",
            "compiled_nuis_image_state_survives_independent_events_without_main_replay",
            "compiled_nuis_close_reason_sets_and_preserves_failure_without_frame_replay",
            "last_completion_tick",
            "frame history must be drained",
            "entry_nodes.contains",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "dev-tensor-application-led-plan",
        path: "docs/reference/nuis-development-tensor.mainline.toml",
        required_patterns: &[
            "nuis-dev-tensor-mainline-v1",
            "ns-nova-application-led",
            "interrupts =",
            "persistent-application-session",
            "lifecycle-failure-resource-safety",
            "sustained-runtime-performance",
            "compiler-component-ownership-transfer",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "dev-tensor-mainline-manifest-validation",
        path: "tools/nuis/src/dev_tensor_mainline_parse.rs",
        required_patterns: &[
            "unsupported mainline schema",
            "duplicate mainline node",
            "duplicate mainline field",
            "duplicate mainline array entry",
            "unknown mainline field",
            "unterminated mainline array",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "dev-tensor-mainline-selection-contract",
        path: "docs/reference/nuis-development-tensor-mainline.md",
        required_patterns: &[
            "mainline_dependency_path",
            "mainline-plan-invalid",
            "mainline-plan-complete",
            "not a measured",
            "baseline validation",
            "not substitutes for runtime",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "application-led-module-migration-roadmap",
        path: "docs/versioning/nuis-beta-0.11-application-led-mainline.md",
        required_patterns: &[
            "beta-0.11.3",
            "entire engine",
            "not compiler self-hosting",
            "existing explicit authorization",
            "gamma-0.5.*",
            "gamma-0.10.*",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "provider-runtime-typed-rejection-admission",
        path: "crates/yir-core/src/provider_runtime_rejection.rs",
        required_patterns: &[
            "pub enum RejectionPhase",
            "pub enum RejectionCode",
            "pub struct Rejection",
            "pub fn admit",
            "self.sequence != sequence",
            "runtime IPC rejection code is unknown",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "provider-runtime-typed-rejection-wire-tests",
        path: "crates/yir-core/src/provider_runtime_rejection_tests.rs",
        required_patterns: &[
            "typed_rejections_roundtrip_only_valid_producer_boundaries",
            "unknown_noncanonical_legacy_and_malformed_rejection_wire_is_rejected",
            "rejection_requires_exact_pending_sequence_and_phase_without_granting_success",
            "rejection_diagnostics_are_bounded_utf8_without_losing_failure_identity",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "provider-runtime-typed-rejection-server-tests",
        path: "tools/nsdb/src/provider_runtime_ipc_tests.rs",
        required_patterns: &[
            "RejectionCode::Budget",
            "RejectionCode::Execution",
            "RejectionCode::Result",
            "cleanup_and_publication_failures_keep_typed_first_fault_and_never_acknowledge",
            "failed publication acknowledged success",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "provider-runtime-typed-rejection-client-tests",
        path: "crates/yir-runtime-host/src/provider_runtime_ipc_tests.rs",
        required_patterns: &[
            "typed_remote_rejections_are_admitted_before_category_delivery_and_never_advance",
            "finish_rejection_requires_finish_identity_and_cannot_become_closed",
            "ApplicationFailureKind::ProviderBudget",
            "ApplicationFailureKind::ProviderExecution",
            "ApplicationFailureKind::ProviderFinalization",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "provider-runtime-ipc-v4-honesty-boundary",
        path: "docs/reference/nuis-yir-provider-runtime-ipc-v4.md",
        required_patterns: &[
            "nuis-yir-provider-runtime-ipc-v4",
            "Wire codes and application failure codes are separate namespaces",
            "Execution is deliberately a boundary category",
            "before target Hello",
            "Mixed v3/v4 peers are rejected",
        ],
    },
];
