use crate::dev_tensor::{DevTensorCell, DevTensorExpectedCoordinate};

pub(crate) const DEV_TENSOR_CELLS: &[DevTensorCell] = &[
    DevTensorCell {
        architecture: "compiler-frontdoor",
        module: "nuis-cli",
        function: "workflow-and-project-orientation",
        status: "stable",
        progress: 100,
        bootstrap_critical: true,
        closure_role: "developer-frontdoor",
        evidence: "workflow/project-status/project-doctor JSON and text frontdoors are regression-backed, share closure_summary source/status/ready/blocker/action/command fields, expose the versioned nuis-frontdoor-reading-order-v1 contract in nested and top-level frontdoor surfaces, order closure_summary before the development-tensor handoff contract, document closure_summary as the canonical human closure line, project-status promotes built-project link-plan evidence into project-status-link-plan closure guidance instead of stopping at artifact-ready, nuis status prints the stable closure-summary-then-dev-tensor transcript sample, and project health tests derive public module, Galaxy surface, and visible Galaxy library-module counts from the resolved project registry while retaining name-level contract assertions",
        next_step: "mirror the same closure-summary-then-dev-tensor reading order into any new project-status/build-report/package frontdoors as those surfaces grow",
        blocker: "the versioned primary frontdoor reading order and registry-derived surface summaries are status-visible, machine-readable, and regression-backed; future package/linker summary surfaces must keep consuming the same contracts",
        next_action: "keep future frontdoor/package/linker summary surfaces aligned to the closure_summary then dev_tensor_weakest_task_card_handoff reading order",
        validation_command: "cargo test -q -p nuis project_status && cargo test -q -p nuis workflow_surface && cargo test -q -p nuis --test status_frontdoor_smoke",
        expected_artifact: "workflow/project-status/project-doctor summary surfaces expose one shared closure_summary contract followed by the versioned nuis-frontdoor-reading-order-v1 handoff contract, project-status consumes link-plan/nsld closure evidence after build, docs define both closure_summary plus tensor task-card as the canonical human reading order, nuis status prints the stable closure-summary-then-tensor transcript sample, and project/workflow/status tests pin field presence, field order, documentation, runtime contract, and registry-derived surface counts",
    },
    DevTensorCell {
        architecture: "compiler-frontdoor",
        module: "nuis-cli",
        function: "artifact-runtime-closure",
        status: "stable",
        progress: 100,
        bootstrap_critical: true,
        closure_role: "artifact-execution-frontdoor",
        evidence: "run-artifact, workflow, artifact-doctor, project-status/project-doctor, build-report, release-check logs, release-check JSON summary renderer, release-check --json CLI entrypoint, command-level release-check --json stdout smoke, explicit runtime materialization policy fields, nsld handoff, self-contained host-runner probe fields, nsdb-ready launch_evidence contract fields, nsdb-facing payload execution trace records, persisted run-artifact nsdb payload handoff metadata, persisted hetero runtime trace metadata, generated payload decoder manifests, generated decoder manifest surface mirrors, nsdb inspect hetero runtime trace consumption, workflow/artifact-doctor persisted handoff mirrors, workflow/artifact-doctor launch-evidence mirrors, nsdb inspect payload handoff event consumption, nsdb event filters, dedicated nsdb events command, nsdb replay-plan checkpoints with stable frame/value anchors, value-sample references, trace-backed sample resolution status, value-sample materialization descriptors, value slot/schema metadata, typed value snapshot references, concrete metadata content summaries, opaque payload file summaries, decoder capability/detail-level boundaries, spec-driven lightweight payload format probes, external decoder manifest loading, ASCII/hex external magic probes, external decoder capability/detail declarations, decoder manifest diagnostics, inspect-level decoder manifest summaries, per-record decoder manifest diagnostics, decoder manifest protocol/schema version checks, and final-output boundary reports share closure evidence",
        next_step: "turn per-domain run-artifact trace records into real device execution samples without coupling release-check to runtime execution",
        blocker: "release-check now explicitly remains a pure readiness gate, so real runtime evidence must come from run-artifact/device sample lanes",
        next_action: "turn per-domain run-artifact trace records into real device execution samples without coupling release-check to runtime execution",
        validation_command: "cargo test -q -p nuis run_artifact && cargo test -q -p nsdb",
        expected_artifact: "workflow/artifact-doctor/project-status/project-doctor/build-report/release-check-summary/release-check-json/nsdb-facing surfaces report persisted debugger handoff/runtime trace metadata, generated payload decoder manifests, generated decoder manifest mirrors, and nsdb tooling consumes/filter/replay-plans it through inspect, events, replay-plan frame/value anchors, value-sample references, trace-backed sample-resolution status, materialized sample descriptors, value slot/schema metadata, typed value snapshot refs, value content summaries, opaque payload file summaries, decoder registry status, decoder capability/detail boundaries, spec-driven lightweight payload format probes, external decoder manifest loading, ASCII/hex external magic probes, external decoder capability/detail declarations, decoder manifest diagnostics, inspect-level decoder manifest summaries, per-record decoder manifest diagnostics, and decoder manifest protocol/schema version checks",
    },
    DevTensorCell {
        architecture: "linker-toolchain",
        module: "nsld",
        function: "artifact-chain-drive",
        status: "stable",
        progress: 100,
        bootstrap_critical: true,
        closure_role: "linker-artifact-chain",
        evidence: "nsld drive can apply whitelisted artifact-chain steps, stop cleanly on host-assisted final output boundaries, report mutation_policy, expose nsld-drive-safe-next-v1 gate fields, Nuis closure_summary promotes mutating drive recommendations into nsld-drive-safe-next next-action/command selection through the command-set safe_next probe, self-contained NSB smoke asserts the clean safe-next gate after until-clean, official shader/kernel hetero smoke asserts whitelisted drive apply plus rerun-drive safe-next guidance, nsld provider-sample boundary tests assert safe_next_contract/action/command/reason/gate fields through both apply and until-clean final-output boundary stops, and final-output object-package/replay plus closure summaries now mirror the shared artifact_chain_safe_next contract and probe command without giving replay mutation semantics",
        next_step: "keep future final-output, package, and replay consumers on the shared artifact_chain_safe_next mirror instead of introducing parallel linker transition vocabularies",
        blocker: "artifact-chain mutation, boundary gates, and package/replay return-to-driver probes are protocolized and regression-backed; future consumers must preserve the read-only replay versus mutating drive separation",
        next_action: "keep future package and replay consumers attached to the shared artifact_chain_safe_next contract and probe command",
        validation_command: "cargo test -q -p nuis workflow_surface && cargo test -q -p nuis project_status && cargo test -q -p nsld drive",
        expected_artifact: "nsld drive JSON reports mutation_policy, safe_next_action, safe_next_command, safe_next_reason, safe_next_contract, safe_next_gate_required, safe_next_gate_action, and crossing command fields; Nuis closure_summary recommends nsld-drive-safe-next plus the safe_next probe command whenever artifact-chain mutation is available; final-output object-package/replay and closure summaries expose artifact_chain_safe_next_contract plus artifact_chain_safe_next_probe_command; self-contained and official hetero smokes assert clean/rerun safe-next gates; provider-sample boundary drive tests assert safe-next gates after boundary materialization and explicit final-output crossing stops",
    },
    DevTensorCell {
        architecture: "linker-toolchain",
        module: "nsld",
        function: "final-output-boundary",
        status: "usable",
        progress: 100,
        bootstrap_critical: true,
        closure_role: "executable-output-boundary",
        evidence: "final-executable-output reports normalized boundary status, materialization status, recommended next action, path presence, ownership, runnable candidate, blockers, Nuis/Nsld mirrors, self-contained relocation-safe images, container-loader handoff readiness, first-payload execution metadata from the final output itself, nsdb-facing payload execution trace metadata, command-level persistence of the first-payload trace as an nsdb handoff record, nsdb replay-plan readiness, replay-evidence-ready status, checkpoint/replayable counts, stable replay next-action/next-command fields, Nuis frontdoor mirrors/closure selection for replay-ready or replay-blocked states, self-contained smoke asserts replay-ready contract/command fields, official hetero smoke asserts the replay-blocked resolve gate, and provider-sample materialization now exposes nsld-final-output-boundary-return-v1 plus nsdb-payload-execution-replay-plan-v1 so device samples can return to the same final-output replay vocabulary",
        next_step: "carry the same final-output replay vocabulary into future package-summary and debugger replay transcript surfaces",
        blocker: "final-output ready/blocked gates and provider-sample return gates share one vocabulary now; remaining risk is future package-summary/debugger transcript surfaces drifting from that contract",
        next_action: "mirror final-output replay vocabulary into future package-summary and debugger replay transcript surfaces as they are added",
        validation_command: "cargo test -q -p nsld final_executable_output && cargo test -q -p nsdb && cargo test -q -p nuis --test self_contained_nsb_smoke && cargo test -q -p nuis --test official_galaxy_hetero_smoke",
        expected_artifact: "final-output boundary emits trace-ready first-payload metadata, persists an nsdb debugger handoff TOML, exposes replay next-action/next-command fields, workflow mirrors replay-evidence-ready plus checkpoint/replayable counts and commands, self-contained smoke asserts replay-ready command fields, official hetero smoke asserts replay-blocked resolve fields, and provider-sample materialization reports the final-output return/replay contracts",
    },
    DevTensorCell {
        architecture: "heterogeneous-runtime",
        module: "nustar",
        function: "registered-domain-contracts",
        status: "usable",
        progress: 100,
        bootstrap_critical: true,
        closure_role: "heterogeneous-domain-registration",
        evidence: "domain registration, backend readiness, dispatch/link-plan consumption, Nsld assembly, final-layout payloads, frontdoor mirrors, provider registry/probes, fallback and native execution are connected. Five ordered requests use four CoreML nodes and one Metal node and compare [11,17,23,29] with zero mismatch. Native outputs can use sealed NUISPFD1 carriers or an honest host-owned fallback. Dependency edges preserve producer storage through provider.output.transfer.v1 when a transferable carrier exists and otherwise record memory-owned staging without inventing device residency. CoreML configures independent transferable input channels, including two-input fan-in. Unix output verification returns a read-only mmap-backed ProviderOutputPayload shared by comparison, summaries, hashes, and completed-output metadata instead of retaining a duplicate Vec; portable hex output retains an owned fallback. Writable single-frame carriers emit fixed metadata plus a sparse payload span. Output residency and session contracts record honest host/device capability, deterministic leases, lifecycle hooks, GLM-owned handles, and graph-close release. Worker transports prove one persistent stdio PID and frame-bound SCM_RIGHTS ownership. UnixWorkerProcessTransport inherits only the child socket endpoint, validates a PID handshake against Child::id, preserves sparse original input role indices, detects worker exit while awaiting a reply, and sends post-spawn descriptors to the same compiled worker process. NUISPWU2 adds a hash-checked opaque binary request and one ordered semantic role per descriptor. NUISPWUR7 adds request length/hash identity without body echo, adapter protocol length/hash metadata, and ordered worker-owned output descriptor manifests, binds the original request hash and input/output role manifests, and carries the positive Nuis invocation status; decoding rejects non-positive status, mismatched ancillary count, unreadable payload, and output hash drift. The std provider-worker lifecycle and dispatch registry are authored in Nuis. ProviderWorkerRequest carries opaque request and descriptor-table handles; ProviderDispatchBinding supplies an open-ended provider key, dispatch token, capability hash, and enabled state. The registered `provider_request_ingress` intrinsic preserves its five-scalar compatibility form and adds an eight-scalar capsule form carrying token plus input/output role counts. Data Nustar interpretation returns only the opaque request handle, GLM records five or eight value reads, and LLVM performs scalar passthrough while preserving all metadata in YIR. The persistent Nuis worker reads capsule scalars from its verified frame, validates token and role counts, emits eight explicit ingress dependencies, invokes a registry-derived provider-neutral capsule invoker, and only then replies. The thin Unix ABI adapter creates negotiated anonymous output descriptors and transfers them with SCM_RIGHTS; Nsdb independently verifies every role, length, and FNV hash before publishing worker-invoked evidence. Process-adapter v4 supplies open ordered literal, verified-path, descriptor-path, and descriptor-carrier argument templates. Registered PixelMagic gray8, WitSage Metal f32 bias, and WitSage large, chained, and two-input fan-in CoreML requests execute beneath persistent Nuis workers with hash-verified executables and model control assets; every worker result returns as a sealed transferable NUISPFD1 carrier. `nuis-provider-process-adapter-cache-v1` derives an open identity from source, runner contract, ordered frameworks, OS, and architecture; one graph owns immutable images, four CoreML requests prove `compiled,hit,hit,hit`, distinct Metal source remains independently compiled, and graph teardown removes all temporary files. `nuis-provider-worker-adapter-control-v1` compacts the fixed launch header and ordered open arguments into one request-hash-bound record and enforces a portable 1800-byte budget before sendmsg. `nuis-provider-worker-adapter-control-carrier-v1` spills manifests above the 384-byte inline budget into an unlinked length/hash-bound `control.adapter` descriptor; the v25 worker requires that role to be unique and last, excludes it from capsule input counts and input byte sums, and real CoreML reports carrier mode while preserving two-input fan-in. `nuis-provider-output-binding-v1` maps ordered roles to output buffers, ProviderWorkerLease retains every verified result, and provider sessions allocate one GLM-owned output handle per role while preserving the first output as the compatibility primary. Nuis validates handles and registration identity, rejects mismatched capability or capsule metadata, advances ordered accept/reject/commit state, and AOT-executes lifecycle, ingress, invocation, and reply control flow. C and Objective-C runners remain bootstrap ABI probes or concrete backend adapters rather than owners of worker control flow",
        next_step: "publish every registered worker output into graph ownership and dependency lookup instead of retaining only the compatibility primary output",
        blocker: "ordered output bindings, independently retained lease results, and per-role session handles now exist, but CompletedProviderOutput storage and NativeProviderRequestExecution still publish only one output under the producer request id",
        next_action: "index completed outputs by producer request plus output buffer or role, move every additional worker output into that table, resolve dependency bindings against the selected producer output, and prove distinct consumers plus graph-close release",
        validation_command: "cargo test -q -p nsdb lease_preserves_registered_primary_and_additional_outputs -- --test-threads=1 && cargo test -q -p nsdb request_allocates_ordered_role_bound_output_handles -- --test-threads=1 && cargo test -q -p nuis --test official_galaxy_hetero_smoke official_galaxy_hetero_projects_emit_shader_and_kernel_artifacts -- --test-threads=1 && cargo test -q -p nuis dev_tensor",
        expected_artifact: "worker registration and NUISPWUH3 expose input/control/output budgets, NUISPWUR7 verifies ordered output carriers, ProviderRequest binds roles to buffers, ProviderWorkerLease retains every descriptor, sessions allocate one GLM-owned handle per role, and the next layer publishes all outputs into graph completion ownership",
    },
    DevTensorCell {
        architecture: "standard-library",
        module: "std",
        function: "host-io-filesystem-text",
        status: "usable",
        progress: 100,
        bootstrap_critical: true,
        closure_role: "bootstrap-std-foundation",
        evidence: "std IO/filesystem/text/stdin examples, std_filesystem_smoke light lane, observable CLI smoke, direct cli_wc_demo argv/file/text-stats run, direct cli_pgm_invert_demo image-shaped file read/write run, reusable StdReportContracts, direct cli_report_file_demo argv/file/text report output, PixelMagic report-file consumption of std-preprocessed PGM input, PixelMagic/WitSage report-file workloads, official_galaxy_hetero_smoke shader/kernel artifact smokes, direct run-artifact hetero trace record assertions, explicit nsdb provider-sample materialization, deterministic provider-sample artifact files with hash evidence, registered nuis-provider-runner-adapter-v1 fallback descriptors, PixelMagic Metal provider-sample evidence carries PGM input size plus gray8 width/height/stride/max-value/operation/payload path/byte-count/hash through run-artifact and materialized artifacts, the raw std-preprocessed pixel payload is persisted beside those artifacts, and execute-provider-samples validates, uploads, inverts, and reads back that buffer through a real Metal command buffer on macOS while preserving deterministic fallback elsewhere",
        next_step: "keep the completed std host IO/filesystem/text-to-PixelMagic payload boundary regression-stable while image execution evolves in the PixelMagic and heterogeneous-runtime cells",
        blocker: "none for the current bootstrap std scope; richer image codecs and asynchronous IO remain later capability work rather than closure blockers",
        next_action: "route subsequent image-buffer generalization through PixelMagic/provider contracts without widening the completed std bootstrap boundary",
        validation_command: "cargo test -q -p nuis --test std_filesystem_smoke && cargo test -q -p nuis --test official_galaxy_hetero_smoke",
        expected_artifact: "Std observable CLI smoke covers stdin, wc-style file/text stats, PGM image-shaped file transformation, report-file generation, PixelMagic std-preprocessed PGM input consumption, PixelMagic/WitSage report workloads, hetero domain artifacts, run-artifact trace records, materialized provider-sample manifests, shape/hash-bound raw gray8 payload persistence, provider runner adapter contract metadata, deterministic fallback evidence, and real Metal buffer upload/invert/readback output bytes/hash/device evidence on supported macOS hosts",
    },
    DevTensorCell {
        architecture: "standard-library",
        module: "pixelmagic",
        function: "image-processing-lane",
        status: "active",
        progress: 68,
        bootstrap_critical: false,
        closure_role: "official-compute-package",
        evidence: "PixelMagic has official package contracts, shader surfaces, domain demos, a std-report-file workload, checked shader pipeline builds that emit Metal sidecar/payload artifacts, direct run-artifact assertions for shader hetero runtime trace records, provider-scoped sample validation descriptors, std-preprocessed PGM evidence carrying gray8 width/height/stride/max-value/invert operation/payload path/byte-count/hash through run-artifact JSON/provider-sample manifests/materialized sample artifacts, execute-provider-samples coverage for the Metal/Apple GPU provider family, protocolized provider output payload handoff files, adapter capability/probe status, comparison metadata, and a native Metal runner that validates and uploads the raw pixel payload, dispatches a gray8 invert kernel, reads back four transformed bytes, records output hash and Apple GPU identity, and preserves deterministic fallback on unsupported hosts",
        next_step: "register additional PixelMagic format/filter kernels and compare full expected output content through the common provider request model",
        blocker: "PixelMagic now runs one real registered shape/hash-bound gray8 invert buffer through Metal, but only one pixel format/filter operation is executable",
        next_action: "register a second PixelMagic kernel descriptor without coupling Nsdb to package-specific request construction",
        validation_command: "cargo test -q -p nuis --test official_galaxy_hetero_smoke && cargo test -q -p nsdb provider_sample",
        expected_artifact: "PixelMagic shader pipeline emits checked Metal sidecar/payload artifacts, report-file evidence, run-artifact trace records, shape/hash-bound gray8 provider requests, materialized raw pixel payload and provider-sample artifacts, deterministic fallback output, and native Metal buffer upload/invert/readback output with execution contract/status/device/bytes/hash evidence",
    },
    DevTensorCell {
        architecture: "standard-library",
        module: "witsage",
        function: "classical-ml-lane",
        status: "active",
        progress: 93,
        bootstrap_critical: false,
        closure_role: "official-compute-package",
        evidence: "WitSage package contracts and CoreML artifacts include feature-grid, affine, chained-affine and two-feature Add. One request collection compares those outputs, then crosses from CoreML Add [10,16,22,28] into a registry-selected Metal f32 bias kernel and compares [11,17,23,29]. Nsdb recognizes no WitSage operation names and records zero-mismatch outputs plus dependency, adapter-order and collection evidence",
        next_step: "exercise portable non-zero tolerance profiles and one additional model family through the same provider-neutral comparison boundary",
        blocker: "CPU/ANE multi-model execution and exact deterministic comparison are closed, but cross-provider floating-point variance and model-family diversity remain narrow",
        next_action: "add a non-zero tolerance WitSage baseline without weakening expected-asset hash or non-finite validation",
        validation_command: "cargo test -q -p nuis --test official_galaxy_hetero_smoke && cargo test -q -p nsdb provider_sample",
        expected_artifact: "WitSage emits four CoreML requests and one dependent Metal f32 request in an ordered collection, native predictions or fallback, real linear/fan-in/cross-provider edges, compute-plan evidence, hash-bound expected outputs, per-element comparisons, indexed identities and graph/output hashes",
    },
    DevTensorCell {
        architecture: "language-core",
        module: "nuisc",
        function: "type-control-flow-generics",
        status: "usable",
        progress: 100,
        bootstrap_critical: true,
        closure_role: "language-self-hosting-foundation",
        evidence: "control flow, generics, traits, pointers, floats, enums, error handling, inference, task_result_enum, generic trait-bound guarded-match, GLM buffer, generic_result_buffer_lambda helper with Err fallback, if-expression runtime coverage, nested partial expected-type Result.Ok propagation, nested if/match expected-type Result.Ok/Err propagation, project-source no-annotation higher-order try/await Result binding propagation, async_value YIR boundary lowering, runnable no-annotation try/await Result HOF Ok-path plus async/HOF Err-path binary coverage, true `?` Err continuation for inlined async Result helpers via select-survivor lowering, chained try/await Result HOF native binary coverage across normalize/decorate/pipeline helper boundaries, dynamic host argv input driving helper-side Result `?` continuations through Result-level early-return folding, std-style dynamic Result/Buffer/lambda/trait-bound/pointer bootstrap workload with native binary exit 59, import-boundary std-style workload with public helper module generic Result/HOF helpers, helper-side HOF synthetic functions, helper-module impl method emission for support-side trait-bound bump, inferred imported result_map and Result helper constructor generic arguments, three-module std-style package-boundary workload with helper-to-helper HOF templates, partial expected-type propagation, imported aliases, traits, buffers, pointers, and native binary exit 55, reusable std language contract modules `lib/language_core.ns` and `lib/language_ops.ns` consumed through `std=workspace` with std galaxy auto-injection and native binary exit 55, CLI-shaped std language report consumer combining those contracts with StdTextContracts and StdIoContracts while writing a real stdout report with native exit 0, std language report-file consumer combining the same language contracts with StdReportContracts while writing an argv-selected report file plus stdout with native exit 0, std language workflow consumer combining StdLanguageOps.build_report with a two-step host command workflow through StdCliContracts and native exit 0, std language build-pipeline consumer extending that route into a four-stage prepare/check/compile/package gate through StdCliContracts.build_pipeline_total with native exit 0, larger cli_build_pipeline consumer carrying the auto-injected language gate through NIR/YIR/LLVM and native exit 0 without deferred lowering, scheduler-backed zero/unary/binary i64 async thunks now share one normalized runtime packet and cover completed, timed-out, and cancelled native branches, including recursive binary thunk execution with native exit 14, recursive scalar-leaf struct tasks now encode complete nested layout trees, flatten declaration-ordered leaves into one self-describing scalar/blob slot allocation, and reconstruct nested field SSA through await, direct join, and TaskResult paths with mixed bool/integer/float/String native exit 37; String leaves copy UTF-8 bytes into shape-tokened owned blobs, re-intern on take, and are released by the aggregate drop hook; the native text boundary accepts valid multibyte UTF-8 and rejects overlong, surrogate, truncated, and out-of-range encodings; copy_bytes(ref Buffer) now creates an async-safe Bytes value, lowers to cpu.copy_buffer_owned, and interpreted YIR proves deep-copy independence after source mutation; aggregate finish is transactional and rolls back attached blobs on unset, duplicate, or invalid slots; NuisSchedulerOwnedBlobV1 deep-copies borrowed bytes, requires a GLM token, and crosses scheduler take/cancel paths through validated move/drop hooks; null owned payloads enter Failed(4), task_failed observes that terminal state, a compiled C harness proves the runtime transition, and native timeout/cancel paths prove the deferred aggregate helper never executes; straight-line Bytes locals now receive compiler-synthesized reverse-order cleanup after return-value evaluation while explicit drops and returned aggregate transfers remain exactly once; dynamic same-owner Bytes return branches lower through GLM-typed cpu.select_owned_bytes and a native LLVM ptr select with one-copy/one-drop accounting; return-producing if branches with nested extern-call comparisons now lower through compare_call_result into real guard_host_call_return LLVM blocks, and the persistent Nuis provider worker proves the unselected reply call is not executed; run-artifact JSON readiness assertions, explicit void-main return lowering, report-file main-return runtime coverage, and unconstrained Result.Ok/Err constructor diagnostics have staged CLI/IR/runtime coverage",
        next_step: "keep the completed alpha language bootstrap surface regression-stable while projected and task-carried address ownership advance as post-closure capabilities",
        blocker: "none for the current alpha language bootstrap scope; effectful return-producing if branches now preserve host-call control dependence, while projected and task-carried pointer ownership remain intentionally closed rather than silently weakening GLM",
        next_action: "route further pointer transport through explicit address-kind and nullable metadata while the tensor advances to the next bootstrap-critical coordinate",
        validation_command: "cargo test -q -p nuisc tests_owned_pointer_select && cargo test -q -p nuisc owned_pointer_transfer && cargo test -q -p nuisc --test effectful_if_compile && cargo test -q -p yir-core branch_effect && cargo test -q -p yir-domain-cpu branch_effect && cargo test -q -p yir-exec && cargo test -q -p yir-lower-llvm && cargo test -q -p nuis --test owned_pointer_select_smoke && cargo test -q -p nuis --test branch_effect_result_smoke && cargo check -q -p nuisc",
        expected_artifact: "language bootstrap smoke covers combined generic Result/buffer/lambda helpers, Err fallback, partial expected-type Ok propagation, match/if edge cases, project-source no-annotation try/await Result HOF inference, runnable Ok-path plus async/HOF Err-path, direct `compute(0)` true-`?` Err binary output, chained try/await Result HOF binary output with dynamic helper seeds, std-style dynamic Result/Buffer/lambda/trait-bound/pointer bootstrap binary exit 59, std-style import-boundary bootstrap binary exit 59 with imported generic Result/HOF helpers, inferred imported result_map and Result helper constructor generic arguments, helper-local trait-bound bump, three-module package-boundary bootstrap binary exit 55 with helper-to-helper HOF templates, partial expected-type propagation, imported aliases, traits, buffers, pointers, and native binary exit 55, reusable std language contract modules `lib/language_core.ns` and `lib/language_ops.ns` consumed through `std=workspace` with std galaxy auto-injection and native binary exit 55, CLI-shaped std language report consumer combining those contracts with StdTextContracts and StdIoContracts while writing a real stdout report with native exit 0, std language report-file consumer combining the same language contracts with StdReportContracts while writing an argv-selected report file plus stdout with native exit 0, std language workflow two-step command workflow exit 0 through language/cli std contracts, std language build-pipeline four-stage command pipeline exit 0 through StdCliContracts, the larger cli_build_pipeline language gate preserves auto-injected imports plus native NIR/YIR/LLVM execution without deferred notes, std_language_task_cli stdout exit 0 through language/task std contracts with no task intrinsic deferred-lowering notes, project import/module reports, no LLVM deferred lowering for dynamic language std paths, effectful nested if comparison emits compare_call_result with branch-local host invocation, run-artifact readiness evidence, constructor inference diagnostics, and address-kind/nullable owned pointer selection across Node and Buffer with native exit 78",
    },
    DevTensorCell {
        architecture: "native-binary-system",
        module: "nsb-nsld",
        function: "self-owned-binary-assembly",
        status: "usable",
        progress: 100,
        bootstrap_critical: true,
        closure_role: "self-owned-native-binary",
        evidence: "Nsld container, object/image dry-runs, final executable pipeline, self-contained NSB image emission, container-metadata-first image payload layout, container-payload relocation patching, launcher dry-run checks, host entrypoint handoff stub emission, host-runner image/container probe, Nsld pipeline self-owned image status, entrypoint materialization status, Nuis frontdoor consumption, run-artifact first-payload launch evidence, nsdb-facing payload execution trace records, persisted nsdb payload handoff metadata, nsdb inspect payload execution events, nsdb replay-plan checkpoint source/query-result fields, nsld final-output consumption of nsdb replay summary checkpoint counts, workflow closure_summary replay-ready/replay-blocked gate selection, nsdb-yir-replay-control-v1 adds deterministic frame and breakpoint stops, nsdb-yir-breakpoint-predicate-v1 matches typed phase and entry fields, nsdb-yir-replay-resume-cursor-v1 advertises the exact successor, nsdb-yir-replay-resume-input-v1 requires immediate stopped/next neighbors before suffix consumption, payload handoff events remain preferred while hetero runtime trace records provide a deterministic metadata/device-dispatch fallback, --save-cursor persists nsdb-yir-replay-cursor-record-v1 only for resumable stops, --resume-cursor validates record/transcript/source/manifest contracts before exact suffix consumption, nuis-debugger-cursor-handoff-v1 mirrors cursor path/readiness/status and a cursor-specific next command through final-output and closure summaries without importing Nsdb types, nuis debug-resume validates that handoff before structured-argv Nsdb dispatch and forwards exact/typed breakpoint plus optional cursor-save controls, nuis debug-lineage-repair rejects missing lineage before dispatch and drives the Nsdb-owned idempotent archive/rebuild path through the shared structured-argv executable boundary, PixelMagic emits real data/kernel/shader checkpoints and proves stop-save, resume-stop-replace, then replacement-cursor resume through the Nuis route, multi-data-unit stitching and validation use handle-table ownership plus window ancestry instead of global pipe order, cursor persistence writes and syncs a same-directory temporary file, validates it with the normal loader, atomically renames it, syncs the directory on Unix, preserves the old cursor on validation failure, self-contained NSB smoke rejects terminal cursors with zero consumption, repair journal v3 independently verifies canonical retained-event hash chains in Nsdb and Nuis, v4 anchors a full rotated window with a monotonic generation plus evicted-prefix hash so front truncation fails closed, Nuis preserves validated rotation evidence through final-output JSON/text and closure JSON, a canonical formatting-independent repair_window_hash binds protocol/path/rotation/window head-tail/lineage evidence across those persistent surfaces, v5 persists the Nsdb producer claim while both Nsdb and Nuis independently reject digest mismatch, provider sample materialization now upserts an idempotent provider-device-completion into the shared payload stream while Nsld final-output preserves it, provider-only early handoffs overlay matching hetero runtime traces so official multi-frame replay retains unrelated domain frames, backend-neutral provider_family/output_contract/output_evidence fields survive independent Nuis parsing, the ordered Metal/CoreML completion set carries per-record plus collection hashes through Nsld final-output and Nuis closure JSON, new handoffs persist the set hash as a producer claim, Nsdb and Nuis independently classify it as verified/legacy-unclaimed/mismatch, mismatch blocks replay, closure readiness, and subsequent upserts, explicit digest negotiation binds handoff protocol plus declared total/provider counts and ordered record hashes, new producer records and set claims use independently implemented SHA-256 set-v4 verification that also binds a whitelist-validated authority contract and producer id, explicit SHA set-v3, FNV set-v2, and no-contract set-v1 artifacts remain readable, unknown digest or authority contracts fail closed, the near-limit Nsdb handoff, independent Nuis parser, and Nsld final-output report are split into focused integrity/data modules without changing their protocols, and optional Ed25519 producer claims now bind signature-required canonical set-v5 evidence to an external signing key, fail closed on malformed/untrusted/tampered signatures, verify through independent Nsdb/Nuis implementations, remain metadata-only through Nsld and closure surfaces, an external trust-registry-v1 now validates nonzero generations, key-ID hashes, unique entries, active/revoked rotation, and malformed registry fail-closed behavior through independent Nsdb/Nuis parsers, independent trust-anchor-v1 implementations atomically persist the highest generation plus full registry hash, reject rollback and same-generation forks, and serialize cross-process updates, lock-v1 owner tokens and timestamps recover crashed writers after a bounded lease, the fail-closed file-v1 backend selector reserves an OS-protected adapter boundary, and marker-v1 independently records initialization so a surviving protected marker detects anchor deletion while existing anchors migrate safely",
        next_step: "keep protected-file-v1 regression-stable while platform Keychain, TPM, or service-backed anchors evolve as post-alpha hardening adapters",
        blocker: "none for the current alpha native-binary closure scope; privileged compromise of both protected roots remains outside a filesystem-only adapter and requires a future OS-protected backend",
        next_action: "advance to the next bootstrap-critical coordinate while preserving independent Nsdb/Nuis protected-root verification and Nsld metadata neutrality",
        validation_command: "cargo test -q -p nsdb trust_anchor && cargo test -q -p nsdb trust_registry && cargo test -q -p nuis trust_anchor && cargo test -q -p nuis trust_registry && cargo test -q -p nsld final_executable_output_command_persists_nsdb_handoff_record && cargo test -q -p nuis closure_summary && cargo test -q -p nuis dev_tensor",
        expected_artifact: "provider completion readiness requires SHA-256 integrity, a valid Ed25519 signature, a versioned external trust registry, and an atomic highest-generation/hash anchor with stale-lock recovery, marker-v1 deletion detection, plus independent protected-file-v1 enforcement of two explicit absolute 0700 roots and 0600 files while Nsld remains a neutral metadata consumer",
    },
    DevTensorCell {
        architecture: "developer-system",
        module: "dev-tensor",
        function: "architecture-module-function-progress-model",
        status: "active",
        progress: 97,
        bootstrap_critical: true,
        closure_role: "bootstrap-progress-model",
        evidence: "tensor frontdoor maps progress by architecture, module, and function, summarizes through nuis status, runs drift checks over key docs/tests/frontdoor fields, locks the current alpha minor entry, repository README, and mainline router against version drift, exposes weakest-bootstrap guidance plus a protocolized nuis-dev-tensor-task-card-v1 surface, selects weakest and self-maintenance handoff cells through deterministic status-rank/progress/coordinate ordering instead of registration order, mirrors task-card protocol/source/status/ready/coordinate/action/command/expected artifact through nuis status, reports stdlib manifest-backed coordinate coverage, validates milestone-owned coordinate coverage against the Rust snapshot, derives expected coordinates from the milestone manifest with an explicit fallback, surfaces generated coordinate cache metadata without writing cache files, enforces the repository UTF-8/LF source-text contract through the mainline gate, exposes self-maintenance handoff fields, and validates the complete root/architecture/module/function projection through nuis-dev-tensor-hierarchy-v1 with recursive path, level, aggregate, weakest-child, uniqueness, and leaf-to-cell invariants mirrored through dev-tensor JSON/text and nuis status",
        next_step: "drive the handoff coordinate from the ready task-card protocol while keeping hierarchy validation clean and new linker/stdlib coordinates registered as they land",
        blocker: "three-axis recursive hierarchy integrity, status-aware deterministic navigation, task-card derivation, and self-maintenance handoff are protocolized and status-visible; arbitrary-depth or federated project hierarchy extensions remain future protocol work",
        next_action: "continue mainline closure work from the ready nuis-dev-tensor-task-card-v1 handoff coordinate",
        validation_command: "python3 scripts/check-text-encoding.py && cargo test -q -p nuis dev_tensor",
        expected_artifact: "dev-tensor reports milestone-derived coordinate cache metadata, a clean nuis-dev-tensor-hierarchy-v1 recursive validation report, weakest task-card protocol/source/status/ready/coordinate, status-rank/progress/path priority reason, action, validation command, expected artifact, deterministic handoff mode/coordinate/action/command/expected artifact independent of cell registration order, mirrors hierarchy and actionable task-card fields through nuis status, and the mainline gate rejects source-text encoding drift",
    },
];

pub(crate) const DEV_TENSOR_EXPECTED_COORDINATES: &[DevTensorExpectedCoordinate] = &[
    DevTensorExpectedCoordinate {
        architecture: "compiler-frontdoor",
        module: "nuis-cli",
        function: "workflow-and-project-orientation",
        milestone: "alpha-frontdoor",
        required: true,
    },
    DevTensorExpectedCoordinate {
        architecture: "compiler-frontdoor",
        module: "nuis-cli",
        function: "artifact-runtime-closure",
        milestone: "alpha-frontdoor",
        required: true,
    },
    DevTensorExpectedCoordinate {
        architecture: "linker-toolchain",
        module: "nsld",
        function: "artifact-chain-drive",
        milestone: "alpha-linker",
        required: true,
    },
    DevTensorExpectedCoordinate {
        architecture: "linker-toolchain",
        module: "nsld",
        function: "final-output-boundary",
        milestone: "alpha-linker",
        required: true,
    },
    DevTensorExpectedCoordinate {
        architecture: "heterogeneous-runtime",
        module: "nustar",
        function: "registered-domain-contracts",
        milestone: "alpha-heterogeneous",
        required: true,
    },
    DevTensorExpectedCoordinate {
        architecture: "standard-library",
        module: "std",
        function: "host-io-filesystem-text",
        milestone: "alpha-stdlib",
        required: true,
    },
    DevTensorExpectedCoordinate {
        architecture: "standard-library",
        module: "pixelmagic",
        function: "image-processing-lane",
        milestone: "alpha-official-galaxy",
        required: false,
    },
    DevTensorExpectedCoordinate {
        architecture: "standard-library",
        module: "witsage",
        function: "classical-ml-lane",
        milestone: "alpha-official-galaxy",
        required: false,
    },
    DevTensorExpectedCoordinate {
        architecture: "language-core",
        module: "nuisc",
        function: "type-control-flow-generics",
        milestone: "alpha-language-core",
        required: true,
    },
    DevTensorExpectedCoordinate {
        architecture: "native-binary-system",
        module: "nsb-nsld",
        function: "self-owned-binary-assembly",
        milestone: "alpha-native-binary",
        required: true,
    },
    DevTensorExpectedCoordinate {
        architecture: "developer-system",
        module: "dev-tensor",
        function: "architecture-module-function-progress-model",
        milestone: "alpha-governance",
        required: true,
    },
];
