use crate::dev_tensor_drift::DevTensorDriftCheckSpec;

pub(super) const CHECKS: &[DevTensorDriftCheckSpec] = &[
    DevTensorDriftCheckSpec {
        id: "native-typed-helper-scalar-layout-admission",
        path: "crates/yir-lower-llvm/src/native_session/aggregates.rs",
        required_patterns: &[
            "scalar_value_layout(encoded)",
            "scalar_value_layout(&node.op.args[1])",
            "layout.type_name != result.ty",
            "super::ScalarStateLayout::parse(encoded)?",
            "iteration carry validation remain independent of callback registration",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-typed-helper-execution-evidence",
        path: "tools/nuisc/tests/native_application_bridge/typed_helper_values.rs",
        required_patterns: &[
            "typed_nested_helpers_execute_independent_snapshots_without_owned_allocations",
            "for slots in [1, 6, 64]",
            "emit_registered_with_work_limits",
            "multi_execution::ALLOCATION_PROBE",
            "state_words(reference.state()), output",
            "function.body_nodes.reverse()",
            "ordinary.contains(\"define i64 @nuis_fn_packet(\")",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-typed-helper-admission-evidence",
        path: "tools/nuisc/tests/native_application_bridge/typed_helper_admission.rs",
        required_patterns: &[
            "typed_helper_calls_require_exact_nested_layouts_and_scalar_arguments",
            "typed_helper_values_reject_spoofed_nested_values_and_hidden_effects",
            "typed_helper_early_returns_keep_fallible_suffix_after_guard",
            "mixed_nested_local_rebinding_uses_guarded_native_value_returns",
            "slot bounds",
            "maximum depth",
            "does not admit cpu.print",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-typed-helper-frontdoor-restoration-evidence",
        path: "tools/nuis/tests/native_session_workflow.rs",
        required_patterns: &[
            "native_typed_helper_values_build_cache_and_standalone_relocation",
            "native_typed_local_rebinding_build_cache_and_standalone_relocation",
            "for helper in [\"relay_state\", \"finish\"]",
            "source == CONTROL_COMPOSITION_SOURCE || typed_helper_values",
            "fs::read_to_string(relocated.join(format!(\"{stem}.ll\"))).unwrap()",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-typed-helper-guard-budget-evidence",
        path: "tools/nuisc/tests/native_application_bridge/typed_helper_guards.rs",
        required_patterns: &[
            "typed_helper_guards_preserve_lazy_traps_shared_entries_and_output_sentinels",
            "(0, i64::MIN, -1, required, None)",
            "(0, 10, 2, required - 1, None)",
            "check_guards(SOURCE, 3, false)",
            "check_guards(&source, 5, false)",
            "check_guards(&unused, 5, true)",
            "(2, 7, 0, 0, None)",
            "words.unwrap_or_else(|| vec![-700; 5])",
            "run.status.signal()",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-scalar-layout-unique-nested-siblings",
        path: "crates/yir-core/src/native_scalar_session.rs",
        required_patterns: &[
            "fields.len() > MAX_SCALAR_SLOTS",
            "if !names.insert(name)",
            "state contains duplicate field names",
            "S{nested:N{x:A{a:i64};x:B{b:bool}}}",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-typed-helper-test-registration",
        path: "tools/nuisc/tests/native_application_bridge.rs",
        required_patterns: &[
            "mod typed_helper_values;",
            "mod typed_helper_admission;",
            "mod typed_helper_guards;",
            "mod typed_local_values;",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-scalar-value-return-contract",
        path: "docs/reference/nuis-native-scalar-value-returns-v1.md",
        required_patterns: &[
            "Callback and helper admission remain distinct",
            "Scoped iteration calls retain their separate flat-i64 carry schema",
            "Matching local bindings and rebindings now admit mixed/nested scalar records",
            "full 64-leaf capture plus a separate predicate needs 65 helper arguments",
            "Ordinary LLVM emission, resource aggregates, external FFI and task thunks retain",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-flat-value-private-return-plan",
        path: "crates/yir-lower-llvm/src/native_session/aggregate_values.rs",
        required_patterns: &[
            "super::aggregates::scalar_value_layout(encoded)?",
            "format!(\"[{} x i64]\", self.slots)",
            "extractvalue {ty} {returned}, {slot}",
            "insertvalue {ty} {aggregate}, i64 {field}, {index}",
            "materialize_owned_value",
            "guard_return_struct_cont",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-value-root-helper-admission-separation",
        path: "crates/yir-lower-llvm/src/lib.rs",
        required_patterns: &[
            "let native_value_return = if require_scalar_values",
            "if native_roots.contains(&function_name.as_str())",
            "native_session::aggregate_values::NativeValueReturn::callback",
            "native_session::aggregate_values::NativeValueReturn::helper",
            "helper_signature.native_value_return.as_ref()",
            "helper_signature.llvm_return_type()",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-flat-value-loop-snapshots",
        path: "crates/yir-lower-llvm/src/loop_owned_struct_lowering.rs",
        required_patterns: &[
            "native_value_return: signature.native_value_return.clone()",
            "returns.unpack(result, body, next_reg)",
            "unpack_immediate_owned_struct(result, &self.template, body, next_reg)",
            "Check the private control slot before committing any of the returned carries",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-flat-value-layout-unit-evidence",
        path: "crates/yir-lower-llvm/src/native_session/aggregate_values/tests.rs",
        required_patterns: &[
            "value_return_requires_unique_bounded_scalar_fields",
            "value_returns_keep_declared_field_order_and_guarded_packing",
            "value_returns_reject_nominal_kind_field_and_local_layout_drift",
            "unpack_materializes_independent_named_scalar_values",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-flat-value-execution-evidence",
        path: "tools/nuisc/tests/native_application_bridge/aggregate_values.rs",
        required_patterns: &[
            "native_returns_are_values_while_ordinary_abi_stays_owned",
            "for slots in [1, 2, 7, 64]",
            "multi_execution::ALLOCATION_PROBE",
            "expected.extend([0, value, 0, 0])",
            "call [1 x i64] @nuis_fn_stop(",
            "ApplicationSession::open_registered",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-flat-value-documentation",
        path: "docs/reference/nuis-native-scalar-session-bridge-v1.md",
        required_patterns: &[
            "Native Flat Value Transport",
            "from 13 allocations to 1",
            "Selection happens after native admission, with separate helper and callback checks",
            "Native Callback Value Transport",
            "Reference State Normalization",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-flat-value-tensor-evidence",
        path: "tools/nuis/src/dev_tensor_data.rs",
        required_patterns: &[
            "Native callback roots now use allocation-free LLVM value returns",
            "zero aggregate allocations/drops",
            "Reference callback state binding now follows registered field paths",
            "reduce guarded local helper capture pressure at the 64-argument boundary",
            "Native scalar helpers now admit bounded mixed/nested scalar return layouts",
            "The mixed/nested helper CLI fixture now passes build/run-artifact",
            "Guarded local value selections now close the ns-nova image-session lowering gap",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-callback-value-shared-layout-and-bit-packing",
        path: "crates/yir-lower-llvm/src/native_session/aggregate_values.rs",
        required_patterns: &[
            "super::ScalarStateLayout::parse(encoded)?",
            "slots: state.fields().len()",
            "crate::task_owned_payload::pack_scalar(value, body, next_reg)",
            "crate::task_owned_payload::unpack_scalar(&word, template, body, next_reg)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-callback-value-wrapper-publication",
        path: "crates/yir-lower-llvm/src/native_session/emit.rs",
        required_patterns: &[
            "%returned = call [{slots} x i64] @nuis_fn_{}",
            "%result{index} = extractvalue [{slots} x i64] %returned, {index}",
            "store i64 %result{index}, ptr %output_ptr{index}, align 1",
            "load i64, ptr %input_ptr{index}, align 1",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-callback-value-unit-evidence",
        path: "crates/yir-lower-llvm/src/native_session/aggregate_values/tests/callback.rs",
        required_patterns: &[
            "callback_and_helper_value_plans_share_bounded_scalar_layouts",
            "callback_value_plan_preserves_typed_nested_snapshots_and_guarded_bits",
            "for count in [0, 1, 64, 65]",
            "NativeValueReturn::helper(&layout).is_ok()",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-callback-value-overlap-and-reference-parity-evidence",
        path: "tools/nuisc/tests/native_application_bridge/callback_values.rs",
        required_patterns: &[
            "callback_values_preserve_nested_bits_overlap_and_failure_sentinels_without_allocating",
            "for slots in [1, 6, 64]",
            "[(1, 1), (1, 2), (2, 1), (1, slots + 2)]",
            "Check the entire backing region",
            "state_words(reference.state()), advanced",
            "reference.event(vec![]).unwrap()",
            "reference.close(vec![]).unwrap().unwrap()",
            "ApplicationSession::open_registered",
            "(\"probe_allocs\", 0)",
            "(\"probe_drops\", 0)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-callback-value-frontdoor-evidence",
        path: "tools/nuis/tests/native_session_workflow.rs",
        required_patterns: &[
            "llvm.matches(\"%returned = call [6 x i64]\").count(), 3",
            "line.contains(\"call \") && line.contains(\"@nuis_scheduler_owned_aggregate_\")",
            "functions <= 51",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "reference-state-named-field-normalization",
        path: "crates/yir-runtime-host/src/application_session/state_shape.rs",
        required_patterns: &[
            "const MAX_STATE_DEPTH: usize = 64;",
            "fn bind_layout",
            "supplied.insert(name, field).is_some()",
            "supplied.remove(name).ok_or_else(mismatch)?",
            "child.normalize(value)?",
            "kind.pack(&value)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "reference-state-publication-boundary",
        path: "crates/yir-runtime-host/src/application_session.rs",
        required_patterns: &[
            "let state = boundary.normalize_state(opened.value)?;",
            "invocation.value = self.boundary.normalize_state(invocation.value)?;",
            "self.state = invocation.value;",
            "self.failures.record(ApplicationFailureKind::Callback);",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "reference-state-shape-validation-evidence",
        path: "crates/yir-runtime-host/src/application_session/state_shape/tests.rs",
        required_patterns: &[
            "reorders_named_fields_at_every_depth_and_is_idempotent",
            "preserves_exact_scalar_bits_without_coercion",
            "rejects_missing_extra_duplicate_and_spoofed_fields",
            "rejects_wrong_nominal_types_and_resource_or_scalar_kind_substitution",
            "metadata_must_agree_across_callbacks_including_nested_nominal_identity",
            "metadata_free_yir_keeps_its_signature_only_nested_boundary",
            "reference_states_are_not_limited_to_native_slot_capacity",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "reference-state-lifecycle-and-source-order-evidence",
        path: "tools/nuisc/tests/native_application_bridge/reference_state.rs",
        required_patterns: &[
            "reference_state_normalization_preserves_source_effect_order_for_every_callback",
            "field_effect_order_includes_nested_call_arguments",
            "SOURCE.replace(\"@noinline \", \"\")",
            "malformed_event_state_keeps_last_accepted_state_and_allows_one_cleanup",
            "malformed_close_state_is_terminal_and_does_not_publish_partial_state",
            "state_normalization_does_not_retry_fuel_exhaustion",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "named-constructor-field-effects-ordered",
        path: "tools/nuisc/src/lowering/core_exprs.rs",
        required_patterns: &[
            "for (field_name, field_expr) in fields",
            "let lowered = lower_expr(field_expr, state, bindings)?;",
            "super::body_lowering::chain_nonpure_expr_stmt(field_expr, &lowered, state);",
            "super::edge_helpers::order_emitted_roots_after(",
            "args_out.push(format!(\"{field_name}={lowered}\"));",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "guarded-local-value-extraction",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_values.rs",
        required_patterns: &[
            "control_values::value_type(value, scope, self.catalog, self.layouts)?",
            "yes.name == no.name && yes.ty == no.ty && yes.constant == no.constant",
            "params.extend(captured_params(yes.inputs, scope));",
            "Branch calls, projections and arithmetic stay inside the helper",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "guarded-local-value-lowering-registration",
        path: "tools/nuisc/src/lowering/buffer_loop_outline.rs",
        required_patterns: &[
            "conditional_values::outline(module, &value_catalog, &value_layouts, &mut names)",
            "scalar_helpers::collect_typed_values(module, &value_layouts, &control_catalog)",
            "catalog = scalar_helpers::collect(module);",
            "control_catalog = scalar_helpers::collect_with_layouts(module, &layouts);",
            "scalar_control::outline(",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "guarded-local-value-source-regressions",
        path: "tools/nuisc/src/lowering/tests_branch_helpers/conditional_values.rs",
        required_patterns: &[
            "fallible_local_value_in_effectful_function_is_selected_before_evaluation",
            "selected_local_values_keep_checked_failures_even_when_unused",
            "nested_local_values_capture_rebindings_and_evaluate_effectful_predicate_once",
            "fallible_local_selection_does_not_admit_effectful_arms",
            "one_sided_checked_rebinding_keeps_the_existing_outer_value",
            "mixed_nested_local_selection_keeps_snapshots_and_effectful_predicate_once",
            "typed_literal_narrowing_emits_wrapped_i32_constants_without_cast_instructions",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "guarded-local-value-native-regressions",
        path: "tools/nuisc/tests/control_flow_syntax_native/conditional_values.rs",
        required_patterns: &[
            "guarded_local_values_run_in_effectful_native_functions_and_buffer_loops",
            "native_local_value_failures_are_selected_not_speculated_or_discarded",
            "nested_native_local_selections_preserve_captures_and_nominal_values",
            "mixed_nested_guarded_values_run_with_the_ordinary_owned_abi",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "guarded-local-value-image-session-evidence",
        path: "tools/nuisc/tests/ns_nova_application_session.rs",
        required_patterns: &[
            "compiled_window_selection_skips_ignored_events_and_matches_image_inputs",
            "trace.presented_frames[0], expected[ordinal]",
            "trace.provider_completion_witnesses, witnesses",
            "function.body_nodes.reverse()",
            "compiled_nuis_image_state_survives_independent_events_without_main_replay",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "guarded-typed-value-layout-profile",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/control_values/layouts.rs",
        required_patterns: &[
            "trait ValueLayouts",
            "impl ValueLayouts for FlatLayouts",
            "impl ValueLayouts for TypedLayouts",
            "while let Some(name) = ready.pop_first()",
            "depth > 64 || (nested && nodes > 4096)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "guarded-typed-value-source-boundaries",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/control_values/typed_tests.rs",
        required_patterns: &[
            "typed_values_reuse_flat_dependencies_without_admitting_mixed_loop_carries_or_effects",
            "typed_layouts_reject_cycles_resources_empty_and_duplicate_fields_transitively",
            "typed_constructors_require_exact_leaf_types_unique_fields_and_nominal_records",
            "typed_layouts_bound_neutral_initializer_expansion_before_materializing_a_type_dag",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "guarded-typed-value-native-evidence",
        path: "tools/nuisc/tests/native_application_bridge/typed_local_values.rs",
        required_patterns: &[
            "typed_local_choices_and_one_sided_rebindings_preserve_nested_snapshots_and_bits",
            "for slots in [1, 6, 63]",
            "typed_local_full_record_capture_keeps_native_argument_bounds_explicit",
            "function/argument bounds",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "guarded-typed-neutral-value-validation",
        path: "tools/nuisc/src/lowering/direct_calls/control_boundaries.rs",
        required_patterns: &[
            "is_neutral_guard_seed(ty, default, &state.struct_defs)",
            "nested_guard_zeros_require_exact_types_and_never_evaluate_work",
            "fields.iter().zip(&definition.fields)",
            "!seen.insert(name)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "guarded-i32-literal-constant-lowering",
        path: "tools/nuisc/src/lowering/core_exprs_scalars.rs",
        required_patterns: &[
            "if let NirExpr::Int(value) = value",
            "instruction: \"const_i32\".to_owned()",
            "(*value as i32).to_string()",
        ],
    },
];
