use crate::dev_tensor_drift::DevTensorDriftCheckSpec;

pub(super) const CHECKS: &[DevTensorDriftCheckSpec] = &[
    DevTensorDriftCheckSpec {
        id: "native-literal-print-build-flat-registration",
        path: "tools/nuis/src/dev_tensor_drift_data_native_iteration_calls.rs",
        required_patterns: &[
            "mod literal_print_build;",
            "literal_print_build::CHECKS,",
            ".flatten()",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-literal-print-build-canonical-bounded-portable-token",
        path: "crates/yir-lower-llvm/src/native_session/build_policy.rs",
        required_patterns: &[
            "nuis-native-literal-print-build-policy-v1",
            "MAX_BUILD_POLICY_SITE_BYTES: usize = 256",
            "MAX_BUILD_POLICY_TOKEN_BYTES: usize = 33_000",
            "index >= MAX_LITERAL_PRINT_SITES",
            "policy.token() != token",
            "native_session_literal_print_bound",
            "u128::from(self.helper_entry_limit)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-literal-print-build-token-boundary-regressions",
        path: "crates/yir-lower-llvm/src/native_session/build_policy.rs",
        required_patterns: &[
            "build_policy_token_is_sorted_bounded_utf8_and_exact",
            "build_policy_token_rejects_aliases_excess_duplicate_and_malformed_sites",
            "u64::MAX",
            "MAX_BUILD_POLICY_TOKEN_BYTES + 1",
            "v1.0.1.7a.61",
            "v1.0.1.61.61",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-literal-print-build-separate-mode-and-exact-checkpoint",
        path: "tools/nuisc/src/aot_native_session.rs",
        required_patterns: &[
            "native-session-policy-aot-bundle:",
            "literal_print_packaging_mode",
            "Some(policy) => policy.emit(module, id)",
            "None => yir_lower_llvm::native_session::emit_registered",
            "verify_checkpoint_for_packaging_mode",
            "bridge.llvm_ir != llvm_ir",
            "unexpected policy claim",
            "values != [expected.as_str()]",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-literal-print-build-compilation-and-cache-mode-identity",
        path: "tools/nuisc/src/command_compile.rs",
        required_patterns: &[
            "aot-host-v1:",
            "requested_packaging_mode.unwrap()",
            "crate::aot_native_session::emit_for_packaging_mode",
            "mode != manifest.packaging_mode",
            "cached AOT packaging does not match",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-literal-print-build-independent-packer-selection",
        path: "tools/nuisc/src/aot_native_runner.rs",
        required_patterns: &[
            "build_policy(packaging_mode)?",
            "--native-literal-print-policy",
            ".arg(policy.token())",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-literal-print-build-packer-explicit-option-admission",
        path: "tools/yir-pack-aot/src/host_application_script.rs",
        required_patterns: &[
            "pub struct NativePackagingProfile",
            "LiteralPrintBuildPolicy::parse",
            "policy.is_some() && native.is_none()",
            "requires --native-session",
            "unsupported or duplicate packaging option",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-literal-print-build-packer-rechecks-before-linking",
        path: "tools/yir-pack-aot/src/host_native_session.rs",
        required_patterns: &[
            "Some(policy) => policy.emit(module, id)?",
            "None => emit_registered(module, id)?",
            "let runtime = ensure_runtime_host_staticlib_built()?",
            "policy.bundle_claims()",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-literal-print-build-linked-opt-in-i64-runtime",
        path: "tools/yir-pack-aot/src/host_native_session/llvm.rs",
        required_patterns: &[
            "literal_print_runtime(!bridge.literal_print_sites.is_empty())",
            "define void @nuis_debug_print_i64(i64 %value)",
            "@printf(ptr @native_literal_print_format, i64 %value)",
            "native_literal_print_host_runtime_is_opt_in_and_i64_only",
            "literal_print_runtime(false).is_empty()",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-literal-print-build-source-free-profile-schema",
        path: "tools/nuisc/src/aot_application_bundle.rs",
        required_patterns: &[
            "nuis-native-session-build-inputs-v2",
            "native-scalar-literal-print-llvm-v1",
            "nuis-native-session-build-inputs-v1",
            "native-scalar-llvm-v1",
            "checkpoint::verify(source, path, &inputs)?",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-literal-print-build-source-free-checkpoint-regeneration",
        path: "tools/nuisc/src/aot_application_checkpoint.rs",
        required_patterns: &[
            "application checkpoint YIR is not canonical",
            "crate::aot_native_session::verify_checkpoint_for_packaging_mode",
            "text(\"llvm_ir\")?",
            "text(\"application_bundle\")?",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-literal-print-build-verified-launch-without-runtime-grants",
        path: "tools/nuis/src/artifact_runtime_native_session.rs",
        required_patterns: &[
            "nuisc::aot::verify_build_manifest(manifest)?",
            "verify_checkpoint_for_packaging_mode",
            "&report.packaging_mode",
            "validate_native_application_script",
            "no fallback was attempted",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-literal-print-build-rehashed-tampering-and-source-boundaries",
        path: "tools/nuisc/src/aot_application_bundle_policy_tests.rs",
        required_patterns: &[
            "native_policy_inputs_bind_exact_limits_schema_and_checkpoint",
            "native_policy_inputs_reject_rehashed_missing_duplicate_changed_and_extra_claims",
            "native_pure_profile_rejects_policy_claims_without_implicit_grants",
            "native_policy_artifact_rechecks_exact_sites_literals_and_session_closure",
            "native_policy_build_does_not_admit_compound_selected_or_unordered_helper_prints",
            "row.fnv1a64 = fnv1a64_hex",
            "lacks dependency order",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-literal-print-build-real-cli-cache-and-source-free-execution",
        path: "tools/nuis/tests/native_session_workflow/literal_prints.rs",
        required_patterns: &[
            "native_literal_print_build_cache_and_source_free_materialization",
            "native_literal_print_build_profiles_never_inherit_cached_authority",
            "compile_cache: hit",
            "compile_cache: miss",
            "for cycle in 0..3",
            "prints.repeat(4)",
            "must reject before effects",
            "fs::remove_file(project.0.join(\"main.ns\"))",
            "SIGILL",
            "SIGTRAP",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-literal-print-build-contract-scope-and-no-attestation-claim",
        path: "docs/reference/nuis-native-literal-print-build-policy-v1.md",
        required_patterns: &[
            "native-session-policy-aot-bundle:",
            "33000 bytes per token",
            "not an elapsed-time",
            "not\npublisher authentication",
            "source-to-YIR order propagation",
            "not the default",
            "full-workspace acceptance",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-literal-print-build-complete-six-field-history",
        path: "tools/nuis/src/dev_tensor_data.rs",
        required_patterns: &[
            "Literal-print build policy follow-up:",
            "Previous literal-print policy checkpoint:",
            "Previous literal-print policy task checkpoint:",
            "Previous literal-print policy blocker checkpoint:",
            "Previous literal-print policy action checkpoint:",
            "Previous literal-print policy artifact checkpoint:",
            "Close source effectful-helper dependency order without implicit grants",
            "native_literal_print_build",
        ],
    },
];
