use crate::dev_tensor_drift::DevTensorDriftCheckSpec;

pub(crate) const DEV_TENSOR_RUNTIME_CURRENT_DRIFT_CHECKS: &[DevTensorDriftCheckSpec] = &[
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-data-model-v11-contract",
        path: "docs/reference/nuis-compiler-data-model-v11.toml",
        required_patterns: &[
            "nuis-compiler-data-model-v11",
            "nuis-compiler-data-model-v10",
            "surface.std.compiler-data-model.v11",
            "nuis-compiler-complete-aggregate-forwarding-v1",
            "boundary_count = 2",
            "reference_registry_identity = 1593840720",
            "reference_identity = 551151124",
            "status = \"stable\"",
            "progress = 100",
            "new_scalar_exports = 0",
            "expected_native_exit = 130",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-data-model-v11-forwarding-stdlib",
        path: "stdlib/std/lib/compiler_payload_registry.ns",
        required_patterns: &[
            "pub fn compiler_aggregate_arena_forward_checked",
            "expected_registry_identity: i64",
            "expected_arena_identity: i64",
            "pub fn compiler_aggregate_arena_forward",
            "forwarded_registry_identity",
            "forwarded_arena_identity",
            "return Result.Ok(forwarded)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-data-model-v11-native-forwarding",
        path: "examples/projects/tooling/bootstrap_compiler_data_model_demo/payload_registry_fixture.ns",
        required_patterns: &[
            "let forwarded: CompilerAggregateArena",
            "compiler_aggregate_arena_forward",
            "wrong_registry_error",
            "identity_after_wrong_registry",
            "wrong_registry_error != 3",
            "identity_after_wrong_registry != chunked_identity",
            "chunked_identity != 551151124",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-data-provider-inventory-v1-contract",
        path: "docs/reference/nuis-data-provider-inventory-v1.toml",
        required_patterns: &[
            "nuis-data-provider-inventory-v1",
            "nuis-provider-capability-record-v1",
            "fnv1a64:4e27319a33087b95",
            "data.cpu-memory.reference.v1",
            "priority-desc-provider-id-asc",
            "fnv1a64:a5de1600823540c6",
            "nuis-provider-capability-availability-v1",
            "execution.physical",
            "physical_dpu_claimed = false",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-ns-nova-application-lifecycle-v1-contract",
        path: "docs/reference/nuis-ns-nova-application-lifecycle-v1.toml",
        required_patterns: &[
            "nuis-ns-nova-application-lifecycle-v1",
            "progress = 99",
            "owned-state-transition",
            "abstract-monotonic-step",
            "nuis-yir-provider-physical-completion-v1",
            "provider-neutral-metal-fence-import-verified",
            "two-live-command-buffers-monotonic-verified",
            "three-frame-same-command-metal-raster-and-fence-verified",
            "pixelmagic-profile-module-bound-to-render-pass-verified",
            "bounded-wgsl-vertex-fragment-to-msl24-verified",
            "compiled-yir-to-content-addressed-msl-verified",
            "run-artifact-registration-resolved-verified",
            "descriptor-v2-vertex-fragment-identity-verified",
            "registered-request-through-nuis-worker-verified",
            "hash-bound-capability-fd-verified",
            "160x120-rgba8-worker-fence-verified",
            "function-table-bound-helper-and-aggregate-loop-verified",
            "last-structurally-presented-frame-only",
            "physical_fence_completion_claimed = true",
            "metal_physical_fence_observed = true",
            "host-auto-recommended",
            "window-and-fabric-boot-observed",
            "cross-domain-result-state-projection-verified",
            "three-frame-nuis-update-loop-verified",
            "provider-token-clock-root-native-tamper-rejection-verified",
            "registered-provider-post-return-receipt-verified",
            "kernel-provider-final-binary-verified",
            "worker-result-stream-yir-lifecycle-presentation-verified",
            "hash-bound-three-frame-rgba8-and-physical-fence-verified",
            "target-discovery-without-provider-preexecution-verified",
            "separate-process-three-live-draw-dispatches-and-replay-equivalence-verified",
            "child_driven_provider_dispatch = true",
            "three-frame-single-session-single-worker-monotonic-sequence-verified",
            "explicit-result-edge-cycle-guard-verified",
            "compiled-hit-hit-across-frame-dispatch-verified",
            "stable_interactive_loop_claimed = false",
            "conditional_present_lowering = true",
            "cross_domain_result_state_projection = true",
            "bounded_update_loop = true",
            "runtime_owned_result_handle = true",
            "provider_issued_completion_receipt = true",
            "receipt_identity_carried_in_application_state = true",
            "registered_provider_completion_witness = true",
            "provider_neutral_physical_completion_adapter = true",
            "metal_live_completion_clock = true",
            "physical_completion_required_policy = true",
            "physical_completion_gates_present = true",
            "structured_present_trace = true",
            "reference_function_table_execution = true",
            "nuis_native_receipt_validation = true",
            "live_backend_completion_clock = true",
            "compiled_inline_shader_module_binding = true",
            "canonical_wgsl_to_msl_raster_lowering = true",
            "same_command_gpu_frame_and_fence = true",
            "physical_gpu_frame_rasterization = true",
            "production_metal_raster_provider_registration = true",
            "automatic_project_render_codegen = true",
            "automatic_provider_request_projection = true",
            "multi_entry_code_asset_descriptor = true",
            "production_worker_result_presentation = true",
            "bounded_provider_result_stream = true",
            "single_runtime_result_target = true",
            "multi_target_provider_result_schedule = false",
            "provider_result_payload_tamper_rejection = true",
            "self_contained_host_runner_result_injection = false",
            "resource_bound_gpu_rasterization = false",
            "dynamic_cross_domain_present_predicate = false",
            "loop_carried_application_state = true",
            "aggregate_state_carry_status = \"recursive-scalar-aggregate-backedge-native-verified\"",
            "compiler_special_cases = 0",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-ns-nova-owned-app-runtime",
        path: "stdlib/ns-nova/lib/app_runtime.ns",
        required_patterns: &[
            "pub struct NovaAppState",
            "pub struct NovaFrameTransaction",
            "pub struct NovaFrameResultHandle",
            "last_completion_token",
            "last_completion_root",
            "completion_receipt_token",
            "completion_receipt_matches",
            "i64_xor",
            "provider_token: i64",
            "completion_root: i64",
            "pub fn open(",
            "pub fn begin_frame(",
            "pub fn capture_frame_result(",
            "pub fn frame_result_ready(",
            "pub fn submit_frame(",
            "pub fn commit_frame(",
            "pub fn close(",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-ns-nova-showcase-project",
        path: "examples/projects/domains/ns_nova_showcase/nuis.toml",
        required_patterns: &[
            "ns_nova_showcase",
            "ns-nova=workspace",
            "pixelmagic=workspace",
            "ns-nova:lib/app_runtime.ns",
            "cpu.Main -> shader.PixelMagicRenderSurface via data.FabricPlane",
            "official.shader:provider-sample=project-render",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-ns-nova-showcase-galaxy-package",
        path: "examples/projects/domains/ns_nova_showcase/galaxy.toml",
        required_patterns: &[
            "package_kind = \"nuis-framework\"",
            "framework = \"ns-nova\"",
            "project = \"nuis.toml\"",
            "\"ns-nova.toml\"",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-ns-nova-showcase-framework-profile",
        path: "examples/projects/domains/ns_nova_showcase/ns-nova.toml",
        required_patterns: &[
            "ns-nova-manifest-v1",
            "entry_cpu_unit = \"cpu.Main\"",
            "render_bridge_unit = \"data.FabricPlane\"",
            "render_surface_unit = \"shader.PixelMagicRenderSurface\"",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-ns-nova-showcase-regression",
        path: "tools/nuisc/src/project/tests/ns_nova_runtime.rs",
        required_patterns: &[
            "compiles_ns_nova_lifecycle_with_pixelmagic_rendering",
            "NovaAppRuntime.begin_frame",
            "NovaAppRuntime.capture_frame_result",
            "NovaAppRuntime.submit_frame",
            "PixelMagicRenderSurface",
            "inline_wgsl",
            "branch_effect",
            "present_frame",
            "present_requested",
            "projected shader.observe",
            "completion_token",
            "completion_clock",
            "completion_root",
            "provider-issued shader completion receipt",
            "loop_while_i64_effect",
            "render_showcase_frame",
            "render_pass.op.args.get(3)",
            "edge.from == inline_shader.name",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-shader-profile-inline-module-binding",
        path: "tools/nuisc/src/project/profile_refs.rs",
        required_patterns: &[
            "bind_shader_profile_modules",
            "ShaderBeginPass",
            "_profile_wgsl",
            "node.op.args.push(shader_module.clone())",
            "EdgeKind::Dep",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "yir-render-pass-inline-module-and-rgba8-frame",
        path: "crates/yir-core/src/value_types.rs",
        required_patterns: &[
            "pub shader_module: Option<InlineShaderModule>",
            "pub struct InlineShaderModule",
            "pub rgba8: Option<Vec<u8>>",
            "pub fn from_rgba8",
            "RGBA8 frame byte count",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "yir-host-rgba8-frame-export",
        path: "crates/yir-host-render/src/lib.rs",
        required_patterns: &[
            "if let Some(rgba8) = &frame.rgba8",
            "rasterize_rgba8",
            "pixels.extend_from_slice(&rgba[..3])",
            "rasterizes_rgba8_without_falling_back_to_glyph_rows",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "yir-shader-rgba8-overlay-fail-closed",
        path: "crates/yir-domain-shader/src/frame_surface.rs",
        required_patterns: &[
            "base.rgba8.is_some() || top.rgba8.is_some()",
            "shader.overlay does not yet support RGBA8 frame surfaces",
            "overlay_rejects_rgba8_frames_instead_of_returning_empty_rows",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "yir-shader-begin-pass-inline-module",
        path: "crates/yir-domain-shader/src/execute_core.rs",
        required_patterns: &[
            "let shader_module = node",
            "expect_inline_shader_module",
            "shader.begin_pass expects inline shader module value",
            "language: \"wgsl\".to_owned()",
            "symbol(\"source\")",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuisc-canonical-inline-wgsl-metal-raster-lowering",
        path: "tools/nuisc/src/shader_msl_render_emitter.rs",
        required_patterns: &[
            "LoweredMslRenderModule",
            "lower_canonical_inline_wgsl_render_for_profile",
            "does not yet support resource bindings",
            "canonical fullscreen WGSL vertex stage",
            "nuis-module-native-ir msl2.4",
            "vertex_id",
            "stage_in",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuisc-shader-render-codegen-table",
        path: "tools/nuisc/src/shader_render_codegen_table.rs",
        required_patterns: &[
            "nuis-shader-render-codegen-table-v1",
            "nuis-shader-render-code-asset-v1",
            "nuis-shader-render-pass-projection-v1",
            "table_from_compiled_project_yir",
            "shader.begin_pass",
            "lower_canonical_inline_wgsl_render_for_profile",
            "nuis.shader.project.",
            "source_fnv1a64",
            "unique_render_result_node",
            "result_node",
            "result_resource",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "yir-domain-result-state-projection",
        path: "crates/yir-lower-llvm/src/preclassified_lowering.rs",
        required_patterns: &[
            "lower_domain_result_observer_node",
            "YirResultRole::StateProbe",
            "YirResultRole::CompletionToken",
            "YirResultRole::CompletionClock",
            "YirResultRole::CompletionRoot",
            "LlvmValueRef::DomainResult",
            "payload remains {family}-provider-owned",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "yir-provider-completion-receipt-v1-contract",
        path: "crates/yir-core/src/result_receipt.rs",
        required_patterns: &[
            "nuis-yir-provider-completion-receipt-v1",
            "nuis-yir-provider-physical-completion-v1",
            "ProviderCompletionReceipt",
            "ProviderPhysicalCompletion",
            "ProviderCompletionClockKind",
            "begin_registered_provider_completion",
            "stage_provider_physical_completion",
            "finish_registered_provider_completion",
            "requires physical fence evidence",
            "issue_provider_completion_receipt",
            "provider_completion_receipt_root",
            "provider_completion_receipt_token",
            "project_provider_completion_receipt",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "yir-provider-completion-registration-policy",
        path: "crates/yir-core/src/registry.rs",
        required_patterns: &[
            "ProviderCompletionRegistration",
            "ProviderCompletionEvidencePolicy",
            "RuntimeOrderAllowed",
            "PhysicalFenceRequired",
            "physical_fence_required",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "yir-reference-function-execution-engine",
        path: "crates/yir-exec/src/execution_engine.rs",
        required_patterns: &[
            "execute_function",
            "execute_function_body",
            "try_execute_scoped_owned_struct_loop",
            "parse_loop_owned_struct_carry",
            "flatten_owned_struct",
            "rebuild_owned_struct",
            "MAX_FUNCTION_CALL_DEPTH",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "yir-reference-function-execution-regression",
        path: "crates/yir-exec/src/lib.rs",
        required_patterns: &[
            "registered_function_call_executes_with_bound_parameters",
            "scoped_owned_struct_loop_executes_helper_and_carries_result",
            "Some(&Value::Int(42))",
            "Some(&Value::Int(3))",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "yir-runtime-host-structured-present-gate",
        path: "crates/yir-runtime-host/src/lib.rs",
        required_patterns: &[
            "execute_module_source_with_registry",
            "render_trace_to_ppm_bytes",
            "presented_frames",
            "executed YIR graph did not present a frame",
            "renderer_requires_a_structurally_presented_frame",
            "render_module_to_ppm_bytes_with_provider_result_stream",
            "count_module_node_executions",
            "PROVIDER_RESULT_STREAM_ENV",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "yir-cpu-structured-present-record",
        path: "crates/yir-domain-cpu/src/branch_effect.rs",
        required_patterns: &["present_frame", "record_presented_frame"],
    },
    DevTensorDriftCheckSpec {
        id: "yir-shader-provider-physical-completion-registration",
        path: "crates/yir-domain-shader/src/lib.rs",
        required_patterns: &[
            "provider_completion_registration",
            "ProviderCompletionRegistration::new",
            "shader.clock.frame.v1",
            "begin_pass",
            "draw_instanced",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-metal-provider-physical-completion-adapter",
        path: "tools/nsdb/src/provider_runner_metal.rs",
        required_patterns: &[
            "PROVIDER_PHYSICAL_COMPLETION_CONTRACT",
            "completion_status",
            "completion_source_clock",
            "ProviderPhysicalCompletion::new",
            "physical_completion",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-metal-provider-live-physical-completion-regression",
        path: "tools/nsdb/src/provider_runner_metal_tests.rs",
        required_patterns: &[
            "executes_gray8_invert_on_the_system_metal_device",
            "apple.mach-continuous.v1",
            "metal.command-buffer.completed",
            "ProviderCompletionClockKind::PhysicalFence",
            "second.physical_completion.source_clock > first.physical_completion.source_clock",
            "changed its registered clock binding",
            "ns_nova_presents_a_registered_frame_after_real_metal_completion",
            "begin_witness.completion_clock, 5",
            "draw_witness.completion_clock, 6",
            "trace.presented_frames.len()",
            "Metal-backed NS Nova presentation must retain RGBA8 pixels",
            "assert_eq!(rgba8.len(), 160 * 120 * 4)",
            "ppm_header_len",
            "requires physical fence evidence",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-metal-rgba8-render-adapter",
        path: "tools/nsdb/src/provider_runner_metal_render.rs",
        required_patterns: &[
            "METAL_RGBA8_RENDER_CONTRACT",
            "execute_rgba8_render",
            "prepare_rgba8_render_worker_invocation",
            "execute_rgba8_render_asset",
            "Metal RGBA8 render dimensions must be positive",
            "checked_mul(height)",
            "execute_metal_platform",
            "TempMslSource",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-metal-rgba8-production-worker-route",
        path: "tools/nsdb/src/provider_execution_metal.rs",
        required_patterns: &[
            "render-rgba8",
            "prepare_rgba8_render_worker_invocation",
            "METAL_RGBA8_RENDER_CONTRACT",
            "provider-frame-rgba8",
            "verified MSL code asset capability",
            "image-2d-row-major:pixel-format=rgba8",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-shader-project-render-provider-projection",
        path: "tools/nuis/src/artifact_device_sample_shader_render.rs",
        required_patterns: &[
            "nuis-shader-render-provider-projection-v1",
            "nuis.domain.shader.render-codegen-table.toml",
            "select_compiled_code_asset_contribution",
            "nuis-provider-request-collection-v1",
            "nuis-provider-code-asset-descriptor-v2",
            "image-2d-row-major:pixel-format=rgba8",
            "source_yir_version",
            "nuis-provider-runtime-result-binding-v1",
            "runtime_result_node",
            "runtime_result_resource",
            "real-device",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-ns-nova-aot-metal-render-worker-regression",
        path: "tools/nuis/src/artifact_device_sample_shader_render_tests.rs",
        required_patterns: &[
            "executes_ns_nova_aot_render_projection_through_nuis_worker",
            "crate::handle_build",
            "crate::render_run_artifact_json",
            "nuis-provider-code-asset-descriptor-v2",
            "prepare_runtime_provider_results",
            "runtime_ipc_lifecycle_child",
            "child-yir-node-ipc",
            "frame_count = 3",
            "render_module_to_ppm_bytes_with_provider_result_stream",
            "payload drift must fail before presentation",
            "provider-frame-rgba8",
            "metal-command-buffer-completed",
            "runtime_dispatch_session_worker_count",
            "runtime_dispatch_session_request_sequences",
            "runtime_dispatch_session_adapter_cache_statuses",
            "runtime-session provider output should remain materializable",
            "verified MSL code asset capability",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-provider-runtime-result-stream",
        path: "tools/nsdb/src/provider_runtime_result_stream.rs",
        required_patterns: &[
            "nuis-provider-runtime-result-stream-v1",
            "ProviderRuntimeResultTarget",
            "ProviderPhysicalCompletion::parse",
            "stream_hash",
            "nuis.runtime.provider-result.",
            "rejected manifest protocol",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "yir-host-provider-runtime-result-consumer",
        path: "crates/yir-runtime-host/src/provider_result_stream.rs",
        required_patterns: &[
            "nuis-provider-runtime-result-stream-v1",
            "ProviderResultShaderMod",
            "ProviderResultSource",
            "physical_fence_required",
            "stage_provider_physical_completion",
            "provider runtime result stream is exhausted",
            "payload path is not output-relative",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-runtime-provider-result-preparation",
        path: "tools/nuis/src/artifact_runtime_provider_results.rs",
        required_patterns: &[
            "provider_runtime_result_targets",
            "find_source_yir",
            "source_yir_path",
            "currently requires exactly one target",
            "ipc::run_command",
            "child-yir-node-ipc",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "yir-provider-runtime-ipc-contract",
        path: "crates/yir-core/src/provider_runtime_ipc.rs",
        required_patterns: &[
            "nuis-yir-provider-runtime-ipc-v1",
            "MAX_DISPATCHES",
            "MAX_PAYLOAD_BYTES",
            "runtime IPC payload identity mismatch",
            "ProviderPhysicalCompletion::parse",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-child-driven-runtime-provider-session",
        path: "tools/nsdb/src/provider_runtime_ipc.rs",
        required_patterns: &[
            "serve_runtime_provider_session",
            "ProviderRuntimeDispatchSession::open",
            "runtime IPC request target or sequence mismatch",
            "session.close()",
            "Message::Closed(count)",
            "child-yir-node-ipc",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-child-runtime-ipc-transport",
        path: "tools/nuis/src/artifact_runtime_provider_ipc.rs",
        required_patterns: &[
            "configure_connection",
            "set_nonblocking(false)",
            "Shutdown::Both",
            "child.kill()",
            "mode(0o700)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-metal-rgba8-render-fence-source",
        path: "tools/nsdb/provider-runners/metal_rgba8_render.m",
        required_patterns: &[
            "MTLPixelFormatRGBA8Unorm",
            "drawPrimitives:MTLPrimitiveTypeTriangleStrip",
            "waitUntilCompleted",
            "MTLCommandBufferStatusCompleted",
            "getBytes:output.mutableBytes",
            "mach_continuous_time",
            "nuis-yir-provider-physical-completion-v1",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-metal-provider-physical-fence-source",
        path: "tools/nsdb/provider-runners/metal_gray8_unary.m",
        required_patterns: &[
            "waitUntilCompleted",
            "MTLCommandBufferStatusCompleted",
            "mach_continuous_time",
            "nuis-yir-provider-physical-completion-v1",
            "apple.mach-continuous.v1",
            "metal.command-buffer.completed",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-provider-physical-completion-graph-close",
        path: "tools/nsdb/src/provider_graph_output.rs",
        required_patterns: &[
            "physical_completion_from_summary",
            "PROVIDER_PHYSICAL_COMPLETION_CONTRACT",
            "physical-fence-observed",
            "physical-fence-and-worker-output-verified",
            "completion.to_wire()",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-provider-completion-receipt-native-regression",
        path: "tools/nuisc/tests/provider_completion_receipt_native.rs",
        required_patterns: &[
            "clocked_kernel_result_receipt_runs_as_native_binary",
            "kernel_completion_token",
            "kernel_completion_clock",
            "kernel_completion_root",
            "ns_nova_rejects_mismatched_provider_receipt_fields_natively",
            "assert_eq!(status.code(), Some(0))",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-ns-nova-registered-renderer-frame-export-regression",
        path: "tools/nuisc/tests/ns_nova_showcase_compile.rs",
        required_patterns: &[
            "builds_ns_nova_showcase_window_aot_bundle",
            "render_module_to_ppm_bytes",
            "registered Shader renderer should export the NS Nova frame",
            "P6\\n160 120\\n255\\n",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "yir-explicit-result-edge-dependency-guard",
        path: "crates/yir-syntax/src/lib.rs",
        required_patterns: &["explicit_edges", "explicit_edges.contains"],
    },
    DevTensorDriftCheckSpec {
        id: "yir-explicit-result-edge-dependency-regression",
        path: "crates/yir-syntax/tests/dependency_edges.rs",
        required_patterns: &[
            "does_not_infer_dependency_against_explicit_result_edge",
            "still_infers_mutual_argument_dependencies_without_explicit_edges",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-ns-nova-conditional-present-runtime",
        path: "crates/yir-domain-cpu/src/tests_branch_effect.rs",
        required_patterns: &[
            "branch_effect_presents_a_frame_only_when_selected",
            "BranchEffectAccess::ValueRead",
            "effect cpu.present_frame",
            "state.events.is_empty()",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-ns-nova-conditional-present-llvm",
        path: "crates/yir-lower-llvm/src/tests/branch_effect_tests.rs",
        required_patterns: &[
            "conditional_present_preserves_control_flow_at_the_host_adapter_boundary",
            "branch_effect_then",
            "branch_effect_else",
            "cpu.present_frame frame remains a host-adapter boundary",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuisc-provider-capability-registration-schema",
        path: "tools/nuisc/src/registry_provider_capability.rs",
        required_patterns: &[
            "nuis-provider-capability-record-v1",
            "NustarProviderCapabilityRegistration",
            "provider_capability_registrations",
            "six ordered fields",
            "strictly sorted and unique",
            "priority must be positive",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-data-provider-conformance-v1-contract",
        path: "docs/reference/nuis-data-provider-conformance-v1.toml",
        required_patterns: &[
            "nuis-data-provider-conformance-v1",
            "nuis-provider-conformance-capsule-v1",
            "nuis-provider-conformance-replay-v1",
            "fnv1a64:82270e31b99f2c0b",
            "fnv1a64:7ee93c8f8a4ae011",
            "execution_authority = \"conformance-only\"",
            "physical_execution_claimed = false",
            "grants_physical_certification = false",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-data-provider-conformance-replay",
        path: "tools/nsdb/src/provider_conformance_capsule.rs",
        required_patterns: &[
            "nuis-provider-conformance-capsule-v1",
            "nuis-provider-conformance-replay-v1",
            "data_reference_conformance_capsule",
            "replay_provider_conformance_capsule",
            "provider-conformance-replay:capsule-drift",
            "provider-conformance-replay:clock-order-invalid",
            "provider-conformance-replay:glm-release-missing",
            "provider-conformance-replay:physical-authority-forbidden",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nustar-data-provider-capability-registration",
        path: "nustar-packages/data.toml",
        required_patterns: &[
            "provider_capabilities",
            "data.cpu-memory.reference.v1",
            "data.host.bundle.v1",
            "clock.fabric-monotonic",
            "completion.verified",
            "execution.reference",
            "glm.owned-transfer",
            "memory.cpu",
            "movement.copy",
            "residency.host",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-provider-capability-aot-generator",
        path: "tools/nsdb/build.rs",
        required_patterns: &[
            "provider_capability_registrations",
            "canonical_capability_manifest",
            "nuis-provider-capability-manifest-v1",
            "PROVIDER_CAPABILITY_MANIFEST_HASH",
            "provider_capability_registry_generated.rs",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-provider-capability-selection",
        path: "tools/nsdb/src/provider_capability_registry.rs",
        required_patterns: &[
            "nuis-provider-capability-registry-v1",
            "nuis-provider-capability-selection-v1",
            "select_provider_capability",
            "canonical_requirements",
            "duplicate-requirement",
            "provider-capability-selection:unsupported",
            "provider-capability-selection:provider-unavailable",
            "provider_entry_is_available",
            "rhs.priority",
            "lhs.provider_id",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-cpu-memory-reference-execution",
        path: "tools/nsdb/src/provider_sample_execute_tests.rs",
        required_patterns: &[
            "executes_registered_native_worker_with_two_graph_outputs",
            "data.cpu-memory.reference.v1",
            "fnv1a64:4e27319a33087b95",
            "fnv1a64:01cb51b49b12a49e",
            "provider_capability_availability_status",
            "nuis-provider-completion-evidence-v1",
            "nuis-provider-glm-release-evidence-v1",
            "nuis-provider-completion-clock-v1",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-provider-conformance-completion-binding",
        path: "tools/nsdb/src/provider_completion_evidence.rs",
        required_patterns: &[
            "ProviderConformanceLifecycleEvidence",
            "completion_evidence_from_output",
            "render_completion_event_fields",
            "parse_completion_event_fields",
            "append_completion_hash_material",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-provider-conformance-lifecycle-gate",
        path: "tools/nsld/src/final_executable_output_conformance.rs",
        required_patterns: &[
            "validate_provider_conformance_evidence",
            "PROVIDER_CONFORMANCE_CAPSULE_CONTRACT",
            "PROVIDER_CONFORMANCE_REPLAY_CONTRACT",
            "PROVIDER_CONFORMANCE_EXECUTION_AUTHORITY",
            "physical-execution-claim-forbidden",
            "not-applicable-evidence-not-empty",
            "provider-family-mismatch",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-provider-conformance-final-output-projection",
        path: "tools/nsld/src/json_final_output_provider_completion.rs",
        required_patterns: &[
            "conformance_json",
            "capability_selection_hash",
            "capsule_hash",
            "replay_hash",
            "execution_authority",
            "physical_execution_claimed",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "run-artifact-host-runner-resolution",
        path: "tools/nuis/src/artifact_host_runner.rs",
        required_patterns: &[
            "resolve_nuis_host_runner_program",
            "nuis-host-runner",
            "NUIS_HOST_RUNNER",
        ],
    },
];
