use crate::dev_tensor_drift::DevTensorDriftCheckSpec;

pub(crate) const CHECKS: &[DevTensorDriftCheckSpec] = &[
    DevTensorDriftCheckSpec {
        id: "bounded-buffer-continue-admission",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/validation.rs",
        required_patterns: &[
            "control_flow::normalize(effects, scope, step)?",
            "writable.insert(normalized.running.clone())",
            "writable.extend(normalized.breaking.iter().cloned())",
            "normalized_effects.as_deref().unwrap_or(effects)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "bounded-buffer-continue-local-suffix",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/control_flow.rs",
        required_patterns: &[
            "__nuis_buffer_continue",
            "same_step(rewritten.last()?, step)",
            "index + 1 != body.len()",
            "body.insert(0, set_flag(&flag, 1))",
            "rewritten.push(set_flag(flag, 0))",
            "then_body: tail",
            "A child loop owns its control scope",
            "value == step",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "bounded-buffer-continue-execution",
        path: "tools/nuisc/tests/buffer_while/continues.rs",
        required_patterns: &[
            "guarded_continue_preserves_prefix_state_and_steps_once",
            "continue_unit_steps_do_not_wrap_at_integer_boundaries",
            "nested_and_sequential_continue_guards_snapshot_each_predicate_once",
            "continue_skips_suffix_reads_math_calls_and_nested_loop_bounds",
            "nested_continue_targets_only_its_own_loop_and_resets_each_iteration",
            "continue_rejects_missing_or_mismatched_steps_and_unsupported_exits",
            "continue_helpers_grow_linearly_and_keep_private_names_and_real_scalar_calls",
            "continue_effect_order_survives_yir_declaration_reordering",
            "continue_shares_session_fuel_without_leaking_private_or_failed_state",
            "let controls = 32",
            "state.fields.len(), 1",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "pixelmagic-guarded-continue-source",
        path: "stdlib/pixelmagic/lib/pixels.ns",
        required_patterns: &[
            "Finish red pixels early",
            "continue;",
            "let checksum: i64 = checksum + pixels[index]",
            "let index: i64 = index + 1",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "bounded-buffer-branch-carry-admission",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/validation.rs",
        required_patterns: &[
            "!header_inputs.contains(name)",
            "name != &prepared.binding_name",
            "!mutations.writable.contains(name)",
            "inputs.insert(name.clone())",
            "carries.push(name.clone())",
            "PreparedLoopCompare::Lt",
            "PreparedLoopCompare::Gt",
            "NirExpr::StoreAt",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "bounded-buffer-branch-state-projections",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/branches.rs",
        required_patterns: &[
            "Snapshot once",
            "scalar_carries::state_type",
            "scalar_carries::value",
            "inputs.extend(carries.iter().cloned())",
            "scalar_carries::projected_call",
            "NirStmt::Return(Some(returned.clone()))",
            "__nuis_branch_state",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "bounded-buffer-branch-pass-through-guard",
        path: "tools/nuisc/src/lowering/direct_calls/control_boundaries.rs",
        required_patterns: &[
            "is_pass_through_guard_seed",
            "i64_parameter",
            "fields.len() == definition.fields.len()",
            "type_name == &ty.name",
            "name == &field.name",
            "lower_guard_return",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "bounded-buffer-branch-carry-execution",
        path: "tools/nuisc/tests/buffer_while/branch_carries.rs",
        required_patterns: &[
            "branch_carries_preserve_untaken_and_zero_trip_seeds",
            "nested_branch_carries_merge_all_slots_and_preserve_sequential_rebindings",
            "branch_carry_predicate_is_snapshotted_before_state_and_buffer_updates",
            "branch_carry_traps_keep_source_order_before_and_after_writes",
            "branch_carries_reject_mutable_headers_non_i64_state_and_ownership_control",
            "branch_carries_share_callback_fuel_without_committing_failed_state",
            "branch_carries_keep_linear_helper_growth_and_generated_name_isolation",
            "branch_carries_feed_subsequent_loops",
            "let branches = 32",
            "completion_status().is_err()",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "pure-helper-analysis-expansion-budget",
        path: "tools/nuisc/src/lowering/loop_purity_inline_budget.rs",
        required_patterns: &[
            "MAX_INLINE_EXPR_NODES",
            "MAX_INLINE_EXPR_DEPTH",
            "checked_sub(cost)",
            "bounded_inline_substitution",
            "_ => return false",
            "inline_budget_counts_cast_depth_and_declines_unknown_shapes",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "pure-helper-analysis-expansion-evidence",
        path: "tools/nuisc/src/lowering/loop_purity_inline_tests.rs",
        required_patterns: &[
            "inline_collection_rejects_effectful_prefix_before_expansion",
            "inline_collection_bounds_pure_rebinding_expansion_without_losing_purity",
            "inline_collection_does_not_classify_effectful_return_as_pure",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "pixelmagic-branch-carry-native-evidence",
        path: "tools/nuisc/tests/pixelmagic_buffer_loop.rs",
        required_patterns: &[
            "real control boundary and branch-local count",
            "checkerboard_red_total",
            "row helpers must retain nested pixel loops",
            "checkerboard_row_start",
            "checkerboard_row_end",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "pixelmagic-branch-carry-packaged-evidence",
        path: "tools/nuis/tests/headless_image_loop.rs",
        required_patterns: &[
            "real control boundary and branch-local count",
            "checkerboard_red_total",
            "packaged row helpers must retain nested pixel loops",
            "checkerboard_row_start",
            "checkerboard_row_end",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "bounded-buffer-recursive-loop-admission",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/validation.rs",
        required_patterns: &[
            "protected.contains(&prepared.binding_name)",
            "protected.extend(header_inputs.iter().cloned())",
            "carries.retain(|name| scope.contains_key(name))",
            "&mutations.protected",
            "inputs.extend(plan.header_inputs)",
            ".filter(|name| plan.break_flag.as_ref() != Some(name))",
            ".chain([plan.induction])",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "bounded-buffer-recursive-loop-outlining",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/branches.rs",
        required_patterns: &[
            "validated nested loop",
            "outline_loop(",
            "carries.retain(|name| scope.contains_key(name))",
            "NirStmt::While { body, .. } => collect_bindings(body, names)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "bounded-buffer-recursive-loop-evidence",
        path: "tools/nuisc/tests/buffer_while/nested_loops.rs",
        required_patterns: &[
            "nested_buffer_loops_execute_real_helpers_and_reset_iteration_locals",
            "nested_loops_preserve_persistent_counters_and_support_scalar_only_children",
            "nested_descending_loops_and_outer_dependent_bounds_keep_exact_state",
            "branch_nested_loops_return_visible_locals_without_speculating_bounds",
            "nested_loop_traps_keep_source_order_across_loop_boundaries",
            "nested_loops_reject_ancestor_header_mutation_and_unsupported_control",
            "nested_loops_share_session_fuel_and_never_commit_failed_callback_state",
            "recursive_loops_retain_scalar_callees_and_linear_helper_growth",
            "let depth = 8",
            "native_run",
            "event_budgeted",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-helper-declared-result-fallback",
        path: "crates/yir-lower-llvm/src/lib.rs",
        required_patterns: &[
            ".and_then(|function| function.result.as_ref())",
            ".map(|result| result.node.as_str())",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "bounded-buffer-break-source-provenance",
        path: "tools/nuisc/src/lowering/scoped_loop_lowering.rs",
        required_patterns: &[
            "scoped_break_controls",
            "Only the normalizer proves",
            "A user struct with the same shape",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "bounded-buffer-break-shared-contract",
        path: "crates/yir-core/src/loop_carry_contract/scoped_scalars.rs",
        required_patterns: &[
            "scoped_call_i64_carries_break",
            "pub break_on_return: bool",
            "break_control_can_be_the_only_carried_slot",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "bounded-buffer-break-driver",
        path: "crates/yir-domain-cpu/src/execute_scoped_loop.rs",
        required_patterns: &[
            "scoped loop break flag requires an i64 zero seed",
            "scoped loop break flag must be i64 0 or 1",
            "if !self.exited",
            "if self.exited || !active",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "bounded-buffer-break-native-control",
        path: "crates/yir-lower-llvm/src/simple_loop_lowering.rs",
        required_patterns: &[
            "scoped_call_i64_carries_break",
            "carry.store_return(pointer_bits, body, next_reg, next_block)?",
            "loop_while_i64_advance",
            "label %{loop_exit}, label %{advance}",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "bounded-buffer-break-native-validation",
        path: "crates/yir-lower-llvm/src/loop_owned_struct_lowering.rs",
        required_patterns: &[
            "require_control_value(initial, 0, body, next_reg, next_block)",
            "require_control_value(raw, 1, body, next_reg, next_block)",
            "loop_break_control_invalid",
            "before committing any of the returned carries",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "bounded-buffer-break-execution",
        path: "tools/nuisc/tests/buffer_while/breaks.rs",
        required_patterns: &[
            "break_preserves_current_and_prefix_effects_without_user_scalar_carries",
            "break_commits_all_scalar_carries_and_does_not_run_the_remaining_iterations",
            "break_skips_suffix_traps_calls_and_child_bounds_but_not_prefix_effects",
            "nested_break_exits_only_its_loop_and_keeps_the_child_exit_counter",
            "break_and_explicit_step_continue_have_distinct_nested_guard_semantics",
            "break_rejects_unmodeled_induction_mutations_and_nonterminal_exits",
            "break_keeps_effect_order_after_yir_declaration_reordering",
            "break_uses_shared_session_fuel_and_never_exports_its_private_control_slot",
            "break_contract_keeps_glm_inputs_and_rejects_payload_or_zero_trip_seed_drift",
            "break_helpers_have_linear_growth_private_names_and_one_time_predicates",
            "malformed_return_control_traps_in_native_and_reference_execution",
            "index < 1000000000000",
            "event_budgeted",
            "native_run",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nir-branch-constant-state-join",
        path: "tools/nuisc/src/optimize.rs",
        required_patterns: &[
            "Only the enclosing block knows",
            "*env = then_env",
            "*env = else_env",
            "then_env.get(name) == Some(value) && else_env.get(name) == Some(value)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nir-branch-constant-state-join-evidence",
        path: "tools/nuisc/src/optimize_branch_tests.rs",
        required_patterns: &[
            "dynamic_branch_invalidates_rebound_literals_without_pruning_live_arm_state",
            "selected_constant_branch_uses_its_outgoing_environment",
            "nested_loop_mutation_invalidates_the_enclosing_branch_literal",
            "dynamic_branch_keeps_unchanged_literals_without_leaking_branch_locals",
        ],
    },
];
