use crate::dev_tensor_drift::DevTensorDriftCheckSpec;

pub(super) const CHECKS: &[DevTensorDriftCheckSpec] = &[
    DevTensorDriftCheckSpec {
        id: "native-stored-projections-flat-interface-completed-control-catalog",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/scalar_helpers.rs",
        required_patterns: &[
            "Nested interfaces remain on the local selection route",
            "catalog.contains_key(&function.name)",
            "control_loops::contains_loop(&function.body)",
            "control_values::supported_type(&param.ty, &flat)",
            "control_values::supported_type(ty, &flat)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-stored-projections-flat-not-nested-control-authority-tests",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/control_values/typed_tests.rs",
        required_patterns: &[
            "flat_control_interfaces_admit_completed_nested_results_without_nested_transport_authority",
            "nested_value_admission_does_not_grant_nonloop_control_outlining_authority",
            "assert!(roots.contains(\"choose\"))",
            "\"nested_input\"",
            "\"nested_return\"",
            "\"cycle_caller\"",
            "module.functions.reverse()",
            "assert!(!roots.contains(name)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-stored-projections-bounded-materialized-not-inline-proof",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_record_views.rs",
        required_patterns: &[
            "fn completed_projection_type(",
            "&& access(value).is_none()",
            "Only this stored binding becomes ready",
            "every unselected result field remain evaluated exactly once",
            "Do not extend inline expression typing",
            "charge(remaining, fields.len())?",
            "fields.find(|(name, _)| name == field)",
            "ty.filter(|ty| !transport_types.contains(&ty.name))",
            "scalar_aliases::validate_expansion(&result, &mut context.remaining)?",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-stored-projections-catalog-and-every-caller-transaction",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_projection.rs",
        required_patterns: &[
            "result_catalog.retain(|name, _| !generated.contains(name))",
            "if !scoped.contains(&name)",
            "record_views::normalize_call_results(",
            "valid_caller(&module.functions[*i].body, &name, &plan)",
            "matches!(input, Input::Keep(_)) || access(arg).is_some()",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-stored-projections-unit-and-independent-check-oracle",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_stored_projection_tests.rs",
        required_patterns: &[
            "stored_projection_keeps_nested_call_rhs_and_independent_bindings_unchanged",
            "stored_projection_retains_scalar_mixed_kinds_and_every_original_call",
            "stored_projection_requires_exact_fields_declared_kinds_and_completed_catalog",
            "stored_projection_does_not_authorize_unbound_inline_projections_or_scalar_mode",
            "stored_projection_keeps_lexical_version_control_and_transport_exclusions",
            "stored_projection_scalar_reads_cannot_strip_protected_parent_kinds",
            "stored_projection_keeps_whole_consumers_and_unused_fallible_rhs",
            "stored_projection_budget_and_depth_roll_back_the_complete_candidate",
            "stored_projection_preserves_unselected_result_checks_with_an_independent_oracle",
            "stored_projection_requires_every_caller_in_both_function_storage_orders",
            "for budget in 1..1024",
            "yir.nodes.reverse()",
            "assert_eq!(module, before)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-stored-projections-native-full-independent-returns",
        path: "tools/nuisc/tests/native_application_bridge/typed_sparse_captures.rs",
        required_patterns: &[
            "typed_sparse_stored_projections_keep_full_returns_before_selecting_subrecords",
            "typed_sparse_stored_projections_keep_whole_record_consumers_conservative",
            "assert_eq!(returns.len(), 2",
            "returns[0].split_once('=').unwrap().0",
            "returns[1].split_once('=').unwrap().0",
            "!body.contains(\"insertvalue [64 x i64]\")",
            "define [64 x i64] @nuis_fn_produce(",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-stored-projections-half-result-full-envelope-fixture",
        path: "tools/nuisc/tests/native_application_bridge/typed_alias_capture_fixture.rs",
        required_patterns: &[
            "pub fn stored_projection_source(checked: bool)",
            "pub fn stored_projection_transport_source()",
            "struct CallEnvelope {{ selected: SelectedPayload, ignored: IgnoredPayload }}",
            "definition(0..32)",
            "definition(32..64)",
            "produce(payload.f0, {first_unused}).selected",
            "produce(payload.f0 + 30, payload.f62).selected",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-stored-projections-source-free-unselected-field-failure",
        path: "tools/nuis/tests/native_session_workflow/capture_fields.rs",
        required_patterns: &[
            "native_stored_projections_preserve_source_free_unselected_result_checks",
            "let checked = aliases::stored_projection_source(true)",
            "f62: checked(unused)",
            "check_selected_unused_call(&checked)",
            "&aliases::stored_projection_transport_source(),",
            "for _ in 0..2",
            "!stderr.contains(\"SIGKILL\")",
            "fs::remove_file(project.0.join(\"main.ns\"))",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-stored-projections-tensor-scope",
        path: "tools/nuis/src/dev_tensor_data.rs",
        required_patterns: &[
            "Stored call-result projection follow-up:",
            "stored projection readiness is not unbound inline authority or computed-call spilling",
            "native_stored_projections",
            "active/86 is unchanged",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-stored-projections-documentation-boundary",
        path: "docs/reference/nuis-native-scalar-loop-snapshots-v1.md",
        required_patterns: &[
            "## Stored Call Result Projections",
            "The initializer itself is never erasable",
            "This is not inline projection authority",
            "an unselected field of the",
            "budgets 1 through 1023",
            "No new opcode, native limit or public ABI is added",
        ],
    },
];
