use crate::dev_tensor_drift::DevTensorDriftCheckSpec;

pub(crate) const DEV_TENSOR_RUNTIME_CURRENT_DRIFT_CHECKS: &[DevTensorDriftCheckSpec] = &[
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-data-model-v11-contract",
        path: "docs/reference/nuis-compiler-data-model-v11.toml",
        required_patterns: &[
            "nuis-compiler-data-model-v11",
            "nuis-compiler-data-model-v10",
            "surface.std.compiler-data-model.v11",
            "nuis-compiler-complete-aggregate-forwarding-v1",
            "boundary_count = 2",
            "reference_registry_identity = 1593840720",
            "reference_identity = 551151124",
            "status = \"stable\"",
            "progress = 100",
            "new_scalar_exports = 0",
            "expected_native_exit = 130",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-data-model-v11-forwarding-stdlib",
        path: "stdlib/std/lib/compiler_payload_registry.ns",
        required_patterns: &[
            "pub fn compiler_aggregate_arena_forward_checked",
            "expected_registry_identity: i64",
            "expected_arena_identity: i64",
            "pub fn compiler_aggregate_arena_forward",
            "forwarded_registry_identity",
            "forwarded_arena_identity",
            "return Result.Ok(forwarded)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-data-model-v11-native-forwarding",
        path: "examples/projects/tooling/bootstrap_compiler_data_model_demo/payload_registry_fixture.ns",
        required_patterns: &[
            "let forwarded: CompilerAggregateArena",
            "compiler_aggregate_arena_forward",
            "wrong_registry_error",
            "identity_after_wrong_registry",
            "wrong_registry_error != 3",
            "identity_after_wrong_registry != chunked_identity",
            "chunked_identity != 551151124",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-data-provider-inventory-v1-contract",
        path: "docs/reference/nuis-data-provider-inventory-v1.toml",
        required_patterns: &[
            "nuis-data-provider-inventory-v1",
            "nuis-provider-capability-record-v1",
            "fnv1a64:d9930501cc045ea0",
            "data.cpu-memory.reference.v1",
            "priority-desc-provider-id-asc",
            "fnv1a64:80daf599c694cf56",
            "physical_dpu_claimed = false",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuisc-provider-capability-registration-schema",
        path: "tools/nuisc/src/registry_provider_capability.rs",
        required_patterns: &[
            "nuis-provider-capability-record-v1",
            "NustarProviderCapabilityRegistration",
            "provider_capability_registrations",
            "six ordered fields",
            "strictly sorted and unique",
            "priority must be positive",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nustar-data-provider-capability-registration",
        path: "nustar-packages/data.toml",
        required_patterns: &[
            "provider_capabilities",
            "data.cpu-memory.reference.v1",
            "data.host.bundle.v1",
            "clock.fabric-monotonic",
            "completion.verified",
            "glm.owned-transfer",
            "memory.cpu",
            "movement.copy",
            "residency.host",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-provider-capability-aot-generator",
        path: "tools/nsdb/build.rs",
        required_patterns: &[
            "provider_capability_registrations",
            "canonical_capability_manifest",
            "nuis-provider-capability-manifest-v1",
            "PROVIDER_CAPABILITY_MANIFEST_HASH",
            "provider_capability_registry_generated.rs",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-provider-capability-selection",
        path: "tools/nsdb/src/provider_capability_registry.rs",
        required_patterns: &[
            "nuis-provider-capability-registry-v1",
            "nuis-provider-capability-selection-v1",
            "select_provider_capability",
            "canonical_requirements",
            "duplicate-requirement",
            "provider-capability-selection:unsupported",
            "rhs.priority",
            "lhs.provider_id",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-cpu-memory-reference-execution",
        path: "tools/nsdb/src/provider_sample_execute_tests.rs",
        required_patterns: &[
            "executes_registered_native_worker_with_two_graph_outputs",
            "data.cpu-memory.reference.v1",
            "fnv1a64:d9930501cc045ea0",
            "fnv1a64:d0e7db5a3ab8fb6b",
            "nuis-provider-completion-evidence-v1",
            "nuis-provider-glm-release-evidence-v1",
            "nuis-provider-completion-clock-v1",
        ],
    },
];
