use crate::dev_tensor_drift::DevTensorDriftCheckSpec;

pub(crate) const DEV_TENSOR_RUNTIME_DEV_LINEAGE_DRIFT_CHECKS: &[DevTensorDriftCheckSpec] = &[
    DevTensorDriftCheckSpec {
        id: "dev-tensor-task-card-recursive-lineage",
        path: "tools/nuis/src/dev_tensor_task_card_lineage.rs",
        required_patterns: &[
            "nuis-dev-tensor-task-card-lineage-v1",
            "validate_dev_tensor_task_card_lineage",
            "resolve_leaf_ancestry",
            "find_node_ancestry",
            "common_ancestor_index",
            "recursive_lineage_resolves_current_task_and_handoff_leaves",
            "direct_lineage_has_zero_transition_depth",
            "lineage_rejects_an_unreachable_handoff_leaf",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "dev-tensor-task-card-lineage-render",
        path: "tools/nuis/src/dev_tensor_task_card_lineage_render.rs",
        required_patterns: &[
            "weakest_bootstrap_task_card_lineage_protocol",
            "weakest_bootstrap_task_card_lineage_status",
            "weakest_bootstrap_task_card_lineage_errors",
            "weakest_bootstrap_task_card_task_ancestry",
            "weakest_bootstrap_task_card_handoff_ancestry",
            "weakest_bootstrap_task_card_common_ancestor_path",
            "weakest_bootstrap_task_card_transition_depth",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "dev-tensor-task-card-lineage-regression",
        path: "tools/nuis/src/dev_tensor_tests.rs",
        required_patterns: &[
            "nuis-dev-tensor-task-card-lineage-v1",
            "weakest_bootstrap_task_card_lineage_status",
            "weakest_bootstrap_task_card_lineage_errors",
            "weakest_bootstrap_task_card_task_ancestry",
            "weakest_bootstrap_task_card_handoff_ancestry",
            "weakest_bootstrap_task_card_transition_depth",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "dev-tensor-task-card-lineage-doc",
        path: "docs/reference/nuis-development-tensor.md",
        required_patterns: &[
            "nuis-dev-tensor-task-card-lineage-v1",
            "weakest_bootstrap_task_card_lineage_status",
            "weakest_bootstrap_task_card_task_ancestry",
            "weakest_bootstrap_task_card_handoff_ancestry",
            "weakest_bootstrap_task_card_common_ancestor_path",
            "weakest_bootstrap_task_card_transition_depth",
            "transition depth zero",
            "different reachable leaf",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "beta-0.10-mainline-router",
        path: "docs/current-mainline-map.md",
        required_patterns: &[
            "current `beta-0.10.*` reading route",
            "nuis-beta-0.10.0-self-hosting-entry.md",
            "nuis-beta-0.6.0-mainline-entry.md",
            "previous curated `beta-0.3.*` entry",
            "recorded predecessor `beta-0.0.1` entry",
            "nuis-beta-0.0.1-mainline-entry.md",
            "direct predecessor `alpha-0.20.*` closeout entry",
            "predecessor `alpha-0.17.*` registered worker entry",
            "predecessor `alpha-0.16.*` tensor-guided closure entry",
            "nuis-development-tensor.md",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "beta-0.10-repository-frontdoor",
        path: "README.md",
        required_patterns: &[
            "repository is on `beta-0.10.*`",
            "formal staged self-hosting migration line",
            "stage0-to-stage1-migration/active",
            "nuis-beta-0.10.0-self-hosting-entry.md",
            "nuis-beta-0.6.0-mainline-entry.md",
            "registered execution domains",
            "nuis-nsld-final-output-selection-evidence-file-v1",
            "generated GNU resolver and symbol-version registry",
            "bootstrap-reproducibility",
            "Development tensor",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "beta-0.10-self-hosting-migration-entry",
        path: "docs/versioning/nuis-beta-0.10.0-self-hosting-entry.md",
        required_patterns: &[
            "c496bb67",
            "stage0-to-stage1-migration",
            "migration active: `true`",
            "final readiness: `false`",
            "closed gates: `1/5`",
            "candidate-owned native object or equivalent Nsld input",
            "Stage0 remains part of the",
        ],
    },
];
