use crate::dev_tensor_drift::DevTensorDriftCheckSpec;

pub(super) const CHECKS: &[DevTensorDriftCheckSpec] = &[
    DevTensorDriftCheckSpec {
        id: "native-logical-child-trees-recursive-exact-bool-proof-and-original-depth",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/effectful_selections_predicates.rs",
        required_patterns: &["left: Box<Predicate>", "right: Box<Predicate>", "if depth >= 32",
            "prove_at_depth(lhs, scope, signatures, budget, depth + 1)", "prove_at_depth(rhs, scope, signatures, budget, depth + 1)",
            "nested::inspect_at_depth(condition, scope, signatures, budget, depth)", "ty == scalar_type(\"bool\")",
            "budget.logical_edges.checked_sub(1)?", "calls.extend(left_calls)"],
    },
    DevTensorDriftCheckSpec {
        id: "native-logical-child-trees-shared-region-edge-budget-not-per-root-reset",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/effectful_selections_nested.rs",
        required_patterns: &["pub(super) logical_edges: usize", "logical_edges: 32", "nodes: 64", "expressions: 256",
            "predicates::prove(condition, scope, signatures, budget)?", "captures.len() > 31"],
    },
    DevTensorDriftCheckSpec {
        id: "native-logical-child-trees-linear-helper-installation-guarded-complete-rhs",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/effectful_selections_predicates.rs",
        required_patterns: &["let left = install(*left, names, bindings, helpers)", "let right = install(*right, names, bindings, helpers)",
            "let mut args = vec![left]", "args.extend(params.iter().map(|p| NirExpr::Var(p.name.clone())))",
            "let result = if selected { right } else { complement(right) }", "then_body: vec![NirStmt::Return(Some(NirExpr::Bool(false)))]"],
    },
    DevTensorDriftCheckSpec {
        id: "native-logical-child-trees-once-only-types-hygiene-atomic-vetoes-and-complete-shared-bounds",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/effectful_selections_logical_trees_tests.rs",
        required_patterns: &["tree_logical_effectful_scalar_selections_guard_each_edge_keep_calls_once_types_and_hygiene",
            "tree_logical_effectful_scalar_selections_share_exact_edge_expression_and_combined_depth_bounds",
            "tree_logical_effectful_scalar_selections_share_edges_across_original_sibling_regions_atomically",
            "tree_logical_effectful_scalar_selections_bound_complete_rhs_capture_union_not_each_leaf",
            "tree_logical_effectful_scalar_selections_reject_hidden_leaves_and_late_invalid_descendants_atomically",
            "for edges in [32, 33]", "for count in [16, 17]", "for count in [31, 32]", "assert_eq!(names, before_names)",
            "(decide(saved / 2) && first) || second", "first || (decide(saved / 2) && second)", "assert_eq!(calls, 1)"],
    },
    DevTensorDriftCheckSpec {
        id: "native-logical-child-trees-transitive-yir-order-five-types-policy-and-checkpoint-vetoes",
        path: "tools/nuisc/src/aot_application_effect_call_tree_logical_tests.rs",
        required_patterns: &["native_tree_logical_effectful_scalar_selections_keep_transitive_guard_check_call_order_and_exact_types",
            "native_tree_logical_effectful_scalar_selections_preserve_policy_checkpoint_and_removed_order_vetoes",
            "assert_eq!(predicates, 8)", "yir_core::EdgeKind::Effect", "lacks dependency order", "verify_nuis_compiled_artifact"],
    },
    DevTensorDriftCheckSpec {
        id: "native-logical-child-trees-real-selected-leaves-merges-cache-source-free-restoration-and-traps",
        path: "tools/nuis/tests/native_session_workflow/effect_call_tree_logical.rs",
        required_patterns: &["native_tree_logical_effectful_scalar_selections_build_cache_restore_and_keep_each_edge_selected_once",
            "native_tree_logical_effectful_scalar_selections_trap_at_every_selected_tree_leaf_and_original_merge_boundary",
            "for c in [false, true]", "compile_cache: hit", "for _ in 0..3", "args[6] = \"0\"",
            "fs::remove_dir_all(project.0.join(\".nuis\"))", "SIGILL", "SIGTRAP", "rejected_before_open(run)"],
    },
    DevTensorDriftCheckSpec {
        id: "native-logical-child-trees-source-mixed-left-right-nesting-and-current-merge-checks",
        path: "tools/nuisc/tests/native_application_bridge/tree_logical_effectful_scalar_selections.ns",
        required_patterns: &["expected(first_choice(outer, a, b, c), saved)",
            "(probe_a(a, saved, saved / da) && probe_b(b, saved, saved / db)) || probe_c(c, saved, saved / dc)",
            "probe_d(a, saved, wanted, saved / dd) || (probe_e(b, saved, wanted, saved / de) && probe_f(c, saved, wanted, saved / df))",
            "(probe_a(a, saved, saved / da) || probe_b(b, saved, saved / db)) && probe_c(c, saved, saved / dc)",
            "probe_d(a, saved, wanted, saved / dd) && (probe_e(b, saved, wanted, saved / de) || probe_f(c, saved, wanted, saved / df))",
            "wanted + (proof - saved)", "first_work(saved, saved / first_leaf)", "second_work(saved, saved / second_leaf)"],
    },
    DevTensorDriftCheckSpec {
        id: "native-logical-child-trees-contract-direct-root-boundaries-and-native-fixture",
        path: "docs/reference/nuis-native-effectful-scalar-selection-v1.md",
        required_patterns: &["## Bounded Logical Child Trees", "32 logical edges", "complete RHS capture union",
            "one bool helper per original logical edge", "480 successful", "Eighteen selected", "Logical child-tree acceptance:"],
    },
    DevTensorDriftCheckSpec {
        id: "native-logical-child-trees-complete-computed-history-and-next-staging-value-root-task",
        path: "tools/nuis/src/dev_tensor_data.rs",
        required_patterns: &["Bounded logical child trees follow-up:", "Previous computed-child checkpoint:",
            "Previous computed-child task checkpoint:", "Previous computed-child blocker checkpoint:",
            "Previous computed-child action checkpoint:", "Previous computed-child artifact checkpoint:",
            "Prove guarded logical value roots in effectful scalar region staging", "native_tree_logical_effectful_scalar_selections"],
    },
    DevTensorDriftCheckSpec {
        id: "native-computed-logical-child-bounded-exact-bool-left-and-shared-effect-discovery",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/effectful_selections_predicates.rs",
        required_patterns: &["prove_at_depth(lhs, scope, signatures, budget, depth + 1)",
            "prove_at_depth(rhs, scope, signatures, budget, depth + 1)", "calls.extend(left_calls)",
            "nested::inspect_at_depth(condition, scope, signatures, budget, depth)", "ty == scalar_type(\"bool\")", "let mut args = vec![left]"],
    },
    DevTensorDriftCheckSpec {
        id: "native-computed-logical-child-left-only-effects-types-polarity-and-atomic-vetoes",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/effectful_selections_computed_predicates_tests.rs",
        required_patterns: &["computed_logical_effectful_scalar_selections_keep_left_checks_at_argument_zero_and_left_only_effects",
            "computed_logical_effectful_scalar_selections_preserve_comparison_call_types_polarity_and_hygiene",
            "computed_logical_effectful_scalar_selections_reject_nested_leaves_bad_left_signatures_and_private_reads_atomically",
            "assert_eq!(module, before)", "assert_eq!(names, before_names)", "\"argument\"", "\"escape\""],
    },
    DevTensorDriftCheckSpec {
        id: "native-computed-logical-child-shared-operands-expression-depth-and-ancestor-capture-limits",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/effectful_selections_computed_predicates_tests.rs",
        required_patterns: &["computed_logical_effectful_scalar_selections_share_both_operands_expression_depth_and_ancestor_captures",
            "for expressions in [4, 5]", "for additions in [29, 30]", "for count in [28, 29]",
            "assert_eq!(budget.nodes, 1)", "assert_eq!(budget.expressions, 0)"],
    },
    DevTensorDriftCheckSpec {
        id: "native-computed-logical-child-yir-transitive-effect-order-and-unchanged-policy-vetoes",
        path: "tools/nuisc/src/aot_application_effect_call_computed_logical_tests.rs",
        required_patterns: &["native_computed_logical_effectful_scalar_selections_order_left_checks_calls_predicates_and_rhs_guards",
            "native_computed_logical_effectful_scalar_selections_preserve_default_policy_checkpoint_and_order_vetoes",
            "yir_core::EdgeKind::Effect", "seen.contains(pair[1].as_str())", "assert_eq!(predicates.len(), 4)",
            "lacks dependency order", "verify_nuis_compiled_artifact"],
    },
    DevTensorDriftCheckSpec {
        id: "native-computed-logical-child-source-left-and-rhs-checks-after-current-merge",
        path: "tools/nuisc/tests/native_application_bridge/computed_logical_effectful_scalar_selections.ns",
        required_patterns: &["first_gate(first, saved, saved / first_left)", "second_gate(second, saved, wanted, saved / second_left)",
            "first_true(reply, saved, saved / first_rhs)", "second_false(reply, saved, wanted, saved / second_rhs)",
            "print(91)", "print(92)", "expected(first, reply, saved)"],
    },
    DevTensorDriftCheckSpec {
        id: "native-computed-logical-child-real-left-once-source-free-restoration-and-left-rhs-leaf-traps",
        path: "tools/nuis/tests/native_session_workflow/effect_call_computed_logical.rs",
        required_patterns: &["native_computed_logical_effectful_scalar_selections_build_cache_restore_and_evaluate_left_once",
            "native_computed_logical_effectful_scalar_selections_trap_at_left_rhs_and_leaf_including_skipped_rhs",
            "for reply in [false, true]", "compile_cache: hit", "for _ in 0..3", "[5, 7, 9, 6, 8, 10]",
            "fs::remove_dir_all(project.0.join(\".nuis\"))", "SIGILL", "SIGTRAP", "rejected_before_open(run)"],
    },
    DevTensorDriftCheckSpec {
        id: "native-computed-logical-child-contract-original-site-left-effects-and-bounded-acceptance",
        path: "docs/reference/nuis-native-effectful-scalar-selection-v1.md",
        required_patterns: &["## Computed Logical Child Gates", "Left calls contribute to effect discovery",
            "480 successful", "Sixteen selected left/RHS/leaf trap", "YIR Effect-path ordering", "Computed logical child acceptance:"],
    },
    DevTensorDriftCheckSpec {
        id: "native-computed-logical-child-complete-six-field-logical-history-and-next-tree-task",
        path: "tools/nuis/src/dev_tensor_data.rs",
        required_patterns: &["Computed logical child gates follow-up:", "Previous logical-child checkpoint:",
            "Previous logical-child task checkpoint:", "Previous logical-child blocker checkpoint:",
            "Previous logical-child action checkpoint:", "Previous logical-child artifact checkpoint:",
            "Prove bounded logical trees in effectful scalar selection regions", "native_computed_logical_effectful_scalar_selections"],
    },
    DevTensorDriftCheckSpec {
        id: "native-logical-effectful-selection-owned-atom-single-edge-proof-and-shared-bounds",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/effectful_selections_predicates.rs",
        required_patterns: &["calls.extend(left_calls)", "budget.expressions.checked_sub(1)?",
            "prove_at_depth(lhs, scope, signatures, budget, depth + 1)",
            "prove_at_depth(rhs, scope, signatures, budget, depth + 1)", "right_inputs.len() > 31",
            "left_inputs.union(&right_inputs)", "selected: *op == NirBinaryOp::And"],
    },
    DevTensorDriftCheckSpec {
        id: "native-logical-effectful-selection-complete-guarded-rhs-zero-seed-and-complement-installation",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/effectful_selections_predicates.rs",
        required_patterns: &["let mut args = vec![left]", "args.extend(params.iter().map(|p| NirExpr::Var(p.name.clone())))",
            "__nuis_effect_call_predicate", "let result = if selected { right } else { complement(right) }",
            "then_body: vec![NirStmt::Return(Some(NirExpr::Bool(false)))]", "NirStmt::Return(Some(result))",
            "let call = NirExpr::Call { callee: name, args }", "complement(call)"],
    },
    DevTensorDriftCheckSpec {
        id: "native-logical-effectful-selection-actual-merges-types-polarity-hygiene-and-atomic-vetoes",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/effectful_selections_predicates_tests.rs",
        required_patterns: &["logical_effectful_scalar_selections_guard_complete_rhs_and_keep_actual_child_merges",
            "logical_effectful_scalar_selections_preserve_owned_types_literals_polarity_and_hygiene",
            "logical_effectful_scalar_selections_reject_unproved_operands_signatures_and_private_escapes_atomically",
            "assert_eq!(module, before)", "assert_eq!(names, before_names)", "\"left_type\"", "\"rhs_type\"", "\"escape\""],
    },
    DevTensorDriftCheckSpec {
        id: "native-logical-effectful-selection-exact-expression-depth-and-rhs-capture-limits",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/effectful_selections_predicates_tests.rs",
        required_patterns: &["logical_effectful_scalar_selections_share_expression_depth_and_rhs_capture_limits",
            "for expressions in [3, 4]", "for count in [31, 32]", "for additions in [29, 30]",
            "assert_eq!(budget.nodes, 1)", "assert_eq!(budget.expressions, 0)"],
    },
    DevTensorDriftCheckSpec {
        id: "native-logical-effectful-selection-yir-effect-order-typed-emission-policy-checkpoint-vetoes",
        path: "tools/nuisc/src/aot_application_effect_call_logical_tests.rs",
        required_patterns: &["native_logical_effectful_scalar_selections_order_guards_divisions_rhs_calls_and_actual_merges",
            "native_logical_effectful_scalar_selections_preserve_default_policy_checkpoint_and_removed_order_vetoes",
            "assert_eq!(predicates.len(), 4)", "yir_core::EdgeKind::Effect", "lacks dependency order", "verify_nuis_compiled_artifact"],
    },
    DevTensorDriftCheckSpec {
        id: "native-logical-effectful-selection-real-truth-matrix-poisoned-rhs-source-free-restoration-and-traps",
        path: "tools/nuis/tests/native_session_workflow/effect_call_logical.rs",
        required_patterns: &["native_logical_effectful_scalar_selections_build_cache_restore_and_skip_poisoned_rhs",
            "native_logical_effectful_scalar_selections_trap_at_selected_rhs_and_leaf_without_publication",
            "for reply in [false, true]", "for stage in 0..4", "compile_cache: hit", "for _ in 0..3",
            "fs::remove_dir_all(project.0.join(\".nuis\"))", "SIGILL", "SIGTRAP", "rejected_before_open(run)"],
    },
    DevTensorDriftCheckSpec {
        id: "native-logical-effectful-selection-contract-original-site-zero-seed-and-truth-boundaries",
        path: "docs/reference/nuis-native-effectful-scalar-selection-v1.md",
        required_patterns: &["## Single Edge Logical Child Predicates", "complement-coded helper results",
            "480 successful", "Eight selected RHS/leaf trap", "Computed left gates", "Logical child-selection acceptance:"],
    },
    DevTensorDriftCheckSpec {
        id: "native-logical-effectful-selection-full-ordered-history-and-next-computed-gate-task",
        path: "tools/nuis/src/dev_tensor_data.rs",
        required_patterns: &["Guarded logical child predicates follow-up:", "Previous ordered-region checkpoint:",
            "Previous ordered-region task checkpoint:", "Previous ordered-region blocker checkpoint:",
            "Previous ordered-region action checkpoint:", "Previous ordered-region artifact checkpoint:",
            "Prove computed single-edge logical child gates at their original sites", "native_logical_effectful_scalar_selections"],
    },
    DevTensorDriftCheckSpec {
        id: "native-ordered-effectful-selection-budget-bounded-walk-and-single-outer-target",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/effectful_selections_ordered.rs",
        required_patterns: &["statements.len() > budget.nodes", "while let Some(offset)",
            "let index = cursor + offset", "scope.get(&proof.name)?", "name != &proof.name || ty != &proof.ty",
            "scope.contains_key(name) && name != &target", "let (target, ty) = target?", "let suffix = &statements[cursor..]",
            "if statements.is_empty()", "next.inputs.difference(&staging.defined)", "staging.defined.insert(proof.name)"],
    },
    DevTensorDriftCheckSpec {
        id: "native-ordered-effectful-selection-single-shared-dispatch-and-depth",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/effectful_selections_nested.rs",
        required_patterns: &["ordered::prove(statements, scope, signatures, budget, depth)",
            "regions::prove(statements, scope, signatures, budget)", "nodes: 64", "expressions: 256", "depth >= 8", "captures.len() > 31"],
    },
    DevTensorDriftCheckSpec {
        id: "native-ordered-effectful-selection-complete-source-merge-installation",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/effectful_selections.rs",
        required_patterns: &["mod ordered;", "Vec<(Vec<regions::Statement>, Box<Plan>)>",
            "SelectedValue::Ordered(children, suffix, result)", "for (stage, child) in children", "body.extend(regions::install(stage, names, bindings, helpers))",
            "let (statements, _, _) = install(*child, names, bindings, helpers)", "body.extend(regions::install(suffix, names, bindings, helpers))"],
    },
    DevTensorDriftCheckSpec {
        id: "native-ordered-effectful-selection-adjacent-final-mixed-types-vetoes-and-shared-limits",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/effectful_selections_ordered_tests.rs",
        required_patterns: &["ordered_effectful_scalar_selections_merge_adjacent_children_before_later_predicates_and_final_results",
            "ordered_effectful_scalar_selections_preserve_shape_polarity_exact_types_and_name_hygiene",
            "ordered_effectful_scalar_selections_reject_other_targets_exports_exits_resources_and_private_escapes_atomically",
            "ordered_effectful_scalar_selections_share_child_count_stage_capture_depth_node_and_expression_limits",
            "for count in [20, 21]", "for count in [16, 17]", "for depth in [8, 9]", "for count in [27, 28]",
            "(10, 256, false)", "(64, 13, false)", "assert_eq!(budget.nodes, 1)"],
    },
    DevTensorDriftCheckSpec {
        id: "native-ordered-effectful-selection-typed-order-policy-and-checkpoint-vetoes",
        path: "tools/nuisc/src/aot_application_effect_call_ordered_tests.rs",
        required_patterns: &["native_ordered_effectful_scalar_selections_order_adjacent_predicates_final_children_and_exact_types",
            "native_ordered_effectful_scalar_selections_preserve_default_policy_checkpoint_and_removed_order_vetoes",
            "assert_eq!(carriers, 2)", "yir_core::EdgeKind::Effect", "lacks dependency order", "verify_sources", "paired-final"],
    },
    DevTensorDriftCheckSpec {
        id: "native-ordered-effectful-selection-real-current-adjacent-and-final-child-restoration-and-traps",
        path: "tools/nuis/tests/native_session_workflow/effect_call_ordered.rs",
        required_patterns: &["native_ordered_effectful_scalar_selections_build_cache_restore_and_keep_adjacent_and_final_child_versions",
            "native_ordered_effectful_scalar_selections_trap_at_selected_adjacent_middle_final_and_suffix_stages",
            "for third in [false, true]", "for stage in 0..7", "compile_cache: hit", "for _ in 0..3",
            "fs::remove_dir_all(project.0.join(\".nuis\"))", "SIGILL", "SIGTRAP", "rejected_before_open(run)"],
    },
    DevTensorDriftCheckSpec {
        id: "native-ordered-effectful-selection-canonical-walk-contract-and-native-fixture",
        path: "docs/reference/nuis-native-effectful-scalar-selection-v1.md",
        required_patterns: &["## Ordered Scalar Regions", "one or more", "zero through 16", "first child determines",
            "before plan allocation", "actual merge", "480 successful transitions", "Thirteen selected trap",
            "Ordered scalar-region acceptance:"],
    },
    DevTensorDriftCheckSpec {
        id: "native-ordered-effectful-selection-complete-six-field-history-and-next-logical-child-task",
        path: "tools/nuis/src/dev_tensor_data.rs",
        required_patterns: &["Unified ordered scalar regions follow-up:", "Previous repeated child-selection checkpoint:",
            "Previous repeated child-selection task checkpoint:", "Previous repeated child-selection blocker checkpoint:",
            "Previous repeated child-selection action checkpoint:", "Previous repeated child-selection artifact checkpoint:",
            "Prove guarded single-edge logical child predicates inside ordered scalar regions", "native_ordered_effectful_scalar_selections"],
    },
    DevTensorDriftCheckSpec {
        id: "native-repeated-effectful-selection-two-child-single-target-region-proof",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/effectful_selections_ordered.rs",
        required_patterns: &["while let Some(offset)", "scope.get(&proof.name)?",
            "scope.contains_key(name) && name != &target", "statements[cursor..index]",
            "append_stage(stage, &mut staging, signatures, budget)?", "name != &proof.name || ty != &proof.ty",
            "staging.defined.insert(proof.name)", "next.inputs.difference(&staging.defined)",
            "staging.local = next.local"],
    },
    DevTensorDriftCheckSpec {
        id: "native-repeated-effectful-selection-shared-budget-dispatch-and-sibling-depth",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/effectful_selections_nested.rs",
        required_patterns: &["ordered::prove(statements, scope, signatures, budget, depth)",
            "nodes: 64", "expressions: 256", "depth >= 8", "captures.len() > 31"],
    },
    DevTensorDriftCheckSpec {
        id: "native-repeated-effectful-selection-ordered-stage-and-complete-child-merge-installation",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/effectful_selections.rs",
        required_patterns: &["mod ordered;", "Vec<(Vec<regions::Statement>, Box<Plan>)>",
            "SelectedValue::Ordered(children, suffix, result)", "for (stage, child) in children",
            "body.extend(regions::install(stage, names, bindings, helpers))", "install(*child, names, bindings, helpers)", "body.extend(regions::install(suffix, names, bindings, helpers))"],
    },
    DevTensorDriftCheckSpec {
        id: "native-repeated-effectful-selection-current-versions-types-vetoes-and-shared-limits",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/effectful_selections_repeated_tests.rs",
        required_patterns: &["repeated_effectful_scalar_selections_keep_current_merges_and_private_stage_versions",
            "repeated_effectful_scalar_selections_preserve_exact_types_polarities_prefixes_and_hygiene",
            "repeated_effectful_scalar_selections_reject_unproved_shapes_and_private_child_exports_atomically",
            "repeated_effectful_scalar_selections_share_stage_capture_depth_node_and_expression_limits",
            "for count in [16, 17]", "for depth in [8, 9]", "for count in [28, 29]",
            "(9, 256, false)", "(64, 13, false)", "assert_eq!(module, before)"],
    },
    DevTensorDriftCheckSpec {
        id: "native-repeated-effectful-selection-typed-order-policy-and-checkpoint-vetoes",
        path: "tools/nuisc/src/aot_application_effect_call_repeated_tests.rs",
        required_patterns: &["native_repeated_effectful_scalar_selections_order_sibling_stages_and_keep_exact_types",
            "native_repeated_effectful_scalar_selections_preserve_policy_checkpoint_and_removed_order_vetoes",
            "assert_eq!(carriers, 2)", "for mask in 0..8", "yir_core::EdgeKind::Effect",
            "lacks dependency order", "verify_sources"],
    },
    DevTensorDriftCheckSpec {
        id: "native-repeated-effectful-selection-real-current-siblings-source-free-restoration-and-traps",
        path: "tools/nuis/tests/native_session_workflow/effect_call_repeated.rs",
        required_patterns: &["native_repeated_effectful_scalar_selections_build_cache_restore_and_read_current_sibling_versions",
            "native_repeated_effectful_scalar_selections_trap_at_each_selected_stage_before_publication",
            "for stage in 0..6", "compile_cache: hit", "for _ in 0..3",
            "fs::remove_dir_all(project.0.join(\".nuis\"))", "SIGILL", "SIGTRAP", "rejected_before_open(run)"],
    },
    DevTensorDriftCheckSpec {
        id: "native-repeated-effectful-selection-two-current-merges-contract-and-native-fixture",
        path: "docs/reference/nuis-native-effectful-scalar-selection-v1.md",
        required_patterns: &["## Repeated Child Selections", "exactly two immediate child", "1 through 16",
            "second predicate", "actual merge", "320 successful transitions", "Twelve selected trap",
            "adjacent children", "Repeated child-selection acceptance:"],
    },
    DevTensorDriftCheckSpec {
        id: "native-repeated-effectful-selection-six-field-history-and-next-ordered-region-task",
        path: "tools/nuis/src/dev_tensor_data.rs",
        required_patterns: &["Repeated guarded child selections follow-up:",
            "Previous continued child-selection checkpoint:", "Previous continued child-selection task checkpoint:",
            "Previous continued child-selection blocker checkpoint:", "Previous continued child-selection action checkpoint:",
            "Previous continued child-selection artifact checkpoint:",
            "Prove a bounded ordered scalar region walk", "native_repeated_effectful_scalar_selections"],
    },
    DevTensorDriftCheckSpec {
        id: "native-continued-effectful-selection-single-child-suffix-and-outer-target-proof",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/effectful_selections_ordered.rs",
        required_patterns: &["statements[cursor..index]", "scope.get(&proof.name)?",
            "scope.contains_key(name) && name != &target", "name != &proof.name || ty != &proof.ty",
            "append_stage(suffix, &mut staging, signatures, budget)?",
            "staging.defined.insert(proof.name)", "next.inputs.difference(&staging.defined)"],
    },
    DevTensorDriftCheckSpec {
        id: "native-continued-effectful-selection-dispatch-without-budget-reset",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/effectful_selections_nested.rs",
        required_patterns: &["ordered::prove(statements, scope, signatures, budget, depth)",
            "nodes: 64", "expressions: 256",
            "depth >= 8", "captures.len() > 31"],
    },
    DevTensorDriftCheckSpec {
        id: "native-continued-effectful-selection-prefix-child-merge-suffix-installation",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/effectful_selections.rs",
        required_patterns: &["mod ordered;", "Vec<(Vec<regions::Statement>, Box<Plan>)>",
            "SelectedValue::Ordered(children, suffix, result)", "body.extend(regions::install(stage, names, bindings, helpers))",
            "let (statements, _, _) = install(*child, names, bindings, helpers)", "body.extend(regions::install(suffix, names, bindings, helpers))"],
    },
    DevTensorDriftCheckSpec {
        id: "native-continued-effectful-selection-current-versions-polarities-vetoes-and-shared-limits",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/effectful_selections_continued_tests.rs",
        required_patterns: &["continued_effectful_scalar_selections_read_child_merge_before_ordered_private_suffixes",
            "continued_effectful_scalar_selections_keep_exact_types_optional_prefixes_polarities_and_hygiene",
            "continued_effectful_scalar_selections_reject_other_writes_exports_exits_resources_and_extra_children",
            "continued_effectful_scalar_selections_share_suffix_prefix_depth_capture_and_work_limits",
            "for count in [16, 17]", "for depth in [8, 9]", "for expressions in [9, 10]",
            "for nodes in [6, 7]", "assert_eq!(escaped, before)"],
    },
    DevTensorDriftCheckSpec {
        id: "native-continued-effectful-selection-typed-trap-order-policy-and-checkpoint-vetoes",
        path: "tools/nuisc/src/aot_application_effect_call_continued_tests.rs",
        required_patterns: &["native_continued_effectful_scalar_selections_order_child_merge_suffix_arguments_and_exact_types",
            "native_continued_effectful_scalar_selections_preserve_policy_order_and_checkpoint_vetoes",
            "assert_eq!(carriers, 2)", "yir_core::EdgeKind::Effect", "lacks dependency order", "verify_sources"],
    },
    DevTensorDriftCheckSpec {
        id: "native-continued-effectful-selection-real-child-to-suffix-restoration-and-selected-stage-traps",
        path: "tools/nuis/tests/native_session_workflow/effect_call_continued.rs",
        required_patterns: &["native_continued_effectful_scalar_selections_build_cache_restore_and_keep_child_to_suffix_versions",
            "native_continued_effectful_scalar_selections_trap_before_suffix_or_publication_at_each_selected_stage",
            "for stage in 0..5", "compile_cache: hit", "for _ in 0..3",
            "fs::remove_dir_all(project.0.join(\".nuis\"))", "SIGILL", "SIGTRAP", "rejected_before_open(run)"],
    },
    DevTensorDriftCheckSpec {
        id: "native-continued-effectful-selection-bounded-merge-before-suffix-contract",
        path: "docs/reference/nuis-native-effectful-scalar-selection-v1.md",
        required_patterns: &["## Scalar Suffixes After Child Selections", "zero through 16", "1 through 16",
            "same single existing outer target", "actual merged target", "64` or `40", "24` or `15",
            "Repeated sibling child selections", "Ten"],
    },
    DevTensorDriftCheckSpec {
        id: "native-continued-effectful-selection-six-field-history-and-next-repeated-child-task",
        path: "tools/nuis/src/dev_tensor_data.rs",
        required_patterns: &["Scalar suffixes after guarded child selections follow-up:",
            "Previous staged child-selection checkpoint:", "Previous staged child-selection task checkpoint:",
            "Previous staged child-selection blocker checkpoint:", "Previous staged child-selection action checkpoint:",
            "Previous staged child-selection artifact checkpoint:",
            "Prove repeated scalar child selections inside one guarded region", "native_continued_effectful_scalar_selections"],
    },
    DevTensorDriftCheckSpec {
        id: "native-staged-effectful-selection-reuses-bounded-versioned-staging",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/effectful_selections_regions.rs",
        required_patterns: &["pub(super) struct Staging", "pub(super) fn stage(",
            "(1..=16).contains(&statements.len())", "reads.difference(&defined)",
            "local.insert(name.clone(), inferred)", "scope.contains_key(name) && name != target"],
    },
    DevTensorDriftCheckSpec {
        id: "native-staged-effectful-selection-local-child-proof-and-single-outer-target",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/effectful_selections_ordered.rs",
        required_patterns: &["statements[cursor..index]", "append_stage(stage, &mut staging, signatures, budget)?",
            "&staging.local", "scope.get(&proof.name)?", "scope.contains_key(name) && name != &target",
            "proof.inputs.difference(&staging.defined)", "children.push((stage, child))"],
    },
    DevTensorDriftCheckSpec {
        id: "native-staged-effectful-selection-prefix-before-descendants-installation",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/effectful_selections.rs",
        required_patterns: &["mod ordered;", "Vec<(Vec<regions::Statement>, Box<Plan>)>",
            "SelectedValue::Ordered(children, suffix, result)", "body.extend(regions::install(stage, names, bindings, helpers))",
            "install(*child, names, bindings, helpers)", "control_values::zero_value"],
    },
    DevTensorDriftCheckSpec {
        id: "native-staged-effectful-selection-version-retention-hygiene-and-proof-limits",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/effectful_selections_staged_tests.rs",
        required_patterns: &["staged_effectful_scalar_selections_capture_child_versions_after_ordered_prefixes",
            "staged_effectful_scalar_selections_preserve_both_retention_levels_types_and_hygiene",
            "staged_effectful_scalar_selections_reject_child_exports_other_writes_suffixes_and_signatures",
            "staged_effectful_scalar_selections_share_prefix_depth_node_expression_and_capture_limits",
            "for count in [16, 17]", "for depth in [8, 9]", "for count in [29, 30]",
            "for expressions in [7, 8]", "assert_eq!(module, before)"],
    },
    DevTensorDriftCheckSpec {
        id: "native-staged-effectful-selection-typed-order-policy-and-checkpoint-vetoes",
        path: "tools/nuisc/src/aot_application_effect_call_staged_tests.rs",
        required_patterns: &["native_staged_effectful_scalar_selections_order_prefixes_before_child_predicates_and_keep_exact_types",
            "native_staged_effectful_scalar_selections_preserve_policy_order_and_checkpoint_vetoes",
            "assert_eq!(carriers, 2)", "yir_core::EdgeKind::Effect", "lacks dependency order", "verify_sources"],
    },
    DevTensorDriftCheckSpec {
        id: "native-staged-effectful-selection-real-private-versions-retention-and-traps",
        path: "tools/nuis/tests/native_session_workflow/effect_call_staged.rs",
        required_patterns: &["native_staged_effectful_scalar_selections_build_cache_restore_and_keep_prefix_retention",
            "native_staged_effectful_scalar_selections_trap_on_selected_prefix_predicate_or_child_argument_before_publication",
            "for enabled in [false, true]", "for outer in [false, true]", "for child in [false, true]",
            "compile_cache: hit", "for _ in 0..3", "fs::remove_dir_all(project.0.join(\".nuis\"))",
            "SIGILL", "SIGTRAP", "rejected_before_open(run)"],
    },
    DevTensorDriftCheckSpec {
        id: "native-staged-effectful-selection-two-level-retention-contract",
        path: "docs/reference/nuis-native-effectful-scalar-selection-v1.md",
        required_patterns: &["## Staging Before Child Selections", "1 through 16", "after the prefix",
            "private staged values", "single existing outer target", "11 -> 16", "11 -> 6",
            "mixed staging followed", "suffix statements after the child"],
    },
    DevTensorDriftCheckSpec {
        id: "native-staged-effectful-selection-complete-six-field-history-and-next-suffix-task",
        path: "tools/nuis/src/dev_tensor_data.rs",
        required_patterns: &["Staging before guarded child selections follow-up:",
            "Previous sequential scalar-region checkpoint:", "Previous sequential scalar-region task checkpoint:",
            "Previous sequential scalar-region blocker checkpoint:", "Previous sequential scalar-region action checkpoint:",
            "Previous sequential scalar-region artifact checkpoint:",
            "Prove scalar suffixes after nested guarded selections", "native_staged_effectful_scalar_selections"],
    },
    DevTensorDriftCheckSpec {
        id: "native-sequential-effectful-region-separate-versioned-proof",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/effectful_selections_regions.rs",
        required_patterns: &["(2..=16).contains(&statements.len())", "scope.get(target)?",
            "scope.contains_key(name) && name != target", "nested::consume_node(budget)?",
            "nested::inspect(value, &local, signatures, budget)?", "reads.difference(&defined)",
            "local.insert(name.clone(), inferred)", "SelectedValue::Region(staged.statements"],
    },
    DevTensorDriftCheckSpec {
        id: "native-sequential-effectful-region-guarded-installation-and-shared-budget",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/effectful_selections.rs",
        required_patterns: &["mod regions;", "Region(Vec<regions::Statement>, NirExpr)",
            "SelectedValue::Region(statements, value)", "body.extend(statements)",
            "control_values::zero_value", "body.push(NirStmt::Return(Some(value)))"],
    },
    DevTensorDriftCheckSpec {
        id: "native-sequential-effectful-region-recursive-leaf-registration",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/effectful_selections_nested.rs",
        required_patterns: &["body.len() > 1", "regions::prove(statements, scope, signatures, budget)",
            "nodes: 64", "expressions: 256", "depth >= 8", "captures.len() > 31"],
    },
    DevTensorDriftCheckSpec {
        id: "native-sequential-effectful-region-version-types-exports-and-bounds-tests",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/effectful_selections_regions_tests.rs",
        required_patterns: &["sequential_effectful_scalar_regions_capture_rhs_versions_and_keep_private_staging",
            "sequential_effectful_scalar_regions_preserve_nested_masks_exact_types_and_hygiene",
            "sequential_effectful_scalar_regions_reject_exports_other_writes_exits_and_unproved_work",
            "sequential_effectful_scalar_regions_bound_statements_shared_work_and_external_captures",
            "for count in [16, 17]", "for count in [30, 31]", "assert_eq!(module, before)"],
    },
    DevTensorDriftCheckSpec {
        id: "native-sequential-effectful-region-typed-order-and-authority-vetoes",
        path: "tools/nuisc/src/aot_application_effect_call_regions_tests.rs",
        required_patterns: &["native_sequential_effectful_scalar_regions_keep_guard_to_staging_order_and_exact_types",
            "native_sequential_effectful_scalar_regions_preserve_policy_order_and_checkpoint_vetoes",
            "assert_eq!(regions, 2)", "yir_core::EdgeKind::Effect", "lacks dependency order",
            "fixture_with_source", "verify_sources"],
    },
    DevTensorDriftCheckSpec {
        id: "native-sequential-effectful-region-real-staged-restoration-and-traps",
        path: "tools/nuis/tests/native_session_workflow/effect_call_regions.rs",
        required_patterns: &["native_sequential_effectful_scalar_regions_build_cache_restore_and_preserve_staged_versions",
            "native_sequential_effectful_scalar_regions_trap_on_selected_prefix_and_later_stage_before_publication",
            "compile_cache: hit", "for _ in 0..3", "fs::remove_dir_all(project.0.join(\".nuis\"))",
            "SIGILL", "SIGTRAP", "rejected_before_open(run)", "if prefix_trap"],
    },
    DevTensorDriftCheckSpec {
        id: "native-sequential-effectful-region-scoped-version-and-retention-contract",
        path: "docs/reference/nuis-native-effectful-scalar-selection-v1.md",
        required_patterns: &["## Sequential Scalar Regions", "2 through 16", "RHS expressions",
            "unused effectful calls", "mixed staging followed", "11 -> 16 -> 32", "11 -> 6 -> 0"],
    },
    DevTensorDriftCheckSpec {
        id: "native-sequential-effectful-region-complete-six-field-history-and-next-task",
        path: "tools/nuis/src/dev_tensor_data.rs",
        required_patterns: &["Sequential guarded scalar regions follow-up:",
            "Previous nested scalar-update checkpoint:", "Previous nested scalar-update task checkpoint:",
            "Previous nested scalar-update blocker checkpoint:", "Previous nested scalar-update action checkpoint:",
            "Previous nested scalar-update artifact checkpoint:",
            "Prove scalar staging before nested guarded selections", "native_sequential_effectful_scalar_regions"],
    },
    DevTensorDriftCheckSpec {
        id: "native-effectful-selection-flat-registration",
        path: "tools/nuis/src/dev_tensor_drift_data_native_iteration_calls.rs",
        required_patterns: &["mod effectful_selections;", "effectful_selections::CHECKS,", ".flatten()"],
    },
    DevTensorDriftCheckSpec {
        id: "native-effectful-selection-separate-signature-proof-and-bounds",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/effectful_selections.rs",
        required_patterns: &["Signature discovery is not body/effect admission", "f.generic_params.is_empty()",
            "f.where_bounds.is_empty()", "inputs.len() > 31", "let mut budget = 256",
            "depth >= 32", "NirBinaryOp::And | NirBinaryOp::Or", "!pure.contains(name)"],
    },
    DevTensorDriftCheckSpec {
        id: "native-effectful-selection-hygienic-guard-before-original-work",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/effectful_selections.rs",
        required_patterns: &["__nuis_effect_call_gate", "__nuis_effect_call_arm", "control_values::zero_value",
            "NirStmt::Return(Some(value))", "__nuis_effect_call_result", "NirExpr::Var(p.name.clone())"],
    },
    DevTensorDriftCheckSpec {
        id: "native-effectful-selection-shared-outliner-and-verification",
        path: "tools/nuisc/src/lowering/buffer_loop_outline.rs",
        required_patterns: &["effectful_selections::outline(module, &mut names)",
            "crate::nir_verify::verify_nir_module(module)?", "functions: effectful_selections.clone()",
            "guarded_functions: effectful_selections"],
    },
    DevTensorDriftCheckSpec {
        id: "native-effectful-selection-direct-call-frontier",
        path: "tools/nuisc/src/lowering/direct_calls.rs",
        required_patterns: &["Calls may hide effects or traps", "chain_statement_effect(state, &name)"],
    },
    DevTensorDriftCheckSpec {
        id: "native-effectful-selection-ordered-argument-roots",
        path: "tools/nuisc/src/lowering/body_calls.rs",
        required_patterns: &["lower_ordered_call_arguments", "state.last_effect_anchor.clone()",
            "state.yir.nodes.len()", "state.yir.edges.len()", "order_emitted_roots_after"],
    },
    DevTensorDriftCheckSpec {
        id: "native-effectful-selection-trapping-arithmetic-frontier",
        path: "tools/nuisc/src/lowering/core_exprs.rs",
        required_patterns: &["matches!(op, NirBinaryOp::Div | NirBinaryOp::Rem)",
            "body_lowering::chain_statement_effect(state, &name)"],
    },
    DevTensorDriftCheckSpec {
        id: "native-effectful-selection-no-eager-effectful-fallback",
        path: "tools/nuisc/src/lowering/if_lowering.rs",
        required_patterns: &["then_args", "!is_terminal_branch_pure_expr(arg, &state.pure_helpers)",
            "!is_terminal_branch_pure_expr(lhs_value, &state.pure_helpers)",
            "conditional effectful binding requires guarded helper lowering"],
    },
    DevTensorDriftCheckSpec {
        id: "native-effectful-selection-exact-types-hygiene-and-proof-limits",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/effectful_selections_tests.rs",
        required_patterns: &["effectful_selections_capture_only_scalars_and_keep_work_behind_guards",
            "effectful_selections_support_exact_five_scalar_zeros_and_return_or_const_destinations",
            "effectful_selections_leave_pure_and_loop_routes_and_unsupported_shapes_unchanged",
            "effectful_selection_expression_proof_bounds_depth_nodes_and_exact_signatures",
            "effectful_selections_keep_private_names_hygienic_and_capture_current_bindings",
            "effectful_selections_do_not_discover_async_resource_optional_or_generic_signatures"],
    },
    DevTensorDriftCheckSpec {
        id: "native-effectful-selection-order-grants-and-checkpoint-regressions",
        path: "tools/nuisc/src/aot_application_effect_call_tests.rs",
        required_patterns: &["native_effectful_selected_calls_keep_source_order_and_guard_arguments",
            "native_effectful_selected_calls_preserve_profile_checks_and_reject_removed_order",
            "native_effectful_selected_calls_bind_source_free_checkpoint", "lacks dependency order",
            "yir_core::EdgeKind::Effect"],
    },
    DevTensorDriftCheckSpec {
        id: "native-effectful-selection-real-cache-restore-and-native-traps",
        path: "tools/nuis/tests/native_session_workflow/effect_calls.rs",
        required_patterns: &["native_effectful_selected_calls_build_cache_restore_and_execute_only_selected_arguments",
            "native_effectful_selected_calls_trap_on_selected_division_before_suffix_or_publication",
            "compile_cache: hit", "for _ in 0..3", "fs::remove_dir_all(project.0.join(\".nuis\"))",
            "SIGILL", "SIGTRAP", "rejected_before_open(run)"],
    },
    DevTensorDriftCheckSpec {
        id: "native-effectful-selection-contract-and-complete-tensor-history",
        path: "docs/reference/nuis-native-effectful-scalar-selection-v1.md",
        required_patterns: &["256 nodes", "at most 31", "Both guard helpers are invoked in order",
            "helper-entry budget", "source-to-YIR order propagation", "pure", "three standalone restoration cycles"],
    },
    DevTensorDriftCheckSpec {
        id: "native-effectful-selection-six-field-history-and-next-weakest",
        path: "tools/nuis/src/dev_tensor_data.rs",
        required_patterns: &["Guarded effectful scalar selections follow-up:",
            "Previous literal-print build checkpoint:", "Previous literal-print build task checkpoint:",
            "Previous literal-print build blocker checkpoint:", "Previous literal-print build action checkpoint:",
            "Previous literal-print build artifact checkpoint:",
            "Extend guarded effectful scalar selections without eager fallback", "native_effectful_selected_calls"],
    },
    DevTensorDriftCheckSpec {
        id: "native-effectful-scalar-rebinding-existing-capture-proof",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/effectful_selections.rs",
        required_patterns: &["yes.is_empty() || no.is_empty()", "scope.get(name)?",
            "let [NirStmt::Let { name, .. }]", "Retain the pre-branch binding",
            "value: NirExpr::Var(name.clone())", "prepare(condition, yes, no, scope, signatures, pure)"],
    },
    DevTensorDriftCheckSpec {
        id: "native-effectful-scalar-rebinding-polarities-types-versions-and-limits",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/effectful_selections_tests.rs",
        required_patterns: &["effectful_scalar_rebindings_retain_existing_values_for_both_polarities_and_exact_types",
            "effectful_scalar_rebindings_keep_sequential_versions_and_private_guards",
            "effectful_scalar_rebindings_reject_fresh_constants_mismatches_and_capture_overflow",
            "for count in [30, 31]", "assert_eq!(module, before)", "__nuis_effect_call_gate_0"],
    },
    DevTensorDriftCheckSpec {
        id: "native-effectful-scalar-rebinding-emitted-order-policy-and-checkpoint",
        path: "tools/nuisc/src/aot_application_effect_call_tests.rs",
        required_patterns: &["native_effectful_scalar_rebindings_keep_retained_arms_and_guarded_argument_order",
            "native_effectful_scalar_rebindings_preserve_policy_order_and_source_free_checkpoint_checks",
            "for shape in [\"paired\", \"then\", \"else\",", "assert_eq!(retained, 2)", "lacks dependency order"],
    },
    DevTensorDriftCheckSpec {
        id: "native-effectful-scalar-rebinding-real-source-free-runs-and-selected-traps",
        path: "tools/nuis/tests/native_session_workflow/effect_calls.rs",
        required_patterns: &["native_effectful_scalar_rebindings_build_cache_restore_and_preserve_current_values",
            "native_effectful_scalar_rebindings_trap_only_in_the_selected_update_before_publication",
            "check_rebindings", "for _ in 0..3", "fs::remove_dir_all(project.0.join(\".nuis\"))",
            "compile_cache: hit", "rejected_before_open(run)"],
    },
    DevTensorDriftCheckSpec {
        id: "native-effectful-scalar-rebinding-scoped-contract",
        path: "docs/reference/nuis-native-effectful-scalar-selection-v1.md",
        required_patterns: &["## One-Sided Rebinding", "pre-branch binding, not a typed zero",
            "31-capture limit", "neither selected update preserves `11`",
            "both produce `7`", "three standalone restoration cycles", "remains i64"],
    },
    DevTensorDriftCheckSpec {
        id: "native-effectful-scalar-rebinding-six-field-history-and-next-task",
        path: "tools/nuis/src/dev_tensor_data.rs",
        required_patterns: &["Guarded one-sided scalar rebindings follow-up:",
            "Previous guarded scalar-selection checkpoint:", "Previous guarded scalar-selection task checkpoint:",
            "Previous guarded scalar-selection blocker checkpoint:", "Previous guarded scalar-selection action checkpoint:",
            "Previous guarded scalar-selection artifact checkpoint:",
            "Prove nested guarded scalar selections without eager fallback", "native_effectful_scalar_rebindings"],
    },
    DevTensorDriftCheckSpec {
        id: "native-nested-effectful-selection-shared-guard-installation",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/effectful_selections.rs",
        required_patterns: &["nested::prepare(", "enum SelectedValue", "Nested(Box<Plan>)",
            "Descendant predicates are emitted only after this ancestor guard",
            "install(*child, names, bindings, helpers)", "body.push(NirStmt::Return(Some(value)))"],
    },
    DevTensorDriftCheckSpec {
        id: "native-nested-effectful-selection-independent-cumulative-proof",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/effectful_selections_nested.rs",
        required_patterns: &["nodes: 64", "expressions: 256", "depth >= 8", "consume_node(budget)?",
            "&mut budget.expressions", "scope.get(name)?", "yes.name != no.name",
            "captures.len() > 31", "captures.union(&condition_inputs)", "!pure.contains(name)"],
    },
    DevTensorDriftCheckSpec {
        id: "native-nested-effectful-selection-registered-control-boundary",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/scalar_control.rs",
        required_patterns: &["A registered leading guard is already a complete control boundary",
            "if guarded.contains(&function.name)", "|| !retained.contains(&function.name)"],
    },
    DevTensorDriftCheckSpec {
        id: "native-nested-effectful-selection-types-hygiene-and-tree-bounds",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/effectful_selections_nested_tests.rs",
        required_patterns: &["nested_effectful_scalar_selections_capture_inner_predicates_after_ancestor_guards",
            "nested_effectful_scalar_selections_keep_exact_types_polarities_and_name_hygiene",
            "nested_effectful_scalar_selections_reject_unproved_exports_effects_and_signatures",
            "nested_effectful_scalar_selections_bound_depth_tree_expression_and_predicate_captures",
            "for depth in [8, 9]", "for depth in [5, 6]", "for count in [126, 127]", "for count in [30, 31]"],
    },
    DevTensorDriftCheckSpec {
        id: "native-nested-effectful-selection-registration-not-private-name",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/scalar_control_tests.rs",
        required_patterns: &["registered_scalar_guards_remain_intact_without_name_prefix_admission",
            "user_named_boundary", "ordinary", "assert!(!helpers.is_empty())", "&before"],
    },
    DevTensorDriftCheckSpec {
        id: "native-nested-effectful-selection-emitted-order-types-policy-and-checkpoint",
        path: "tools/nuisc/src/aot_application_effect_call_tests.rs",
        required_patterns: &["native_nested_effectful_scalar_selections_order_predicates_after_each_ancestor_guard",
            "native_nested_effectful_scalar_selections_keep_policy_order_and_checkpoint_vetoes",
            "nested_then", "nested_else", "assert_eq!(predicate_carriers, 3)", "lacks dependency order"],
    },
    DevTensorDriftCheckSpec {
        id: "native-nested-effectful-selection-real-poisoned-predicates-and-restoration",
        path: "tools/nuis/tests/native_session_workflow/effect_calls.rs",
        required_patterns: &["native_nested_effectful_scalar_selections_build_cache_restore_and_mask_inactive_conditions",
            "native_nested_effectful_scalar_selections_trap_on_selected_predicates_or_arguments_before_publication",
            "for outer in [false, true]", "for inner in [false, true]", "for leaf in [false, true]",
            "for _ in 0..3", "fs::remove_dir_all(project.0.join(\".nuis\"))", "SIGILL", "SIGTRAP"],
    },
    DevTensorDriftCheckSpec {
        id: "native-nested-effectful-selection-scoped-ancestor-contract",
        path: "docs/reference/nuis-native-effectful-scalar-selection-v1.md",
        required_patterns: &["## Nested Existing-Scalar Updates", "eight selection levels",
            "64 tree nodes", "shared 256-expression-node budget", "descendant predicates",
            "registered guard boundaries", "160 successful transitions"],
    },
    DevTensorDriftCheckSpec {
        id: "native-nested-effectful-selection-complete-six-field-history",
        path: "tools/nuis/src/dev_tensor_data.rs",
        required_patterns: &["Nested guarded scalar updates follow-up:",
            "Previous one-sided scalar-rebinding checkpoint:", "Previous one-sided scalar-rebinding task checkpoint:",
            "Previous one-sided scalar-rebinding blocker checkpoint:", "Previous one-sided scalar-rebinding action checkpoint:",
            "Previous one-sided scalar-rebinding artifact checkpoint:",
            "Prove sequential statements inside guarded scalar regions", "native_nested_effectful_scalar_selections"],
    },
];
