use crate::dev_tensor_drift::DevTensorDriftCheckSpec;

pub(crate) const DEV_TENSOR_RUNTIME_NSLD_DRIFT_CHECKS: &[DevTensorDriftCheckSpec] = &[
    DevTensorDriftCheckSpec {
        id: "nustar-domain-contract-completeness-status",
        path: "tools/nuisc/src/registry_contract.rs",
        required_patterns: &[
            "contract_status",
            "required_domain_contract_groups",
            "missing_domain_contract_groups",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nustar-domain-contract-completeness-json",
        path: "tools/nuisc/src/registry_domain_json.rs",
        required_patterns: &[
            "contract_complete",
            "required_contract_groups",
            "missing_contract_groups",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nustar-dispatch-readiness-contract",
        path: "tools/nuisc/src/registry_contract.rs",
        required_patterns: &[
            "NUSTAR_DOMAIN_CONTRACT_GROUP_DISPATCH_READINESS",
            "dispatch_readiness_summary",
            "required_dispatch_readiness_signals",
            "dispatch_bridge_materialized",
            "execution_readiness_materialized",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nustar-dispatch-readiness-json",
        path: "tools/nuisc/src/registry_domain_json.rs",
        required_patterns: &[
            "dispatch_readiness_status",
            "dispatch_bridge_materialized",
            "execution_readiness_materialized",
            "dispatch_readiness_missing_signals",
            "NUSTAR_DOMAIN_CONTRACT_GROUP_DISPATCH_READINESS",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nustar-dispatch-readiness-link-plan-consumption",
        path: "tools/nuis/src/surface_render/link_plan.rs",
        required_patterns: &[
            "backend_artifact_ready",
            "link_plan_heterogeneous_backend_artifact_ready_units",
            "link_plan_heterogeneous_backend_artifact_first_unready",
            "link_plan_heterogeneous_domain_registry_dispatch_ready_units",
            "link_plan_heterogeneous_domain_registry_dispatch_first_blocked",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nustar-dispatch-readiness-link-plan-model",
        path: "tools/nuis/src/surface_render/link_plan_readiness.rs",
        required_patterns: &[
            "registry_dispatch_readiness_status",
            "registry_dispatch_readiness_ready",
            "registry_dispatch_missing_signals",
            "registry_dispatch_bridge_materialized",
            "registry_execution_readiness_materialized",
            "backend_artifact_key",
            "backend_artifact_candidate",
            "backend_artifact_missing_signals",
            "registry_dispatch_readiness_blocked",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nustar-dispatch-readiness-workflow-consumption",
        path: "tools/nuis/src/workflow/link_plan_domain.rs",
        required_patterns: &[
            "registry_dispatch_readiness_status",
            "registry_dispatch_readiness_ready",
            "registry_dispatch_missing_signals",
            "registry_dispatch_bridge_materialized",
            "registry_execution_readiness_materialized",
            "backend_artifact_key",
            "backend_artifact_candidate",
            "backend_artifact_ready",
            "backend_artifact_missing_signals",
            "backend_artifact_first_unready",
            "registry_dispatch_readiness_blocked",
            "workflow_registry_dispatch_readiness",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nustar-dispatch-readiness-nsld-final-output-ordering",
        path: "tools/nsld/src/main_final_executable_backend_artifact_tests.rs",
        required_patterns: &[
            "final_executable_output_orders_nustar_dispatch_blockers_before_output_bytes",
            "nustar-dispatch:official.ghost:registry-unavailable",
            "backend_artifact_candidate_count",
            "backend_artifact_ready_count",
            "backend_artifact_selection_status",
            "backend_artifact_ordered_candidates",
            "backend_artifact_selected_candidate",
            "backend_artifact_selection_reason",
            "backend_artifact_assembly_status",
            "backend_artifact_selected_payload_path",
            "backend_artifact_selected_payload_consumed",
            "backend_artifact_assembly_first_blocker",
            "backend_artifact_first_unready",
            "nustar-backend-artifact:ghost:ghost:none:unready",
            "final_executable_output_selects_first_ready_backend_artifact_candidate_by_priority",
            "consumed-by-final-layout",
            "final-executable-output:missing",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-final-output-payload-trace-object-evidence",
        path: "tools/nsld/src/main_final_executable_output_tests.rs",
        required_patterns: &[
            "self_contained_final_executable_emit_writes_nsld_owned_output",
            "payload_execution_trace_protocol",
            "payload_execution_trace_available",
            "payload_execution_trace_record_count",
            "payload_execution_trace_ready_record_count",
            "handoff-payload-trace-to-nsdb",
            "object_output_family",
            "object_output_magic_status",
            "object_output_magic",
            "0xcffaedfe",
            "final_executable_output_rejects_tampered_output_bytes",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-drive-safe-next-gate-contract",
        path: "tools/nsld/src/drive_gate_tests.rs",
        required_patterns: &[
            "drive_until_clean_report_json_exposes_boundary_safe_next_contract",
            "nsld-drive-safe-next-v1",
            "safe_next_gate_required",
            "safe_next_gate_action",
            "explicit-boundary-crossing-command-available",
            "NUIS_NSLD_HOST_FINALIZER_POLICY=allow-host-invoke",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-object-output-multi-backend-identity",
        path: "tools/nsld/src/object_identity.rs",
        required_patterns: &[
            "object_identity_recognizes_mach_o_elf_and_coff_magic",
            "object_identity_reports_missing_and_invalid_magic",
            "object_magic_status",
            "object_family_for_format",
            "object_magic_hex",
            "0xcffaedfe",
            "0x7f454c46",
            "0x6486",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-final-output-nsdb-handoff-persistence",
        path: "tools/nsld/src/main_final_executable_output_nsdb_handoff_tests.rs",
        required_patterns: &[
            "final_executable_output_command_persists_nsdb_handoff_record",
            "final_executable_output_replay_blocks_pending_hetero_closure",
            "nuis-nsdb-payload-execution-handoff-v1",
            "nsdb-yir-payload-execution-trace-v1",
            "nuis-hetero-execution-closure-v1",
            "host-runner-backend-artifact-payload:not-observed",
            "nsld-final-executable-output",
            "payload-trace:container-loader:nuis.bootstrap.lifecycle.v1",
            "final_output_nsdb_handoff_persisted",
            "final_output_nsdb_handoff_record_count",
            "final_output_nsdb_replay_status",
            "replay-evidence-ready",
            "final_output_nsdb_replay_checkpoint_count",
            "final_output_nsdb_replayable_checkpoint_count",
            "handoff-payload-trace-to-nsdb",
            "object_package_summary_contract",
            "nsld-object-package-summary-v1",
            "object_package_summary_status",
            "object_package_summary_replay_status",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-lib-payload-replay-summary",
        path: "tools/nsdb/src/lib.rs",
        required_patterns: &[
            "PayloadExecutionReplaySummary",
            "payload_execution_replay_summary",
            "payload_execution_replay_summary_consumes_ready_handoff",
            "payload_execution_replay_summary_blocks_pending_hetero_closure",
            "nsdb-payload-execution-replay-plan-v1",
            "hetero-execution-closure",
            "replay-evidence-ready",
            "checkpoint_count",
            "replayable_checkpoint_count",
            "payload-execution-replay:no-checkpoints",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "workflow-final-output-replay-closure-gate",
        path: "tools/nuis/src/main_tests/workflow_surface.rs",
        required_patterns: &[
            "workflow_json_blocks_replay_when_hetero_closure_is_pending",
            "nuis-hetero-execution-closure-v1",
            "host-runner-backend-artifact-payload:not-observed",
            "nsld_final_executable_output_nsdb_replay_ready",
            "nsld_final_executable_output_nsdb_replay_first_blocker",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "release-check-final-output-replay-closure-gate",
        path: "tools/nuis/src/main_tests/artifact_runtime_release_check.rs",
        required_patterns: &[
            "release_check_summary_json_blocks_pending_hetero_closure",
            "nuis-hetero-execution-closure-v1",
            "host-runner-backend-artifact-payload:not-observed",
            "nsld_final_executable_output_nsdb_replay_ready",
            "nsld_final_executable_output_nsdb_replay_first_blocker",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "project-doctor-link-plan-replay-closure-gate",
        path: "tools/nuis/src/main_tests/project_health.rs",
        required_patterns: &[
            "project_doctor_json_promotes_pending_hetero_closure_from_link_plan",
            "project-doctor-link-plan",
            "inspect-nsdb-replay-evidence",
            "nsld_final_executable_output_nsdb_replay_ready",
            "nsld_final_executable_output_nsdb_replay_first_blocker",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "run-artifact-json-final-output-replay-surface",
        path: "tools/nuis/src/main_tests/artifact_runtime_run_artifact.rs",
        required_patterns: &[
            "run_artifact_json_reports_ready_after_final_pipeline_exists",
            "run_artifact_json_blocks_missing_backend_payload_replay_gate",
            "payload-execution-replay:blocked-checkpoint",
            "nsdb-payload-execution-replay-plan-v1",
            "nsld_final_executable_output_nsdb_replay_ready",
            "nsld_final_executable_output_nsdb_replay_status",
            "nsld_final_executable_output_nsdb_replay_first_blocker",
            "nsld_final_executable_output_object_package_contract",
            "nsld_final_executable_output_object_package_ready",
            "nsld_final_executable_output_debugger_transcript_contract",
            "nsld_final_executable_output_debugger_transcript_ready",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "link-plan-json-final-output-replay-surface",
        path: "tools/nuis/src/surface_render/link_plan_nsld_tail.rs",
        required_patterns: &[
            "nsld_final_executable_output_nsdb_replay_contract",
            "nsld_final_executable_output_nsdb_replay_ready",
            "nsld_final_executable_output_nsdb_replay_status",
            "nsld_final_executable_output_nsdb_replay_first_blocker",
            "nsld_final_executable_output_object_package_contract",
            "nsld_final_executable_output_object_package_ready",
            "nsld_final_executable_output_debugger_transcript_contract",
            "nsld_final_executable_output_debugger_transcript_ready",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "link-plan-text-final-output-replay-surface",
        path: "tools/nuis/src/surface_render/link_plan_text_nsld_output.rs",
        required_patterns: &[
            "nsld_final_executable_output_nsdb_replay_contract",
            "nsld_final_executable_output_nsdb_replay_ready",
            "nsld_final_executable_output_nsdb_replay_status",
            "nsld_final_executable_output_nsdb_replay_first_blocker",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "workflow-text-final-output-replay-surface",
        path: "tools/nuis/src/workflow/command.rs",
        required_patterns: &[
            "nsld_final_executable_output_nsdb_replay_contract",
            "nsld_final_executable_output_nsdb_replay_ready",
            "nsld_final_executable_output_nsdb_replay_status",
            "nsld_final_executable_output_nsdb_replay_first_blocker",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nustar-backend-artifact-image-role-evidence",
        path: "tools/nsld/src/main_final_executable_image_backend_payload_tests.rs",
        required_patterns: &[
            "final_executable_image_dry_run_reports_backend_artifact_payload_roles",
            "backend_artifact_payload_count",
            "backend_artifact_payload_present_count",
            "backend_artifact_payload_role_status",
            "backend_artifact_payload_ids",
            "backend_artifact_payload_kinds",
            "backend_artifact_payload_first_missing",
            "nustar-backend-artifact:kernel:aarch64:apple-silicon-cpu",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-final-output-launcher-handoff-evidence",
        path: "tools/nsld/src/main_final_executable_launcher_output_tests.rs",
        required_patterns: &[
            "final_executable_launcher_manifest_describes_runnable_nsb_entry",
            "verify_final_executable_launcher_manifest_reports_drift",
            "final_executable_launcher_dry_run_rejects_tampered_final_output_bytes",
            "nuis-host-launcher-manifest-v1",
            "nuis-host-launcher-dry-run-v1",
            "nsld-final-output-handoff-v1",
            "handoff-container-loader-first-payload",
            "payload0004.scheduler-metadata",
            "host-launcher:final-output-hash-mismatch",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-device-provider-sample-final-output-evidence",
        path: "tools/nsld/src/final_executable_provider_sample.rs",
        required_patterns: &[
            "nsld_device_provider_sample_evidence",
            "nuis.nsdb.device-provider-samples.toml",
            "nuis-device-provider-samples-v1",
            "nsdb-yir-device-provider-sample-v1",
            "provider-sample-pending",
            "provider-sample-materialized",
            "provider-sample-blocked",
            "blocked-provider-sample",
            "device-provider-sample",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-device-provider-sample-final-output-surface",
        path: "tools/nsld/src/main_final_executable_provider_sample_tests.rs",
        required_patterns: &[
            "final_output_reports_pending_device_provider_sample_manifest_as_blocker",
            "final_output_accepts_ready_device_provider_sample_manifest",
            "check_report_exposes_device_provider_sample_manifest_summary",
            "artifact_chain_points_provider_sample_boundary_to_nsdb_materializer",
            "artifact_chain_points_blocked_provider_sample_boundary_to_payload_repair",
            "device_provider_sample_manifest_available",
            "device_provider_sample_manifest_status",
            "device_provider_sample_manifest_blocked_record_count",
            "device_provider_sample_manifest_first_blocker",
            "final_executable_output_device_provider_sample_manifest_status",
            "final_executable_output_device_provider_sample_manifest_blocked_record_count",
            "repair-provider-output-payload",
            "repair provider output payload diagnostics",
            "nsdb materialize-provider-samples",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-device-provider-sample-drive-boundary",
        path: "tools/nsld/src/drive_provider_sample_tests.rs",
        required_patterns: &[
            "drive_apply_materializes_provider_sample_boundary_via_nsdb",
            "drive_apply_keeps_blocked_provider_sample_repair_boundary_read_only",
            "drive_until_clean_names_provider_sample_boundary_stop_reason",
            "drive_until_clean_names_blocked_provider_sample_repair_stop_reason",
            "drive_until_clean_stops_at_blocked_provider_sample_repair_boundary",
            "write_blocked_device_provider_sample_manifest",
            "materialize-provider-samples",
            "repair-provider-output-payload",
            "provider-sample-materialization-required",
            "provider-output-payload-repair-required",
            "blocked-boundary-diagnostic-repair",
            "whitelisted-artifact-mutation-loop-diagnostic-repair",
            "applied materialize-provider-samples",
            "safe_next_action",
            "safe_next_command",
            "safe_next_reason",
            "safe_next_contract",
            "safe_next_gate_required",
            "safe_next_gate_action",
            "explicit-boundary-crossing-command-available",
            "nsld_drive_apply",
            "mutation_policy",
            "whitelisted-boundary-materialization",
            "blocked-read-only-boundary",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-drive-gate-json-safe-next-contract",
        path: "tools/nsld/src/drive_gate_tests.rs",
        required_patterns: &[
            "drive_apply_report_json_exposes_gate_fields_when_boundary_is_read_only",
            "drive_until_clean_report_json_exposes_boundary_safe_next_contract",
            "nsld_drive_apply",
            "nsld_drive_until_clean",
            "safe_next_action",
            "safe_next_command",
            "safe_next_reason",
            "explicit-boundary-crossing-command-available",
            "stop_gate_action",
            "stop_gate_env_assignments",
            "stop_crossing_env_assignments",
            "stop_crossing_command_resolved",
            "whitelisted-artifact-mutation-loop-stopped",
            "blocked-read-only-boundary",
            "NUIS_NSLD_ALLOW_HOST_FINALIZER=1",
        ],
    },
];
