use crate::dev_tensor_drift::DevTensorDriftCheckSpec;

pub(crate) const CHECKS: &[DevTensorDriftCheckSpec] = &[
    DevTensorDriftCheckSpec {
        id: "bounded-buffer-branch-carry-admission",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/validation.rs",
        required_patterns: &[
            "!header_inputs.contains(name)",
            "name != &prepared.binding_name",
            "!mutations.writable.contains(name)",
            "inputs.insert(name.clone())",
            "carries.push(name.clone())",
            "PreparedLoopCompare::Lt",
            "PreparedLoopCompare::Gt",
            "NirExpr::StoreAt",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "bounded-buffer-branch-state-projections",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/branches.rs",
        required_patterns: &[
            "Snapshot once",
            "scalar_carries::state_type",
            "scalar_carries::value",
            "inputs.extend(carries.iter().cloned())",
            "scalar_carries::projected_call",
            "NirStmt::Return(Some(returned.clone()))",
            "__nuis_branch_state",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "bounded-buffer-branch-pass-through-guard",
        path: "tools/nuisc/src/lowering/direct_calls/control_boundaries.rs",
        required_patterns: &[
            "is_pass_through_guard_seed",
            "i64_parameter",
            "fields.len() == definition.fields.len()",
            "type_name == &ty.name",
            "name == &field.name",
            "lower_guard_return",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "bounded-buffer-branch-carry-execution",
        path: "tools/nuisc/tests/buffer_while/branch_carries.rs",
        required_patterns: &[
            "branch_carries_preserve_untaken_and_zero_trip_seeds",
            "nested_branch_carries_merge_all_slots_and_preserve_sequential_rebindings",
            "branch_carry_predicate_is_snapshotted_before_state_and_buffer_updates",
            "branch_carry_traps_keep_source_order_before_and_after_writes",
            "branch_carries_reject_mutable_headers_non_i64_state_and_ownership_control",
            "branch_carries_share_callback_fuel_without_committing_failed_state",
            "branch_carries_keep_linear_helper_growth_and_generated_name_isolation",
            "branch_carries_feed_subsequent_loops",
            "let branches = 32",
            "completion_status().is_err()",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "pure-helper-analysis-expansion-budget",
        path: "tools/nuisc/src/lowering/loop_purity_inline_budget.rs",
        required_patterns: &[
            "MAX_INLINE_EXPR_NODES",
            "MAX_INLINE_EXPR_DEPTH",
            "checked_sub(cost)",
            "bounded_inline_substitution",
            "_ => return false",
            "inline_budget_counts_cast_depth_and_declines_unknown_shapes",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "pure-helper-analysis-expansion-evidence",
        path: "tools/nuisc/src/lowering/loop_purity_inline_tests.rs",
        required_patterns: &[
            "inline_collection_rejects_effectful_prefix_before_expansion",
            "inline_collection_bounds_pure_rebinding_expansion_without_losing_purity",
            "inline_collection_does_not_classify_effectful_return_as_pure",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "pixelmagic-branch-carry-native-evidence",
        path: "tools/nuisc/tests/pixelmagic_buffer_loop.rs",
        required_patterns: &[
            "real control boundary and branch-local count",
            "checkerboard_red_total",
            "row helpers must retain nested pixel loops",
            "checkerboard_row_start",
            "checkerboard_row_end",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "pixelmagic-branch-carry-packaged-evidence",
        path: "tools/nuis/tests/headless_image_loop.rs",
        required_patterns: &[
            "real control boundary and branch-local count",
            "checkerboard_red_total",
            "packaged row helpers must retain nested pixel loops",
            "checkerboard_row_start",
            "checkerboard_row_end",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "bounded-buffer-recursive-loop-admission",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/validation.rs",
        required_patterns: &[
            "protected.contains(&prepared.binding_name)",
            "protected.extend(header_inputs.iter().cloned())",
            "carries.retain(|name| scope.contains_key(name))",
            "&mutations.protected",
            "inputs.extend(plan.header_inputs)",
            "plan.carries.into_iter().chain([plan.induction])",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "bounded-buffer-recursive-loop-outlining",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/branches.rs",
        required_patterns: &[
            "validated nested loop",
            "outline_loop(",
            "carries.retain(|name| scope.contains_key(name))",
            "NirStmt::While { body, .. } => collect_bindings(body, names)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "bounded-buffer-recursive-loop-evidence",
        path: "tools/nuisc/tests/buffer_while/nested_loops.rs",
        required_patterns: &[
            "nested_buffer_loops_execute_real_helpers_and_reset_iteration_locals",
            "nested_loops_preserve_persistent_counters_and_support_scalar_only_children",
            "nested_descending_loops_and_outer_dependent_bounds_keep_exact_state",
            "branch_nested_loops_return_visible_locals_without_speculating_bounds",
            "nested_loop_traps_keep_source_order_across_loop_boundaries",
            "nested_loops_reject_ancestor_header_mutation_and_unsupported_control",
            "nested_loops_share_session_fuel_and_never_commit_failed_callback_state",
            "recursive_loops_retain_scalar_callees_and_linear_helper_growth",
            "let depth = 8",
            "native_run",
            "event_budgeted",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nir-branch-constant-state-join",
        path: "tools/nuisc/src/optimize.rs",
        required_patterns: &[
            "Only the enclosing block knows",
            "*env = then_env",
            "*env = else_env",
            "then_env.get(name) == Some(value) && else_env.get(name) == Some(value)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nir-branch-constant-state-join-evidence",
        path: "tools/nuisc/src/optimize_branch_tests.rs",
        required_patterns: &[
            "dynamic_branch_invalidates_rebound_literals_without_pruning_live_arm_state",
            "selected_constant_branch_uses_its_outgoing_environment",
            "nested_loop_mutation_invalidates_the_enclosing_branch_literal",
            "dynamic_branch_keeps_unchanged_literals_without_leaking_branch_locals",
        ],
    },
];
