use crate::dev_tensor_drift::DevTensorDriftCheckSpec;

pub(crate) const DEV_TENSOR_RUNTIME_MUTEX_DRIFT_CHECKS: &[DevTensorDriftCheckSpec] = &[
    DevTensorDriftCheckSpec {
        id: "scheduler-mutex-yir-contract",
        path: "crates/yir-core/src/mutex_contract.rs",
        required_patterns: &[
            "mutation=lease-replace-release-epoch-v1",
            "CPU_SHARED_MUTEX_RUNTIME_METADATA",
            "mutex_contract=scheduler-handle-v1",
            "visibility=acquire-release-epoch-v1",
            "authority=linear-guard-v1",
            "authority=linear-permit-lease-v1",
            "permit_cardinality=share-literal-1-to-64-v1",
            "permit_policy=one-shot-generation-bound-v1",
            "payload_policy=scalar-i32-i64-native-staged-fallback-v1",
            "lifecycle=explicit-close-revoke-v1",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "scheduler-mutex-cpu-contract-validation",
        path: "crates/yir-domain-cpu/src/describe_async.rs",
        required_patterns: &[
            "describe_mutex_effect",
            "CPU_MUTEX_RUNTIME_METADATA",
            "rejects_shared_mutex_close_lifecycle_drift",
            "mutex_lease_replace",
            "shared_mutex_share_metadata_keeps_static_cardinality_dependency",
            "rejects_shared_mutex_metadata_drift",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "scheduler-mutex-runtime-visibility",
        path: "tools/nuisc/src/aot_c_shim_mutex_runtime.rs",
        required_patterns: &[
            "NuisSchedulerMutexSlotV1",
            "NuisSchedulerMutexPermitSlotV1",
            "NUIS_SCHEDULER_MUTEX_SCALAR_I32_V1",
            "nuis_scheduler_mutex_new_scalar_v1",
            "nuis_scheduler_mutex_value_scalar_v1",
            "nuis_scheduler_mutex_lease_replace_scalar_v1",
            "nuis_scheduler_mutex_lease_replace_i64_v1",
            "nuis_scheduler_mutex_permit_cardinality_get_v1",
            "nuis_scheduler_mutex_permit_i64_v1",
            "nuis_scheduler_mutex_permit_lock_i64_v1",
            "nuis_scheduler_mutex_lease_unlock_i64_v1",
            "memory_order_acquire",
            "memory_order_release",
            "acquire_epoch",
            "release_epoch",
            "nuis_scheduler_mutex_shared_close_i64_v1",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "scheduler-mutex-contention-runtime-smoke",
        path: "tools/nuisc/src/aot_tests/shim_mutex.rs",
        required_patterns: &[
            "scheduler_mutex_handles_reject_contention_and_publish_release_epoch",
            "scheduler_mutex_scalar_protocol_preserves_signed_i32_bits",
            "scheduler_shared_mutex_permits_are_lane_bound_and_one_shot",
            "hold_mutex_worker",
            "contend_mutex_worker",
            "nuis_scheduler_mutex_rejected_close_count_get_v1",
            "nuis_scheduler_mutex_lease_replace_i64_v1",
            "nuis_scheduler_mutex_lease_replace_scalar_v1",
            "nuis_scheduler_mutex_permit_cardinality_get_v1",
            "nuis_scheduler_mutex_active_permit_count_get_v1",
            "nuis_scheduler_mutex_rejected_permit_count_get_v1",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "scheduler-shared-mutex-llvm-native-lowering",
        path: "crates/yir-lower-llvm/src/mutex_capability_lowering.rs",
        required_patterns: &[
            "nuis_scheduler_mutex_share_i64_v1",
            "nuis_scheduler_mutex_shared_close_i64_v1",
            "nuis_scheduler_mutex_permit_i64_v1",
            "nuis_scheduler_mutex_permit_lock_i64_v1",
            "permit cardinality is not static",
            "emit_mutex_replace",
            "MutexPermitLlvmValueRef",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "scheduler-mutex-scalar-llvm-abi",
        path: "crates/yir-lower-llvm/src/mutex_scalar.rs",
        required_patterns: &[
            "MutexScalarKind::I32",
            "MutexScalarKind::I64",
            "nuis_scheduler_mutex_new_scalar_v1",
            "nuis_scheduler_mutex_value_scalar_v1",
            "nuis_scheduler_mutex_lease_replace_scalar_v1",
            "nuis_scheduler_mutex_lease_replace_i64_v1",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "branch-local-concurrency-selected-prefix-lowering",
        path: "tools/nuisc/src/lowering/if_lowering_runtime.rs",
        required_patterns: &[
            "extract_selectable_runtime_binding_head",
            "is_selectable_cpu_runtime_expr",
            "lower_selected_cpu_runtime_effect",
            "lower_selectable_runtime_prefix",
            "Runtime-prefix lowering is speculative",
            "lower_selected_cpu_mutex_capability_effect",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "branch-local-concurrency-exactly-once-regression",
        path: "tools/nuisc/tests/thread_mutex_branch_compile.rs",
        required_patterns: &[
            "hello_thread_mutex_if_lock_branch.ns",
            "hello_thread_mutex_match_join_result_branch.ns",
            "lowers_branch_local_mutex_lock_through_one_selected_runtime_prefix",
            "lowers_branch_local_thread_result_through_one_selected_runtime_prefix",
            "task_shared_mutex_branch_demo",
            "lowers_branch_local_shared_mutex_capabilities_exactly_once",
            "rejects_branch_selected_shared_mutex_static_contract_drift",
            "CPU_SHARED_MUTEX_RUNTIME_METADATA",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "branch-local-concurrency-native-cancel-unlock",
        path: "tools/nuis/tests/concurrency_branch_native_smoke.rs",
        required_patterns: &[
            "task_branch_cancel_unlock_demo",
            "task_shared_mutex_permit_demo",
            "branch_selected_cancel_and_unlock_reach_native_binary_once_per_chain",
            "shared_mutex_permits_cross_two_native_task_boundaries_without_handle_copies",
            "task_shared_mutex_cardinality_demo",
            "static_three_lane_cardinality_reaches_native_runtime",
            "task_shared_mutex_replace_demo",
            "lease_replace_is_visible_across_native_task_permits",
            "task_shared_mutex_branch_demo",
            "branch_selected_shared_mutex_capabilities_reach_native_binary_once",
            "task_shared_mutex_i32_demo",
            "i32_shared_mutex_payload_crosses_native_task_boundaries_without_type_erasure",
            "Some(25)",
            "Some(33)",
            "Some(43)",
            "mutex_contract=scheduler-handle-v1",
            "deferred lowering for cpu.mutex",
            "Some(81)",
            "Some(89)",
            "Some(65)",
            "Some(63)",
        ],
    },
];
