use crate::dev_tensor_drift::DevTensorDriftCheckSpec;

pub(super) const CHECKS: &[DevTensorDriftCheckSpec] = &[
    DevTensorDriftCheckSpec {
        id: "native-return-invariant-bounded-identity-proof",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/control_loops/return_invariant_facts.rs",
        required_patterns: &[
            "type Origin = (String, Vec<String>)",
            "fields.len() > 64",
            "self.stable.get_mut(name)",
            "stable[index] &=",
            "self.block(then_body, &mut left, depth + 1)?",
            "self.block(else_body, &mut right, depth + 1)?",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-invariant-compact-rewrite",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/control_loops/return_invariants.rs",
        required_patterns: &[
            "const MAX_WORK: usize = 65_536",
            "const MAX_DEPTH: usize = 64",
            "body: self.effects(body, records, depth + 1)?",
            "exits::return_owned(iteration.effects, self.signal)",
            "__nuis_loop_fields",
            "__nuis_loop_snapshot",
            "self.mutable_value(record, &temporary)?",
            "self.read(record, &[], 0)?",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-invariant-nested-fixed-point",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/control_loops/return_invariant_loops.rs",
        required_patterns: &[
            "for observation in &mut self.observations",
            "if old == new { old.clone() } else { None }",
            "self.budget.tick(depth)?",
            "self.observations.push(env.clone())",
            "self.block(body, &mut iteration, depth + 1)?",
            "if &summary == env",
            "*env = summary",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-invariant-nested-negative-proofs",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/control_loops/return_invariant_loops_tests.rs",
        required_patterns: &[
            "return_invariant_loops_reach_a_fixed_point_for_delayed_aliases",
            "return_invariant_loops_do_not_forget_zero_trips_or_restored_exit_snapshots",
            "return_invariant_loops_reject_escaping_locals_bad_conditions_and_exhaustion",
            "Budget(MAX_WORK - measured.0 - 1)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-invariant-nested-differential-proof",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/control_loops/return_invariant_nested_tests.rs",
        required_patterns: &[
            "return_invariant_nested_loops_match_observed_indices_exits_and_arithmetic_oracle",
            "return_invariants_keep_admitted_inner_plan_when_outer_revalidation_fails",
            "assert_eq!(prepared.body, inner.0)",
            "assert_eq!(prepared.structs, inner.1)",
            "carry.tag + i * 1000",
            "assert_eq!(actual, execute(&independent)",
            "assert_eq!(actual, expected",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-invariant-transactional-admission",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/control_loops/returns.rs",
        required_patterns: &[
            "catalog.get(&function.name)?",
            "invariants::rewrite(",
            "for nested in [true, false]",
            "candidate_layouts",
            "scalar_helpers::validate_control_body",
            "plan.structs = structs",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-invariant-private-definitions",
        path: "tools/nuisc/src/lowering/buffer_loop_outline.rs",
        required_patterns: &[
            "for definition in plan.structs",
            "names.insert(definition.name.clone())",
            "module.structs.push(definition)",
            "let value_layouts = control_values::TypedLayouts::collect(module)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-invariant-negative-proof-regressions",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/control_loops/return_invariant_facts_tests.rs",
        required_patterns: &[
            "return_invariant_facts_check_every_write_not_only_the_backedge",
            "return_invariant_facts_merge_both_arms_without_leaking_local_aliases",
            "return_invariant_facts_do_not_equate_roots_calls_or_algebra",
            "return_invariant_facts_reject_unknown_shapes_types_and_exhausted_proofs",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-invariant-differential-regressions",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/control_loops/return_invariants_tests.rs",
        required_patterns: &[
            "return_invariants_keep_all_stable_rhs_without_creating_empty_record_types",
            "return_invariants_fresh_names_and_failed_attempts_leave_input_untouched",
            "return_invariants_match_independent_payloads_zero_trips_and_selected_traps",
            "assert_eq!(actual, execute(&independent)",
            "assert_eq!(actual, expected",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-invariant-scoped-capture-plan",
        path: "tools/nuisc/src/lowering/direct_calls/capture_params.rs",
        required_patterns: &[
            "fn for_scoped(",
            "Self::records(leaves, function, module, Some(&records))",
            "plan.supports_scoped(function, seeds)",
            "slots.extend((start..index).map(Slot::Scalar))",
            "Slot::Bools(_) => false",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-invariant-capture-plan-regressions",
        path: "tools/nuisc/src/lowering/direct_calls/capture_params_tests.rs",
        required_patterns: &[
            "scoped_record_plans_keep_boolean_slots_and_unproven_records_independent",
            "assert_eq!(flat.len(), 65)",
            "assert!(!ordinary.supports_scoped",
            "CapturePlan::records(malformed",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-signal-minted-provenance",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/control_loops/returns.rs",
        required_patterns: &[
            "struct Signal(String)",
            "fn prepare(",
            "catalog.get(&function.name)?",
            "signal: Signal(state.flag)",
            "reserve_references(&function.body, &mut names)?",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-signal-function-local-routing",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/control_loops/nested.rs",
        required_patterns: &[
            "return_signals: &BTreeMap<String, returns::Signal>",
            "return_signal: return_signals.get(&function.name)",
            "return_signal: Option<&'a returns::Signal>",
            "self.return_signal",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-signal-bounded-ownership-proof",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/control_loops/return_signal.rs",
        required_patterns: &[
            "const MAX_WORK: usize = 65_536",
            "const MAX_DEPTH: usize = 64",
            "self.remaining.checked_sub(1)?",
            "body.get(index + 1) != Some(&NirStmt::Break)",
            "then_body == &[NirStmt::Break]",
            "self.block(body, false, depth + 1)?",
            "NirExpr::Var(name) if name != self.signal",
            "_ => return None",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-signal-canonical-last-slot",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/control_loops/exits.rs",
        required_patterns: &[
            "return_signal: Option<&returns::Signal>",
            "return_signal::can_share(iteration.effects, signal.name())",
            "control_flow::normalize_return_exit(",
            "Some(name) != breaking.as_ref()",
            "carries.push(flag.clone())",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-signal-normalizer-reuse",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/control_flow.rs",
        required_patterns: &[
            "fn normalize_return_exit(",
            "normalize_with_step(effects, scope, step, true, Some(signal))",
            "let break_only = breaking.is_some() && !contains_continue(effects)",
            "body.insert(0, set_flag(breaking, 0))",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-signal-negative-proof-regressions",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/control_loops/return_signal_proof_tests.rs",
        required_patterns: &[
            "return_signal_requires_canonical_publication_before_every_owned_break",
            "return_signal_keeps_child_breaks_local_and_continues_independent",
            "return_signal_rejects_hidden_reads_and_unknown_syntax",
            "return_signal_bounds_both_work_and_depth_without_granting_partial_proof",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-signal-differential-regressions",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/control_loops/return_signal_tests.rs",
        required_patterns: &[
            "return_signal_only_reuses_minted_signals_and_keeps_the_canonical_slot_last",
            "return_signal_matches_independent_lowering_and_source_exit_oracles",
            "returns::normalize(function, &layouts)",
            "yir.nodes.reverse()",
            "execute(&independent)",
            "fixture::expected(case, leading, limit, stop)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-signal-ordinary-execution",
        path: "tools/nuisc/tests/control_flow_syntax_native/scoped_field_seeds.rs",
        required_patterns: &[
            "scoped_return_signal_preserves_native_break_continue_and_parent_propagation",
            "return_signal::CASES",
            "return_signal::expected(case, leading, limit, stop)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-signal-source-free-arity",
        path: "tools/nuis/tests/native_session_workflow/sparse_typed_records.rs",
        required_patterns: &[
            "native_materialized_nested_returns_restore_complete_state_without_sources",
            "&[12, 16]",
            "assert_eq!(iterations, captures)",
            "materialize-artifact",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-full-width-source-free-restoration",
        path: "tools/nuis/tests/native_session_workflow/sparse_typed_records.rs",
        required_patterns: &[
            "native_full_width_nested_returns_restore_complete_state_without_sources",
            "check_captures(&source, true, &[5, 11], 64)",
            "assert_eq!(iterations, captures)",
            "(9..width).map",
            "fs::remove_file(project.0.join(\"main.ns\"))",
            "verify(&project, &restored, branches, width)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-index-recovery-observation-budget",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/continuation_reads.rs",
        required_patterns: &[
            "const MAX_WORK: usize = 65_536",
            "const MAX_DEPTH: usize = 64",
            "let continuation = continuation?",
            "self.remaining.checked_sub(self.last.len())?",
            "**last > index",
            "_ => None",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-index-recovery-conservative-analysis",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/continuation_reads_tests.rs",
        required_patterns: &[
            "continuation_reads_include_generated_outputs_and_ignore_past_reads",
            "continuation_reads_keep_all_branches_headers_checked_operands_and_redefinitions",
            "continuation_reads_bound_scan_depth_and_suffix_materialization",
            "continuation_reads_reject_unknown_syntax_without_partial_authority",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-index-recovery-exit-gate",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/control_loops/exits.rs",
        required_patterns: &[
            "if iteration.leading && recover_index",
            "boundary.after.push(copy(induction, &advanced))",
            "carries.push(flag.clone())",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-index-recovery-enclosing-continuation",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/control_loops/nested.rs",
        required_patterns: &[
            "self.block(then_body, scope.clone(), after.as_ref())",
            "continuation.is_none_or(|reads| reads.contains(induction))",
            "let returned_reads = carries.iter().cloned().collect()",
            "Some(&returned_reads)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-index-recovery-generated-arm-output",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/branches.rs",
        required_patterns: &[
            "let arm_reads = carries.iter().cloned().collect()",
            "Some(&arm_reads)",
            "reads.as_mut().and_then(|reads| reads.after(position))",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-index-recovery-reference-regressions",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/control_loops/index_recovery_tests.rs",
        required_patterns: &[
            "index_recovery_only_elides_unobserved_exits_and_keeps_helper_outputs",
            "index_recovery_matches_independent_results_across_zero_trips_and_backedges",
            "yir.nodes.reverse()",
            "case.recoveries",
            "yir_core::Value::Int(expected)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-index-recovery-ordinary-execution",
        path: "tools/nuisc/tests/control_flow_syntax_native/scoped_field_seeds.rs",
        required_patterns: &[
            "scoped_index_recovery_preserves_native_exits_and_generated_backedges",
            "scoped_index_recovery_keeps_selected_work_and_skips_unreachable_traps",
            "index_recovery_selected_trap",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-index-recovery-loop-exit-inputs",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/scalar_control.rs",
        required_patterns: &[
            "| NirStmt::Expr(value)",
            "NirStmt::Break | NirStmt::Continue => {}",
            "collect_inputs(body, inputs)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-index-recovery-loop-exit-input-regression",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/scalar_control_tests.rs",
        required_patterns: &[
            "scalar_branch_inputs_keep_loop_effects_without_reading_exit_markers",
            "then_body: vec![NirStmt::Break]",
            "else_body: vec![NirStmt::Continue]",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-storage-admission-revalidation",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/control_loops/returns.rs",
        required_patterns: &[
            "Source admission always checks independent storage",
            "catalog.get(&function.name)?",
            "storage::candidate(function, layouts, catalog)?",
            "scalar_helpers::validate_control_body(function, &plan.body, catalog, layouts)?",
            "if independent",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-storage-candidate-scope",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/control_loops/return_storage.rs",
        required_patterns: &[
            "layouts.get(&result.name)?",
            "mutable && ty == *result && !scope.contains_key(name)",
            "_ => break",
            "writes.extend(sequences::carry_names(body))",
            "candidates.into_iter().find(|name| writes.contains(name))",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-storage-regressions",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/control_loops/return_storage_tests.rs",
        required_patterns: &[
            "return_storage_reuses_exact_initialized_records_without_name_conventions",
            "return_storage_revalidates_new_inner_writes_without_weakening_source_order",
            "return_storage_never_grants_original_invalid_reads_or_return_types",
            "return_storage_keeps_parameters_constants_late_and_scoped_bindings_independent",
            "return_storage_matches_independent_payload_execution_and_selected_traps",
            "assert_eq!(actual, execute(&independent)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-storage-width-boundaries",
        path: "tools/nuisc/tests/native_application_bridge/sparse_typed_return_carries.rs",
        required_patterns: &[
            "for width in [9, 30, 31, 57, 58, 59, 60, 61, 62, 63, 64]",
            "for width in [9, 63, 64]",
            "for (width, rejected) in [(64, 65)]",
            "tag: i32_from_i64(17), enabled: !enabled",
            "assert_eq!(carried_widths(&compiled.yir), [width - 1, width])",
            "assert_eq!(carried_widths(&compiled.yir), [width - 1, width + 1])",
            "check_compact(&source, cases, width - 4)",
            "typed_sparse_nested_returns_preserve_invariant_negative_zero_and_nan_payloads",
            "including private return/control state",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-nested-return-source-fixture",
        path: "tools/nuisc/tests/control_flow_syntax_native/scoped_return_typed_record_carries.ns",
        required_patterns: &[
            "while j < inner_limit",
            "if j == 2",
            "return State { left: selected, right: carry.right, count: limit",
            "if j > 1 { let unreachable = 1 / (j - j); }",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-nested-return-control-seed-proof",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_record_loop_demand_tests.rs",
        required_patterns: &[
            "materialized_word_loop_returns_keep_pending_values_and_control_seeds",
            "call.seeds.len()).max(), Some(9)",
            "assert_eq!(widths, [8, 9])",
            "call.break_on_return).count(), 2",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-nested-return-atomic-execution",
        path: "tools/nuisc/tests/native_application_bridge/sparse_typed_return_carries.rs",
        required_patterns: &[
            "typed_sparse_nested_returns_publish_current_snapshots_and_skip_dead_suffixes",
            "typed_sparse_nested_returns_share_work_budgets_without_partial_publication",
            "typed_sparse_nested_return_payload_failures_leave_the_last_state_untouched",
            "typed_sparse_nested_loops_keep_64_word_budget_failures_atomic",
            "typed_sparse_nested_returns_reject_unused_noncanonical_inputs_before_work",
            "typed_sparse_nested_returns_reject_expanded_private_state_before_native_emission",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-nested-return-budget-probe",
        path: "tools/nuisc/tests/native_application_bridge/sparse_typed_return_probe.rs",
        required_patterns: &[
            "assert_eq!(state_words(reference.state()), input)",
            "matches!(run.status.signal(), Some(4 | 5))",
            "expected.extend(case.remaining)",
            "expected.repeat(repeats)",
            "Re-enter the same callback after exact exhaustion to prove fresh counters",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-nested-return-ordinary-execution",
        path: "tools/nuisc/tests/control_flow_syntax_native/scoped_field_seeds.rs",
        required_patterns: &[
            "materialized_typed_record_nested_returns_execute_and_keep_payload_traps_lazy",
            "materialized_nested_return_trap",
            "materialized_nested_return_lazy_{limit}",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-nested-return-source-free-workflow",
        path: "tools/nuis/tests/native_session_workflow/sparse_typed_records.rs",
        required_patterns: &[
            "native_materialized_nested_returns_restore_complete_state_without_sources",
            "scoped_return_typed_record_carries.ns",
            "fs::remove_file(project.0.join(\"main.ns\"))",
            "materialize-artifact",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-nested-return-private-bound-diagnostic",
        path: "crates/yir-lower-llvm/src/native_session/loops/scoped.rs",
        required_patterns: &[
            "carries.seeds.len() > super::super::MAX_SCALAR_SLOTS",
            "carried words exceed the {}-word native limit",
            "including private return/control state",
            "65 carried words exceed the 64-word native limit",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-nested-return-documented-boundary",
        path: "docs/reference/nuis-native-scalar-value-returns-v1.md",
        required_patterns: &[
            "### Nested Return And Budget Proof",
            "Invariant-field promotion reduces the inner backedge to N-1 words and the outer backedge to N",
            "Changing that tag removes the proof and",
            "still rejects at 65 outer words",
            "reduce nested return snapshot carries while preserving observed exits",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-materialized-word-demand-proof",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_record_demand.rs",
        required_patterns: &[
            "bindings::normalize(&mut probe)",
            "live.remove(name)",
            "field_type(source, &path[1..], self.layouts)? != *ty",
            "live.entry(name).or_default().extend(paths)",
            "self.observe(value, &mut live)",
            "self.loop_entry(condition, body, live, depth)",
            "materialized_record_demand_bounds_work_and_depth_without_partial_authority",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-materialized-word-input-proof",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_record_words.rs",
        required_patterns: &[
            "demand::reconstruction(function, position, &name, &input, definitions, layouts)",
            "*value = reconstruction",
            "normalized.insert(*index, input)",
            "value == &reconstruction",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-materialized-word-join-regressions",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_record_joins_tests.rs",
        required_patterns: &[
            "materialized_word_joins_project_input_without_erasing_outer_assignments",
            "materialized_word_joins_union_fallthrough_reads_and_kill_overwritten_versions",
            "materialized_word_joins_keep_all_caller_codec_proof_transactional",
            "materialized_word_joins_keep_unused_checked_field_dependencies",
            "materialized_word_joins_analyze_hygienic_copies_without_renaming_control",
            "materialized_word_joins_keep_early_return_and_opaque_full_input_demand",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-materialized-word-native-execution",
        path: "tools/nuisc/tests/native_application_bridge/sparse_typed_record_carries.rs",
        required_patterns: &[
            "typed_materialized_join_snapshots_keep_current_words_and_complete_64_word_state",
            "check_alternating(fixture::join_source)",
            "assert_eq!(call.seeds.len(), width)",
            "assert_eq!(call.operands.len(), 6)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-materialized-word-ordinary-execution",
        path: "tools/nuisc/tests/control_flow_syntax_native/scoped_field_seeds.rs",
        required_patterns: &[
            "materialized_typed_record_joins_execute_and_keep_selected_traps",
            "materialized_record_join_trap",
            "materialized_record_join_lazy_{limit}",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-materialized-word-source-free-workflow",
        path: "tools/nuis/tests/native_session_workflow/sparse_typed_records.rs",
        required_patterns: &[
            "native_materialized_join_snapshots_restore_current_versions_without_sources",
            "scoped_join_typed_record_carries.ns",
            "materialize-artifact",
            "fs::remove_file(project.0.join(\"main.ns\"))",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-materialized-word-documented-boundary",
        path: "docs/reference/nuis-native-scalar-value-returns-v1.md",
        required_patterns: &[
            "### Materialized Join Proof",
            "Changing nested loops use bounded fixed-point and lexical exit-edge proof",
            "reduce nested return snapshot carries while preserving observed exits",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-materialized-word-loop-fixed-point",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_record_demand.rs",
        required_patterns: &[
            "let mut header = after.clone()",
            "self.observe(condition, &mut header)",
            "self.merge(&mut next, before)",
            "if next == header",
            "NirStmt::Break => live = targets?.on_break.clone()",
            "NirStmt::Continue => live = targets?.on_continue.clone()",
            "materialized_record_demand_bounds_nested_fixed_point_work",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-materialized-word-loop-exit-regressions",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_record_loop_demand_tests.rs",
        required_patterns: &[
            "materialized_word_loops_reach_a_fixed_point_for_cyclic_snapshots",
            "materialized_word_loops_execute_cyclic_snapshots_before_and_after_projection",
            "materialized_word_loops_keep_zero_trip_break_continue_and_return_demands",
            "materialized_word_loops_bind_breaks_to_the_nearest_loop",
            "materialized_word_loops_bind_continues_to_the_nearest_header",
            "materialized_word_loops_reject_exits_without_a_loop_target",
            "materialized_word_loops_observe_headers_and_unused_checked_fields",
            "materialized_word_loops_keep_whole_input_and_all_caller_proofs",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-materialized-word-loop-source-fixture",
        path: "tools/nuisc/tests/control_flow_syntax_native/scoped_loop_typed_record_carries.ns",
        required_patterns: &[
            "while i < limit",
            "let inner_limit = i % 3",
            "while j < inner_limit",
            "let selected = selected; let previous = selected",
            "value: previous.value + 0.5",
            "gain: previous.gain + 0.5",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-materialized-word-loop-native-execution",
        path: "tools/nuisc/tests/native_application_bridge/sparse_typed_record_carries.rs",
        required_patterns: &[
            "typed_materialized_loop_snapshots_keep_current_words_and_complete_64_word_state",
            "typed_materialized_loop_snapshots_keep_inner_break_and_continue_local",
            "find(|call| call.seeds.len() == width)",
            "assert_eq!(call.operands.len(), 6)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-materialized-word-loop-ordinary-execution",
        path: "tools/nuisc/tests/control_flow_syntax_native/scoped_field_seeds.rs",
        required_patterns: &[
            "materialized_typed_record_loops_execute_and_keep_nested_traps_lazy",
            "materialized_record_loop_trap",
            "materialized_loop_lazy_{exit}",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-materialized-word-loop-source-free-workflow",
        path: "tools/nuis/tests/native_session_workflow/sparse_typed_records.rs",
        required_patterns: &[
            "native_materialized_loop_snapshots_restore_nested_versions_without_sources",
            "scoped_loop_typed_record_carries.ns",
            "fs::remove_file(project.0.join(\"main.ns\"))",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-materialized-word-loop-documented-boundary",
        path: "docs/reference/nuis-native-scalar-value-returns-v1.md",
        required_patterns: &[
            "### Nested Loop Demand",
            "Break uses the nearest loop exit; continue uses that loop's header",
            "reduce nested return snapshot carries while preserving observed exits",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "private-record-join-copy-family-proof",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_join_plan.rs",
        required_patterns: &[
            "binding.valid &= ty.is_some()",
            "binding.ty.as_ref() == ty",
            "(scope != binding.scope && !info.returns) || (info.in_loop && rebound)",
            "!control_values::supported_type(ty, layouts)",
            "path.len() == 1 || field_type(ty, &path[1..], layouts).is_none()",
            "inputs.insert(param.name.clone(), paths.clone())",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "private-record-join-input-reconstruction",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_joins.rs",
        required_patterns: &[
            "plan::collect(function, layouts)",
            "control_values::zero_value(&param.ty, layouts)",
            "__nuis_capture_join_input",
            "names.get(name)",
            "function.body.splice(0..0, seeds)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "private-record-join-reconstruction-regressions",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_join_tests.rs",
        required_patterns: &[
            "fallthrough_record_joins_project_fields_without_changing_public_inputs",
            "fallthrough_record_joins_keep_nested_reaching_values_and_old_copies",
            "fallthrough_record_joins_retain_loop_reads_without_rewriting_backedges",
            "fallthrough_record_joins_preserve_selected_unused_constructor_work_and_calls",
            "fallthrough_record_joins_project_copy_families_and_nominal_prefixes",
            "fallthrough_record_joins_leave_whole_uses_and_computed_callers_unchanged",
            "fallthrough_record_joins_require_exact_types_and_preserve_name_hygiene",
            "fallthrough_record_joins_preserve_scalar_kinds",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "private-record-join-source-composition",
        path: "tools/nuisc/tests/native_application_bridge/typed_alias_capture_fixture.rs",
        required_patterns: &[
            "pub fn join_source()",
            "return current.f0 + old.f3;",
            "3 => \"999\"",
            "fields(\"old.f63 / old.f1 + 27\")",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "private-record-loop-entry-reconstruction-regressions",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_loop_join_tests.rs",
        required_patterns: &[
            "loop_record_inputs_preserve_zero_trips_and_per_trip_snapshots",
            "loop_record_inputs_preserve_nested_writes_and_control_exits",
            "loop_record_inputs_keep_checked_unused_constructor_work_per_trip",
            "loop_record_inputs_follow_cyclic_copies_and_nominal_prefixes",
            "loop_record_inputs_reject_whole_escapes_and_computed_callers_transactionally",
            "loop_record_reconstruction_retains_original_bodies_and_exact_type_vetoes",
            "divisor - i + 1",
            "assert_eq!(&helper.body[2..], &before.body[1..])",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "private-record-loop-snapshot-source-composition",
        path: "tools/nuisc/tests/native_application_bridge/typed_alias_capture_fixture.rs",
        required_patterns: &[
            "pub fn loop_join_source()",
            "let current = current; let before = current;",
            "before.marker + current.marker",
            "divisor: 0, marker: 0, unused: 7 }, 0)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "private-record-loop-snapshot-native-lifecycle",
        path: "tools/nuisc/tests/native_application_bridge/typed_sparse_captures.rs",
        required_patterns: &[
            "typed_sparse_captures_preserve_loop_record_snapshots",
            "let source = aliases::loop_join_source()",
            "assert_eq!(slots, [0, 1, 2, 4])",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "private-record-loop-snapshot-source-free-restoration",
        path: "tools/nuis/tests/native_session_workflow/capture_fields.rs",
        required_patterns: &[
            "native_sparse_captures_loop_snapshots_build_cache_and_restore_without_sources",
            "check_sparse_workflow_with_iteration(",
            "&aliases::loop_join_source()",
        ],
    },
];
