use crate::dev_tensor::{DevTensorCell, DevTensorExpectedCoordinate};

pub(crate) const DEV_TENSOR_CELLS: &[DevTensorCell] = &[
    DevTensorCell {
        architecture: "compiler-frontdoor",
        module: "nuis-cli",
        function: "workflow-and-project-orientation",
        status: "stable",
        progress: 93,
        bootstrap_critical: true,
        closure_role: "developer-frontdoor",
        evidence: "workflow/project-status/project-doctor JSON and text frontdoors are regression-backed, share closure_summary status/ready/blocker/action/command fields, document closure_summary as the canonical human closure line, and project-status now promotes built-project link-plan evidence into project-status-link-plan closure guidance instead of stopping at artifact-ready",
        next_step: "mirror task-card navigation language into workflow/frontdoor docs next to the closure_summary reading rule so status-visible weakest task-card and project closure guidance converge on one frontdoor story",
        blocker: "project-status can now consume link-plan closure evidence, but tensor task-card navigation language is still mostly in dev-tensor output rather than the frontdoor docs",
        next_action: "mirror task-card navigation language into workflow/frontdoor docs next to the closure_summary reading rule",
        validation_command: "cargo test -q -p nuis project_status && cargo test -q -p nuis workflow_surface",
        expected_artifact: "workflow/project-status/project-doctor summary surfaces expose one shared closure_summary contract, project-status consumes link-plan/nsld closure evidence after build, and docs define both closure_summary plus tensor task-card as the canonical human reading order",
    },
    DevTensorCell {
        architecture: "compiler-frontdoor",
        module: "nuis-cli",
        function: "artifact-runtime-closure",
        status: "stable",
        progress: 100,
        bootstrap_critical: true,
        closure_role: "artifact-execution-frontdoor",
        evidence: "run-artifact, workflow, artifact-doctor, project-status/project-doctor, build-report, release-check logs, release-check JSON summary renderer, release-check --json CLI entrypoint, command-level release-check --json stdout smoke, explicit runtime materialization policy fields, nsld handoff, self-contained host-runner probe fields, nsdb-ready launch_evidence contract fields, nsdb-facing payload execution trace records, persisted run-artifact nsdb payload handoff metadata, persisted hetero runtime trace metadata, generated payload decoder manifests, generated decoder manifest surface mirrors, nsdb inspect hetero runtime trace consumption, workflow/artifact-doctor persisted handoff mirrors, workflow/artifact-doctor launch-evidence mirrors, nsdb inspect payload handoff event consumption, nsdb event filters, dedicated nsdb events command, nsdb replay-plan checkpoints with stable frame/value anchors, value-sample references, trace-backed sample resolution status, value-sample materialization descriptors, value slot/schema metadata, typed value snapshot references, concrete metadata content summaries, opaque payload file summaries, decoder capability/detail-level boundaries, spec-driven lightweight payload format probes, external decoder manifest loading, ASCII/hex external magic probes, external decoder capability/detail declarations, decoder manifest diagnostics, inspect-level decoder manifest summaries, per-record decoder manifest diagnostics, decoder manifest protocol/schema version checks, and final-output boundary reports share closure evidence",
        next_step: "turn per-domain run-artifact trace records into real device execution samples without coupling release-check to runtime execution",
        blocker: "release-check now explicitly remains a pure readiness gate, so real runtime evidence must come from run-artifact/device sample lanes",
        next_action: "turn per-domain run-artifact trace records into real device execution samples without coupling release-check to runtime execution",
        validation_command: "cargo test -q -p nuis run_artifact && cargo test -q -p nsdb",
        expected_artifact: "workflow/artifact-doctor/project-status/project-doctor/build-report/release-check-summary/release-check-json/nsdb-facing surfaces report persisted debugger handoff/runtime trace metadata, generated payload decoder manifests, generated decoder manifest mirrors, and nsdb tooling consumes/filter/replay-plans it through inspect, events, replay-plan frame/value anchors, value-sample references, trace-backed sample-resolution status, materialized sample descriptors, value slot/schema metadata, typed value snapshot refs, value content summaries, opaque payload file summaries, decoder registry status, decoder capability/detail boundaries, spec-driven lightweight payload format probes, external decoder manifest loading, ASCII/hex external magic probes, external decoder capability/detail declarations, decoder manifest diagnostics, inspect-level decoder manifest summaries, per-record decoder manifest diagnostics, and decoder manifest protocol/schema version checks",
    },
    DevTensorCell {
        architecture: "linker-toolchain",
        module: "nsld",
        function: "artifact-chain-drive",
        status: "stable",
        progress: 93,
        bootstrap_critical: true,
        closure_role: "linker-artifact-chain",
        evidence: "nsld drive can apply whitelisted artifact-chain steps, stop cleanly on host-assisted final output boundaries, report mutation_policy, expose nsld-drive-safe-next-v1 gate fields, and Nuis closure_summary now promotes mutating drive recommendations into nsld-drive-safe-next next-action/command selection through the command-set safe_next probe",
        next_step: "carry the safe-next closure gate into self-contained native-binary and hetero artifact smokes so drive-safe mutation remains the canonical path across CPU/shader/kernel payload chains",
        blocker: "safe-next is now first-class in workflow/project-status closure summaries, but native-binary and hetero artifact smokes still need broader end-to-end coverage for the same gate",
        next_action: "mirror nsld-drive-safe-next closure behavior through native-binary and hetero artifact smoke paths",
        validation_command: "cargo test -q -p nuis workflow_surface && cargo test -q -p nuis project_status && cargo test -q -p nsld drive",
        expected_artifact: "nsld drive JSON reports mutation_policy, safe_next_action, safe_next_command, safe_next_reason, safe_next_contract, safe_next_gate_required, safe_next_gate_action, and crossing command fields while Nuis closure_summary recommends nsld-drive-safe-next plus the safe_next probe command whenever artifact-chain mutation is available",
    },
    DevTensorCell {
        architecture: "linker-toolchain",
        module: "nsld",
        function: "final-output-boundary",
        status: "active",
        progress: 93,
        bootstrap_critical: true,
        closure_role: "executable-output-boundary",
        evidence: "final-executable-output reports normalized boundary status, materialization status, recommended next action, path presence, ownership, runnable candidate, blockers, Nuis/Nsld mirrors, self-contained relocation-safe images, container-loader handoff readiness, first-payload execution metadata from the final output itself, nsdb-facing payload execution trace metadata, command-level persistence of the first-payload trace as an nsdb handoff record, nsdb replay-plan readiness, replay-evidence-ready status, checkpoint/replayable counts, stable replay next-action/next-command fields, and Nuis frontdoor mirrors/closure selection for replay-ready or replay-blocked states",
        next_step: "carry final-output replay next-action/next-command fields into self-contained native-binary and hetero artifact smoke assertions so execution closure and debugger replay closure share one boundary contract",
        blocker: "final-output replay evidence now has stable next-action/next-command fields, but native-binary and hetero smoke coverage still needs to assert those gates end-to-end",
        next_action: "mirror final-output replay gate fields through native-binary and hetero artifact smoke paths",
        validation_command: "cargo test -q -p nsld final_executable_output && cargo test -q -p nuis workflow_surface && cargo test -q -p nuis --test self_contained_nsb_smoke",
        expected_artifact: "final-output boundary emits trace-ready first-payload metadata, persists an nsdb debugger handoff TOML, exposes replay next-action/next-command fields, and workflow mirrors replay-evidence-ready plus checkpoint/replayable counts and commands",
    },
    DevTensorCell {
        architecture: "heterogeneous-runtime",
        module: "nustar",
        function: "registered-domain-contracts",
        status: "active",
        progress: 93,
        bootstrap_critical: true,
        closure_role: "heterogeneous-domain-registration",
        evidence: "domain units, lowering targets, backend families, target devices, backend artifact candidate readiness, contract completeness status, contract drift checks, heterogeneous domain readiness, dispatch readiness, bridge materialization, link-plan readiness consumption, Nsld final-output blocker ordering, Nsld backend artifact candidate selection status/selected candidate, selected-candidate assembly boundary status, final-layout backend artifact payload consumption, image dry-run backend artifact payload role evidence, artifact-doctor/workflow JSON mirrors, run-artifact launch evidence backend payload traces, run-artifact hetero runtime trace readiness fields, per-domain runtime trace records, provider-scoped deferred device execution sample descriptors, sample descriptor summary counts/providers/provider-families, pending-validation counts, provider handoff status/target fields, persisted provider handoff queue records, sample input/output evidence fields, validation status fields, requested provider runner adapter contracts, materialized provider runner adapter results, and host-runner direct NSB backend payload role-table scans are mirrored through frontdoor surfaces",
        next_step: "let Nustar backends replace requested host-simulated provider runner adapters with real Metal/CoreML provider samples behind the same adapter contract",
        blocker: "run-artifact now records requested provider runner adapter contracts, but Metal/CoreML provider samples are still host-simulated rather than real device execution",
        next_action: "replace requested host-simulated provider runner adapters with real Metal/CoreML provider samples behind the same adapter contract",
        validation_command: "cargo test -q -p nuis artifact_runtime && cargo test -q -p nuis --test self_contained_nsb_smoke",
        expected_artifact: "run-artifact and host-runner surfaces expose backend payload role-table evidence plus provider-scoped device execution sample descriptors with provider-family summaries, pending-validation counts, provider handoff status, persisted handoff queue records, input/output evidence, validation status, and requested provider runner adapter contracts carried into nsdb materialization",
    },
    DevTensorCell {
        architecture: "standard-library",
        module: "std",
        function: "host-io-filesystem-text",
        status: "usable",
        progress: 93,
        bootstrap_critical: true,
        closure_role: "bootstrap-std-foundation",
        evidence: "std IO/filesystem/text/stdin examples, std_filesystem_smoke light lane, observable CLI smoke, direct cli_wc_demo argv/file/text-stats run, direct cli_pgm_invert_demo image-shaped file read/write run, reusable StdReportContracts, direct cli_report_file_demo argv/file/text report output, PixelMagic/WitSage report-file workloads, official_galaxy_hetero_smoke shader/kernel artifact smokes, direct run-artifact hetero trace record assertions, explicit nsdb provider-sample materialization, deterministic provider-sample artifact files with hash evidence, and registered nuis-provider-runner-adapter-v1 host-simulated adapter descriptors for official PixelMagic/WitSage traces anchor the current host-backed CLI plus hetero-build foundation",
        next_step: "connect the image-shaped std CLI lane to PixelMagic inputs so filesystem/text preprocessing can feed shader payload validation instead of remaining a standalone host utility",
        blocker: "std now has a real PGM file transform smoke, but PixelMagic shader samples still do not consume std-preprocessed image artifacts",
        next_action: "connect the image-shaped std CLI lane to PixelMagic inputs",
        validation_command: "cargo test -q -p nuis --test std_filesystem_smoke && cargo test -q -p nuis --test official_galaxy_hetero_smoke",
        expected_artifact: "Std observable CLI smoke covers stdin, wc-style file/text stats, PGM image-shaped file transformation, report-file generation, PixelMagic/WitSage report workloads, hetero domain artifacts, run-artifact trace records, materialized provider-sample manifests, deterministic provider-sample artifact evidence, and provider runner adapter contract metadata",
    },
    DevTensorCell {
        architecture: "standard-library",
        module: "pixelmagic",
        function: "image-processing-lane",
        status: "early",
        progress: 40,
        bootstrap_critical: false,
        closure_role: "official-compute-package",
        evidence: "PixelMagic has official package contracts, shader surfaces, domain demos, a std-report-file workload, a checked shader pipeline build smoke that emits Metal sidecar/payload artifacts, and direct run-artifact assertions for shader hetero runtime trace records plus provider-scoped sample validation descriptors",
        next_step: "connect PixelMagic shader trace records to real image-kernel output validation and device execution samples",
        blocker: "PixelMagic emits shader artifacts and run-artifact trace records, but still lacks real image-kernel output validation and device execution samples",
        next_action: "connect PixelMagic shader trace records to real image-kernel output validation and device execution samples",
        validation_command: "cargo test -q -p nuis --test official_galaxy_hetero_smoke",
        expected_artifact: "PixelMagic shader pipeline emits checked Metal sidecar/payload artifacts, report-file evidence, run-artifact trace records, and provider-scoped sample validation descriptors",
    },
    DevTensorCell {
        architecture: "standard-library",
        module: "witsage",
        function: "classical-ml-lane",
        status: "early",
        progress: 34,
        bootstrap_critical: false,
        closure_role: "official-compute-package",
        evidence: "WitSage has official package contracts, kernel-facing surfaces, domain demos, a std-report-file workload, a checked kernel tensor build smoke that emits CoreML sidecar/payload artifacts, and direct run-artifact assertions for kernel hetero runtime trace records plus provider-scoped sample validation descriptors",
        next_step: "connect WitSage kernel trace records to broader matrix/vector runtime validation and device execution samples",
        blocker: "WitSage emits kernel tensor artifacts and run-artifact trace records, but still lacks broader matrix/vector runtime validation and device execution samples",
        next_action: "connect WitSage kernel trace records to broader matrix/vector runtime validation and device execution samples",
        validation_command: "cargo test -q -p nuis --test official_galaxy_hetero_smoke",
        expected_artifact: "WitSage kernel tensor workload emits checked CoreML sidecar/payload artifacts, report-file evidence, run-artifact trace records, and provider-scoped sample validation descriptors",
    },
    DevTensorCell {
        architecture: "language-core",
        module: "nuisc",
        function: "type-control-flow-generics",
        status: "active",
        progress: 93,
        bootstrap_critical: true,
        closure_role: "language-self-hosting-foundation",
        evidence: "control flow, generics, traits, pointers, floats, enums, error handling, inference, task_result_enum, generic trait-bound guarded-match, GLM buffer, generic_result_buffer_lambda helper with Err fallback, if-expression runtime coverage, nested partial expected-type Result.Ok propagation, nested if/match expected-type Result.Ok/Err propagation, project-source no-annotation higher-order try/await Result binding propagation, async_value YIR boundary lowering, runnable no-annotation try/await Result HOF binary coverage, explicit void-main return lowering, report-file main-return runtime coverage, and unconstrained Result.Ok/Err constructor diagnostics have staged CLI/IR/runtime coverage",
        next_step: "extend async Result try/await HOF runtime coverage across Err-path and run-artifact/self-check evidence",
        blocker: "no-annotation try/await Result HOF now builds and runs on the Ok path, but Err-path async Result lowering and run-artifact evidence still need coverage",
        next_action: "add Err-path async Result HOF runtime smoke and run-artifact assertions for the no-annotation project",
        validation_command: "cargo test -q -p nuis --test language_bootstrap_smoke && cargo test -q -p nuisc zero_arg_expectations && cargo check -q -p nuisc",
        expected_artifact: "language bootstrap smoke covers combined generic Result/buffer/lambda helpers, Err fallback, partial expected-type Ok propagation, match/if edge cases, project-source no-annotation try/await Result HOF inference and runnable Ok-path binary output, zero-arg expectation tests lock unconstrained Result constructor diagnostics, nested if/match Result.Ok/Err constructors retain concrete type arguments, and frontend/runtime coverage proves no-annotation higher-order try/await Result bindings retain Error",
    },
    DevTensorCell {
        architecture: "native-binary-system",
        module: "nsb-nsld",
        function: "self-owned-binary-assembly",
        status: "active",
        progress: 93,
        bootstrap_critical: true,
        closure_role: "self-owned-native-binary",
        evidence: "Nsld container, object/image dry-runs, final executable pipeline, self-contained NSB image emission, container-metadata-first image payload layout, container-payload relocation patching, launcher dry-run checks, host entrypoint handoff stub emission, host-runner image/container probe, Nsld pipeline self-owned image status, entrypoint materialization status, Nuis frontdoor consumption, run-artifact first-payload launch evidence, nsdb-facing payload execution trace records, persisted nsdb payload handoff metadata, nsdb inspect payload execution events, nsdb events query contract fields, nsdb replay-plan checkpoint source/query-result fields, nsld final-output consumption of nsdb replay summary checkpoint counts, workflow closure_summary replay-ready/replay-blocked gate selection, and self-contained workflow/artifact smoke promotion of replay-ready final-output evidence into a ready closure_summary are visible",
        next_step: "carry replay-ready self-contained NSB closure evidence into release-check/build-report surfaces and nsld-owned object package summaries",
        blocker: "self-contained workflow closure can now become replay-ready, but release-check/build-report and package-summary surfaces still need the same final-output replay closure assertion",
        next_action: "mirror replay-ready self-contained NSB closure evidence through release-check/build-report package summaries",
        validation_command: "cargo test -q -p nuis --test self_contained_nsb_smoke && cargo test -q -p nsdb && cargo test -q -p nsld final_executable_output",
        expected_artifact: "self-owned NSB artifacts expose payload execution trace records, persist them as nsdb handoff metadata, nsdb summarizes replayable checkpoints, nsld final-output reports replay-evidence-ready plus checkpoint/replayable counts, workflow closure_summary promotes replay-ready final output into a ready frontdoor task, and release/package summaries mirror that closure",
    },
    DevTensorCell {
        architecture: "developer-system",
        module: "dev-tensor",
        function: "architecture-module-function-progress-model",
        status: "active",
        progress: 92,
        bootstrap_critical: true,
        closure_role: "bootstrap-progress-model",
        evidence: "tensor frontdoor maps progress by architecture, module, and function, summarizes through nuis status, runs drift checks over key docs/tests/frontdoor fields, exposes weakest-bootstrap guidance plus a protocolized nuis-dev-tensor-task-card-v1 surface, mirrors task-card protocol/source/status/ready/coordinate/action/command/expected artifact through nuis status, reports stdlib manifest-backed coordinate coverage, validates milestone-owned coordinate coverage against the Rust snapshot, derives expected coordinates from the milestone manifest with an explicit fallback, and surfaces generated coordinate cache metadata without writing cache files",
        next_step: "use the ready task-card protocol to drive the next weakest bootstrap coordinate while keeping new linker/stdlib coordinates registered as they land",
        blocker: "tensor navigation and task-card derivation are protocolized and status-visible; remaining risk is keeping workflow/status consumers and new linker/stdlib coordinates aligned as final-output closure changes",
        next_action: "continue mainline closure work from the ready nuis-dev-tensor-task-card-v1 coordinate",
        validation_command: "cargo test -q -p nuis dev_tensor",
        expected_artifact: "dev-tensor reports milestone-derived coordinate cache metadata plus weakest task-card protocol/source/status/ready/coordinate, priority reason, action, validation command, expected artifact, and mirrors the actionable task-card fields through nuis status",
    },
];

pub(crate) const DEV_TENSOR_EXPECTED_COORDINATES: &[DevTensorExpectedCoordinate] = &[
    DevTensorExpectedCoordinate {
        architecture: "compiler-frontdoor",
        module: "nuis-cli",
        function: "workflow-and-project-orientation",
        milestone: "alpha-frontdoor",
        required: true,
    },
    DevTensorExpectedCoordinate {
        architecture: "compiler-frontdoor",
        module: "nuis-cli",
        function: "artifact-runtime-closure",
        milestone: "alpha-frontdoor",
        required: true,
    },
    DevTensorExpectedCoordinate {
        architecture: "linker-toolchain",
        module: "nsld",
        function: "artifact-chain-drive",
        milestone: "alpha-linker",
        required: true,
    },
    DevTensorExpectedCoordinate {
        architecture: "linker-toolchain",
        module: "nsld",
        function: "final-output-boundary",
        milestone: "alpha-linker",
        required: true,
    },
    DevTensorExpectedCoordinate {
        architecture: "heterogeneous-runtime",
        module: "nustar",
        function: "registered-domain-contracts",
        milestone: "alpha-heterogeneous",
        required: true,
    },
    DevTensorExpectedCoordinate {
        architecture: "standard-library",
        module: "std",
        function: "host-io-filesystem-text",
        milestone: "alpha-stdlib",
        required: true,
    },
    DevTensorExpectedCoordinate {
        architecture: "standard-library",
        module: "pixelmagic",
        function: "image-processing-lane",
        milestone: "alpha-official-galaxy",
        required: false,
    },
    DevTensorExpectedCoordinate {
        architecture: "standard-library",
        module: "witsage",
        function: "classical-ml-lane",
        milestone: "alpha-official-galaxy",
        required: false,
    },
    DevTensorExpectedCoordinate {
        architecture: "language-core",
        module: "nuisc",
        function: "type-control-flow-generics",
        milestone: "alpha-language-core",
        required: true,
    },
    DevTensorExpectedCoordinate {
        architecture: "native-binary-system",
        module: "nsb-nsld",
        function: "self-owned-binary-assembly",
        milestone: "alpha-native-binary",
        required: true,
    },
    DevTensorExpectedCoordinate {
        architecture: "developer-system",
        module: "dev-tensor",
        function: "architecture-module-function-progress-model",
        milestone: "alpha-governance",
        required: true,
    },
];
