use crate::dev_tensor_drift::DevTensorDriftCheckSpec;

pub(crate) const DEV_TENSOR_RUNTIME_SHADER_GRAPH_DRIFT_CHECKS: &[DevTensorDriftCheckSpec] = &[
    DevTensorDriftCheckSpec {
        id: "runtime-small-immutable-resource-contract",
        path: "crates/yir-core/src/provider_runtime_resource.rs",
        required_patterns: &["pub struct DispatchResource", "immutable-le", "self.bytes.len() > 64", "runtime resource content identity mismatch"],
    },
    DevTensorDriftCheckSpec {
        id: "shader-fragment-uniform-contract",
        path: "crates/yir-domain-shader/src/fragment_uniform.rs",
        required_patterns: &["nuis-shader-fragment-uniform-v1", "pub struct ShaderFragmentUniform", "uniform_tuple", "fragment_uniform_capability", "without implicit conversion"],
    },
    DevTensorDriftCheckSpec {
        id: "shader-uniform-front-to-yir-regression",
        path: "tools/nuisc/src/lowering/tests_async_runtime/domain_primitives.rs",
        required_patterns: &["typed_uniform_draw_survives_nir_optimization_and_yir_verification", "simplify_nir_module", "verify_nir_module", "draw.op.args.len(), 5"],
    },
    DevTensorDriftCheckSpec {
        id: "shader-uniform-lowering-reflection-regression",
        path: "tools/nuisc/src/shader_msl_render_emitter_tests.rs",
        required_patterns: &["lowers_one_typed_fragment_uniform_into_content_bound_msl_reflection", "native_binding_normalization_is_idempotent_before_resource_reflection", "constant float4& tint [[buffer(2)]]"],
    },
    DevTensorDriftCheckSpec {
        id: "metal-immutable-uniform-upload",
        path: "tools/nsdb/provider-runners/metal_rgba8_render.m",
        required_patterns: &["nuis-metal-rgba8-render-provider-runner-v3", "MTLArgumentAccessReadOnly", "MTLDataTypeFloat4", "newBufferWithBytes:uniformValues", "setFragmentBuffer:uniformBuffer"],
    },
    DevTensorDriftCheckSpec {
        id: "runtime-uniform-replay-identity-regression",
        path: "crates/yir-runtime-host/src/provider_result_draw_tests.rs",
        required_patterns: &["replay_uniform_identity_is_checked_before_consuming_frame", "ShaderFragmentUniform", "remaining(&adapter), 1"],
    },
    DevTensorDriftCheckSpec {
        id: "ns-nova-real-tint-pixel-regression",
        path: "tools/nuis/src/artifact_device_sample_shader_render_tests.rs",
        required_patterns: &["Nuis-owned uniform bytes must change actual GPU pixels", "compiled tint uniform must switch identical coverage from red to blue", "offline execution must not invent runtime uniform data", "differs from admitted code capability"],
    },
    DevTensorDriftCheckSpec {
        id: "shader-canonical-vertex-rejects-substitution",
        path: "tools/nuisc/src/shader_msl_render_emitter_tests.rs",
        required_patterns: &[
            "rejects_vertex_semantics_that_the_canonical_emitter_would_discard",
            "canonical_vertex_comments_do_not_change_lowering_or_fake_entry_detection",
            "refusing to substitute fullscreen geometry",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "runtime-dispatch-typed-scalar-wire",
        path: "crates/yir-core/src/provider_runtime_arguments.rs",
        required_patterns: &[
            "pub struct DispatchArguments",
            "BTreeMap<String, u64>",
            "runtime dispatch arguments are not canonical",
            "runtime dispatch argument is duplicated",
            "arguments_are_typed_bounded_and_canonical",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "registered-runtime-argument-admission",
        path: "tools/nsdb/src/provider_execution_adapter.rs",
        required_patterns: &[
            "prepare_runtime_arguments: Option<PrepareRuntimeArguments>",
            "type PrepareRuntimeArguments",
            "Option<&yir_core::provider_runtime_ipc::DispatchArguments>",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "metal-bounded-runtime-draw-arguments",
        path: "tools/nsdb/src/provider_execution_metal_draw.rs",
        required_patterns: &[
            "prepare_runtime_arguments",
            "ShaderDrawArguments::from_dispatch",
            "Metal runtime draw dimensions differ from admitted output",
            "render_draw_counts",
            "Metal unbound draw count exceeds admitted vertex/instance budget",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "metal-runtime-draw-admission-regression",
        path: "tools/nsdb/src/provider_execution_metal_draw_tests.rs",
        required_patterns: &[
            "runtime_draw_binding_changes_only_admitted_scalars",
            "invalid_runtime_draw_binding_does_not_mutate_admitted_request",
            "offline_defaults_and_runtime_counts_share_validation",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "shader-dynamic-count-profile-provenance",
        path: "tools/nuisc/src/project/shader_validation_flow_tests.rs",
        required_patterns: &[
            "dynamic_counts_retain_profile_value_provenance",
            "unrelated_profile_operands_and_cycles_do_not_authorize_draw_counts",
            "draw_count_uses_profile",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "shader-registered-draw-validation",
        path: "crates/yir-domain-shader/src/draw_request.rs",
        required_patterns: &[
            "pub struct ShaderDrawDescriptor",
            "pub fn validate_draw_instanced",
            "pub fn record_draw_instanced",
            "describe_shader_node(node, resource)?",
            "prepare_render_pass",
            "empty or overflowing output dimensions",
            "nuis-shader-unbound-draw-v1",
            "pub fn provider_arguments",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "shader-validated-reference-rasterization-boundary",
        path: "crates/yir-domain-shader/src/render_pass.rs",
        required_patterns: &[
            "ValidatedRenderPass",
            "rasterize_reference",
            "Option<GeometryInputs<'a>>",
            "ShaderDrawDescriptor::new",
            "vertex layout size overflows",
            "parse_ball_packet(packet, packet_operation)?",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "shader-borrowed-draw-validation-regression",
        path: "crates/yir-domain-shader/src/draw_request_tests.rs",
        required_patterns: &[
            "descriptor_uses_pass_extent_without_reference_rasterization_or_effects",
            "reference_path_retains_pixels_and_emits_one_event",
            "assert_shared_rejection",
            "binding_validation_borrows_inputs_and_checks_geometry_bounds",
            "empty_and_overflowing_extents_fail_before_any_rasterization",
            "std::ptr::eq",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "runtime-provider-draw-without-cpu-reference-regression",
        path: "crates/yir-runtime-host/src/provider_result_draw_tests.rs",
        required_patterns: &[
            "provider_frame_uses_pass_extent_not_ascii_preview_minimum_and_records_actual_pixels",
            "invalid_request_fails_before_consuming_provider_result_or_emitting_draw",
            "returned_dimension_drift_does_not_stage_completion_or_emit_draw",
            "unbound_draw_keeps_reference_execution_and_does_not_consume_provider_frame",
            "frame[1x1; rgba8_bytes=4]",
            "replay_rejects_changed_runtime_counts_before_consuming_frame",
            "unsupported_pass_projection_rejects_before_consuming_frame",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-shader-vulkan-device-sample-registration",
        path: "tools/nuis/src/artifact_device_sample_shader_vulkan.rs",
        required_patterns: &[
            "DeviceSampleInputRegistration",
            "official.shader.vulkan-copy-u32",
            "official.shader.vulkan-add-u32",
            "official.shader.vulkan-add-pair-u32",
            "official.shader.vulkan-sub-u32",
            "official.shader.vulkan-mul-u32",
            "official.shader.vulkan-xor-u32",
            "official.shader.vulkan-u32-chain",
            "official.shader:provider-sample=vulkan-add-u32",
            "official.shader:provider-sample=vulkan-add-pair-u32",
            "official.shader:provider-sample=vulkan-sub-u32",
            "official.shader:provider-sample=vulkan-mul-u32",
            "official.shader:provider-sample=vulkan-xor-u32",
            "official.shader:provider-sample=vulkan-u32-chain",
            "provider_request_collection_contract=nuis-provider-request-collection-v1",
            "provider_request_count=2",
            "provider_request_1_input_binding_0_source=dependency",
            "provider_request_1_dependency_0_transport_contract=nuis-provider-edge-transport-v1",
            "provider_code_asset_identity_set_count=2",
            "provider_family: \"spirv:vulkan-gpu\"",
            "render_u32_sample_request_evidence",
            "render_u32_prefixed_request_evidence",
            "render_u32_dependency_edge",
            "render_u32_pair_artifact_binding",
            "nuis-provider-input-binding-v2",
            "tensor-row-major",
            "2x2",
            "shader.vulkan.copy-u32.spirv",
            "shader.vulkan.add-u32.spirv",
            "shader.vulkan.add-pair-u32.spirv",
            "shader.vulkan.sub-u32.spirv",
            "shader.vulkan.mul-u32.spirv",
            "shader.vulkan.xor-u32.spirv",
            "code_asset_registration_by_id",
            "provider_kernel_operation={}",
            "provider_code_asset_format=spirv-binary",
            "provider_adapter_binding_provider_family=spirv:vulkan-gpu",
            "select_compiled_code_asset_contribution",
            "render_selected_contribution_set_evidence",
            "validate_provider_request_evidence",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-shader-metal-device-sample-registration",
        path: "tools/nuis/src/artifact_device_sample_shader_metal.rs",
        required_patterns: &[
            "official.shader.metal-copy-u32",
            "official.shader.metal-add-u32",
            "official.shader.metal-add-pair-u32",
            "official.shader.metal-sub-u32",
            "official.shader.metal-mul-u32",
            "official.shader.metal-xor-u32",
            "official.shader.metal-u32-chain",
            "official.shader:provider-sample=metal-copy-u32",
            "official.shader:provider-sample=metal-add-u32",
            "official.shader:provider-sample=metal-add-pair-u32",
            "official.shader:provider-sample=metal-sub-u32",
            "official.shader:provider-sample=metal-mul-u32",
            "official.shader:provider-sample=metal-xor-u32",
            "official.shader:provider-sample=metal-u32-chain",
            "shader.metal.copy-u32.msl",
            "shader.metal.add-u32.msl",
            "shader.metal.add-pair-u32.msl",
            "shader.metal.sub-u32.msl",
            "shader.metal.mul-u32.msl",
            "shader.metal.xor-u32.msl",
            "code_asset_registration_by_id",
            "provider_kernel_operation={}",
            "render_u32_sample_request_evidence",
            "render_u32_prefixed_request_evidence",
            "render_u32_dependency_edge",
            "render_u32_pair_artifact_binding",
            "nuis-provider-input-binding-v2",
            "tensor-row-major",
            "2x2",
            "msl2.4",
            "provider_adapter_binding_provider_family=metal:apple-silicon-gpu",
            "select_compiled_code_asset_contribution",
            "render_selected_contribution_set_evidence",
            "nuis-module-lowering-plan",
            "provider_request_collection_contract",
            "provider_request_1_input_binding_0_source=dependency",
            "glm:provider-edge:shader.metal.chain.add-u32:output.values->shader.metal.chain.xor-u32:input.values",
            "provider_code_asset_identity_set_count=2",
            "validate_provider_request_evidence",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-shader-metal-fan-out-device-sample-registration",
        path: "tools/nuis/src/artifact_device_sample_shader_metal_fan_out.rs",
        required_patterns: &[
            "official.shader.metal-add-xor-pair-u32",
            "official.shader:provider-sample=metal-add-xor-pair-u32",
            "shader.metal.add-xor-pair-u32.msl",
            "add-xor-pair-u32",
            "render_u32_output_evidence",
            "provider_output_binding_count=2",
            "provider_output_comparison_collection_count=2",
            "output.xor",
            "0x73bb5b39fe3ab738",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-shader-vulkan-reduced-fan-out-graph-registration",
        path: "tools/nuis/src/artifact_device_sample_shader_vulkan_fan_out.rs",
        required_patterns: &[
            "official.shader.vulkan-reduced-output-fan-out-u32",
            "official.shader:provider-sample=vulkan-reduced-output-fan-out-u32",
            "shader.vulkan.add-xor-pair-reduced-u32.spirv",
            "shader.vulkan.copy-u32.spirv",
            "shader.vulkan.xor-u32.spirv",
            "render_reduced_graph_consumer",
            "render_u32_dependency_binding",
            "render_u32_dependency_edge",
            "REDUCED_GRAPH_SUM_TRANSPORT_TOKEN",
            "REDUCED_GRAPH_XOR_TRANSPORT_TOKEN",
            "provider_request_count=3",
            "provider_request_1_input_binding_0_shape=2x2",
            "provider_request_1_dependency_0_producer_output_buffer=output.values",
            "provider_request_2_input_binding_0_shape=2x1",
            "provider_request_2_input_binding_0_byte_length=8",
            "provider_request_2_kernel_dispatch=2x1x1",
            "provider_request_2_dependency_0_producer_output_buffer=output.xor",
            "provider-clock:request-2:dispatch-ready",
            "provider_code_asset_identity_set_count=3",
            "0xa8c7f832281a39c5",
            "resolve_reduced_graph_code_asset_evidence",
            "render_selected_contribution_set_evidence",
            "validate_provider_request_evidence",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-shader-vulkan-cuda-fan-out-graph-registration",
        path: "tools/nuis/src/artifact_device_sample_shader_vulkan_cuda_fan_out.rs",
        required_patterns: &[
            "official.shader.vulkan-cuda-reduced-output-fan-out-u32",
            "kernel.cuda.copy-u32.ptx",
            "nuis_kernel_copy_u32",
            "provider_request_count=3",
            "cuda:nvidia-gpu",
            "spirv:vulkan-gpu",
            "render_u32_prefixed_request_evidence_with_scalars",
            "render_u32_dependency_binding",
            "render_u32_dependency_edge",
            "SUM_TRANSPORT_TOKEN",
            "XOR_TRANSPORT_TOKEN",
            "provider_code_asset_identity_set_count=3",
            "select_compiled_code_asset_contribution",
            "render_selected_contribution_set_evidence",
            "validate_provider_request_evidence",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-u32-request-typed-edge-rendering",
        path: "tools/nuis/src/artifact_device_sample_shader_common.rs",
        required_patterns: &[
            "element_count: usize",
            "args.element_count",
            "render_u32_dependency_binding",
            "producer_request_index: usize",
            "consumer_request_index: usize",
            "provider-clock:request-{producer_request_index}:completed",
            "provider-clock:request-{consumer_request_index}:dispatch-ready",
            "input_binding_contract=nuis-provider-input-binding-v2",
            "input_binding_0_layout={layout}",
            "input_binding_0_shape={shape}",
            "input_binding_0_row_stride_bytes={row_stride_bytes}",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-device-sample-canonical-provider-family",
        path: "tools/nuis/src/artifact_device_sample_registration.rs",
        required_patterns: &[
            "provider_family",
            "registered_provider_family",
            "provider_sample_registration_id",
            "metadata_selector",
            "selected_registration",
            "evidence_matches_registration",
            "nuis.pixelmagic.gray8-filter",
            "official.shader.metal-copy-u32",
            "official.shader.metal-add-u32",
            "official.shader.metal-add-pair-u32",
            "artifact_device_sample_shader_metal_fan_out::registration",
            "official.shader.metal-sub-u32",
            "official.shader.metal-mul-u32",
            "official.shader.metal-xor-u32",
            "official.shader.metal-u32-chain",
            "official.shader.vulkan-add-u32",
            "official.shader.vulkan-add-pair-u32",
            "official.shader.vulkan-sub-u32",
            "official.shader.vulkan-mul-u32",
            "official.shader.vulkan-xor-u32",
            "official.shader.vulkan-u32-chain",
            "artifact_device_sample_shader_vulkan_fan_out::reduced_graph_registration",
            "artifact_device_sample_shader_vulkan_cuda_fan_out::registration",
            "provider_sample_registration_package=official.shader",
            "vulkan",
            "discrete-or-integrated-gpu",
            "spirv:vulkan-gpu",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-code-asset-selection-set-single-base-case",
        path: "tools/nsdb/src/provider_code_asset_selection_payload.rs",
        required_patterns: &[
            "SINGLE_CONTRACT | SET_CONTRACT",
            "single_item_selection_set_round_trips_as_base_case",
            "compiled_code_asset_selection_count",
            "nuis-provider-code-asset-contribution-selection-set-v1",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-shader-vulkan-provider-demo",
        path: "examples/projects/domains/shader_vulkan_provider_demo/nuis.toml",
        required_patterns: &[
            "shader_vulkan_provider_demo",
            "cpu=cpu.x86_64.sysv64",
            "shader=shader.vulkan.spv1_6",
            "nuis-self-contained-image",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-shader-vulkan-add-provider-demo",
        path: "examples/projects/domains/shader_vulkan_add_provider_demo/nuis.toml",
        required_patterns: &[
            "shader_vulkan_add_provider_demo",
            "official.shader:provider-sample=vulkan-add-u32",
            "shader=shader.vulkan.spv1_6",
            "nuis-self-contained-image",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-shader-vulkan-sub-provider-demo",
        path: "examples/projects/domains/shader_vulkan_sub_provider_demo/nuis.toml",
        required_patterns: &[
            "shader_vulkan_sub_provider_demo",
            "official.shader:provider-sample=vulkan-sub-u32",
            "shader=shader.vulkan.spv1_6",
            "nuis-self-contained-image",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-shader-vulkan-add-pair-provider-demo",
        path: "examples/projects/domains/shader_vulkan_add_pair_provider_demo/nuis.toml",
        required_patterns: &[
            "shader_vulkan_add_pair_provider_demo",
            "official.shader:provider-sample=vulkan-add-pair-u32",
            "shader=shader.vulkan.spv1_6",
            "nuis-self-contained-image",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-shader-vulkan-mul-provider-demo",
        path: "examples/projects/domains/shader_vulkan_mul_provider_demo/nuis.toml",
        required_patterns: &[
            "shader_vulkan_mul_provider_demo",
            "official.shader:provider-sample=vulkan-mul-u32",
            "shader=shader.vulkan.spv1_6",
            "nuis-self-contained-image",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-shader-vulkan-xor-provider-demo",
        path: "examples/projects/domains/shader_vulkan_xor_provider_demo/nuis.toml",
        required_patterns: &[
            "shader_vulkan_xor_provider_demo",
            "official.shader:provider-sample=vulkan-xor-u32",
            "shader=shader.vulkan.spv1_6",
            "nuis-self-contained-image",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-shader-vulkan-chain-provider-demo",
        path: "examples/projects/domains/shader_vulkan_chain_provider_demo/nuis.toml",
        required_patterns: &[
            "shader_vulkan_chain_provider_demo",
            "official.shader:provider-sample=vulkan-u32-chain",
            "shader=shader.vulkan.spv1_6",
            "nuis-self-contained-image",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-shader-vulkan-reduced-output-fan-out-provider-demo",
        path: "examples/projects/domains/shader_vulkan_reduced_output_fan_out_provider_demo/nuis.toml",
        required_patterns: &[
            "shader_vulkan_reduced_output_fan_out_provider_demo",
            "official.shader:provider-sample=vulkan-reduced-output-fan-out-u32",
            "shader=shader.vulkan.spv1_6",
            "nuis-self-contained-image",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-shader-vulkan-cuda-fan-out-provider-demo",
        path: "examples/projects/domains/shader_vulkan_cuda_fan_out_provider_demo/nuis.toml",
        required_patterns: &[
            "shader_vulkan_cuda_fan_out_provider_demo",
            "official.shader:provider-sample=vulkan-cuda-reduced-output-fan-out-u32",
            "code_assets = [\"kernel.cuda.copy-u32.ptx\"]",
            "shader=shader.vulkan.spv1_6",
            "nuis-self-contained-image",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "official-shader-metal-provider-demo",
        path: "examples/projects/domains/shader_metal_provider_demo/nuis.toml",
        required_patterns: &[
            "shader_metal_provider_demo",
            "official.shader:provider-sample=metal-copy-u32",
            "shader=shader.metal.msl2_4",
            "nuis-self-contained-image",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "official-shader-metal-add-provider-demo",
        path: "examples/projects/domains/shader_metal_add_provider_demo/nuis.toml",
        required_patterns: &[
            "shader_metal_add_provider_demo",
            "official.shader:provider-sample=metal-add-u32",
            "shader=shader.metal.msl2_4",
            "nuis-self-contained-image",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "official-shader-metal-add-pair-provider-demo",
        path: "examples/projects/domains/shader_metal_add_pair_provider_demo/nuis.toml",
        required_patterns: &[
            "shader_metal_add_pair_provider_demo",
            "official.shader:provider-sample=metal-add-pair-u32",
            "shader=shader.metal.msl2_4",
            "nuis-self-contained-image",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "official-shader-metal-fan-out-provider-demo",
        path: "examples/projects/domains/shader_metal_fan_out_provider_demo/nuis.toml",
        required_patterns: &[
            "shader_metal_fan_out_provider_demo",
            "official.shader:provider-sample=metal-add-xor-pair-u32",
            "shader=shader.metal.msl2_4",
            "nuis-self-contained-image",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "official-shader-metal-sub-provider-demo",
        path: "examples/projects/domains/shader_metal_sub_provider_demo/nuis.toml",
        required_patterns: &[
            "shader_metal_sub_provider_demo",
            "official.shader:provider-sample=metal-sub-u32",
            "shader=shader.metal.msl2_4",
            "nuis-self-contained-image",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "official-shader-metal-mul-provider-demo",
        path: "examples/projects/domains/shader_metal_mul_provider_demo/nuis.toml",
        required_patterns: &[
            "shader_metal_mul_provider_demo",
            "official.shader:provider-sample=metal-mul-u32",
            "shader=shader.metal.msl2_4",
            "nuis-self-contained-image",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "official-shader-metal-xor-provider-demo",
        path: "examples/projects/domains/shader_metal_xor_provider_demo/nuis.toml",
        required_patterns: &[
            "shader_metal_xor_provider_demo",
            "official.shader:provider-sample=metal-xor-u32",
            "shader=shader.metal.msl2_4",
            "nuis-self-contained-image",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "official-shader-metal-chain-provider-demo",
        path: "examples/projects/domains/shader_metal_chain_provider_demo/nuis.toml",
        required_patterns: &[
            "shader_metal_chain_provider_demo",
            "official.shader:provider-sample=metal-u32-chain",
            "shader=shader.metal.msl2_4",
            "nuis-self-contained-image",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "official-shader-metal-provider-smoke",
        path: "tools/nuis/tests/official_galaxy_hetero_smoke/shader_metal.rs",
        required_patterns: &[
            "shader_metal_generated_msl_sample_executes_provider_output",
            "shader_metal_generated_add_msl_sample_executes_provider_output",
            "shader_metal_generated_add_pair_msl_sample_executes_provider_output",
            "shader_metal_generated_fan_out_msl_writes_two_provider_outputs",
            "shader_metal_generated_sub_msl_sample_executes_provider_output",
            "shader_metal_generated_mul_msl_sample_executes_provider_output",
            "shader_metal_generated_xor_msl_sample_executes_provider_output",
            "shader_metal_generated_chain_msl_sample_executes_provider_graph",
            "shader_metal_provider_demo",
            "shader_metal_add_provider_demo",
            "shader_metal_add_pair_provider_demo",
            "shader_metal_fan_out_provider_demo",
            "shader_metal_sub_provider_demo",
            "shader_metal_mul_provider_demo",
            "shader_metal_xor_provider_demo",
            "shader_metal_chain_provider_demo",
            "official.shader.metal-copy-u32",
            "provider_sample_registration_id={}",
            "official.shader.metal-add-u32",
            "official.shader.metal-add-pair-u32",
            "official.shader.metal-add-xor-pair-u32",
            "official.shader.metal-sub-u32",
            "official.shader.metal-mul-u32",
            "official.shader.metal-xor-u32",
            "official.shader.metal-u32-chain",
            "code_asset_target=msl2.4",
            "nuis-metal-u32-copy-provider-runner-v1",
            "nuis-metal-u32-canonical-provider-runner-v1",
            "0x88201fb960ff6465",
            "0x02f6f7f591bff68f",
            "0xbada6f73928b9f42",
            "0x73bb5b39fe3ab738",
            "native_output_0_output_binding_count = \\\"2\\\"",
            "native_output_0_comparison_collection_statuses = \\\"comparison-passed,comparison-passed\\\"",
            "input_binding_contract=nuis-provider-input-binding-v2",
            "input_binding_1_row_stride_bytes=8",
            "0x88201fb960ff6465",
            "provider-tensor-u32",
            "native_output_count = \\\"2\\\"",
            "provider_edge_transport_receipt_count = \\\"1\\\"",
            "compiled_code_asset_selection_count = \\\"2\\\"",
            "compiled_code_asset_selection_status",
            "assemble_provider_complete_final_image",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "linux-vulkan-provider-sample-smoke",
        path: "tools/nuis/tests/official_galaxy_hetero_smoke/linux_vulkan.rs",
        required_patterns: &[
            "linux_vulkan_shader_sample_executes_provider_output",
            "linux_vulkan_add_shader_sample_executes_provider_output",
            "linux_vulkan_add_pair_shader_sample_executes_provider_output",
            "linux_vulkan_sub_shader_sample_executes_provider_output",
            "linux_vulkan_mul_shader_sample_executes_provider_output",
            "linux_vulkan_xor_shader_sample_executes_provider_output",
            "linux_vulkan_chain_shader_sample_executes_provider_graph",
            "linux_vulkan_reduced_fan_out_shader_feeds_independent_typed_downstream_inputs",
            "shader_vulkan_add_provider_demo",
            "shader_vulkan_add_pair_provider_demo",
            "shader_vulkan_sub_provider_demo",
            "shader_vulkan_mul_provider_demo",
            "shader_vulkan_xor_provider_demo",
            "shader_vulkan_chain_provider_demo",
            "shader_vulkan_reduced_output_fan_out_provider_demo",
            "execute-provider-samples",
            "materialize-provider-samples",
            "native_output_count: 3",
            "compiled_selection_count: 3",
            "graph.edges.len()",
            "provider_edge_transport_receipt_{receipt_index}_byte_length",
            "assemble_provider_complete_final_image",
            "nsld_final_executable_output_object_package_provider_dispatch_identity_status",
            "nsld_final_executable_output_debugger_api_provider_dispatch_identity_status",
            "spirv.vulkan-gpu.bundle.v1",
            "nuis-vulkan-spirv-provider-execution-v1",
            "0x6ebcdd244b594ee4",
            "0xdce2c1aca0f32707",
            "0xbada6f73928b9f42",
            "0x279d73758e81abdd",
            "0xa8c7f832281a39c5",
            "input_binding_contract=nuis-provider-input-binding-v2",
            "input_binding_1_row_stride_bytes=8",
            "0x88201fb960ff6465",
            "0x02f6f7f591bff68f",
            "0x88201fb960ff6465",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-provider-input-binding-v2",
        path: "tools/nsdb/src/provider_input_binding.rs",
        required_patterns: &[
            "nuis-provider-input-binding-v1",
            "nuis-provider-input-binding-v2",
            "layout",
            "row_stride_bytes",
            "tensor-row-major",
            "input_binding_matches_buffer",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-shader-typed-output-binding-evidence",
        path: "tools/nuis/src/artifact_device_sample_shader_common.rs",
        required_patterns: &[
            "nuis-provider-output-binding-v2",
            "render_u32_output_evidence",
            "output_binding_{index}_layout",
            "output_binding_{index}_row_stride_bytes",
            "output_comparison_collection_contract",
            "output_comparison_collection_count",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-provider-input-binding-v2-payload",
        path: "tools/nsdb/src/provider_request_payload.rs",
        required_patterns: &[
            "PROVIDER_INPUT_BINDING_CONTRACT",
            "binding.layout",
            "row_stride_bytes",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-provider-output-binding-v2",
        path: "tools/nsdb/src/provider_output_binding.rs",
        required_patterns: &[
            "nuis-provider-output-binding-v1",
            "nuis-provider-output-binding-v2",
            "layout",
            "row_stride_bytes",
            "tensor-row-major",
            "output_binding_matches_buffer",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-provider-output-binding-v2-payload",
        path: "tools/nsdb/src/provider_request_payload.rs",
        required_patterns: &[
            "PROVIDER_OUTPUT_BINDING_CONTRACT",
            "binding.layout",
            "binding.row_stride_bytes",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-vulkan-final-image-dispatch-smoke",
        path: "tools/nsld/src/main_container_metadata_binding_tests.rs",
        required_patterns: &[
            "final_image_loader_verifies_vulkan_provider_dispatch_without_backend_branch",
            "spirv:vulkan-gpu",
            "spirv.vulkan-gpu.bundle.v1",
            "spirv.vulkan.real-device",
            "spirv.vulkan.fake-device",
            "fnv1a64:f8efa211643f7bcd",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-vulkan-completion-dispatch-authority",
        path: "tools/nsdb/src/provider_completion_dispatch.rs",
        required_patterns: &[
            "vulkan_completion_authority_is_bound_from_open_final_image_dispatch",
            "vulkan_completion_authority_rejects_runner_identity_drift",
            "spirv:vulkan-gpu",
            "spirv.vulkan-gpu.bundle.v1",
            "provider-completion-dispatch:runner-drift",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-code-asset-selection-set-base-case",
        path: "tools/nsld/src/final_executable_output_code_asset.rs",
        required_patterns: &[
            "nuis-provider-code-asset-contribution-selection-set-v1",
            "selected_count == 1",
            "validates_verified_or_not_applicable_selection",
        ],
    },
];
