use crate::dev_tensor_drift::DevTensorDriftCheckSpec;

pub(super) const CHECKS: &[DevTensorDriftCheckSpec] = &[
    DevTensorDriftCheckSpec {
        id: "native-literal-print-policy-flat-registration",
        path: "tools/nuis/src/dev_tensor_drift_data_native_iteration_calls.rs",
        required_patterns: &[
            "mod literal_print_policy;",
            "literal_print_policy::CHECKS,",
            ".flatten()",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-literal-print-policy-explicit-bounded-operand-authority",
        path: "crates/yir-lower-llvm/src/native_session/literal_prints.rs",
        required_patterns: &[
            "MAX_LITERAL_PRINT_SITES: usize = 64",
            "empty or duplicate grant",
            "static site bound",
            "if !self.sites.contains(&node.name)",
            "direct i64 constant",
            "value.op.args[0].parse::<i64>().is_ok()",
            "unselected grant",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-literal-print-policy-transitive-order-without-global-grants",
        path: "crates/yir-lower-llvm/src/native_session/literal_prints.rs",
        required_patterns: &[
            "pub(super) fn validate_closure",
            "effectful.insert(caller.clone())",
            "super::calls::target",
            "semantics.has_effect",
            "\"guard_return\" | \"div\" | \"rem\"",
            "Two bounded traversals",
            "let before = reachable(site, &dependencies)",
            "let after = reachable(site, &dependents)",
            "lacks dependency order",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-literal-print-policy-separate-emission-and-conservative-bound",
        path: "crates/yir-lower-llvm/src/native_session/mod.rs",
        required_patterns: &[
            "pub fn emit_registered_with_literal_prints",
            "emit_with_policy(module, id, loop_work_limit, helper_entry_limit, None)",
            "Some(policy)",
            "pub literal_print_sites: Vec<String>",
            "self.literal_print_sites.len() as u128 * u128::from(self.helper_entry_limit)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-literal-print-policy-default-function-veto-preserved",
        path: "crates/yir-lower-llvm/src/native_session/function.rs",
        required_patterns: &[
            "pub literal_prints: Option<&'a LiteralPrintPolicy>",
            "!admitted(&node.op.instruction)",
            "policy.permit(node, &self.nodes)",
            "native scalar bridge does not admit",
            "requires external initialization",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-literal-print-policy-closure-validation-before-emission",
        path: "crates/yir-lower-llvm/src/native_session/admission.rs",
        required_patterns: &[
            "policy: Option<&LiteralPrintPolicy>",
            "literal_prints: policy",
            "calls::validate_graph(&graph)?",
            "policy.validate_closure(&selected_functions, &graph, &admission)?",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-literal-print-policy-exact-i64-and-bool-lowering",
        path: "crates/yir-lower-llvm/src/function_lowering/strict_scalar.rs",
        required_patterns: &[
            "\"print\" | \"guard_print\"",
            "require_value(node, value, CpuCallScalarKind::I64, registers)?",
            "require_value(node, &node.op.args[0], CpuCallScalarKind::Bool, registers)?",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-literal-print-policy-admission-and-transitive-veto-tests",
        path: "tools/nuisc/tests/native_application_bridge/literal_print_policy.rs",
        required_patterns: &[
            "native_literal_print_policy_is_explicit_bounded_and_not_a_pure_bridge_widening",
            "native_literal_print_policy_rechecks_values_guards_order_and_helper_grants",
            "MAX_LITERAL_PRINT_SITES",
            "u64::MAX",
            "independent_effect_call",
            "does not admit cpu.print",
            "i64::MIN.to_string()",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-literal-print-policy-real-returned-state-and-independent-oracles",
        path: "tools/nuisc/tests/native_application_bridge/literal_print_execution.rs",
        required_patterns: &[
            "ApplicationSession::open_registered",
            "reference.event(vec![])",
            "reference.close(vec![])",
            "native.valid(&bridge, input, &state, &prints, calls)",
            "native.invalid(&bridge, ty)",
            "864",
            "1512",
            "write_and_link_with_source",
            "native_literal_print_policy_traps_keep_prior_effects_and_never_publish_output",
            "Some(4 | 5)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-literal-print-policy-canonical-preflight-overlap-and-no-publication",
        path: "tools/nuisc/tests/native_application_bridge/literal_print_driver.rs",
        required_patterns: &[
            "Observe admitted source entries",
            "Actual prior returned state is the next input",
            "self.store(\"%storage\", 10",
            "self.empty_probes()",
            "Observe output before the original fatal trap",
            "@effect_trap_probe",
            "self.read(\"@effect_out\", slot, CANARY)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-literal-print-policy-scoped-receipt-and-next-artifact-boundary",
        path: "docs/reference/nuis-native-literal-print-policy-v1.md",
        required_patterns: &[
            "Literal-print policy acceptance:",
            "1296",
            "3888",
            "1010",
            "Twenty-four",
            "not automatic application",
            "`active/99`",
            "No",
            "fresh Linux/GPU/Windows",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-literal-print-policy-complete-six-field-history",
        path: "tools/nuis/src/dev_tensor_data.rs",
        required_patterns: &[
            "Literal-print policy follow-up:",
            "Previous typed-return checkpoint:",
            "Previous typed-return task checkpoint:",
            "Previous typed-return blocker checkpoint:",
            "Previous typed-return action checkpoint:",
            "Previous typed-return artifact checkpoint:",
            "Carry checked literal-print policy through build/cache/launch identity",
            "native_literal_print_policy",
        ],
    },
];
