use crate::dev_tensor_drift::DevTensorDriftCheckSpec;

pub(super) const CHECKS: &[DevTensorDriftCheckSpec] = &[
    DevTensorDriftCheckSpec {
        id: "native-caller-spills-bounded-owned-input-preflight",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_caller_spills.rs",
        required_patterns: &[
            "prepare_with_budget(caller, name, plan, layouts, catalog, controls, 65_536)",
            "scalar_aliases::validate_expansion(&caller.body, &mut remaining)?",
            "if depth >= 64",
            "!plan.word_inputs.is_empty()",
            "!written.contains(param.name.as_str())",
            "!controls.contains(&param.name)",
            "control_values::supported_type(&param.ty, layouts)",
            "Some(ty)",
            "scalar_aliases::validate_expansion(&prepared.body, &mut context.remaining)?",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-caller-spills-binding-roots-complete-ordered-operands",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_caller_spills.rs",
        required_patterns: &[
            "NirStmt::Let { value, .. } | NirStmt::Const { value, .. } if !in_loop",
            "NirStmt::While { body, .. } => self.block(body, true)?",
            "self.block(then_body, in_loop)?",
            "self.block(else_body, in_loop)?",
            "record_views::materialized_operand_type(",
            "args.iter_mut().zip(&self.plan.original_types)",
            "self.names.len() + 1",
            "__nuis_caller_operand",
            "std::mem::replace(arg, NirExpr::Var(name.clone()))",
            "ty: Some(ty.clone())",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-caller-spills-shared-kind-proof-not-inline-authority",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_record_views.rs",
        required_patterns: &[
            "pub(super) fn materialized_operand_type(",
            "preserves the complete RHS",
            "This grants no inline readiness or erasure authority",
            "evaluated_scalar_type(value, ready, catalog, layouts, remaining, 0)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-caller-spills-every-caller-atomic-installation",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_projection.rs",
        required_patterns: &[
            "mod caller_spills;",
            "let mut prepared_callers = BTreeMap::new()",
            "if !callers.iter().all(|i|",
            "if scoped.contains(&name)",
            "caller_spills::prepare(",
            "&result_catalog",
            "prepared_callers.insert(*i, caller)",
            "for (index, caller) in prepared_callers",
            "module.functions[index] = caller",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-caller-spills-unit-negatives-and-independent-oracle",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_caller_spills_tests.rs",
        required_patterns: &[
            "caller_spills_preserve_complete_operands_in_exact_source_order_and_independent_bindings",
            "caller_spills_retain_unused_checked_arguments_and_exact_subrecord_kinds",
            "caller_spills_roll_back_every_caller_if_any_site_or_catalog_is_unproven",
            "caller_spills_keep_mixed_kinds_branch_locality_and_exact_constructor_fields",
            "caller_spills_keep_nested_expressions_conditions_and_loop_returns_conservative",
            "caller_spills_bound_work_depth_names_and_registered_controls_before_installation",
            "caller_spills_preserve_guarded_unused_checks_with_an_independent_oracle",
            "for budget in 1..2048",
            "yir.nodes.reverse()",
            "assert_eq!(module, before)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-caller-spills-explicit-ir-full-producer-and-native-trap",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_caller_spills_native_tests.rs",
        required_patterns: &[
            "caller_spills_execute_projected_ir_with_full_results_and_guarded_native_failures",
            "Explicit private-capture registration, not source-name eligibility",
            "function(&compiled.nir, \"produce\")",
            "assert_eq!(producer_calls.len(), 1",
            "before < produced && produced < after && after < invoked",
            "Some(\"26\")",
            "Some(\"0\")",
            "Duration::from_secs(10)",
            "child.kill()",
            "child.wait()",
            "Some(4 | 5)",
            ".current_dir(&scratch.0)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-caller-spills-drift-registration",
        path: "tools/nuis/src/dev_tensor_drift_data_native_iteration_calls.rs",
        required_patterns: &["mod caller_spills;", ".chain(caller_spills::CHECKS.iter())"],
    },
    DevTensorDriftCheckSpec {
        id: "native-caller-spills-tensor-scope",
        path: "tools/nuis/src/dev_tensor_data.rs",
        required_patterns: &[
            "Binding-root caller operand materialization follow-up:",
            "complete operands remain evaluated once in source order",
            "not general expression spilling or return/loop authority",
            "caller_spills",
            "active/86 is unchanged",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-caller-spills-return-root-bounded-statement-window",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_caller_spills.rs",
        required_patterns: &[
            "NirStmt::Return(Some(NirExpr::Call { callee, args }))",
            "if !in_loop && callee == self.name",
            "result.extend(self.operands(args)?)",
            "NirStmt::While { body, .. } => self.block(body, true)?",
            "scalar_aliases::validate_expansion(&prepared.body, &mut context.remaining)?",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-caller-spills-return-root-atomic-and-exit-oracle",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_caller_spills_return_tests.rs",
        required_patterns: &[
            "caller_spills_return_roots_preserve_exact_operands_branch_exit_and_mixed_callers",
            "caller_spills_return_roots_keep_atomic_vetoes_and_unproven_versions_unchanged",
            "caller_spills_return_roots_preserve_guarded_unused_checks_with_an_independent_oracle",
            "assert_return(after, value)",
            "names(then_body).is_disjoint(&names(else_body))",
            "for first in 0..4",
            "for unused in 0..4",
            "for guard in 0..3",
            "yir.nodes.reverse()",
            "assert_eq!(module, before)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-caller-spills-return-root-native-harness",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_caller_spills_native_tests.rs",
        required_patterns: &[
            "caller_spills_return_roots_execute_full_operands_and_preserve_early_exit_traps",
            "run_probes(true)",
            "format!(\"return {call};\")",
            "before < produced && produced < after && after < invoked",
            "Some(4 | 5)",
            "Duration::from_secs(10)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-caller-spills-return-root-documentation-boundary",
        path: "docs/reference/nuis-native-scalar-loop-snapshots-v1.md",
        required_patterns: &[
            "## Return Root Caller Materialization",
            "All original operands receive typed, complete bindings",
            "Root\nreturns inside loops",
            "earlier exit",
            "not automatic\nsource-function eligibility",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-caller-spills-return-root-tensor-scope",
        path: "tools/nuis/src/dev_tensor_data.rs",
        required_patterns: &[
            "Return-root caller operand materialization follow-up:",
            "root returns outside loops",
            "All original operands remain complete and evaluated once in source order",
            "not condition/nested-expression/loop or scoped/word authority",
            "active/86 remains unchanged",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-caller-spills-if-root-exact-owned-predicate-plan",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_projection.rs",
        required_patterns: &[
            "predicate_result: bool",
            "predicate_result: function.return_type.as_ref() == Some(&scalar_type(\"bool\"))",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-caller-spills-if-root-bounded-statement-window",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_caller_spills.rs",
        required_patterns: &[
            "if !in_loop",
            "if let NirExpr::Call { callee, args } = condition",
            "if !self.plan.predicate_result",
            "result.extend(self.operands(args)?)",
            "self.block(then_body, in_loop)?",
            "self.block(else_body, in_loop)?",
            "NirStmt::While { body, .. } => self.block(body, true)?",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-caller-spills-if-root-oracle-and-vetoes",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_caller_spills_condition_tests.rs",
        required_patterns: &[
            "caller_spills_condition_roots_preserve_full_order_branches_and_mixed_callers",
            "caller_spills_condition_roots_keep_nested_loop_kind_and_atomic_veto_boundaries",
            "caller_spills_condition_roots_preserve_early_exit_and_selected_checks_with_an_independent_oracle",
            "for branches in 0..4",
            "yir.nodes.reverse()",
            "assert_eq!(then_body, old_then)",
            "assert_eq!(else_body, old_else)",
            "assert_eq!(module, before)",
            "assert!(plan.predicate_result)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-caller-spills-if-root-native-predicate-and-selected-traps",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_caller_spills_native_tests.rs",
        required_patterns: &[
            "caller_spills_condition_roots_execute_selected_branches_and_retain_native_traps",
            "run_source_probe(&source, true, expected)",
            "let result_kind = if predicate { \"i1\" } else { \"i64\" }",
            "Some(\"11\")",
            "Some(\"19\")",
            "before < produced && produced < after && after < invoked",
            "Some(4 | 5)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-caller-spills-if-root-parser-delimiter-restoration",
        path: "tools/nuisc/src/frontend/parser_exprs.rs",
        required_patterns: &[
            "let old = self.allow_struct_literals",
            "self.allow_struct_literals = true",
            "let parsed = self.parse_argument_list_contents(terminator)",
            "self.allow_struct_literals = old",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-caller-spills-if-root-parser-arguments-and-limits",
        path: "tools/nuisc/src/frontend/parser_condition_arguments_tests.rs",
        required_patterns: &[
            "condition_call_arguments_admit_nested_literals_without_consuming_outer_blocks",
            "condition_call_arguments_restore_literal_mode_on_success_errors_and_nested_conditions",
            "condition_call_arguments_retain_expression_depth_limits_and_error_restoration",
            "assert_eq!(parser.allow_struct_literals, mode",
            "assert_eq!(parser.expression_depth, 0)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-caller-spills-if-root-parser-test-registration",
        path: "tools/nuisc/src/frontend/parser.rs",
        required_patterns: &["mod parser_condition_arguments_tests;"],
    },
    DevTensorDriftCheckSpec {
        id: "native-caller-spills-if-root-documentation-scope",
        path: "docs/reference/nuis-native-scalar-loop-snapshots-v1.md",
        required_patterns: &[
            "## If Condition Root Caller Materialization",
            "private proof fact, not a new serialized ABI",
            "independent 192-case before/after oracle",
            "not relaxed speculation",
            "restores the outer literal mode on success and error",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-caller-spills-if-root-tensor-scope",
        path: "tools/nuis/src/dev_tensor_data.rs",
        required_patterns: &[
            "If-condition-root caller operand materialization follow-up:",
            "exact owned non-optional non-generic bool result",
            "not nested/short-circuit condition, loop or scoped/word authority",
            "192 independent before/after oracle cases",
            "active/86 remains unchanged",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-caller-spills-documentation-boundary",
        path: "docs/reference/nuis-native-scalar-loop-snapshots-v1.md",
        required_patterns: &[
            "## Binding Root Caller Materialization",
            "all original operands",
            "No materialization is lifted from a condition",
            "producer's NIR definition is unchanged",
            "not automatic source-function eligibility",
            "ten-second native deadline",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-caller-spills-gated-owned-single-edge-preflight",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_caller_spills.rs",
        required_patterns: &[
            "result.extend(self.gated_predicate(condition)?)",
            "op: op @ (NirBinaryOp::And | NirBinaryOp::Or)",
            "self.ready.get(name.as_str()).copied() == Some(&scalar_type(\"bool\"))",
            "!self.plan.predicate_result || !gate_ready",
            "conditional_values::prefix::bounded(&body)",
            "The complete RHS stays in its selected arm",
            "NirExpr::Bool(disjunction)",
            "__nuis_caller_predicate",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-caller-spills-gated-prefix-fresh-owned-selection",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_values.rs",
        required_patterns: &[
            "mod prefix_tests;",
            "prefix::bounded(body)",
            "if inner.contains_key(name)",
            "!local_names.contains(name)",
            "inputs.retain(|name| !local_names.contains(name))",
            "let mut preserved = locals.to_vec()",
            "preserved.extend(selected.body)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-caller-spills-gated-shared-prefix-bounds",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_values_prefix.rs",
        required_patterns: &[
            "if body.len() > 32",
            "let mut work = 4096usize",
            "if depth >= 64 || work == 0",
            "pending.len() + args.len() > work",
            "pending.len() + fields.len() > work",
            "NirBinaryOp::And | NirBinaryOp::Or",
            "_ => return false",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-caller-spills-gated-source-laziness-across-control-routes",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_values.rs",
        required_patterns: &[
            "condition laziness must not depend on which route owns the function",
            "extract_selections: !control_roots.contains(&function.name)",
            "self.gated_condition(condition, scope)",
            "mod logical;",
            "let mut args = vec![condition]",
            "Branch calls, projections and arithmetic stay inside the helper",
            "params[1..]",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-caller-spills-gated-unit-atomic-and-exit-oracle",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_caller_spills_gated_tests.rs",
        required_patterns: &[
            "caller_spills_gated_predicates_keep_complete_rhs_in_one_selected_arm",
            "caller_spills_gated_predicates_retain_kind_gate_loop_budget_and_atomic_vetoes",
            "caller_spills_gated_predicates_preserve_skipped_checks_and_selected_results_with_an_oracle",
            "assert!(skipped.is_empty())",
            "assert_eq!(then_body, old_then)",
            "assert_eq!(else_body, old_else)",
            "assert_eq!(module, before)",
            "super::conditions::execute(&before_module)",
            "super::conditions::execute(&module)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-caller-spills-gated-source-prefix-runtime-and-vetoes",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_values_prefix_tests.rs",
        required_patterns: &[
            "conditional_prefix_values_keep_fresh_ordered_locals_inside_guarded_selections",
            "conditional_prefix_values_keep_rebindings_effects_kinds_and_limits_conservative",
            "conditional_prefix_values_gate_pure_call_conditions_without_eager_rhs_checks",
            "assert_eq!(&then_body[..2], &original_body[..2])",
            "assert_eq!(module, before",
            "for _ in 0..70",
            "for _ in 0..13",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-caller-spills-gated-native-lazy-rhs-and-source-order",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_caller_spills_native_tests.rs",
        required_patterns: &[
            "caller_spills_gated_predicates_execute_lazy_rhs_and_keep_native_traps",
            "run_projected_probe(&source, true, true, expected)",
            "= add i64 0, 20",
            "sdiv i64 {numerator},",
            "ordered operand producer must belong to one guarded body",
            "before < produced && produced < after && after < invoked",
            "Some(4 | 5)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-caller-spills-gated-test-registration",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_caller_spills_tests.rs",
        required_patterns: &["mod gated;"],
    },
    DevTensorDriftCheckSpec {
        id: "native-caller-spills-gated-documentation-boundary",
        path: "docs/reference/nuis-native-scalar-loop-snapshots-v1.md",
        required_patterns: &[
            "## Selected Short-Circuit RHS Materialization",
            "4096 expression nodes and depth",
            "The skipped arm does no RHS work",
            "independent 384-case before/after oracle",
            "total bool-word decoder divisions by two",
            "not general short-circuit capture closure",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-caller-spills-gated-tensor-scope",
        path: "tools/nuis/src/dev_tensor_data.rs",
        required_patterns: &[
            "Selected short-circuit RHS caller materialization follow-up:",
            "384 independent before/after oracle cases",
            "original business branches are not duplicated",
            "both local-selection and full-control source routes",
            "active/86 remains unchanged",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-source-logical-roots-exact-kinds-and-statement-window",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_values.rs",
        required_patterns: &[
            "mod roots_tests;",
            "predicate_returns: function.return_type.as_ref() == Some(&scalar_type(\"bool\"))",
            "ty.as_ref().is_none_or(|ty| ty == &scalar_type(\"bool\"))",
            "NirStmt::Return(Some(value)) if !in_loop && self.predicate_returns",
            "self.block(body, &mut scope.clone(), true)",
            "fn guard_selection(",
            "Capture the current version before the destination is",
            "self.extract_selections = selections",
            "self.predicate_returns = returns",
            "ty.clone().or(guarded_kind)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-source-logical-roots-runtime-versions-and-vetoes",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_values_roots_tests.rs",
        required_patterns: &[
            "conditional_root_values_preserve_lazy_bindings_constants_and_returns",
            "conditional_root_values_keep_complete_rhs_binding_identity_and_idempotence",
            "conditional_root_values_preserve_selected_versions_nested_bindings_and_early_exits",
            "conditional_root_values_keep_kind_loop_nested_effect_and_work_vetoes_unchanged",
            "conditional_root_values_retain_effectful_nested_return_speculation_rejection",
            "conditional_root_values_keep_inferred_local_kinds_for_following_logical_edges",
            "usize::from(selected) + usize::from(second_selected)",
            "\"rebind\", \"changed\", \"branch\", \"return\"",
            "yir.functions.reverse()",
            "assert_eq!(module, before",
            "Some((**rhs).clone())",
            "mod native;",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-source-logical-roots-default-aot-not-private-registration",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_values_roots_native_tests.rs",
        required_patterns: &[
            "conditional_root_values_execute_default_source_lazy_rhs_and_native_traps",
            "No explicit private projection registration or foreign runtime shim",
            "crate::pipeline::compile_source(&source)",
            "Duration::from_secs(10)",
            "child.kill()",
            "child.wait()",
            "Some(4 | 5)",
            "fs::remove_dir_all",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "reference-entry-exits-use-registered-contract-and-owned-tail",
        path: "crates/yir-exec/src/execution_engine/entry_exits.rs",
        required_patterns: &[
            "function.role == YirFunctionRole::Entry",
            "domain.function_exit(",
            "engine.state.values.insert(result.node.clone(), value)",
            "self.closed.insert(owner.name.as_str())",
            "delayed.remove(node)",
            "this entry's tail",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "reference-cpu-composite-print-return-exit-arity-and-selection",
        path: "crates/yir-domain-cpu/src/function_exit.rs",
        required_patterns: &[
            "\"guard_print_return\" => (3, 3, 2, None)",
            "node(\"guard_print_return\", &[\"ready\", \"printed\", \"returned\"])",
            "(\"guard_print_return\", 3)",
            "state.expect_value(&node.op.args[index]).cloned()",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-composite-print-return-retains-statement-effect-frontier",
        path: "tools/nuisc/src/lowering/guard_ops.rs",
        required_patterns: &[
            "pub(super) fn lower_guard_print_return(",
            "from: return_name,\n        to: name.clone(),\n    });\n    chain_statement_effect(state, &name);",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "reference-entry-exits-preserve-global-work-errors-and-verification",
        path: "crates/yir-exec/tests/registered_execution.rs",
        required_patterns: &[
            "registered_entry_exit_skips_only_owned_tail_and_publishes_the_actual_result",
            "registered_entry_exit_errors_propagate_without_executing_tail_or_retrying",
            "registered_entry_exit_does_not_relax_single_entry_verification",
            "trace.values[\"tail\"], Value::Int(42)",
            "trace.values[\"global\"], Value::Int(9)",
            "2 entry functions",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-source-logical-roots-documentation-boundary",
        path: "docs/reference/nuis-native-scalar-loop-snapshots-v1.md",
        required_patterns: &[
            "## Source Logical Value Roots",
            "before destination rebinding",
            "not wider private capture projection",
            "entry-local return",
            "single-entry verification",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-source-logical-roots-tensor-scope",
        path: "tools/nuis/src/dev_tensor_data.rs",
        required_patterns: &[
            "Source logical value-root follow-up:",
            "complete RHS stays in its selected guard",
            "Registered entry exits stop only their owned tail",
            "active/86 remains unchanged",
        ],
    },
];
