use crate::dev_tensor_drift::DevTensorDriftCheckSpec;

pub(crate) const DEV_TENSOR_RUNTIME_DRIFT_CHECKS: &[DevTensorDriftCheckSpec] = &[
    DevTensorDriftCheckSpec {
        id: "workflow-surface-json-regression",
        path: "tools/nuis/src/main_tests/workflow_surface.rs",
        required_patterns: &[
                "nsld_final_executable_output_boundary_status",
                "nsld_final_executable_output_materialization_status",
                "nsld_final_executable_output_execution_handoff_contract",
                "nsld_final_executable_output_execution_handoff_ready",
                "nsld_final_executable_output_execution_handoff_status",
                "nsld_final_executable_output_execution_handoff_target",
                "nsld_final_executable_output_execution_handoff_evidence_status",
                "nsld_final_executable_output_execution_handoff_first_blocker",
                "nsld_final_executable_output_execution_handoff_decision_code",
                "nsld_final_executable_output_payload_execution_trace_protocol",
                "nsld_final_executable_output_payload_execution_trace_available",
                "nsld_final_executable_output_payload_execution_trace_record_count",
                "nsld_final_executable_output_payload_execution_trace_ready_record_count",
                "nsld_final_executable_output_nsdb_replay_contract",
                "nsld_final_executable_output_nsdb_replay_ready",
                "nsld_final_executable_output_nsdb_replay_status",
                "nsld_final_executable_output_nsdb_replay_checkpoint_count",
                "nsld_final_executable_output_nsdb_replayable_checkpoint_count",
                "nsld_final_executable_output_artifact_chain_safe_next_contract",
                "nsld_final_executable_output_artifact_chain_safe_next_probe_command",
                "closure_summary_artifact_chain_safe_next_contract",
                "closure_summary_artifact_chain_safe_next_probe_command",
                "nsld_final_executable_output_nsdb_replay_command",
                "nsld_final_executable_output_nsdb_replay_next_action",
                "nsld_final_executable_output_nsdb_replay_next_command",
                "nsld_final_executable_output_nsdb_replay_first_blocker",
                "nsld_final_executable_pipeline_execution_handoff_contract",
                "nsld_final_executable_pipeline_execution_handoff_ready",
                "nsld_final_executable_pipeline_execution_handoff_status",
                "nsld_final_executable_pipeline_execution_handoff_target",
                "nsld_final_executable_pipeline_execution_handoff_evidence_status",
                "nsld_final_executable_pipeline_execution_handoff_first_blocker",
                "nsld_final_executable_pipeline_execution_handoff_decision_code",
                "workflow_run_artifact_prelaunch_kind",
                "workflow_run_artifact_prelaunch_status",
                "workflow_run_artifact_prelaunch_evidence_status",
                "workflow_run_artifact_prelaunch_command",
                "workflow_run_artifact_prelaunch_reason",
                "closure_summary_source",
                "closure_summary_status",
                "closure_summary_ready",
                "closure_summary_primary_blocker",
                "closure_summary_next_action",
                "closure_summary_next_command",
                "safe_next_contract",
                "safe_next_probe_json_command",
                "safe_next_gate_required_field",
                "safe_next_gate_action_field",
                "workflow_launch_evidence_protocol",
                "workflow_launch_evidence_debugger_contract",
                "workflow_launch_evidence_host_runner_probe_status",
                "workflow_nsdb_handoff_available",
                "link_plan_heterogeneous_backend_artifact_units",
                "link_plan_heterogeneous_backend_artifact_ready_units",
                "link_plan_heterogeneous_backend_artifact_first_unready",
                "nsld_final_executable_output_recommended_next_action",
                "nsld_final_executable_output_object_valid",
                "nsld_final_executable_output_object_family",
                "nsld_final_executable_output_object_magic_status",
            "nsld_final_executable_output_object_magic",
                "nsld_final_executable_output_object_expected_hash",
                "nsld_final_executable_output_object_actual_hash",
                "nsld_final_executable_output_object_issues",
                "nsld_self_owned_image_status",
                "nsld_backend_artifact_payload_evidence_available",
                "nsld_backend_artifact_payload_count",
                "nsld_backend_artifact_payload_role_status",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "project-frontdoor-closure-summary",
        path: "tools/nuis/src/main_tests/project_health.rs",
        required_patterns: &[
            "closure_summary_source",
            "closure_summary_status",
            "closure_summary_ready",
            "closure_summary_primary_blocker",
            "closure_summary_next_action",
            "closure_summary_next_command",
            "safe_next_contract",
            "safe_next_probe_json_command",
            "safe_next_gate_required_field",
            "project-status-link-plan",
            "prepared artifact chain is missing `link-inputs`",
            "project-status",
            "project-doctor",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "project-frontdoor-link-plan-closure-summary",
        path: "tools/nuis/src/surface_render/project_closure.rs",
        required_patterns: &[
            "project_closure_summary",
            "link_plan_source",
            "nsld_prepared_artifact_chain_summary",
            "nsld_drive_recommendation_for_output_dir",
            "with_nsld_drive_safe_next",
            "nsld_final_executable_tail_summary",
            "from_nsld_final_output_closure",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "frontdoor-closure-summary-final-output-replay-gate",
        path: "tools/nuis/src/closure_summary.rs",
        required_patterns: &[
            "from_nsld_final_output_closure",
            "with_nsld_drive_safe_next",
            "nsld-drive-safe-next",
            "nsld-drive-safe-next-v1 gate required",
            "run-artifact-or-replay-nsdb",
            "inspect-nsdb-replay-evidence",
            "replay evidence is blocked",
            "final_output.nsdb_replay_ready",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "frontdoor-closure-summary-canonical-doc",
        path: "docs/reference/nuis-frontdoor-surface-reference.md",
        required_patterns: &[
            "canonical human closure summary",
            "read this group first",
            "closure_summary_primary_blocker",
            "closure_summary_next_action",
            "Reading order",
            "dev_tensor_weakest_task_card_coordinate",
            "dev_tensor_weakest_task_card_handoff_coordinate",
            "which bootstrap coordinate should we push",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-artifact-workflow-closure-summary-reading-rule",
        path: "docs/reference/nuis-native-artifact-workflow.md",
        required_patterns: &[
            "canonical human closure line",
            "workflow",
            "project-status",
            "project-doctor",
            "read it before drilling",
            "dev_tensor_weakest_task_card_*",
            "dev_tensor_weakest_task_card_handoff_*",
            "artifact closure work and tensor-driven",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "workflow-object-output-identity-mirror",
        path: "tools/nuis/src/workflow/object_identity.rs",
        required_patterns: &[
            "workflow_object_identity_mirrors_nsld_object_magic_families",
            "workflow_object_identity",
            "object_family_for_format",
            "object_magic_status",
            "object_magic_hex",
            "0xcffaedfe",
            "0x7f454c46",
            "0x6486",
        ],
    },
    DevTensorDriftCheckSpec {
            id: "artifact-runtime-json-regression",
            path: "tools/nuis/src/main_tests/artifact_runtime.rs",
            required_patterns: &[
                "nsld_final_executable_output_boundary_status",
                "nsld_final_executable_output_materialization_status",
                "nsld_final_executable_output_execution_handoff_contract",
                "nsld_final_executable_output_execution_handoff_ready",
                "nsld_final_executable_output_execution_handoff_status",
                "nsld_final_executable_output_execution_handoff_target",
                "nsld_final_executable_output_execution_handoff_evidence_status",
                "nsld_final_executable_output_execution_handoff_first_blocker",
                "nsld_final_executable_output_execution_handoff_decision_code",
                "nsld_final_executable_output_payload_execution_trace_protocol",
                "nsld_final_executable_output_payload_execution_trace_available",
                "nsld_final_executable_output_payload_execution_trace_record_count",
                "nsld_final_executable_output_payload_execution_trace_ready_record_count",
                "nsld_final_executable_pipeline_execution_handoff_contract",
                "nsld_final_executable_pipeline_execution_handoff_ready",
                "nsld_final_executable_pipeline_execution_handoff_status",
                "nsld_final_executable_pipeline_execution_handoff_target",
                "nsld_final_executable_pipeline_execution_handoff_evidence_status",
                "nsld_final_executable_pipeline_execution_handoff_first_blocker",
                "nsld_final_executable_pipeline_execution_handoff_decision_code",
                "nsld_final_executable_output_recommended_next_action",
                "nsld_self_owned_image_status",
                "run_artifact_prelaunch_kind",
                "run_artifact_prelaunch_status",
                "run_artifact_prelaunch_evidence_status",
                "run_artifact_prelaunch_runner_command_present",
                "run_artifact_prelaunch_entrypoint_present",
                "run_artifact_prelaunch_entrypoint_protocol",
                "run_artifact_prelaunch_entrypoint_protocol_valid",
                "nsld-host-entrypoint",
                "artifact_closure_kind",
                "artifact_closure_status",
                "artifact_closure_evidence_status",
                "artifact_closure_runner_command_present",
                "artifact_closure_entrypoint_present",
                "artifact_closure_entrypoint_protocol",
                "artifact_closure_entrypoint_protocol_valid",
                "artifact_launch_evidence_protocol",
                "artifact_launch_evidence_debugger_contract",
                "artifact_launch_evidence_host_runner_probe_status",
                "artifact_nsdb_handoff_available",
                "artifact_nsdb_handoff_protocol",
                "artifact_nsdb_handoff_record_count",
                "nsld_backend_artifact_payload_evidence_available",
                "nsld_backend_artifact_payload_count",
                "nsld_backend_artifact_payload_role_status",
                "nsld_backend_artifact_payload_ids",
                "nsld_backend_artifact_payload_kinds",
                "artifact_launch_evidence_backend_artifact_payload_evidence_available",
                "artifact_launch_evidence_backend_artifact_payload_count",
                "artifact_launch_evidence_backend_artifact_payload_role_status",
                "launch_evidence_backend_artifact_payload_evidence_available",
                "launch_evidence_backend_artifact_payload_count",
                "launch_evidence_backend_artifact_payload_role_status",
                "host_runner_backend_artifact_payload_count",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "artifact-doctor-metadata-mirrors",
            path: "tools/nuis/src/artifact_doctor_mirrors.rs",
            required_patterns: &[
                "collect_payload_decoder_manifest_mirror",
                "collect_device_provider_sample_manifest_mirror",
                "collect_backend_artifact_payload_evidence",
                "PayloadDecoderManifestMirror",
                "DeviceProviderSampleManifestMirror",
                "BackendArtifactPayloadEvidence",
                "provider_bundle_registry_contract",
                "provider_bundle_manifest_hash",
                "first_provider_bundle_package_id",
                "provider_bundle_evidence_status",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "artifact-runtime-run-artifact-json-regression",
            path: "tools/nuis/src/main_tests/artifact_runtime_run_artifact.rs",
            required_patterns: &[
                "repair_provider_output_payload",
                "hetero_runtime_trace_device_sample_handoff_status",
                "device_provider_sample_manifest_persisted",
                "materialize_provider_samples",
                "nsdb materialize-provider-samples",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "run-artifact-hetero-runtime-trace-surface",
            path: "tools/nuis/src/artifact_runtime_trace.rs",
            required_patterns: &[
                "HeteroRuntimeTraceSummary",
                "nsdb-yir-hetero-runtime-trace-v1",
                "hetero_runtime_trace_available",
                "hetero_runtime_trace_status",
                "hetero_runtime_trace_payload_evidence_available",
                "hetero_runtime_trace_domain_families",
                "HeteroRuntimeTraceRecord",
                "trace_record_for_unit",
                "persist_nsdb_trace",
                "backend-artifact",
                "domain-metadata",
                "artifact_device_sample",
                "DEVICE_PROVIDER_SAMPLE_FILE_NAME",
                "render_device_provider_sample_manifest_toml",
                "handoff-to-nsdb-trace",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "run-artifact-host-runner-probe-surface",
            path: "tools/nuis/src/artifact_runtime_command.rs",
            required_patterns: &[
                "run_artifact_host_runner_surface",
                "HostRunnerJsonSurface",
                "run_nsld_host_runner",
                "try_run_nsld_host_runner",
                "resolve_nuis_host_runner_program",
                "from_surfaces_with_backend_payload_evidence",
                "HeteroRuntimeTraceSummary",
                "persist_launch_evidence_nsdb_handoff",
                "nuis-host-runner",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "run-artifact-nsdb-handoff-persistence",
            path: "tools/nuis/src/artifact_nsdb_handoff.rs",
            required_patterns: &[
                "nuis-nsdb-payload-execution-handoff-v1",
                "nuis.nsdb.payload-execution-handoff.toml",
                "persist_launch_evidence_nsdb_handoff",
                "launch_evidence_nsdb_handoff_persisted",
                "launch_evidence_nsdb_handoff_record_count",
                "launch_evidence_nsdb_handoff_ready_record_count",
                "launch_evidence_nsdb_handoff_first_trace_id",
                "hetero_execution_closure_next_action",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "nsdb-payload-execution-handoff-consumer",
            path: "tools/nsdb/src/handoff.rs",
            required_patterns: &[
                "nuis.nsdb.payload-execution-handoff.toml",
                "nuis-nsdb-payload-execution-handoff-v1",
                "nsdb-yir-payload-execution-trace-v1",
                "read_payload_execution_handoff",
                "payload_handoff_status",
                "parse_payload_execution_events",
                "NsdbPayloadExecutionEvent",
                "hetero_execution_closure_status",
                "hetero_execution_closure_ready",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "nsdb-inspect-payload-handoff-surface",
            path: "tools/nsdb/src/json.rs",
            required_patterns: &[
                "payload_execution_handoff_available",
                "payload_execution_handoff_protocol",
                "payload_execution_handoff_debugger_contract",
                "payload_execution_handoff_status",
                "payload_execution_handoff_record_count",
                "payload_execution_handoff_first_trace_id",
                "payload_execution_event_filter_active",
                "payload_execution_handoff_hetero_execution_closure_status",
                "provider_output_payload_path",
                "provider_output_payload_hash",
                "provider_output_payload_attach_status",
                "payload_execution_event_count",
                "payload_execution_event_query_contract",
                "payload_execution_event_source",
                "payload_execution_event_query_result_count",
                "nsdb_replay_plan_json",
                "replay_hetero_execution_closure_status",
                "debugger_transcript_contract",
                "payload_decoder_manifest_status",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "nsdb-replay-device-sample-handoff-consumer",
            path: "tools/nsdb/src/replay.rs",
            required_patterns: &[
                "device_sample_handoffs",
                "provider-handoff-observed",
                "device-sample-handoff",
                "provider_handoff_materialization_status",
                "provider_sample_blocker",
                "provider-output-payload-invalid",
                "hetero_execution_closure_blocker",
                "hetero-execution-closure",
                "replay_source_events",
                "hetero_runtime_trace",
                "domain-metadata",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "nsdb-yir-replay-transcript-consumer",
            path: "tools/nsdb/src/transcript.rs",
            required_patterns: &[
                "nsdb-yir-replay-transcript-v1",
                "nsdb-yir-replay-identity-v1",
                "final_image_binding_proof_hash",
                "transcript-consumed",
                "transcript-stopped",
                "transcript-blocked",
                "nsdb-yir-replay-control-v1",
                "nsdb-yir-breakpoint-predicate-v1",
                "nsdb-yir-replay-resume-cursor-v1",
                "nsdb-yir-replay-resume-input-v1",
                "frame-selected",
                "breakpoint-hit",
                "breakpoint-predicate-hit",
                "resume-ready",
                "cursor-accepted",
                "cursor-rejected",
                "replayed_checkpoint_count",
                "build_replay_transcript",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "nsdb-yir-replay-control-cli",
            path: "tools/nsdb/src/cli.rs",
            required_patterns: &[
                "--frame",
                "--break-at",
                "--break-phase",
                "--break-entry",
                "--resume-after",
                "--resume-next",
                "--resume-cursor",
                "--save-cursor",
                "mutually exclusive",
                "NsdbReplayControl",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "nsdb-yir-replay-cursor-persistence",
            path: "tools/nsdb/src/cursor.rs",
            required_patterns: &[
                "nsdb-yir-replay-cursor-record-v2",
                "resume_cursor_ready",
                "load_replay_cursor",
                "persist_cursor_content_atomically",
                "create_new(true)",
                "sync_all",
                "fs::rename",
                "transcript_contract",
                "source_contract",
                "identity_contract",
                "final_image_binding_proof_hash",
                "provider_dispatch_authority_contract",
                "provider_dispatch_table_hash",
                "provider_dispatch_selected_set_hash",
                "provider_dispatch_identity_hash",
                "load_replay_cursor_with_dispatch",
                "after_frame_id",
                "next_frame_id",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "nsdb-yir-replay-cursor-lineage",
            path: "tools/nsdb/src/cursor_lineage.rs",
            required_patterns: &[
                "nsdb-yir-replay-cursor-lineage-v2",
                "LINEAGE_LIMIT",
                "previous_hash",
                "current_hash",
                "final_image_binding_proof_hash",
                "persist_validated_content_atomically",
                "breaks the cursor hash chain",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "nsdb-yir-replay-control-native-smoke",
            path: "tools/nuis/tests/self_contained_nsb_smoke.rs",
            required_patterns: &[
                "nsdb-yir-replay-control-v1",
                "debugger_transcript_control_status",
                "nsdb-yir-breakpoint-predicate-v1",
                "nsdb-yir-replay-resume-cursor-v1",
                "nsdb-yir-replay-resume-input-v1",
                "frame-selected",
                "breakpoint-hit",
                "breakpoint-predicate-hit",
                "cursor-rejected",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "nsdb-yir-replay-cursor-official-hetero-smoke",
            path: "tools/nuis/tests/official_galaxy_hetero_smoke/replay.rs",
            required_patterns: &[
                "debugger_transcript_final_image_binding_proof_hash",
                "nuis.nsdb.replay-cursor.toml",
                "nsdb-yir-replay-cursor-record-v2",
                "debug-resume",
                "cursor-unavailable",
                "cursor-accepted",
                "breakpoint-hit",
                "debugger_transcript_selected_frame_id",
                "debugger_transcript_replayed_checkpoint_count",
                "replaced replay cursor next frame",
                "nuis chained heterogeneous debug resume",
                "nsdb-yir-replay-cursor-lineage-v2",
                "entry_count = 2",
                "replay cursor lineage content hash",
                "provider_dispatch_identity_hash",
                "nsld_final_executable_output_debugger_cursor_lineage_provider_dispatch_identity_hash",
                "closure_summary_debugger_cursor_lineage_provider_dispatch_identity_hash",
                "nsld_final_executable_output_debugger_cursor_ready",
                "nsld_final_executable_output_debugger_cursor_next_command",
                "closure_summary_debugger_cursor_ready",
                "closure_summary_debugger_cursor_next_command",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "nuis-debugger-cursor-handoff-mirror",
            path: "tools/nuis/src/artifact_nsdb_replay_cursor.rs",
            required_patterns: &[
                "nuis-debugger-cursor-handoff-v1",
                "nuis.nsdb.replay-cursor.toml",
                "cursor-resume-ready",
                "cursor-unavailable",
                "cursor-invalid",
                "nuis debug-resume",
                "next_command",
                "transcript_contract",
                "source_contract",
                "identity_contract",
                "final_image_binding_proof_hash",
                "same_manifest",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "nuis-debugger-cursor-lineage-mirror",
            path: "tools/nuis/src/artifact_nsdb_replay_cursor_lineage.rs",
            required_patterns: &[
                "nuis-debugger-cursor-lineage-mirror-v1",
                "nsdb-yir-replay-cursor-lineage-v2",
                "provider_dispatch_identity_hash",
                "lineage-unavailable",
                "lineage-invalid",
                "lineage-ready",
                "cursor_hash",
                "final_image_binding_proof_hash",
                "entry_count",
                "latest_hash",
                "first_blocker",
                "repair-cursor-lineage",
                "debug-lineage-repair",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "nsdb-yir-replay-cursor-lineage-repair",
            path: "tools/nsdb/src/cursor_lineage.rs",
            required_patterns: &[
                "nsdb-yir-replay-cursor-lineage-repair-v2",
                "already-ready",
                "lineage-rebuilt",
                "repair-history-recovered",
                "lineage_mutated",
                "repair_journal_mutated",
                "archive_invalid_lineage",
                "invalid-",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "nuis-debug-resume-frontdoor",
            path: "tools/nuis/src/debug_resume_command.rs",
            required_patterns: &[
                "handle_debug_resume",
                "read_debugger_cursor_handoff",
                "cursor.ready",
                "--resume-cursor",
                "--break-at",
                "--break-phase",
                "--break-entry",
                "--save-cursor",
                "NUIS_NSDB_BIN",
                "resolve_nsdb_program",
                "resolve_artifact_output_input",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "nuis-debug-resume-cli",
            path: "tools/nuis/src/cli.rs",
            required_patterns: &[
                "DebugResume",
                "debug-resume",
                "parse_debug_resume_args",
                "breakpoint_phase",
                "cursor_output",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "nuis-debug-resume-control-parser",
            path: "tools/nuis/src/cli/support.rs",
            required_patterns: &[
                "DebugResumeArgs",
                "--break-at",
                "--break-phase",
                "--break-entry",
                "--save-cursor",
                "mutually exclusive",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "nuis-debugger-cursor-final-output-mirror",
            path: "tools/nuis/src/workflow/link_plan_final_output.rs",
            required_patterns: &[
                "read_debugger_cursor_handoff",
                "debugger_cursor_handoff_contract",
                "debugger_cursor_path",
                "debugger_cursor_ready",
                "debugger_cursor_status",
                "debugger_cursor_next_command",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "frontdoor-debugger-transcript-command-handoff",
            path: "tools/nuis/src/closure_summary.rs",
            required_patterns: &[
                "debugger_transcript_next_command",
                "closure_summary_debugger_transcript_next_command",
                "nsdb_replay_next_command",
                "closure_summary_debugger_cursor_handoff_contract",
                "closure_summary_debugger_cursor_path",
                "closure_summary_debugger_cursor_ready",
                "closure_summary_debugger_cursor_status",
                "closure_summary_debugger_cursor_next_command",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "nsdb-provider-sample-materializer",
            path: "tools/nsdb/src/provider_sample_materialize.rs",
            required_patterns: &[
                "materialize_provider_samples",
                "provider-sample-materialized",
                "provider-sample-blocked",
                "nuis-nsdb-provider-sample-artifact-v1",
                "deterministic-provider-sample-artifact",
                "nsdb-materialize-provider-samples",
                "provider_runner_adapter_id",
                "provider_runner_real_device_capable",
                "provider_runner_real_device_probe_status",
                "provider_execution_comparison_contract",
                "provider_execution_comparison_status",
                "provider_output_payload_contract",
                "provider_output_payload_status",
                "provider_output_payload_evidence_status",
                "provider_output_payload_next_action",
                "provider_output_payload_evidence",
                "provider_output_payload_detail",
                "provider_bundle_registry_contract",
                "provider_bundle_manifest_contract",
                "provider_bundle_manifest_hash",
                "provider_bundle_manifest_entry_count",
                "first_provider_bundle_package_id",
                "first_provider_bundle_id",
                "selected_provider_bundle_set_contract",
                "selected_provider_bundle_count",
                "selected_provider_bundle_set_hash",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "nsld-provider-bundle-final-output-evidence",
            path: "tools/nsld/src/final_executable_provider_sample.rs",
            required_patterns: &[
                "nuis-provider-bundle-registry-v1",
                "nuis-provider-bundle-manifest-v1",
                "provider_bundle_manifest_hash",
                "provider_bundle_manifest_entry_count",
                "first_provider_bundle_package_id",
                "first_provider_bundle_id",
                "provider-bundle-evidence-invalid",
                "provider_bundle_evidence_is_valid",
                "selected_provider_bundle_set_validation_status",
                "nuis-selected-provider-bundle-set-v1",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "nuis-provider-bundle-final-output-mirror",
            path: "tools/nuis/src/workflow/link_plan_json_nsld_output.rs",
            required_patterns: &[
                "device_provider_sample_provider_bundle_registry_contract",
                "device_provider_sample_provider_bundle_manifest_hash",
                "device_provider_sample_manifest_first_provider_bundle_package_id",
                "object_package_provider_bundle_registry_contract",
                "object_package_provider_bundle_manifest_hash",
                "object_package_first_provider_bundle_id",
                "object_package_provider_bundle_evidence_status",
                "object_package_selected_provider_bundle_set_contract",
                "object_package_selected_provider_bundle_count",
                "object_package_selected_provider_bundle_set_hash",
                "object_package_selected_provider_bundle_set_validation_status",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "nuis-provider-bundle-closure-mirror",
            path: "tools/nuis/src/closure_summary_provider_bundle.rs",
            required_patterns: &[
                "ProviderBundleClosureMirror",
                "registry_contract",
                "manifest_contract",
                "manifest_hash",
                "manifest_entry_count",
                "first_package_id",
                "first_bundle_id",
                "evidence_status",
                "selected_set_contract",
                "selected_count",
                "selected_set_hash",
                "selected_set_validation_status",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nuis-provider-bundle-workflow-closure-render",
            path: "tools/nuis/src/workflow/link_plan_json.rs",
            required_patterns: &["append_projection_json_fields"],
        },
    DevTensorDriftCheckSpec {
            id: "nsdb-provider-sample-materializer-cli",
            path: "tools/nsdb/src/cli.rs",
            required_patterns: &[
                "MaterializeProviderSamples",
                "materialize-provider-samples",
                "--provider-family",
                "parses_materialize_provider_samples_command",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "run-artifact-launch-evidence-surface",
            path: "tools/nuis/src/artifact_launch_evidence.rs",
            required_patterns: &[
                "RunArtifactLaunchEvidence",
                "json_fields_with_prefix",
                "nuis-run-artifact-launch-evidence-v1",
                "nsdb-yir-launch-evidence-v1",
                "nsdb-yir-payload-execution-trace-v1",
                "launch_evidence_first_payload_status",
                "launch_evidence_first_payload_entry_symbol",
                "launch_evidence_payload_execution_trace_records",
                "payload_execution_trace_records",
                "handoff-payload-trace-to-nsdb",
                "launch_evidence_backend_artifact_payload_evidence_available",
                "launch_evidence_backend_artifact_payload_count",
                "launch_evidence_backend_artifact_payload_role_status",
                "launch_evidence_backend_artifact_payload_ids",
                "launch_evidence_backend_artifact_payload_kinds",
                "nuis-hetero-execution-closure-v1",
                "launch_evidence_hetero_execution_closure_status",
                "handoff-hetero-execution-evidence-to-nsdb",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "run-artifact-host-runner-json-surface",
            path: "tools/nuis/src/artifact_host_runner.rs",
            required_patterns: &["HostRunnerJsonSurface", "host_runner_invoked", "host_runner_backend_artifact_payload_count", "host_runner_backend_artifact_payload_table_hash", "host_runner_container_loader_metadata_binding_validation_status", "host_runner_container_loader_selected_provider_bundle_set_hash"],
        },
        DevTensorDriftCheckSpec {
            id: "host-runner-container-loader-handoff-policy",
            path: "tools/nuis-host-runner/src/container.rs",
            required_patterns: &[
                "host_assisted_loader",
                "backend_artifact_payload_count",
                "backend_artifact_payload_table_hash",
                "container_loader_handoff_blockers",
                "external-import:",
                "container-loader:blocker",
                "position(|byte| *byte == 0)",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "host-runner-backend-artifact-payload-scan",
            path: "tools/nuis-host-runner/src/container_backend_payload.rs",
            required_patterns: &[
                "BackendArtifactPayloadSummary",
                "scan_backend_artifact_payloads",
                "backend_artifact_payload",
                "nustar-backend-artifact",
                "role_status",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "host-runner-container-loader-policy-regression",
            path: "tools/nuis-host-runner/src/tests.rs",
            required_patterns: &[
                "allows_host_assisted_container_handoff_when_required_external_import_is_declared",
                "blocks_self_contained_container_handoff_when_required_external_import_is_declared",
                "allows_host_assisted_container_loader_handoff_when_external_import_loader_blockers_are_declared",
                "container_loader_handoff_status",
                "container_loader_handoff_ready",
                "backend_artifact_payload_count",
                "backend_artifact_payload_first_kind",
                "nustar-backend-artifact:kernel:aarch64:apple-silicon-cpu",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "self-contained-nsb-frontdoor-smoke",
            path: "tools/nuis/tests/self_contained_nsb_smoke.rs",
            required_patterns: &[
                "self_contained_nsb_route_moves_from_nsld_drive_to_run_artifact_handoff",
                "nuis-self-contained-image",
                "self-contained-image-awaiting-nsld-handoff",
                "nsld-host-entrypoint",
                "host_runner_invoked",
                "host_runner_nsb_readable",
                "host_runner_nsb_hash_matches",
                "host_runner_nsb_payload_region_mapped",
                "host_runner_nsb_payload_scan_kind",
                "nsld-container-toml",
                "safe_next_contract",
                "safe_next_action",
                "safe_next_reason",
                "drive reached a clean artifact chain",
                "host_runner_container_loader_status",
                "host_runner_container_loader_entry_symbol",
                "host_runner_container_loader_handoff_ready",
                "host_runner_container_loader_handoff_status",
                "host_runner_backend_artifact_payload_count",
                "host_runner_backend_artifact_payload_first_kind",
                "launch_evidence_first_payload_status",
                "launch_evidence_first_payload_entry_symbol",
                "run-artifact-or-replay-nsdb",
                "nsdb-payload-execution-replay-plan-v1",
                "nsld_final_executable_output_nsdb_replay_command",
                "nsld_final_executable_output_nsdb_replay_ready",
                "build-report",
                "nsld_final_executable_output_nsdb_replayable_checkpoint_count",
                "nsld_final_executable_output_nsdb_replay_next_action",
            ],
        },
];
