use crate::dev_tensor_drift::DevTensorDriftCheckSpec;

pub(crate) const DEV_TENSOR_RUNTIME_PROVIDER_DRIFT_CHECKS: &[DevTensorDriftCheckSpec] = &[
        DevTensorDriftCheckSpec {
            id: "provider-request-ingress-llvm-passthrough",
            path: "crates/yir-lower-llvm/src/data_ingress_lowering.rs",
            required_patterns: &[
                "lower_data_provider_request_ingress",
                "provider_request_ingress",
                "request handle is outside",
                "preserves descriptor/provider metadata in YIR",
                "LlvmValueRef::I64",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-provider-worker-transport",
            path: "tools/nsdb/src/provider_worker_transport.rs",
            required_patterns: &[
                "nuis-provider-worker-transport-v1",
                "nuis-provider-worker-transport-registry-v1",
                "framed.stdio.worker.v1",
                "persistent-child-stdio",
                "registered-protocol-ready",
                "descriptor_transfer_status",
                "NUISPW1",
                "worker_pid",
                "two_requests_share_one_persistent_worker_process",
                "unix.scm-rights.worker.v1",
                "persistent-unix-socket",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-provider-worker-request-envelope",
            path: "tools/nsdb/src/provider_worker_request.rs",
            required_patterns: &[
                "nuis-provider-worker-request-envelope-v1",
                "NUISPWU2",
                "MAX_PROVIDER_WORKER_PAYLOAD_BYTES",
                "payload_hash",
                "descriptor_roles",
                "encode_provider_worker_request",
                "decode_provider_worker_request",
                "NUISPWUR7",
                "dispatch_status",
                "output_descriptor_hashes",
                "encode_provider_worker_reply",
                "decode_provider_worker_reply",
                "envelope_round_trips_opaque_payload_and_ordered_roles",
                "envelope_rejects_payload_or_role_count_tampering",
                "reply_round_trips_opaque_payload_and_request_identity",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-provider-worker-transport-unix",
            path: "tools/nsdb/src/provider_worker_transport_unix.rs",
            required_patterns: &[
                "encode_provider_worker_request",
                "decode_provider_worker_request",
                "decode_provider_worker_reply",
                "UnixDatagram::pair",
                "SCM_RIGHTS",
                "CMSG_FIRSTHDR",
                "CMSG_DATA",
                "MSG_CTRUNC",
                "FD_CLOEXEC",
                "OwnedFd",
                "descriptor count mismatch",
                "identity mismatch",
                "UnixWorkerProcessTransport",
                "NUIS_PROVIDER_WORKER_SOCKET_FD",
                "pre_exec",
                "child.id()",
                "descriptor_capability",
                "payload_hash",
                "descriptor_roles",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-provider-worker-transport-unix-tests",
            path: "tools/nsdb/src/provider_worker_transport_unix_tests.rs",
            required_patterns: &[
                "EBADF",
                "nuis_worker_negotiates_three_inputs_control_and_two_output_fan_out",
                "\"input.0\"",
                "\"input.1\"",
                "\"input.2\"",
                "\"control.adapter\"",
                "\"output.primary\"",
                "\"output.audit\"",
                "first_byte_sum, 77",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nuis-provider-worker-image",
            path: "stdlib/std/provider_worker_image.ns",
            required_patterns: &[
                "provider_worker.open",
                "provider_worker.receive",
                "provider_worker.launch_provider_key",
                "provider_worker.launch_capability_hash",
                "provider_worker.capsule_token",
                "provider_worker.capsule_input_count",
                "provider_worker.capsule_output_count",
                "nuis_provider_worker_request_v1",
                "provider_request_ingress",
                "async fn step_worker",
                "while running == 1",
                "await step_worker(running)",
                "host_provider_worker_reply",
                "host_provider_worker_close",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-provider-worker-image-registration",
            path: "tools/nsdb/src/provider_runner_registry.rs",
            required_patterns: &[
                "nuis-provider-worker-image-registry-v1",
                "ProviderWorkerImageRegistration",
                "select_provider_worker_image_registration",
                "nuis-provider-worker-operation-registry-v1",
                "select_provider_worker_operation_registration",
                "std.provider-worker.unix.aot-v27",
                "PROVIDER_WORKER_DESCRIPTOR_CAPABILITY_CONTRACT",
                "PROVIDER_WORKER_OUTPUT_DESCRIPTOR_CAPABILITY_CONTRACT",
                "max_semantic_descriptors: 31",
                "max_control_descriptors: 1",
                "max_output_descriptors: 8",
                "nuis-provider-runner-profile-registry-v1",
                "ProviderRunnerProfile",
                "select_provider_runner_profile",
                "select_provider_bundle_by_family",
                "runner_profiles_are_unique_contract_bound_static_contributions",
                "runner_selector_contains_no_provider_specific_match",
                "stable_registration_scalar",
                "worker_image_registration_is_open_ended_and_provider_bound",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-provider-runner-native-profile",
            path: "tools/nsdb/src/provider_runner_native.rs",
            required_patterns: &[
                "PROVIDER_RUNNER_PROFILE_REGISTRY_CONTRACT",
                "PROVIDER_BUNDLE",
                "data.host.bundle.v1",
                "data:host",
                "data.host.provider-worker-native",
                "provider-worker-native-runner",
                "native-provider-worker-available",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-provider-runner-metal-profile",
            path: "tools/nsdb/src/provider_runner_metal.rs",
            required_patterns: &[
                "PROVIDER_RUNNER_PROFILE_REGISTRY_CONTRACT",
                "PROVIDER_BUNDLE",
                "metal.apple-silicon-gpu.bundle.v1",
                "metal:apple-silicon-gpu",
                "metal.apple-silicon-gpu.real-device",
                "metal_probe_status",
                "Metal.framework",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-provider-runner-coreml-profile",
            path: "tools/nsdb/src/provider_runner_coreml.rs",
            required_patterns: &[
                "PROVIDER_RUNNER_PROFILE_REGISTRY_CONTRACT",
                "PROVIDER_BUNDLE",
                "coreml.apple-ane.bundle.v1",
                "coreml:apple-ane",
                "coreml.apple-ane.real-device",
                "coreml_probe_status",
                "CoreML.framework",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-provider-worker-image-resolver",
            path: "tools/nsdb/src/provider_worker_image.rs",
            required_patterns: &[
                "nuis-provider-worker-image-resolver-v1",
                "compute_compile_cache_key_with_identity",
                "lookup_compile_cache",
                "restore_compile_cache",
                "store_compile_cache",
                "NUIS_PROVIDER_WORKER_PROVIDER_KEY",
                "NUIS_PROVIDER_WORKER_CAPABILITY_HASH",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-provider-worker-session-lease",
            path: "tools/nsdb/src/provider_worker_lease.rs",
            required_patterns: &[
                "nuis-provider-worker-lease-v1",
                "resolve_provider_worker_image",
                "adapter_image_dir",
                "expected_sequence",
                "try_clone_worker_descriptor",
                "nuis-provider-worker-dispatch-permit-v1",
                "operation.operation_token",
                "register_provider_execution_capsule",
                "register_provider_execution_capsule_invoker",
                "capsule.capsule_token",
                "nuis-provider-worker-process-adapter-v5",
                "nuis-provider-worker-adapter-control-v2",
                "PROVIDER_WORKER_ADAPTER_CONTROL_CARRIER_CONTRACT",
                "PROVIDER_WORKER_ADAPTER_CONTROL_ROLE",
                "MAX_PROVIDER_WORKER_DISPATCH_PAYLOAD_BYTES",
                "MAX_INLINE_ADAPTER_CONTROL_BYTES",
                "render_adapter_control",
                "output_roles",
                "output_byte_lengths",
                "validate_dispatch_payload_size",
                "executable_hash",
                "execution_capsule_status: \"worker-invoked\"",
                "worker_output_receipt_status: \"verified\"",
                "additional_worker_outputs",
                "ProviderWorkerOutput",
                "dispatch_status: reply.dispatch_status",
                "UnixWorkerProcessTransport::spawn",
                "remove_image_dir",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-provider-worker-multi-output-lease-regression",
            path: "tools/nsdb/src/provider_worker_lease_tests.rs",
            required_patterns: &[
                "lease_preserves_registered_primary_and_additional_outputs",
                "process_adapter_materializes_and_validates_two_output_carriers",
                "NUIS_PROVIDER_OUTPUT_FDS",
                "output_hashes=",
                "nuis-provider-output-binding-v1",
                "PROVIDER_GRAPH_OUTPUT_OWNERSHIP_CONTRACT",
                "worker_dependency_binding",
                "output.audit",
                "transferable-carrier",
                "verified-payload",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-provider-execution-capsule",
            path: "tools/nsdb/src/provider_execution_capsule.rs",
            required_patterns: &[
                "nuis-provider-execution-capsule-v1",
                "builtin-nustar-provider-execution-capsule-registry",
                "worker-authorized-parent-adapter-v1",
                "register_provider_execution_capsule",
                "nuis-provider-execution-capsule-invoker-v1",
                "register_provider_execution_capsule_invoker",
                "capsule_registration_is_open_ended_and_role_bound",
                "capsule_registration_rejects_invalid_roles_or_operation_identity",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "official-provider-execution-capsule-evidence",
            path: "tools/nuis/tests/official_galaxy_hetero_smoke/provider_execution_evidence.rs",
            required_patterns: &[
                "nuis-provider-execution-capsule-v1",
                "capsule-token:",
                "native_output_3_worker_execution_capsule_invocation_mode = \\\"nuis-provider-worker-process-adapter-v5\\\"",
                "native_output_3_worker_execution_capsule_input_roles = \\\"input.0,input.1\\\"",
                "native_output_0_worker_adapter_control_mode = \\\"carrier\\\"",
                "output.result",
                "worker-invoked",
                "registered-invoked",
                "nuis-provider-worker-output-descriptor-v1",
                "worker_output_receipt_status",
                "native_output_4_output_handle_roles",
                "native_output_4_output_handle_ids",
                "native_output_4_output_handle_ownership_tokens",
                "native_output_4_graph_output_ownership_contract",
                "native_output_4_graph_output_release_count",
                "native_output_4_graph_output_release_roles",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-provider-worker-normal-execution",
            path: "tools/nsdb/src/provider_sample_execute.rs",
            required_patterns: &[
                "ProviderWorkerLeaseManager::new",
                "ProviderProcessAdapterCache::default",
                "worker_leases.dispatch",
                "select_provider_execution_adapter",
                ".prepare_worker_adapter",
                "(execution_adapter.execute)",
                "bind_output_binding_summary",
                "compare_provider_output_collection",
                "bind_output_comparison_collection",
                "worker_leases.close",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-provider-bundle-registry",
            path: "tools/nsdb/src/provider_bundle_registry.rs",
            required_patterns: &[
                "nuis-provider-bundle-registry-v1",
                "nuis-provider-bundle-manifest-v1",
                "nuis-selected-provider-bundle-set-v1",
                "ProviderBundleRegistration",
                "ProviderBundleManifestEntry",
                "provider_bundle_registrations",
                "PROVIDER_BUNDLE_MANIFEST_HASH",
                "provider_bundle_manifest_is_valid",
                "provider_bundle_manifest_hash",
                "ProviderBundleEvidence",
                "provider_bundle_evidence",
                "SelectedProviderBundleSetEvidence",
                "selected_provider_bundle_set_evidence",
                "select_provider_bundle_by_family",
                "select_provider_bundle_by_adapter_kind",
                "provider_bundles_cross_bind_unique_runner_and_execution_registrations",
                "PROVIDER_RUNNER_PROFILE_REGISTRY_CONTRACT",
                "PROVIDER_EXECUTION_ADAPTER_REGISTRY_CONTRACT",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsld-selected-provider-bundle-container-binding",
            path: "tools/nsld/src/main_container_metadata_binding_tests.rs",
            required_patterns: &[
                "container_immutably_binds_verified_selected_provider_bundle_set",
                "identity.selected-provider-bundle-set",
                "nuis-selected-provider-bundle-set-v1",
                "metadata_binding_table_hash",
                "container_emit_rejects_mismatched_selected_provider_bundle_set",
                "container_verify_rejects_tampered_embedded_metadata_binding",
                "final_image_loader_verifies_embedded_selected_provider_bundle_binding",
                "container_loader_metadata_binding_validation_status",
                "container_loader_selected_provider_bundle_set_contract",
                "invalid immutable metadata binding",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "host-runner-final-image-metadata-binding-verifier",
            path: "tools/nuis-host-runner/src/container_metadata_binding.rs",
            required_patterns: &[
                "MetadataBindingSummary",
                "scan_metadata_bindings",
                "identity.selected-provider-bundle-set",
                "nuis-selected-provider-bundle-set-v1",
                "metadata-binding-table-hash-mismatch",
                "rejects_length_preserving_selected_provider_binding_tamper",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nuis-launch-metadata-binding-gate",
            path: "tools/nuis/src/artifact_launch_binding.rs",
            required_patterns: &[
                "host_runner_binding_first_blocker",
                "container_loader_metadata_binding_validation_status",
                "container-loader-metadata-binding:not-verified",
                "selected-provider-bundle-set:contract-mismatch",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nuisc-provider-bundle-manifest-schema",
            path: "tools/nuisc/src/registry_provider_bundle.rs",
            required_patterns: &[
                "nuis-provider-bundle-manifest-entry-v1",
                "NustarProviderBundleRegistration",
                "provider_bundle_registrations",
                "six ordered fields",
                "is_rust_const",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-provider-bundle-aot-generator",
            path: "tools/nsdb/build.rs",
            required_patterns: &[
                "ensure_registered_domains_valid",
                "provider_bundle_registrations",
                "registrations.sort_by",
                "nuis-provider-bundle-manifest-v1",
                "PROVIDER_BUNDLE_MANIFEST_HASH",
                "PROVIDER_BUNDLE_MANIFEST_ENTRIES",
                "fnv1a64",
                "OUT_DIR",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nustar-data-provider-bundle-registration",
            path: "nustar-packages/data.toml",
            required_patterns: &[
                "provider_bundles",
                "nuis-provider-bundle-manifest-entry-v1",
                "data.host.bundle.v1",
                "provider_runner_native::PROVIDER_BUNDLE",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nustar-shader-provider-bundle-registration",
            path: "nustar-packages/shader.toml",
            required_patterns: &[
                "provider_bundles",
                "metal.apple-silicon-gpu.bundle.v1",
                "provider_runner_metal::PROVIDER_BUNDLE",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nustar-kernel-provider-bundle-registration",
            path: "nustar-packages/kernel.toml",
            required_patterns: &[
                "provider_bundles",
                "coreml.apple-ane.bundle.v1",
                "provider_runner_coreml::PROVIDER_BUNDLE",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-provider-execution-adapter-registry",
            path: "tools/nsdb/src/provider_execution_adapter.rs",
            required_patterns: &[
                "nuis-provider-execution-adapter-registry-v1",
                "ProviderExecutionAdapterRegistration",
                "PrepareProviderWorkerAdapter",
                "ExecuteProviderRequest",
                "select_provider_execution_adapter",
                "select_provider_bundle_by_adapter_kind",
                "provider_sample_frontdoor_contains_no_concrete_execution_branches",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-provider-execution-metal-registration",
            path: "tools/nsdb/src/provider_execution_metal.rs",
            required_patterns: &[
                "PROVIDER_EXECUTION_ADAPTER_REGISTRY_CONTRACT",
                "metal-real-device-runner",
                "prepare_worker_adapter",
                "parse_metal_worker_output",
                "is_gray8_invert",
                "is_f32_bias",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-provider-execution-coreml-registration",
            path: "tools/nsdb/src/provider_execution_coreml.rs",
            required_patterns: &[
                "PROVIDER_EXECUTION_ADAPTER_REGISTRY_CONTRACT",
                "coreml-real-device-runner",
                "prepare_worker_adapter",
                "parse_coreml_worker_output",
                "validate_provider_model_asset",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-provider-execution-native-registration",
            path: "tools/nsdb/src/provider_execution_native.rs",
            required_patterns: &[
                "PROVIDER_EXECUTION_ADAPTER_REGISTRY_CONTRACT",
                "provider-worker-native-runner",
                "DATA_FAN_OUT_SOURCE",
                "resolve_c",
                "nuis-data-fan-out-provider-runner-v1",
                "take_provider_worker_native_output",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-provider-worker-native-frontdoor-regression",
            path: "tools/nsdb/src/provider_sample_execute_tests.rs",
            required_patterns: &[
                "executes_registered_native_worker_with_two_graph_outputs",
                "data.host.provider-worker-native",
                "nuis-provider-worker-native-execution-v1",
                "nuis-provider-worker-process-adapter-v5",
                "nuis-provider-process-adapter-cache-v1",
                "nuis-provider-bundle-registry-v1",
                "nuis-provider-bundle-manifest-v1",
                "provider_bundle_manifest_entry_count = 3",
                "provider_bundle_package_id = \\\"official.data\\\"",
                "provider_bundle_id = \\\"data.host.bundle.v1\\\"",
                "transferable-carrier",
                "native_output_output_binding_count = \\\"2\\\"",
                "nuis-provider-output-comparison-collection-result-v1",
                "native_output_comparison_collection_count = \\\"2\\\"",
                "native_output_comparison_collection_mismatch_counts = \\\"0,0\\\"",
                "native_output_graph_output_release_count = \\\"2\\\"",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-provider-worker-summary",
            path: "tools/nsdb/src/provider_worker_summary.rs",
            required_patterns: &[
                "bind_worker_output",
                "worker_adapter_cache_contract",
                "worker_adapter_cache_identity",
                "worker_adapter_cache_status",
                "worker_adapter_executable_hash",
                "worker_adapter_control_contract",
                "worker_adapter_control_mode",
                "worker_additional_output_roles",
                "worker_additional_output_retention_statuses",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-provider-process-adapter-cache",
            path: "tools/nsdb/src/provider_process_adapter.rs",
            required_patterns: &[
                "nuis-provider-process-adapter-cache-v1",
                "ProviderProcessAdapterCache",
                "resolve_c",
                "compile_c_process_adapter",
                "process_adapter_cache_identity",
                "std::env::consts::OS",
                "std::env::consts::ARCH",
                "frameworks.join",
                "\"compiled\"",
                "\"hit\"",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-data-fan-out-process-adapter-source",
            path: "tools/nsdb/provider-runners/data_fan_out.c",
            required_patterns: &[
                "NUIS_PROVIDER_OUTPUT_FDS",
                "output.primary=fd:",
                "output.audit=fd:",
                "output_hashes=",
                "pwrite",
                "fnv1a64",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nuis-provider-worker-shim-transport",
            path: "tools/nuisc/src/aot_c_shim_provider_worker_runtime.rs",
            required_patterns: &[
                "NUISPWU2",
                "recvmsg",
                "SCM_RIGHTS",
                "FD_CLOEXEC",
                "nuis_host_provider_worker_receive",
                "nuis_host_provider_worker_capsule_token",
                "nuis_host_provider_worker_capsule_input_count",
                "nuis_host_provider_worker_capsule_output_count",
                "nuis_host_provider_worker_invoke_capsule",
                "nuis_provider_worker_invoke_process_adapter",
                "nuis-provider-worker-adapter-control-v2",
                "nuis-provider-worker-process-adapter-v5",
                "nuis_provider_worker_prepare_adapter_outputs",
                "nuis_provider_worker_expose_adapter_outputs",
                "nuis_provider_worker_validate_adapter_outputs",
                "nuis_provider_worker_role_count(fields[6])",
                "executable_hash",
                "waitpid",
                "nuis_provider_worker_output_hashes",
                "nuis_provider_worker_payload_scalar",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nuis-provider-worker-process-adapter-multi-output-shim",
            path: "tools/nuisc/src/aot_c_shim_provider_worker_process_adapter.rs",
            required_patterns: &[
                "nuis_provider_worker_parse_size_manifest",
                "nuis_provider_worker_parse_u64_manifest",
                "nuis_provider_worker_prepare_adapter_outputs",
                "nuis_provider_worker_expose_adapter_outputs",
                "NUIS_PROVIDER_OUTPUT_FD",
                "NUIS_PROVIDER_OUTPUT_FDS",
                "output_hashes",
                "nuis_provider_worker_validate_adapter_outputs",
                "nuispfd1-result",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-provider-worker-result-slot-hashes",
            path: "tools/nsdb/src/provider_worker_result.rs",
            required_patterns: &[
                "output_index",
                "output_hashes=",
                "output_hash=",
                "output hash manifest is too short",
                "parses_legacy_and_ordered_output_hash_protocols",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-provider-adapter-control-output-manifest-regression",
            path: "tools/nsdb/src/provider_worker_lease_tests.rs",
            required_patterns: &[
                "adapter_control_carries_ordered_output_role_and_length_manifests",
                "output.primary,output.audit",
                "24,8",
                "nuis-provider-worker-adapter-control-v2",
                "nuis-provider-worker-process-adapter-v5",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nuis-provider-worker-output-shim",
            path: "tools/nuisc/src/aot_c_shim_provider_worker_output.rs",
            required_patterns: &[
                "NUISPWUR7",
                "nuis_provider_worker_prepare_generic_outputs",
                "nuis_provider_worker_render_output_manifests",
                "NUIS_PROVIDER_WORKER_MAX_OUTPUT_FDS",
                "nuis_host_provider_worker_reply",
                "SCM_RIGHTS",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nuis-provider-worker-shim-launch",
            path: "tools/nuisc/src/aot_c_shim_provider_worker_launch.rs",
            required_patterns: &[
                "NUIS_PROVIDER_WORKER_SOCKET_FD",
                "NUISPWUH3",
                "nuis-provider-worker-descriptor-capability-v1",
                "nuis-provider-worker-output-descriptor-capability-v1",
                "NUIS_PROVIDER_WORKER_MAX_SEMANTIC_DESCRIPTORS",
                "NUIS_PROVIDER_WORKER_MAX_CONTROL_DESCRIPTORS",
                "NUIS_PROVIDER_WORKER_MAX_OUTPUT_DESCRIPTORS",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nuis-provider-worker-control-shim",
            path: "tools/nuisc/src/aot_c_shim_provider_worker_control.rs",
            required_patterns: &[
                "append_provider_worker_control_helpers",
                "nuis_provider_worker_payload_has",
                "nuis_provider_worker_split_tabs",
                "nuis_provider_worker_classify_descriptor_roles",
                "nuis_provider_worker_load_adapter_control",
                "nuis-provider-worker-adapter-control-carrier-v1",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-metal-opaque-carrier-input",
            path: "tools/nsdb/src/provider_runner_metal.rs",
            required_patterns: &[
                "execute_f32_bias_input",
                "ProviderCarrierInput::Path",
                "ProviderCarrierInput::OpaqueBytes",
                "select_provider_carrier_channel_adapter",
                "prepare_provider_carrier_channel",
                "frame_argument",
                "select_provider_output_carrier_adapter",
                "prepare_provider_output_carrier",
                "execute_f32_bias_bytes_platform",
                "prepare_gray8_worker_invocation",
                "parse_metal_worker_output",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-provider-input-binding",
            path: "tools/nsdb/src/provider_input_binding.rs",
            required_patterns: &[
                "nuis-provider-input-binding-v1",
                "parse_input_bindings",
                "validate_input_bindings",
                "validate_dependency_binding",
                "artifact",
                "dependency",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-provider-request-dependency",
            path: "tools/nsdb/src/provider_request.rs",
            required_patterns: &[
                "nuis-provider-request-dependency-v1",
                "validate_collection_dependencies",
                "dependency_graph_is_acyclic",
                "producer_request_id",
                "producer_output_buffer",
                "consumer_input_buffer",
                "*producer_index < consumer_index",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-provider-request-payload",
            path: "tools/nsdb/src/provider_request_payload.rs",
            required_patterns: &[
                "provider_request_dependency_contract",
                "provider_request_dependency_edge_count",
                "provider_request_dependency_edges",
                "provider_request_dependency_graph_hash",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-provider-output-comparison",
            path: "tools/nsdb/src/provider_output_comparison.rs",
            required_patterns: &[
                "PROVIDER_OUTPUT_COMPARISON_DESCRIPTOR_CONTRACT",
                "compare_provider_output",
                "absolute_tolerance",
                "relative_tolerance",
                "non_finite_policy",
                "comparison-passed",
                "size/hash evidence mismatch",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-metal-f32-provider-runner-source",
            path: "tools/nsdb/provider-runners/metal_f32_bias.m",
            required_patterns: &[
                "nuis_f32_bias",
                "nuis-metal-f32-bias-provider-runner-v1",
                "newBufferWithBytes",
                "dispatchThreads",
                "waitUntilCompleted",
                "carrierFrame",
                "NUISPCV1",
                "fnv1a64",
                "fdDescriptor",
                "mappedCarrierPacket",
                "mmap",
                "dataWithBytesNoCopy",
                "NUISPFD1",
                "newBufferWithBytesNoCopy",
                "NUIS_PROVIDER_OUTPUT_FD",
                "pwrite",
                "output_hash",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-coreml-provider-runner",
            path: "tools/nsdb/src/provider_runner_coreml.rs",
            required_patterns: &[
                "nuis-coreml-model-prediction-provider-runner-v1",
                "coreml-model-prediction-completed",
                "execute_model_prediction_inputs",
                "CoreMlProviderInput",
                "CoreMlProviderInputSource::PreparedChannel",
                "ProviderCarrierInput::Path",
                "ProviderCarrierInput::OpaqueBytes",
                "select_provider_carrier_channel_adapter",
                "prepare_provider_carrier_channel",
                "frame_argument",
                "select_provider_output_carrier_adapter",
                "prepare_provider_output_carrier",
                "nuis-coreml-compute-plan-evidence-v1",
                "compute_plan_supported_devices",
                "CoreML provider runner",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-coreml-provider-runner-source",
            path: "tools/nsdb/provider-runners/coreml_vector_affine.m",
            required_patterns: &[
                "MLMultiArray",
                "--multi",
                "inputData",
                "tensorFromInput",
                "carrierFrames",
                "NUISPCV1",
                "fnv1a64",
                "fdDescriptor",
                "mappedCarrierPacket",
                "carrierPacketOwners",
                "alignedCarrierFrames(packet)",
                "mmap",
                "dataWithBytesNoCopy",
                "initWithDataPointer",
                "NUISPFD1",
                "NUIS_PROVIDER_OUTPUT_FD",
                "pwrite",
                "output_hash",
                "inputFeatures",
                "compileModelAtURL",
                "predictionFromFeatures",
                "MLComputePlan",
                "computeDeviceUsageForNeuralNetworkLayer",
                "preferredComputeDevice",
                "supportedComputeDevices",
                "MLModelConfiguration",
                "MLComputeUnitsCPUAndNeuralEngine",
                "nuis-coreml-model-prediction-provider-runner-v1",
                "output_hex",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nuis-coreml-model-asset-builder",
            path: "tools/nuis/src/artifact_coreml_model.rs",
            required_patterns: &[
                "witsage_vector_affine_model",
                "witsage_dense_transform_model",
                "witsage_vector_add_model",
                "witsage.vector.affine",
                "witsage.feature-grid.projection",
                "compute_plan_preferred_devices=neural-engine",
                "input.features",
                "output.features",
                "65_568",
            ],
        },
];
