use crate::dev_tensor_drift::DevTensorDriftCheckSpec;

pub(super) const CHECKS: &[DevTensorDriftCheckSpec] = &[
    DevTensorDriftCheckSpec {
        id: "native-complete-return-condition-type-contract-and-mode-separation",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_terminal.rs",
        required_patterns: &[
            "mod computed_tests;",
            "Every tree evaluates its original pure condition inside selected",
            "Partial trees separately prove replay or stored exit signals",
            "let admitted = control_values::value_type(condition, &inner, catalog, layouts)",
            "control_values::value_type(condition, &inner, catalog, layouts).as_ref()",
            "== Some(&scalar_type(\"bool\"))",
            "if !admitted",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-complete-return-condition-whole-tree-preflight-and-scalar-captures",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_terminal.rs",
        required_patterns: &[
            "if !bounded(body)",
            "Every leaf returns; no parent continuation is copied into the helper",
            "let mut statements = 32usize",
            "if depth >= 64",
            "conditional_values::prefix::computed_expression_roots(expressions)",
            "if inner.contains_key(name)",
            "declared.is_some_and(|declared| declared != &ty)",
            "capture(condition, outer, inputs)",
            ".is_some_and(|ty| return_values::capture(result, ty))",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-complete-return-condition-execution-counts-kinds-checks-and-exits",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_complete_predicate_tests.rs",
        required_patterns: &[
            "conditional_return_complete_predicates_evaluate_calls_and_fields_once_behind_outer_guards",
            "assert_eq!(cases, 288)",
            "conditional_return_complete_predicates_keep_computed_bool_kinds_and_nested_comparisons",
            "assert_eq!(cases, 96)",
            "conditional_return_complete_predicates_keep_reached_division_and_remainder_checks",
            "assert_eq!(cases, 36)",
            "conditional_return_complete_predicates_keep_real_zero_returns_and_skip_parent_suffixes",
            "assert_eq!(cases, 18)",
            "conditional_return_complete_predicates_keep_prefix_checks_current_versions_and_sibling_paths",
            "assert_eq!(cases, 28)",
            "assert_eq!(nested_cases, 24)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-complete-return-condition-structural-budget-and-rejection-proofs",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_complete_predicate_tests.rs",
        required_patterns: &[
            "conditional_return_complete_predicates_retain_whole_bodies_captures_hygiene_and_idempotence",
            "assert_eq!(original, cloned)",
            "name.starts_with(\"__nuis_return_exit\")",
            "assert_eq!(module, once)",
            "conditional_return_complete_predicates_bound_condition_work_and_retain_partial_effect_and_capture_vetoes",
            "for count in [29, 30]",
            "for over in [false, true]",
            "callee: \"decide\".into()",
            "for _ in 0..64",
            "if helper(produce(divisor)) { return helper(produce(divisor)); }",
            "assert_eq!(module, before",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-complete-return-condition-default-source-aot-and-reached-traps",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_complete_predicate_native_tests.rs",
        required_patterns: &[
            "conditional_return_complete_predicates_execute_default_aot_conditions_once_and_selected_traps",
            "conditional_return_complete_predicates_execute_default_aot_real_zero_exits_and_checked_conditions",
            "tests::native::run",
            "Some(\"99\\n77\\n19\")",
            "Some(\"99\\n0\")",
            "\"division\"",
            "\"remainder\"",
            "run(&source, expected)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-complete-return-condition-previous-inline-source-now-compiles",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_inline_tests.rs",
        required_patterns: &[
            "let complete = base.replace(",
            "if divisor > 0 { return helper(produce(divisor)); } else { return false; }",
            "crate::pipeline::compile_source(&complete).unwrap()",
            "yir_lower_llvm::emit_module(&compiled.yir).unwrap()",
            "conditional_return_inline_comparisons_share_budgets_and_retain_non_total_vetoes",
            "if helper(produce(divisor)) == true",
            "if divisor / divisor == 0",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-complete-return-condition-documentation-boundary",
        path: "docs/reference/nuis-native-scalar-loop-snapshots-v1.md",
        required_patterns: &[
            "## Pure Computed Predicates In Complete Return Trees",
            "Nine compiler tests cover 490 runtime source cases and 980 reference executions",
            "Sixteen default-source AOT variants",
            "No exit-readiness expression or continuation seed is generated",
            "pure is not total",
            "Outer entry predicates remain atomic",
            "32 original statements",
            "not partial-tree computed-predicate authority",
            "1868/1868 passing drift checks",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-complete-return-condition-tensor-boundary-and-validation",
        path: "tools/nuis/src/dev_tensor_data.rs",
        required_patterns: &[
            "Complete-tree computed-predicate follow-up:",
            "Complete-tree computed-predicate acceptance:",
            "490 runtime source cases and 980 ordinary/reversed reference executions",
            "no condition replay or extra exit flag",
            "partial-tree computed/call-derived exit predicates remain unproven",
            "conditional_return_complete_predicates",
            "active/86 remains unchanged",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-inline-return-condition-shared-predicate-facts-and-registration",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns.rs",
        required_patterns: &[
            "#[path = \"conditional_returns_predicates.rs\"]",
            "mod predicates;",
            "if !entry::admitted(condition, scope, catalog, layouts)",
            "fallthrough::prepare(body, result, scope, catalog, layouts)",
            "if !has_return",
            "readiness: partial.then_some((yes_ready, no_ready))",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-inline-return-condition-partial-only-typed-grammar-and-preflight",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_terminal.rs",
        required_patterns: &[
            "if !bounded_tree(body, true)",
            "let admitted = control_values::value_type(condition, &inner, catalog, layouts)",
            "== Some(&scalar_type(\"bool\"))",
            "Partial trees separately prove replay or stored exit signals",
            "capture(condition, outer, inputs)",
            "inner.clone()",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-inline-return-condition-no-initializer-replay-before-selected-work",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_fallthrough.rs",
        required_patterns: &[
            "mod inline_tests;",
            "terminal::partial_inputs(body, result, scope, catalog, layouts)?",
            "let aliases = predicates::Values::from_parent(scope)",
            "aliases.bind(name, value)",
            "aliases.boolean(condition)?",
            "readiness(then_body, &aliases, leaves)?",
            "readiness(else_body, &aliases, leaves)?",
            "seed_fallthroughs(&mut body, result)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-inline-return-condition-runtime-exit-order-and-kind-proofs",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_inline_tests.rs",
        required_patterns: &[
            "conditional_return_inline_comparisons_keep_signed_operators_selected_work_and_exits",
            "assert_eq!(cases, 216)",
            "conditional_return_inline_comparisons_keep_bool_literals_and_current_atoms",
            "assert_eq!(cases, 192)",
            "conditional_return_inline_comparisons_keep_zero_results_extremes_and_parent_rebinding",
            "assert_eq!(cases, 50)",
            "conditional_return_inline_comparisons_keep_prefix_checks_early_exits_and_parent_suffixes",
            "assert_eq!(cases, 20)",
            "conditional_return_inline_comparisons_isolate_sibling_atoms_and_current_bool_versions",
            "assert_eq!(cases, 24)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-inline-return-condition-original-bodies-budget-and-rejection-proofs",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_inline_tests.rs",
        required_patterns: &[
            "conditional_return_inline_comparisons_retain_bodies_captures_hygiene_and_idempotence",
            "assert_seed_after_work(original, seeded)",
            "assert_eq!(module, once)",
            "conditional_return_inline_comparisons_share_budgets_and_retain_non_total_vetoes",
            "for count in [30, 31]",
            "if helper(produce(divisor)) == true",
            "if divisor / divisor == 0",
            "if (divisor > 0) == true",
            "let decision = divisor > 0; if decision == true",
            "if divisor > 0 { return helper(produce(divisor)); } else { return false; }",
            "assert_eq!(module, before",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-inline-return-condition-default-source-native-work-exits-and-traps",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_inline_native_tests.rs",
        required_patterns: &[
            "conditional_return_inline_comparisons_execute_default_aot_selected_work_and_traps",
            "conditional_return_inline_comparisons_execute_default_aot_zero_returns_and_continuation_checks",
            "tests::native::run",
            "Some(\"99\\n77\\n19\")",
            "Some(\"99\\n0\")",
            "Some(\"99\\n19\")",
            "run(&source, expected)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-inline-return-condition-documented-partial-only-boundary",
        path: "docs/reference/nuis-native-scalar-loop-snapshots-v1.md",
        required_patterns: &[
            "## Inline Total Comparisons In Partial Return Trees",
            "Nine compiler tests cover 502 runtime source cases and 1004 reference executions",
            "Fourteen default-source AOT variants",
            "This partial-tree proof does not grant complete-tree computed-predicate authority",
            "No initializer, call, arithmetic or check is replayed",
            "at most three normalized expression nodes",
            "Logical outer gates and other inline conditions",
            "not general inline-predicate authority",
            "1860/1860 passing drift checks",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-inline-return-condition-tensor-scope-and-validation",
        path: "tools/nuis/src/dev_tensor_data.rs",
        required_patterns: &[
            "Inline partial-tree comparison follow-up:",
            "Inline partial-tree comparison acceptance:",
            "502 runtime source cases and 1004 ordinary/reversed reference executions",
            "Complete all-return trees and outer entry predicates retain the old grammar",
            "conditional_return_inline_comparisons",
            "active/86 remains unchanged",
        ],
    },
];
