use crate::dev_tensor_drift::DevTensorDriftCheckSpec;

pub(crate) const DEV_TENSOR_CORE_DRIFT_CHECKS: &[DevTensorDriftCheckSpec] = &[
    DevTensorDriftCheckSpec {
        id: "language-control-flow-statement-syntax",
        path: "tools/nuisc/src/frontend/parser_statements.rs",
        required_patterns: &[
            "fn parse_loop_stmt",
            "fn parse_if_let_stmt_after_keyword",
            "condition: AstExpr::Bool(true)",
            "vec![self.parse_if_stmt()?]",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "language-control-flow-expression-syntax",
        path: "tools/nuisc/src/frontend/parser_exprs.rs",
        required_patterns: &[
            "fn parse_if_expr_after_keyword",
            "fn parse_if_let_expr_after_keyword",
            "AstStmt::Return(Some(self.parse_if_expr_after_keyword()?))",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "language-control-flow-syntax-regression",
        path: "tools/nuisc/src/frontend/tests_control_flow/surface_syntax.rs",
        required_patterns: &[
            "lowers_loop_syntax_into_existing_unbounded_while_form",
            "lowers_else_if_statement_into_nested_if_chain",
            "lowers_else_if_expression_into_nested_typed_binding_chain",
            "lowers_if_let_and_else_if_let_into_nested_match_dispatch",
            "lowers_if_let_expression_binding_into_typed_branch_target",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "language-control-flow-syntax-compile-regression",
        path: "tools/nuisc/tests/control_flow_syntax_compile.rs",
        required_patterns: &[
            "loop_and_else_if_syntax_cross_the_full_compile_pipeline",
            "guard_loop_continue",
            "guard_return",
            "node.op.module == \"deferred\"",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "language-loop-terminal-state-lowering",
        path: "tools/nuisc/src/lowering/loop_execution.rs",
        required_patterns: &[
            "PreparedLoopBody::Continue",
            "fn lower_mixed_prepared_loop_body",
            "lower_guard_loop_print_continue",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "language-loop-terminal-state-llvm",
        path: "crates/yir-lower-llvm/src/guard_return_lowering.rs",
        required_patterns: &[
            "guard_loop_continue_repeat",
            "guard_loop_print_continue_repeat",
            "guard_return_struct_then",
            "can_emit_owned_struct_return",
            "emit_owned_struct_return",
            "materialize_owned_variant_storage",
            "value contains a resource outside the owned aggregate ABI",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "language-guard-return-owned-layout",
        path: "tools/nuisc/src/lowering/guard_ops.rs",
        required_patterns: &[
            "function_owned_struct_layout",
            "owned_layout_is_variant_union",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "language-loop-terminal-state-native-regression",
        path: "tools/nuisc/tests/control_flow_syntax_native.rs",
        required_patterns: &[
            "mixed_loop_terminal_tree_runs_as_a_native_binary",
            "assert_eq!(status.code(), Some(10))",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "language-control-flow-syntax-reference",
        path: "docs/grammar/nuislang.bnf",
        required_patterns: &[
            "<loop_stmt>",
            "<if_condition>",
            "<if_expr>",
            "<continue_stmt>",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "frontdoor-final-output-boundary-status",
        path: "tools/nuis/src/surface_render/link_plan_nsld_tail.rs",
        required_patterns: &[
            "nsld_final_executable_output_boundary_status",
            "nsld_final_executable_output_materialization_status",
            "nsld_final_executable_output_execution_handoff_contract",
            "nsld_final_executable_output_execution_handoff_ready",
            "nsld_final_executable_output_execution_handoff_status",
            "nsld_final_executable_output_execution_handoff_target",
            "nsld_final_executable_output_execution_handoff_evidence_status",
            "nsld_final_executable_output_execution_handoff_first_blocker",
            "nsld_final_executable_output_execution_handoff_decision_code",
            "nsld_final_executable_output_recommended_next_action",
            "nsld_final_executable_output_ready",
            "nsld_final_executable_output_object_valid",
            "nsld_final_executable_output_object_expected_hash",
            "nsld_final_executable_output_object_actual_hash",
            "nsld_final_executable_output_object_issues",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-final-output-materialization-status",
        path: "tools/nsld/src/final_executable_output_handoff.rs",
        required_patterns: &[
            "final_executable_output_materialization_status",
            "final_executable_output_execution_handoff_contract",
            "final_executable_output_execution_handoff_ready",
            "final_executable_output_execution_handoff_status",
            "final_executable_output_execution_handoff_target",
            "final_executable_output_execution_handoff_evidence_status",
            "final_executable_output_execution_handoff_first_blocker",
            "final_executable_output_execution_handoff_decision_code",
            "final_executable_output_recommended_next_action",
            "final_executable_first_payload_execution",
            "first_payload_execution.ready",
            "handoff-to-container-loader",
            "handoff-container-loader-first-payload",
            "self-contained-image-ready",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-final-output-report-assembly",
        path: "tools/nsld/src/final_executable_output.rs",
        required_patterns: &[
            "final_executable_container_loader_evidence",
            "container_loader_handoff_ready",
            "container_loader_payload_scan_kind",
            "nsld_nustar_dispatch_blockers",
            "nustar-dispatch:",
            "backend_artifact_assembly_status",
            "first_payload_execution_status",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-final-output-materialization-regression",
        path: "tools/nsld/src/main_final_executable_output_tests.rs",
        required_patterns: &[
            "materialization_status",
            "execution_handoff_contract",
            "execution_handoff_ready",
            "execution_handoff_status",
            "execution_handoff_target",
            "execution_handoff_evidence_status",
            "execution_handoff_first_blocker",
            "execution_handoff_decision_code",
            "container_loader_status",
            "container_loader_handoff_ready",
            "container_loader_payload_scan_kind",
            "first_payload_execution_status",
            "first_payload_execution_ready",
            "first_payload_execution_target",
            "handoff-to-container-loader",
            "handoff-container-loader-first-payload",
            "recommended_next_action",
            "self-contained-image-ready",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-host-finalizer-gate-surface",
        path: "tools/nsld/src/json_final_executable.rs",
        required_patterns: &[
            "host_finalizer_gate_status",
            "host_finalizer_gate_action",
            "policy-blocked",
            "explicit-allow-missing",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-host-finalizer-gate-artifact",
        path: "tools/nsld/src/final_executable_render.rs",
        required_patterns: &[
            "host_finalizer_gate_status",
            "host_finalizer_gate_action",
            "set-env:NUIS_NSLD_HOST_FINALIZER_POLICY=allow-host-invoke",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-host-finalizer-gate-regression",
        path: "tools/nsld/src/main_final_executable_emit_tests.rs",
        required_patterns: &[
            "host_finalizer_gate_status",
            "policy-blocked",
            "set-env:NUIS_NSLD_HOST_FINALIZER_POLICY=allow-host-invoke",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-check-host-finalizer-gate-surface",
        path: "tools/nsld/src/json_check_final.rs",
        required_patterns: &[
            "final_executable_host_finalizer_gate_status",
            "final_executable_host_finalizer_gate_action",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-executable-finalizer-registry-contract",
        path: "tools/nsld/src/final_executable_finalizer_registry.rs",
        required_patterns: &[
            "nuis-nsld-executable-finalizer-registry-v1",
            "nsld.finalizer.elf.amd64.artifact-image-v1",
            "nsld.finalizer.mach-o.arm64.artifact-image-v1",
            "nsld.finalizer.mach-o.arm64.host-command-shell-v1",
            "nsld.finalizer.elf.registered-v1",
            "nsld.finalizer.pe-coff.registered-v1",
            "registered-not-implemented",
            "invoke_registered_finalizer",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-elf-amd64-artifact-image-finalizer",
        path: "tools/nsld/src/final_executable_elf_artifact.rs",
        required_patterns: &[
            "compiled-artifact-native-handoff",
            "build_elf_amd64_host_object_linkage",
            "ET_EXEC or ET_DYN",
            "PT_LOAD",
            "ELF_AMD64_CPU_ABI",
            "atomic_write_executable",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-elf-amd64-object-input-parser",
        path: "tools/nsld/src/final_executable_elf_input.rs",
        required_patterns: &[
            "ParsedElfObjectLinkage",
            "parse_elf64_amd64_object_linkage",
            "explicit-addend SHT_RELA",
            "R_X86_64_PLT32",
            "unsupported R_X86_64 type",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-elf-amd64-host-object-linkage",
        path: "tools/nsld/src/final_executable_elf_object.rs",
        required_patterns: &[
            "nuis-nsld-elf-amd64-host-object-linkage-v1",
            "program-llvm",
            "runtime-shim",
            "strong symbol",
            "internally_resolved_symbols",
            "hash mismatch",
            "apply_elf_amd64_platform_structure_plan",
            "platform_patch_application",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-elf-amd64-placement-binding-contract",
        path: "tools/nsld/src/final_executable_elf_layout.rs",
        required_patterns: &[
            "nuis-nsld-elf-amd64-placement-binding-v1",
            "ELF_AMD64_PAYLOAD_FILE_OFFSET",
            "ELF_AMD64_PAGE_SIZE",
            "SectionClass::Text",
            ".bss.nuis_common",
            "coalesced-to-definition",
            "weak-zero",
            "external-compatibility",
            "plan_hash",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-elf-amd64-placement-binding-regression",
        path: "tools/nsld/src/final_executable_elf_layout_tests.rs",
        required_patterns: &[
            "places_real_host_objects_and_binds_cross_object_reference",
            "places_all_runtime_classes_and_binds_common_and_absolute_symbols",
            "placement_plan_is_independent_of_input_object_order",
            "preserves_unresolved_system_symbols_as_an_explicit_compatibility_boundary",
            "resolves_an_unmatched_weak_reference_to_zero",
            "rejects_tls_until_the_runtime_has_a_tls_placement_contract",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-elf-amd64-relocation-application-contract",
        path: "tools/nsld/src/final_executable_elf_relocation.rs",
        required_patterns: &[
            "nuis-nsld-elf-amd64-relocation-application-v1",
            "R_X86_64_PC32",
            "R_X86_64_PLT32",
            "planned-platform-structure",
            "relocation_value",
            "encode_signed32",
            "placement hash mismatch",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-elf-amd64-relocation-application-regression",
        path: "tools/nsld/src/final_executable_elf_relocation_tests.rs",
        required_patterns: &[
            "previews_real_cross_object_plt32_call",
            "registered_shapes_produce_checked_little_endian_previews",
            "unresolved_system_target_remains_a_platform_structure_boundary",
            "rejects_unsigned_and_signed_32_bit_overflow",
            "rejects_pc_relative_displacement_outside_i32",
            "placement_hash_drift_fails_before_relocation_planning",
            "relocation_plan_is_independent_of_input_object_order",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-elf-amd64-materialization-preview-contract",
        path: "tools/nsld/src/final_executable_elf_materialization.rs",
        required_patterns: &[
            "nuis-nsld-elf-amd64-materialization-preview-v1",
            "build_elf_amd64_merged_image",
            "verified-plan-bound",
            "verified-zero-fill",
            "write-once-preview",
            "source hash drift",
            "overlaps an earlier span",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-elf-amd64-materialization-preview-regression",
        path: "tools/nsld/src/final_executable_elf_materialization_tests.rs",
        required_patterns: &[
            "materializes_real_sections_and_previews_plt32_without_mutation",
            "unresolved_system_target_remains_deferred_after_materialization",
            "materialization_is_independent_of_image_object_input_order",
            "source_hash_and_parsed_linkage_drift_fail_before_copy",
            "plan_hash_drift_and_overlapping_direct_patches_fail_closed",
            "merged_zero_fill_sections_are_audited_separately",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-elf-amd64-patch-application-contract",
        path: "tools/nsld/src/final_executable_elf_application.rs",
        required_patterns: &[
            "nuis-nsld-elf-amd64-patch-application-v1",
            "materialization preview drift",
            "direct-patches-applied",
            "applied-write-once",
            "application_ledger_hash",
            "apply_write_once",
            "source image drift",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-elf-amd64-patch-application-regression",
        path: "tools/nsld/src/final_executable_elf_application_tests.rs",
        required_patterns: &[
            "applies_real_plt32_patch_once_and_emits_a_bound_ledger",
            "unresolved_system_target_stays_deferred_and_preserves_the_image",
            "application_is_independent_of_image_object_input_order",
            "source_and_preview_drift_fail_before_any_write",
            "write_once_primitive_rejects_overlap_and_source_drift",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-elf-amd64-platform-structure-plan-contract",
        path: "tools/nsld/src/final_executable_elf_platform.rs",
        required_patterns: &[
            "nuis-nsld-elf-amd64-platform-structure-plan-v1",
            "PLATFORM_RULES",
            "x86_64.external-plt32.nonlazy.v1",
            "r-x86-64-jump-slot",
            "dynamic_symbol_slots",
            "build_relocation_binding",
            "allocated-ready-for-platform-patching",
            "validate_registry",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-elf-amd64-platform-structure-plan-regression",
        path: "tools/nsld/src/final_executable_elf_platform_tests.rs",
        required_patterns: &[
            "plans_real_external_plt_got_and_rela_without_mutating_the_applied_ledger",
            "repeated_external_calls_share_one_target_but_keep_distinct_bindings",
            "internally_closed_image_does_not_gain_platform_regions",
            "unregistered_external_shape_and_ledger_drift_fail_closed",
            "overlapping_deferred_sources_are_rejected_before_slot_assignment",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-elf-amd64-platform-patch-application-contract",
        path: "tools/nsld/src/final_executable_elf_platform_application.rs",
        required_patterns: &[
            "nuis-nsld-elf-amd64-platform-patch-application-v1",
            "PLATFORM_ENCODERS",
            "reserve_direct_patch_spans",
            "write_dynamic_relocations",
            "apply_deferred_bindings",
            "platform-structures-and-deferred-patches-applied-with-unresolved-dynamic-binds",
            "application_ledger_hash",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-elf-amd64-platform-patch-application-regression",
        path: "tools/nsld/src/final_executable_elf_platform_application_tests.rs",
        required_patterns: &[
            "emits_real_plt_got_dynamic_records_and_deferred_patch_bytes",
            "repeated_calls_share_structures_but_each_source_is_patched_once",
            "closed_image_is_preserved_without_platform_writes",
            "base_image_and_plan_drift_fail_before_platform_publication",
            "platform_write_once_primitive_rejects_overlap_and_source_drift",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-elf-amd64-artifact-image-regression",
        path: "tools/nsld/src/final_executable_elf_artifact_tests.rs",
        required_patterns: &[
            "nsld.finalizer.elf.amd64.artifact-image-v1",
            "select_executable_finalizer",
            "invoke_registered_finalizer",
            "ELF_TYPE_SHARED",
            "unsupported calling ABI",
            "CPU ABI mismatch",
            "hash mismatch",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-macho-artifact-image-finalizer",
        path: "tools/nsld/src/final_executable_macho_artifact.rs",
        required_patterns: &[
            "compiled-artifact-native-handoff",
            "validate_macho_host_object_handoff",
            "MH_EXECUTE",
            "validate_fat_macho_arm64_executable",
            "atomic_write_executable",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-macho-relocatable-object-handoff",
        path: "tools/nsld/src/final_executable_macho_object.rs",
        required_patterns: &[
            "program-llvm",
            "runtime-shim",
            "nuis-nsld-macho-host-object-linkage-v1",
            "parse_macho_arm64_object_linkage",
            "identity drift",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-macho-object-table-parser",
        path: "tools/nsld/src/final_executable_macho_input.rs",
        required_patterns: &[
            "MH_OBJECT",
            "LC_SEGMENT_64",
            "LC_SYMTAB",
            "NLIST_64_SIZE",
            "ARM64_RELOCATION_ADDEND",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiled-artifact-host-object-bundle",
        path: "crates/nuis-artifact/src/artifact/host_objects.rs",
        required_patterns: &[
            "NHOB",
            "HOST_OBJECT_BUNDLE_VERSION",
            "host object bundle contains duplicate id",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiled-artifact-verifier-temp-isolation",
        path: "tools/nuisc/src/aot_compiled_artifact_verify.rs",
        required_patterns: &[
            "VERIFY_TEMP_SEQUENCE",
            "std::process::id()",
            "fs::create_dir(&temp_root)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-executable-finalizer-invoke-plan-projection",
        path: "tools/nsld/src/final_executable_writer.rs",
        required_patterns: &[
            "finalizer_contract",
            "finalizer_registry_hash",
            "finalizer_target_key",
            "finalizer_provider_id",
            "finalizer_provider_status",
            "finalizer_execution_kind",
            "finalizer_input_summary",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-nsb-relocation-application-layout",
        path: "tools/nsld/src/final_executable_layout_stage.rs",
        required_patterns: &[
            "relocation_application_strategy",
            "nsb-loader-relocation-table",
            "relocation_application_table_hash",
            "relocation_applications",
            "payload0001.container-payload",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-nsb-relocation-application-image-report",
        path: "tools/nsld/src/final_executable_image_stage.rs",
        required_patterns: &[
            "relocation_application_strategy",
            "relocation_application_count",
            "relocation_application_table_hash",
            "relocation_application_audit_status",
            "relocation_application_audit_blockers",
            "relocation_patch_preview_status",
            "relocation_patch_preview_table_hash",
            "relocation_patch_application_status",
            "relocation_patch_application_table_hash",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-nsb-relocation-application-image-verify",
        path: "tools/nsld/src/final_executable_image_verify.rs",
        required_patterns: &[
            "relocation_patch_preview_record_table_hash",
            "relocation_patch_byte_audit_status",
            "relocation_patch_byte_audit_hash",
            "parse_final_executable_image_header",
            "verify_final_executable_image_payload_region",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-nsb-relocation-application-image-resolver",
        path: "tools/nsld/src/final_executable_image_relocation.rs",
        required_patterns: &[
            "resolved_patch_value",
            "target_symbol_image_offset",
            "resolver_status",
            "u64-le-resolved-image-offset",
            "apply_relocation_patches",
            "relocation_patch_byte_audit",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-nsb-relocation-application-image-actual",
        path: "tools/nsld/src/final_executable_image_actual.rs",
        required_patterns: &[
            "relocation_patch_preview_records_from_source",
            "relocation_patch_preview_record_table_hash",
            "resolved_patch_value",
            "target_symbol_image_offset",
            "resolver_status",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-nsb-relocation-final-emit-surface",
        path: "tools/nsld/src/final_executable_emit_shape.rs",
        required_patterns: &[
            "image_dry_run_resolver_status",
            "image_dry_run_patch_application_status",
            "image_dry_run_patch_byte_audit_status",
            "image_dry_run_patch_byte_audit_hash",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-nsb-relocation-final-output-surface",
        path: "tools/nsld/src/final_executable_output.rs",
        required_patterns: &[
            "expected_image_resolver_status",
            "expected_image_patch_application_status",
            "expected_image_patch_byte_audit_status",
            "matches_verified_patched_image",
            "object_output_valid",
            "object_output_expected_hash",
            "object_output_actual_hash",
            "object_output_issues",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-nsb-relocation-final-output-check-surface",
        path: "tools/nsld/src/check_final.rs",
        required_patterns: &[
            "final_executable_output_expected_image_resolver_status",
            "final_executable_output_expected_image_patch_application_status",
            "final_executable_output_expected_image_patch_byte_audit_status",
            "final_executable_output_matches_verified_patched_image",
            "final_executable_output_object_valid",
            "final_executable_output_object_expected_hash",
            "final_executable_output_object_actual_hash",
            "final_executable_output_object_issues",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-nsb-relocation-final-output-check-json",
        path: "tools/nsld/src/json_check_final.rs",
        required_patterns: &[
            "final_executable_output_expected_image_resolver_status",
            "final_executable_output_expected_image_patch_application_status",
            "final_executable_output_expected_image_patch_byte_audit_status",
            "final_executable_output_matches_verified_patched_image",
            "final_executable_output_object_valid",
            "final_executable_output_object_expected_hash",
            "final_executable_output_object_actual_hash",
            "final_executable_output_object_issues",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-nsb-relocation-application-regression",
        path: "tools/nsld/src/main_final_executable_layout_tests.rs",
        required_patterns: &[
            "relocation_application_strategy",
            "relocation_application_count",
            "relocation_application_table_hash",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-check-next-action-final-output-boundary",
        path: "tools/nsld/src/check.rs",
        required_patterns: &[
            "artifact_chain_final_output_boundary_ready",
            "final-output-boundary",
            "artifact_chain_final_output_boundary_command_resolved",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-check-next-action-final-output-boundary-regression",
        path: "tools/nsld/src/drive_tests.rs",
        required_patterns: &[
            "drive_until_clean_command_reaches_host_assisted_pipeline_block",
            "final-output-boundary",
            "final-executable-output",
            "blocked-boundary",
            "read-only-boundary:final-executable-output",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-driver-final-output-boundary-doc",
        path: "docs/reference/nsld-driver-frontdoor.md",
        required_patterns: &[
            "final-output-boundary",
            "blocked-boundary",
            "nsld final-executable-output <input>",
            "Host-assisted final executable emission",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "frontdoor-self-owned-image-status",
        path: "tools/nuis/src/surface_render/link_plan_nsld_tail.rs",
        required_patterns: &[
            "nsld_self_owned_image_status",
            "nsld_entrypoint_materialization_status",
            "nsld_self_owned_image_header_valid",
            "nsld_final_executable_pipeline_execution_handoff_contract",
            "nsld_final_executable_pipeline_execution_handoff_ready",
            "nsld_final_executable_pipeline_execution_handoff_status",
            "nsld_final_executable_pipeline_execution_handoff_target",
            "nsld_final_executable_pipeline_execution_handoff_evidence_status",
            "nsld_final_executable_pipeline_execution_handoff_first_blocker",
            "nsld_final_executable_pipeline_execution_handoff_decision_code",
            "nsld_final_executable_pipeline_entrypoint_materialization_kind",
            "nsld_final_executable_pipeline_entrypoint_materialization_path",
            "nsld_final_executable_pipeline_entrypoint_materialization_ready",
            "nsld_final_executable_pipeline_entrypoint_materialization_first_blocker",
            "nsld_final_executable_pipeline_entrypoint_materialization_present",
            "nsld_final_executable_pipeline_entrypoint_materialization_hash",
            "nsld_final_executable_pipeline_entrypoint_materialization_runner_command",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-pipeline-orchestrator-split-surface",
        path: "tools/nsld/src/final_executable_pipeline.rs",
        required_patterns: &[
            "nsld_pipeline_self_owned_image_status",
            "nsld_pipeline_entrypoint_materialization_status",
            "final_executable_pipeline_required_stage_paths",
            "render_final_executable_pipeline",
            "push_optional_string_mismatch",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-pipeline-self-owned-image-status",
        path: "tools/nsld/src/final_executable_pipeline_status.rs",
        required_patterns: &[
            "nsld_pipeline_self_owned_image_status",
            "launcher_manifest_ready",
            "image_header_valid",
            "path-missing",
            "header-invalid",
            "hash-missing",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-pipeline-entrypoint-materialization",
        path: "tools/nsld/src/final_executable_pipeline_entrypoint.rs",
        required_patterns: &[
            "nsld_pipeline_entrypoint_materialization_status",
            "nsld_pipeline_entrypoint_materialization_plan",
            "nsld_write_host_entrypoint_script",
            "entrypoint_materialization_evidence",
            "render_host_entrypoint_runner_command",
            "host-launcher-ready",
            "image-ready-entrypoint-pending",
            "entrypoint-materializer",
            "host-shell-entrypoint-plan",
            "nuis-nsld-host-entrypoint-v1",
            "NUIS_HOST_ENTRYPOINT_STUB_PROTOCOL",
            "nuis.host-entrypoint.sh",
            "NUIS_HOST_RUNNER",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-pipeline-render-contract",
        path: "tools/nsld/src/final_executable_pipeline_render.rs",
        required_patterns: &[
            "nuis-nsld-final-executable-pipeline-v1",
            "entrypoint_materialization_status",
            "entrypoint_materialization_runner_command",
            "execution_handoff_contract",
            "execution_handoff_decision_code",
            "scheduler_metadata_payload_id",
            "required_stage_path_count",
            "missing_required_stage_paths",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-pipeline-required-paths",
        path: "tools/nsld/src/final_executable_pipeline_paths.rs",
        required_patterns: &[
            "NsldFinalExecutablePipelineRequiredPaths",
            "final_executable_pipeline_required_stage_paths",
            "entrypoint_materialization_path",
            "final_executable_emitted",
            "missing_paths",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-pipeline-mismatch-helpers",
        path: "tools/nsld/src/final_executable_pipeline_mismatch.rs",
        required_patterns: &[
            "optional_bool_text",
            "push_usize_mismatch",
            "push_bool_mismatch",
            "push_optional_string_mismatch",
            "expected",
            "found",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-check-pipeline-handoff-status",
        path: "tools/nsld/src/reports_check.rs",
        required_patterns: &[
            "final_executable_pipeline_execution_handoff_contract",
            "final_executable_pipeline_execution_handoff_ready",
            "final_executable_pipeline_execution_handoff_status",
            "final_executable_pipeline_execution_handoff_target",
            "final_executable_pipeline_execution_handoff_evidence_status",
            "final_executable_pipeline_execution_handoff_first_blocker",
            "final_executable_pipeline_execution_handoff_decision_code",
            "final_executable_pipeline_entrypoint_materialization_kind",
            "final_executable_pipeline_entrypoint_materialization_path",
            "final_executable_pipeline_entrypoint_materialization_ready",
            "final_executable_pipeline_entrypoint_materialization_first_blocker",
            "final_executable_pipeline_entrypoint_materialization_present",
            "final_executable_pipeline_entrypoint_materialization_hash",
            "final_executable_pipeline_entrypoint_materialization_runner_command",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-pipeline-self-owned-image-regression",
        path: "tools/nsld/src/main_final_executable_pipeline_tests.rs",
        required_patterns: &[
            "actual_self_owned_image_status",
            "actual_entrypoint_materialization_status",
            "actual_entrypoint_materialization_kind",
            "actual_entrypoint_materialization_ready",
            "actual_entrypoint_materialization_first_blocker",
            "actual_entrypoint_materialization_present",
            "actual_entrypoint_materialization_hash",
            "actual_entrypoint_materialization_runner_command",
            "actual_execution_handoff_contract",
            "actual_execution_handoff_ready",
            "actual_execution_handoff_status",
            "actual_execution_handoff_target",
            "actual_execution_handoff_evidence_status",
            "actual_execution_handoff_first_blocker",
            "actual_execution_handoff_decision_code",
            "self_owned_image_status",
            "entrypoint_materialization_status",
            "host-shell-entrypoint-plan",
            "NUIS_HOST_RUNNER",
            "nuis-host-runner --manifest",
            "required_stage_path_count, 10",
            "verify_final_executable_pipeline_reports_missing_entrypoint_materialization",
            "verify_final_executable_pipeline_reports_tampered_entrypoint_materialization",
            "entrypoint_materialization_hash mismatch",
            "nsld-final-output-handoff-v1",
            "handoff-container-loader-first-payload",
            "Some(\"ready\")",
            "Some(\"host-launcher-ready\")",
        ],
    },
];
