use crate::dev_tensor_drift::DevTensorDriftCheckSpec;

pub(super) const CHECKS: &[DevTensorDriftCheckSpec] = &[
    DevTensorDriftCheckSpec {
        id: "native-return-parent-entry-per-field-summary",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/control_loops/return_invariant_parent_entries.rs",
        required_patterns: &[
            "pub(in super::super) fn parent_entries(",
            "proof.loop_summary(&NirExpr::Bool(true), body, &mut env, depth)?",
            "proof.shape(&value.ty)?.leaves.len() != value.words.len()",
            "*next = next.checked_add(1)?",
            "origin.clone().or(Some(Origin::Snapshot(version, index)))",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-parent-entry-conservative-fallback",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/control_loops/return_invariants.rs",
        required_patterns: &[
            "self.nested && contains_loop(body)",
            "snapshots.parent_entries(",
            "entries.forget_writes(",
            "const MAX_WORK: usize = 65_536",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-parent-entry-negative-fixed-points",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/control_loops/return_invariant_parent_entries_tests.rs",
        required_patterns: &[
            "return_invariant_parent_entries_keep_only_per_write_stable_fields",
            "return_invariant_parent_entries_include_later_trips_and_intermediate_exits",
            "return_invariant_parent_entries_do_not_share_varying_fields_or_export_locals",
            "return_invariant_parent_entries_reject_exhaustion_and_preserve_the_input",
            "assert!(snapshots.env == before)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-parent-entry-native-boundary-proof",
        path: "tools/nuisc/tests/native_application_bridge/sparse_typed_return_carries.rs",
        required_patterns: &[
            "typed_sparse_nested_returns_preserve_parent_entry_fields_and_reject_first_trip_aliases",
            "fixture::parent_return_source(width)",
            "width - if changed_tag { 2 } else { 4 }",
            "if changed_tag && limit == 1",
            "typed_record_inputs::check_flattened(&source, cases)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-parent-entry-private-arity-proof",
        path: "tools/nuisc/tests/native_application_bridge/sparse_typed_return_child_exits.rs",
        required_patterns: &[
            "typed_nested_preheader_snapshots_keep_explicit_private_iteration_arities",
            "fixture::return_source(9), vec![9, 12]",
            "fixture::parent_return_source(64)",
            "vec![7, 12]",
            "assert_eq!(actual, expected)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-parent-entry-source-free-restoration",
        path: "tools/nuis/tests/native_session_workflow/sparse_typed_records.rs",
        required_patterns: &[
            "native_parent_entries_restore_full_width_invariants_without_source",
            "&fixture::parent_return_source(64)",
            "&[7, 12]",
            "fs::remove_file(project.0.join(\"main.ns\"))",
            "assert_eq!(fs::read_to_string(restored.join(&llvm_name)).unwrap(), llvm)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-preheader-branch-pair-join",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/control_loops/return_invariant_snapshots.rs",
        required_patterns: &[
            "pub(in super::super) fn join(",
            "for (name, entry) in &self.env",
            "(Some(left), Some(right)) if left == right",
            ".entry((left.clone(), right.clone()))",
            "self.env = joined",
            "budget.charge(entry.words.len())?",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-preheader-branch-pair-negative-proofs",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/control_loops/return_invariant_snapshots_tests.rs",
        required_patterns: &[
            "return_invariant_snapshot_joins_keep_correlated_arm_values_and_nested_aliases",
            "return_invariant_snapshot_joins_do_not_equate_swapped_arms_or_separate_calls",
            "return_invariant_snapshot_joins_are_atomic_typed_scoped_and_budgeted",
            "return_invariant_snapshot_joins_never_share_unknown_leaves",
            "assert!(snapshots.env == before)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-preheader-branch-transactional-differential-proof",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/control_loops/return_invariant_joins_tests.rs",
        required_patterns: &[
            "return_invariant_joins_revalidate_correlated_arms_and_match_independent_payloads",
            "tests::promoted(&source)",
            "nested_tests::execute(&independent)",
            "cases::expected(case, choose, limit).ok_or(())",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-preheader-branch-native-boundary-proof",
        path: "tools/nuisc/tests/native_application_bridge/sparse_typed_return_carries.rs",
        required_patterns: &[
            "typed_sparse_nested_returns_execute_joined_preheader_snapshots_at_full_width",
            "fixture::joined_return_source(width)",
            "typed_sparse_nested_return_joins_reject_one_changed_arm_before_native_emission",
            "65 carried words exceed the 64-word native limit",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-preheader-branch-ordinary-native-proof",
        path: "tools/nuisc/tests/control_flow_syntax_native/scoped_field_seeds.rs",
        required_patterns: &[
            "scoped_return_joins_execute_correlated_arms_old_versions_and_selected_checks",
            "join_cases::source(case, choose, limit)",
            "join_cases::expected(case, choose, limit)",
            "selected preheader check must still trap",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-preheader-branch-source-free-restoration",
        path: "tools/nuis/tests/native_session_workflow/sparse_typed_records.rs",
        required_patterns: &[
            "native_joined_preheaders_restore_full_width_snapshots_without_source",
            "&fixture::joined_return_source(64)",
            "&[5, 11]",
            "fs::remove_file(project.0.join(\"main.ns\"))",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-preheader-snapshot-fixed-point",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/control_loops/return_invariant_facts.rs",
        required_patterns: &[
            "Snapshot(usize, usize)",
            "proof.entries = env.clone()",
            "proof.loop_summary(&NirExpr::Bool(true), body, &mut env, 0)?",
            "entry.words[index].is_some()",
            "value.words[index] == entry.words[index]",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-preheader-snapshot-versions",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/control_loops/return_invariant_snapshots.rs",
        required_patterns: &[
            "*next = next.checked_add(1)?",
            "Origin::Snapshot(version, index)",
            "budget.tick(depth)?",
            "Self::writes(then_body, writes, budget, depth + 1)?",
            "Self::writes(body, writes, budget, depth + 1)?",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-preheader-snapshot-negative-proofs",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/control_loops/return_invariant_snapshots_tests.rs",
        required_patterns: &[
            "return_invariant_snapshots_prove_cross_binding_field_and_computed_snapshots",
            "return_invariant_snapshots_keep_old_versions_after_rebinding",
            "return_invariant_snapshots_invalidate_preheader_branch_and_loop_writes",
            "return_invariant_snapshots_check_later_trips_and_restored_intermediate_writes",
            "return_invariant_snapshots_reject_qualifiers_and_exhausted_mutation_scans",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-preheader-snapshot-transactional-revalidation",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/control_loops/return_invariant_child_tests.rs",
        required_patterns: &[
            "return_invariants_revalidate_full_width_preheader_snapshots_with_changed_tags",
            "tests::promoted(&source)",
            "assert_eq!(widths, [width - 4, width])",
            "return_invariants_do_not_treat_delayed_entry_aliases_as_loop_invariants",
            "nested_tests::execute(&independent)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-preheader-snapshot-changed-tag-execution",
        path: "tools/nuisc/tests/native_application_bridge/sparse_typed_return_carries.rs",
        required_patterns: &[
            "typed_sparse_nested_returns_execute_changed_outer_tags_with_preheader_snapshots",
            "assert_eq!(carried_widths(&compiled.yir), [width - 4, width])",
            "event[2] = 17",
            ".replace(\"count: limit\", \"count: limit + 1\")",
            "including private return/control state",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-preheader-snapshot-parent-trip-execution",
        path: "tools/nuisc/tests/control_flow_syntax_native/scoped_field_seeds.rs",
        required_patterns: &[
            "scoped_return_preheaders_preserve_old_versions_and_later_parent_trips",
            "let carry = delayed; let delayed = other;",
            "let carry = relay(seed); let tag = carry.tag; let carry = relay(carry);",
            "compile_and_run(&format!(\"parent_snapshot_{limit}\"), &parent)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-preheader-snapshot-source-free-restoration",
        path: "tools/nuis/tests/native_session_workflow/sparse_typed_records.rs",
        required_patterns: &[
            "native_changed_outer_tags_restore_preheader_snapshots_without_source",
            "changed_outer_tag && phase != \"open\" && limit > 0",
            "fs::remove_file(project.0.join(\"main.ns\"))",
            "assert_eq!(fs::read_to_string(restored.join(&llvm_name)).unwrap(), llvm)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-readonly-scoped-record-all-caller-proof",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_scoped.rs",
        required_patterns: &[
            "let transport = (seeds.is_some() || readonly)",
            "!written.contains(&path[0])",
            "inputs.transport.retain(|index| transport.contains(index))",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-readonly-scoped-record-negative-callers",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_scoped_tests.rs",
        required_patterns: &[
            "scoped_readonly_record_transport_requires_every_caller_and_does_not_grant_seed_authority",
            "inputs[\"helper\"].transport.contains(&0), readonly",
            "!inputs[\"helper\"].elidable.contains_key(&0)",
            "module.functions.reverse()",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-readonly-scoped-record-mixed-contract",
        path: "crates/yir-core/src/loop_carry_contract/scoped_record_tests.rs",
        required_patterns: &[
            "scoped_record_mixed_captures_keep_kinds_and_only_i64_state_mappings",
            "\"bool\", \"i32\", \"f32\", \"f64\"",
            "\"$current\", \"$owned_struct_carry:0:first\"",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-readonly-scoped-record-reference-bits",
        path: "crates/yir-domain-cpu/src/execute_scoped_loop/record_inputs.rs",
        required_patterns: &[
            "scoped_record_mixed_captures_snapshot_exact_bits_and_dynamic_i64_slots",
            "scoped_record_capture_rejects_wrong_kinds_without_scalar_coercions",
            "state.values.clear()",
            "0x7ff8_0000_0000_4321",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-opaque-child-snapshot-evaluation-and-bounds",
        path: "tools/nuisc/tests/native_application_bridge/sparse_typed_return_child_exits.rs",
        required_patterns: &[
            "typed_nested_child_breaks_preserve_opaque_snapshot_calls_with_readonly_record_inputs",
            "snapshot.count - carry.count",
            "typed_nested_opaque_child_snapshots_preserve_traps_and_entry_reservations",
            "remaining: [59, 52]",
            "entries: 11",
            "typed_nested_opaque_continue_snapshots_preserve_readonly_inputs",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-opaque-child-snapshot-source-free-restoration",
        path: "tools/nuis/tests/native_session_workflow/sparse_typed_records.rs",
        required_patterns: &[
            "native_opaque_child_snapshots_restore_readonly_record_inputs_without_source",
            "&[6, 6, 11]",
            "let snapshot = relay(carry)",
            "assert_eq!(fs::read_to_string(restored.join(&llvm_name)).unwrap(), llvm)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-ordinary-child-invariant-admission",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/control_loops/return_invariants.rs",
        required_patterns: &[
            "let records = if self.nested",
            "exits::return_owned(iteration.effects, self.signal)",
            "the legacy fallback remains innermost-return-only",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-ordinary-child-invariant-differential-regressions",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/control_loops/return_invariant_child_tests.rs",
        required_patterns: &[
            "return_invariants_preserve_ordinary_child_mutations_snapshots_and_exit_indices",
            "tests::promoted(&source)",
            "assert_eq!(actual, nested_tests::execute(&independent)",
            "assert_eq!(actual, expected",
            "carry.tag + j * 100",
            "value: carry.value + old.value",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-dead-record-ready-input-proof",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_dead_records.rs",
        required_patterns: &[
            "candidates(function, layouts, 65_536)",
            "!writes.contains_key(p.name.as_str())",
            "writes[name.as_str()] != 1",
            "declared.is_none_or(|declared| declared == &ty)",
            "depth >= 64",
            "expected.remove(name)?",
            "(remaining > 0).then_some(dead)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-dead-record-ready-input-negative-regressions",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_dead_records_tests.rs",
        required_patterns: &[
            "dead_record_snapshots_drop_only_unobserved_ready_reconstructions",
            "dead_record_snapshots_preserve_live_writes_shadowed_names_and_local_sources",
            "dead_record_snapshots_preserve_calls_checked_fields_and_codecs",
            "dead_record_snapshots_require_exact_nominal_field_and_binding_types",
            "dead_record_snapshots_do_not_treat_resources_or_borrows_as_ready_values",
            "dead_record_snapshots_keep_all_callers_transactional",
            "dead_record_snapshots_bound_proof_work_without_partial_removal",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-dead-record-projection-integration",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_projection.rs",
        required_patterns: &[
            "let mut candidate = module.functions[index].clone()",
            "record_views::normalize(&mut candidate, layouts)",
            "dead_records::normalize(&mut candidate, layouts)",
            "valid_caller(&module.functions[*i].body, &name, &plan)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-total-record-view-projection-proof",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_record_views.rs",
        required_patterns: &[
            "normalized(function, layouts, 65_536)",
            "if depth >= 64",
            "!writes.contains_key(p.name.as_str())",
            "self.writes.get(name) != Some(&1) || self.parameters.contains(name)",
            "dead_records::ready_type(",
            "(context.remaining > 0).then_some(result)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-total-record-view-projection-negative-regressions",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_record_views_tests.rs",
        required_patterns: &[
            "record_views_project_leaf_subrecord_and_alias_chains_without_erasing_checked_work",
            "record_views_do_not_project_computed_checked_or_codec_constructors",
            "record_views_keep_whole_escapes_and_mutated_or_shadowed_sources",
            "record_views_require_exact_nominal_fields_binding_types_and_value_inputs",
            "record_views_keep_all_callers_transactional",
            "record_views_bound_work_and_depth_without_partial_rewrites",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-total-record-view-mixed-types-and-reference-parity",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_record_views_tests.rs",
        required_patterns: &[
            "record_views_project_mixed_leaf_types_instead_of_word_codecs",
            "record_views_preserve_reference_results_and_selected_failures",
            "assert_eq!(execute(&module), before)",
            "yir.nodes.reverse()",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-partial-child-snapshot-execution-boundaries",
        path: "tools/nuisc/tests/native_application_bridge/sparse_typed_return_child_exits.rs",
        required_patterns: &[
            "typed_nested_child_exits_project_partly_observed_reconstructions",
            "typed_nested_checked_child_snapshots_preserve_evaluated_constructors",
            "typed_nested_child_exit_snapshot_traps_preserve_atomic_callback_publication",
            "snapshot.count - snapshot.count",
            "remaining: [59, 53]",
            "typed_nested_child_exits_do_not_infer_invariance_through_opaque_calls",
            "carried words exceed the 64-word native limit",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-checked-child-bounded-layout-cache",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/control_loops/return_invariant_facts.rs",
        required_patterns: &[
            "BTreeMap<String, Rc<RecordShape>>",
            "if shape.tree.ty != *ty",
            "if base.words.len() != shape.leaves.len()",
            "self.budget.charge(range.len())?",
            "base.words.get(range.clone())?.to_vec()",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-checked-child-layout-cache-regressions",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/control_loops/return_invariant_facts_tests.rs",
        required_patterns: &[
            "return_invariant_field_ranges_bound_wide_reads_without_caching_origins",
            "Budget(4096)",
            "return_invariant_cached_shapes_keep_nominal_qualifier_checks",
            "proof.shape(&reference).is_none()",
            "proof.shape(&optional).is_none()",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-checked-child-full-width-revalidation",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/control_loops/return_invariant_child_tests.rs",
        required_patterns: &[
            "return_invariants_promote_child_checked_record_snapshots_at_full_width",
            "10 / (carry.count - carry.count)",
            "tests::promoted(&source)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-checked-child-evaluation-order",
        path: "tools/nuisc/tests/native_application_bridge/sparse_typed_return_child_exits.rs",
        required_patterns: &[
            "typed_nested_checked_child_snapshots_preserve_unused_traps_and_field_order",
            "remaining: [59, if call_first { 52 } else { 53 }]",
            "typed_nested_checked_continue_snapshots_preserve_selected_trip",
            "remaining: [59, if late { 48 } else { 53 }]",
            "snapshot.count - carry.count",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-checked-child-source-free-restoration",
        path: "tools/nuis/tests/native_session_workflow/sparse_typed_records.rs",
        required_patterns: &[
            "native_checked_child_snapshots_restore_computed_records_without_source",
            "if continuing { [4, 6, 11] } else { [6, 6, 11] }",
            "let checked_snapshot = 10 / (snapshot.count - carry.count)",
            "fs::remove_file(project.0.join(\"main.ns\"))",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-partial-child-snapshot-source-free-restoration",
        path: "tools/nuis/tests/native_session_workflow/sparse_typed_records.rs",
        required_patterns: &[
            "native_partial_child_snapshots_restore_full_width_state_without_sources",
            "[2, 6, 11] } else { [4, 6, 11]",
            "let checked_snapshot = 10 / snapshot.count",
            "fs::remove_file(project.0.join(\"main.ns\"))",
            "fs::remove_file(project.0.join(\"nuis.toml\"))",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-observed-child-source-free-restoration",
        path: "tools/nuis/tests/native_session_workflow/sparse_typed_records.rs",
        required_patterns: &[
            "native_observed_child_exit_indices_restore_full_width_state_without_sources",
            "Some(continuing)",
            "fs::remove_file(project.0.join(\"main.ns\"))",
            "fs::remove_file(project.0.join(\"nuis.toml\"))",
            "assert_eq!(fs::read_to_string(restored.join(&llvm_name)).unwrap(), llvm)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-readonly-scoped-scalar-contract",
        path: "crates/yir-core/src/loop_carry_contract/scoped_record_tests.rs",
        required_patterns: &[
            "scoped_readonly_records_share_dependencies_without_inventing_backedges",
            "scoped_plain_owned_captures_keep_resource_glm_modes",
            "parse_scoped_i64_carry(args)?.unwrap().dependencies()",
            "parse_scoped_call(args)?.unwrap().dependencies()",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-readonly-scoped-scalar-reference",
        path: "crates/yir-domain-cpu/src/tests_loop_effect_execution.rs",
        required_patterns: &[
            "scoped_readonly_records_execute_without_multi_carry_authority",
            "0x7ff8_0000_0000_1234",
            "state.values.remove(name)",
            "CpuMod.describe(&invalid, &resource()).is_err()",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-readonly-scoped-scalar-llvm",
        path: "crates/yir-lower-llvm/src/scoped_record_args/tests.rs",
        required_patterns: &[
            "scoped_readonly_record_actions_validate_before_native_emission",
            "assert_eq!(body, [\"entry:\"])",
            "assert_eq!(reg, 73)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-readonly-scoped-scalar-all-callers",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_scoped_tests.rs",
        required_patterns: &[
            "scoped_readonly_record_transport_covers_plain_and_single_carry_actions",
            "inputs[\"helper\"].carried.is_empty()",
            "inputs[\"helper\"].elidable.is_empty()",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-opaque-continue-snapshot-timing",
        path: "tools/nuisc/tests/native_application_bridge/sparse_typed_return_child_exits.rs",
        required_patterns: &[
            "typed_nested_opaque_continue_snapshot_traps_keep_iteration_timing",
            "if k == 1 {{ continue; }} {call}",
            "remaining: [59, if late { 47 } else { 52 }]",
            "entries: if late { 16 } else { 11 }",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-opaque-continue-snapshot-source-free",
        path: "tools/nuis/tests/native_session_workflow/sparse_typed_records.rs",
        required_patterns: &[
            "native_opaque_continue_snapshots_restore_readonly_record_inputs_without_source",
            "&[4, 6, 11]",
            "Some(true)",
            "fs::remove_file(project.0.join(\"main.ns\"))",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-readonly-scoped-single-carry-induction-orders",
        path: "tools/nuisc/tests/control_flow_syntax_native/scoped_field_seeds.rs",
        required_patterns: &[
            "scoped_readonly_record_single_carry_runs_with_both_induction_orders",
            "scoped_call_i64_carry",
            "arg.starts_with(\"$value_record:\")",
            "for leading in [false, true]",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-readonly-scoped-plain-shared-parser",
        path: "crates/yir-core/src/loop_carry_contract/scoped_call.rs",
        required_patterns: &[
            "args.get(6).map(String::as_str) != Some(\"scoped_call\")",
            "arity.checked_add(8)",
            "!named(&args[8])",
            "readonly_record(operand)?",
            "scoped read-only record cannot contain carry mappings",
        ],
    },
];
