use crate::dev_tensor_drift::DevTensorDriftCheckSpec;

pub(super) const CHECKS: &[DevTensorDriftCheckSpec] = &[
    DevTensorDriftCheckSpec {
        id: "native-return-suffix-original-preflight-before-recursive-work",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_suffix.rs",
        required_patterns: &[
            "if !preflight(body)",
            "let mut statements = 32",
            "statements -= body.len()",
            "intermediate |= index + 1 < body.len()",
            "intermediate && conditional_values::prefix::computed_expression_roots(expressions)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-suffix-original-lexical-type-and-reachability-proof",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_suffix.rs",
        required_patterns: &[
            "validate(body, scope.clone(), result, catalog, layouts)?",
            "if !continues",
            "if scope.contains_key(name)",
            "declared.is_some_and(|ty| ty != &inferred)",
            "let yes = validate(then_body, scope.clone(), result, catalog, layouts)?",
            "continues = yes || no",
            "!= Some(scalar_type(\"bool\"))",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-suffix-borrowed-expanded-plan-before-expression-cloning",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_suffix.rs",
        required_patterns: &[
            "Statement(&'a NirStmt)",
            "let plan = plan(body.iter().collect(), &mut statements)?",
            "*statements = statements.checked_sub(1)?",
            "let tail = &sequence[index + 1..]",
            "Do not append any inherited suffix to an observed return",
            "conditional_values::prefix::computed_expression_roots(expressions).then(|| materialize(plan))",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-suffix-independent-arm-and-capture-revalidation",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns.rs",
        required_patterns: &[
            "mod suffix;",
            "suffix::prepare(then_body, result, scope, catalog, layouts)",
            "suffix::prepare(else_body, result, scope, catalog, layouts)",
            "yes_source.as_deref().unwrap_or(then_body)",
            "signal::prepare(body, result, scope, catalog, layouts)?",
            "if !has_return",
            ".is_some_and(|ty| return_values::capture(result, ty))",
            "Wrap original leaves, never the other proof's synthetic scalar seeds",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-suffix-reference-structure-budget-and-veto-proofs",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_suffix_tests.rs",
        required_patterns: &[
            "conditional_return_suffixes_run_only_continuing_paths_and_preserve_selected_checks",
            "assert_eq!(cases, 360)",
            "conditional_return_suffixes_keep_earlier_parent_exits_and_current_scalar_versions",
            "assert_eq!(cases, 34)",
            "conditional_return_suffixes_keep_real_zero_exits_separate_from_parent_continuations",
            "assert_eq!(cases, 48)",
            "conditional_return_suffixes_preserve_original_conditions_parent_tail_and_helper_hygiene",
            "conditional_return_suffixes_bound_original_and_expanded_work_before_expression_cloning",
            "conditional_return_suffixes_reject_scope_leaks_effects_rebinding_unreachable_work_and_new_exit_authority",
            "assert_eq!(module, before)",
            "assert_eq!(module, once)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-suffix-default-source-binaries-and-selected-traps",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_suffix_native_tests.rs",
        required_patterns: &[
            "conditional_return_suffixes_execute_default_aot_selected_and_skipped_tail_checks",
            "conditional_return_suffixes_execute_default_aot_real_zero_and_parent_continuations",
            "use super::super::super::tests::native::run",
            "Some(\"99\\n0\")",
            "Some(\"99\\n77\\n19\")",
            "(true, false, true, 2, 0, None)",
            "run(&source, expected)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-suffix-documentation-independent-bounds-and-scope",
        path: "docs/reference/nuis-native-scalar-loop-snapshots-v1.md",
        required_patterns: &[
            "## Bounded Pure Intermediate Suffixes",
            "Original lexical scopes, exact declared/inferred types and reachability are",
            "independently limited to 32 statements and 4096 expression nodes",
            "Eight compiler tests cover 442 runtime source cases and 884 ordinary/reversed",
            "A normalization-induced local name collision is",
            "Eighteen default-source",
            "not fresh Linux/GPU acceptance",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-suffix-tensor-receipt-and-next-unproven-boundary",
        path: "tools/nuis/src/dev_tensor_data.rs",
        required_patterns: &[
            "Bounded intermediate-suffix follow-up:",
            "Bounded intermediate-suffix acceptance:",
            "442 runtime source cases and 884 ordinary/reversed reference executions",
            "Previous outer-entry checkpoint:",
            "conditional_return_suffixes",
            "active/89",
            "logical entry/inline conditions outside these proofs",
        ],
    },
];
