use crate::dev_tensor_drift::DevTensorDriftCheckSpec;

pub(crate) const DEV_TENSOR_RUNTIME_BOOTSTRAP_REPRODUCIBILITY_DRIFT_CHECKS:
    &[DevTensorDriftCheckSpec] = &[
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-data-model-v3-contract",
        path: "docs/reference/nuis-compiler-data-model-v3.toml",
        required_patterns: &[
            "nuis-compiler-data-model-v3",
            "surface.std.compiler-data-model.v3",
            "stdlib/std/lib/compiler_data.ns",
            "stdlib/std/lib/compiler_token_emit.ns",
            "maximum_records = 4",
            "packed_word_bytes = 7",
            "emission_capacity_bytes = 128",
            "expected_native_exit = 122",
            "expected_emitted_bytes = 59",
            "candidate_prefix_emitted_bytes = 91",
            "candidate_prefix_emitted_hash = 1277127995",
            "compiler_token_materializer_decode_first_page",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-component-reproducibility-contract",
        path: "docs/reference/nuis-compiler-component-reproducibility-v1.toml",
        required_patterns: &[
            "nuis-compiler-component-reproducibility-v1",
            "nuis-compiler-two-clean-build-roots-v1",
            "nuis bootstrap-reproducibility",
            "compile_cache_status = \"bypass\"",
            "run_count = 2",
            "reproducible-equivalent-awaiting-authorization",
            "no-physical-paths-or-timestamps-in-aggregate",
            "replacement_authorized = false",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-component-reproducibility-artifact",
        path: "crates/nuis-artifact/src/compiler_component_reproducibility.rs",
        required_patterns: &[
            "COMPILER_COMPONENT_REPRODUCIBILITY_PROTOCOL",
            "COMPILER_COMPONENT_CLEAN_BUILD_CONTRACT",
            "build_compiler_component_reproducibility_from_paths",
            "read_compiler_component_reproducibility",
            "compile-cache bypass evidence",
            "two distinct build roots",
            "drifted across clean runs",
            "replacement_authorized: false",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-component-reproducibility-frontdoor",
        path: "tools/nuis/src/bootstrap_reproducibility.rs",
        required_patterns: &[
            "handle_bootstrap_reproducibility",
            "prepare_empty_output_root",
            "handle_bootstrap_clean_candidate_build",
            "clean-build-0",
            "clean-build-1",
            "build_compiler_component_reproducibility_from_paths",
            "bootstrap compiler reproducibility: verified",
            "replacement_authorized: false",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-component-reproducibility-native-regression",
        path: "tools/nuis/tests/compiler_structural_projection_candidate.rs",
        required_patterns: &[
            "bootstrap-reproducibility",
            "two_uncached_clean_candidates_bind_one_reproducibility_aggregate",
            "compile_cache_status.as_deref(), Some(\"bypass\")",
            "reproducible-equivalent-awaiting-authorization",
            "bound root tampering must invalidate aggregate",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-try-expansion-compilation-local-counter",
        path: "tools/nuisc/src/frontend/stmt_lowering_try.rs",
        required_patterns: &[
            "thread_local!",
            "TRY_EXPANSION_COUNTER: Cell<usize>",
            "reset_try_expansion_counter",
            "next_try_expansion_id",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-try-expansion-reproducibility-regression",
        path: "tools/nuisc/src/frontend/tests_reproducibility.rs",
        required_patterns: &[
            "repeated_same_thread_lowering_resets_try_expansion_names",
            "lower_ast_to_nir(&ast)",
            "__nuis_try_result_0",
            "assert_eq!(first, second)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-token-decoder-artifact",
        path: "crates/nuis-artifact/src/compiler_token_decoder.rs",
        required_patterns: &[
            "nuis-compiler-token-decoder-v1",
            "decode_compiler_token_stream",
            "COMPILER_TOKEN_DECODER_MAX_BYTES",
            "COMPILER_TOKEN_DECODER_MAX_RECORDS",
            "fold_hex_payload",
            "fold_integer_payload",
            "fold_symbol_payload",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-token-decoder-stdlib",
        path: "stdlib/std/lib/compiler_tokens.ns",
        required_patterns: &[
            "mod cpu StdCompilerTokens",
            "compiler_token_decoder_step",
            "compiler_token_decoder_count_step",
            "compiler_token_decoder_semantic_step",
            "compiler_token_decoder_finish",
            "compiler_token_decoder_max_bytes",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-token-decoder-candidate-abi",
        path: "examples/projects/tooling/bootstrap_structural_projection_candidate/main.ns",
        required_patterns: &[
            "use cpu StdCompilerTokens",
            "nuis_bootstrap_candidate_token_start_v1",
            "nuis_bootstrap_candidate_token_step_v1",
            "nuis_bootstrap_candidate_token_semantic_step_v1",
            "nuis_bootstrap_candidate_token_finish_v1",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-token-decoder-production-binding",
        path: "crates/nuis-artifact/src/compiler_candidate_production.rs",
        required_patterns: &[
            "nuis-compiler-candidate-production-v5",
            "token_decoder_contract",
            "token_record_count",
            "token_semantic_fold",
            "token_page_identity",
            "canonical token page identity mismatch",
            "ast_page_identity",
            "AST structural page identity mismatch",
            "nir_page_identity",
            "NIR structural page identity mismatch",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-candidate-production-contract",
        path: "docs/reference/nuis-compiler-candidate-production-v5.toml",
        required_patterns: &[
            "nuis-compiler-candidate-production-v5",
            "nuis-stage1-materialized-token-ast-nir-page-producer-v5",
            "stage1-candidate-component-production-no-replacement",
            "nuis bootstrap-candidate-build",
            "host-byte-transport-packing-and-state-orchestration-without-token-ast-or-nir-semantics",
            "reference_token_page_identity = 164749511446",
            "reference_ast_page_identity = 174028320749",
            "reference_nir_page_identity = 132469386887",
            "replacement_authorized = false",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-development-tensor-candidate-production-baseline",
        path: "docs/reference/nuis-development-tensor.md",
        required_patterns: &[
            "stage-neutral boundary to",
            "`usable/91`",
            "both driver and\nreproducibility gate at `usable/92`",
            "Data model v3 is `usable/92`",
            "NIR identity `132469386887`",
            "Deterministic page continuation is now the shared weakest boundary",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-candidate-production-artifact",
        path: "crates/nuis-artifact/src/compiler_candidate_production.rs",
        required_patterns: &[
            "COMPILER_CANDIDATE_PRODUCTION_PROTOCOL",
            "COMPILER_CANDIDATE_PRODUCTION_AUTHORITY",
            "build_compiler_candidate_production",
            "read_compiler_candidate_production",
            "compiler_candidate_stage_fold",
            "compiler_candidate_bundle_fold",
            "ast_page_contract",
            "AST structural page identity mismatch",
            "nir_page_contract",
            "NIR structural page identity mismatch",
            "replacement_authorized: false",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-candidate-production-frontdoor",
        path: "tools/nuis/src/bootstrap_candidate_build.rs",
        required_patterns: &[
            "handle_bootstrap_candidate_build",
            "run_candidate_adapter",
            "promote_compiler_component_candidate",
            "build_compiler_candidate_production",
            "BootstrapDiff",
            "equivalent-awaiting-authorization",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-compiler-candidate-production-native-regression",
        path: "tools/nuis/tests/compiler_structural_projection_candidate.rs",
        required_patterns: &[
            "bootstrap-candidate-build",
            "read_compiler_candidate_production",
            "COMPILER_COMPONENT_STAGE1_CANDIDATE_ROLE",
            "nuis-stage1-token-ast-nir-materializer-v5",
            "token_page_identity, 164_749_511_446",
            "ast_page_identity, 174_028_320_749",
            "nir_page_identity, 132_469_386_887",
            "equivalent_count, 13",
            "adapter tampering must invalidate production proof",
        ],
    },
];
