use crate::dev_tensor_drift::DevTensorDriftCheckSpec;

pub(crate) const DEV_TENSOR_RUNTIME_NSLD_SHELL_IMAGE_DRIFT_CHECKS: &[DevTensorDriftCheckSpec] = &[
    DevTensorDriftCheckSpec {
        id: "nsld-macho-arm64-shell-image-serialization-contract",
        path: "tools/nsld/src/final_executable_macho_shell_image.rs",
        required_patterns: &[
            "nuis-nsld-macho-arm64-shell-image-serialization-v2",
            "serialize_macho_arm64_shell_image",
            "signed-private-image-validated",
            "private-not-published",
            "plan_macho_arm64_ad_hoc_signature",
            "encode_macho_arm64_ad_hoc_signature",
            "validate_macho_arm64_signed_shell_image",
            "encode_shell_header_and_commands",
            "encode_shell_linkedit",
            "rewrite_shell_image_addresses",
            "serialization_ledger_hash",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-macho-arm64-shell-image-final-address-evidence",
        path: "tools/nsld/src/final_executable_macho_shell_image_tests.rs",
        required_patterns: &[
            "serializes_a_deterministic_private_arm64_shell_image",
            "relocation-final-address",
            "stub-final-address",
            "serializes_internal_got_rebase_with_final_pointer_value",
            "internal-got-final-address",
            "signed_image_validator_rejects_signed_content_drift",
            "signed_image_validator_rejects_load_command_boundary_drift",
            "signed_image_validator_rejects_signature_padding_drift",
            "platform image drift",
            "input hash drift",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-macho-arm64-os-loader-probe-contract",
        path: "tools/nsld/src/final_executable_macho_loader_probe.rs",
        required_patterns: &[
            "nuis-nsld-macho-arm64-os-loader-probe-v1",
            "probe_macho_arm64_signed_shell_image",
            "explicit-loader-probe-apply-required",
            "private-image-has-external-compatibility-bindings",
            "eligible-isolated-os-loader-probe-passed",
            "PROBE_TIMEOUT",
            "CAPTURE_LIMIT_BYTES",
            "cleanup_probe_paths",
            "probe_ledger_hash",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-macho-arm64-os-loader-probe-evidence",
        path: "tools/nsld/src/final_executable_macho_loader_probe_tests.rs",
        required_patterns: &[
            "plan_only_probe_requires_explicit_apply_without_materializing",
            "isolated_probe_is_accepted_by_the_os_loader_and_cleans_up",
            "probe_rejects_external_compatibility_input_before_materialization",
            "probe_rejects_private_image_byte_drift",
            "cleanup_preserves_paths_not_created_by_the_probe",
            "capture_limit_detects_oversized_probe_output",
            "publication_eligible",
            "cleanup_succeeded",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-macho-arm64-publication-admission-receipt-contract",
        path: "tools/nsld/src/final_executable_macho_admission_receipt.rs",
        required_patterns: &[
            "nuis-nsld-macho-arm64-publication-admission-v1",
            "nuis.nsld.macho-arm64-publication-admission.toml",
            "persist_macho_arm64_publication_admission_receipt",
            "parse_macho_arm64_publication_admission_receipt",
            "receipt_hash_sha256",
            "StrictReceiptFields",
            "atomic_write_receipt",
            "options.mode(0o600)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-macho-arm64-publication-admission-validation-contract",
        path: "tools/nsld/src/final_executable_macho_admission.rs",
        required_patterns: &[
            "nuis-nsld-macho-arm64-publication-admission-validation-v1",
            "build_macho_arm64_publication_admission_receipt",
            "verify_macho_arm64_publication_admission_receipt",
            "validate_successful_macho_arm64_loader_probe",
            "receipt-hash-mismatch",
            "private-image-identity-mismatch",
            "signature-identity-mismatch",
            "loader-probe-evidence-invalid",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-macho-arm64-publication-admission-cli-evidence",
        path: "tools/nsld/tests/host_finalizer_cli.rs",
        required_patterns: &[
            "cli_persists_and_replays_internal_private_image_admission_receipt",
            "verify-final-executable-private-image-admission",
            "publication-admission-replay-verified",
            "receipt-hash-mismatch",
            "write_internal_native_cpu_fixture_returning",
            "\\\"private_image_matches\\\":false",
            "\\\"signature_identity_matches\\\":false",
            "private-image-identity-mismatch",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-registered-private-image-publication-capability",
        path: "tools/nsld/src/final_executable_finalizer_registry.rs",
        required_patterns: &[
            "PrivateImagePublisher",
            "private_image_publication_capability",
            "supports_private_image_publication",
            "invoke_registered_private_image_publication",
            "MACHO_ARM64_PRIVATE_IMAGE_PUBLICATION_CAPABILITY",
            "private_image_publication=",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-macho-arm64-private-image-publication-contract",
        path: "tools/nsld/src/final_executable_macho_publication.rs",
        required_patterns: &[
            "nuis-nsld-registered-private-image-publication-v1",
            "publish_macho_arm64_private_image",
            "verify_macho_arm64_publication_admission_receipt",
            "atomic_install_private_image",
            "options.mode(0o700)",
            "temporary private-image byte identity drift",
            "sha256_file",
            "file_matches_bytes",
            "64 * 1024",
            "sync_directory",
            "publication_ledger_sha256",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-macho-arm64-private-image-publication-cli-evidence",
        path: "tools/nsld/tests/host_finalizer_cli.rs",
        required_patterns: &[
            "final-executable-private-image-publication",
            "ready-private-image-publication-plan",
            "blocked-publication-admission-invalid",
            "private-image-published",
            "publication-admission:receipt-hash-mismatch",
            "assert_eq!(private_image_mode, 0o700)",
            "private_execution.status.success()",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-macho-arm64-shell-image-three-surface-evidence",
        path: "tools/nsld/tests/host_finalizer_cli.rs",
        required_patterns: &[
            "nuis-nsld-macho-arm64-shell-image-serialization-v2",
            "signed-private-image-validated",
            "private-not-published",
            "ad-hoc-payload-validated",
            "signed-private-image-structurally-valid",
            "independent-os-load-validation-pending",
            "nuis-nsld-macho-arm64-os-loader-probe-v1",
            "blocked-external-compatibility-input",
            "shell_image_serialization",
            "finalizer_input_shell_image_contract",
            "finalizer_input_shell_image_rewrite",
            "persisted_invoke_plan",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-macho-arm64-ad-hoc-signature-contract",
        path: "tools/nsld/src/final_executable_macho_shell_signature.rs",
        required_patterns: &[
            "nuis-nsld-macho-arm64-ad-hoc-signature-v1",
            "plan_macho_arm64_ad_hoc_signature",
            "encode_macho_arm64_ad_hoc_signature",
            "CSMAGIC_EMBEDDED_SIGNATURE",
            "CSMAGIC_CODEDIRECTORY",
            "HASH_TYPE_SHA256",
            "CODE_PAGE_SIZE_BYTES",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-macho-arm64-signed-image-validation-contract",
        path: "tools/nsld/src/final_executable_macho_shell_signature_validation.rs",
        required_patterns: &[
            "nuis-nsld-macho-arm64-signed-image-validation-v1",
            "nuis-nsld-macho-arm64-publication-eligibility-v1",
            "validate_macho_arm64_signed_shell_image",
            "signed-private-image-structurally-valid",
            "blocked-independent-os-load-validation-pending",
            "validate_load_commands",
            "validate_code_slots",
            "validation_ledger_hash",
        ],
    },
];
