use crate::dev_tensor_drift::DevTensorDriftCheckSpec;

pub(super) const CHECKS: &[DevTensorDriftCheckSpec] = &[
    DevTensorDriftCheckSpec {
        id: "native-session-guarded-break-source-normalization",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/control_flow.rs",
        required_patterns: &[
            "let break_only = breaking.is_some() && !contains_continue(effects)",
            "let running_value = i64::from(!break_only)",
            "if breaking != Some(flag)",
            "rhs: Box::new(NirExpr::Int(running_value))",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-guarded-break-scalar-source-admission",
        path: "tools/nuisc/src/lowering/buffer_loop_outline.rs",
        required_patterns: &[".filter(|plan| plan.has_store || plan.break_flag.is_some())"],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-guarded-break-parity-and-rejections",
        path: "tools/nuisc/tests/native_application_bridge/break_loops.rs",
        required_patterns: &[
            "guarded_break_scoped_calls_preserve_native_reference_and_typed_session_parity",
            "guarded_break_keeps_shared_layout_kinds_closure_and_general_call_rejections",
            "guarded_break_reference_fuel_failure_keeps_accepted_state",
            "scalar_break_source_preserves_provenance_and_rejects_unmodeled_updates",
            "assert_native_parity(BREAKS, true)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-guarded-break-execution-and-control",
        path: "tools/nuisc/tests/native_application_bridge/break_execution.rs",
        required_patterns: &[
            "guarded_break_native_calls_commit_carries_and_release_aggregates_before_exit",
            "guarded_break_rejects_nonzero_control_seeds_even_on_zero_trips",
            "guarded_break_rejects_invalid_returned_controls_without_exporting_state",
            "guarded_break_does_not_bypass_the_full_induction_preflight",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-guarded-break-source-nested-scope",
        path: "tools/nuisc/tests/native_application_bridge/break_source.rs",
        required_patterns: &[
            "scalar_break_source_keeps_current_skips_suffix_and_isolates_nested_exits",
            "ApplicationSession::open_registered",
            "assert_eq!(state_words(session.state()), result)",
            "for multi_state in [false, true]",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-guarded-break-frontdoor-restoration",
        path: "tools/nuis/tests/native_session_workflow.rs",
        required_patterns: &[
            "break_loops.ns",
            "native_guarded_break_build_cache_and_standalone_relocation",
            "loop_break_control_invalid",
            "check_workflow(BREAK_SOURCE)",
            "branch_loops.ns",
            "native_multi_state_branch_build_cache_and_standalone_relocation",
            "check_workflow(BRANCH_SOURCE)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-flat-helper-return-contract",
        path: "crates/yir-lower-llvm/src/native_session/aggregates.rs",
        required_patterns: &[
            "pub(super) fn result_layout",
            "layout.fields.len() <= super::MAX_SCALAR_SLOTS",
            "result.ownership != YirValueOwnership::Owned",
            "flat_return_layout_has_a_slot_bound_not_precombined_arities",
            "flat_return_call_rejects_missing_layout_and_other_payload_families",
            "ordinary_flat_returns_preserve_declared_names_without_a_loop_carry_schema",
            "names.insert(name)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-flat-helper-call-closure",
        path: "crates/yir-lower-llvm/src/native_session/calls.rs",
        required_patterns: &[
            "super::aggregates::parse(node)?",
            "call.operands.len()",
            "super::aggregates::result_layout(function, nodes)? == layout",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-flat-helper-admission-proof",
        path: "tools/nuisc/tests/native_application_bridge/aggregate_admission.rs",
        required_patterns: &[
            "flat_aggregate_calls_require_exact_call_result_and_parameter_contracts",
            "flat_aggregate_edges_reject_hidden_effects_foreign_values_and_recursive_helpers",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-flat-helper-nested-release-proof",
        path: "tools/nuisc/tests/native_application_bridge/aggregate_execution.rs",
        required_patterns: &[
            "ordinary_flat_returns_preserve_exact_captures_order_and_nested_drop_balance",
            "multi_execution::execute_observed",
            "for slots in [2, 3, 7]",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-flat-helper-selected-path-proof",
        path: "tools/nuisc/tests/native_application_bridge/aggregate_guards.rs",
        required_patterns: &[
            "aggregate_early_return_skips_unselected_loop_preflight_but_selected_path_traps",
            "native_loop_preflight",
            "ApplicationSession::open_registered",
            "trap must not return callback state",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-multi-state-branch-lifecycle-proof",
        path: "tools/nuisc/tests/native_application_bridge/branch_loops.rs",
        required_patterns: &[
            "guarded_multi_state_exits_preserve_native_reference_and_typed_session_parity",
            "assert_native_parity(BRANCHES, true)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-checked-arithmetic-exact-kinds",
        path: "crates/yir-lower-llvm/src/function_lowering/strict_scalar.rs",
        required_patterns: &[
            "matches!(node.op.instruction.as_str(), \"div\" | \"rem\")",
            "native integer division/remainder",
            "require_value(node, operand, CpuCallScalarKind::I64, registers)?",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-checked-arithmetic-source-speculation",
        path: "tools/nuisc/src/lowering/speculation.rs",
        required_patterns: &[
            "pub(super) fn collect_checked_arithmetic",
            "while let Some(name) = pending.pop_first()",
            "NirBinaryOp::Div | NirBinaryOp::Rem",
            "purity_does_not_make_transitive_checked_arithmetic_speculatable",
            "reordered.functions.reverse()",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-checked-arithmetic-execution",
        path: "tools/nuisc/tests/native_application_bridge/division_execution.rs",
        required_patterns: &[
            "checked_division_remainder_match_wide_oracle_and_skip_unselected_invalid_values",
            "selected_invalid_arithmetic_traps_even_for_unused_results_and_arguments",
            "invalid_constant_arithmetic_is_not_folded_away_or_hoisted_across_a_guard",
            "reference_arithmetic_failure_preserves_the_last_accepted_session_state",
            "i128::from(case.left)",
            "assert_eq!(cases.len(), 230)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-checked-arithmetic-admission",
        path: "tools/nuisc/tests/native_application_bridge/division_admission.rs",
        required_patterns: &[
            "generic_division_and_remainder_require_two_exact_i64_operands",
            "fallible_aggregate_returns_use_guarded_helpers_instead_of_speculation",
            "assert_native_parity(DIVISION, true)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-checked-arithmetic-frontdoor",
        path: "tools/nuis/tests/native_session_workflow.rs",
        required_patterns: &[
            "division_loops.ns",
            "native_checked_division_build_cache_and_standalone_relocation",
            "integer_divisor_invalid",
            "check_workflow(DIVISION_SOURCE)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-flat-value-control-catalog",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/control_values/tests.rs",
        required_patterns: &[
            "value_catalog_keeps_transitive_types_effects_cycles_and_buffer_admission_separate",
            "aggregate_control_outlining_shares_suffixes_and_captures_existing_records",
            "assert_eq!(helpers.len(), 32 * 3)",
            "scalar_helpers::collect_with_layouts",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-shared-value-operators-and-neutral-guards",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/control_values.rs",
        required_patterns: &[
            "pub(super) fn binary_type",
            "NirBinaryOp::Div",
            "NirBinaryOp::Rem",
            "pub(super) fn zero_value",
            "NirExpr::Bool(false)",
            "NirExpr::Int(0)",
            "NirExpr::StructLiteral",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-fallible-aggregate-execution",
        path: "tools/nuisc/tests/native_application_bridge/aggregate_division.rs",
        required_patterns: &[
            "fallible_flat_branches_match_oracles_and_release_real_aggregate_temporaries",
            "fallible_flat_branches_trap_only_on_reached_operands_including_prefixes",
            "flat_branch_literal_failures_stay_behind_the_selected_guard",
            "registered_flat_state_branches_keep_declared_field_names_and_declaration_order_parity",
            "counted_loop_bearing_aggregate_branches_gain_guarded_lowering",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-counted-value-source-admission",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/control_loops.rs",
        required_patterns: &[
            "prepare_counted_while(",
            "locals.contains(name)",
            "!updates.contains(input) && scope.get(input)? == &scalar_type(\"i64\")",
            "!updates.insert(name.to_owned())",
            "&& nonfallible_i64(value, scope)",
            "prepare_chained_while(",
            "chained.carries.len() != tail.len()",
            "validate_condition(condition, scope, &updates, &available)?",
            "validate_condition_leaf(condition, scope, updates, available)?",
            "([then_update], [else_update])",
            "([update], []) | ([], [update]) => binding(update)",
            "(name == binding(else_update)?).then_some(name)",
            "!updates.contains(name) && scope.get(name) == Some(&scalar_type(\"i64\"))",
            "counted_control_catalog_is_transitive_without_widening_buffer_admission",
            "counted_control_catalog_rejects_mutation_type_effect_and_invariant_drift",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-counted-value-outlining-selection",
        path: "tools/nuisc/src/lowering/buffer_loop_outline.rs",
        required_patterns: &["helper.may_loop || checked_arithmetic.contains(&function.name)"],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-counted-value-transitive-boundaries",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/scalar_helpers.rs",
        required_patterns: &[
            "collect_profile(module, &control_values::FlatLayouts::new(), false)",
            "control_loops::contains_loop(&function.body)",
            "helper.may_loop |= helper",
            ".any(|name| admitted[name].may_loop)",
            "control_loops::validate(condition, body, locals, loop_bindings)?",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-counted-value-execution",
        path: "tools/nuisc/tests/native_application_bridge/aggregate_counted.rs",
        required_patterns: &[
            "guarded_counted_values_match_reference_and_independent_oracle",
            "guarded_counted_preflight_and_arithmetic_trap_only_when_selected",
            "loop_only_branches_preserve_preflight_without_checked_arithmetic",
            "loop_carried_updates_inside_flat_branches_gain_guarded_lowering",
            "counted_flat_branch_helpers_compose_with_typed_lifecycle",
            "aggregate_loop_probe::execute(",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-guarded-loop-execution-probe",
        path: "tools/nuisc/tests/native_application_bridge/aggregate_loop_probe.rs",
        required_patterns: &[
            "probe_trap_evidence",
            "multi_execution::ALLOCATION_PROBE",
            "call void @llvm.trap()",
            "ApplicationSession::open_registered(",
            "dynamic_loop_guard::run_bounded(",
            "assert_eq!(actual, oracle)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-carried-value-source-policy",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/control_loops/carries_tests.rs",
        required_patterns: &[
            "ordered_carries_share_preparation_without_widening_buffer_catalog",
            "carry_catalog_is_not_a_finite_backend_profile_table",
            "carries_reject_seed_order_effect_and_header_mutation_drift",
            "carry_updates_require_exact_i64_declarations_and_values",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-carried-value-execution",
        path: "tools/nuisc/tests/native_application_bridge/aggregate_carried.rs",
        required_patterns: &[
            "guarded_carried_values_match_reference_and_ordered_wrapping_oracle",
            "variable_carry_widths_and_loop_only_guards_retain_every_slot",
            "guarded_carries_trap_before_updates_and_never_speculate_skipped_calls",
            "one_sided_carry_updates_inside_flat_branches_gain_shared_keep_lowering",
            "carried_flat_branch_helpers_compose_with_typed_lifecycle",
            "aggregate_loop_probe::execute(",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-carried-value-frontdoor",
        path: "tools/nuis/tests/native_session_workflow.rs",
        required_patterns: &[
            "aggregate_carried_loops.ns",
            "native_guarded_carried_aggregate_build_cache_and_standalone_relocation",
            "check_workflow(AGGREGATE_CARRIED_SOURCE)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-conditional-value-source-policy",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/control_loops/conditional_tests.rs",
        required_patterns: &[
            "conditional_carries_reuse_ordered_preparation_and_keep_buffer_catalog_narrow",
            "conditional_comparisons_support_invariant_atoms_and_reversed_operands",
            "reversed_condition_preparation_does_not_hoist_expressions",
            "conditional_carries_reject_stale_state_fallible_predicates_and_body_effects",
            "conditional_arms_cannot_mutate_the_header_or_change_scalar_kind",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-conditional-comparison-normalization",
        path: "tools/nuisc/src/lowering/loop_preparation_flow.rs",
        required_patterns: &[
            "parse_prepared_loop_state_ref_expr(&rhs, binding_name, carries)?",
            "!matches!(lhs, NirExpr::Int(_) | NirExpr::Var(_))",
            "PreparedLoopCompare::Lt => PreparedLoopCompare::Gt",
            "PreparedLoopCompare::Ge => PreparedLoopCompare::Le",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-conditional-metadata",
        path: "crates/yir-lower-llvm/src/native_session/loops/conditional.rs",
        required_patterns: &[
            "shape::validate(node)?",
            "yir_domain_cpu::parse_conditional_carries(",
            "LoopCondExpr::Binary { lhs, rhs, .. }",
            "!branch.payload.is_empty()",
            "condition_source(kind, index, carries.len())",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-conditional-metadata-regressions",
        path: "crates/yir-lower-llvm/src/native_session/loops/conditional/tests.rs",
        required_patterns: &[
            "conditional_metadata_preserves_selected_and_previous_state_contracts",
            "conditional_metadata_rejects_hidden_payloads_forward_state_and_ignored_tokens",
            "conditional_metadata_enforces_slot_and_induction_bounds",
            "compound_metadata_preserves_nested_state_and_opaque_rhs_names",
            "compound_metadata_bounds_depth_and_nodes_before_recursive_parsing",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-conditional-exact-kinds",
        path: "crates/yir-lower-llvm/src/function_lowering/strict_scalar.rs",
        required_patterns: &[
            "native_session::loops::conditional::parse(node)?",
            "require_value(node, &carry.initial, CpuCallScalarKind::I64, registers)?",
            "crate::loop_carry_condition::rhs_names(&carry.condition)",
            "require_value(node, rhs, CpuCallScalarKind::I64, registers)?",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-conditional-reference-driver",
        path: "crates/yir-domain-cpu/src/execute_scalar_flow.rs",
        required_patterns: &[
            "\"cond_chain\" => (false, false, true)",
            "matches!(instruction, \"chain\" | \"cond_chain\")",
            "RegisteredExecutionStep::Continue",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-conditional-reference-steps",
        path: "crates/yir-domain-cpu/tests/scalar_flow_execution.rs",
        required_patterns: &[
            "conditional_chain_returns_ordered_state_and_retains_cooperative_steps",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-conditional-value-execution",
        path: "tools/nuisc/tests/native_application_bridge/aggregate_conditional.rs",
        required_patterns: &[
            "conditional_carries_match_native_reference_and_independent_ordered_oracle",
            "all_conditional_comparisons_reversed_operands_and_variable_widths_execute",
            "conditional_carry_preflight_traps_before_updates_and_skipped_calls_remain_skipped",
            "conditional_native_admission_rejects_scalar_kind_drift_even_on_zero_trips",
            "conditional_native_admission_rejects_missing_operands_and_hidden_branch_payloads",
            "conditional_reference_fuel_failure_retains_accepted_state_and_cleanup",
            "conditional_flat_branch_helpers_compose_with_typed_lifecycle",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-conditional-value-frontdoor",
        path: "tools/nuis/tests/native_session_workflow.rs",
        required_patterns: &[
            "aggregate_conditional_loops.ns",
            "native_guarded_conditional_aggregate_build_cache_and_standalone_relocation",
            "check_workflow(AGGREGATE_CONDITIONAL_SOURCE)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-one-sided-shared-preparation",
        path: "tools/nuisc/src/lowering/loop_preparation_carry_tree.rs",
        required_patterns: &[
            "([update], []) | ([], [update])",
            "normalized_then.is_empty() && normalized_else.is_empty()",
            "[] => Some(PreparedCarryDecisionTree::Leaf(Box::new(",
            "PreparedCarryBranchSource::KeepCurrentValue",
            "then_body.iter().chain(else_body).find_map",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-one-sided-value-source-policy",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/control_loops/one_sided_tests.rs",
        required_patterns: &[
            "missing_carry_arms_use_shared_keep_and_preserve_transitive_catalog_scope",
            "empty_or_malformed_carry_arms_cannot_create_or_erase_state",
            "one_sided_updates_require_existing_exact_i64_mutable_seeds_and_invariants",
            "invalid_one_sided_carry_seeds_and_types_are_rejected_before_lowering",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-one-sided-execution-registration",
        path: "tools/nuisc/tests/native_application_bridge.rs",
        required_patterns: &["mod aggregate_one_sided;"],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-one-sided-value-execution",
        path: "tools/nuisc/tests/native_application_bridge/aggregate_one_sided.rs",
        required_patterns: &[
            "one_sided_carries_preserve_own_state_and_source_order_in_real_native_execution",
            "one_sided_comparisons_reversed_operands_and_variable_widths_execute",
            "one_sided_preflight_and_checked_leaf_traps_do_not_speculate_skipped_calls",
            "one_sided_flat_branch_helpers_compose_with_typed_lifecycle",
            "one_sided_reference_fuel_failure_retains_accepted_state_and_cleanup",
            "aggregate_loop_probe::execute(",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-one-sided-value-frontdoor",
        path: "tools/nuis/tests/native_session_workflow.rs",
        required_patterns: &[
            "aggregate_one_sided_loops.ns",
            "native_guarded_one_sided_aggregate_build_cache_and_standalone_relocation",
            "check_workflow(AGGREGATE_ONE_SIDED_SOURCE)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-compound-condition-shape-bounds",
        path: "crates/yir-lower-llvm/src/native_session/loops/conditional/shape.rs",
        required_patterns: &[
            "MAX_CONDITION_NODES: usize = 127",
            "MAX_CONDITION_DEPTH: usize = 32",
            "node.op.args.len() > MAX_ARGS",
            "while let Some(depth) = pending.pop()",
            "has noncanonical conditional metadata",
            "Some(candidate) == node.op.args.first()",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-compound-shared-parser-depth",
        path: "crates/yir-domain-cpu/src/loop_metadata.rs",
        required_patterns: &[
            "parse_loop_carry_condition_at_depth",
            "if depth > 256",
            "loop condition depth limit of 256",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-compound-short-circuit-emitter",
        path: "crates/yir-lower-llvm/src/loop_carry_condition.rs",
        required_patterns: &[
            "fn rhs_names",
            "fn resolve_rhs",
            "fn emit_branch",
            "carry_predicate_{op}_rhs",
            "emit_branch(lhs, state, left_targets",
            "emit_branch(rhs, state, targets",
            "phi i1",
            "previous_carries",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-compound-emitter-integration",
        path: "crates/yir-lower-llvm/src/function_lowering/loop_cond_chain.rs",
        required_patterns: &[
            "crate::loop_carry_condition::rhs_names(&carry.condition)",
            "crate::loop_carry_condition::resolve_rhs(",
            "crate::loop_carry_condition::emit(",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-compound-source-policy",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/control_loops/compound_tests.rs",
        required_patterns: &[
            "compound_predicates_reuse_shared_preparation_without_widening_buffer_catalog",
            "every_compound_leaf_requires_exact_state_order_and_invariant_atoms",
            "source_condition_catalog_does_not_duplicate_native_profile_budgets",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-compound-backend-regressions",
        path: "crates/yir-lower-llvm/src/tests/compound_carry_tests.rs",
        required_patterns: &[
            "generic_compound_carries_keep_scalar_kinds_and_short_circuit_blocks",
            "shared_conditional_parser_depth_is_bounded_before_native_admission",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-compound-execution-registration",
        path: "tools/nuisc/tests/native_application_bridge.rs",
        required_patterns: &["mod aggregate_compound;", "mod predicate_probe;"],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-compound-value-execution",
        path: "tools/nuisc/tests/native_application_bridge/aggregate_compound.rs",
        required_patterns: &[
            "compound_carries_match_independent_oracle_and_actual_short_circuit_counts",
            "compound_precedence_grouping_and_variable_widths_execute",
            "compound_carry_preflight_and_checked_traps_preserve_selected_path_evaluation",
            "compound_rhs_kind_drift_rejects_even_in_skipped_leaves_and_zero_trip_loops",
            "registered_emission_rejects_deep_conditions_during_general_yir_verification",
            "compound_flat_branch_helpers_compose_with_typed_lifecycle",
            "compound_reference_fuel_failure_retains_accepted_state_and_cleanup",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-compound-comparison-observation",
        path: "tools/nuisc/tests/native_application_bridge/predicate_probe.rs",
        required_patterns: &[
            "line.contains(\" = icmp \")",
            "load volatile i64, ptr @probe_predicates",
            "probe_predicate_evidence",
            "carry_predicate_merge",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-compound-value-frontdoor",
        path: "tools/nuis/tests/native_session_workflow.rs",
        required_patterns: &[
            "aggregate_compound_loops.ns",
            "native_guarded_compound_aggregate_build_cache_and_standalone_relocation",
            "check_workflow(AGGREGATE_COMPOUND_SOURCE)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-reference-integer-wrapping",
        path: "crates/yir-domain-cpu/src/execute_scalar.rs",
        required_patterns: &[
            "wrapping_add(",
            "wrapping_sub(",
            "wrapping_mul(",
            "wrapping_neg()",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-reference-integer-wrapping-regression",
        path: "crates/yir-domain-cpu/src/tests_scalar_logic.rs",
        required_patterns: &[
            "scalar_integer_arithmetic_wraps_independently_of_host_build_profile",
            "invalid_integer_divisors_report_errors_without_panicking",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-counted-value-frontdoor",
        path: "tools/nuis/tests/native_session_workflow.rs",
        required_patterns: &[
            "aggregate_counted_loops.ns",
            "native_guarded_counted_aggregate_build_cache_and_standalone_relocation",
            "check_workflow(AGGREGATE_COUNTED_SOURCE)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-fallible-aggregate-frontdoor",
        path: "tools/nuis/tests/native_session_workflow.rs",
        required_patterns: &[
            "aggregate_division_loops.ns",
            "native_fallible_aggregate_build_cache_and_standalone_relocation",
            "check_workflow(AGGREGATE_DIVISION_SOURCE)",
        ],
    },
];
