use crate::dev_tensor_drift::DevTensorDriftCheckSpec;

pub(super) const CHECKS: &[DevTensorDriftCheckSpec] = &[
    DevTensorDriftCheckSpec {
        id: "native-return-logical-arm-original-preflight-and-typed-capture-validation",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_terminal.rs",
        required_patterns: &[
            "if !bounded_tree(body, true)",
            "let mut statements = 32usize",
            "expressions.push((value, 0, true))",
            "expressions.push((condition, 0, true))",
            "conditional_values::prefix::computed_expression_roots(expressions)",
            "control_values::value_type(condition, &inner, catalog, layouts)",
            "Non-total partial predicates use stored signals",
            "scope.get(name).is_some_and(scalar)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-logical-arm-return-only-prefix-and-shared-root-bounds",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_values_prefix.rs",
        required_patterns: &[
            "pub(in crate::lowering::buffer_loop_outline) fn bounded",
            "expressions(pending)",
            "pub(in crate::lowering::buffer_loop_outline) fn return_body",
            "pending.push((value, 0, true))",
            ".map(|(expr, depth)| (expr, depth, false))",
            "let mut work = 4096usize",
            "if depth >= 64 || work == 0",
            "!logical_root",
            "depth != 0",
            "!matches!(lhs.as_ref(), NirExpr::Bool(_) | NirExpr::Var(_))",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-logical-arm-original-and-expanded-suffix-roots-before-cloning",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_suffix.rs",
        required_patterns: &[
            "validate(body, scope.clone(), result, catalog, layouts)?",
            "plan(body.iter().collect(), &mut statements)?",
            "expressions.push((*condition, 0, true))",
            "expressions.push((condition, 0, true))",
            "expressions.push((value, 0, true))",
            "Bound expanded code before cloning any expression",
            "computed_expression_roots(expressions).then(|| materialize(plan))",
            "scope.contains_key(name)",
            "Do not append any inherited suffix to an observed return",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-logical-arm-reference-order-prefixes-and-zero-exits",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_logical_roots_tests.rs",
        required_patterns: &[
            "conditional_return_logical_roots_preserve_conditions_bindings_selected_checks_and_exits",
            "assert_eq!(cases, 720)",
            "conditional_return_logical_roots_keep_earlier_local_checks_and_continuation_bindings",
            "assert_eq!(cases, 180)",
            "conditional_return_logical_roots_compose_outer_entries_and_real_zero_parent_exits",
            "assert_eq!(cases, 96)",
            "prefix_checked = 10 / prefix",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-logical-arm-structure-budgets-vetoes-and-idempotence",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_logical_roots_tests.rs",
        required_patterns: &[
            "conditional_return_logical_roots_keep_original_helper_roots_private_signals_and_hygiene",
            "conditional_return_logical_roots_share_original_expanded_statement_node_and_depth_budgets",
            "conditional_return_logical_roots_retain_nested_derived_gate_scope_effect_and_capture_vetoes",
            "[\"exited\", \"value\"]",
            "assert_eq!(module, once)",
            "assert_eq!(module, before)",
            "for count in [61, 62]",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-logical-arm-default-source-binaries-and-selected-traps",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_logical_roots_native_tests.rs",
        required_patterns: &[
            "conditional_return_logical_roots_execute_default_aot_selected_conditions_and_binding_roots",
            "conditional_return_logical_roots_execute_default_aot_local_prefixes_outer_composition_and_zero_exits",
            "Some(\"99\\n0\")",
            "Some(\"99\\n77\\n10\")",
            "run(&source, expected)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-logical-arm-documented-independent-source-boundary",
        path: "docs/reference/nuis-native-scalar-loop-snapshots-v1.md",
        required_patterns: &[
            "## Guarded Logical Roots in Return Arms",
            "Eight compiler tests cover 996 runtime source cases and 1992 ordinary/reversed",
            "Ten earlier suites retain their newly admitted source",
            "General selection-prefix",
            "Nested logical roots, derived left gates",
            "The rebuilt CLI reports `active/91`",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-logical-arm-tensor-evidence-and-residual-boundaries",
        path: "tools/nuis/src/dev_tensor_data.rs",
        required_patterns: &[
            "Guarded logical-arm-root follow-up:",
            "Guarded logical-arm-root acceptance:",
            "Previous logical-entry checkpoint:",
            "996 runtime source cases and 1992 ordinary/reversed reference executions",
            "conditional_return_logical_roots",
            "active/91",
            "nested/derived-gate logical entry conditions",
        ],
    },
];
