use crate::dev_tensor_drift::DevTensorDriftCheckSpec;

pub(crate) const DEV_TENSOR_RUNTIME_STD_DRIFT_CHECKS: &[DevTensorDriftCheckSpec] = &[
    DevTensorDriftCheckSpec {
        id: "provider-neutral-device-sample-input-registration",
        path: "tools/nuis/src/artifact_device_sample_registration.rs",
        required_patterns: &[
            "nuis-device-sample-input-registration-v1",
            "DeviceSampleInputRegistration",
            "enrich_registered_input_evidence",
            "persist_registered_input_payloads",
            "registrations",
            "unregistered backends must remain generic",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "pixelmagic-owned-device-sample-input-registration",
        path: "tools/nuis/src/artifact_device_sample_pixelmagic.rs",
        required_patterns: &[
            "nuis.pixelmagic",
            "supports_filter_plan",
            "pixelmagic_filter_plan_evidence",
            "provider_filter_plan_hash=",
            "load_filter_plan_for_artifact_metadata",
            "artifact-request-selected",
            "persist_pixelmagic_payloads",
            "contract.pixelmagic.provider-sample-input-registration.v1",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "pixelmagic-owned-filter-plan-contract",
        path: "stdlib/pixelmagic/provider-plans/gray8-invert-threshold.nspf",
        required_patterns: &[
            "protocol=nuis-pixelmagic-filter-plan-v1",
            "package_id=nuis.pixelmagic",
            "plan_id=pixelmagic.gray8.invert-threshold",
            "stage_order=invert,threshold",
            "stage.invert.request_id=pixelmagic.gray8.invert",
            "stage.threshold.request_id=pixelmagic.gray8.threshold",
            "stage.threshold.input_source=dependency",
            "stage.threshold.producer_request_id=pixelmagic.gray8.invert",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "pixelmagic-filter-plan-aot-parser",
        path: "tools/nuis/src/artifact_device_sample_pixelmagic_plan.rs",
        required_patterns: &[
            "nuis-pixelmagic-filter-plan-v1",
            "nuis-pixelmagic-filter-plan-catalog-v1",
            "load_filter_plan",
            "PixelMagicFilterPlanCatalog",
            "provider_plan_default",
            "provider_plans",
            "requested_plan_id",
            "provider_filter_plan_artifact_request_id",
            "render_evidence",
            "persist_payloads",
            "dependency stage",
            "provider_filter_plan_stage_order",
            "nuis-provider-request-collection-v1",
            "nuis-provider-edge-transport-v1",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "pixelmagic-owned-second-filter-plan",
        path: "stdlib/pixelmagic/provider-plans/gray8-threshold.nspf",
        required_patterns: &[
            "protocol=nuis-pixelmagic-filter-plan-v1",
            "package_id=nuis.pixelmagic",
            "plan_id=pixelmagic.gray8.threshold-only",
            "stage_order=threshold",
            "stage.threshold.input_source=artifact",
            "stage.threshold.expected_bytes=0,0,15,15",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "pixelmagic-provider-registration-package-surface",
        path: "stdlib/pixelmagic/module.toml",
        required_patterns: &[
            "package_id = \"nuis.pixelmagic\"",
            "contract.pixelmagic.provider-sample-input-registration.v1",
            "contract.pixelmagic.filter-plan.v1",
            "provider_plan_catalog_contract",
            "provider_plan_default",
            "provider-plans/gray8-invert-threshold.nspf",
            "provider-plans/gray8-threshold.nspf",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "pixelmagic-artifact-provider-metadata-request",
        path: "examples/projects/domains/pixelmagic_pipeline_demo/nuis.toml",
        required_patterns: &[
            "artifact_provider_metadata",
            "@scope(domain=shader,trace=hetero-trace:shader:metal:apple-silicon-gpu)",
            "nuis.pixelmagic:filter-plan=pixelmagic.gray8.invert-threshold",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "artifact-provider-metadata-scope-protocol",
        path: "tools/nuisc/src/artifact_provider_metadata.rs",
        required_patterns: &[
            "nuis-artifact-provider-metadata-scope-v1",
            "domain_family",
            "trace_id",
            "project_artifact_provider_metadata_for_trace",
            "unscoped_entries_remain_global",
            "projection_keeps_order_and_strips_scope_envelopes",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "artifact-provider-metadata-runtime-scope-evidence",
        path: "tools/nuis/src/artifact_device_sample/scoped_metadata_tests.rs",
        required_patterns: &[
            "two_trace_scopes_select_independent_pixelmagic_plans",
            "pixelmagic.gray8.invert-threshold",
            "pixelmagic.gray8.threshold-only",
            "unscoped_metadata_remains_visible_to_every_trace",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "witsage-owned-output-comparison-profile",
        path: "stdlib/witsage/provider-comparison-profiles/cross-provider-f32.nwcp",
        required_patterns: &[
            "protocol=nuis-witsage-output-comparison-profile-v1",
            "package_id=nuis.witsage",
            "profile_id=witsage.cross-provider.f32",
            "absolute_tolerance=0.00001",
            "relative_tolerance=0.000001",
            "non_finite_policy=reject",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "witsage-owned-model-predict-comparison-profile",
        path: "stdlib/witsage/provider-comparison-profiles/model-predict-f32.nwcp",
        required_patterns: &[
            "protocol=nuis-witsage-output-comparison-profile-v1",
            "package_id=nuis.witsage",
            "profile_id=witsage.model-predict.f32",
            "absolute_tolerance=0.00001",
            "relative_tolerance=0.000001",
            "non_finite_policy=reject",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "witsage-output-comparison-profile-package-surface",
        path: "stdlib/witsage/module.toml",
        required_patterns: &[
            "package_id = \"nuis.witsage\"",
            "contract.witsage.output-comparison-profile.v1",
            "contract.witsage.cluster-assignment.v1",
            "provider_comparison_profiles",
            "provider-comparison-profiles/cross-provider-f32.nwcp",
            "provider-comparison-profiles/model-predict-f32.nwcp",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "witsage-output-comparison-profile-aot-parser",
        path: "tools/nuis/src/artifact_device_sample_witsage.rs",
        required_patterns: &[
            "nuis-witsage-output-comparison-profile-v1",
            "load_comparison_profile",
            "valid_non_zero_tolerance",
            "must reject non-finite values",
            "output_comparison_expected_content_hash",
            "output_comparison_profile_source_hash",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "witsage-non-zero-tolerance-official-evidence",
        path: "tools/nuis/tests/official_galaxy_hetero_smoke/build.rs",
        required_patterns: &[
            "provider_request_4_output_comparison_profile_id=witsage.cross-provider.f32",
            "provider_request_4_output_comparison_expected_content_hash=0xe31371394cd0b1bd",
            "provider_request_4_output_comparison_absolute_tolerance=0.00001",
            "provider_request_4_output_comparison_relative_tolerance=0.000001",
            "provider_request_4_output_comparison_non_finite_policy=reject",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "witsage-kmeans-native-output-evidence",
        path: "tools/nuis/tests/official_galaxy_hetero_smoke/provider_execution_evidence.rs",
        required_patterns: &[
            "native_output_5_request_id",
            "witsage.kmeans.centroid-score",
            "native_output_5_hash",
            "0xaa7b3732298c3952",
            "native_output_5_comparison_element_count",
            "native_output_5_comparison_mismatch_count",
            "native_output_6_request_id",
            "witsage.kmeans.assignment",
            "native_output_6_kind",
            "provider-scalar-u32",
            "nuis-metal-f32-argmax-provider-runner-v1",
            "native_output_6_hash",
            "0xad2aca7747985764",
            "native_output_6_comparison_element_count",
            "native_output_6_comparison_mismatch_count",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "pixelmagic-threshold-only-native-fixture",
        path: "examples/projects/domains/pixelmagic_threshold_provider_demo/nuis.toml",
        required_patterns: &[
            "pixelmagic_threshold_provider_demo",
            "nuis.pixelmagic:filter-plan=pixelmagic.gray8.threshold-only",
            "shader=shader.metal.msl2_4",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "pixelmagic-multi-plan-official-execution-evidence",
        path: "tools/nuis/tests/official_galaxy_hetero_smoke/provider_execution_evidence.rs",
        required_patterns: &[
            "pixelmagic_threshold_provider_demo",
            "provider_filter_plan_stage_count=1",
            "provider_request_dependency_edge_count = \\\"0\\\"",
            "native_output_0_hash = \\\"0x4d00177f9dae564b\\\"",
            "pixelmagic_pipeline_demo",
            "provider_request_dependency_edge_count = \\\"1\\\"",
            "native_output_1_hash = \\\"0xfc6f93a90d12d41b\\\"",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "std-tooling-doc-smoke-chain",
        path: "examples/projects/tooling/README.md",
        required_patterns: &[
            "cargo test -q -p nuis --test std_filesystem_smoke",
            "filesystem_io_report_demo",
            "cli_report_file_demo",
            "std-preprocessed PixelMagic input",
            "text_report_json_demo",
            "terminal/stdin/TTY",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "std-readme-host-io-text-lane",
        path: "stdlib/std/README.md",
        required_patterns: &[
            "beta-0.0.1",
            "host I/O and text",
            "filesystem/path/location",
            "worker lease",
            "supported Apple hosts",
            "lib/io_contracts.ns",
            "lib/text_contracts.ns",
            "lib/fs_contracts.ns",
            "lib/report_contracts.ns",
            "stdin_runtime_demo",
            "filesystem_io_report_demo",
            "cli_wc_demo",
            "cli_report_file_demo",
            "StdReportContracts",
            "argv -> file.read -> buffer",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "beta-0.0.1-mainline-entry",
        path: "docs/versioning/nuis-beta-0.0.1-mainline-entry.md",
        required_patterns: &[
            "first beta line",
            "early beta foundation hardening",
            "registered heterogeneous provider closure",
            "Nsld/NSB image",
            "Nsdb trace/replay",
            "fixed per-output Shader write extents",
            "development tensor",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "beta-0.0.1-mainline-router",
        path: "docs/current-mainline-map.md",
        required_patterns: &[
            "current `beta-0.0.1` reading route",
            "nuis-beta-0.0.1-mainline-entry.md",
            "direct predecessor `alpha-0.20.*` closeout entry",
            "predecessor `alpha-0.17.*` registered worker entry",
            "predecessor `alpha-0.16.*` tensor-guided closure entry",
            "nuis-development-tensor.md",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "beta-0.0.1-repository-frontdoor",
        path: "README.md",
        required_patterns: &[
            "now on `beta-0.0.1`",
            "registered Nuis worker / Nustar execution capsule",
            "verified heterogeneous output carrier",
            "registered heterogeneous provider closure",
            "shared Shader body contract",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "source-task-ready-delay-builtin",
        path: "tools/nuisc/src/frontend/task_builtins.rs",
        required_patterns: &[
            "\"ready_after\"",
            "NirExpr::CpuReadyAfter",
            "expects integer delay",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "source-task-ready-delay-lowering",
        path: "tools/nuisc/src/lowering/cpu_exprs.rs",
        required_patterns: &[
            "NirExpr::CpuReadyAfter",
            "lower_cpu_ready_after",
            "instruction: \"ready_after\"",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "scheduler-backed-task-result-lowering",
        path: "crates/yir-lower-llvm/src/async_resource_lowering.rs",
        required_patterns: &[
            "@nuis_scheduler_task_spawn_i64_v1",
            "@nuis_scheduler_task_spawn_invoker_i64_v1",
            "@nuis_scheduler_task_timeout_v1",
            "@nuis_scheduler_task_ready_after_v1",
            "@nuis_scheduler_task_cancel_v1",
            "@nuis_scheduler_task_join_state_v1",
            "@nuis_scheduler_task_value_i64_v1",
            "DeferredTaskThunkScalar",
            "arguments.len() * 8",
            "runtime_state",
            "runtime_handle",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "scheduler-task-invoker-wrapper",
        path: "crates/yir-lower-llvm/src/lib.rs",
        required_patterns: &[
            "render_scalar_task_invoker",
            "signature.params.iter().copied().enumerate()",
            "CpuCallScalarKind::F32",
            "CpuCallScalarKind::F64",
            "bitcast float %task_result to i32",
            "bitcast double %task_result to i64",
            "@nuis_task_invoker_",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "scheduler-backed-task-result-runtime",
        path: "tools/nuisc/src/aot_c_shim_runtime.rs",
        required_patterns: &[
            "nuis_scheduler_task_states[256]",
            "nuis_scheduler_task_spawn_i64_v1",
            "nuis_scheduler_task_spawn_invoker_i64_v1",
            "nuis_scheduler_task_timeout_v1",
            "nuis_scheduler_task_ready_after_v1",
            "nuis_scheduler_task_cancel_v1",
            "nuis_scheduler_task_join_state_v1",
            "nuis_scheduler_task_value_i64_v1",
            "NuisSchedulerTaskInvokerI64",
            "NuisSchedulerTaskThunkPacket",
            "NuisSchedulerOwnedPayloadV1",
            "nuis_scheduler_task_spawn_owned_v1",
            "nuis_scheduler_task_spawn_owned_invoker_v1",
            "nuis_scheduler_task_take_owned_v1",
            "nuis_scheduler_owned_payload_drop_v1",
            "nuis_scheduler_payload_free_v1",
            "nuis_scheduler_task_release_owned_payload_v1",
            "nuis_scheduler_task_thunk_packets[256]",
            "nuis_scheduler_task_execute_thunk_v1",
            "nuis_scheduler_task_release_context_v1",
            "nuis_lifecycle_tick_once_v1",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-registered-provider-request",
        path: "tools/nsdb/src/provider_request.rs",
        required_patterns: &[
            "nuis-provider-buffer-descriptor-v1",
            "nuis-provider-kernel-descriptor-v1",
            "ProviderBufferDescriptor",
            "ProviderKernelDescriptor",
            "ProviderScalarBinding",
            "provider_output_binding::{",
            "ProviderOutputBinding",
            "validate_output_bindings",
            "output_bindings",
            "element_type",
            "byte_length",
            "comparison_id",
            "PROVIDER_OUTPUT_COMPARISON_COLLECTION_CONTRACT",
            "output_comparisons",
            "provider_request_from_evidence",
            "parse_legacy_pixelmagic_request",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-registered-provider-request-regression",
        path: "tools/nsdb/src/provider_request_tests.rs",
        required_patterns: &[
            "parses_ordered_multi_output_bindings_with_compatibility_primary",
            "parses_output_comparison_collection_bound_to_distinct_outputs",
            "collection_dependency_selects_additional_output_semantics",
            "rejects_registered_descriptor_with_mismatched_buffer_binding",
            "output.audit",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-provider-output-comparison-collection",
        path: "tools/nsdb/src/provider_output_comparison_descriptor.rs",
        required_patterns: &[
            "PROVIDER_OUTPUT_COMPARISON_COLLECTION_CONTRACT",
            "parse_output_comparisons",
            "validate_output_comparisons",
            "comparison.id",
            "binding.comparison_id",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "scheduler-recursive-struct-owned-payload-lowering",
        path: "crates/yir-lower-llvm/src/task_owned_payload.rs",
        required_patterns: &[
            "emit_owned_struct_spawn",
            "emit_owned_struct_invoker_spawn",
            "emit_owned_struct_take",
            "stable_struct_type_id",
            "@nuis_scheduler_task_spawn_owned_v1",
            "@nuis_scheduler_task_spawn_owned_invoker_v1",
            "@nuis_scheduler_task_take_owned_v1",
            "@nuis_scheduler_owned_payload_drop_v1",
            "@nuis_scheduler_owned_aggregate_drop_v1",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-protected-file-trust-anchor-backend",
        path: "tools/nsdb/src/provider_completion_trust_anchor.rs",
        required_patterns: &[
            "NUIS_PROVIDER_COMPLETION_TRUST_ANCHOR_ROOT",
            "NUIS_PROVIDER_COMPLETION_TRUST_ANCHOR_MARKER_ROOT",
            "protected_path_is_rooted",
            "options.mode(0o600)",
            "AnchorCheck::Rollback",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-protected-file-trust-anchor-regression",
        path: "tools/nsdb/src/provider_completion_trust_anchor_tests.rs",
        required_patterns: &[
            "PermissionsExt::from_mode(0o700)",
            "protected_backend_ignores_deleted_ordinary_file_anchor_pair",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-independent-protected-file-trust-anchor-backend",
        path: "tools/nuis/src/artifact_nsdb_handoff_trust_anchor.rs",
        required_patterns: &[
            "NUIS_PROVIDER_COMPLETION_TRUST_ANCHOR_ROOT",
            "NUIS_PROVIDER_COMPLETION_TRUST_ANCHOR_MARKER_ROOT",
            "protected_path_is_rooted",
            "options.mode(0o600)",
            "AnchorCheck::Rollback",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-independent-protected-file-trust-anchor-regression",
        path: "tools/nuis/src/artifact_nsdb_handoff_trust_anchor_tests.rs",
        required_patterns: &[
            "PermissionsExt::from_mode(0o700)",
            "independent_protected_backend_ignores_deleted_ordinary_file_anchor_pair",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "owned-pointer-address-kind-native-smoke",
        path: "tools/nuis/tests/owned_pointer_select_smoke.rs",
        required_patterns: &[
            "address_kind=node",
            "address_kind=buffer",
            "nullable=true",
            "owned_transfer",
            "nullable=false",
            "nuis_fn_consume_transfer_left",
            "call void @free(ptr",
            "Some(94)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "owned-pointer-transfer-typed-yir-contract",
        path: "crates/yir-core/src/owned_select_tree.rs",
        required_patterns: &[
            "OwnedSelectTransferAddressKind",
            "address_kind=",
            "nullable=true",
            "nullable=false",
            "OwnedTransfer",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "owned-pointer-transfer-node-buffer-lowering",
        path: "tools/nuisc/src/lowering/tests_owned_pointer_transfer.rs",
        required_patterns: &[
            "lowers_explicit_node_and_buffer_transfer_metadata",
            "address_kind=node",
            "address_kind=buffer",
            "nullable=false",
            "deferred lowering for cpu.select_owned_bytes_tree",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "owned-pointer-transfer-cpu-metadata-validation",
        path: "crates/yir-domain-cpu/src/tests_owned_select_non_null.rs",
        required_patterns: &[
            "owned_select_tree_consumes_transfer_kind_and_nullability_metadata",
            "address_kind=buffer",
            "nullable=true",
            "null non-nullable buffer owned pointer transfer",
            "node pointer",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "language-bootstrap-result-task-smoke",
        path: "tools/nuis/tests/language_bootstrap_smoke.rs",
        required_patterns: &[
            "task_result_enum_project_anchors_language_bootstrap_smoke",
            "generic_trait_and_glm_buffer_projects_anchor_language_bootstrap_smoke",
            "generic_result_buffer_lambda_project_combines_language_bootstrap_features",
            "no_annotation_try_await_result_hof_project_anchors_language_bootstrap_smoke",
            "../../examples/projects/task/task_result_enum_demo",
            "../../examples/projects/task/task_no_annotation_try_await_result_hof_demo/main.ns",
            "../../examples/projects/task/task_no_annotation_try_await_result_hof_demo",
            "../../examples/projects/state/generic_method_bound_guarded_nested_match_demo",
            "../../examples/projects/state/glm_buffer_roundtrip_state_demo",
            "../../examples/projects/state/generic_result_buffer_lambda_helper_demo",
            "cpu.async_value",
            "__hof_result_map_raise_value__i64__i64__ErrorEnvelope",
            "__hof_result_map___lambda_build_report_0__i64__i64__HelperError",
            "__hof_result_map___lambda_build_report_2__i64__i64__HelperError",
            "ok__i64__HelperError(seed)",
            "Result<i64, ErrorEnvelope>",
            "enum Result<T, E>",
            "return Result.Err(error)",
            "if (seed == 3)",
            "err__i64__HelperError(HelperError.Invalid",
            "return Result.Err<i64, HelperError>",
            "trait Addable",
            "impl.Addable.for.i64.add(local, local)",
            "impl.Addable.for.i64.add(item, item)",
            "buffer_len(buffer)",
            "cpu.store_at",
            "edge lifetime",
            "cpu.variant_is",
            "cpu.task_completed",
            "policy=signature-whitelist-required",
            "task_result_enum_demo should execute the Result/task/error path",
            "generic Result/buffer/lambda helper binary",
            "__hof_map_result___lambda_compute_0__i64__i64__Error",
            "let mapped = map_result",
            "Result.Ok(await work(fetch(seed)?))",
            "let err_result: Result<i64, Error> = await compute_err_hof(5)",
            "no-annotation try/await Result HOF run-artifact json",
            "should execute Ok and Err paths",
            "59",
            "11",
        ],
    },
];
