use crate::dev_tensor_drift::DevTensorDriftCheckSpec;

pub(crate) const CHECKS: &[DevTensorDriftCheckSpec] = &[
    DevTensorDriftCheckSpec {
        id: "pixelmagic-color-run-break-source",
        path: "stdlib/pixelmagic/lib/pixels.ns",
        required_patterns: &[
            "pub struct PixelRunStats",
            "pub fn recolor_run(",
            "end > pixels.len || pixels.len > 4194304",
            "expected > 4294967295 || replacement < 0 || replacement > 4294967295",
            "if pixels[index] != expected { break; }",
            "pixels[index] = replacement",
            "end: index, written: written, checksum: checksum",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "pixelmagic-color-run-native-evidence",
        path: "tools/nuisc/tests/pixelmagic_buffer_loop/color_runs.rs",
        required_patterns: &[
            "recolor_run_matches_native_and_reference_boundaries_without_touching_the_tail",
            "scoped_call_i64_carries_break",
            "reference run statistics and every pixel",
            "native run statistics and every pixel",
            "invalid input and the nonmatching suffix must perform no writes",
            "write_and_link_with_source",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "pixelmagic-color-run-application-consumer",
        path: "examples/projects/domains/ns_nova_image_showcase/main.ns",
        required_patterns: &[
            "PixelMagicPixels.recolor_run(pixels, 0, 32, pixels[0], 4278255360)",
            "marker.end != 4 || marker.written != 4 || marker.checksum != 17113021440",
            "let snapshot: Bytes = copy_bytes(pixels)",
            "free(pixels)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "pixelmagic-color-run-packaged-evidence",
        path: "tools/nuis/tests/headless_image_loop.rs",
        required_patterns: &[
            "scoped_call_i64_carries_break",
            "packaged recoloring must retain driver-level break",
            "iterations=5 final=4 action cpu.scoped_call_i64_carries_break",
            "y < 5 && x < 20",
            "2 * (768 + 4 + 1)",
            "each callback exits at the first nonmatching pixel",
            "ApplicationProviderSource::Replay",
            "saved_stream",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "bounded-buffer-continue-admission",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/validation.rs",
        required_patterns: &[
            "control_flow::normalize(effects, scope, step)?",
            "writable.insert(normalized.running.clone())",
            "writable.extend(normalized.breaking.iter().cloned())",
            "normalized_effects.as_deref().unwrap_or(effects)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "bounded-buffer-continue-local-suffix",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/control_flow.rs",
        required_patterns: &[
            "__nuis_buffer_continue",
            "same_step(rewritten.last()?, step)",
            "index + 1 != body.len()",
            "body.insert(0, set_flag(&flag, 1))",
            "rewritten.push(set_flag(flag, 0))",
            "then_body: tail",
            "A child loop owns its control scope",
            "value == step",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "bounded-buffer-continue-execution",
        path: "tools/nuisc/tests/buffer_while/continues.rs",
        required_patterns: &[
            "guarded_continue_preserves_prefix_state_and_steps_once",
            "continue_unit_steps_do_not_wrap_at_integer_boundaries",
            "nested_and_sequential_continue_guards_snapshot_each_predicate_once",
            "continue_skips_suffix_reads_math_calls_and_nested_loop_bounds",
            "nested_continue_targets_only_its_own_loop_and_resets_each_iteration",
            "continue_rejects_missing_or_mismatched_steps_and_unsupported_exits",
            "continue_helpers_grow_linearly_and_keep_private_names_and_real_scalar_calls",
            "continue_effect_order_survives_yir_declaration_reordering",
            "continue_shares_session_fuel_without_leaking_private_or_failed_state",
            "let controls = 32",
            "state.fields.len(), 1",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "pixelmagic-guarded-continue-source",
        path: "stdlib/pixelmagic/lib/pixels.ns",
        required_patterns: &[
            "Finish red pixels early",
            "continue;",
            "let checksum: i64 = checksum + pixels[index]",
            "let index: i64 = index + 1",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "bounded-buffer-branch-carry-admission",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/validation.rs",
        required_patterns: &[
            "!header_inputs.contains(name)",
            "name != &prepared.binding_name",
            "!mutations.writable.contains(name)",
            "inputs.insert(name.clone())",
            "carries.push(name.clone())",
            "PreparedLoopCompare::Lt",
            "PreparedLoopCompare::Gt",
            "NirExpr::StoreAt",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "bounded-buffer-branch-state-projections",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/branches.rs",
        required_patterns: &[
            "Snapshot once",
            "scalar_carries::state_type",
            "scalar_carries::value",
            "inputs.extend(carries.iter().cloned())",
            "scalar_carries::projected_call",
            "NirStmt::Return(Some(returned.clone()))",
            "__nuis_branch_state",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "bounded-buffer-branch-pass-through-guard",
        path: "tools/nuisc/src/lowering/direct_calls/control_boundaries.rs",
        required_patterns: &[
            "is_pass_through_guard_seed",
            "i64_parameter",
            "fields.len() == definition.fields.len()",
            "type_name == &ty.name",
            "name == &field.name",
            "lower_guard_return",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "bounded-buffer-branch-carry-execution",
        path: "tools/nuisc/tests/buffer_while/branch_carries.rs",
        required_patterns: &[
            "branch_carries_preserve_untaken_and_zero_trip_seeds",
            "nested_branch_carries_merge_all_slots_and_preserve_sequential_rebindings",
            "branch_carry_predicate_is_snapshotted_before_state_and_buffer_updates",
            "branch_carry_traps_keep_source_order_before_and_after_writes",
            "branch_carries_reject_mutable_headers_non_i64_state_and_ownership_control",
            "branch_carries_share_callback_fuel_without_committing_failed_state",
            "branch_carries_keep_linear_helper_growth_and_generated_name_isolation",
            "branch_carries_feed_subsequent_loops",
            "let branches = 32",
            "completion_status().is_err()",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "pure-helper-analysis-expansion-budget",
        path: "tools/nuisc/src/lowering/loop_purity_inline_budget.rs",
        required_patterns: &[
            "MAX_INLINE_EXPR_NODES",
            "MAX_INLINE_EXPR_DEPTH",
            "checked_sub(cost)",
            "bounded_inline_substitution",
            "_ => return false",
            "inline_budget_counts_cast_depth_and_declines_unknown_shapes",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "pure-helper-analysis-expansion-evidence",
        path: "tools/nuisc/src/lowering/loop_purity_inline_tests.rs",
        required_patterns: &[
            "inline_collection_rejects_effectful_prefix_before_expansion",
            "inline_collection_bounds_pure_rebinding_expansion_without_losing_purity",
            "inline_collection_does_not_classify_effectful_return_as_pure",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "pixelmagic-branch-carry-native-evidence",
        path: "tools/nuisc/tests/pixelmagic_buffer_loop.rs",
        required_patterns: &[
            "real control boundary and branch-local count",
            "checkerboard_red_total",
            "row helpers must retain nested pixel loops",
            "checkerboard_row_start",
            "checkerboard_row_end",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "pixelmagic-branch-carry-packaged-evidence",
        path: "tools/nuis/tests/headless_image_loop.rs",
        required_patterns: &[
            "real control boundary and branch-local count",
            "checkerboard_red_total",
            "packaged row helpers must retain nested pixel loops",
            "checkerboard_row_start",
            "checkerboard_row_end",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "bounded-buffer-recursive-loop-admission",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/validation.rs",
        required_patterns: &[
            "protected.contains(&prepared.binding_name)",
            "protected.extend(header_inputs.iter().cloned())",
            "carries.retain(|name| scope.contains_key(name))",
            "&mutations.protected",
            "inputs.extend(plan.header_inputs)",
            ".filter(|name| plan.break_flag.as_ref() != Some(name))",
            ".chain([plan.induction])",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "bounded-buffer-recursive-loop-outlining",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/branches.rs",
        required_patterns: &[
            "validated nested loop",
            "outline_loop(",
            "carries.retain(|name| scope.contains_key(name))",
            "NirStmt::While { body, .. } => collect_bindings(body, names)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "bounded-buffer-recursive-loop-evidence",
        path: "tools/nuisc/tests/buffer_while/nested_loops.rs",
        required_patterns: &[
            "nested_buffer_loops_execute_real_helpers_and_reset_iteration_locals",
            "nested_loops_preserve_persistent_counters_and_support_scalar_only_children",
            "nested_descending_loops_and_outer_dependent_bounds_keep_exact_state",
            "branch_nested_loops_return_visible_locals_without_speculating_bounds",
            "nested_loop_traps_keep_source_order_across_loop_boundaries",
            "nested_loops_reject_ancestor_header_mutation_and_unsupported_control",
            "nested_loops_share_session_fuel_and_never_commit_failed_callback_state",
            "recursive_loops_retain_scalar_callees_and_linear_helper_growth",
            "let depth = 8",
            "native_run",
            "event_budgeted",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-helper-declared-result-fallback",
        path: "crates/yir-lower-llvm/src/lib.rs",
        required_patterns: &[
            ".and_then(|function| function.result.as_ref())",
            ".map(|result| result.node.as_str())",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "bounded-buffer-break-source-provenance",
        path: "tools/nuisc/src/lowering/scoped_loop_lowering.rs",
        required_patterns: &[
            "scoped_break_controls",
            "Only the normalizer proves",
            "A user struct with the same shape",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "bounded-buffer-break-shared-contract",
        path: "crates/yir-core/src/loop_carry_contract/scoped_scalars.rs",
        required_patterns: &[
            "scoped_call_i64_carries_break",
            "pub break_on_return: bool",
            "break_control_can_be_the_only_carried_slot",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "bounded-buffer-break-driver",
        path: "crates/yir-domain-cpu/src/execute_scoped_loop.rs",
        required_patterns: &[
            "scoped loop break flag requires an i64 zero seed",
            "scoped loop break flag must be i64 0 or 1",
            "if !self.exited",
            "if self.exited || !active",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "bounded-buffer-break-native-control",
        path: "crates/yir-lower-llvm/src/simple_loop_lowering.rs",
        required_patterns: &[
            "scoped_call_i64_carries_break",
            "carry.store_return(pointer_bits, body, next_reg, next_block)?",
            "loop_while_i64_advance",
            "label %{loop_exit}, label %{advance}",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "bounded-buffer-break-native-validation",
        path: "crates/yir-lower-llvm/src/loop_owned_struct_lowering.rs",
        required_patterns: &[
            "require_control_value(initial, 0, body, next_reg, next_block)",
            "require_control_value(raw, 1, body, next_reg, next_block)",
            "loop_break_control_invalid",
            "before committing any of the returned carries",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "bounded-buffer-break-execution",
        path: "tools/nuisc/tests/buffer_while/breaks.rs",
        required_patterns: &[
            "break_preserves_current_and_prefix_effects_without_user_scalar_carries",
            "break_commits_all_scalar_carries_and_does_not_run_the_remaining_iterations",
            "break_skips_suffix_traps_calls_and_child_bounds_but_not_prefix_effects",
            "nested_break_exits_only_its_loop_and_keeps_the_child_exit_counter",
            "break_and_explicit_step_continue_have_distinct_nested_guard_semantics",
            "break_rejects_unmodeled_induction_mutations_and_nonterminal_exits",
            "break_keeps_effect_order_after_yir_declaration_reordering",
            "break_uses_shared_session_fuel_and_never_exports_its_private_control_slot",
            "break_contract_keeps_glm_inputs_and_rejects_payload_or_zero_trip_seed_drift",
            "break_helpers_have_linear_growth_private_names_and_one_time_predicates",
            "malformed_return_control_traps_in_native_and_reference_execution",
            "index < 1000000000000",
            "event_budgeted",
            "native_run",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nir-branch-constant-state-join",
        path: "tools/nuisc/src/optimize.rs",
        required_patterns: &[
            "Only the enclosing block knows",
            "*env = then_env",
            "*env = else_env",
            "then_env.get(name) == Some(value) && else_env.get(name) == Some(value)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "owned-cleanup-return-layout",
        path: "crates/yir-lower-llvm/src/guard_return_lowering/cleanup_return.rs",
        required_patterns: &[
            "Both arms must have a valid ABI before emitting either branch or cleanup",
            "materialize_owned_value(pair[1], &template)",
            "aggregate value requires a function return layout",
            "return value contains the Bytes being dropped",
            "emit_owned_struct_return(value, body, next_reg)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "owned-cleanup-return-native-reference-proof",
        path: "tools/nuisc/tests/owned_cleanup_return.rs",
        required_patterns: &[
            "native_nested_aggregate_cleanup_returns_preserve_both_paths_and_release_blobs",
            "guard_drop_owned_bytes_return",
            "branch_drop_owned_bytes_return",
            "function.body_nodes.reverse()",
            "reference cleanup return paths",
            "nuis_scheduler_owned_blob_live_count_get_v1",
            "write_and_link_with_source",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "registered-function-exit-contract",
        path: "crates/yir-core/src/registry.rs",
        required_patterns: &[
            "fn function_exit(",
            "exits only that invocation",
            "must not execute work or reset fuel",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "registered-function-exit-dispatch",
        path: "crates/yir-exec/src/execution_engine.rs",
        required_patterns: &[
            "module.function_exit(node, self.resources[&node.resource], &self.state)?",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "registered-function-exit-proof",
        path: "crates/yir-exec/tests/registered_execution.rs",
        required_patterns: &[
            "registered_function_exit_skips_tail_and_returns_only_from_the_nested_invocation",
            "registered_function_exit_errors_propagate_without_fallback_or_retry",
            "exit_probe.stop",
            "step budget exhausted",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "owned-cleanup-terminal-source-result",
        path: "tools/nuisc/src/lowering/if_lowering.rs",
        required_patterns: &[
            "let returned = lower_branch_drop_owned_bytes_return(",
            "push_dep_edges(state, &returned, &selected)",
            "return Ok(LoweredIfOutcome::Returned(selected))",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nir-branch-constant-state-join-evidence",
        path: "tools/nuisc/src/optimize_branch_tests.rs",
        required_patterns: &[
            "dynamic_branch_invalidates_rebound_literals_without_pruning_live_arm_state",
            "selected_constant_branch_uses_its_outgoing_environment",
            "nested_loop_mutation_invalidates_the_enclosing_branch_literal",
            "dynamic_branch_keeps_unchanged_literals_without_leaking_branch_locals",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-scalar-session-bridge-api",
        path: "crates/yir-lower-llvm/src/native_session/mod.rs",
        required_patterns: &[
            "pub fn emit_registered(",
            "crate::emit_native_scalar_module(&selected)",
            "yir_core::native_scalar_session",
            "pub state_layout: ScalarStateLayout",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-scalar-session-shared-values",
        path: "crates/yir-core/src/native_scalar_session.rs",
        required_patterns: &[
            "nuis-native-scalar-session-bridge-v1",
            "pub const MAX_SCALAR_SLOTS: usize = 64",
            "noncanonical scalar word",
            "pub struct ScalarStateLayout",
            "shared_layout_reconstructs_nested_nominal_state_without_losing_float_bits",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-scalar-session-host-binding",
        path: "crates/yir-runtime-host/src/native_application_session.rs",
        required_patterns: &[
            "pub unsafe fn from_static(",
            "self.module != module || self.id != id",
            "artifact identity mismatch",
            "self.layout.unpack(&output)?",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-scalar-session-host-policy",
        path: "crates/yir-runtime-host/src/application_session/execution.rs",
        required_patterns: &[
            "Reference(FunctionSession",
            "Native(NativeSessionBindings",
            "reference-executor fuel cannot preempt a native session callback",
            "Self::Native(binding) => binding.invoke",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-scalar-session-production-entry",
        path: "crates/yir-runtime-host/src/native_application_session/entry.rs",
        required_patterns: &[
            "pub struct NativeSessionDescriptorV1",
            "if module != compiled_module",
            "ApplicationSession::open_native_registered",
            "session.completion_status()?",
            "pub unsafe extern \"C\" fn nuis_native_application_script_main",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-scalar-session-production-proof",
        path: "tools/nuisc/tests/native_application_host.rs",
        required_patterns: &[
            "packaged_native_session_uses_shared_host_without_reference_fallback",
            "--native-session",
            "unreachable_callback_body",
            "cleanup must use last accepted state",
            "artifact identity mismatch",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-scalar-session-host-failure-proof",
        path: "crates/yir-runtime-host/src/native_application_session/tests.rs",
        required_patterns: &[
            "native_host_admits_arguments_and_rejects_reference_fuel_before_entry",
            "native_event_failure_retains_last_state_and_cannot_turn_cleanup_into_success",
            "malformed_native_output_and_failed_close_never_publish_partial_state_or_retry",
            "native_static_descriptor_rejects_drift_and_bad_scripts_before_any_callback",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-scalar-session-bridge-admission",
        path: "crates/yir-lower-llvm/src/native_session/admission.rs",
        required_patterns: &[
            "ApplicationSessionSignature::bind",
            "callback return layouts disagree",
            "calls::validate_graph(&graph)",
            "MAX_TOTAL_NODES",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-scalar-session-function-admission",
        path: "crates/yir-lower-llvm/src/native_session/function.rs",
        required_patterns: &[
            "parameter node/signature drift",
            "requires external initialization or cross-function values",
            "one declared typed return",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-scalar-session-call-closure",
        path: "crates/yir-lower-llvm/src/native_session/calls.rs",
        required_patterns: &[
            "MAX_FUNCTIONS: usize = 64",
            "MAX_CALL_DEPTH: usize = 32",
            "helper signature drift",
            "rejects recursive helper call cycles",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-scalar-session-helper-proof",
        path: "tools/nuisc/tests/native_application_bridge/helpers.rs",
        required_patterns: &[
            "acyclic_scalar_helpers_execute_with_typed_native_reference_parity",
            "reachable_helpers_reject_signature_lane_effect_and_dependency_drift",
            "selected_call_graph_is_bounded_acyclic_and_ignores_unreachable_effects",
            "strict_native_helpers_reject_implicit_scalar_coercions_and_unmaterialized_values",
            "reachable_helper_node_limits_apply_to_each_body_and_the_whole_closure",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-scalar-session-exact-helper-values",
        path: "crates/yir-lower-llvm/src/function_lowering/strict_scalar.rs",
        required_patterns: &[
            "lower_scalar_value_arg",
            "exactly match its declared scalar kind",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-scalar-session-counted-loop-admission",
        path: "crates/yir-lower-llvm/src/native_session/loops.rs",
        required_patterns: &[
            "MAX_ITERATIONS: i128 = 65536",
            "fn constant_inputs",
            "finite non-wrapping induction",
            "does not admit this scalar carry source",
            "counted_loop_proof_matches_small_independent_step_simulation",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-scalar-session-counted-loop-proof",
        path: "tools/nuisc/tests/native_application_bridge/loops.rs",
        required_patterns: &[
            "counted_scalar_loops_compose_with_native_helpers_and_reference_state",
            "native_counted_loops_reject_hidden_effects",
            "native_counted_loops_reject_induction_and_carry_drift",
            "plain_loop_reference_fuel_exhaustion_retains_the_accepted_session_state",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-scalar-session-dynamic-loop-admission",
        path: "crates/yir-lower-llvm/src/native_session/loops/dynamic.rs",
        required_patterns: &[
            "native_loop_preflight",
            "select i1 {nonzero}, i64 {magnitude}, i64 1",
            "udiv i64",
            "icmp ule i128 {trips}, {MAX_ITERATIONS}",
            "call void @llvm.trap()",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-scalar-session-dynamic-loop-parity",
        path: "tools/nuisc/tests/native_application_bridge/dynamic_loops.rs",
        required_patterns: &[
            "dynamic_scalar_loops_preserve_native_reference_and_typed_helper_parity",
            "dynamic_bound_may_share_a_carry_seed_without_duplicate_effect_edges",
            "assert_native_parity(DYNAMIC, true)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-scalar-session-dynamic-loop-guard-proof",
        path: "tools/nuisc/tests/native_application_bridge/dynamic_loop_guard.rs",
        required_patterns: &[
            "dynamic_loop_guard_matches_checked_simulation_before_any_iteration",
            "invalid_dynamic_induction_traps_instead_of_returning_a_callback_error",
            "dynamic_induction_rejects_implicit_boolean_bounds",
            "checked_add(step)",
            "checked_sub(step)",
            "Duration::from_secs(10)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "cpu-plain-scalar-chain-execution-proof",
        path: "crates/yir-domain-cpu/tests/scalar_flow_execution.rs",
        required_patterns: &[
            "plain_scalar_chain_is_cooperative_and_returns_source_ordered_carries",
            "plain_scalar_chain_carry_overflow_wraps_and_invalid_kinds_fail_closed",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-scalar-session-bridge-emission",
        path: "crates/yir-lower-llvm/src/native_session/emit.rs",
        required_patterns: &[
            "%counts_ok = and i1 %argc_ok, %outc_ok",
            "label %bad_scalar",
            "nuis_scheduler_owned_aggregate_get_v1",
            "nuis_scheduler_owned_aggregate_drop_v1",
            "store i64 %result",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-scalar-session-materialization",
        path: "crates/yir-lower-llvm/src/function_lowering.rs",
        required_patterns: &[
            "require_scalar_values: bool",
            "required_values.push(node.name.as_str())",
            "native scalar callback did not materialize value",
            "native scalar callback did not emit a terminal return",
            "native_session::loops::emit_guard",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-scalar-session-execution-proof",
        path: "tools/nuisc/tests/native_application_bridge.rs",
        required_patterns: &[
            "registered_scalar_callbacks_execute_natively_without_main_replay_or_interpreter",
            "native_bridge_rejects_signature_layout_lane_and_initialization_drift",
            "scalar_words_reject_noncanonical_encodings_without_losing_float_bits",
            "did not materialize value",
            "0x7ff8_0000_0000_4321",
            "write_and_link_with_source",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-scalar-session-boundaries-proof",
        path: "tools/nuisc/tests/native_application_bridge/bounds.rs",
        required_patterns: &[
            "native_bridge_accepts_the_slot_bound_and_rejects_larger_signatures",
            "zero_argument_native_open_accepts_null_input_without_accessing_it",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-float-parameter-binding",
        path: "crates/yir-lower-llvm/src/param_lowering.rs",
        required_patterns: &[
            "mismatched LLVM binding",
            "floating_parameters_remain_typed_and_never_convert_to_fallback_integers",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-frontdoor-launch",
        path: "tools/nuis/src/artifact_runtime_native_session.rs",
        required_patterns: &[
            "verify_nuis_compiled_artifact",
            "validate_native_application_script",
            "native launch binary does not match",
            "no fallback was attempted",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-frontdoor-checkpoint",
        path: "tools/nuisc/src/aot_native_session.rs",
        required_patterns: &[
            "native-session-aot-bundle:",
            "emit_registered(module, id)",
            "bridge.llvm_ir != llvm_ir",
            "native_session_layout",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-session-frontdoor-relocation-proof",
        path: "tools/nuis/tests/native_session_workflow.rs",
        required_patterns: &[
            "native_build_run_artifact_cache_and_standalone_relocation",
            "compile_cache: hit",
            "fs::remove_dir_all(&output)",
            "materialize-artifact",
            "rejected_before_open",
            "native_loop_preflight",
            "dynamic_loops.ns",
        ],
    },
];
