use crate::dev_tensor_drift::DevTensorDriftCheckSpec;

pub(super) const CHECKS: &[DevTensorDriftCheckSpec] = &[
    DevTensorDriftCheckSpec {
        id: "native-return-signal-bounded-original-tree-admission",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_signal.rs",
        required_patterns: &[
            "terminal::partial_inputs(body, result, scope, catalog, layouts)?",
            "let mut has_return = false",
            "let mut continues = false",
            "Some(NirStmt::Return(Some(_))) => has_return = true",
            "continues.then_some(Arm { inputs, has_return })",
            "Only validated bounded terminal trees reach this rewrite",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-signal-private-independent-once-only-value-and-exit",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_signal.rs",
        required_patterns: &[
            "visibility: NirVisibility::Private",
            "(\"exited\", scalar_type(\"bool\")), (\"value\", result.clone())",
            "short-circuit outliner can guard their RHS before construction",
            "branches::fresh_name(\"__nuis_return_leaf\", bindings)",
            "body.push(returned(signal, true, NirExpr::Var(name)))",
            "body.push(returned(signal, false, seed))",
            "branches::fresh_name(\"__nuis_return_snapshot\", bindings)",
            "value: field(\"value\")",
            "value: field(\"exited\")",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-signal-original-leaves-not-replay-seeds",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns.rs",
        required_patterns: &[
            "mod signal;",
            "signal::prepare(body, result, scope, catalog, layouts)?",
            "has_return |= arm.has_return",
            "if !has_return",
            ".is_some_and(|ty| return_values::capture(result, ty))",
            "Wrap original leaves, never the other proof's synthetic scalar seeds",
            "yes = (!then_body.is_empty()).then(|| then_body.to_vec())",
            "plan.yes.unwrap_or_default()",
            "plan.no.unwrap_or_default()",
            "signal::read(call, &returned, result, bindings)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-signal-layout-refresh-before-shared-control-lowering",
        path: "tools/nuisc/src/lowering/buffer_loop_outline.rs",
        required_patterns: &[
            "let mut value_layouts = control_values::TypedLayouts::collect(module)",
            "Stored return signals introduce private typed result layouts",
            "layouts = control_values::layouts(module)",
            "value_layouts = control_values::TypedLayouts::collect(module)",
            "scalar_helpers::collect_typed_values(module, &value_layouts, &control_catalog)",
            "selections.extend(conditional_values::outline(",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-signal-reference-once-only-structure-and-budget-proofs",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_signal_tests.rs",
        required_patterns: &[
            "conditional_return_stored_signals_evaluate_predicates_once_before_exits_or_continuations",
            "assert_eq!(cases, 288)",
            "conditional_return_stored_signals_distinguish_real_zero_and_false_from_fallthrough",
            "conditional_return_stored_signals_preserve_nested_siblings_mixed_arms_and_current_captures",
            "let divisor = divisor + 2",
            "conditional_return_stored_signals_publish_one_private_snapshot_and_preserve_leaf_work",
            "assert_eq!(module, once)",
            "conditional_return_stored_signals_share_preflight_and_retain_effect_scope_and_capture_vetoes",
            "for count in [30, 31]",
            "conditional_return_stored_signals_bound_all_original_condition_and_leaf_nodes",
            "for over in [false, true]",
            "for _ in 0..64",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-signal-default-source-binaries-and-reached-traps",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_returns_signal_native_tests.rs",
        required_patterns: &[
            "conditional_return_stored_signals_execute_default_aot_computed_exits_and_continuations",
            "conditional_return_stored_signals_execute_default_aot_zero_results_and_parent_traps",
            "tests::native::run",
            "Some(\"99\\n77\\n19\")",
            "Some(\"99\\n0\")",
            "\"call\"",
            "\"alias\"",
            "\"inline-field\"",
            "\"division\"",
            "helper(produce(0))",
            "(\"||\", false, None)",
            "run(&source, expected)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-signal-documented-independent-proof-and-boundaries",
        path: "docs/reference/nuis-native-scalar-loop-snapshots-v1.md",
        required_patterns: &[
            "## Stored Exit Signals For Partial Return Trees",
            "Eight compiler tests cover 334 runtime source cases and 668 ordinary/reversed",
            "Twenty default-source AOT variants",
            "The parent stores the complete helper result exactly once",
            "short-circuit expression directly inside a record field can eagerly lower its",
            "No source/public/FFI/callback ABI, native word limit",
            "Logical outer gates and other inline conditions",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-return-signal-tensor-receipt-and-scope",
        path: "tools/nuis/src/dev_tensor_data.rs",
        required_patterns: &[
            "Stored partial-tree exit-signal follow-up:",
            "Stored partial-tree exit-signal acceptance:",
            "conditional_return_stored_signals",
            "334 runtime source cases and 668 ordinary/reversed reference executions",
            "private typed snapshot",
            "no predicate replay",
            "active/87",
        ],
    },
];
