use crate::dev_tensor_drift::DevTensorDriftCheckSpec;

pub(crate) const DEV_TENSOR_RUNTIME_DRIFT_CHECKS: &[DevTensorDriftCheckSpec] = &[
    DevTensorDriftCheckSpec {
        id: "workflow-surface-json-regression",
        path: "tools/nuis/src/main_tests/workflow_surface.rs",
        required_patterns: &[
                "nsld_final_executable_output_boundary_status",
                "nsld_final_executable_output_materialization_status",
                "nsld_final_executable_output_execution_handoff_contract",
                "nsld_final_executable_output_execution_handoff_ready",
                "nsld_final_executable_output_execution_handoff_status",
                "nsld_final_executable_output_execution_handoff_target",
                "nsld_final_executable_output_execution_handoff_evidence_status",
                "nsld_final_executable_output_execution_handoff_first_blocker",
                "nsld_final_executable_output_execution_handoff_decision_code",
                "nsld_final_executable_output_payload_execution_trace_protocol",
                "nsld_final_executable_output_payload_execution_trace_available",
                "nsld_final_executable_output_payload_execution_trace_record_count",
                "nsld_final_executable_output_payload_execution_trace_ready_record_count",
                "nsld_final_executable_output_nsdb_replay_contract",
                "nsld_final_executable_output_nsdb_replay_ready",
                "nsld_final_executable_output_nsdb_replay_status",
                "nsld_final_executable_output_nsdb_replay_checkpoint_count",
                "nsld_final_executable_output_nsdb_replayable_checkpoint_count",
                "nsld_final_executable_output_nsdb_replay_command",
                "nsld_final_executable_output_nsdb_replay_next_action",
                "nsld_final_executable_output_nsdb_replay_next_command",
                "nsld_final_executable_output_nsdb_replay_first_blocker",
                "nsld_final_executable_pipeline_execution_handoff_contract",
                "nsld_final_executable_pipeline_execution_handoff_ready",
                "nsld_final_executable_pipeline_execution_handoff_status",
                "nsld_final_executable_pipeline_execution_handoff_target",
                "nsld_final_executable_pipeline_execution_handoff_evidence_status",
                "nsld_final_executable_pipeline_execution_handoff_first_blocker",
                "nsld_final_executable_pipeline_execution_handoff_decision_code",
                "workflow_run_artifact_prelaunch_kind",
                "workflow_run_artifact_prelaunch_status",
                "workflow_run_artifact_prelaunch_evidence_status",
                "workflow_run_artifact_prelaunch_command",
                "workflow_run_artifact_prelaunch_reason",
                "closure_summary_source",
                "closure_summary_status",
                "closure_summary_ready",
                "closure_summary_primary_blocker",
                "closure_summary_next_action",
                "closure_summary_next_command",
                "safe_next_contract",
                "safe_next_probe_json_command",
                "safe_next_gate_required_field",
                "safe_next_gate_action_field",
                "workflow_launch_evidence_protocol",
                "workflow_launch_evidence_debugger_contract",
                "workflow_launch_evidence_host_runner_probe_status",
                "workflow_nsdb_handoff_available",
                "link_plan_heterogeneous_backend_artifact_units",
                "link_plan_heterogeneous_backend_artifact_ready_units",
                "link_plan_heterogeneous_backend_artifact_first_unready",
                "nsld_final_executable_output_recommended_next_action",
                "nsld_final_executable_output_object_valid",
                "nsld_final_executable_output_object_family",
                "nsld_final_executable_output_object_magic_status",
            "nsld_final_executable_output_object_magic",
                "nsld_final_executable_output_object_expected_hash",
                "nsld_final_executable_output_object_actual_hash",
                "nsld_final_executable_output_object_issues",
                "nsld_self_owned_image_status",
                "nsld_backend_artifact_payload_evidence_available",
                "nsld_backend_artifact_payload_count",
                "nsld_backend_artifact_payload_role_status",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "project-frontdoor-closure-summary",
        path: "tools/nuis/src/main_tests/project_health.rs",
        required_patterns: &[
            "closure_summary_source",
            "closure_summary_status",
            "closure_summary_ready",
            "closure_summary_primary_blocker",
            "closure_summary_next_action",
            "closure_summary_next_command",
            "safe_next_contract",
            "safe_next_probe_json_command",
            "safe_next_gate_required_field",
            "project-status-link-plan",
            "prepared artifact chain is missing `link-inputs`",
            "project-status",
            "project-doctor",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "project-frontdoor-link-plan-closure-summary",
        path: "tools/nuis/src/surface_render/project_closure.rs",
        required_patterns: &[
            "project_closure_summary",
            "link_plan_source",
            "nsld_prepared_artifact_chain_summary",
            "nsld_drive_recommendation_for_output_dir",
            "with_nsld_drive_safe_next",
            "nsld_final_executable_tail_summary",
            "from_nsld_final_output_closure",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "frontdoor-closure-summary-final-output-replay-gate",
        path: "tools/nuis/src/closure_summary.rs",
        required_patterns: &[
            "from_nsld_final_output_closure",
            "with_nsld_drive_safe_next",
            "nsld-drive-safe-next",
            "nsld-drive-safe-next-v1 gate required",
            "run-artifact-or-replay-nsdb",
            "inspect-nsdb-replay-evidence",
            "replay evidence is blocked",
            "final_output.nsdb_replay_ready",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "frontdoor-closure-summary-canonical-doc",
        path: "docs/reference/nuis-frontdoor-surface-reference.md",
        required_patterns: &[
            "canonical human closure summary",
            "read this group first",
            "closure_summary_primary_blocker",
            "closure_summary_next_action",
            "Reading order",
            "dev_tensor_weakest_task_card_coordinate",
            "dev_tensor_weakest_task_card_handoff_coordinate",
            "which bootstrap coordinate should we push",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-artifact-workflow-closure-summary-reading-rule",
        path: "docs/reference/nuis-native-artifact-workflow.md",
        required_patterns: &[
            "canonical human closure line",
            "workflow",
            "project-status",
            "project-doctor",
            "read it before drilling",
            "dev_tensor_weakest_task_card_*",
            "dev_tensor_weakest_task_card_handoff_*",
            "artifact closure work and tensor-driven",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "workflow-object-output-identity-mirror",
        path: "tools/nuis/src/workflow/object_identity.rs",
        required_patterns: &[
            "workflow_object_identity_mirrors_nsld_object_magic_families",
            "workflow_object_identity",
            "object_family_for_format",
            "object_magic_status",
            "object_magic_hex",
            "0xcffaedfe",
            "0x7f454c46",
            "0x6486",
        ],
    },
    DevTensorDriftCheckSpec {
            id: "artifact-runtime-json-regression",
            path: "tools/nuis/src/main_tests/artifact_runtime.rs",
            required_patterns: &[
                "nsld_final_executable_output_boundary_status",
                "nsld_final_executable_output_materialization_status",
                "nsld_final_executable_output_execution_handoff_contract",
                "nsld_final_executable_output_execution_handoff_ready",
                "nsld_final_executable_output_execution_handoff_status",
                "nsld_final_executable_output_execution_handoff_target",
                "nsld_final_executable_output_execution_handoff_evidence_status",
                "nsld_final_executable_output_execution_handoff_first_blocker",
                "nsld_final_executable_output_execution_handoff_decision_code",
                "nsld_final_executable_output_payload_execution_trace_protocol",
                "nsld_final_executable_output_payload_execution_trace_available",
                "nsld_final_executable_output_payload_execution_trace_record_count",
                "nsld_final_executable_output_payload_execution_trace_ready_record_count",
                "nsld_final_executable_pipeline_execution_handoff_contract",
                "nsld_final_executable_pipeline_execution_handoff_ready",
                "nsld_final_executable_pipeline_execution_handoff_status",
                "nsld_final_executable_pipeline_execution_handoff_target",
                "nsld_final_executable_pipeline_execution_handoff_evidence_status",
                "nsld_final_executable_pipeline_execution_handoff_first_blocker",
                "nsld_final_executable_pipeline_execution_handoff_decision_code",
                "nsld_final_executable_output_recommended_next_action",
                "nsld_self_owned_image_status",
                "run_artifact_prelaunch_kind",
                "run_artifact_prelaunch_status",
                "run_artifact_prelaunch_evidence_status",
                "run_artifact_prelaunch_runner_command_present",
                "run_artifact_prelaunch_entrypoint_present",
                "run_artifact_prelaunch_entrypoint_protocol",
                "run_artifact_prelaunch_entrypoint_protocol_valid",
                "nsld-host-entrypoint",
                "artifact_closure_kind",
                "artifact_closure_status",
                "artifact_closure_evidence_status",
                "artifact_closure_runner_command_present",
                "artifact_closure_entrypoint_present",
                "artifact_closure_entrypoint_protocol",
                "artifact_closure_entrypoint_protocol_valid",
                "artifact_launch_evidence_protocol",
                "artifact_launch_evidence_debugger_contract",
                "artifact_launch_evidence_host_runner_probe_status",
                "artifact_nsdb_handoff_available",
                "artifact_nsdb_handoff_protocol",
                "artifact_nsdb_handoff_record_count",
                "nsld_backend_artifact_payload_evidence_available",
                "nsld_backend_artifact_payload_count",
                "nsld_backend_artifact_payload_role_status",
                "nsld_backend_artifact_payload_ids",
                "nsld_backend_artifact_payload_kinds",
                "artifact_launch_evidence_backend_artifact_payload_evidence_available",
                "artifact_launch_evidence_backend_artifact_payload_count",
                "artifact_launch_evidence_backend_artifact_payload_role_status",
                "launch_evidence_backend_artifact_payload_evidence_available",
                "launch_evidence_backend_artifact_payload_count",
                "launch_evidence_backend_artifact_payload_role_status",
                "host_runner_backend_artifact_payload_count",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "artifact-doctor-metadata-mirrors",
            path: "tools/nuis/src/artifact_doctor_mirrors.rs",
            required_patterns: &[
                "collect_payload_decoder_manifest_mirror",
                "collect_device_provider_sample_manifest_mirror",
                "collect_backend_artifact_payload_evidence",
                "PayloadDecoderManifestMirror",
                "DeviceProviderSampleManifestMirror",
                "BackendArtifactPayloadEvidence",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "artifact-runtime-run-artifact-json-regression",
            path: "tools/nuis/src/main_tests/artifact_runtime_run_artifact.rs",
            required_patterns: &[
                "repair_provider_output_payload",
                "hetero_runtime_trace_device_sample_handoff_status",
                "device_provider_sample_manifest_persisted",
                "materialize_provider_samples",
                "nsdb materialize-provider-samples",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "run-artifact-hetero-runtime-trace-surface",
            path: "tools/nuis/src/artifact_runtime_trace.rs",
            required_patterns: &[
                "HeteroRuntimeTraceSummary",
                "nsdb-yir-hetero-runtime-trace-v1",
                "hetero_runtime_trace_available",
                "hetero_runtime_trace_status",
                "hetero_runtime_trace_payload_evidence_available",
                "hetero_runtime_trace_domain_families",
                "HeteroRuntimeTraceRecord",
                "trace_record_for_unit",
                "persist_nsdb_trace",
                "backend-artifact",
                "domain-metadata",
                "artifact_device_sample",
                "DEVICE_PROVIDER_SAMPLE_FILE_NAME",
                "render_device_provider_sample_manifest_toml",
                "handoff-to-nsdb-trace",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "run-artifact-host-runner-probe-surface",
            path: "tools/nuis/src/artifact_runtime_command.rs",
            required_patterns: &[
                "run_artifact_host_runner_surface",
                "HostRunnerJsonSurface",
                "run_nsld_host_runner",
                "try_run_nsld_host_runner",
                "resolve_nuis_host_runner_program",
                "from_surfaces_with_backend_payload_evidence",
                "HeteroRuntimeTraceSummary",
                "persist_launch_evidence_nsdb_handoff",
                "nuis-host-runner",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "run-artifact-nsdb-handoff-persistence",
            path: "tools/nuis/src/artifact_nsdb_handoff.rs",
            required_patterns: &[
                "nuis-nsdb-payload-execution-handoff-v1",
                "nuis.nsdb.payload-execution-handoff.toml",
                "persist_launch_evidence_nsdb_handoff",
                "launch_evidence_nsdb_handoff_persisted",
                "launch_evidence_nsdb_handoff_record_count",
                "launch_evidence_nsdb_handoff_ready_record_count",
                "launch_evidence_nsdb_handoff_first_trace_id",
                "run-artifact-launch-evidence",
                "hetero_execution_closure_protocol",
                "hetero_execution_closure_next_action",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "nsdb-payload-execution-handoff-consumer",
            path: "tools/nsdb/src/handoff.rs",
            required_patterns: &[
                "nuis.nsdb.payload-execution-handoff.toml",
                "nuis-nsdb-payload-execution-handoff-v1",
                "nsdb-yir-payload-execution-trace-v1",
                "read_payload_execution_handoff",
                "payload_handoff_status",
                "parse_payload_execution_events",
                "NsdbPayloadExecutionEvent",
                "hetero_execution_closure_status",
                "hetero_execution_closure_ready",
                "handoff-hetero-execution-evidence-to-nsdb",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "nsdb-inspect-payload-handoff-surface",
            path: "tools/nsdb/src/json.rs",
            required_patterns: &[
                "payload_execution_handoff_available",
                "payload_execution_handoff_protocol",
                "payload_execution_handoff_debugger_contract",
                "payload_execution_handoff_status",
                "payload_execution_handoff_record_count",
                "payload_execution_handoff_first_trace_id",
                "payload_execution_event_filter_active",
                "payload_execution_handoff_hetero_execution_closure_status",
                "provider_output_payload_path",
                "provider_output_payload_hash",
                "provider_output_payload_attach_status",
                "payload_execution_event_count",
                "payload_execution_event_query_contract",
                "payload_execution_event_source",
                "payload_execution_event_query_result_count",
                "nsdb_replay_plan_json",
                "replay_hetero_execution_closure_status",
                "debugger_transcript_contract",
                "payload_decoder_manifest_status",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "nsdb-replay-device-sample-handoff-consumer",
            path: "tools/nsdb/src/replay.rs",
            required_patterns: &[
                "device_sample_handoffs",
                "provider-handoff-observed",
                "device-sample-handoff",
                "provider_handoff_materialization_status",
                "provider_sample_blocker",
                "provider-output-payload-invalid",
                "hetero_execution_closure_blocker",
                "hetero-execution-closure",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "nsdb-yir-replay-transcript-consumer",
            path: "tools/nsdb/src/transcript.rs",
            required_patterns: &[
                "nsdb-yir-replay-transcript-v1",
                "transcript-consumed",
                "transcript-blocked",
                "replayed_checkpoint_count",
                "build_replay_transcript",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "frontdoor-debugger-transcript-command-handoff",
            path: "tools/nuis/src/closure_summary.rs",
            required_patterns: &[
                "debugger_transcript_next_command",
                "closure_summary_debugger_transcript_next_command",
                "nsdb_replay_next_command",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "nsdb-provider-sample-materializer",
            path: "tools/nsdb/src/provider_sample_materialize.rs",
            required_patterns: &[
                "materialize_provider_samples",
                "provider-sample-materialized",
                "provider-sample-blocked",
                "nuis-nsdb-provider-sample-artifact-v1",
                "deterministic-provider-sample-artifact",
                "nsdb-materialize-provider-samples",
                "provider_runner_adapter_id",
                "provider_runner_real_device_capable",
                "provider_runner_real_device_probe_status",
                "provider_execution_comparison_contract",
                "provider_execution_comparison_status",
                "provider_output_payload_contract",
                "provider_output_payload_status",
                "provider_output_payload_evidence_status",
                "provider_output_payload_next_action",
                "provider_output_payload_evidence",
                "provider_output_payload_detail",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "nsdb-provider-sample-materializer-cli",
            path: "tools/nsdb/src/cli.rs",
            required_patterns: &[
                "MaterializeProviderSamples",
                "materialize-provider-samples",
                "--provider-family",
                "parses_materialize_provider_samples_command",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "run-artifact-launch-evidence-surface",
            path: "tools/nuis/src/artifact_launch_evidence.rs",
            required_patterns: &[
                "RunArtifactLaunchEvidence",
                "json_fields_with_prefix",
                "nuis-run-artifact-launch-evidence-v1",
                "nsdb-yir-launch-evidence-v1",
                "nsdb-yir-payload-execution-trace-v1",
                "launch_evidence_first_payload_status",
                "launch_evidence_first_payload_entry_symbol",
                "launch_evidence_payload_execution_trace_records",
                "payload_execution_trace_records",
                "handoff-payload-trace-to-nsdb",
                "launch_evidence_backend_artifact_payload_evidence_available",
                "launch_evidence_backend_artifact_payload_count",
                "launch_evidence_backend_artifact_payload_role_status",
                "launch_evidence_backend_artifact_payload_ids",
                "launch_evidence_backend_artifact_payload_kinds",
                "nuis-hetero-execution-closure-v1",
                "launch_evidence_hetero_execution_closure_status",
                "handoff-hetero-execution-evidence-to-nsdb",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "run-artifact-host-runner-json-surface",
            path: "tools/nuis/src/artifact_host_runner.rs",
            required_patterns: &["HostRunnerJsonSurface", "host_runner_invoked", "host_runner_backend_artifact_payload_count", "host_runner_backend_artifact_payload_table_hash"],
        },
    DevTensorDriftCheckSpec {
            id: "host-runner-container-loader-handoff-policy",
            path: "tools/nuis-host-runner/src/container.rs",
            required_patterns: &[
                "host_assisted_loader",
                "backend_artifact_payload_count",
                "backend_artifact_payload_table_hash",
                "container_loader_handoff_blockers",
                "external-import:",
                "container-loader:blocker",
                "position(|byte| *byte == 0)",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "host-runner-backend-artifact-payload-scan",
            path: "tools/nuis-host-runner/src/container_backend_payload.rs",
            required_patterns: &[
                "BackendArtifactPayloadSummary",
                "scan_backend_artifact_payloads",
                "backend_artifact_payload",
                "nustar-backend-artifact",
                "role_status",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "host-runner-container-loader-policy-regression",
            path: "tools/nuis-host-runner/src/tests.rs",
            required_patterns: &[
                "allows_host_assisted_container_handoff_when_required_external_import_is_declared",
                "blocks_self_contained_container_handoff_when_required_external_import_is_declared",
                "allows_host_assisted_container_loader_handoff_when_external_import_loader_blockers_are_declared",
                "container_loader_handoff_status",
                "container_loader_handoff_ready",
                "backend_artifact_payload_count",
                "backend_artifact_payload_first_kind",
                "nustar-backend-artifact:kernel:aarch64:apple-silicon-cpu",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "self-contained-nsb-frontdoor-smoke",
            path: "tools/nuis/tests/self_contained_nsb_smoke.rs",
            required_patterns: &[
                "self_contained_nsb_route_moves_from_nsld_drive_to_run_artifact_handoff",
                "nuis-self-contained-image",
                "self-contained-image-awaiting-nsld-handoff",
                "nsld-host-entrypoint",
                "host_runner_invoked",
                "host_runner_nsb_readable",
                "host_runner_nsb_hash_matches",
                "host_runner_nsb_payload_region_mapped",
                "host_runner_nsb_payload_scan_kind",
                "nsld-container-toml",
                "safe_next_contract",
                "safe_next_action",
                "safe_next_reason",
                "drive reached a clean artifact chain",
                "host_runner_container_loader_status",
                "host_runner_container_loader_entry_symbol",
                "host_runner_container_loader_handoff_ready",
                "host_runner_container_loader_handoff_status",
                "host_runner_backend_artifact_payload_count",
                "host_runner_backend_artifact_payload_first_kind",
                "launch_evidence_first_payload_status",
                "launch_evidence_first_payload_entry_symbol",
                "run-artifact-or-replay-nsdb",
                "nsdb-payload-execution-replay-plan-v1",
                "nsld_final_executable_output_nsdb_replay_command",
                "nsld_final_executable_output_nsdb_replay_ready",
                "build-report",
                "nsld_final_executable_output_nsdb_replayable_checkpoint_count",
                "nsld_final_executable_output_nsdb_replay_next_action",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "run-artifact-entrypoint-protocol-regression",
            path: "tools/nuis/src/main_tests/artifact_runtime_run_artifact.rs",
            required_patterns: &[
                "run_artifact_prelaunch_kind",
                "run_artifact_prelaunch_status",
                "run_artifact_prelaunch_evidence_status",
                "nsld-host-entrypoint",
                "run_artifact_json_blocks_nsld_prelaunch_when_entrypoint_stub_is_missing",
                "run_artifact_json_blocks_nsld_prelaunch_when_entrypoint_protocol_is_missing",
                "host entrypoint stub is missing on disk",
                "nuis-nsld-host-entrypoint-v1",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "frontdoor-reference-doc",
            path: "docs/reference/nuis-frontdoor-surface-reference.md",
            required_patterns: &[
                "nsld_final_executable_output_boundary_status",
                "nsld_final_executable_output_materialization_status",
                "nsld_final_executable_output_execution_handoff_contract",
                "nsld_final_executable_output_execution_handoff_ready",
                "nsld_final_executable_output_execution_handoff_status",
                "nsld_final_executable_output_execution_handoff_target",
                "nsld_final_executable_output_execution_handoff_evidence_status",
                "nsld_final_executable_output_execution_handoff_first_blocker",
                "nsld_final_executable_output_execution_handoff_decision_code",
                "nsld_final_executable_output_payload_execution_trace_protocol",
                "nsld_final_executable_output_payload_execution_trace_available",
                "nsld_final_executable_output_payload_execution_trace_record_count",
                "nsld_final_executable_output_payload_execution_trace_ready_record_count",
                "nsld_final_executable_pipeline_execution_handoff_contract",
                "nsld_final_executable_pipeline_execution_handoff_ready",
                "nsld_final_executable_pipeline_execution_handoff_status",
                "nsld_final_executable_pipeline_execution_handoff_target",
                "nsld_final_executable_pipeline_execution_handoff_evidence_status",
                "nsld_final_executable_pipeline_execution_handoff_first_blocker",
                "nsld_final_executable_pipeline_execution_handoff_decision_code",
                "nsld_final_executable_output_recommended_next_action",
                "nsld_self_owned_image_status",
                "run_artifact_prelaunch_kind",
                "run_artifact_prelaunch_status",
                "run_artifact_prelaunch_evidence_status",
                "workflow_run_artifact_prelaunch_kind",
                "workflow_run_artifact_prelaunch_status",
                "workflow_run_artifact_prelaunch_evidence_status",
                "workflow_run_artifact_prelaunch_command",
                "workflow_run_artifact_prelaunch_reason",
                "workflow_launch_evidence_protocol",
                "workflow_launch_evidence_debugger_contract",
                "workflow_launch_evidence_host_runner_probe_status",
                "run_artifact_prelaunch_command",
                "run_artifact_prelaunch_runner_command_present",
                "run_artifact_prelaunch_entrypoint_present",
                "run_artifact_prelaunch_entrypoint_protocol",
                "run_artifact_prelaunch_entrypoint_protocol_valid",
                "host_runner_invoked",
                "host_runner_status",
                "host_runner_nsb_readable",
                "host_runner_nsb_payload_region_mapped",
                "host_runner_container_loader_handoff_status",
                "launch_evidence_protocol",
                "launch_evidence_debugger_contract",
                "launch_evidence_payload_execution_trace_protocol",
                "launch_evidence_payload_execution_trace_record_count",
                "launch_evidence_first_payload_status",
                "launch_evidence_first_payload_entry_symbol",
                "launch_evidence_first_payload_first_blocker",
                "launch_evidence_first_blocker",
                "artifact_closure_kind",
                "artifact_closure_status",
                "artifact_closure_evidence_status",
                "artifact_closure_command",
                "artifact_closure_runner_command_present",
                "artifact_closure_entrypoint_present",
                "artifact_closure_entrypoint_protocol",
                "artifact_closure_entrypoint_protocol_valid",
                "artifact_launch_evidence_protocol",
                "artifact_launch_evidence_debugger_contract",
                "artifact_launch_evidence_host_runner_probe_status",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "release-check-device-sample-handoff-mirror",
            path: "tools/nuis/src/release_check_command.rs",
            required_patterns: &[
                "collect_device_sample_handoff_mirror",
                "append_workflow_link_plan_json_fields",
                "release_check_device_sample_handoff",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "native-artifact-workflow-doc",
            path: "docs/reference/nuis-native-artifact-workflow.md",
            required_patterns: &[
                "nsld_final_executable_output_boundary_status",
                "nsld_final_executable_output_materialization_status",
                "nsld_final_executable_output_execution_handoff_contract",
                "nsld_final_executable_output_execution_handoff_ready",
                "nsld_final_executable_output_execution_handoff_status",
                "nsld_final_executable_output_execution_handoff_target",
                "nsld_final_executable_output_execution_handoff_evidence_status",
                "nsld_final_executable_output_execution_handoff_first_blocker",
                "nsld_final_executable_output_execution_handoff_decision_code",
                "nsld_final_executable_output_payload_execution_trace_protocol",
                "nsld_final_executable_output_payload_execution_trace_available",
                "nsld_final_executable_output_payload_execution_trace_record_count",
                "nsld_final_executable_output_payload_execution_trace_ready_record_count",
                "nsld_final_executable_pipeline_execution_handoff_contract",
                "nsld_final_executable_pipeline_execution_handoff_ready",
                "nsld_final_executable_pipeline_execution_handoff_status",
                "nsld_final_executable_pipeline_execution_handoff_target",
                "nsld_final_executable_pipeline_execution_handoff_evidence_status",
                "nsld_final_executable_pipeline_execution_handoff_first_blocker",
                "nsld_final_executable_pipeline_execution_handoff_decision_code",
                "nsld_final_executable_output_recommended_next_action",
                "nsld_self_owned_image_status",
                "run_artifact_prelaunch_kind",
                "run_artifact_prelaunch_status",
                "run_artifact_prelaunch_evidence_status",
                "workflow_run_artifact_prelaunch_kind",
                "workflow_run_artifact_prelaunch_status",
                "workflow_run_artifact_prelaunch_evidence_status",
                "workflow_run_artifact_prelaunch_command",
                "workflow_run_artifact_prelaunch_reason",
                "workflow_launch_evidence_protocol",
                "workflow_launch_evidence_debugger_contract",
                "workflow_launch_evidence_host_runner_probe_status",
                "workflow_nsdb_handoff_available",
                "workflow_nsdb_handoff_protocol",
                "workflow_nsdb_handoff_record_count",
                "link_plan_heterogeneous_backend_artifact_units",
                "link_plan_heterogeneous_backend_artifact_ready_units",
                "link_plan_heterogeneous_backend_families",
                "link_plan_heterogeneous_target_devices",
                "link_plan_heterogeneous_backend_artifact_first_unready",
                "run_artifact_prelaunch_command",
                "run_artifact_prelaunch_runner_command_present",
                "run_artifact_prelaunch_entrypoint_present",
                "run_artifact_prelaunch_entrypoint_protocol",
                "run_artifact_prelaunch_entrypoint_protocol_valid",
                "host_runner_invoked",
                "host_runner_status",
                "host_runner_nsb_readable",
                "host_runner_nsb_payload_region_mapped",
                "host_runner_container_loader_handoff_status",
                "launch_evidence_protocol",
                "launch_evidence_debugger_contract",
                "launch_evidence_payload_execution_trace_protocol",
                "launch_evidence_payload_execution_trace_record_count",
                "launch_evidence_first_payload_status",
                "launch_evidence_first_payload_entry_symbol",
                "launch_evidence_first_payload_first_blocker",
                "launch_evidence_first_blocker",
                "artifact_closure_kind",
                "artifact_closure_status",
                "artifact_closure_evidence_status",
                "artifact_closure_command",
                "artifact_closure_runner_command_present",
                "artifact_closure_entrypoint_present",
                "artifact_closure_entrypoint_protocol",
                "artifact_closure_entrypoint_protocol_valid",
                "artifact_launch_evidence_protocol",
                "artifact_launch_evidence_debugger_contract",
                "artifact_launch_evidence_host_runner_probe_status",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "std-filesystem-light-smoke",
            path: "tools/nuis/tests/std_filesystem_smoke.rs",
            required_patterns: &[
                "STD_TOOLING_LIGHT_SMOKE_PROJECTS",
                "std_tooling_light_project_smokes_build_doctor_and_run",
                "text_pipeline_demo",
                "io_runtime_demo",
                "stdin_runtime_demo",
                "filesystem_io_report_demo",
                "std_tooling_observable_cli_smoke_checks_reports_and_stdin",
                "run_binary_with_stdin",
                "run_binary_with_args",
                "host_stdin_read",
                "cli_wc_demo",
                "cli_pgm_invert_demo",
                "P2\\n2 2\\n15\\n15 11 6 7\\n",
                "cli_report_file_demo",
                "pixelmagic_report_file_demo",
                "std-preprocessed-pgm",
                "input_bytes: 20",
                "witsage_report_file_demo",
                "StdReportContracts.cli_report_file_status_total",
                "StdReportContracts.cli_report_file_validation_total",
                "PixelMagicContracts.filter_chain_total",
                "WitSageContracts.classifier_pipeline_total",
                "host_argv_count",
                "host_file_read",
                "host_file_write",
                "host_text_word_count",
                "bytes: 31",
                "words: 5",
                "runtime_materialization_policy",
                "host_stdout_write",
                "host_stderr_write",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "official-galaxy-hetero-smoke",
            path: "tools/nuis/tests/official_galaxy_hetero_smoke.rs",
            required_patterns: &[
                "official_galaxy_hetero_projects_emit_shader_and_kernel_artifacts",
                "nsld drive apply official galaxy hetero smoke",
                "whitelisted-artifact-mutation",
                "nsld-drive-safe-next-v1",
                "rerun-drive-to-refresh-next-action",
                "resolve-final-output-nsdb-replay",
                "nsld_final_executable_output_nsdb_replay_contract",
                "nsld_final_executable_output_nsdb_replay_first_blocker",
                "PixelMagicContracts.shader_pipeline_total",
                "WitSageContracts.kernel_pipeline_total",
                "hetero_runtime_trace_device_sample_descriptor_count",
                "materialize_provider_samples",
                "provider-sample-materialized",
                "deterministic-provider-sample-artifact",
                "nuis-provider-runner-v1",
                "nuis-provider-runner-adapter-v1",
                "nuis-provider-runner-registry-v1",
                "builtin-nustar-provider-runner-registry",
                "provider_runner_real_device_capable",
                "host-simulated-provider-runner",
                "first_output_payload_comparison_contract",
                "first_output_payload_input_evidence_hash",
                "first_output_payload_native_output_kind",
                "first_output_payload_native_output_bytes",
                "artifact_device_provider_sample_manifest_status",
                "replay-device-sample",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "nsdb-metal-provider-runner",
            path: "tools/nsdb/src/provider_runner_metal.rs",
            required_patterns: &[
                "nuis-metal-provider-runner-v1",
                "metal-command-buffer-completed",
                "execute_u32_add",
                "Metal provider runner",
                "remove_file",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "std-tooling-doc-smoke-chain",
            path: "examples/projects/tooling/README.md",
            required_patterns: &[
                "cargo test -q -p nuis --test std_filesystem_smoke",
                "filesystem_io_report_demo",
                "cli_report_file_demo",
                "std-preprocessed PixelMagic input",
                "text_report_json_demo",
                "terminal/stdin/TTY",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "std-readme-host-io-text-lane",
            path: "stdlib/std/README.md",
            required_patterns: &[
                "host I/O and text",
                "filesystem/path/location",
                "nuis-provider-runner-adapter-v1",
                "lib/io_contracts.ns",
                "lib/text_contracts.ns",
                "lib/fs_contracts.ns",
                "lib/report_contracts.ns",
                "stdin_runtime_demo",
                "filesystem_io_report_demo",
                "cli_wc_demo",
                "cli_report_file_demo",
                "StdReportContracts",
                "argv -> file.read -> buffer",
            ],
        },
    DevTensorDriftCheckSpec {
        id: "source-task-ready-delay-builtin",
        path: "tools/nuisc/src/frontend/task_builtins.rs",
        required_patterns: &[
            "\"ready_after\"",
            "NirExpr::CpuReadyAfter",
            "expects integer delay",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "source-task-ready-delay-lowering",
        path: "tools/nuisc/src/lowering/cpu_exprs.rs",
        required_patterns: &[
            "NirExpr::CpuReadyAfter",
            "lower_cpu_ready_after",
            "instruction: \"ready_after\"",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "scheduler-backed-task-result-lowering",
            path: "crates/yir-lower-llvm/src/async_resource_lowering.rs",
            required_patterns: &[
                "@nuis_scheduler_task_spawn_i64_v1",
                "@nuis_scheduler_task_spawn_invoker_i64_v1",
                "@nuis_scheduler_task_timeout_v1",
                "@nuis_scheduler_task_ready_after_v1",
                "@nuis_scheduler_task_cancel_v1",
                "@nuis_scheduler_task_join_state_v1",
                "@nuis_scheduler_task_value_i64_v1",
                "DeferredTaskThunkScalar",
                "arguments.len() * 8",
                "runtime_state",
                "runtime_handle",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "scheduler-task-invoker-wrapper",
            path: "crates/yir-lower-llvm/src/lib.rs",
            required_patterns: &[
                "render_scalar_task_invoker",
                "signature.params.iter().copied().enumerate()",
                "CpuCallScalarKind::F32",
                "CpuCallScalarKind::F64",
                "bitcast float %task_result to i32",
                "bitcast double %task_result to i64",
                "@nuis_task_invoker_",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "scheduler-backed-task-result-runtime",
            path: "tools/nuisc/src/aot_c_shim_runtime.rs",
            required_patterns: &[
                "nuis_scheduler_task_states[256]",
                "nuis_scheduler_task_spawn_i64_v1",
                "nuis_scheduler_task_spawn_invoker_i64_v1",
                "nuis_scheduler_task_timeout_v1",
                "nuis_scheduler_task_ready_after_v1",
                "nuis_scheduler_task_cancel_v1",
                "nuis_scheduler_task_join_state_v1",
                "nuis_scheduler_task_value_i64_v1",
                "NuisSchedulerTaskInvokerI64",
                "NuisSchedulerTaskThunkPacket",
                "NuisSchedulerOwnedPayloadV1",
                "nuis_scheduler_task_spawn_owned_v1",
                "nuis_scheduler_task_spawn_owned_invoker_v1",
                "nuis_scheduler_task_take_owned_v1",
                "nuis_scheduler_owned_payload_drop_v1",
                "nuis_scheduler_payload_free_v1",
                "nuis_scheduler_task_release_owned_payload_v1",
                "nuis_scheduler_task_thunk_packets[256]",
                "nuis_scheduler_task_execute_thunk_v1",
                "nuis_scheduler_task_release_context_v1",
                "nuis_lifecycle_tick_once_v1",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "scheduler-recursive-struct-owned-payload-lowering",
            path: "crates/yir-lower-llvm/src/task_owned_payload.rs",
            required_patterns: &[
                "emit_owned_struct_spawn",
                "emit_owned_struct_invoker_spawn",
                "emit_owned_struct_take",
                "stable_struct_type_id",
                "@nuis_scheduler_task_spawn_owned_v1",
                "@nuis_scheduler_task_spawn_owned_invoker_v1",
                "@nuis_scheduler_task_take_owned_v1",
                "@nuis_scheduler_owned_payload_drop_v1",
                "@nuis_scheduler_owned_aggregate_drop_v1",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "language-bootstrap-result-task-smoke",
            path: "tools/nuis/tests/language_bootstrap_smoke.rs",
            required_patterns: &[
                "task_result_enum_project_anchors_language_bootstrap_smoke",
                "generic_trait_and_glm_buffer_projects_anchor_language_bootstrap_smoke",
                "generic_result_buffer_lambda_project_combines_language_bootstrap_features",
                "no_annotation_try_await_result_hof_project_anchors_language_bootstrap_smoke",
                "../../examples/projects/task/task_result_enum_demo",
                "../../examples/projects/task/task_no_annotation_try_await_result_hof_demo/main.ns",
                "../../examples/projects/task/task_no_annotation_try_await_result_hof_demo",
                "../../examples/projects/state/generic_method_bound_guarded_nested_match_demo",
                "../../examples/projects/state/glm_buffer_roundtrip_state_demo",
                "../../examples/projects/state/generic_result_buffer_lambda_helper_demo",
                "cpu.async_value",
                "__hof_result_map_raise_value__i64__i64__ErrorEnvelope",
                "__hof_result_map___lambda_build_report_0__i64__i64__HelperError",
                "__hof_result_map___lambda_build_report_2__i64__i64__HelperError",
                "ok__i64__HelperError(seed)",
                "Result<i64, ErrorEnvelope>",
                "enum Result<T, E>",
                "return Result.Err(error)",
                "if (seed == 3)",
                "err__i64__HelperError(HelperError.Invalid",
                "return Result.Err<i64, HelperError>",
                "trait Addable",
                "impl.Addable.for.i64.add(local, local)",
                "impl.Addable.for.i64.add(item, item)",
                "buffer_len(buffer)",
                "cpu.store_at",
                "edge lifetime",
                "cpu.variant_is",
                "cpu.task_completed",
                "policy=signature-whitelist-required",
                "task_result_enum_demo should execute the Result/task/error path",
                "generic Result/buffer/lambda helper binary",
                "__hof_map_result___lambda_compute_0__i64__i64__Error",
                "let mapped = map_result",
                "Result.Ok(await work(fetch(seed)?))",
                "let err_result: Result<i64, Error> = await compute_err_hof(5)",
                "no-annotation try/await Result HOF run-artifact json",
                "should execute Ok and Err paths",
                "59",
                "11",
            ],
        },
];
