use crate::dev_tensor_drift::DevTensorDriftCheckSpec;

pub(crate) const DEV_TENSOR_RUNTIME_BOOTSTRAP_DRIFT_CHECKS: &[DevTensorDriftCheckSpec] = &[
    DevTensorDriftCheckSpec {
        id: "runtime-lifecycle-bootstrap-plan",
        path: "crates/nuis-runtime/src/lifecycle_bootstrap.rs",
        required_patterns: &[
            "nuis-runtime-lifecycle-bootstrap-plan-v1",
            "nuis-runtime-lifecycle-bootstrap-plan-identity-v1",
            "loader_entry_machine_arch",
            "plan_lifecycle_bootstrap",
            "map-section",
            "apply-relocation",
            "bind-loader-entry",
            "bind-runtime-service",
            "runtime.clock-root",
            "runtime.glm-root",
            "enter-nuis-bootstrap",
            "bind-provider-dispatch",
            "activate-scheduler",
            "runtime-bootstrap:entry-relocation-target-mismatch",
            "runtime-bootstrap:mapped-section-count-mismatch",
            "runtime-bootstrap:applied-relocation-count-mismatch",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "runtime-lifecycle-bootstrap-execution",
        path: "crates/nuis-runtime/src/lifecycle_execution.rs",
        required_patterns: &[
            "nuis-runtime-lifecycle-bootstrap-execution-v1",
            "nuis-runtime-lifecycle-bootstrap-execution-identity-v1",
            "nuis-runtime-compiled-entry-transfer-v1",
            "entry_machine_arch",
            "OwnedImageMapping",
            "OwnedMappedSectionHandle",
            "OwnedAppliedRelocationHandle",
            "OwnedRuntimeServiceHandle",
            "prepare_lifecycle_bootstrap_execution",
            "consume-mapped-section",
            "consume-applied-relocation",
            "activate-runtime-service",
            "transfer-compiled-entry",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "runtime-native-lifecycle-entry-context",
        path: "crates/nuis-runtime/src/native_entry_context.rs",
        required_patterns: &[
            "nuis-runtime-lifecycle-entry-context-i64-v1",
            "nuis-runtime-lifecycle-entry-context-v1",
            "NativeLifecycleEntryContextV1",
            "#[repr(C)]",
            "struct_size_bytes",
            "runtime.clock-root",
            "runtime.glm-root",
            "bind_transfer_context",
            "native-entry-context:identity-mismatch",
            "native-entry-context:service-binding-invalid",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "runtime-native-executable-memory-adapter",
        path: "crates/nuis-runtime/src/executable_memory.rs",
        required_patterns: &[
            "nuis-executable-memory-adapter-v1",
            "nuis-native-entry-invocation-v1",
            "nuis-native-entry-invocation-permit-v1",
            "NUIS_LIFECYCLE_ENTRY_CONTEXT_ABI_V1",
            "nuis-native-entry-code",
            "ExecutableMemoryAdapter",
            "NativeHostExecutableMemoryAdapter",
            "NativeEntryInvocationPermit",
            "AuthorizedNativeEntry",
            "canonical_machine_arch",
            "native_host_machine_arch",
            "PROT_READ | libc::PROT_WRITE",
            "PROT_READ | libc::PROT_EXEC",
            "sys_icache_invalidate",
            "section-kind-unsupported",
            "section-bytes-unverified",
            "entry-range-invalid",
            "host-machine-arch-mismatch",
            "permit-identity-mismatch",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-native-lifecycle-entry-section",
        path: "tools/nsld/src/native_entry.rs",
        required_patterns: &[
            "nuis.nsld.native-entry.bin",
            "NATIVE_ENTRY_RELOCATION_SLOT_BYTES",
            "emit_native_entry_asset",
            "native_entry_code_range",
            "NUIS_LIFECYCLE_ENTRY_CONTEXT_ABI_V1",
            "NUIS_NATIVE_ENTRY_SECTION_KIND",
            "native_entry_machine_arch",
            "native_entry_machine_arch(\"arm64\")",
            "native_entry_machine_arch(\"amd64\")",
            "unsupported Nsld native lifecycle-entry architecture",
            "unsupported Nsld native lifecycle-entry calling ABI",
            "cmp dword ptr [rdi+8],1",
            "cmp dword ptr [rcx+8],1",
            "ldr w1,[x0,#8]",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "host-runner-native-entry-metadata-gate",
        path: "tools/nuis-host-runner/src/container.rs",
        required_patterns: &[
            "loader_entry_abi_contract",
            "loader_entry_machine_arch",
            "NUIS_LIFECYCLE_ENTRY_CONTEXT_ABI_V1",
            "container-loader:entry-abi-unsupported",
            "container-loader:entry-machine-arch-unsupported",
            "container-loader:symbol-range-invalid",
            "container-loader:symbol-hash-invalid",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "host-runner-native-entry-byte-handoff",
        path: "tools/nuis-host-runner/src/native_entry.rs",
        required_patterns: &[
            "nuis-host-native-entry-handoff-v1",
            "nuis-nsld-container-end-v1",
            "container-payload-padding-invalid",
            "verified-after-relocation-normalization",
            "native-entry:section-hash-mismatch",
            "native-entry:code-hash-mismatch",
            "ExecutableEntryRequest::from_transfer",
            "NativeHostExecutableMemoryAdapter.prepare",
            "NativeEntryInvocationPermit::from_transfer",
            "preparation.authorize(permit, context)",
            "NativeLifecycleEntryContextV1::from_transfer",
            "context_identity_hash",
            "native-entry:bootstrap-return-mismatch",
            "invocation_requested",
            "machine_arch_status",
            "drop(preparation)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "host-runner-native-entry-probe-flag",
        path: "tools/nuis-host-runner/src/args.rs",
        required_patterns: &[
            "--invoke-native-entry",
            "invoke_native_entry",
            "native_entry_invocation_requires_explicit_flag",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-runtime-service-bindings",
        path: "tools/nsld/src/container_metadata_bindings.rs",
        required_patterns: &[
            "runtime.clock-root",
            "runtime.glm-root",
            "clock_protocol_hash",
            "glm_binding_material",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-runtime-only-binding-proof",
        path: "tools/nsdb/src/handoff_binding.rs",
        required_patterns: &[
            "provider_selection_absent",
            "provider_selection_verified",
            "claim_builder_accepts_verified_runtime_only_binding_table",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nuis-runtime-only-binding-proof",
        path: "tools/nuis/src/artifact_nsdb_handoff_binding.rs",
        required_patterns: &[
            "provider_selection_absent",
            "provider_selection_verified",
            "independently_verifies_runtime_only_binding_proof",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "host-runner-runtime-bootstrap-adapter",
        path: "tools/nuis-host-runner/src/runtime_bootstrap.rs",
        required_patterns: &[
            "plan_lifecycle_bootstrap",
            "LifecycleBootstrapFacts",
            "MappedSectionFacts",
            "AppliedRelocationFacts",
            "runtime_service_binding_facts",
            "OwnedImageMapping",
            "prepare_lifecycle_bootstrap_execution",
            "RuntimeBootstrapHandoff",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsld-final-output-runtime-bootstrap-identity",
        path: "tools/nsld/src/final_executable_bootstrap.rs",
        required_patterns: &[
            "nsld_final_output_bootstrap_plan",
            "actual_relocation_patch_application_status",
            "actual_relocation_patch_byte_audit_status",
            "MappedSectionFacts",
            "AppliedRelocationFacts",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "nsdb-runtime-bootstrap-replay-identity",
        path: "tools/nsdb/src/lib.rs",
        required_patterns: &[
            "nuis-runtime-lifecycle-bootstrap-plan-identity-v1",
            "runtime_bootstrap_identity_status",
            "runtime-bootstrap-identity:invalid",
        ],
    },
];
