use crate::dev_tensor_drift::DevTensorDriftCheckSpec;

pub(super) const CHECKS: &[DevTensorDriftCheckSpec] = &[
    DevTensorDriftCheckSpec {
        id: "native-typed-helper-scalar-layout-admission",
        path: "crates/yir-lower-llvm/src/native_session/aggregates.rs",
        required_patterns: &[
            "scalar_value_layout(encoded)",
            "scalar_value_layout(&node.op.args[1])",
            "layout.type_name != result.ty",
            "super::ScalarStateLayout::parse(encoded)?",
            "iteration carry validation remain independent of callback registration",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-typed-helper-execution-evidence",
        path: "tools/nuisc/tests/native_application_bridge/typed_helper_values.rs",
        required_patterns: &[
            "typed_nested_helpers_execute_independent_snapshots_without_owned_allocations",
            "for slots in [1, 6, 64]",
            "emit_registered_with_work_limits",
            "multi_execution::ALLOCATION_PROBE",
            "state_words(reference.state()), output",
            "function.body_nodes.reverse()",
            "ordinary.contains(\"define i64 @nuis_fn_packet(\")",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-typed-helper-admission-evidence",
        path: "tools/nuisc/tests/native_application_bridge/typed_helper_admission.rs",
        required_patterns: &[
            "typed_helper_calls_require_exact_nested_layouts_and_scalar_arguments",
            "typed_helper_values_reject_spoofed_nested_values_and_hidden_effects",
            "typed_helper_early_returns_keep_fallible_suffix_after_guard",
            "mixed_nested_local_rebinding_uses_guarded_native_value_returns",
            "slot bounds",
            "maximum depth",
            "does not admit cpu.print",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-typed-helper-frontdoor-restoration-evidence",
        path: "tools/nuis/tests/native_session_workflow.rs",
        required_patterns: &[
            "native_typed_helper_values_build_cache_and_standalone_relocation",
            "native_typed_local_rebinding_build_cache_and_standalone_relocation",
            "for helper in [\"relay_state\", \"finish\"]",
            "source == CONTROL_COMPOSITION_SOURCE || typed_helper_values",
            "fs::read_to_string(relocated.join(format!(\"{stem}.ll\"))).unwrap()",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-typed-helper-guard-budget-evidence",
        path: "tools/nuisc/tests/native_application_bridge/typed_helper_guards.rs",
        required_patterns: &[
            "typed_helper_guards_preserve_lazy_traps_shared_entries_and_output_sentinels",
            "(0, i64::MIN, -1, required, None)",
            "(0, 10, 2, required - 1, None)",
            "check_guards(SOURCE, 3, false)",
            "check_guards(&source, 5, false)",
            "check_guards(&unused, 5, true)",
            "(2, 7, 0, 0, None)",
            "words.unwrap_or_else(|| vec![-700; 5])",
            "run.status.signal()",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-scalar-layout-unique-nested-siblings",
        path: "crates/yir-core/src/native_scalar_session.rs",
        required_patterns: &[
            "fields.len() > MAX_SCALAR_SLOTS",
            "if !names.insert(name)",
            "state contains duplicate field names",
            "S{nested:N{x:A{a:i64};x:B{b:bool}}}",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-typed-helper-test-registration",
        path: "tools/nuisc/tests/native_application_bridge.rs",
        required_patterns: &[
            "mod typed_helper_values;",
            "mod typed_helper_admission;",
            "mod typed_helper_guards;",
            "mod typed_local_values;",
            "mod typed_sparse_captures;",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-scalar-value-return-contract",
        path: "docs/reference/nuis-native-scalar-value-returns-v1.md",
        required_patterns: &[
            "Callback and helper admission remain distinct",
            "Scoped iteration calls retain their separate flat-i64 carry schema",
            "Matching local bindings and rebindings now admit mixed/nested scalar records",
            "i64 leaves plus its predicate still needs 65 arguments",
            "No missing fields are filled with synthetic zeros or partial records",
            "Alias normalization is transactional",
            "Forward branch substitution now materializes a binding",
            "now gives straight-line record writes separate private identities",
            "Two or more boolean captures share nonnegative i64 words of at most 63 bits",
            "Ordinary LLVM emission, resource aggregates, external FFI and task thunks retain",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-flat-value-private-return-plan",
        path: "crates/yir-lower-llvm/src/native_session/aggregate_values.rs",
        required_patterns: &[
            "super::aggregates::scalar_value_layout(encoded)?",
            "format!(\"[{} x i64]\", self.slots)",
            "extractvalue {ty} {returned}, {slot}",
            "insertvalue {ty} {aggregate}, i64 {field}, {index}",
            "materialize_owned_value",
            "guard_return_struct_cont",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-value-root-helper-admission-separation",
        path: "crates/yir-lower-llvm/src/lib.rs",
        required_patterns: &[
            "let native_value_return = if require_scalar_values",
            "if native_roots.contains(&function_name.as_str())",
            "native_session::aggregate_values::NativeValueReturn::callback",
            "native_session::aggregate_values::NativeValueReturn::helper",
            "helper_signature.native_value_return.as_ref()",
            "helper_signature.llvm_return_type()",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-flat-value-loop-snapshots",
        path: "crates/yir-lower-llvm/src/loop_owned_struct_lowering.rs",
        required_patterns: &[
            "native_value_return: signature.native_value_return.clone()",
            "returns.unpack(result, body, next_reg)",
            "unpack_immediate_owned_struct(result, &self.template, body, next_reg)",
            "Check the private control slot before committing any of the returned carries",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-flat-value-layout-unit-evidence",
        path: "crates/yir-lower-llvm/src/native_session/aggregate_values/tests.rs",
        required_patterns: &[
            "value_return_requires_unique_bounded_scalar_fields",
            "value_returns_keep_declared_field_order_and_guarded_packing",
            "value_returns_reject_nominal_kind_field_and_local_layout_drift",
            "unpack_materializes_independent_named_scalar_values",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-flat-value-execution-evidence",
        path: "tools/nuisc/tests/native_application_bridge/aggregate_values.rs",
        required_patterns: &[
            "native_returns_are_values_while_ordinary_abi_stays_owned",
            "for slots in [1, 2, 7, 64]",
            "multi_execution::ALLOCATION_PROBE",
            "expected.extend([0, value, 0, 0])",
            "call [1 x i64] @nuis_fn_stop(",
            "ApplicationSession::open_registered",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-flat-value-documentation",
        path: "docs/reference/nuis-native-scalar-session-bridge-v1.md",
        required_patterns: &[
            "Native Flat Value Transport",
            "from 13 allocations to 1",
            "Selection happens after native admission, with separate helper and callback checks",
            "Native Callback Value Transport",
            "Reference State Normalization",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-flat-value-tensor-evidence",
        path: "tools/nuis/src/dev_tensor_data.rs",
        required_patterns: &[
            "Native callback roots now use allocation-free LLVM value returns",
            "zero aggregate allocations/drops",
            "Reference callback state binding now follows registered field paths",
            "project field demand through fallthrough record joins while preserving branch-selected values and loop backedges",
            "Same-name branch-local aliases now have independent lexical identities",
            "Native scalar helpers now admit bounded mixed/nested scalar return layouts",
            "The mixed/nested helper CLI fixture now passes build/run-artifact",
            "Guarded local value selections now close the ns-nova image-session lowering gap",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-callback-value-shared-layout-and-bit-packing",
        path: "crates/yir-lower-llvm/src/native_session/aggregate_values.rs",
        required_patterns: &[
            "super::ScalarStateLayout::parse(encoded)?",
            "slots: state.fields().len()",
            "crate::task_owned_payload::pack_scalar(value, body, next_reg)",
            "crate::task_owned_payload::unpack_scalar(&word, template, body, next_reg)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-callback-value-wrapper-publication",
        path: "crates/yir-lower-llvm/src/native_session/emit.rs",
        required_patterns: &[
            "%returned = call [{slots} x i64] @nuis_fn_{}",
            "%result{index} = extractvalue [{slots} x i64] %returned, {index}",
            "store i64 %result{index}, ptr %output_ptr{index}, align 1",
            "load i64, ptr %input_ptr{index}, align 1",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-callback-value-unit-evidence",
        path: "crates/yir-lower-llvm/src/native_session/aggregate_values/tests/callback.rs",
        required_patterns: &[
            "callback_and_helper_value_plans_share_bounded_scalar_layouts",
            "callback_value_plan_preserves_typed_nested_snapshots_and_guarded_bits",
            "for count in [0, 1, 64, 65]",
            "NativeValueReturn::helper(&layout).is_ok()",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-callback-value-overlap-and-reference-parity-evidence",
        path: "tools/nuisc/tests/native_application_bridge/callback_values.rs",
        required_patterns: &[
            "callback_values_preserve_nested_bits_overlap_and_failure_sentinels_without_allocating",
            "for slots in [1, 6, 64]",
            "[(1, 1), (1, 2), (2, 1), (1, slots + 2)]",
            "Check the entire backing region",
            "state_words(reference.state()), advanced",
            "reference.event(vec![]).unwrap()",
            "reference.close(vec![]).unwrap().unwrap()",
            "ApplicationSession::open_registered",
            "(\"probe_allocs\", 0)",
            "(\"probe_drops\", 0)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "native-callback-value-frontdoor-evidence",
        path: "tools/nuis/tests/native_session_workflow.rs",
        required_patterns: &[
            "llvm.matches(\"%returned = call [6 x i64]\").count(), 3",
            "line.contains(\"call \") && line.contains(\"@nuis_scheduler_owned_aggregate_\")",
            "functions <= 51",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "reference-state-named-field-normalization",
        path: "crates/yir-runtime-host/src/application_session/state_shape.rs",
        required_patterns: &[
            "const MAX_STATE_DEPTH: usize = 64;",
            "fn bind_layout",
            "supplied.insert(name, field).is_some()",
            "supplied.remove(name).ok_or_else(mismatch)?",
            "child.normalize(value)?",
            "kind.pack(&value)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "reference-state-publication-boundary",
        path: "crates/yir-runtime-host/src/application_session.rs",
        required_patterns: &[
            "let state = boundary.normalize_state(opened.value)?;",
            "invocation.value = self.boundary.normalize_state(invocation.value)?;",
            "self.state = invocation.value;",
            "self.failures.record(ApplicationFailureKind::Callback);",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "reference-state-shape-validation-evidence",
        path: "crates/yir-runtime-host/src/application_session/state_shape/tests.rs",
        required_patterns: &[
            "reorders_named_fields_at_every_depth_and_is_idempotent",
            "preserves_exact_scalar_bits_without_coercion",
            "rejects_missing_extra_duplicate_and_spoofed_fields",
            "rejects_wrong_nominal_types_and_resource_or_scalar_kind_substitution",
            "metadata_must_agree_across_callbacks_including_nested_nominal_identity",
            "metadata_free_yir_keeps_its_signature_only_nested_boundary",
            "reference_states_are_not_limited_to_native_slot_capacity",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "reference-state-lifecycle-and-source-order-evidence",
        path: "tools/nuisc/tests/native_application_bridge/reference_state.rs",
        required_patterns: &[
            "reference_state_normalization_preserves_source_effect_order_for_every_callback",
            "field_effect_order_includes_nested_call_arguments",
            "SOURCE.replace(\"@noinline \", \"\")",
            "malformed_event_state_keeps_last_accepted_state_and_allows_one_cleanup",
            "malformed_close_state_is_terminal_and_does_not_publish_partial_state",
            "state_normalization_does_not_retry_fuel_exhaustion",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "named-constructor-field-effects-ordered",
        path: "tools/nuisc/src/lowering/core_exprs.rs",
        required_patterns: &[
            "for (field_name, field_expr) in fields",
            "let lowered = lower_expr(field_expr, state, bindings)?;",
            "super::body_lowering::chain_nonpure_expr_stmt(field_expr, &lowered, state);",
            "super::edge_helpers::order_emitted_roots_after(",
            "args_out.push(format!(\"{field_name}={lowered}\"));",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "guarded-local-value-extraction",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/conditional_values.rs",
        required_patterns: &[
            "if control_catalog.contains_key(&function.name)",
            "control_values::value_type(value, scope, self.catalog, self.layouts)?",
            "yes.name == no.name && yes.ty == no.ty && yes.constant == no.constant",
            "params.extend(captured_params(yes.inputs, scope));",
            "Branch calls, projections and arithmetic stay inside the helper",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "guarded-local-value-lowering-registration",
        path: "tools/nuisc/src/lowering/buffer_loop_outline.rs",
        required_patterns: &[
            "let selections = conditional_values::outline(",
            "&control_catalog,",
            "scalar_helpers::collect_typed_values(module, &value_layouts, &control_catalog)",
            "catalog = scalar_helpers::collect(module);",
            "control_catalog = scalar_helpers::collect_with_layouts(module, &layouts);",
            "scalar_control::outline(",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "guarded-local-value-source-regressions",
        path: "tools/nuisc/src/lowering/tests_branch_helpers/conditional_values.rs",
        required_patterns: &[
            "fallible_local_value_in_effectful_function_is_selected_before_evaluation",
            "selected_local_values_keep_checked_failures_even_when_unused",
            "nested_local_values_capture_rebindings_and_evaluate_effectful_predicate_once",
            "fallible_local_selection_does_not_admit_effectful_arms",
            "one_sided_checked_rebinding_keeps_the_existing_outer_value",
            "mixed_nested_local_selection_keeps_snapshots_and_effectful_predicate_once",
            "typed_literal_narrowing_emits_wrapped_i32_constants_without_cast_instructions",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "guarded-local-value-native-regressions",
        path: "tools/nuisc/tests/control_flow_syntax_native/conditional_values.rs",
        required_patterns: &[
            "guarded_local_values_run_in_effectful_native_functions_and_buffer_loops",
            "native_local_value_failures_are_selected_not_speculated_or_discarded",
            "nested_native_local_selections_preserve_captures_and_nominal_values",
            "mixed_nested_guarded_values_run_with_the_ordinary_owned_abi",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "guarded-local-value-image-session-evidence",
        path: "tools/nuisc/tests/ns_nova_application_session.rs",
        required_patterns: &[
            "compiled_window_selection_skips_ignored_events_and_matches_image_inputs",
            "trace.presented_frames[0], expected[ordinal]",
            "trace.provider_completion_witnesses, witnesses",
            "function.body_nodes.reverse()",
            "compiled_nuis_image_state_survives_independent_events_without_main_replay",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "guarded-typed-value-layout-profile",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/control_values/layouts.rs",
        required_patterns: &[
            "trait ValueLayouts",
            "impl ValueLayouts for FlatLayouts",
            "impl ValueLayouts for TypedLayouts",
            "while let Some(name) = ready.pop_first()",
            "depth > 64 || (nested && nodes > 4096)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "guarded-typed-value-source-boundaries",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/control_values/typed_tests.rs",
        required_patterns: &[
            "typed_values_reuse_flat_dependencies_without_admitting_mixed_loop_carries_or_effects",
            "typed_layouts_reject_cycles_resources_empty_and_duplicate_fields_transitively",
            "typed_constructors_require_exact_leaf_types_unique_fields_and_nominal_records",
            "typed_layouts_bound_neutral_initializer_expansion_before_materializing_a_type_dag",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "guarded-typed-value-native-evidence",
        path: "tools/nuisc/tests/native_application_bridge/typed_local_values.rs",
        required_patterns: &[
            "typed_local_choices_and_one_sided_rebindings_preserve_nested_snapshots_and_bits",
            "for slots in [1, 6, 63, 64]",
            "typed_local_incompressible_capture_keeps_native_argument_bounds_explicit",
            "function/argument bounds",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "private-value-capture-layout-authority",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_layouts.rs",
        required_patterns: &[
            "generated.contains(&function.name)",
            "!scoped.contains(&function.name)",
            "scoped_loop_lowering::collect_scoped_call_targets(module, &eligible)",
            "control_values::supported_type(&param.ty, layouts)",
            "direct_calls::CapturePlan::new(leaves)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "private-value-capture-word-contract",
        path: "tools/nuisc/src/lowering/direct_calls/capture_params.rs",
        required_patterns: &[
            "const BOOLS_PER_WORD: usize = 63;",
            "bools.len() < 2",
            "self.leaves[group[0]].name.clone()",
            "1_i64 << bit",
            "private value capture layout/argument mismatch",
            "cast_bool_to_i64",
            "cast_i64_to_bool",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "private-value-capture-call-definition-agreement",
        path: "tools/nuisc/src/lowering/direct_calls/aggregate_params.rs",
        required_patterns: &[
            "state.capture_plans.get(&function.name).cloned()",
            "plan.lower_parameters(function, state, bindings, function_parameters)",
            "plan.lower_arguments(&flattened, state)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "private-value-capture-shape-regressions",
        path: "tools/nuisc/src/lowering/direct_calls/capture_params_tests.rs",
        required_patterns: &[
            "boolean_capture_groups_preserve_scalar_order_and_bound_word_width",
            "generated_capture_transport_does_not_rewrite_user_signatures_or_namesakes",
            "scoped_boolean_iteration_parameters_remain_independent_of_value_captures",
            "generated_value_helpers_used_as_scoped_actions_keep_logical_parameters",
            "[2, 62, 63, 64, 65, 126, 127, 128]",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "private-value-capture-native-word-evidence",
        path: "tools/nuisc/tests/native_application_bridge/typed_capture_words.rs",
        required_patterns: &[
            "typed_capture_words_execute_high_bits_word_boundaries_and_independent_flags",
            "assert_eq!(selection.parameters.len(), 2)",
            "assert_eq!(packet.parameters.len(), 64)",
            "function.body_nodes.reverse()",
            "probe_allocs",
            "probe_drops",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "private-value-capture-frontdoor-evidence",
        path: "tools/nuis/tests/native_session_workflow/capture_words.rs",
        required_patterns: &[
            "native_64_slot_captures_build_cache_and_restore_without_sources",
            "compile_cache: hit",
            "fs::remove_file(project.0.join(\"main.ns\"))",
            "fs::read_to_string(restored.join(&llvm_name)).unwrap(),",
            "rejected_before_open",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "private-value-capture-preserves-native-argument-bound",
        path: "crates/yir-lower-llvm/src/native_session/function.rs",
        required_patterns: &[
            "function.parameters.len() > MAX_SCALAR_SLOTS",
            "native scalar bridge exceeds its function/argument bounds",
            "native scalar bridge parameter node/signature drift",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "private-value-capture-projection-authority",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_projection.rs",
        required_patterns: &[
            "generated.contains(&f.name)",
            "!scoped.contains(&f.name) || scoped_generated.contains(&f.name)",
            "protected.get(&name)",
            "!protected.is_some_and(|inputs| inputs.contains(index))",
            "!pending.contains_key(callee)",
            "valid_caller(&module.functions[*i].body, &name, &plan)",
            "selected >= leaves(&param.ty, layouts)",
            "!written.contains(&p.name)",
            "aliases::normalize(&mut candidate, layouts)",
            "bindings::normalize(&mut candidate)",
            "snapshots::normalize(&mut candidate, layouts)",
            "module.functions[index] = candidate",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "private-value-capture-projection-before-packing",
        path: "tools/nuisc/src/lowering/buffer_loop_outline.rs",
        required_patterns: &[
            "capture_projection::project(",
            "&projection_functions,",
            "&generated_helpers,",
            "crate::nir_verify::verify_nir_module(module)?",
            "capture_layouts::collect(module, &capture_functions, &value_layouts)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "private-value-capture-complete-expression-discovery",
        path: "tools/nuisc/src/nir_walk.rs",
        required_patterns: &[
            "NirExpr::CastI64ToI32(inner)",
            "NirExpr::CpuExternCallOwnedObject { args, .. }",
            "NirExpr::KernelMapAxis { input, scalar, .. }",
            "NirExpr::ShaderBindSet { pipeline, bindings }",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "private-value-capture-projection-regressions",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_projection_tests.rs",
        required_patterns: &[
            "projection_flows_from_nested_helpers_to_callers_in_any_storage_order",
            "projection_retains_exact_nominal_subrecords_and_deduplicates_prefix_uses",
            "projection_keeps_whole_uses_and_control_flow_rebound_parameters",
            "projection_does_not_duplicate_or_discard_computed_record_arguments",
            "projection_vetoes_calls_hidden_in_unsupported_expressions",
            "projection_tracks_field_demand_beneath_integer_conversions",
            "projected_local_choices_preserve_effectful_predicate_once_and_old_snapshots",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "private-value-capture-sparse-native-evidence",
        path: "tools/nuisc/tests/native_application_bridge/typed_sparse_captures.rs",
        required_patterns: &[
            "typed_sparse_captures_execute_64_integer_state_with_four_private_arguments",
            "typed_sparse_captures_follow_aliases_inside_guarded_private_helpers",
            "typed_sparse_captures_preserve_old_and_rebound_record_versions",
            "typed_sparse_captures_keep_same_name_branch_aliases_and_suffixes_independent",
            "typed_sparse_captures_preserve_branch_local_rebound_snapshots",
            "typed_sparse_captures_compose_with_invariant_iteration_aliases",
            "typed_sparse_captures_project_wide_invariant_iteration_inputs",
            "typed_sparse_captures_preserve_cross_scope_terminal_snapshots",
            "[2, 3]",
            "assert_eq!(selection.parameters.len(), 4)",
            "assert_eq!(choose.parameters.len(), 64)",
            "function.body_nodes.reverse()",
            "probe_allocs",
            "probe_drops",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "private-value-capture-sparse-frontdoor-evidence",
        path: "tools/nuis/tests/native_session_workflow/capture_fields.rs",
        required_patterns: &[
            "native_sparse_captures_build_cache_and_restore_without_sources",
            "native_sparse_captures_aliases_build_cache_and_restore_without_sources",
            "native_sparse_captures_snapshots_build_cache_and_restore_without_sources",
            "native_sparse_captures_scoped_aliases_build_cache_and_restore_without_sources",
            "native_sparse_captures_scoped_snapshots_build_cache_and_restore_without_sources",
            "native_sparse_captures_loop_aliases_build_cache_and_restore_without_sources",
            "native_sparse_captures_wide_iteration_inputs_build_cache_and_restore_without_sources",
            "native_sparse_captures_terminal_snapshots_build_cache_and_restore_without_sources",
            "verify_selected_failures(&project, &restored)",
            "native session process failed:",
            "no fallback was attempted",
            "compile_cache: hit",
            "fs::remove_file(project.0.join(\"main.ns\"))",
            "fs::read_to_string(restored.join(&llvm_name)).unwrap(),",
            "rejected_before_open",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "private-value-capture-immutable-alias-authority",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_aliases.rs",
        required_patterns: &[
            "!writes.contains_key(&p.name)",
            "self.writes.get(name) == Some(&1)",
            "!self.parameters.contains(name)",
            "self.invariant_origin(origin)",
            "self.parameters.contains(root) && !self.writes.contains_key(root)",
            "declared.is_none_or(|ty| ty == &origin.ty)",
            "nested_scopes.push(scope.clone())",
            "walk::rewrite_expr(expr",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "private-value-capture-immutable-alias-regressions",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_aliases_tests.rs",
        required_patterns: &[
            "immutable_alias_chains_expose_only_used_nested_fields",
            "alias_demand_propagates_across_private_call_chains_in_both_orders",
            "branch_local_aliases_keep_independent_lexical_origins",
            "alias_subrecord_returns_preserve_nominal_type_and_full_prefix_demand",
            "whole_alias_uses_and_caller_veto_leave_the_original_body_unchanged",
            "invariant_outer_and_iteration_local_alias_reads_project",
            "repeated_branch_alias_names_project_independent_fields",
            "nested_same_name_aliases_keep_distinct_types_and_origins",
            "branch_alias_names_do_not_hide_outer_writes_or_parameter_rebindings",
            "branch_alias_normalization_remains_transactional_on_computed_callers",
            "projected_same_name_aliases_preserve_reference_execution",
            "mixed_alias_leaves_preserve_exact_scalar_kinds",
            "rebound_origin_still_executes_the_old_alias_snapshot",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "private-value-capture-invariant-loop-alias-regressions",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_loop_aliases_tests.rs",
        required_patterns: &[
            "invariant_loop_alias_chains_keep_nested_scopes_and_exact_field_demand",
            "loop_aliases_keep_mutating_origins_and_rebound_local_snapshots_whole",
            "loop_alias_projection_preserves_whole_uses_and_computed_caller_transactions",
            "loop_alias_origins_require_unwritten_parameters_not_computed_locals",
            "loop_aliases_do_not_hide_reference_or_annotation_mismatches",
            "projected_loop_aliases_preserve_zero_trips_checked_work_and_reference_results",
            "loop_aliases_keep_preceding_record_versions_after_top_level_rebinding",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "private-value-capture-invariant-loop-alias-source",
        path: "tools/nuisc/tests/native_application_bridge/typed_alias_capture_fixture.rs",
        required_patterns: &[
            "pub fn loop_source()",
            "while i < limit",
            "let saved = input; let second = saved;",
            "relay(second.numerator) / second.denominator",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "branch-value-snapshot-before-forward-substitution",
        path: "tools/nuisc/src/lowering/if_lowering_chains.rs",
        required_patterns: &[
            "binding_rebound_in_tail(&name, &value, tail)",
            "dependencies.contains(name.as_str())",
            "crate::nir_walk::walk_child_exprs(expr",
            "lower_binding_if_chain(tail, state, &local_bindings, pure_helpers)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "private-value-capture-alias-shared-source-fixture",
        path: "tools/nuisc/tests/native_application_bridge/typed_alias_capture_fixture.rs",
        required_patterns: &[
            "include_str!(\"typed_sparse_captures.ns\")",
            "let saved = payload;",
            "let second: Payload = saved;",
            "return fallback.f63 / fallback.f1;",
            "pub fn rebound_source()",
            "return relay(second.f0) + saved.f0;",
            "pub fn scoped_source()",
            "const saved: Payload = payload;",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "private-value-capture-lexical-identity-authority",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_bindings.rs",
        required_patterns: &[
            "if !walk::supported(&function.body)",
            "reserved.insert(name.clone())",
            "rewrite(value, &visible)",
            "visible.entry(name.clone()).or_insert_with",
            "branches::fresh_name(\"__nuis_capture_local\", &mut reserved)",
            "pending.push((else_body, visible.clone(), true))",
            "pending.push((then_body, visible.clone(), true))",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "private-value-capture-lexical-identity-regressions",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_bindings_tests.rs",
        required_patterns: &[
            "sibling_aliases_and_later_bindings_have_independent_identities",
            "nested_and_loop_writes_keep_their_visible_binding_identity",
            "private_names_reserve_later_bindings_and_do_not_rename_fields_or_callees",
            "unsupported_expressions_leave_the_complete_candidate_unchanged",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "branch-value-snapshot-native-execution",
        path: "tools/nuisc/tests/control_flow_syntax_native/alias_snapshots.rs",
        required_patterns: &[
            "native_alias_snapshots_survive_origin_and_alias_rebindings",
            "native_snapshot_projection_retains_discarded_checked_rebindings",
            "Some(24)",
            "include_str!(\"alias_snapshots.ns\")",
            "assert_eq!(status.code(), Some(187))",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "branch-value-snapshot-native-source",
        path: "tools/nuisc/tests/control_flow_syntax_native/alias_snapshots.ns",
        required_patterns: &[
            "@noinline fn choose(state: State, flag: bool)",
            "@noinline fn rebound_alias(state: State, flag: bool)",
            "@noinline fn guard(state: State, flag: bool)",
            "@noinline fn binding(state: State, flag: bool)",
            "return relay(saved.left) + state.left;",
            "@noinline fn checked_snapshot(state: State, divisor: i64, flag: bool)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "private-value-capture-snapshot-identity-authority",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_snapshots.rs",
        required_patterns: &[
            "snapshot_candidates(function, layouts)",
            "entry.versionable &= !info.in_loop",
            "entry.scope == scope || info.returns",
            "entry.ty.as_ref() == ty",
            "entry.count > 0 && parameters.contains(name)",
            "pending.push((then_body, versions.clone()))",
            "scopes::collect(&function.body)",
            "control_values::supported_type(ty, layouts)",
            "reserved.insert(name.clone())",
            "versions.get(name)",
            "branches::fresh_name(\"__nuis_capture_snapshot\", &mut reserved)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "private-value-capture-snapshot-regressions",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_snapshots_tests.rs",
        required_patterns: &[
            "straight_line_origin_and_alias_rebindings_expose_old_field_demand",
            "self_rebinding_reads_previous_version_and_reserves_future_names",
            "snapshot_projection_keeps_nominal_subrecords_in_private_call_chains",
            "whole_old_records_and_computed_callers_keep_original_snapshots",
            "control_boundary_writes_prevent_all_versions_of_that_name",
            "stable_versions_remain_visible_to_nested_reads_without_changing_loop_carries",
            "mixed_rebinding_preserves_scalar_kinds_and_constructor_work",
            "snapshots_reject_untyped_reference_and_mismatched_versions",
            "discarded_rebound_constructor_keeps_checked_work_in_reference_execution",
            "record_rebinding_admission_preserves_type_and_scalar_boundaries",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "private-value-capture-scoped-snapshot-regressions",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/capture_snapshots_tests.rs",
        required_patterns: &[
            "branch_local_rebindings_project_old_alias_fields",
            "scoped_snapshot_versions_preserve_nested_reads_siblings_and_suffixes",
            "scoped_snapshot_writes_across_branches_and_loop_iterations_stay_unchanged",
            "scoped_snapshot_projection_is_transactional_for_whole_records_and_computed_callers",
            "scoped_snapshots_reject_untyped_reference_and_mismatched_versions",
            "discarded_scoped_rebound_constructor_keeps_selected_checked_work",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "private-value-capture-scoped-snapshot-source",
        path: "tools/nuisc/tests/native_application_bridge/typed_alias_capture_fixture.rs",
        required_patterns: &[
            "pub fn scoped_rebound_source()",
            "return relay(second.f0) + saved.f0;",
            "return second.f63 / second.f1 + saved.f0;",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "pure-value-record-rebinding-admission",
        path: "tools/nuisc/src/lowering/buffer_loop_outline/scalar_helpers.rs",
        required_patterns: &[
            "if let Some(previous) = locals.get(name)",
            "!matches!(stmt, NirStmt::Let { .. })",
            "previous != &inferred",
            "layouts.scalar(&inferred.name)",
            "declared.is_some_and(|ty| ty != &inferred)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "private-value-capture-sparse-guard-evidence",
        path: "tools/nuisc/tests/native_application_bridge/typed_helper_guards.rs",
        required_patterns: &[
            "typed_sparse_capture_guards_preserve_selected_failures_bits_and_entry_budgets",
            "check_guards(&source, 6, false)",
            "i64::MIN, -1, required, None",
            "required - 1, None",
            "probe_allocs",
            "probe_drops",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "guarded-typed-neutral-value-validation",
        path: "tools/nuisc/src/lowering/direct_calls/control_boundaries.rs",
        required_patterns: &[
            "is_neutral_guard_seed(ty, default, &state.struct_defs)",
            "nested_guard_zeros_require_exact_types_and_never_evaluate_work",
            "fields.iter().zip(&definition.fields)",
            "!seen.insert(name)",
        ],
    },
    DevTensorDriftCheckSpec {
        id: "guarded-i32-literal-constant-lowering",
        path: "tools/nuisc/src/lowering/core_exprs_scalars.rs",
        required_patterns: &[
            "if let NirExpr::Int(value) = value",
            "instruction: \"const_i32\".to_owned()",
            "(*value as i32).to_string()",
        ],
    },
];
