use crate::dev_tensor_drift::DevTensorDriftCheckSpec;

pub(crate) const DEV_TENSOR_RUNTIME_EXECUTION_DRIFT_CHECKS: &[DevTensorDriftCheckSpec] = &[
    DevTensorDriftCheckSpec {
            id: "run-artifact-entrypoint-protocol-regression",
            path: "tools/nuis/src/main_tests/artifact_runtime_run_artifact.rs",
            required_patterns: &[
                "run_artifact_prelaunch_kind",
                "run_artifact_prelaunch_status",
                "run_artifact_prelaunch_evidence_status",
                "nsld-host-entrypoint",
                "run_artifact_json_blocks_nsld_prelaunch_when_entrypoint_stub_is_missing",
                "run_artifact_json_blocks_nsld_prelaunch_when_entrypoint_protocol_is_missing",
                "host entrypoint stub is missing on disk",
                "nuis-nsld-host-entrypoint-v1",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "frontdoor-reference-doc",
            path: "docs/reference/nuis-frontdoor-surface-reference.md",
            required_patterns: &[
                "nsld_final_executable_output_boundary_status",
                "nsld_final_executable_output_materialization_status",
                "nsld_final_executable_output_execution_handoff_contract",
                "nsld_final_executable_output_execution_handoff_ready",
                "nsld_final_executable_output_execution_handoff_status",
                "nsld_final_executable_output_execution_handoff_target",
                "nsld_final_executable_output_execution_handoff_evidence_status",
                "nsld_final_executable_output_execution_handoff_first_blocker",
                "nsld_final_executable_output_execution_handoff_decision_code",
                "nsld_final_executable_output_payload_execution_trace_protocol",
                "nsld_final_executable_output_payload_execution_trace_available",
                "nsld_final_executable_output_payload_execution_trace_record_count",
                "nsld_final_executable_output_payload_execution_trace_ready_record_count",
                "nsld_final_executable_pipeline_execution_handoff_contract",
                "nsld_final_executable_pipeline_execution_handoff_ready",
                "nsld_final_executable_pipeline_execution_handoff_status",
                "nsld_final_executable_pipeline_execution_handoff_target",
                "nsld_final_executable_pipeline_execution_handoff_evidence_status",
                "nsld_final_executable_pipeline_execution_handoff_first_blocker",
                "nsld_final_executable_pipeline_execution_handoff_decision_code",
                "nsld_final_executable_output_recommended_next_action",
                "nsld_self_owned_image_status",
                "run_artifact_prelaunch_kind",
                "run_artifact_prelaunch_status",
                "run_artifact_prelaunch_evidence_status",
                "workflow_run_artifact_prelaunch_kind",
                "workflow_run_artifact_prelaunch_status",
                "workflow_run_artifact_prelaunch_evidence_status",
                "workflow_run_artifact_prelaunch_command",
                "workflow_run_artifact_prelaunch_reason",
                "workflow_launch_evidence_protocol",
                "workflow_launch_evidence_debugger_contract",
                "workflow_launch_evidence_host_runner_probe_status",
                "run_artifact_prelaunch_command",
                "run_artifact_prelaunch_runner_command_present",
                "run_artifact_prelaunch_entrypoint_present",
                "run_artifact_prelaunch_entrypoint_protocol",
                "run_artifact_prelaunch_entrypoint_protocol_valid",
                "host_runner_invoked",
                "host_runner_status",
                "host_runner_nsb_readable",
                "host_runner_nsb_payload_region_mapped",
                "host_runner_container_loader_handoff_status",
                "launch_evidence_protocol",
                "launch_evidence_debugger_contract",
                "launch_evidence_payload_execution_trace_protocol",
                "launch_evidence_payload_execution_trace_record_count",
                "launch_evidence_first_payload_status",
                "launch_evidence_first_payload_entry_symbol",
                "launch_evidence_first_payload_first_blocker",
                "launch_evidence_first_blocker",
                "artifact_closure_kind",
                "artifact_closure_status",
                "artifact_closure_evidence_status",
                "artifact_closure_command",
                "artifact_closure_runner_command_present",
                "artifact_closure_entrypoint_present",
                "artifact_closure_entrypoint_protocol",
                "artifact_closure_entrypoint_protocol_valid",
                "artifact_launch_evidence_protocol",
                "artifact_launch_evidence_debugger_contract",
                "artifact_launch_evidence_host_runner_probe_status",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "release-check-device-sample-handoff-mirror",
            path: "tools/nuis/src/release_check_command.rs",
            required_patterns: &[
                "collect_device_sample_handoff_mirror",
                "append_workflow_link_plan_json_fields",
                "release_check_device_sample_handoff",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "native-artifact-workflow-doc",
            path: "docs/reference/nuis-native-artifact-workflow.md",
            required_patterns: &[
                "nsld_final_executable_output_boundary_status",
                "nsld_final_executable_output_materialization_status",
                "nsld_final_executable_output_execution_handoff_contract",
                "nsld_final_executable_output_execution_handoff_ready",
                "nsld_final_executable_output_execution_handoff_status",
                "nsld_final_executable_output_execution_handoff_target",
                "nsld_final_executable_output_execution_handoff_evidence_status",
                "nsld_final_executable_output_execution_handoff_first_blocker",
                "nsld_final_executable_output_execution_handoff_decision_code",
                "nsld_final_executable_output_payload_execution_trace_protocol",
                "nsld_final_executable_output_payload_execution_trace_available",
                "nsld_final_executable_output_payload_execution_trace_record_count",
                "nsld_final_executable_output_payload_execution_trace_ready_record_count",
                "nsld_final_executable_pipeline_execution_handoff_contract",
                "nsld_final_executable_pipeline_execution_handoff_ready",
                "nsld_final_executable_pipeline_execution_handoff_status",
                "nsld_final_executable_pipeline_execution_handoff_target",
                "nsld_final_executable_pipeline_execution_handoff_evidence_status",
                "nsld_final_executable_pipeline_execution_handoff_first_blocker",
                "nsld_final_executable_pipeline_execution_handoff_decision_code",
                "nsld_final_executable_output_recommended_next_action",
                "nsld_self_owned_image_status",
                "run_artifact_prelaunch_kind",
                "run_artifact_prelaunch_status",
                "run_artifact_prelaunch_evidence_status",
                "workflow_run_artifact_prelaunch_kind",
                "workflow_run_artifact_prelaunch_status",
                "workflow_run_artifact_prelaunch_evidence_status",
                "workflow_run_artifact_prelaunch_command",
                "workflow_run_artifact_prelaunch_reason",
                "workflow_launch_evidence_protocol",
                "workflow_launch_evidence_debugger_contract",
                "workflow_launch_evidence_host_runner_probe_status",
                "workflow_nsdb_handoff_available",
                "workflow_nsdb_handoff_protocol",
                "workflow_nsdb_handoff_record_count",
                "link_plan_heterogeneous_backend_artifact_units",
                "link_plan_heterogeneous_backend_artifact_ready_units",
                "link_plan_heterogeneous_backend_families",
                "link_plan_heterogeneous_target_devices",
                "link_plan_heterogeneous_backend_artifact_first_unready",
                "run_artifact_prelaunch_command",
                "run_artifact_prelaunch_runner_command_present",
                "run_artifact_prelaunch_entrypoint_present",
                "run_artifact_prelaunch_entrypoint_protocol",
                "run_artifact_prelaunch_entrypoint_protocol_valid",
                "host_runner_invoked",
                "host_runner_status",
                "host_runner_nsb_readable",
                "host_runner_nsb_payload_region_mapped",
                "host_runner_container_loader_handoff_status",
                "launch_evidence_protocol",
                "launch_evidence_debugger_contract",
                "launch_evidence_payload_execution_trace_protocol",
                "launch_evidence_payload_execution_trace_record_count",
                "launch_evidence_first_payload_status",
                "launch_evidence_first_payload_entry_symbol",
                "launch_evidence_first_payload_first_blocker",
                "launch_evidence_first_blocker",
                "artifact_closure_kind",
                "artifact_closure_status",
                "artifact_closure_evidence_status",
                "artifact_closure_command",
                "artifact_closure_runner_command_present",
                "artifact_closure_entrypoint_present",
                "artifact_closure_entrypoint_protocol",
                "artifact_closure_entrypoint_protocol_valid",
                "artifact_launch_evidence_protocol",
                "artifact_launch_evidence_debugger_contract",
                "artifact_launch_evidence_host_runner_probe_status",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "std-filesystem-light-smoke",
            path: "tools/nuis/tests/std_filesystem_smoke.rs",
            required_patterns: &[
                "STD_TOOLING_LIGHT_SMOKE_PROJECTS",
                "std_tooling_light_project_smokes_build_doctor_and_run",
                "text_pipeline_demo",
                "io_runtime_demo",
                "stdin_runtime_demo",
                "filesystem_io_report_demo",
                "std_tooling_observable_cli_smoke_checks_reports_and_stdin",
                "run_binary_with_stdin",
                "run_binary_with_args",
                "host_stdin_read",
                "cli_wc_demo",
                "cli_pgm_invert_demo",
                "P2\\n2 2\\n15\\n15 11 6 7\\n",
                "cli_report_file_demo",
                "pixelmagic_report_file_demo",
                "std-preprocessed-pgm",
                "input_bytes: 20",
                "witsage_report_file_demo",
                "StdReportContracts.cli_report_file_status_total",
                "StdReportContracts.cli_report_file_validation_total",
                "PixelMagicContracts.filter_chain_total",
                "WitSageContracts.classifier_pipeline_total",
                "host_argv_count",
                "host_file_read",
                "host_file_write",
                "host_text_word_count",
                "bytes: 31",
                "words: 5",
                "runtime_materialization_policy",
                "host_stdout_write",
                "host_stderr_write",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "official-galaxy-hetero-smoke-entry",
            path: "tools/nuis/tests/official_galaxy_hetero_smoke.rs",
            required_patterns: &[
                "official_galaxy_hetero_projects_emit_shader_and_kernel_artifacts",
                "PixelMagicContracts.shader_pipeline_total",
                "WitSageContracts.kernel_pipeline_total",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "official-galaxy-hetero-smoke",
            path: "tools/nuis/tests/official_galaxy_hetero_smoke/build.rs",
            required_patterns: &[
                "nsld drive apply official galaxy hetero smoke",
                "whitelisted-artifact-mutation",
                "nsld-drive-safe-next-v1",
                "rerun-drive-to-refresh-next-action",
                "resolve-final-output-nsdb-replay",
                "nsld_final_executable_output_nsdb_replay_contract",
                "nsld_final_executable_output_nsdb_replay_first_blocker",
                "hetero_runtime_trace_device_sample_descriptor_count",
                "materialize_provider_samples",
                "provider-sample-materialized",
                "deterministic-provider-sample-artifact",
                "nuis-provider-runner-v1",
                "nuis-provider-runner-adapter-v1",
                "nuis-provider-runner-registry-v1",
                "builtin-nustar-provider-runner-registry",
                "provider_runner_real_device_capable",
                "host-simulated-provider-runner",
                "first_output_payload_comparison_contract",
                "first_output_payload_input_evidence_hash",
                "first_output_payload_native_output_kind",
                "first_output_payload_native_output_bytes",
                "pixel_format=gray8",
                "pixel_payload_path=nuis.pixelmagic.std-preprocessed.gray8.bin",
                "nuis-provider-buffer-descriptor-v1",
                "nuis-provider-kernel-descriptor-v1",
                "nuis-provider-model-asset-descriptor-v1",
                "nuis-provider-output-comparison-descriptor-v1",
                "nuis-provider-request-collection-v1",
                "nuis-provider-request-dependency-v1",
                "nuis-provider-input-binding-v1",
                "provider_request_count=5",
                "nuis-provider-request-adapter-binding-v1",
                "nuis-provider-edge-transport-v1",
                "glm:provider-edge:witsage.vector.add:output.features->witsage.vector.metal-bias:input.features",
                "provider-clock:request-3:completed",
                "provider-clock:request-4:dispatch-ready",
                "nuis-provider-edge-transport-receipt-v1",
                "nuis-provider-edge-staging-registry-v1",
                "provider.output.transfer.v1",
                "registered-available",
                "materialize_status",
                "consume_status",
                "release_status",
                "provider_request_2_dependency_0_producer_request_id=witsage.vector.affine",
                "registered-descriptors",
                "nuis-metal-gray8-provider-runner-v1",
                "provider_kernel_id=witsage.feature-grid.projection",
                "nuis-coreml-model-prediction-provider-runner-v1",
                "coreml-model-prediction-completed",
                "nuis-coreml-compute-plan-evidence-v1",
                "first_output_payload_native_compute_plan_supported_devices",
                "nuis-provider-output-collection-v1",
                "native_output_collection_hash",
                "native_output_1_request_id",
                "native_output_1_comparison_status",
                "native_output_2_request_id",
                "native_output_3_request_id",
                "native_output_4_request_id",
                "artifact_device_provider_sample_manifest_status",
                "replay-device-sample",
            ],
        },
    DevTensorDriftCheckSpec {
            id: "nsdb-metal-provider-runner",
            path: "tools/nsdb/src/provider_runner_metal.rs",
            required_patterns: &[
                "nuis-metal-gray8-provider-runner-v1",
                "metal-command-buffer-completed",
                "execute_gray8_invert",
                "output_hex",
                "Metal provider runner",
                "remove_file",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-metal-gray8-provider-runner-source",
            path: "tools/nsdb/provider-runners/metal_gray8_invert.m",
            required_patterns: &[
                "nuis_gray8_invert",
                "newBufferWithBytes",
                "dispatchThreads",
                "waitUntilCompleted",
                "nuis-metal-gray8-provider-runner-v1",
                "output_hex",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-provider-adapter-binding",
            path: "tools/nsdb/src/provider_adapter_binding.rs",
            required_patterns: &[
                "nuis-provider-request-adapter-binding-v1",
                "provider_family",
                "execution_requirement",
                "real-device",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-provider-edge-transport",
            path: "tools/nsdb/src/provider_edge_transport.rs",
            required_patterns: &[
                "nuis-provider-edge-transport-v1",
                "glm:provider-edge:",
                "host-visible-owned-file",
                "producer_clock_evidence",
                "consumer_clock_evidence",
                "validate_dependency_transport",
                "nuis-provider-edge-transport-receipt-v1",
                "ProviderEdgeTransportReceipt",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-provider-edge-transport-receipt-output",
            path: "tools/nsdb/src/provider_transport_receipt_payload.rs",
            required_patterns: &[
                "provider_edge_transport_receipt_contract",
                "provider_edge_transport_receipt_count",
                "materialize_payload_hash",
                "consume_payload_hash",
                "release_payload_hash",
                "provider_edge_transport_receipt_collection_hash",
                "staging_registry_contract",
                "staging_adapter_id",
                "staging_adapter_capability_status",
                "carrier_input_contract",
                "carrier_input_kind",
                "carrier_input_handle",
                "carrier_channel_registry_contract",
                "carrier_channel_registry_source",
                "carrier_channel_adapter_id",
                "carrier_channel_adapter_capability_status",
                "carrier_channel_contract",
                "carrier_channel_mode",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-provider-output-carrier-evidence",
            path: "tools/nsdb/src/provider_native_output_payload.rs",
            required_patterns: &[
                "push_native_output_summary",
                "carrier_registry_contract",
                "carrier_registry_source",
                "carrier_adapter_id",
                "carrier_mode",
                "output_residency_contract",
                "output_residency_kind",
                "output_transfer_scope",
                "output_observation_mode",
                "output_device_retention_status",
                "output.output_carrier_adapter_id",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-provider-edge-staging-registry",
            path: "tools/nsdb/src/provider_edge_staging_registry.rs",
            required_patterns: &[
                "nuis-provider-edge-staging-registry-v1",
                "builtin-provider-edge-staging-registry",
                "host.visible.owned-file.v1",
                "memory.owned-bytes.v1",
                "select_provider_edge_staging_adapter",
                "materialize_provider_edge_carrier",
                "consume_provider_edge_carrier",
                "release_provider_edge_carrier",
                "cleanup_provider_edge_carrier",
                "provider.output.transfer.v1",
                "provider_output_transfer_staging_adapter",
                "auto",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-provider-carrier-input-abi",
            path: "tools/nsdb/src/provider_carrier_input.rs",
            required_patterns: &[
                "nuis-provider-carrier-input-v1",
                "Path",
                "OpaqueBytes",
                "opaque-bytes",
                "handle",
                "bytes",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-provider-carrier-channel",
            path: "tools/nsdb/src/provider_carrier_channel.rs",
            required_patterns: &[
                "nuis-provider-carrier-channel-v1",
                "NUISPCV1",
                "frame_count",
                "byte_length",
                "fnv1a64",
                "to_le_bytes",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-provider-carrier-channel-registry",
            path: "tools/nsdb/src/provider_carrier_channel_registry.rs",
            required_patterns: &[
                "nuis-provider-carrier-channel-registry-v1",
                "builtin-provider-carrier-channel-registry",
                "inherited.fd.v1",
                "registered-unavailable",
                "framed.stdin.v1",
                "registered-available",
                "select_provider_carrier_channel_adapter",
                "provider_carrier_channel_capability",
                "encode_provider_carrier_channel",
                "prepare_provider_carrier_channel",
                "PreparedProviderCarrierChannel",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-provider-carrier-channel-unix",
            path: "tools/nsdb/src/provider_carrier_channel_unix.rs",
            required_patterns: &[
                "InheritedFdCarrier",
                "FD_CLOEXEC",
                "pre_exec",
                "create_unlinked_carrier_file",
                "frame_argument",
                "packet_len",
                "packet_hash",
                "NUISPFD1",
                "getpagesize",
                "align_up",
                "new_writable_single_frame",
                "set_len",
                "system_page_size",
                "output_descriptor",
                "verify_written_output",
                "MappedInheritedFdFrame",
                "mmap",
                "packet_bytes",
                "try_clone",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-provider-output-carrier-registry",
            path: "tools/nsdb/src/provider_output_carrier_registry.rs",
            required_patterns: &[
                "nuis-provider-output-carrier-registry-v1",
                "nuis-provider-output-residency-v1",
                "builtin-provider-output-carrier-registry",
                "inherited.fd.output.v1",
                "hex.stdout.output.v1",
                "select_provider_output_carrier_adapter",
                "prepare_provider_output_carrier",
                "ProviderOutputPayload",
                "InheritedFd(MappedInheritedFdFrame)",
                "as_bytes",
                "host-visible-file",
                "cross-process-static",
                "mapped-on-demand",
                "device_retention_status",
                "output_channel",
                "output_hash",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-provider-output-carrier-unix",
            path: "tools/nsdb/src/provider_output_carrier_unix.rs",
            required_patterns: &[
                "InheritedFdOutputCarrier",
                "NUIS_PROVIDER_OUTPUT_FD",
                "new_writable_single_frame",
                "output_descriptor",
                "verify_written_output",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-provider-output-carrier-transfer",
            path: "tools/nsdb/src/provider_prepared_input.rs",
            required_patterns: &[
                "CompletedProviderOutputKey",
                "direct_channel",
                "try_clone_transferable",
                "provider_output_transfer_staging_adapter",
                "inherited-frame",
                "transferred-output:",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-provider-session-lease",
            path: "tools/nsdb/src/provider_session_registry.rs",
            required_patterns: &[
                "nuis-provider-session-registry-v1",
                "nuis-provider-session-lease-v1",
                "nuis-provider-output-handle-v1",
                "logical.request-process.v1",
                "graph-open,request-begin,request-complete,graph-close",
                "graph-lease-only",
                "glm:provider-session-output:",
                "ProviderSessionOutputHandle",
                "begin_request_with_output_roles",
                "output_handles",
                "complete_request",
                "close",
                "request_allocates_ordered_role_bound_output_handles",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-provider-session-execution",
            path: "tools/nsdb/src/provider_sample_execute.rs",
            required_patterns: &[
                "select_provider_session_adapter",
                "ProviderSessionLease::open",
                "begin_request_with_output_roles",
                "complete_request",
                "bind_session_output",
                "released-at-graph-close",
                "graph_output_close",
                "graph_output_release_count",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-provider-session-summary",
            path: "tools/nsdb/src/provider_session_summary.rs",
            required_patterns: &[
                "bind_session_output",
                "output_handle_roles",
                "output_handle_ids",
                "output_handle_ownership_tokens",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-provider-graph-output-ownership",
            path: "tools/nsdb/src/provider_graph_output.rs",
            required_patterns: &[
                "nuis-provider-graph-output-ownership-v1",
                "CompletedProviderOutputKey",
                "completed_additional_worker_outputs",
                "binding.byte_length",
                "payload_hash_valid",
                "released_output_count",
                "released_output_roles",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-provider-graph-output-regression",
            path: "tools/nsdb/src/provider_graph_output_tests.rs",
            required_patterns: &[
                "graph_routes_distinct_outputs_to_consumers_and_releases_all_at_close",
                "worker_additional_output_becomes_registered_graph_output",
                "buffer.primary",
                "buffer.audit",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-provider-graph-output-evidence",
            path: "tools/nsdb/src/provider_native_output_payload.rs",
            required_patterns: &[
                "graph_output_ownership_contract",
                "graph_output_release_count",
                "graph_output_release_roles",
                "output_binding_contract",
                "output_binding_count",
                "output_binding_element_types",
                "output_binding_byte_lengths",
                "comparison_collection_contract",
                "comparison_collection_count",
                "comparison_collection_statuses",
                "comparison_collection_mismatch_counts",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "std-provider-worker-lifecycle-contract",
            path: "stdlib/std/lib/provider_worker_contracts.ns",
            required_patterns: &[
                "StdProviderWorkerContracts",
                "ProviderWorkerState",
                "request_valid",
                "complete_request",
                "closed_cleanly",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "std-provider-worker-native-runtime-recipe",
            path: "stdlib/std/provider_worker_runtime_recipe.ns",
            required_patterns: &[
                "StdProviderWorkerContracts",
                "ProviderWorkerRuntimeSummary",
                "while sequence < request_count",
                "rejected_sequence",
                "closed_cleanly",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "std-provider-worker-dispatch-contract",
            path: "stdlib/std/lib/provider_worker_dispatch_contracts.ns",
            required_patterns: &[
                "StdProviderWorkerDispatchContracts",
                "ProviderDispatchBinding",
                "ProviderWorkerRequest",
                "descriptor_table_handle",
                "capability_hash",
                "dispatch_status",
                "process_request",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "std-provider-worker-dispatch-native-recipe",
            path: "stdlib/std/provider_worker_dispatch_recipe.ns",
            required_patterns: &[
                "data_handle_table",
                "provider_request_ingress",
                "std_provider_worker_dispatch_ready",
                "ProviderDispatchBinding",
                "ProviderWorkerRequest",
                "request(103, 2, 20, 503, 1, 9999)",
                "closed_cleanly",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "provider-request-ingress-frontend-regression",
            path: "tools/nuisc/tests/provider_request_ingress_compile.rs",
            required_patterns: &[
                "provider_request_ingress(101, 501, 2, 20, 2020)",
                "official.data",
                "data.provider_request_ingress",
                "Nuis-owned provider request ingress",
                "expects 5 legacy args or 8 capsule args",
                "lowers_capsule_provider_request_ingress_with_eight_dependencies",
                "Nuis-owned provider capsule ingress",
                "nuis_provider_worker_request_v1",
                "nuis_fn_worker_request",
                "unsupported arity 5",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "provider-worker-parameterized-export-shim",
            path: "tools/nuisc/src/aot_c_shim_helpers.rs",
            required_patterns: &[
                "ExportedEntry",
                "collect_exported_entries",
                "nuis_fn_",
                "int64_t arg",
                "render_exported_entry_wrapper",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-provider-worker-ingress-adapter",
            path: "tools/nsdb/src/provider_worker_ingress.rs",
            required_patterns: &[
                "nuis-provider-worker-ingress-adapter-v1",
                "map_verified_unix_request_to_ingress",
                "ProviderWorkerIngressFields",
                "ProviderWorkerIngressEntrypoint",
                "invoke_provider_worker_ingress",
                "capsule_token",
                "input_role_count",
                "output_role_count",
                "semantic_descriptor_count",
                "control.adapter",
                "control_descriptor_is_not_a_semantic_capsule_input",
                "verified_unix_request_maps_to_eight_nuis_capsule_ingress_scalars",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "nsdb-provider-worker-control-carrier",
            path: "tools/nsdb/src/provider_worker_control.rs",
            required_patterns: &[
                "PROVIDER_WORKER_ADAPTER_CONTROL_CARRIER_CONTRACT",
                "control.adapter",
                "ProviderWorkerControlCarrier",
                "create_control_file",
                "remove_file",
                "control_carrier_is_unlinked_and_hash_bound",
            ],
        },
        DevTensorDriftCheckSpec {
            id: "provider-request-ingress-data-nustar-contract",
            path: "crates/yir-core/src/data_mod_describe.rs",
            required_patterns: &[
                "provider_request_ingress",
                "describe_provider_request_ingress",
                "5 legacy or 8 capsule arguments",
                "InstructionSemantics::effect",
            ],
        },
];
