name = "shader_vulkan_add_provider_demo"
version = "0.1.0"
entry = "main.ns"
packaging_mode = "nuis-self-contained-image"
artifact_provider_metadata = [
  "official.shader:provider-sample=vulkan-add-u32"
]
modules = ["main.ns", "surface_shader.ns"]
abi = [
  "cpu=cpu.x86_64.sysv64",
  "shader=shader.vulkan.spv1_6",
]
