use std::collections::BTreeMap;

use nuis_semantics::model::{AstExpr, NirExpr, NirStructDef, NirTypeRef};

use super::super::{lower_expr, named_type, FunctionSignature, ModuleConstValue};

#[allow(clippy::too_many_arguments)]
pub(super) fn lower_nova_resource_state_builtin_call(
    callee: &str,
    args: &[AstExpr],
    current_domain: &str,
    _current_function_is_async: bool,
    bindings: &BTreeMap<String, NirTypeRef>,
    _module_consts: &BTreeMap<String, ModuleConstValue>,
    signatures: &BTreeMap<String, FunctionSignature>,
    struct_table: &BTreeMap<String, NirStructDef>,
) -> Result<Option<NirExpr>, String> {
    let expr = match callee {
        "nova_visibility_state" => build_five_field_state(
            args,
            "nova_visibility_state(...) expects 1 arg",
            "NovaVisibilityPacket",
            "NovaVisibilityState",
            [
                "cluster_slot",
                "visible_nodes",
                "occlusion_mode",
                "distance_band",
                "mask",
            ],
            current_domain,
            bindings,
            signatures,
            struct_table,
        )?,
        "nova_cull_state" => build_five_field_state(
            args,
            "nova_cull_state(...) expects 1 arg",
            "NovaCullPacket",
            "NovaCullState",
            [
                "cluster_slot",
                "kept_nodes",
                "cull_mode",
                "lod_band",
                "mask",
            ],
            current_domain,
            bindings,
            signatures,
            struct_table,
        )?,
        "nova_lod_state" => build_five_field_state(
            args,
            "nova_lod_state(...) expects 1 arg",
            "NovaLodPacket",
            "NovaLodState",
            [
                "cluster_slot",
                "level_count",
                "active_level",
                "switch_distance",
                "bias",
            ],
            current_domain,
            bindings,
            signatures,
            struct_table,
        )?,
        "nova_streaming_state" => build_five_field_state(
            args,
            "nova_streaming_state(...) expects 1 arg",
            "NovaStreamingPacket",
            "NovaStreamingState",
            [
                "cluster_slot",
                "resident_levels",
                "prefetch_mode",
                "evict_budget",
                "channel",
            ],
            current_domain,
            bindings,
            signatures,
            struct_table,
        )?,
        "nova_residency_state" => build_five_field_state(
            args,
            "nova_residency_state(...) expects 1 arg",
            "NovaResidencyPacket",
            "NovaResidencyState",
            [
                "cluster_slot",
                "committed_levels",
                "residency_mode",
                "spill_budget",
                "residency_mask",
            ],
            current_domain,
            bindings,
            signatures,
            struct_table,
        )?,
        "nova_eviction_state" => build_five_field_state(
            args,
            "nova_eviction_state(...) expects 1 arg",
            "NovaEvictionPacket",
            "NovaEvictionState",
            [
                "cluster_slot",
                "evicted_levels",
                "eviction_mode",
                "reclaim_budget",
                "eviction_mask",
            ],
            current_domain,
            bindings,
            signatures,
            struct_table,
        )?,
        "nova_prefetch_state" => build_five_field_state(
            args,
            "nova_prefetch_state(...) expects 1 arg",
            "NovaPrefetchPacket",
            "NovaPrefetchState",
            [
                "cluster_slot",
                "requested_levels",
                "prefetch_window",
                "warm_budget",
                "prefetch_mask",
            ],
            current_domain,
            bindings,
            signatures,
            struct_table,
        )?,
        "nova_budget_state" => build_five_field_state(
            args,
            "nova_budget_state(...) expects 1 arg",
            "NovaBudgetPacket",
            "NovaBudgetState",
            [
                "cluster_slot",
                "total_budget",
                "used_budget",
                "headroom",
                "budget_policy",
            ],
            current_domain,
            bindings,
            signatures,
            struct_table,
        )?,
        "nova_pressure_state" => build_five_field_state(
            args,
            "nova_pressure_state(...) expects 1 arg",
            "NovaPressurePacket",
            "NovaPressureState",
            [
                "cluster_slot",
                "pressure_level",
                "saturation",
                "throttled",
                "pressure_mask",
            ],
            current_domain,
            bindings,
            signatures,
            struct_table,
        )?,
        "nova_thermal_state" => build_five_field_state(
            args,
            "nova_thermal_state(...) expects 1 arg",
            "NovaThermalPacket",
            "NovaThermalState",
            [
                "cluster_slot",
                "thermal_level",
                "cooling_mode",
                "throttled",
                "thermal_mask",
            ],
            current_domain,
            bindings,
            signatures,
            struct_table,
        )?,
        "nova_power_state" => build_five_field_state(
            args,
            "nova_power_state(...) expects 1 arg",
            "NovaPowerPacket",
            "NovaPowerState",
            [
                "cluster_slot",
                "power_level",
                "source_mode",
                "capped",
                "power_mask",
            ],
            current_domain,
            bindings,
            signatures,
            struct_table,
        )?,
        "nova_latency_state" => build_five_field_state(
            args,
            "nova_latency_state(...) expects 1 arg",
            "NovaLatencyPacket",
            "NovaLatencyState",
            [
                "cluster_slot",
                "frame_latency",
                "input_latency",
                "jitter",
                "latency_mask",
            ],
            current_domain,
            bindings,
            signatures,
            struct_table,
        )?,
        "nova_frame_pacing_state" => build_five_field_state(
            args,
            "nova_frame_pacing_state(...) expects 1 arg",
            "NovaFramePacingPacket",
            "NovaFramePacingState",
            [
                "cluster_slot",
                "cadence",
                "variance",
                "vsync_mode",
                "pacing_mask",
            ],
            current_domain,
            bindings,
            signatures,
            struct_table,
        )?,
        "nova_jank_state" => build_five_field_state(
            args,
            "nova_jank_state(...) expects 1 arg",
            "NovaJankPacket",
            "NovaJankState",
            [
                "cluster_slot",
                "spikes",
                "severity",
                "recovery",
                "jank_mask",
            ],
            current_domain,
            bindings,
            signatures,
            struct_table,
        )?,
        "nova_frame_variance_state" => build_five_field_state(
            args,
            "nova_frame_variance_state(...) expects 1 arg",
            "NovaFrameVariancePacket",
            "NovaFrameVarianceState",
            [
                "cluster_slot",
                "frame_variance",
                "input_variance",
                "burst_mode",
                "variance_mask",
            ],
            current_domain,
            bindings,
            signatures,
            struct_table,
        )?,
        _ => return Ok(None),
    };
    Ok(Some(expr))
}

fn build_five_field_state(
    args: &[AstExpr],
    arg_error: &str,
    packet_type: &str,
    state_type: &str,
    fields: [&str; 5],
    current_domain: &str,
    bindings: &BTreeMap<String, NirTypeRef>,
    signatures: &BTreeMap<String, FunctionSignature>,
    struct_table: &BTreeMap<String, NirStructDef>,
) -> Result<NirExpr, String> {
    let [packet] = args else {
        return Err(arg_error.to_owned());
    };
    let packet = lower_expr(
        packet,
        current_domain,
        bindings,
        signatures,
        struct_table,
        Some(&named_type(packet_type)),
    )?;
    Ok(NirExpr::StructLiteral {
        type_name: state_type.to_owned(),
        fields: vec![
            (fields[0].to_owned(), field(packet.clone(), fields[0])),
            (fields[1].to_owned(), field(packet.clone(), fields[1])),
            (fields[2].to_owned(), field(packet.clone(), fields[2])),
            (fields[3].to_owned(), field(packet.clone(), fields[3])),
            (fields[4].to_owned(), field(packet, fields[4])),
        ],
    })
}

fn field(base: NirExpr, field: &str) -> NirExpr {
    NirExpr::FieldAccess {
        base: Box::new(base),
        field: field.to_owned(),
    }
}
