use super::packet_helpers::{scalar_to_color_key, scalar_to_f32};
use super::BallPacket;
use yir_core::Value;

pub(crate) fn parse_ball_packet_tuple(items: &[Value], op: &str) -> Result<BallPacket, String> {
    let color_key = scalar_to_color_key(&items[0], op)?;
    let speed = scalar_to_f32(&items[1], op)?;
    let radius_scale = match items.get(2) {
        Some(value) => scalar_to_f32(value, op)?,
        None => 1.0,
    };
    Ok(BallPacket {
        color_key,
        speed,
        radius_scale,
        color_min: 0,
        color_max: 127,
        color_step: 4,
        color_disabled: 0,
        speed_min: 0,
        speed_max: 63,
        speed_step: 2,
        speed_disabled: 0,
        radius_min: 0,
        radius_max: 127,
        radius_step: 3,
        radius_disabled: 0,
        accent: color_key,
        surface: (radius_scale * 8.0).round() as i64,
        panel_mode: if speed.round() as i64 % 2 == 0 { 0 } else { 1 },
        contrast: speed.round() as i64,
        surface_density: speed.round() as i64,
        surface_elevation: (radius_scale * 16.0).round() as i64,
        surface_grid: color_key.rem_euclid(3),
        surface_sheen: color_key,
        viewport_x: color_key.rem_euclid(4),
        viewport_y: speed.round() as i64 % 3,
        viewport_width: 48,
        viewport_height: 18,
        layer_order: 1,
        layer_blend: speed.round() as i64 % 3,
        layer_visibility: 1,
        layer_clip: (radius_scale * 8.0).round() as i64,
        scene_root_count: 7,
        scene_active_camera: color_key.rem_euclid(3),
        scene_light_count: 3,
        scene_animation_phase: speed.round() as i64 % 4,
        camera_kind: speed.round() as i64 % 3,
        camera_focus: color_key.rem_euclid(6),
        camera_zoom: speed.round() as i64,
        camera_orbit: (radius_scale * 12.0).round() as i64,
        material_shader_kind: speed.round() as i64 % 3,
        material_albedo: color_key,
        material_roughness: speed.round() as i64,
        material_emissive: (radius_scale * 24.0).round() as i64,
        light_kind: speed.round() as i64 % 3,
        light_intensity: speed.round() as i64,
        light_range: (radius_scale * 18.0).round() as i64,
        light_reactive: color_key,
        mesh_primitive: speed.round() as i64 % 3,
        mesh_vertex_count: (speed.round() as i64).max(3),
        mesh_index_count: (radius_scale * 18.0).round() as i64,
        mesh_skinning: color_key,
        transform_translate: speed.round() as i64,
        transform_rotate: speed.round() as i64 % 4,
        transform_scale: (radius_scale * 16.0).round() as i64,
        transform_pivot: color_key.rem_euclid(6),
        node_id: color_key.rem_euclid(8),
        node_parent_id: speed.round() as i64 % 4,
        node_flags: color_key,
        node_depth: 2,
        scene_link_node_slot: color_key.rem_euclid(8),
        scene_link_transform_slot: speed.round() as i64,
        scene_link_mesh_slot: (radius_scale * 18.0).round() as i64,
        scene_link_material_slot: color_key,
        scene_link_light_slot: speed.round() as i64 % 3,
        scene_link_layer_slot: 1,
        instance_node_slot: color_key.rem_euclid(8),
        instance_count: 3,
        instance_stride: color_key.rem_euclid(5) + 2,
        instance_phase: speed.round() as i64,
        instance_material_slot: color_key,
        instance_light_slot: speed.round() as i64 % 3,
        scene_graph_root_slot: color_key.rem_euclid(8),
        scene_graph_node_count: 6,
        scene_graph_link_count: 3,
        scene_graph_instance_count: 3,
        scene_graph_active_layer: 1,
        scene_node_slot: color_key.rem_euclid(8),
        scene_node_first_child_slot: speed.round() as i64,
        scene_node_sibling_slot: (radius_scale * 18.0).round() as i64,
        scene_node_instance_slot: 3,
        scene_node_visibility: 1,
        instance_group_root_slot: 3,
        instance_group_count: 4,
        instance_group_visible_count: 3,
        instance_group_phase_bias: speed.round() as i64,
        instance_group_material_slot: color_key,
        scene_cluster_root_slot: color_key.rem_euclid(8),
        scene_cluster_node_budget: 6,
        scene_cluster_instance_group_slot: 3,
        scene_cluster_material_slot: color_key,
        scene_cluster_layer_slot: 1,
        visibility_cluster_slot: 3,
        visibility_visible_nodes: 5,
        visibility_occlusion_mode: 1,
        visibility_distance_band: speed.round() as i64 % 4,
        visibility_mask: 7,
        cull_cluster_slot: 3,
        cull_kept_nodes: 4,
        cull_mode: speed.round() as i64 % 2,
        cull_lod_band: speed.round() as i64 % 4,
        cull_mask: 7,
        lod_cluster_slot: 3,
        lod_level_count: 4,
        lod_active_level: speed.round() as i64 % 3,
        lod_switch_distance: (radius_scale * 24.0).round() as i64,
        lod_bias: color_key,
        streaming_cluster_slot: 3,
        streaming_resident_levels: 2,
        streaming_prefetch_mode: speed.round() as i64 % 2,
        streaming_evict_budget: (radius_scale * 16.0).round() as i64,
        streaming_channel: color_key,
        residency_cluster_slot: 3,
        residency_committed_levels: 2,
        residency_mode: speed.round() as i64 % 2,
        residency_spill_budget: (radius_scale * 24.0).round() as i64,
        residency_mask: 7,
        eviction_cluster_slot: 3,
        eviction_levels: speed.round() as i64 % 2,
        eviction_mode: speed.round() as i64 % 2,
        eviction_reclaim_budget: (radius_scale * 12.0).round() as i64,
        eviction_mask: 6,
        prefetch_cluster_slot: 3,
        prefetch_requested_levels: 2,
        prefetch_window: speed.round() as i64 % 2,
        prefetch_warm_budget: (radius_scale * 10.0).round() as i64,
        prefetch_mask: 5,
        budget_cluster_slot: 3,
        budget_total: 12,
        budget_used: (radius_scale * 8.0).round() as i64,
        budget_headroom: 5,
        budget_policy: speed.round() as i64 % 2,
        pressure_cluster_slot: 3,
        pressure_level: 2,
        pressure_saturation: (radius_scale * 10.0).round() as i64,
        pressure_throttled: speed.round() as i64 % 2,
        pressure_mask: 6,
        thermal_cluster_slot: 3,
        thermal_level: 2,
        thermal_cooling_mode: speed.round() as i64 % 2,
        thermal_throttled: speed.round() as i64 % 2,
        thermal_mask: 6,
        power_cluster_slot: 3,
        power_level: 2,
        power_source_mode: speed.round() as i64 % 2,
        power_capped: speed.round() as i64 % 2,
        power_mask: 6,
        latency_cluster_slot: 3,
        latency_frame: 4,
        latency_input: 2,
        latency_jitter: speed.round() as i64 % 2,
        latency_mask: 7,
        frame_pacing_cluster_slot: 3,
        frame_pacing_cadence: 4,
        frame_pacing_variance: speed.round() as i64 % 2,
        frame_pacing_vsync_mode: speed.round() as i64 % 2,
        frame_pacing_mask: 7,
        frame_variance_cluster_slot: 3,
        frame_variance_frame: 2,
        frame_variance_input: speed.round() as i64 % 2,
        frame_variance_burst: 4,
        frame_variance_mask: 7,
        jank_cluster_slot: 3,
        jank_spikes: 1 + speed.round() as i64 % 2,
        jank_severity: speed.round() as i64 % 3,
        jank_recovery: 4,
        jank_mask: 7,
        pass_stage: speed.round() as i64 % 3,
        pass_clear_mode: color_key,
        pass_sample_count: 4,
        pass_debug_view: color_key.rem_euclid(6),
        frame_index: speed.round() as i64,
        frame_present_mode: color_key.rem_euclid(3),
        frame_sync_interval: 1,
        frame_exposure: (radius_scale * 24.0).round() as i64,
        target_kind: color_key.rem_euclid(3),
        target_width: 48,
        target_height: 18,
        target_multisample: color_key,
        frame_graph_passes: 2,
        frame_graph_targets: 1,
        frame_graph_present_stage: speed.round() as i64 % 3,
        frame_graph_debug_overlay: color_key.rem_euclid(6),
        attachment_slot: 0,
        attachment_format_kind: color_key,
        attachment_load_op: speed.round() as i64 % 3,
        attachment_store_op: 1,
        pass_chain_stages: 2,
        pass_chain_fanout: 1,
        pass_chain_resolve_stage: speed.round() as i64 % 3,
        pass_chain_barrier_mode: color_key,
        barrier_scope: 1,
        barrier_source_stage: speed.round() as i64 % 3,
        barrier_target_stage: 2,
        barrier_flush_mode: color_key,
        resource_buffers: 2,
        resource_textures: 1,
        resource_samplers: 1,
        resource_residency: color_key,
        schedule_lanes: 2,
        schedule_queue_depth: 4,
        schedule_async_budget: (radius_scale * 24.0).round() as i64,
        schedule_tick_mode: speed.round() as i64 % 3,
        submission_batches: 2,
        submission_fences: 1,
        submission_signal_mode: speed.round() as i64 % 3,
        submission_present_hint: color_key,
        queue_kind: speed.round() as i64 % 3,
        queue_priority: 2,
        queue_budget: (radius_scale * 24.0).round() as i64,
        queue_ownership: color_key,
        semaphore_wait_count: 1,
        semaphore_signal_count: 2,
        semaphore_timeline_mode: speed.round() as i64 % 3,
        semaphore_scope: color_key,
        timeline_value: (radius_scale * 24.0).round() as i64,
        timeline_step: 1,
        timeline_epoch: 0,
        timeline_domain: color_key,
        fence_signaled: if speed.round() as i64 % 2 == 0 { 0 } else { 1 },
        fence_epoch: 0,
        fence_scope: color_key,
        fence_recycle_mode: 1,
        signal_kind: speed.round() as i64 % 3,
        signal_phase: 2,
        signal_fanout: 3,
        signal_ack_mode: color_key,
        event_kind: speed.round() as i64 % 3,
        event_route: 2,
        event_priority: 3,
        event_payload_mode: color_key,
        dispatch_queue_kind: speed.round() as i64 % 3,
        dispatch_lane: 2,
        dispatch_batch: 3,
        dispatch_completion_mode: color_key,
        feedback_status: if speed.round() as i64 % 2 == 0 { 0 } else { 1 },
        feedback_latency: speed.round() as i64,
        feedback_retries: radius_scale.round() as i64 % 4,
        feedback_channel: color_key,
        intent_kind: speed.round() as i64 % 3,
        intent_target: color_key.rem_euclid(6),
        intent_urgency: speed.round() as i64,
        intent_policy: color_key,
        reaction_kind: speed.round() as i64 % 3,
        reaction_result_slot: color_key.rem_euclid(6),
        reaction_stability: radius_scale.round() as i64 % 4,
        reaction_echo_mode: color_key,
        outcome_kind: speed.round() as i64 % 3,
        outcome_final_slot: color_key.rem_euclid(6),
        outcome_confidence: speed.round() as i64,
        outcome_settle_mode: color_key,
        resolution_kind: speed.round() as i64 % 3,
        resolution_commit_slot: color_key.rem_euclid(6),
        resolution_convergence: radius_scale.round() as i64 % 4,
        resolution_policy_mode: color_key,
        commit_kind: speed.round() as i64 % 3,
        commit_applied_slot: color_key.rem_euclid(6),
        commit_durability: speed.round() as i64,
        commit_commit_mode: color_key,
        snapshot_kind: speed.round() as i64 % 3,
        snapshot_source_slot: color_key.rem_euclid(6),
        snapshot_retention: radius_scale.round() as i64 % 4,
        snapshot_replay_mode: color_key,
        checkpoint_kind: speed.round() as i64 % 3,
        checkpoint_anchor_slot: color_key.rem_euclid(6),
        checkpoint_rollback_depth: speed.round() as i64,
        checkpoint_resume_mode: color_key,
        toggle_state: if speed.round() as i64 % 2 == 0 { 0 } else { 1 },
        focus_index: color_key.rem_euclid(3),
        progress_value: speed.round() as i64,
        progress_max: 63,
        meter_value: (radius_scale * 96.0).round() as i64,
        meter_max: 127,
        button_state: if speed.round() as i64 % 2 == 0 { 0 } else { 1 },
        button_intent: color_key.rem_euclid(3),
        header_title_mode: color_key.rem_euclid(2),
        toggle_disabled: radius_scale.round() as i64 % 2,
        text_caret: color_key.rem_euclid(6),
        text_echo: color_key,
        text_placeholder: radius_scale.round() as i64,
        text_read_only: 0,
        text_dirty: 0,
        select_index: color_key.rem_euclid(3),
        select_options: 3,
        select_multiple: 0,
        select_committed: 1,
        checkbox_checked: color_key.rem_euclid(2),
        checkbox_disabled: 0,
        radio_selected: color_key.rem_euclid(4),
        radio_options: 4,
        radio_disabled: 0,
        textarea_lines: 3,
        textarea_scroll: speed.round() as i64,
        textarea_placeholder: radius_scale.round() as i64,
        textarea_read_only: 0,
        textarea_dirty: 0,
        tabs_active: color_key.rem_euclid(4),
        tabs_count: 4,
        tabs_compact: 0,
        list_selected: color_key.rem_euclid(5),
        list_items: 5,
        list_dense: 0,
        table_rows: 4,
        table_cols: 3,
        table_selected_row: color_key.rem_euclid(4),
        table_zebra: 1,
        tree_selected: color_key.rem_euclid(6),
        tree_nodes: 6,
        tree_expanded: speed.round() as i64 % 2,
        inspector_selected: color_key.rem_euclid(4),
        inspector_fields: 4,
        inspector_pinned: speed.round() as i64 % 2,
        outline_selected: color_key.rem_euclid(6),
        outline_items: 6,
        outline_collapsed: speed.round() as i64 % 2,
    })
}
